### ISSUE TITLE
Import {SelectItem} from '@ui-kitten/components'

### ISSUE THREAD

**Issue by niloufarMakhzani** [akveo/react-native-ui-kitten#1000]
I want to use Select from '@ui-kitten/components' but when I try to import it I get this erro:
 "Cannot resolve symbol 'SelectItem'"

Is there anything else I should install or what?

**Comment by artyorsh** [comment]
@niloufarMakhzani Related code?

**Comment by niloufarMakhzani** [comment]
"@ui-kitten/components": "^4.4.1",
    "@ui-kitten/eva-icons": "^4.4.1",
    "react-native-ui-kitten": "^4.4.0-beta.3",

Just when I try the following code:
import { SelectItem} from '@ui-kitten/components';

I get error which it's now found!

**Comment by artyorsh** [comment]
You use the wrong documentation. `SelectItem` is presented in version 5.
Please switch the documentation version or [upgrade](https://akveo.github.io/react-native-ui-kitten/docs/migration/4x500-migration).

![image](https://user-images.githubusercontent.com/10753921/79001644-827fb480-7b57-11ea-8a71-a5df5a8afb39.png)

And, by the way, using both `react-native-ui-kitten` and `@ui-kitten/components` packages is redundant.
