### ISSUE TITLE
How can I use clear(method)

### ISSUE THREAD

**Issue by afmejia** [akveo/react-native-ui-kitten#1001]
## 💬 Question
I am using a Select component in a form, after form is submitted the first time, every time form is rendered the Select component has the previous selected value. I would like to reset the value to none and show placeholder on a new submission. I know that a clear() method is available bue I cannot see an example of how to use this method.

Anybody could help me with an example of the clear() method on a Select component?

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |1.3.2|
| @ui-kitten/components   |   4.3.2      |

**Comment by artyorsh** [comment]
You can do this via ref. And, by the way, everything that marked with `method` in the documentation is assumes calling refs.
```js
// 1. Create a ref (you should use React.useRef in case your component is a function)
const selectRef = React.createRef();

// 2. Assign to a component
<Select ref={this.selectRef} />

// 3. Trigger this call inside the event you're interested.
selectRef.current.clear();
```

**Comment by afmejia** [comment]
Thanks @artyorsh , I implemented your suggestion but I get this error message "selectRef.current.clear is not a function. (In 'selectRef.current.clear()', 'selectRef.current.clear' is undefined)". I already inspected selectRef and other props are present, but methods doesn't.

**Comment by artyorsh** [comment]
Can you please share the full code?

**Comment by afmejia** [comment]
const selectRef = createRef();


```javascript
const selectRef  = createRef();

function AddClientScreen(props) {
    const { client } = state;

    useEffect(() => selectRef.current.clear(), [client]);
    ...
    return (
        <Select
            ref={selectRef}
            data={departmentOptions}
            ...
        />
    );
}
```

**Comment by artyorsh** [comment]
@afmejia 
// 1. Create a ref (you should use React.useRef in case your component is a function)
> you should use React.useRef in case your component is a function

**Comment by afmejia** [comment]
I get same error. Inspecting selectRef.current object I found this:
```javascript
Object {
  "_reactInternalFiber": FiberNode {
    "tag": 1,
    "key": null,
    "type": [Function SelectComponent],
  },
  "_reactInternalInstance": Object {},
  "animateIcon": [Function anonymous],
  "context": Object {},
  "dispatchActive": [Function anonymous],
  "getComponentStyle": [Function anonymous],
  "handleVisibleChange": [Function anonymous],
  "iconAnimation": 0,
  "onBlur": [Function anonymous],
  "onFocus": [Function anonymous],
  "onMouseEnter": [Function anonymous],
  "onMouseLeave": [Function anonymous],
  "onPress": [Function anonymous],
  "onPressIn": [Function anonymous],
  "onPressOut": [Function anonymous],
  "onSelect": [Function anonymous],
  "refs": Object {},
  "renderComponentChildren": [Function anonymous],
  "renderControlChildren": [Function anonymous],
  "renderControlElement": [Function anonymous],
  "renderDefaultIconElement": [Function anonymous],
  "renderIconElement": [Function anonymous],
  "renderLabelElement": [Function anonymous],
  "renderOptionsListElement": [Function anonymous],
  "renderTextElement": [Function anonymous],
  "selectionStrategy": SingleSelectStrategy {
    "keyExtractor": undefined,
    "selectedOption": undefined,
  },
  "setVisibility": [Function anonymous],
  "startIconAnimation": [Function anonymous],
  "state": Object {
    "visible": false,
  },
  "updater": Object {
    "enqueueForceUpdate": [Function enqueueForceUpdate],
    "enqueueReplaceState": [Function enqueueReplaceState],
    "enqueueSetState": [Function enqueueSetState],
    "isMounted": [Function isMounted],
  },
  "webEventResponder": WebEventResponderInstance {
    "eventHandlers": Object {
      "onBlur": [Function onBlur],
      "onFocus": [Function onFocus],
      "onMouseEnter": [Function onMouseEnter],
      "onMouseLeave": [Function onMouseLeave],
    },
  },
}

```

**Comment by afmejia** [comment]
@artyorsh  I compare the files: sect.component.d.ts and input.component.d.ts in node modules/@ui-kitten and I noticed that in the second file the methods describe in the documentation are missing.

**Comment by artyorsh** [comment]
@afmejia sorry, checked the wrong release sources. This method is [really missing in v4.3.2](https://github.com/akveo/react-native-ui-kitten/blob/v4.3.2/src/components/ui/select/select.component.tsx), but I can suggest upgrading to latest versions, e.g [4.4.1](https://github.com/akveo/react-native-ui-kitten/blob/v4.4.1/src/components/ui/select/select.component.tsx#L218).
