### ISSUE TITLE
JSON value '#8F9BB3' of type NNString cannot be converted to a UIColor. Did you forget to call processColor() on the JS side?

### ISSUE THREAD

**Issue by NguyenPhatBG** [akveo/react-native-ui-kitten#1005]
When I import and using Select component, issue is throw in above?
How can I fix that?

import React from 'react';
import { SafeAreaView, Text, View } from 'react-native';
import * as eva from '@eva-design/eva';
import { ApplicationProvider, IndexPath, Layout, Select, SelectItem } from '@ui-kitten/components';

const HomeScreen = () => {
  const [selectedIndex, setSelectedIndex] = React.useState(new IndexPath(0));
  return (
    <Layout style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
      <Text category='h1'>HOME</Text>
      <Select
        selectedIndex={selectedIndex}
        onSelect={index => setSelectedIndex(index)}
      >
        <SelectItem title='Option 1'/>
        <SelectItem title='Option 2'/>
        <SelectItem title='Option 3'/>
      </Select>
    </Layout>
  );
}

export default () => (
  <ApplicationProvider {...eva} theme={eva.light}>
    <HomeScreen />
  </ApplicationProvider>
);

**Comment by WilliamBlais** [comment]
I'm having the same issue.

**Comment by artyorsh** [comment]
I can't help without seeing your configuration. Please include a package.json

And for the future questions make sure to follow the issue template you delete when opening a new issue.

**Comment by WilliamBlais** [comment]
@artyorsh I'm having the same issue while using <Select>. Here's a few extra information;

`{
  "main": "index.js",
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "expo start --web",
    "start": "react-native start",
    "test": "jest",
    "pod": "cd ios && pod install && cd .."
  },
  "dependencies": {
    "@eva-design/eva": "^2.0.0-alpha.1",
    "@react-native-community/masked-view": "^0.1.8",
    "@react-navigation/native": "^5.1.5",
    "@react-navigation/stack": "^5.2.10",
    "@types/node": "^13.11.1",
    "@ui-kitten/components": "^5.0.0-alpha.1",
    "@ui-kitten/eva-icons": "^5.0.0-alpha.1",
    "expo": "~37.0.3",
    "expo-linear-gradient": "^8.1.0",
    "expo-updates": "~0.1.0",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "~0.61.5",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-reanimated": "^1.8.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.4.0",
    "react-native-svg": "^12.1.0",
    "react-native-unimodules": "~0.9.0",
    "react-native-web": "~0.11.7"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0",
    "@types/react": "~16.9.23",
    "@types/react-native": "~0.61.23",
    "babel-preset-expo": "~8.1.0",
    "jest-expo": "~37.0.0",
    "typescript": "~3.8.3"
  },
  "jest": {
    "preset": "react-native"
  },
  "private": true
}
`
Observations;

- #8F9BB3 is color-basic-600 in the theme.
- when removing this line from the render() function in select.component.js, the error disappear:
`            react_1.default.createElement(react_native_1.View, { style: style },
`
- Removing { style: style } has no effect.

**Comment by WilliamBlais** [comment]
@artyorsh removing "evaStyle" from createElement(chevronDown_component_1.ChevronDown... in select.component.js removes the error. I'm unsure what to do next.

**Comment by WilliamBlais** [comment]
@NguyenPhatBG You can temporarily fix this issue by adding a accessoryRight prop to <Select>.

**Comment by lfabreges** [comment]
I ran into the same issue, here's how to fix it in `select.component.tsx`:

```ts
private renderDefaultIconElement = ({tintColor, ...evaStyle}): React.ReactElement => {
    return (
      <Animated.View style={{ transform: [{ rotate: this.expandToRotateInterpolation }] }}>
        <ChevronDown {...evaStyle} fill={tintColor}/>
      </Animated.View>
    );
  };
```

Otherwise, like @WilliamBlais noticed, you pass a tintColor prop to the icon instead of using only the fill prop.

**Comment by artyorsh** [comment]
Hello 👋 
Instead of patching dependency sources, use `react-native-svg@9.13.3`. There was a breaking change in future releases of that library, and I’ll mention that in the docs soon.
Thanks for reporting.
