### ISSUE TITLE
Different height for Input and Select on Android

### ISSUE THREAD

**Issue by jorgnyg** [akveo/react-native-ui-kitten#1006]
## 🐛 Bug Report

Height of Input and Select component is not equal on Android, but seems to be right on iOS

## To Reproduce

Add Input and Select component on a flexDirection: "row" to clearly see the difference. 
![image](https://user-images.githubusercontent.com/35953480/79040779-45650200-7beb-11ea-8a91-a231621fd172.png)

## Expected behavior
Should have the same height (like on iOS)
![image](https://user-images.githubusercontent.com/35953480/79040788-57df3b80-7beb-11ea-8310-06141bc198c2.png)

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   1.4.0     |
| @ui-kitten/components   |    4.4.1     |

## Environment information

```bash
System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  npmPackages:
    react: ~16.9.0 => 16.9.0 
    react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4 
```

**Comment by interstellarbox** [comment]
Can confirm the same issue for me.
It also doesn't really clear how you can change the height for the Select component.
<Select style={{height: <number>}} .../> doesn't help.

**Comment by jorgnyg** [comment]
Migrated to 5.0.0-alpha1, but Select appears to have the same problem as reported

**Comment by Aleksefo** [comment]
The issue still exists in 5.0.0.
iOS works as intended, but Android has shorter Select.

![Screenshot 2021-02-12 at 08 33 30](https://user-images.githubusercontent.com/18084119/107737399-0329b700-6d0d-11eb-98b9-e721c228e7cf.png)
