### ISSUE TITLE
Android fonts is not the same as at iphone

### ISSUE THREAD

**Issue by fireridlle** [akveo/react-native-ui-kitten#1007]
## 🐛 Bug Report

<Text category="s1">
Doesn't look the same on both ios and android
## To Reproduce
const App = (): React.ReactFragment => <Text>Lorem ipsum dolor sit amet, consectetur adipiscing</Text>;

## Expected behavior
Text should look the same on both ios and android

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |     1.4.0   |
| @ui-kitten/components   |     4.4.1    |

**Comment by artyorsh** [comment]
It's default behavior of React Native. You might want to follow [this guide](https://akveo.github.io/react-native-ui-kitten/docs/guides/branding) to configure the typography.

**Comment by fcamargo10** [comment]
Same problem! How you fix ?
