### ISSUE TITLE
Ged rid of android blue status bar

### ISSUE THREAD

**Issue by fireridlle** [akveo/react-native-ui-kitten#1008]
## 💬 Question
![IMAGE 2020-04-11 14:10:37](https://user-images.githubusercontent.com/12122603/79042184-32a7f880-7bfe-11ea-9a59-76da469536dc.jpg)

is't possible to remove this blue bar?
it's emulator pixel 3 xl

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    1.4.0    |
| @ui-kitten/components   |    4.4.1     |

**Comment by sudomann** [comment]
Are you just starting out with your app? Can you share its code? I don't see how that bar would be caused by ui-kitten

**Comment by lesmo** [comment]
`ui-kitten` doesn't do anything with the status bar... but you can "get rid of it" by using the [StatusBar](https://reactnative.dev/docs/statusbar) component of React Native:

```jsx
<StatusBar hidden={true} />
```
