### ISSUE TITLE
Custom mapping not working

### ISSUE THREAD

**Issue by harryy2510** [akveo/react-native-ui-kitten#1009]
## 🐛 Bug Report

Passing a custom mapping like this doesn't work for some reason
![image](https://user-images.githubusercontent.com/7416971/79053682-c7414380-7c5c-11ea-8589-7785a931e1fc.png)
![image](https://user-images.githubusercontent.com/7416971/79053692-d7f1b980-7c5c-11ea-8c4e-bfb68cdb3df4.png)

But passing it like this works 
![image](https://user-images.githubusercontent.com/7416971/79053697-df18c780-7c5c-11ea-9688-c36ff39f5996.png)
![image](https://user-images.githubusercontent.com/7416971/79053708-e7710280-7c5c-11ea-95ed-b716a9a25f61.png)

Custom mapping is the same for both scenarios
![image](https://user-images.githubusercontent.com/7416971/79053732-10919300-7c5d-11ea-87ee-baf82dd9fa28.png)

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    ^2.0.0-alpha.1    |
| @ui-kitten/components   |     ^5.0.0-alpha.1    |

## Environment information

```bash

  System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  Binaries:
    Node: 13.9.0 - ~/.nvm/versions/node/v13.9.0/bin/node
    Yarn: 1.22.4 - ~/.yvm/shim/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v13.9.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 27, 28
      Build Tools: 27.0.3, 28.0.3, 29.0.3
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  npmPackages:
    react: ~16.13.1 => 16.13.1 
    react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 

```

**Comment by artyorsh** [comment]
@harryy2510 any chance `@ui-kitten/metro-config` is included in your package.json and has it's configuration in `metro.config.js`?

**Comment by harryy2510** [comment]
Yes I do have `@ui-kitten/metro-config` installed but doesn't have `metro.config.js` but instead `webpack.config.js`

![image](https://user-images.githubusercontent.com/7416971/79198522-3da69700-7e51-11ea-9b0e-65714e4c0bd1.png)

![image](https://user-images.githubusercontent.com/7416971/79198538-45fed200-7e51-11ea-8a31-18cacd2e5faa.png)

**Comment by gabrielepmattia** [comment]
I had the same issue, I solved it by following this guide https://akveo.github.io/react-native-ui-kitten/docs/guides/improving-performance#improving-performance

**Comment by artyorsh** [comment]
@gabrielepmattia @harryy2510 Sorry for the late reply. Just tried it in a fresh project [initialized with template](https://github.com/akveo/react-native-ui-kitten/tree/next#quick-start) and couldn't reproduce.

Could you please share a reproducible demo or describe the steps on how did you initialize?
What `@ui-kitten/metro-config` does is pre-generating styles during the metro bundler build time. And if it was successful, ApplicationProvider will ignore `customMapping`. Not having metro.config.js means not having anything pre-generated.

**Comment by artyorsh** [comment]
[Snack Demo](https://snack.expo.io/kE_DDpx01)

**Comment by gabrielepmattia** [comment]
@artyorsh Sorry to reopen the issue but I created from scratch a new project, I copied your `mapping.json` and it is still not working. Here's the repository of the sample project (https://github.com/gabrielepmattia/react-native-ui-kitten-custom-mapping-issue), you can check the commits for seeing what I've done, maybe I'm doing something wrong. Steps to reproduce:
1. Start new project with `npx react-native init MyApp --template @ui-kitten/template-js`
2. Create `mapping.json` and import in `App.tsx` with `import { default as appMapping } from './mapping.json';`
3. Add `customMapping={appMapping}` to ApplicationProvider in `App.tsx`
4. Add `resolveJsonModule` in tsconfig.json for allowing loading of json files
5. Run `npx react-native run-android` or `npx react-native run-ios`

I attach here the screenshots, again only pre-building the mapping makes the button turn pink. I also get type errors in the custom mapping and in the button icon (attached screenshot).

<img src="https://user-images.githubusercontent.com/7265233/80359158-ba883680-887d-11ea-9194-537bd30bda7d.png" width="200" /> <img src="https://user-images.githubusercontent.com/7265233/80359829-b1e43000-887e-11ea-8b35-1ca8aa8e8fe6.png" width="200" />

<img width="1311" alt="Screenshot 2020-04-27 at 12 04 06" src="https://user-images.githubusercontent.com/7265233/80360277-61b99d80-887f-11ea-89d9-0f28020192fa.png">

Thank you for your time 

P.S.: Moreover the Heart icon in the button is missing.

**Comment by KaKaVip** [comment]
@artyorsh But not working with [Custom Component Mapping ](https://akveo.github.io/react-native-ui-kitten/docs/design-system/custom-component-mapping#create-a-custom-component-mapping
)
I copied CircleButton and custom mapping for CircleButton. but not working.

**Comment by artyorsh** [comment]
@KaKaVip yep, thanks for the details. I fixed that in [d120d5d](https://github.com/akveo/react-native-ui-kitten/pull/1055/commits/d120d5d690eeac78341f16254fd589e18660ef48). This is an upcoming change anyway, but if you need to use it currently, this may achieved by modifying props like the [migration guide says](https://akveo.github.io/react-native-ui-kitten/docs/migration/4x500-migration#migrate-high-order-components). Sorry for such type of issue.

@gabrielepmattia thanks for the details 👍The commit above also gives some notes on this. The problem is [you use](https://github.com/gabrielepmattia/react-native-ui-kitten-custom-mapping-issue/blob/master/metro.config.js#L17) metro configuration which creates a styles during the build time. `customMapping` property is not required in this case as it is completely ignored. What you can do is modifying your metro.config.js with.
```js
const evaConfig = {
  evaPackage: '@eva-design/eva',
  customMappingPath: './path-to/custom-mapping.json', 
};
```

Maake sure to restart the bundler afterwards.

**Comment by gabrielepmattia** [comment]
> @KaKaVip yep, thanks for the details. I fixed that in [d120d5d](https://github.com/akveo/react-native-ui-kitten/pull/1055/commits/d120d5d690eeac78341f16254fd589e18660ef48). This is an upcoming change anyway, but if you need to use it currently, this may achieved by modifying props like the [migration guide says](https://akveo.github.io/react-native-ui-kitten/docs/migration/4x500-migration#migrate-high-order-components). Sorry for such type of issue.
> 
> @gabrielepmattia thanks for the details The commit above also gives some notes on this. The problem is [you use](https://github.com/gabrielepmattia/react-native-ui-kitten-custom-mapping-issue/blob/master/metro.config.js#L17) metro configuration which creates a styles during the build time. `customMapping` property is not required in this case as it is completely ignored. What you can do is modifying your metro.config.js with.
> 
> ```js
> const evaConfig = {
>   evaPackage: '@eva-design/eva',
>   customMappingPath: './path-to/custom-mapping.json', 
> };
> ```
> 
> Maake sure to restart the bundler afterwards.

Perfect, now it's clear but `metro.config.js` is created automatically by the project template, I think it should pointed out in the docs as a side note that the custom mapping must not to be used in the `ApplicationProvider`, especially for newcomers as me! Thank you!

**Comment by artyorsh** [comment]
> it should pointed out in the docs as a side note that the custom mapping must not to be used

That is what I did 🙌

**Comment by shalu-tulsyan** [comment]
![Screenshot from 2021-09-22 18-06-57](https://user-images.githubusercontent.com/83806212/134344741-092439fe-f15e-4ddd-9aab-270782d9d919.png)
Having error on customMapping, how to resolve this?
