### ISSUE TITLE
TopNavigationAction is not show the back icon on UI Kitten 5

### ISSUE THREAD

**Issue by mhhonline** [akveo/react-native-ui-kitten#1010]
## 🐛 Bug Report
 
I just tried the new version 5.0.0. I followed the example of how to implement the TopNavigationAction. the icon on top is not shown. 

I did not install the font, I guess this has nothing to do with that. 
to confirm that the icon component is working in general, on the screen I added the Facebook icon without an issue. only on the nav. BTW, the same issue happened on both iOS and Android
<img width="341" alt="Screen Shot 2020-04-12 at 8 51 23 AM" src="https://user-images.githubusercontent.com/8745720/79061639-e6f75c80-7c9a-11ea-9d30-03b9b1b93d0f.png">

## To Reproduce
I used expo to install all required libs following the steps below: 
https://akveo.github.io/react-native-ui-kitten/docs/guides/getting-started#getting-started
https://akveo.github.io/react-native-ui-kitten/docs/guides/icon-packages#icon-packages
https://akveo.github.io/react-native-ui-kitten/docs/guides/configure-navigation#configure-navigation

## Expected behavior
I expect to see the back icon and make it function on both Android and iOS

If I tried to install expo install react-native-svg@9.13.6
I got this version in package.json
"react-native-svg": "11.0.1",

I tried to change the version in package.json to 9.13.6 then re-run the npm I but it failed in building the app. 
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-12 at 08 42 44](https://user-images.githubusercontent.com/8745720/79061563-1ce81100-7c9a-11ea-893c-002b2c96173b.png)

## UI Kitten and Eva version

|"dependencies": {
    "@eva-design/eva": "^2.0.0-alpha.1",
    "@react-native-community/masked-view": "0.1.6",
    "@react-navigation/native": "^5.1.5",
    "@react-navigation/stack": "^5.2.10",
    "@ui-kitten/components": "^5.0.0-alpha.1",
    "@ui-kitten/eva-icons": "^5.0.0-alpha.1",
    "expo": "~37.0.3",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-reanimated": "~1.7.0",
    "react-native-safe-area-context": "0.7.3",
    "react-native-screens": "~2.2.0",
    "react-native-svg": "11.0.1",
    "react-native-web": "~0.11.7"
  },
  "devDependencies": {
    "babel-preset-expo": "~8.1.0",
    "@babel/core": "^7.8.6"
  },
## Environment information

System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 356.41 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    npm: 6.13.4 - /usr/local/bin/npm
  Managers:
    CocoaPods: 1.0.1 - /Users/mohammed-macbookPro/.rvm/rubies/ruby-2.3.0/bin/pod
    Homebrew: 2.1.11 - /usr/local/bin/brew
    pip3: 19.0.3 - /usr/bin/pip3
    RubyGems: 2.5.1 - /Users/mohammed-macbookPro/.rvm/rubies/ruby-2.3.0/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.23.0 - /usr/local/bin/git
    Clang: 1103.0.32.29 - /usr/bin/clang
  Servers:
    Apache: 2.4.41 - /usr/sbin/apachectl
  Virtualization:
    Parallels: 15.1.3 - /usr/local/bin/prlctl
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 17, 18, 19, 20, 21, 22, 23, 26, 27, 28, 29
      Build Tools: 29.0.3
      System Images: android-23 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Nano: 2.0.6 - /usr/bin/nano
    Vim: 8.1 - /usr/bin/vim
    WebStorm: 2019.3.3
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 1.8.0_101 - /usr/bin/javac
    Perl: 5.18.4 - /usr/bin/perl
    PHP: 7.3.11 - /usr/bin/php
    Python: 2.7.16 - /usr/bin/python
    Python3: 3.7.3 - /usr/bin/python3
    Ruby: 2.3.0 - /Users/mohammed-macbookPro/.rvm/rubies/ruby-2.3.0/bin/ruby
  Databases:
    MongoDB: 4.2.0 - /usr/local/bin/mongo
    SQLite: 3.28.0 - /Users/mohammed-macbookPro/Library/Android/sdk/platform-tools/sqlite3
  Browsers:
    Chrome: 80.0.3987.163
    Firefox: 66.0.2
    Safari: 13.1

```bash

```

**Comment by artyorsh** [comment]
I suppose you're doing something wrong. See the working example on snack https://snack.expo.io/WcuOHWMqE

**Comment by mhhonline** [comment]
thank you Artur, 
it was a documentation issue. in the example. 

it used leftControl={BackAction()} whereas it should use accessoryLeft={BackAction}

<TopNavigation title='MyApp' alignment='center' **leftControl={BackAction()}/**> 
<TopNavigation  title='MyApp' alignment='center' **accessoryLeft={BackAction}**/>

Thanks

**Comment by artyorsh** [comment]
@mhhonline

> it was a documentation issue. in the example.

[Was it](
https://akveo.github.io/react-native-ui-kitten/docs/components/top-navigation/overview#topnavigationaction)? Can't see there is a `leftControl` prop in the examples

**Comment by mhhonline** [comment]
@artyorsh
you are right, in the component example's is correct. 

I started from the beginning here in "Details Screen"
https://akveo.github.io/react-native-ui-kitten/docs/guides/configure-navigation#create-screens

you can see `leftControl`
```
return (
    <SafeAreaView style={{ flex: 1 }}>
      <TopNavigation title='MyApp' alignment='center' leftControl={BackAction()}/>
      <Divider/>
      <Layout style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        <Text category='h1'>DETAILS</Text>
      </Layout>
    </SafeAreaView>
  );
```
