### ISSUE TITLE
Different `Toggle` component `backgroundThumbColor` for checked and unchecked

### ISSUE THREAD

**Issue by lesmo** [akveo/react-native-ui-kitten#1012]
## 💬 Question

I'm trying to figure out a way to set a custom "thumb" color when the `Toggle` component's `checked` state is `false`:

![image](https://user-images.githubusercontent.com/2228196/79086845-25286680-7d03-11ea-9feb-794417721993.png) ![image](https://user-images.githubusercontent.com/2228196/79086851-2a85b100-7d03-11ea-80ad-7381c311e57b.png)

We're supporting light and dark schemes, which are literally black and white. In dark scheme, `white` is the primary color and in the light scheme `black` is the primary color. It looks good on all the components we're using.... except for `Toggle`.

We're trying to make the "thumb" color to be colored as the theme's primary color only when it's not _checked_, as it's default coloring works perfectly when _it's checked_. Reading the source code for `Toggle` there doesn't seem to be any way to do this... so...

Is this even possible as it is? Would I need to write a custom `Toggle` component?

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    ^1.4.0    |
| @ui-kitten/components   |     ^4.4.1    |

**Comment by artyorsh** [comment]
@lesmo in the default state of `primary` variant (which is also default) [Toggle uses](https://github.com/eva-design/eva/blob/master/packages/eva/mapping.json#L5412) the first level of background. I guess there is no way to change this except modifying mapping.

**Comment by lesmo** [comment]
Hey! I've been chasing that `json` file but couldn't find it, thanks! After doing some testing, I figured `control` state could've worked for us too... but hey, now I know how mapping works.

Documentation is pretty sparse in this regard, I think. But I finally understood how this works. I fixed it by writing this mapping thanks to that `json`:

```json
{
  "components": {
    "Toggle": {
      "meta": {},
      "appearances": {
        "default": {
          "mapping": {},
          "variantGroups": {
            "status": {
              "primary": {
                "thumbBackgroundColor": "color-primary-default",
                "state": {
                  "checked": {
                    "thumbBackgroundColor": "background-basic-color-1"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

Any chance this could be written as YAML in a future release? Hehe...

I'll close this. Thanks!
