### ISSUE TITLE
v5 - icon size

### ISSUE THREAD

**Issue by WilliamBlais** [akveo/react-native-ui-kitten#1014]
## UI Kitten and Eva version
    "@eva-design/eva": "^2.0.0-alpha.1",
    "@ui-kitten/components": "^5.0.0-alpha.1",

Hi,
I'm trying change the size of an icon on the Button element.

`              <Button
                style={styles.loginBtn}
                accessoryLeft={iconFacebook}
              ></Button>
`

`    const iconFacebook = (props: IconProps) => (
      <Icon {...props} name="facebook"></Icon>
    );
`

How can I pass the height and width to the icon? Which type is the props parameter?

Btw, I love UI kitten, thank you for your awesome package.

**Comment by artyorsh** [comment]
@WilliamBlais thanks for the feedback.

The documentation says:
> In case of using Eva Icons it renders [svg images](https://github.com/react-native-community/react-native-svg).

Meaning it accepts [the same properties](https://github.com/react-native-community/react-native-svg#common-props) as svg elements, including `width`, `height` or even `style`.

Also:
![image](https://user-images.githubusercontent.com/10753921/79155727-4314ca80-7dda-11ea-92c8-c69e5fab1b25.png)

**Comment by arthurliebhardt** [comment]
@artyorsh somehow I also can not change the size of an icon. When I try another style={styles.icon} it just Show nothing. When I change the Button width and height it just expands the Button , but not the icon somehow.

**Comment by artyorsh** [comment]
@arthurliebhardt 
When there is a need to modify the existing props, keep in mind that you should also keep the initial stylings provided by the library.

```js
// 1. Notice we have the props here. Provided by Eva and UI Kitten
// 2. In case of using `@ui-kitten/eva-icons` the icon you render is react-native-svg element,
//    so, to change the color you should use `fill` property
const StarIcon = (props) => (
  <Icon {...props} fill='red' name='star' />
);

<Button accessoryLeft={StarIcon} />
```

**Comment by arthurliebhardt** [comment]
@artyorsh ok, sorry didn't know that. Thank you :) .
