### ISSUE TITLE
v5 breaks support for functional components with hooks in accessories

### ISSUE THREAD

**Issue by Photonios** [akveo/react-native-ui-kitten#1015]
## 🐛 Bug Report
v5 breaks support for rendering components with hooks in props such as `accessoryLeft` due to the implementation of: https://github.com/akveo/react-native-ui-kitten/blob/next/src/components/devsupport/components/falsyFC/falsyFC.component.tsx

`FalsyFC` should not make the assumption that components are plain functions. It should properly use `React.createElement` so hooks continue working.

## To Reproduce
```
const MyHookComponent = () => {
        const [name, setName] = React.useState('');
        React.useEffect(() => {
              setName('test');
        });

        return <Text>{name}</Text>;
};

const MyApp = () => (
        <TopNavigation
                accessoryLeft={MyHookComponent}
                title={"test"}
          />
);
```

## Expected behavior

For `FalsyFC` to render components with hooks by properly using `React.createElement`.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |  2.0.0-alpha.1      |
| @ui-kitten/components   | 5.0.0-alpha.1        |

**Comment by artyorsh** [comment]
@Photonios thanks for reporting and pointing for the possible solution.

As a workaround, you may create a function that renders a function component: https://snack.expo.io/AAtTzHId3
