### ISSUE TITLE
Vue Native

### ISSUE THREAD

**Issue by ChristopherJohnson25** [akveo/react-native-ui-kitten#1016]
Does anyone have any experience utilizing this add on with Vue Native? My understanding is that they should be compatible...

**Comment by artyorsh** [comment]
As a maintainer, I didn't tried that. But I've seen projects using other ui libraries without any problems. Have you tried following the [official docs](https://vue-native.io/docs/installation.html)?

**Comment by ChristopherJohnson25** [comment]
I have looked at the docs, they are OK. I'll keep trying and update you if I get it to work!

**Comment by artyorsh** [comment]
@ChristopherJohnson25 thanks a lot! We're also open for PRs, you may create an article for our docs on how to run it, so other users who interested in this may know ;)

**Comment by yhc44** [comment]
@ChristopherJohnson25 hey, did you find a solution?

I want to use it in vue native, but there is an error "undefined is not an object".

I dont know how to map all props to application-provider. In react native you simply use {...props}

**Comment by malashkevich** [comment]
I would propose to move this question to the SO.

**Comment by asifma** [comment]
Did anyone found a solution to use UI Kitten?
