### ISSUE TITLE
Need Support in Implementing Drawer with passing Params

### ISSUE THREAD

**Issue by mhhonline** [akveo/react-native-ui-kitten#1018]
## 💬 Question
I am working on a Drawer to navigate to different screens.
 
The structure is as follow:
-NEWS -- DrawerItem
-SEND REPORT -- DrawerItem
-PUBLICATION --DrawerGroup
    -- ITEM#1 --DrawerItem
    --ITEM#2 -- DrawerItem

All News, ITEMS#1 and ITEMS#2 are pointing to the same Screen (RssFeedScreen). 

**How to:**
1- pass params from DrawerItem to the screen (RssFeedScreen) in my case. I tried with onPress but no luck. 
2- on RssFeedScreen, how can I get the prams, so I do further action? 
3- call the right screen (component) when I press on DrawerItem. there is something I miss understand in the order. drawerItem and screen order in the drawer because of DrawerGroup. **In case I want to call different screens for each ITEM**
4- for some reason, my Android device renders the screen as RTL. did I miss any configuration file?

I uploaded the project on git to be clear. 
here is the link: https://github.com/mhhonline/UI-Kitten-Drawer-ex

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |     2.0.0-alpha.1   |
| @ui-kitten/components   |    5.0.0-alpha.1     |

**Comment by artyorsh** [comment]
@mhhonline 

1. Passing params is described in [React Navigation docs](https://reactnavigation.org/docs/params/)
2. Getting params as well
3. Are you looking for an architecture proposal? Because there are a [react-navigation docs](https://reactnavigation.org/docs/drawer-based-navigation), [UI Kitten docs](https://akveo.github.io/react-native-ui-kitten/docs/components/drawer/overview#drawer), a [demo app](https://github.com/artyorsh/react-navigation-ex-demo) and even [the article from me](https://reactnavigation.org/blog/2019/11/04/using-react-navigation-5-with-ui-kitten/)
4. Definitely not UI Kitten issue, but I guess this is configured to follow the device locale by default. Check the [React Native docs](https://reactnative.dev/blog/2016/08/19/right-to-left-support-for-react-native-apps)

**Comment by artyorsh** [comment]
@mhhonline your code is wrong in [using only a `row` param](https://github.com/mhhonline/UI-Kitten-Drawer-ex/blob/master/navigation/navigation.component.js#L17) of the index object. What you should do is also described in the docs, please read more carefully ;)

![image](https://user-images.githubusercontent.com/10753921/79271029-d10ab700-7ea7-11ea-88ba-e5ad8972afa2.png)

**Comment by mhhonline** [comment]
Greetings @artyorsh 

Sorry for the inconvenience, I learned React-native through expo. So it could be the steps are not correct for running the demo app. 
what I did:
1-  `(yarn install)`
2- `npx react-native start`
```
success Successfully bootstrapped @eva-design/eva
Looking for JS files in
   /Users/mohammed-macbookPro/Downloads/react-navigation-ex-demo-initial-setup 
Loading dependency graph, done.
To reload the app press "r"
To open developer menu press "d"
```

3- `react-native run-ios`
`info Found Xcode workspace "ReactNavigationExDemo.xcworkspace"
info Building (using "xcodebuild -workspace ReactNavigationExDemo.xcworkspace -configuration Debug -scheme ReactNavigationExDemo -destination id=EF160D60-E5BB-47FD-87DA-916588319C7F")
...............
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening ReactNavigationExDemo.xcworkspace. Run CLI with --verbose flag for more details.
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace ReactNavigationExDemo.xcworkspace -configuration Debug -scheme ReactNavigationExDemo -destination id=EF160D60-E5BB-47FD-87DA-916588319C7F

note: Using new build system
note: Planning build
note: Constructing build description
error: /Users/mohammed-macbookPro/Downloads/react-navigation-ex-demo-initial-setup/ios/Pods/Target Support Files/Pods-ReactNavigationExDemo/Pods-ReactNavigationExDemo.debug.xcconfig: unable to open file (in target "ReactNavigationExDemo" in project "ReactNavigationExDemo") (in target 'ReactNavigationExDemo' from project 'ReactNavigationExDemo')
error: /Users/mohammed-macbookPro/Downloads/react-navigation-ex-demo-initial-setup/ios/Pods/Target Support Files/Pods-ReactNavigationExDemo/Pods-ReactNavigationExDemo.debug.xcconfig: unable to open file (in target "ReactNavigationExDemo" in project "ReactNavigationExDemo") (in target 'ReactNavigationExDemo' from project 'ReactNavigationExDemo')
error: /Users/mohammed-macbookPro/Downloads/react-navigation-ex-demo-initial-setup/ios/Pods/Target Support Files/Pods-ReactNavigationExDemo/Pods-ReactNavigationExDemo.debug.xcconfig: unable to open file (in target "ReactNavigationExDemo" in project "ReactNavigationExDemo") (in target 'ReactNavigationExDemo' from project 'ReactNavigationExDemo')
error: /Users/mohammed-macbookPro/Downloads/react-navigation-ex-demo-initial-setup/ios/Pods/Target Support Files/Pods-ReactNavigationExDemo/Pods-ReactNavigationExDemo.debug.xcconfig: unable to open file (in target "ReactNavigationExDemo" in project "ReactNavigationExDemo") (in target 'ReactNavigationExDemo' from project 'ReactNavigationExDemo')
warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the ReactNavigationExDemo editor. (in target 'ReactNavigationExDemo' from project 'ReactNavigationExDemo')
error: /Users/mohammed-macbookPro/Downloads/react-navigation-ex-demo-initial-setup/ios/Pods/Target Support Files/Pods-ReactNavigationExDemoTests/Pods-ReactNavigationExDemoTests.debug.xcconfig: unable to open file (in target "ReactNavigationExDemoTests" in project "ReactNavigationExDemo") (in target 'ReactNavigationExDemoTests' from project 'ReactNavigationExDemo')
error: /Users/mohammed-macbookPro/Downloads/react-navigation-ex-demo-initial-setup/ios/Pods/Target Support Files/Pods-ReactNavigationExDemoTests/Pods-ReactNavigationExDemoTests.debug.xcconfig: unable to open file (in target "ReactNavigationExDemoTests" in project "ReactNavigationExDemo") (in target 'ReactNavigationExDemoTests' from project 'ReactNavigationExDemo')
error: /Users/mohammed-macbookPro/Downloads/react-navigation-ex-demo-initial-setup/ios/Pods/Target Support Files/Pods-ReactNavigationExDemoTests/Pods-ReactNavigationExDemoTests.debug.xcconfig: unable to open file (in target "ReactNavigationExDemoTests" in project "ReactNavigationExDemo") (in target 'ReactNavigationExDemoTests' from project 'ReactNavigationExDemo')
error: /Users/mohammed-macbookPro/Downloads/react-navigation-ex-demo-initial-setup/ios/Pods/Target Support Files/Pods-ReactNavigationExDemoTests/Pods-ReactNavigationExDemoTests.debug.xcconfig: unable to open file (in target "ReactNavigationExDemoTests" in project "ReactNavigationExDemo") (in target 'ReactNavigationExDemoTests' from project 'ReactNavigationExDemo')


** BUILD FAILED **
`


react-native info 
info Fetching system and libraries information...
System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 2.03 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.0.1 - /Users/mohammed-macbookPro/.rvm/rubies/ruby-2.3.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 17, 18, 19, 20, 21, 22, 23, 26, 27, 28, 29
      Build Tools: 29.0.3
      System Images: android-23 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_101 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.9.0 => 16.9.0 
    react-native: ^0.61.5 => 0.61.5 
  npmGlobalPackages:
    *react-native*: Not Found






node --version v 12.16.1
watchman -v 4.9.0
Xcode Version 11.4 (11E146)
Simulator Version 11.4 (921.9)
pod --version 1.0.1
npx react-native --version 3.2.0

**Comment by mhhonline** [comment]
I tried to build from the Xcode

Showing Recent Messages

Build target ReactNavigationExDemoTests of project ReactNavigationExDemo with configuration Debug
error: /Users/mohammed-macbookPro/Downloads/react-navigation-ex-demo-initial-setup/ios/Pods/Target Support Files/Pods-ReactNavigationExDemoTests/Pods-ReactNavigationExDemoTests.debug.xcconfig: unable to open file (in target "ReactNavigationExDemoTests" in project "ReactNavigationExDemo") (in target 'ReactNavigationExDemoTests' from project 'ReactNavigationExDemo')
error: /Users/mohammed-macbookPro/Downloads/react-navigation-ex-demo-initial-setup/ios/Pods/Target Support Files/Pods-ReactNavigationExDemoTests/Pods-ReactNavigationExDemoTests.debug.xcconfig: unable to open file (in target "ReactNavigationExDemoTests" in project "ReactNavigationExDemo") (in target 'ReactNavigationExDemoTests' from project 'ReactNavigationExDemo')
error: /Users/mohammed-macbookPro/Downloads/react-navigation-ex-demo-initial-setup/ios/Pods/Target Support Files/Pods-ReactNavigationExDemoTests/Pods-ReactNavigationExDemoTests.debug.xcconfig: unable to open file (in target "ReactNavigationExDemoTests" in project "ReactNavigationExDemo") (in target 'ReactNavigationExDemoTests' from project 'ReactNavigationExDemo')
error: /Users/mohammed-macbookPro/Downloads/react-navigation-ex-demo-initial-setup/ios/Pods/Target Support Files/Pods-ReactNavigationExDemoTests/Pods-ReactNavigationExDemoTests.debug.xcconfig: unable to open file (in target "ReactNavigationExDemoTests" in project "ReactNavigationExDemo") (in target 'ReactNavigationExDemoTests' from project 'ReactNavigationExDemo')

**Comment by mhhonline** [comment]
> @mhhonline your code is wrong in [using only a `row` param](https://github.com/mhhonline/UI-Kitten-Drawer-ex/blob/master/navigation/navigation.component.js#L17) of the index object. What you should do is also described in the docs, please read more carefully ;)
> 
> ![image](https://user-images.githubusercontent.com/10753921/79271029-d10ab700-7ea7-11ea-88ba-e5ad8972afa2.png)

for this, I tried 
`state.routeNames[(index.row, index.section)`
in the group, if i select item#2, it returns the same route for item#1 which is "Home" route. i.e. all drawer items in a group are pointing to the same route.

**Comment by pitops** [comment]
Hey @mhhonline did you find a solution? this is definitely broken in my eyes
