### ISSUE TITLE
Unable to create card component with full background image

### ISSUE THREAD

**Issue by wontwon** [akveo/react-native-ui-kitten#1020]
## 💬 Question
I'm trying to follow along with the demo application's fitness dashboard where images were used as a background with a text foreground. I've been trying to follow the demo app's UI but have been unsuccessful for some reason I cannot get the image to stretch the entirety of the card component. Does anyone know if this is a bug? Or if not, can they point me in the right direction? Thank you for your help.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |        |
| @ui-kitten/components   | 5.0.0-alpha.1        |

This is what my component code looks like:
``` return (
	    <Card style={styles.container}>
			  <ImageBackground source={{uri: image}} resizeMode={"cover"} style={styles.image}>
				  <View style={styles.overlay}>
					  <View>
						  <Text>Hello</Text>
					  </View>
				  </View>
	      </ImageBackground>
		  </Card>
  );
```

```
const styles = StyleSheet.create({
	container: {
		height: 200,
	},
	card: {
		height: 200,
	},
  image: {
	  ...StyleSheet.absoluteFill,
  },
	overlay: {
  	...StyleSheet.absoluteFill,
		backgroundColor: "rgba(0, 0, 0, 0.3)",
	}
});
```

Image of what is rendered:
![Simulator Screen Shot - iPhone 11 - 2020-04-13 at 23 40 38](https://user-images.githubusercontent.com/3239936/79193827-40b56f00-7de0-11ea-9c62-f54f551d9f70.png)

**Comment by artyorsh** [comment]
> Does anyone know if this is a bug?
The card body is designed to contain a text. It has paddings pre-defined.
You may use the negative paddings like it was suggested in #1002 
Or use a `header` property as was suggested in #1011
