### ISSUE TITLE
Icons does not show

### ISSUE THREAD

**Issue by aprilmintacpineda** [akveo/react-native-ui-kitten#1021]
## To Reproduce

I am unsure how to reproduce this so I will just tell you the steps I did:

1. Created new project with `react-native init myProj`
2. I followed step on https://akveo.github.io/react-native-ui-kitten/docs/components/input/overview#input that one example with `accessoryRight` with `secureTextEntry`.
3. Realising that I need to do something else to make the Icon work, I went to https://akveo.github.io/react-native-ui-kitten/docs/guides/icon-packages#icon-packages and followed instruction

nothing was rendered on the right side of the input BUT I can click on that right side where the icon is suppose to be, and sure enough the functionality works, the `onPress` of `TouchableWithoutFeedback` was being fired and the password was toggling properly, I checked with the inspector and saw the following:

![image](https://user-images.githubusercontent.com/21032419/79224873-6dc05b00-7e8e-11ea-9494-e8561e82a7ba.png)

I can see the `TouchableWithoutFeedback` and the `Icon`, I think it's being rendered but somehow it is transparent making it invisible.

Note that I'm a complete beginner in using this UI kit with react-native, I haven't used any UI kits before, this is my first.

## Expected behavior

Hmmm... Icon should not be invisible(?)

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2.0.0-alpha.1    |
| @ui-kitten/components   |    5.0.0-alpha.1     |
| @ui-kitten/eva-icons   |    4.4.1     |

## Environment information

```bash
  System:
    OS: macOS Sierra 10.12.6
    CPU: (4) x64 Intel(R) Core(TM) i7-2620M CPU @ 2.70GHz
  Binaries:
    Node: 13.12.0 - ~/.nvm/versions/node/v13.12.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v13.12.0/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v13.12.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: /undefined - /usr/bin/xcodebuild
  npmPackages:
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
```

**Comment by artyorsh** [comment]
@aprilmintacpineda `@ui-kitten/eva-icons` should be 5.0

**Comment by aprilmintacpineda** [comment]
@artyorsh That's very kind of you, thank you!

**Comment by Vanclief** [comment]
Same issue, cant see Icons in Android after following the installation guide:

https://akveo.github.io/react-native-ui-kitten/docs/guides/icon-packages#eva-icons


Package | Version
-- | --
@eva-design/eva | 2.0.0
@ui-kitten/components | 5.0.0
@ui-kitten/eva-icons | 5.0.0

```
              <Icon
                fill='#8F9BB3'
                name='star'
              />
```
