### ISSUE TITLE
Configure Navigation Getting Started TopNavigation leftControl (back) is not showing

### ISSUE THREAD

**Issue by arthurliebhardt** [akveo/react-native-ui-kitten#1022]
## 💬 Question
I started with UI kitten and the Getting started tutorial, but after navigation in to the detail screen my leftControl TopNavigationAction in the TopNavigation is not showing an arrow back. I didn't changed the code from the tutorial. (https://akveo.github.io/react-native-ui-kitten/docs/guides/configure-navigation#create-navigator)

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |     2.0.0-alpha.1   |
| @ui-kitten/components   |     5.0.0-alpha.1    |

**Comment by artyorsh** [comment]
@arthurliebhardt This problem is already realized. You should use `accessoryLeft`, [see API](https://akveo.github.io/react-native-ui-kitten/docs/components/top-navigation/api#topnavigation) for more details

**Comment by arthurliebhardt** [comment]
Yes, after checking the component and the API I figured it out. Anyways in your Getting started Guide it's the old convention (https://akveo.github.io/react-native-ui-kitten/docs/guides/configure-navigation#configure-navigation)

Thanks for answering that fast
