### ISSUE TITLE
Selected option title not correctly displayed in V5

### ISSUE THREAD

**Issue by philyboysmith** [akveo/react-native-ui-kitten#1023]
## 🐛 Bug Report

When the new select component is closed, the value displayed comes from the default values (eg 'Option 1', 'Option 2') not those provided by the user.

## To Reproduce

* Copy [simple select](https://akveo.github.io/react-native-ui-kitten/docs/components/select/overview#select ) but change the title of the SelectItems to something "React", "Angular", "Something else"
* Load the component and select "Angular".
* The value displayed when the select closes is "Option 2"

## Expected behavior

* The value displayed when the select closes should be "Angular"

## Link to runnable example or repository (highly encouraged)

https://codesandbox.io/s/gallant-grass-j0tw4?file=/src/App.js
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |  ^2.0.0-alpha.1      |
| @ui-kitten/components   |    ^5.0.0-alpha.1     |

**Comment by artyorsh** [comment]
Mentioned in the [docs](https://akveo.github.io/react-native-ui-kitten/docs/components/select/overview#select)
![image](https://user-images.githubusercontent.com/10753921/79238606-43fc3980-7e78-11ea-9e85-0d3bc87afb11.png)
