### ISSUE TITLE
Missing file from npm 

### ISSUE THREAD

**Issue by jaydotcom** [akveo/react-native-ui-kitten#1027]
## 🐛 Bug Report

Got the following error after compiling : 
Unable to resolve "./card/cardHeader.component" from "node_modules\@ui-kitten\components\ui\index.js"

In fact in my node_modules folder, files in not there (nor in tar I've dowload through your changelog note)

## To Reproduce

Install via npm : npm i @ui-kitten/components@next @eva-design/eva@next react-native-svg --save

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    5.0.0-alpha.1    |
| @ui-kitten/components   |    5.0.0-alpha.1     |

## Environment information

```bash
  System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6308749
```

**Comment by artyorsh** [comment]
Card Header [was removed in v5](https://akveo.github.io/react-native-ui-kitten/docs/migration/4x500-migration#migrate-components), there is [no files missing in index](https://github.com/akveo/react-native-ui-kitten/blob/next/src/components/ui/index.ts#L42). Make sure you start with clearing cache.
Similar issue #997

**Comment by jaydotcom** [comment]
@artyorsh When I npm install the library, I got wrong "Modified date" and that's why I need to clean my cache.
You should have a look here to improve this : https://github.com/npm/npm/issues/20439
