### ISSUE TITLE
BottomNavigationBar is to far down

### ISSUE THREAD

**Issue by arthurliebhardt** [akveo/react-native-ui-kitten#1028]
The BottomNavigation is too far down as seen in my example [here](https://i.imgur.com/oDEX2B8l.png).
Do you have an advice what I'm doing wrong or does it depend on react navigation 5?

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      | 2.0.0-alpha.1       |
| @ui-kitten/components   |5.0.0-alpha.1         |

**Comment by artyorsh** [comment]
@arthurliebhardt you're missing [Safe Area](https://reactnative.dev/docs/safeareaview)

**Comment by arthurliebhardt** [comment]
@arthurliebhardt  thanks for your response, but when I add Safe Area around the navigation or app it just shows and white screen.

**Comment by arthurliebhardt** [comment]
@artyorsh didn't manage to get it work, tried Safe Area everywhere the bottomTabs don't move up. would love to use UI kitten for our app but this is a stopper for me.
