### ISSUE TITLE
Datepicker arrows not visible

### ISSUE THREAD

**Issue by exoer** [akveo/react-native-ui-kitten#1029]
## 🐛 Bug Report
The  _Datepicker_ upper right arrows/chevrons are missing. The buttons are there and clickable, but icons are not visible. 

## To Reproduce

`<Datepicker date={date} onSelect={(nextDate) => setDate(nextDate)} />`

<img width="433" alt="Screenshot 2020-04-15 at 19 18 44" src="https://user-images.githubusercontent.com/557371/79367354-04a01c80-7f4e-11ea-84bc-f772f94ad1e0.png">

I suspected that using multiple icon sets might mess up the datepicker icons 
`
      <IconRegistry
        icons={[
          EvaIconsPack,
          MaterialCommunityIconsPack,
        ]}
      />
`
But i tried to use only the EvaIconsPack and the result stayed the same. 

## Expected behavior

I expect that there are visible arrows/chevrons on the datepicker to page through the months and years.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    ^2.0.0-alpha.1    |
| @ui-kitten/components   |      "^5.0.0-alpha.1"    |

## Environment information
OSX, simulator and iPhone 6s

  System:
    OS: macOS 10.15.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 13.10.1 - /usr/local/bin/node
    Yarn: 1.22.0 - ~/.yarn/bin/yarn
    npm: 6.14.4 - ~/code/src/bitbucket.org/arnejenssen/7stride/sevenstride/node_modules/.bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  npmPackages:
    react: ~16.9.0 => 16.9.0 
    react-native: ~0.61.4 => 0.61.5 

```bash

```

**Comment by artyorsh** [comment]
@exoer is it? make sure to use `@ui-kitten/eva-icons` of v5. [See the snack](https://snack.expo.io/ihTQLb44l) confirming it works well

**Comment by exoer** [comment]
Thanks @artyorsh 
I had the right version of @ui-kitten/eva-icons, but I had the wrong version of 
`"react-native-svg": "^12.0.3",` when i use the version from your snack `"react-native-svg": "9.13.3"` the icons appear as expected.
