### ISSUE TITLE
'anchor' does not exist in Tooltip

### ISSUE THREAD

**Issue by huynhtastic** [akveo/react-native-ui-kitten#1030]
## 🐛 Bug Report

Typescript reports that the `anchor` prop does not exist on Tooltip.

## Expected behavior

For `anchor` to be a correct prop for Tooltip.

## Link to runnable example or repository (highly encouraged)

![image](https://user-images.githubusercontent.com/9666260/79396807-4d51d880-7f42-11ea-8114-155ef1d1fc10.png)

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    5.0.0-alpha.1    |
| @ui-kitten/components   |    5.0.0-alpha.1     |

**Comment by artyorsh** [comment]
Agreed. There’re lots of ts issues I realized myself in a real-world application. Will be solved in alpha.2 Thanks for reporting 👍

**Comment by huynhtastic** [comment]
I've run into a few other missing props for some other components as well. Would you like me to list those as well?

**Comment by artyorsh** [comment]
Sure. That’s would be a great help

**Comment by huynhtastic** [comment]
I was looking through my codebase, but the only one I could find again so far was that `Popover` is missing `backdropStyle`.

I can comment on this issue as I find more. Thanks for the help!

**Comment by artyorsh** [comment]
@huynhtastic installing [utility-types](https://github.com/piotrwitek/utility-types) solves most of the cases. You should install it as `devDependency` to solve this issue temporary.

The reason is that in v5 we moved to this library instead of defining common types ourselves.

**Comment by huynhtastic** [comment]
Ok great! Thanks for the heads up.

Is that in the documentation somewhere? I don't remember reading anything about installing utility-types as a dependency.

**Comment by artyorsh** [comment]
No it’s not. It seems I missed to notice that and now I’m thinking whether it’s ok for users to install this lib if we describe it or we should move back to own type system

**Comment by huynhtastic** [comment]
I think for now, it'd be best if you included it in your documentation so other won't run into this problem as long as you are still using utility-types.
