### ISSUE TITLE
Error after ejecting from Expo

### ISSUE THREAD

**Issue by garrett-gottlieb** [akveo/react-native-ui-kitten#1031]
## 🐛 Bug Report

After ejecting from Expo and replacing unavailable modules, I've narrowed this error to whenever I enable any ui kitten code (eg. Adding back my `<IconRegistry>` or creating the `<ApplicationProvider>` or rendering any other components like `<Layout>`, etc.

Here's the error:
```
[error][tid:com.facebook.react.JavaScript] Invariant Violation: No callback found with cbID 31431 and callID 15715 for module <unknown>. Args: '[1959]'
```

I'm wondering if there are any steps I'm missing in the migration. I've installed pods, and I have react-native-svg installed properly and I can render everything else in the app.

## Expected behavior

It should run without error.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    ^1.3.1    |
| @ui-kitten/components   |     4.4.0-beta.2    |

## Environment information

```bash
  System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
  Binaries:
    Node: 12.14.0 - /usr/local/bin/node
    Yarn: 1.19.1 - ~/.yarn/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27
      Build Tools: 19.1.0, 21.1.2, 23.0.1, 23.0.2, 23.0.3, 24.0.3, 25.0.0, 25.0.2, 26.0.2, 26.0.3, 28.0.2, 28.0.3
      System Images: android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  npmPackages:
    react: ~16.9.0 => 16.9.0
    react-native: ~0.61.4 => 0.61.5
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

**Comment by artyorsh** [comment]
@garrett-gottlieb sorry for the late reply.
UI Kitten has no common with Expo. Ejecting from it is a tricky process and it assumes you may have some issues.

> It should run without error.

I've tried ejecting and it worked for me. I don't actually know how I can reproduce that, but I dead sure this is just another one `clear cache and restart` issue. Is it still actual?

**Comment by garrett-gottlieb** [comment]
The issue was in the monorepo setup. I had to use the yarn workspaces `nohoist` with all UI Kitten repos.
