### ISSUE TITLE
Autocomplete async not found

### ISSUE THREAD

**Issue by DanteVR** [akveo/react-native-ui-kitten#1033]
Good morning, I am using the autocomplete component, when I make the request if it returns the data but does not render it in the view.

Also your example on the UI kitten website doesn't work.

https://akveo.github.io/react-native-ui-kitten/docs/components/autocomplete/examples#autocomplete

**Comment by artyorsh** [comment]
@DanteVR thanks for posting this

> Also your example on the UI kitten website doesn't work.

The issue was that the react-native blog was moved to the new domain, and we were using the old one, breaking this example. Changing the fetch url to `https://reactnative.dev/movies.json` made it work, I'll update it soon.

> it returns the data but does not render it in the view.

Could you please share the full code?
