### ISSUE TITLE
Drawer selected state

### ISSUE THREAD

**Issue by harryy2510** [akveo/react-native-ui-kitten#1034]
## 🐛 Bug Report

I think there should be a change in documentation

As per documentation,
![image](https://user-images.githubusercontent.com/7416971/79537194-658b3a00-809f-11ea-8daa-248e0469f2a6.png)

![image](https://user-images.githubusercontent.com/7416971/79537225-73d95600-809f-11ea-9c35-4767382b3b17.png)

But as I can see the interface required in selectedIndex should be an IndexPath. But react navigation returns a number in current index. It should changed to something like this
![image](https://user-images.githubusercontent.com/7416971/79537334-b13de380-809f-11ea-9b5b-381c9d3e45bc.png)

![image](https://user-images.githubusercontent.com/7416971/79537357-bef36900-809f-11ea-91ab-3aeb7a468ebf.png)

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    ^2.0.0-alpha.1    |
| @ui-kitten/components   |     ^5.0.0-alpha.1    |

## Environment information

```bash

  System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  Binaries:
    Node: 13.9.0 - ~/.nvm/versions/node/v13.9.0/bin/node
    Yarn: 1.22.4 - ~/.yvm/shim/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v13.9.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 27, 28
      Build Tools: 27.0.3, 28.0.3, 29.0.3
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  npmPackages:
    react: ~16.13.1 => 16.13.1 
    react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 

```

**Comment by artyorsh** [comment]
Yup. Thanks for reporting 👍
