### ISSUE TITLE
Fixed options when closing autocomplete

### ISSUE THREAD

**Issue by DanteVR** [akveo/react-native-ui-kitten#1036]
## 🐛 Bug Report

When closing the autocomplete component, the options remain stuck.

## To Reproduce

1.- We open the list of options.
2.- We go back to the previous screen.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2.0.0-alpha.1    |
| @ui-kitten/components   |     5.0.0-alpha.1    |

![screencast-Genymotion-2020-04-17_22 04 21 952](https://user-images.githubusercontent.com/16627238/79627066-d57ade00-80fa-11ea-8850-9ae11469dbea.gif)

![screenshot-2020-04-17_22 32 52 046](https://user-images.githubusercontent.com/16627238/79627144-81bcc480-80fb-11ea-83ed-fea5a390a855.png)

![screenshot-2020-04-17_22 32 58 803](https://user-images.githubusercontent.com/16627238/79627146-8a14ff80-80fb-11ea-9cee-09e0543ff860.png)

**Comment by artyorsh** [comment]
> Fixed options when closing

@DanteVR what I see from the gif is that actually it was closed. Do you mean the delay before became fully hidden?

**Comment by DanteVR** [comment]
> > Opciones fijas al cerrar
> 
> @DanteVR lo que veo del gif es que en realidad estaba cerrado. ¿Quieres decir que la demora antes se ocultó por completo?

Hi @artyorsh, what happens is that if I do not close the autocomplete and return to the previous screen, the autocomplete options remain on the screen as shown in the images.

**Comment by artyorsh** [comment]
@DanteVR use [BackHandler](https://reactnative.dev/docs/backhandler) + calling `hide` for autocomplete ref. I don't think this should be handled out of the box
