### ISSUE TITLE
Remove Padding From Card body Component

### ISSUE THREAD

**Issue by UqabSoft** [akveo/react-native-ui-kitten#1037]
## 💬 Question
Hello,
I am using the Card component and want to remove the padding of the card which is(paddingHorizontal:24, paddingVertical:16), But I am unable to do this. I lookup doc but found nothing.
Is there any way to change card Paddings?
Thanks,
Sarmad
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    1.4.0    |
| @ui-kitten/components   |    4.4.1     |

**Comment by DanteVR** [comment]
I think this is the answer to your question

https://akveo.github.io/react-native-ui-kitten/docs/design-system/customize-mapping#merge-mappings

**Comment by artyorsh** [comment]
It was discussed multiple times:
- #1020
- #1011  
- #1002

**Comment by iamadityaaz** [comment]
I have done multiple mapping for font-family and card 
```
{
  "strict": {
    "text-font-family": "Ubuntu-Regular"
  },
  "components": {
    "Card": {
      "appearances": {
        "outline": {
          "mapping": {
            "bodyPaddingHorizontal": -16,
            "bodyPaddingVertical": -16
          }
        }
      }
    }
  }
}

```
