### ISSUE TITLE
Is it possible to create chips?

### ISSUE THREAD

**Issue by joshbedo** [akveo/react-native-ui-kitten#1039]
I saw that Material is supported now for UI-Kitten and I was curious if it's possible to create chips? or if there are any plans for creating a component? These are super useful and common across applications now I personally need it for something I'm working on now. Thanks!

https://material.io/components/chips/#types

**Comment by artyorsh** [comment]
> I saw that Material is supported

You're wrong in giving such definition. Material is not supported, but with `@eva-design/material` _it's possible_ to create a _material-like_ application.
There is no plans for implementing more components in the near future. If you would like to see this component, please open a new issue using `feature proposal` template.

The easiest way to create a component you're looking for is to use a `small` or `tiny` Button + some border radius.
