### ISSUE TITLE
Button having only icon not working : accessoryLeft does not exist

### ISSUE THREAD

**Issue by LakshanKarunathilake** [akveo/react-native-ui-kitten#1041]
## 🐛 Bug Report

I am trying to create a icon button. But according to the documentation I have to provide accessoryLeft but it doesn't show up in the suggestions and when I try to compile it wont work also.

I get this error

TS2322: Type '{ accessoryLeft: (props: any) => Element; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<StyledComponentProps & ButtonProps, any, any>> & Readonly<...> & Readonly<...>'.   Property 'accessoryLeft' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<StyledComponentProps & ButtonProps, any, any>> & Readonly<...> & Readonly<...>'.

<img width="366" alt="Screenshot 2020-04-20 at 20 26 30" src="https://user-images.githubusercontent.com/33603053/79766398-9096b780-8345-11ea-81ab-fde2ee638319.png">

## To Reproduce

- Use sample code for icon button

## Link to runnable example or repository (highly encouraged)
https://akveo.github.io/react-native-ui-kitten/docs/assets/playground-build/#/ButtonGroupWithIcons

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |        |
| @ui-kitten/components   |  x       |

## Environment information

```bash
 System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.22.1 - ~/.yarn/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild

```

**Comment by artyorsh** [comment]
What versions of `@ui-kitten/components` and `@eva-design/eva` do you use?

**Comment by LakshanKarunathilake** [comment]
``
"@ui-kitten/components": "^4.4.1",
"@eva-design/eva": "^1.4.0",
``

I am using the latest

**Comment by artyorsh** [comment]
You using the latest but the documentation you use is for v5. See the switcher at the top.
![image](https://user-images.githubusercontent.com/10753921/79776683-c1bfb980-833e-11ea-8138-b98e3c738467.png)

**Comment by LakshanKarunathilake** [comment]
Okay, I got it, but by default shouldn't the documentation directly to the stable version. And I am eager to know will that kind of change occur in this library frequently?

**Comment by artyorsh** [comment]
@LakshanKarunathilake what kind of change?
