### ISSUE TITLE
Select don't work for me. Error while updating property 'tintColor' ... RNSVGSvgView

### ISSUE THREAD

**Issue by rosado-io** [akveo/react-native-ui-kitten#1042]
Hi Guys!

I'm work in a concept  with UI Kitten and I congratulate them on their great work, is very nice and cute. 

But, when trying to use Select  as explain in your documentation don't work for me, it sends me next error:
![Screenshot from 2020-04-20 16-42-17](https://user-images.githubusercontent.com/18620124/79802622-e9565800-8325-11ea-98d9-18620cd3051c.png)

Something I'm not doing well...
Any suggestion?

My dependencies are:

    "@eva-design/eva": "^2.0.0-alpha.1",
    "@ui-kitten/components": "^5.0.0-alpha.1",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-image-picker": "^2.3.1",
    "react-native-reanimated": "^1.8.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.5.0",
    "react-native-svg": "^12.1.0"

This is my code:

```ts
import {
    IndexPath,
    Layout,
    Select,
    SelectItem
} from '@ui-kitten/components';
import React from 'react';
import { StyleSheet } from 'react-native';

export const SelectScreen = () => {
    const [
        selectedIndex,
        setSelectedIndex
    ] = React.useState(new IndexPath(0));

    return (
        <Layout style={styles.container} level='1'>
            <Select
                selectedIndex={selectedIndex}
                onSelect={(index) =>
                    setSelectedIndex(index)
                }
            >
                <SelectItem title='Option 1' />
                <SelectItem title='Option 2' />
                <SelectItem title='Option 3' />
            </Select>
        </Layout>
    );
};

const styles = StyleSheet.create({
    container: {
        minHeight: 128
    }
});

```

**Comment by artyorsh** [comment]
Use react-native-svg 9.13.6

**Comment by arminghm** [comment]
Removing the link means the issue is not resolved in the PR and we can't use the latest version of RNSVG?

**Comment by artyorsh** [comment]
@arminghm no, it was duplicated for any reason

**Comment by arminghm** [comment]
@artyorsh Thanks
But I faced the issue with version `"react-native-svg": "^12.1.0"` of RNSVG and as you mentioned here, by changing it to `"react-native-svg": "^9.13.6"`, the problem is solved. Is it an issue with RNSVG?

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    ^2.0.0-alpha.1    |
| @ui-kitten/components   |   ^5.0.0-alpha.1     |

I'll try to reproduce it in a clean project to see if the issue still exists or not 👍

**Comment by artyorsh** [comment]
@atminghm no need. I’ve got this working with latest versions in linked PR, you may refer to it if interested in what was causing it
