### ISSUE TITLE
JSON value 't' of type NSString cannot be converted to a ABI37_0_0YGValue on Input, AutoComplete and AutoCompleteItem

### ISSUE THREAD

**Issue by LluisR** [akveo/react-native-ui-kitten#1045]
## 🐛 Bug Report

I am implementing Kitten UI to my current application and my surprise has come when I have been using one of the following components:
- Input
- AutoComplete
- AutoCompleteItem

In all cases, when I try to load any of these elements on a Screen, I get the following error:
JSON value 't' of type NSString cannot be converted to a ABI37_0_0YGValue. Did you forget the% or pt suffix?

## To Reproduce

Use any of the components mentioned above

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   2.0.0-alpha.1     |
| @ui-kitten/components   |    5.0.0-alpha.1     |

## Environment information

System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    npm: 6.13.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28, 29
      Build Tools: 29.0.3
      System Images: android-26 | Intel x86 Atom_64, android-27 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: ~16.9.0 => 16.9.0 
    react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1

```bash

```

**Comment by artyorsh** [comment]
@LluisR sorry for the late reply. Is it still actual?
If so, could you please provide the full code where the components are used? Having a reproducible demo is also a good option here, you can create one on [snack](https://snack.expo.io/@ui-kitten/playground).
