### ISSUE TITLE
Notice where to get support

### ISSUE THREAD

**Issue by xstable** [akveo/react-native-ui-kitten#1046]
Would be really nice to have a notice - here (in Readme.md) and in you Webpage - where to get support for this Library. 
Like each other good opensource Software, a community will build up around UI-Kitten. So they come together to ask, help and show their work... maybe on on Slack, Discord, or a Forum-Page.

I think it would massively increase the distribution of ui-kitten (btw. an awesome ui-kit), if you provide a general place, where people can get (Community)-Support for the UI.

I suggest to create an slack or Discord-Group, but I'm open for other solutions.. as long there will be one.

**Comment by xstable** [comment]
I've found now, that you have a notice at the bottom of the Documentation-Page:
![image](https://user-images.githubusercontent.com/1778068/79988629-2863e500-84af-11ea-8382-5bf3d1548a37.png)

Notice: there is no _'ui-kitten'_ tag at all used on stackoverflow. Only Tag is `react-native-ui-kitten`.

On the other hand, I still recommend to have something like a community-chat to point users on a single place to help instantly each other (like slack or discord)

**Comment by ivanubi** [comment]
Agree, I think a pinned issue called 'Ask for Support' would be good as well.

**Comment by artyorsh** [comment]
@xstable thanks for having such interest. Having community-open channels like discord, slack (whatever else) is not the thing we can do, since this requires a lot of time efforts to keep it alive :)
This _is_ under our internal discussion sometimes, and I hope we will have it some day.

> there is no 'ui-kitten' tag at all used on stackoverflow

Thanks for the notice. We'll update the tag 👍 

@ivanubi 
> pinned issue called 'Ask for Support'

Haven't seen that in other repositories. I believe that this will become a huge mess the first day it is opened 😄

**Comment by xstable** [comment]
@artyorsh I don't think so... that it's takes much time from your side.
I see it in other Projects (own ones and open-source). You only need to generate a centralized place where the community come together.

You don't have to put all the time new content to this group, you only have to provide the structure (like some chat-channels). Automatically all the community-members will fill this sections with life.

The main Point is to generate a "official" Place where Community-Members can meet.
If only a ui-kitten-user starts such a channel, it might spreaded up over different Messanger-Types (some prefer slack, otherones Discord... and so on). 

So all you have to do is following (would love if you could give it a try... I think it will boots usage of ui-kitten... because Support is one of the most important things for a Software!): 

1. Create A Slack or Discord Channel (for free)
2. Notice at the Documentation-Page that this is official *Community*-Support-Chat.
3. Let it fill with life fully automated by the community 


If you don't have interest or time to moderate such a group, choose a well known contributor who like to be a moderator of such a group. But again. it is nearly no work to setup or moderate such a group. 

*BTW:* I like slack, because it has nice integrations with other Services. For example you can create a News-Channel and automatically connect it to your git-repo to anounce if new Push appears to the Master-Repo.

If you wan't to start it, I can give you helping hands, if needed.

**Comment by artyorsh** [comment]
@xstable would like to have a quick discussion on this in twitter :)
Can we? Please contact me with the link in my bio if yes

**Comment by lesmo** [comment]
I've seen it naturally happens here in the issues that people ask for questions, and some of us try to answer (including the maintainers) - this is usually what I've seen happening on most repos. I think it's a bit easier.

I like the idea of _another_ place, but personally I've never actually used any of them. I usually forget... the cool thing about GitHub is that it's the same place I use for work, so it's easier to check from time to time. Perhaps Slack might be the same for me.

**Comment by malashkevich** [comment]
Hello @lesmo,
Sorry for such delay.

I would say that it's better to stick to the web. The reason is simple - any question could be googled.
For bugs / proposals - GitHub
For questions - SO

If there are already some Slack / Discord / etc group where people are discussing UI Kitten we can put a link on it in docs. But there are no plans to "officially" run the channel.

**Comment by lesmo** [comment]
@malashkevich may I suggest [Github Discussions](https://docs.github.com/en/discussions)?

**Comment by malashkevich** [comment]
@lesmo I don't see any reason to not enable it :)
Thanks for suggestion!
