### ISSUE TITLE
Unable to resolve module `./style/styleConsumer.component`

### ISSUE THREAD

**Issue by madun** [akveo/react-native-ui-kitten#1052]
## 🐛 Bug Report

Hai, i've try to migrating from 4.* to 5 version, i had some problem when i rerun react-native run-android. i do read the documentation migrating from your site, then the result is like this :

<img width="682" alt="image" src="https://user-images.githubusercontent.com/5608541/80283269-8824ef00-8740-11ea-9a53-77d02dc3c796.png">

<img width="490" alt="image" src="https://user-images.githubusercontent.com/5608541/80283289-a4289080-8740-11ea-8214-92c849175546.png">

I've tried running 

> rm -rf ./node_modules ./package-lock.json && npm i

but still not working for me
Thanks before 👍 

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2.0.0-alpha.1    |
| @ui-kitten/components   |    5.0.0-alpha.1     |

## Environment information
System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 23.0.1, 28.0.3, 29.0.2
      System Images: android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.3/11C24b - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by Photonios** [comment]
Have you tried to restart the bundler with the `--reset-cache` flag? I suspect Metro's cache is holding onto an older version of UI kitten.

https://medium.com/@abhisheknalwaya/how-to-clear-react-native-cache-c435c258834e

There is no reference to `styleConsumer.component` anywhere in the code base.

**Comment by madun** [comment]
Okay, thanks for your response. it works 👍

**Comment by Photonios** [comment]
No problem :-)

Please close the issue then.
