### ISSUE TITLE
Module parse failed input.component.js 104:38

### ISSUE THREAD

**Issue by marvinrabe** [akveo/react-native-ui-kitten#1054]
## 🐛 Bug Report

Running v5.0.0-alpha.1 with react native web. The application build fails:

```
/node_modules/@ui-kitten/components/ui/input/input.component.js 104:38
Module parse failed: Unexpected token (104:38)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|         this.webEventResponder = devsupport_1.WebEventResponder.create(this);
|         this.focus = () => {
>             this.textInputRef.current?.focus();
|         };
|         this.blur = () => {
```

It looks like optional chaining is not supported.

## To Reproduce

Steps to reproduce the behavior: Probably nothing special. Run any app on web.

## Expected behavior

Successful build. 

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   5.0.0-alpha.1     |
| @ui-kitten/components   |    2.0.0-alpha.1     |

## Environment information

```bash
  System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 13.12.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  npmPackages:
    react: ~16.9.0 => 16.9.0 
    react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
```

**Comment by artyorsh** [comment]
Consider looking through the discussion in [that issue](https://github.com/akveo/react-native-ui-kitten/issues/996), there is a workaround on this.
