### ISSUE TITLE
Select component not found

### ISSUE THREAD

**Issue by DanteVR** [akveo/react-native-ui-kitten#1056]
## 🐛 Bug Report

I'm following the exact same example of the Select component found in your documentation, but it shows the following error while rendering.

Use version 12.1.0 -> react-native-svg

## To Reproduce

Use the select component in the view

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2.0.0-alpha.1   |
| @ui-kitten/components   |    5.0.0-alpha.1    |

![image](https://user-images.githubusercontent.com/16627238/80291881-1ab09880-8717-11ea-9a20-0747fdc257ca.png)

**Comment by DiegoSeC** [comment]
I had the same error, so I changed my SVG version to `"react-native-svg": "9.13.3"` and everything was working as expected. For more info: https://github.com/akveo/react-native-ui-kitten/issues/1005#issuecomment-615391364

**Comment by artyorsh** [comment]
@DanteVR use the workaround suggested with link shared by @DiegoSeC. The latest react-native-svg versions will be supported in the next release. ([commit](https://github.com/akveo/react-native-ui-kitten/pull/1055/commits/ff9ada3403d54c6bb1a1e17a2026d1d9240cbc48))

**Comment by DanteVR** [comment]
> Tuve el mismo error, así que cambié mi versión SVG a `"react-native-svg": "9.13.3"`y todo funcionaba como se esperaba. Para más información: [# 1005 (comentario)](https://github.com/akveo/react-native-ui-kitten/issues/1005#issuecomment-615391364)


I made the change to react-native-svg@9.13.3 however now I am getting the following error, I have already run npm cache clean --force however the error persists

![image](https://user-images.githubusercontent.com/16627238/80314660-72531080-87b8-11ea-9c15-30e7dc6d7b0a.png)

**Comment by wesleylq** [comment]
> > Tuve el mismo error, así que cambié mi versión SVG a `"react-native-svg": "9.13.3"`y todo funcionaba como se esperaba. Para más información: [# 1005 (comentario)](https://github.com/akveo/react-native-ui-kitten/issues/1005#issuecomment-615391364)
> 
> I made the change to react-native-svg@9.13.3 however now I am getting the following error, I have already run npm cache clean --force however the error persists
> 
> ![image](https://user-images.githubusercontent.com/16627238/80314660-72531080-87b8-11ea-9c15-30e7dc6d7b0a.png)

Happend the same for me here :/

**Comment by wesleylq** [comment]
> > Tuve el mismo error, así que cambié mi versión SVG a `"react-native-svg": "9.13.3"`y todo funcionaba como se esperaba. Para más información: [# 1005 (comentario)](https://github.com/akveo/react-native-ui-kitten/issues/1005#issuecomment-615391364)
> 
> I made the change to react-native-svg@9.13.3 however now I am getting the following error, I have already run npm cache clean --force however the error persists
> 
> ![image](https://user-images.githubusercontent.com/16627238/80314660-72531080-87b8-11ea-9c15-30e7dc6d7b0a.png)

The same thing happened to me :/

**Comment by josef256** [comment]
> > Tuve el mismo error, así que cambié mi versión SVG a `"react-native-svg": "9.13.3"`y todo funcionaba como se esperaba. Para más información: [# 1005 (comentario)](https://github.com/akveo/react-native-ui-kitten/issues/1005#issuecomment-615391364)
> 
> I made the change to react-native-svg@9.13.3 however now I am getting the following error, I have already run npm cache clean --force however the error persists
> 
> ![image](https://user-images.githubusercontent.com/16627238/80314660-72531080-87b8-11ea-9c15-30e7dc6d7b0a.png)


 go to your **metro.config.js** file & add **'tsx'** to  sourceExts

something like this 
`    sourceExts: [...defaultConfig.resolver.sourceExts, 'svg', 'tsx'],`

also im using version **9.13.6** of react-native svg but it should also work with v**9.13.3**
