### ISSUE TITLE
ViewPager do not switch slides

### ISSUE THREAD

**Issue by sergeykuzmich** [akveo/react-native-ui-kitten#1061]
## 🐛 Bug Report

ViewPager component always shows first to second slide animation

## To Reproduce

Try the example on the reference website https://akveo.github.io/react-native-ui-kitten/docs/components/view-pager/overview#viewpager

## Expected behavior

Slides should switch one by one.

## Link to runnable example or repository (highly encouraged)

https://akveo.github.io/react-native-ui-kitten/docs/components/view-pager/overview#viewpager
This will help us to resolve it faster.
-->

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @ui-kitten/components   |   5.0.0-alpha1      |

## Environment information
```bash
System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
  Binaries:
    Node: 13.11.0 - ~/.nvm/versions/node/v13.11.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v13.11.0/bin/yarn
    npm: 6.13.7 - ~/.nvm/versions/node/v13.11.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
```

**Comment by artyorsh** [comment]
@sergeykuzmich thanks for reporting! Made it work with [#8493e99](https://github.com/akveo/react-native-ui-kitten/pull/1055/commits/8493e990f1f11e84dbd821456ef994e1cb5f44eb)

**Comment by sergeykuzmich** [comment]
@artyorsh, hm, I've tried this but didn't get the expected result. Maybe there was some cache.
But anyway, thank you!

**Comment by artyorsh** [comment]
@sergeykuzmich as a workaround, you may get it work by setting `onOffsetChange` property

**Comment by terrierscript** [comment]
I got same error. Is this resolved?

**Comment by artyorsh** [comment]
@terrierscript works as expected in v5 stable

**Comment by terrierscript** [comment]
hmm, I use v5.0.0.
I got this error when append over 3 elements.
