### ISSUE TITLE
DatePicker goes off the screen

### ISSUE THREAD

**Issue by arminghm** [akveo/react-native-ui-kitten#1062]
## 🐛 Bug Report

![Screenshot_20200503-234434](https://user-images.githubusercontent.com/11267514/80923466-424bd480-8d99-11ea-8dcf-54e04ad4ae85.png)

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   ^2.0.0-alpha.1     |
| @ui-kitten/components   |    ^5.0.0-alpha.1     |

```bash

```

**Comment by artyorsh** [comment]
@arminghm datepicker has always a fixed width and can't be smaller by design, use `placement` property to setup it more accurately

**Comment by PrateekGoyal18** [comment]
I have given a `styles.pcicker` class to `DatePicker` like this:
```
picker: {
    marginHorizontal: wp('3%'),
    width: wp('40%'),
},
```
In my case, the datepicker modal is kinda overflowing out the screen, it there anyway to stop this?
