### ISSUE TITLE
"Giant" Button not Appearing

### ISSUE THREAD

**Issue by destinybonavita** [akveo/react-native-ui-kitten#1063]
## 💬 Question

I'm trying to add a simple button using the Facebook Icon but it's not appearing. 
I was using [this](https://github.com/akveo/kittenTricks/blob/503496eb36bf7f8ec5c030001d0433f5a92ef31d/src/layouts/auth/sign-in-4/index.tsx#L102) as a reference for designing a page, but I can't seem to get the social icons setup. I also setup my project using `npx react-native init MyApp --template @ui-kitten/template-js` so I think most things are setup correctly. 

I marked this as a question because I do not think this is a bug, just me being a slow learner.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   2.0.0-alpha.1     |
| @ui-kitten/components   |    5.0.0-alpha.1     |

**Comment by artyorsh** [comment]
You run v5, but the code you're trying to run is v4. See [the docs](https://akveo.github.io/react-native-ui-kitten/docs/components/button/overview#button) or [what's changed](https://akveo.github.io/react-native-ui-kitten/docs/?p=/migration/4x500-migration#4x--500-ui-kitten-migration)
