### ISSUE TITLE
add testID on Calendar

### ISSUE THREAD

**Issue by jbtheard** [akveo/react-native-ui-kitten#1065]
## 💬 Question
Is there any way we can/could access navigation elements such as CalendarMonthHeader via their testID? My end to end tests require navigation before date selection.
Note that adding testID to the dayCell themselves is OK with the renderCell method.

I guess the question/suggestion could be extended to most of the components regarding a default testID...

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |     2.0.0-alpha.1   |
| @ui-kitten/components   |    5.0.0-alpha.1     |

**Comment by artyorsh** [comment]
Yes, there is, but it depends on testing library you use. We didn't add testID's, and internally use [react-native-testing-library query api](https://callstack.github.io/react-native-testing-library/docs/api-queries)

**Comment by moxspoy** [comment]
we can test this library using Detox (our E2E testing library)
