### ISSUE TITLE
Closing the calendar after onSelect event on Datapicker

### ISSUE THREAD

**Issue by simonsankar** [akveo/react-native-ui-kitten#1066]
## 💬 Is there a way close the calendar after an onSelect event on the Datepicker component?

I'd like to close the calendar after the `onSelect` event is triggered. Is this possible somehow?
Thanks!

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      | ^2.0.0-alpha.1 |
| @ui-kitten/components   | ^5.0.0-alpha.1 |

**Comment by artyorsh** [comment]
@simonsankar I tried to achieve the same by ref methods, but it seems buggy for now, and calendar still visible. Will include this in stable release #1055. Thnaks for posting!

**Comment by interstellarbox** [comment]
@simonsankar 
This one works for me
```
ref={datepicker}
onSelect={nextDate => {
...
datapicker.current.blur();
}}
```

**Comment by artyorsh** [comment]
Starting from the stable release this will become a default behavior
