### ISSUE TITLE
Select and Datepicker textStyle prop

### ISSUE THREAD

**Issue by interstellarbox** [akveo/react-native-ui-kitten#1068]
Hi, I need help with styling the Select and Datepicker inputs.
I use "@ui-kitten/components": "^5.0.0-alpha.1",

the textStyle prop works perfectly for the Input component but I can't find the way to style a text for the Select and Datepicker inputs. 

I see that this prop exists in the component source code 

```
export interface SelectProps extends StyledComponentProps, TouchableOpacityProps {
  ...
  textStyle?: StyleProp<TextStyle>;
...
```
but it doesn't work for me.

My example 
```
<Select
            value={displayValue}
            selectedIndex={selectedIndex}
            onSelect={index => {
                setSelectedIndex(index)
                dispatch(...)
            }}
            textStyle={{
                fontSize: 30
            }}
        >
            {data.map((option, index) => <SelectItem key={index} title={option} />)}
</Select>
```

I'm not sure, is it a bug or I'm doing wrong something but what will be the correct way to change text size and height for that inputs? 

The size="large" prop is not big enough for tablets

Thank you

**Comment by artyorsh** [comment]
@interstellarbox we removed such properties in v5, since it not gives you complete flexibility in styling. In v5 this is solved by passing string, numbers _or function components_ to the corresponding properties. See the API tab, and [example](https://snack.expo.io/yp2BOtSFn).

**Comment by interstellarbox** [comment]
@artyorsh Great, it works! Thank you got the answer
