### ISSUE TITLE
Button onPress not being fired until second press

### ISSUE THREAD

**Issue by thehappydinoa** [akveo/react-native-ui-kitten#1069]
## 🐛 Bug Report

I am currently using a button that makes me click it twice.

## To Reproduce

```js
<Button style={styles.button} onPress={handleSubmit(onLogin)}>
      Login
</Button>
```

`handleSubmit` is from the `react-hook-form` library.

## Expected behavior

Button to run `handleSubmit` the first time it is pressed

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    ^2.0.0-alpha.1    |
| @ui-kitten/components   |    ^5.0.0-alpha.1     |

## Environment information

```bash

  System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
  Binaries:
    Node: 13.12.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 15, 23, 24, 26, 27, 28, 29
      Build Tools: 22.0.1, 24.0.1, 27.0.3, 28.0.3, 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

**Comment by artyorsh** [comment]
This is not reproducible when following a `Getting Started` example from the [react-hook-form docs](https://react-hook-form.com/get-started#Quickstart). [See the snack](https://snack.expo.io/rrdVu5obV).

**Comment by mortenmo** [comment]
I'm seeing this same issue (with UI Kitten 5, Expo 37). I'll try and make a simpler repo

**Comment by artyorsh** [comment]
@mortenmo the Snack runs Expo SDK 37 and UI Kitten v5
