### ISSUE TITLE
v5 - Dynamic Icon Rendering

### ISSUE THREAD

**Issue by sidpagariya** [akveo/react-native-ui-kitten#1072]
## 💬 Question
Hi there, I was trying to do change the icon on a button dynamically, and previously in v4 this seemed to work:
```
const renderIcon = (name: string, styles: any) => (
  <Icon {...styles} name={name} />
);
const ButtonIcon = () => renderIcon('info');
```

And in the button's `icon` attribute, I  used to just set it to be `ButtonIcon`.

Now, when I set the button's `accessoryLeft` attribute to `ButtonIcon` the icon doesn't seem to show up. I have to manually declare each icon as follows:
```
const InfoIcon = (props: any) => (
  <Icon {...props} name='info' />
);
```
And then I can set the button's `accessoryLeft` attribute to `InfoIcon`.

With v5 that icon doesn't seem to be showing up and I was wondering what might possibly be going wrong...

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    5.0.0-alpha1    |
| @ui-kitten/components   |    5.0.0-alpha1     |

**Comment by artyorsh** [comment]
Hi 👋
Looks like you omit props passed to `ButtonIcon`. [See the snack](https://snack.expo.io/@ui-kitten/playground) for better understanding.
