### ISSUE TITLE
Icon Margins & Paddings

### ISSUE THREAD

**Issue by destinybonavita** [akveo/react-native-ui-kitten#1075]
## 💬 Question

I'm using `react-native-vector-icons/FontAwesome` for a few icons but there seems to be some padding on both sides. I've tried to remove it manually but I've been had little luck. Is there any padding in the icon component or settings to remove it? 

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    ^4.4.1    |
| @ui-kitten/components   |    ^5.0.0-alpha.1     |

**Comment by artyorsh** [comment]
@destinybonavita in some cases it's controlled by Eva, but you can override it. Could you please provide the full code?

**Comment by destinybonavita** [comment]
Sure!

Icon Registry
```javascript
import React from 'react';
import { StyleSheet } from 'react-native';
import Icon from 'react-native-vector-icons/FontAwesome';

export const FontAwesomeIconsPack = {
    name: 'fontAwesome',
    icons: createIconsMap(),
};

function createIconsMap() {
    return new Proxy({}, { get(target, name) { return IconProvider(name); }, });
}

const IconProvider = (name) => ({ toReactElement: (props) => FontAwesome({ name, ...props }), });

function FontAwesome({ name, style }) {
    const { height, tintColor, ...iconStyle } = StyleSheet.flatten(style);
    return (
        <Icon name={name} size={height} color={tintColor} style={iconStyle} />
    )
}
```

Usage: 
```javascript
import PropTypes from "prop-types"
import React, { Component } from 'react'
import { View, Text } from "react-native";
import { Icon } from "@ui-kitten/components";

export default function IconWithBadge({ name, badgeCount, icon, pack, color, size }) {
    size = 30

    return (
        <View style={{ width: size, height: size }}>
            <Icon name={icon} pack={pack} style={{ width: size, height: size, tintColor: color }} ironStyle={{ marginRight: 0, marginLeft: 0 }} tintColor={color} />
            {badgeCount && badgeCount > 0 && (
                <View style={{ position: 'absolute', right: -6, top: -3, backgroundColor: 'red', borderRadius: 6, width: 15, height: 15, justifyContent: 'center', alignItems: 'center' }}>
                    <Text style={{ color: 'white', fontSize: 10, fontWeight: 'bold' }}>
                        {badgeCount}
                    </Text>
                </View>
            )}
        </View>
    );
}
```

**Comment by artyorsh** [comment]
@destinybonavita what do you expect with usage of `ironStyle`? Margins and paddings are not controlled by the icon itself, but only when using as nested component. In your case there is no UI Kitten issue, but I guess you should check [vector-icons reference](https://github.com/oblador/react-native-vector-icons#icon-component). Each prop except `name` will be passed to the Icon from the package you're using.

**Comment by destinybonavita** [comment]
I just realized the spelling mistake I had there, it was supposed to be `iconStyle` not `ironStyle` 
I'll see if fixing that would fix the padding. If not, i'll contact [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons#icon-component) for more assistance to see if it's on their end. Thanks!
