### ISSUE TITLE
TabView Text Color

### ISSUE THREAD

**Issue by destinybonavita** [akveo/react-native-ui-kitten#1079]
## 💬 Question

How do I change the text color of `Tab` components within a `TabView` component? For some reason the title text is black on both dark and light modes. The primary color for both dark and light mode is white so I'm not sure why it's showing the text as black.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    ^2.0.0-alpha.1    |
| @ui-kitten/components   |    ^5.0.0-alpha.1     |

**Comment by artyorsh** [comment]
@destinybonavita 3 options:

1. As per the example in the docs
> Tab and it's inner views can be styled by passing them as function components.
In most cases this is redundant, if [custom theme is configured](https://akveo.github.io/react-native-ui-kitten/docs/guides/branding).



```js
import { Tab, Text } from '@ui-kitten/components';

<Tab
  title={evaProps => <Text {...evaProps}>USERS</Text>}
/>
```
2. As per the note below that example
> In most cases this is redundant, if [custom theme is configured](https://akveo.github.io/react-native-ui-kitten/docs/guides/branding).

You probably want to change this color everywhere, don't you?

3. By using [custom mapping](https://akveo.github.io/react-native-ui-kitten/docs/design-system/customize-mapping#customize-component-mapping), if the options above don't cover your case

**Comment by destinybonavita** [comment]
I have a custom theme set, and it works fine for everything except `Tab`
Is there a specific theme name used for `Tab`?

**Comment by destinybonavita** [comment]
In order to get the above working, `text-hint-color` and `text-primary-color` is needed to be added to your custom theme. I think the documentation should be updated to reflect this.

**Comment by artyorsh** [comment]
@destinybonavita tab relies on `text-hint-color` in its default state, and becomes `text-primary-color` when active.

> I think the documentation should be updated to reflect this.

This rule worked perfectly in several projects I worked on. In case you need a specific rule for that component, you may use mapping customization feature (option 3), or configure `basic` palette more accurately so that `text-hint-color` will refer to another color value.
