### ISSUE TITLE
Change text color of Tab active in TabView ?

### ISSUE THREAD

**Issue by chipcop106** [akveo/react-native-ui-kitten#1080]
I want to change text color of active Tab in TabView. Document only have props to change Indicator and TabView style. Is there any way to do this ?

https://akveo.github.io/react-native-ui-kitten/docs/components/top-tabs/api#tabview

Sorry for my bad English...

## UI Kitten and Eva version
Version: 5.0.0-alpha.1

**Comment by artyorsh** [comment]
Duplicates #1079
