### ISSUE TITLE
JS file support for custom mappings with metro

### ISSUE THREAD

**Issue by RWOverdijk** [akveo/react-native-ui-kitten#1083]
Based on [this comment](https://github.com/zeit/next.js/issues/12481#issuecomment-627843277)

## 🚀 Feature Proposal

It's already possible to use JS based mappings. It's what we're currently doing to keep things organized (without it UI Kitten's system would be far less appealing).

However, [using it with metro for performance boost](https://akveo.github.io/react-native-ui-kitten/docs/4.x/guides/improving-performance#improving-performance) doesn't work, it requires JSON.

## Motivation

Having one massive JSON file is not really an option. The reason myself (and team) enjoy working with the eva system so much is because of the way we can bundle mappings with our components. Our custom mapping file more or less looks like this (left most out to keep it short):

```js
import QuantityStepper from '../components/QuantityStepper/mapping'
import ExpansionPanel from '../components/ExpansionPanel/mapping'

export default {
  components: {
    QuantityStepper,
    ExpansionPanel,
  }
}
```

This means our mappings are nice and only as tall as they need to be.

**Example mapping.js:**

```js
export default {
  meta: {
    scope: 'all',
    parameters: {},
    variantGroups: {},
    states: {},
    appearances: {
      default: {
        default: true
      }
    }
  },
  appearances: {
    default: {
      mapping: {}
    }
  }
}
```

## Example

It already works with js-based mappings, only the metro config doesn't like it yet.

**Comment by artyorsh** [comment]
@RWOverdijk the only issue feels like a blocker to me is that we should watch for mapping file changes to run generation scripts and reload the app whenever you change the mapping. 

I’m not sure it’s easy enough to integrate for multiple files, but if you have any ideas on this, let’s discuss it in a more details 👍

**Comment by RWOverdijk** [comment]
@artyorsh I understand. I personally wouldn't mind it doing that on changes to the main file only initially, I guess it's a trade-off. Or maybe it should only be used for production builds, and dev just doesn't (if provided mapping isn't JSON). I know it's not as pretty, but at least it keeps working for dev and remains optimised for builds?

**Comment by RWOverdijk** [comment]
New year, new me 😂 

I have created my own metro config based on the ui-kitten one. It bundles all the mapping.json files into one, and writes it to cache using js instead of json (to skip that json parse step).

Couple of restrictinos:

1. It only works with eva-design (minor tweak of course if this proves to be useful).
2. It only works with watchman installed (pending a response [on this issue](https://github.com/facebook/metro/issues/673)).
3. It doesn't have a run-once implementation yet. I'm planning on adding that later this week.

```js
const { getDefaultConfig } = require('@expo/metro-config');
const merge = require('lodash.merge');
const path = require('path');
const fs = require('fs/promises');
const { SchemaProcessor } = require('@eva-design/processor');

const generatedStylesExport = `\n\nexports.styles = require('./generated')`;
const evaBaseDir = path.resolve(__dirname, 'node_modules', '@eva-design', 'eva');
const generatedPath = path.join(evaBaseDir, 'generated.js');
const indexPath = path.join(evaBaseDir, 'index.js');
const schemaProcessor = new SchemaProcessor();
const mappings = {
  __default_mapping: require(path.join(evaBaseDir, 'mapping.json')),
};

async function updateCache(files) {
  await Promise.all(files.map(async f => {
    const { name, exists } = typeof f === 'string' ? { name: f, exists: true } : f;

    if (exists) mappings[name] = JSON.parse(await fs.readFile(name, 'utf8'));
    else delete mappings[name];
  }));

  const styles = schemaProcessor.process(merge({}, ...Object.values(mappings)));

  await Promise.all([
    // Write the generated styles to file
    fs.writeFile(generatedPath, 'module.exports = ' + JSON.stringify(styles)),

    // Make sure the styles are exported.
    new Promise(async r => {
      const contents = await fs.readFile(indexPath, 'utf8');

      if (!contents.includes(generatedStylesExport)) {
        await fs.writeFile(indexPath, contents + generatedStylesExport, 'utf8');
      }

      r();
    })
  ]);
}

function setupWatchers() {
  const watchman = require('fb-watchman');
  const client = new watchman.Client();
  const dir = path.resolve(__dirname, 'src');
  const WATCHER_NAME = 'kitten-styles-watcher';

  function die(error) {
    if (!error) return;

    client.end();

    throw new Error(error);
  }

  return new Promise(r => {
    client.capabilityCheck({ optional: [], required: ['relative_root'] }, error => {
      if (error) die(error);

      client.command(['watch-project', dir], (error, { warning, watch, relative_path }) => {
        if (error) die(error);
        if (warning) console.warn('warning: ', warning);

        // Query initial files
        client.command(['query', __dirname, {
          'glob': ['src/**/mapping.json'],
          'fields': ['name']
        }], async (error, { files }) => {
          if (error) die(error);

          await updateCache(files);

          r(); // Cache has been initialized, let's get ready to bundleeeee.
        });

        // Create a subscription for changes on mapping.json files
        client.command(['subscribe', watch, WATCHER_NAME, {
          expression: ['allof', ['match', 'mapping.json']],
          fields: ['name', 'exists', 'type']
        }], die);

        // Listen for updates to the files we're interested in.
        client.on('subscription', ({ subscription, files, is_fresh_instance }) => {
          if (is_fresh_instance || subscription !== WATCHER_NAME) return;

          return updateCache(files);
        });
      });
    });
  });
}

const create = async () => {
  await setupWatchers();

  return getDefaultConfig(__dirname);
};

module.exports = create();
```

**Comment by RWOverdijk** [comment]
I've built my own ui library.
