### ISSUE TITLE
Improve TypeScript hinting for props with know string literals

### ISSUE THREAD

**Issue by hrastnik** [akveo/react-native-ui-kitten#1084]
## 🚀 Feature Proposal

It's possible to get better TypeScript hinting for props like `category` and `appearance` on the Text component by using a this trick:
https://github.com/microsoft/TypeScript/issues/29729#issuecomment-505826972

It basically comes down to using a union type

```
type Category = ('h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6') | (string & {})

const category1: Category = "h1" // works
const category2: Category = "whatever" // also works 
```

## Motivation

Implementing this small change would enable developers to have better intellisense support in their editors.

**Comment by artyorsh** [comment]
@hrastnik thanks for the proposal. It looks like we have it working properly already, don’t we?
I don’t experience any intellisense issues when using WebStorm / VS Code

**Comment by hrastnik** [comment]
I don't get recommendations for "h1" "h2" etc. Is there something wrong in my config?

**Comment by lesmo** [comment]
> @hrastnik thanks for the proposal. It looks like we have it working properly already, don’t we?
> I don’t experience any intellisense issues when using WebStorm / VS Code

I haven't tested it, but [the code already contains these typings](https://github.com/akveo/react-native-ui-kitten/blob/master/src/components/ui/text/text.component.tsx#L30). I'm guessing @hrastnik is using v4, I remember back then those typings were missing but I didn't miss them enough to open an issue 😅

**Comment by hrastnik** [comment]
The code contains the typings in the form

`type Category = "h1" | string`

In TS, this is equivalent to type `string` so no hint is provided.

Check the linked thread from the issue.

**Comment by artyorsh** [comment]
@hrastnik hm, yep. It doesn't seem to work in VS Code, sorry for the wrong info :) I guess WebStorm does some internal magic on this.

![image](https://user-images.githubusercontent.com/10753921/82216666-f31dac00-9921-11ea-8e16-2359873198cb.png)

Your solution works pretty well, thanks for pointing!
Would you like to open a PR on this? It would be nice to do the same for the properties of other components.

**Comment by lesmo** [comment]
Hey! Great find! I guess WebStorm is using a different TS engine? I stopped using it a very long time ago 😅
