### ISSUE TITLE
Top, Bottom, and "Side" Navigation

### ISSUE THREAD

**Issue by destinybonavita** [akveo/react-native-ui-kitten#1085]
## 💬 Question

Is there any examples of having a nav bar on the top, bottom, and "side" that opens with a hamburger menu? 

I'm trying to add bottom, top, and side nav options to my application but I can't find any recent examples.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |        |
| @ui-kitten/components   |         |

**Comment by artyorsh** [comment]
@destinybonavita yes - https://github.com/artyorsh/react-navigation-ex-demo

**Comment by destinybonavita** [comment]
Thanks so much for your reply! 
I figured out how they're doing it but I'm not sure if that's the best solution for my project. 

How I understand it they're doing it like this
```
--- Hamburger Menu
------Bottom Tab
---------Top Tab
```

However, my app I'm planning on using the combination of all three menu types through out the whole app. Would it make sense to reuse that much code?

**Comment by destinybonavita** [comment]
Attempting to implement the above actually isn't working because of the fact that each layer will change what page is currently shown, so that would be fighting with itself a lot.
