### ISSUE TITLE
Select component not working

### ISSUE THREAD

**Issue by evolvan** [akveo/react-native-ui-kitten#1087]
## 🐛 Bug Report
On Mobile, Select component not working. When I tried to use it. It returns following error 

> JSON value '#8F9BB3' of type NSString cannot be converted to a UIColor. Did you forget to call processColor() on the JS side?
> 
> +[RCTConvert UIColor:]
>     RCTConvert.m:532
> -[RNSVGSvgViewManager set_tintColor:forView:withDefaultView:]
> 

## To Reproduce

Just import Select component and use it. You can see error right in simulator.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   ^2.0.0-alpha.1     |
| @ui-kitten/components   |    ^5.0.0-alpha.1     |
| react-native-svg   |    ^12.1.0     |

## Environment information

```
  System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
```

**Comment by artyorsh** [comment]
duplicates #1077 #1056 #1042 #1005 and became resolved in v5 stable.

**Comment by josef256** [comment]
> You should upgrade to stable.
> duplicates #1077 #1056 #1042 #1005 and became resolved in stable release.

 still has the same issue with react-native-svg **12.1.0**

**Comment by artyorsh** [comment]
Make sure to `pod install` and restart with clearing cache. It works for me and the newly initialized projects

**Comment by evolvan** [comment]
**artyorsh** yes, upgrade @ui-kitten/components fixed it.
Thanks
