### ISSUE TITLE
Exception Thrown while executing UI block IOS device issue

### ISSUE THREAD

**Issue by olukayodea** [akveo/react-native-ui-kitten#1088]
When using Date picker on Mobile IOS Devices using expo, I get the error Exception thrown while  executing UI block

## To Reproduce

Setup Datepicker on iOS, click on the text box

## Expected behavior
![Simulator Screen Shot - iPhone X - 2020-05-14 at 22 54 48](https://user-images.githubusercontent.com/12675677/82003220-2e745e00-9636-11ea-8ac3-491d7c6c53a8.png)

**Comment by presola** [comment]
i have this same issue, i also have errors thrown on my android device
Error while updating property 'fill' of a view managed by: RNSVGGroup

null

java.lang.Double cannot be cast to java.lang.String

**Comment by artyorsh** [comment]
@olukayodea @presola this is not reproducible on latest library versions and was reported multiple times. You can search through the repository closed issues for the details.

[See a demo](https://snack.expo.io/LVJTyXcuq)

**Comment by presola** [comment]
@artyorsh , please see a [snack example here](https://snack.expo.io/a0O3thZZn)
it works on web preview but does not work on ios and android using expo 36.0.0

**Comment by artyorsh** [comment]
@presola because on previous SDK versions you should use 9.13.6, this is what `expo install` command does when you’re on expo-cli compatible to that version

**Comment by anasalaqeel** [comment]
I faced same problem and I added `display="spinner"` and then I added this prop `textColor="#000"` to change text color and here the problem happens, so I uninstalled the datetimepicker module using `npm uninstall @react-native-community/datetimepicker --save` and I install it again then and nothing fixed, so I make a final try by addeding `style={{top: 0}} `and then the textColor prop work fine.

this is my working code
 `<DateTimePicker display="spinner" style={{ top: 0 }} textColor="#000" onChange={handleDateChange} value={new Date()} />`

I hope this help someone
