### ISSUE TITLE
toggle change is  too slow whene debugger is on  

### ISSUE THREAD

**Issue by josef256** [akveo/react-native-ui-kitten#1091]
## To Reproduce

use the **toggle component** & set **RN debugger** on then click the toggle button

## Expected behavior

toggle should change whenever it is clicked, but in this case it's taking **a long time** to do so

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    5.0.0-alpha.1    |
| @ui-kitten/components   |     ^5.0.0-alpha.1    |

```bash

```

**Comment by artyorsh** [comment]
This is not a library issue, since everything works slower in debug mode. Please google for an actual reason if you’re interested in it.

We can reopen this issue if it’s reproduced in release builds.
