### ISSUE TITLE
Call setState with Input onChangeText inside a Modal causing: Warning: Cannot update during an existing state transition (such as within `render`).

### ISSUE THREAD

**Issue by DatXN** [akveo/react-native-ui-kitten#1094]
## 🐛 Bug Report

Call setState with Input onChangeText inside a Modal causing: Warning: Cannot update during an existing state transition (such as within `render`).Warning: Cannot update during an existing state transition (such as within `render`).
 

## To Reproduce

1. Enter any value inside the input, will causing  Warning: Cannot update during an existing state transition (only happen in the first time enter text, next time is not causing warning)

2. Remove the modal wrapping, the warning will not happen

## Link to runnable example or repository (highly encouraged)

```
const CourseInput = (props) => {
  const [value, setValue] = useState("");
  const addCourseHandler = () => {
    props.onAddCourse(value);
    setValue("");
  };
  const courseInputHandler = (enteredText) => {
    console.log(enteredText);
    setValue(enteredText);
  };
  return (
    <Layout
      style={{
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
      }}
    >
      <Modal
        visible={props.visible}
        backdropStyle={styles.backdrop}
        onBackdropPress={props.onCancelAdding}
      >
        <Input
          placeholder="Place your Text"
          value={value}
          onChangeText={courseInputHandler}
          style={{ marginVertical: 20 }}
        />
```

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    ^2.0.0    |
| @ui-kitten/components   |    ^5.0.0     |

## Environment information

```bash

  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  Binaries:
    Node: 12.16.3 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/Documents/Labs/Workspace/React_Native/galio-starter-kit/node_modules/.bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.3 => 16.8.3
    react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
```

**Comment by artyorsh** [comment]
I would suggest separating contents of the Modal if it assumes having a separated state.
This will reduce the amount of component renders, and fix the issue itself. 
[See an example](https://snack.expo.io/NHyH3EuBl)

**Comment by dozsolti** [comment]
A work around that I found is to **move the modal into a separated function** and **wrap it** all in a **try catch**
```
const ExtraRestsModal = () => {
  try {
	  return (
		  <Modal  ...
	  )
  } catch (err) {
	  return null
  }
}
```

**Comment by ohszehong** [comment]
> A work around that I found is to **move the modal into a separated function** and **wrap it** all in a **try catch**
> 
> ```
> const ExtraRestsModal = () => {
>   try {
> 	  return (
> 		  <Modal  ...
> 	  )
>   } catch (err) {
> 	  return null
>   }
> }
> ```

Thanks, this solved my issue!
