### ISSUE TITLE
SelectItem React.createElement: type is invalid -- expected a string

### ISSUE THREAD

**Issue by jasuno** [akveo/react-native-ui-kitten#1095]
When I try to use "SelectIment" react native give me an error that says:

"Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: %s.%s%s, undefined,  You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports."

I checked your index file and there is no "SelectItem" component being exported

```
import { Select, SelectItem } from "@ui-kitten/components";

export default class GetEventDetailsScreen extends Component {
  constructor(props) {
    super(props);
    this.state = {
      selectedIndex: 0,
    };
  }

 <Select
          placeholder="Active"
          selectedIndex={this.state.selectedIndex}
          onSelect={(index) =>
            this.setState({
              selectedIndex: index,
            })
          }
        >
          <SelectItem title="Option 1.1" />
          <SelectItem title="Option 1.2" />
        </Select>
}
```

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      | "^1.3.1"  |
| @ui-kitten/components   | "^4.4.1" |

**Comment by artyorsh** [comment]
The library version you use is v4, and the docs you run are valid for v5.
Consider upgrading the library or switching to the [v4 docs](https://akveo.github.io/react-native-ui-kitten/docs/4.x/) (see the switcher at the top right corner).
