### ISSUE TITLE
Autocomplete Simple Usage

### ISSUE THREAD

**Issue by AmreshVs** [akveo/react-native-ui-kitten#1097]
In documentation, the code view of Autocomplete has an bug.

In Code View - Line no 20
setValue(movies[index].title);

The correct code should be
setValue(data[index].title);

**Explanation:**
If we select the value from filtered list it does not select what we selected. Here the Autocomplete is setting the value of index from the **movies** array. This makes no use of auto complete. It should set value from the filtered list from state **data**.

**Comment by artyorsh** [comment]
Thanks for reporting!

**Comment by imdkbj** [comment]
This is not fixed yet on website, Line 20 of the first example.

https://akveo.github.io/react-native-ui-kitten/docs/components/autocomplete/overview#autocomplete
