### ISSUE TITLE
Input is blurred whenever a letter is typed (iOS)

### ISSUE THREAD

**Issue by andyhmltn** [akveo/react-native-ui-kitten#1098]
## 🐛 Bug Report

I'm trying to use an input component and `setState` as in the example in this repo. However, for whatever reason, when the user types a letter, the input is blurred and the keyboard disappears meaning you can only type one letter at a time

## To Reproduce

I'm currently using it paired with `List` & `renderHeader`:

```
import React, { useState } from 'react'
import { View } from 'react-native'
import ConversationSummary from '../../components/ConversationSummary'
import { Wrapper, List, Header } from './styles'
import { useTheme, Input } from '@ui-kitten/components'

export default function ConversationList() {
  const theme = useTheme()
  const [searchTerm, setSearchTerm] = useState('')
  const backgroundColor = theme['background-basic-color-4']
  const conversations = [null, null, null, null]

  const renderHeader = () => (
    <Header level="1" backgroundColour={backgroundColor}>
      <Input placeholder="Search" value={searchTerm} onChangeText={(searchTerm) => setSearchTerm(searchTerm)} />
    </Header>
  )

  const renderItem = (info) => <ConversationSummary key={`conversation-${info.index}`} conversation={info.item} />

  return (
    <View>
      <Wrapper backgroundColour={backgroundColor}>
        <List
          renderItem={renderItem}
          data={conversations}
          ListHeaderComponent={renderHeader}
          backgroundColour={backgroundColor}
        />
      </Wrapper>
    </View>
  )
}
```

## Expected behavior

The keyboard shouldn't disappear and the input should remain focused

## Link to runnable example or repository (highly encouraged)

`https://snack.expo.io/0dhL6ZXE!`

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   2.0.0     |
| @ui-kitten/components   |    ^5.0.0   |

## Environment information

```bash
  System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 12.4.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  npmPackages:
    react: ~16.9.0 => 16.9.0
    react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
```

**Comment by artyorsh** [comment]
@andyhmltn it becomes blurred because of incorrect usage of `ListHeaderComponent` property. Whenever you do a search, the List also becomes updated, calling state changes in Input.

You may solve this case by avoiding rendering Input with that property, e.g:
```js
<Input />
<List />
```

**Comment by andyhmltn** [comment]
Brilliant, that works and makes sense. Thanks for the fast reply @artyorsh

**Comment by andyhmltn** [comment]
FYI, the reason I did this was this example in the demo app:

https://github.com/akveo/kittenTricks/blob/master/src/layouts/messaging/conversation-list/index.tsx

I guess this works in the demo app, because there's no state changing. But when adding state, the way it's laid out there doesn't work
