### ISSUE TITLE
add onYearChange and onMonthChange callbacks for Calendar component

### ISSUE THREAD

**Issue by XHMM** [akveo/react-native-ui-kitten#1099]
## 🚀 Feature Proposal

add `onYearChange` and `onMonthChange` callbacks on `Calendar` component

## Motivation

listen for year and month change so we can implement business logic based on the current year/month. Although there is `onSelect`, this callback can only be called when the user selects a cell, we cannot get currently showed year/month when the user changed year/month only if user trigger `onSelect` which is limit.

## Example

`<Calendar onMonthChange={fetchOrdersByMonth} onYearChange={fetchOrdersByYear}  onSelect={fetchOrderDetail} />`

**Comment by artyorsh** [comment]
@XHMM makes sense. Thanks for the detailed description 👍 
I guess adding only `onVisibleDateChange` (optional) called with the first date of month is enough for this case. What do you think?

Feel free to help us by opening a PR on this 🐱

**Comment by XHMM** [comment]
Only `onVisibleDateChange` seems more clean. Its signature I think could be `onVisibleDateChange(newDate, oldDate) => void`

When playing with source code, I found `visibleDate` is always set to last month when I change the month (may be caused by this [source](https://github.com/akveo/react-native-ui-kitten/blob/master/src/components/ui/calendar/service/nativeDate.service.ts#L113) ), so I think `onVisibleDateChange` need to 'accurate' this behavior internally right?

I am not very familiar with source code, so I think not able to open PR currently, but I will try to do it.😊

**Comment by artyorsh** [comment]
> I think onVisibleDateChange need to 'accurate' this behavior

Yes. But I don't think we need adding `oldDate`, only the new (you don't have `onChangeText` on Input called with a previous value, right? :) ) But please describe in more details if it can be somehow useful.

**Comment by XHMM** [comment]
Oh you're right, `oldDate` is really unnecessary as you say, because the initial month/year can be inferred from `date` prop.

So next is to implement such a method, I will follow DEV_DOCS.md to try to implement it, also hope others to have a better implementation. 🙂

**Comment by XHMM** [comment]
pr created #[https://github.com/akveo/react-native-ui-kitten/pull/1115](url)

**Comment by heroic** [comment]
@XHMM is the year selection working for you in calendar?

**Comment by XHMM** [comment]
@heroic  this function only be triggered when the day component showed,  so if you only choose a year and then month component showed, this function not be called.

**Comment by violabg** [comment]
Definitely a must have feature.

I need to call a services to show custom cell on calendar based on the selected month, but can't do that without onVisibleDateChange callback
