### ISSUE TITLE
Autocomplete: example component, 

### ISSUE THREAD

**Issue by sourabhbagrecha** [akveo/react-native-ui-kitten#1101]
## 🐛 Bug Report

The autocomplete documentation [here](https://akveo.github.io/react-native-ui-kitten/docs/components/autocomplete/overview#autocomplete) is having some issues while rendering the example component. The search results are overlapping with the search bar.

## To Reproduce
So as per the current example in the autocomplete documentation, following is the behavior of the AutoComplete component:
**Before Keyboard Focus:**
![image](https://user-images.githubusercontent.com/27056663/82300118-08531300-99d4-11ea-95b5-d05dd9128bcf.png)
**After Keyboard Focus:**
![image](https://user-images.githubusercontent.com/27056663/82300143-0e48f400-99d4-11ea-91f9-5c3c21389c93.png)

## Expected behavior
![image](https://user-images.githubusercontent.com/27056663/82300540-9f1fcf80-99d4-11ea-81fc-9d690f8a1ea4.png)

The above issue can be simply fixed by shifting the position of `{data.map(renderOption)}` from inside the <AutoComplete/> tag to outside.

Current documentation:
![image](https://user-images.githubusercontent.com/27056663/82300968-3553f580-99d5-11ea-8b0a-f586e775dc01.png)

Expected documentation:
![image](https://user-images.githubusercontent.com/27056663/82301100-66ccc100-99d5-11ea-8ce3-e4c714f94b56.png)

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2.0.0    |
| @ui-kitten/components   |    5.0.0     |

## Environment information

```
  System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD

```

**Comment by artyorsh** [comment]
This is the space of the status bar, which is not configured in your case. See #743

**Comment by sourabhbagrecha** [comment]
Got it. Thanks!
