### ISSUE TITLE
Select: placeholderMarginHorizontal console warning

### ISSUE THREAD

**Issue by Dammic** [akveo/react-native-ui-kitten#1103]
## 🐛 Bug Report

Variable `placeholderMarginHorizontal` is no longer used (but left in mapping), which causes console warning.
As you can see here, it was used in the previous version (one commit before 5.0.0):
https://github.com/akveo/react-native-ui-kitten/blob/ff7b5a5bd5943605d2b1d13faec0161dad7a45fa/src/components/ui/select/select.component.tsx#L362
But in the current one, it's not used:
https://github.com/akveo/react-native-ui-kitten/blob/master/src/components/ui/select/select.component.tsx#L337

As one can see, in the newest eva-design/eva this variable is still present:
https://github.com/eva-design/eva/blob/master/packages/eva/mapping.json#L3691

## To Reproduce

NA - simply try to use Select component on a normal github project, and the warning (error) should be in console.

## Expected behavior

There is no warning in the console.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      | 2.0.0       |
| @ui-kitten/components   |  5.0.0       |

## Environment information

```bash
  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 13.12.0 - ~/.nvm/versions/node/v13.12.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v13.12.0/bin/npm
  IDEs:
    Xcode: /undefined - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4

```

EDIT: Ah, of course I've forgot to put in the warning:
![Screenshot 2020-05-19 at 14 39 13](https://user-images.githubusercontent.com/18100361/82409213-8a434a80-9a6d-11ea-81a7-cce1412ac13f.png)

**Comment by Roeefl** [comment]
This happens to me as well

**Comment by GlCap** [comment]
I too have this problem.

**Comment by topwebtek7** [comment]
still having this issue, any workaround to this yet?
