### ISSUE TITLE
tabBarStyle prop of TabView

### ISSUE THREAD

**Issue by dolhadan** [akveo/react-native-ui-kitten#1104]
## 💬 Question

Shouldn't the `tabBarStyle` props of a `TabView` component apply the style to the container `View` element of the `TabBar` element ?
https://github.com/akveo/react-native-ui-kitten/blob/master/src/components/ui/tab/tabBar.component.tsx#L187

Right now there is no way of adding a margin, for example, to the whole tab bar. You either apply it on the `TabView` container but that would apply the margins to the tabs too or you apply it to the tabBar using the `tabBarStyle` but that won't affect the indicator.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2.0.0    |
| @ui-kitten/components   |    5.0.0     |

**Comment by Wellbrito29** [comment]
Im trying to do a tabbar with borderRadius and i having some problems to align the icons inside either
