### ISSUE TITLE
How do change the courner radius on input text forms?

### ISSUE THREAD

**Issue by MScMechatronics** [akveo/react-native-ui-kitten#1105]
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |        |
| @ui-kitten/components   |         |

**Comment by arminghm** [comment]
You can use the `borderRadius` style property
```javascript
<Input style={{borderRadius: 20}} />
````

**Comment by artyorsh** [comment]
@arminghm thanks for chipping in 👍

**Comment by MScMechatronics** [comment]
Thanks, it came handy!
