### ISSUE TITLE
Change input height has no effect

### ISSUE THREAD

**Issue by foubei** [akveo/react-native-ui-kitten#1106]
## 🐛 Bug Report

I wanted to play with the height of the input, but it's not changing directly from input style

## To Reproduce

```
<Input
  size="large"
  style={{
    height: 60,
  }}
/>
```

## Expected behavior

The input size should be 80 instead of the original large input size which is 48.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2.0.0    |
| @ui-kitten/components   |    5.0.0     |

## Environment information

```bash
Run npx envinfo --preset react-native
  System:
    OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 12.16.3 - /usr/bin/node
    npm: 6.14.4 - /usr/bin/npm
  npmPackages:
    react: 16.13.1 => 16.13.1 
    react-native: 0.62.2 => 0.62.2
```

**Comment by arminghm** [comment]
might be related to #747 .
you might need to set the height inside textStyle property too.
