### ISSUE TITLE
Is it possible to increase or decrease all font-size in runtime?

### ISSUE THREAD

**Issue by nbastoWM** [akveo/react-native-ui-kitten#1108]
## 💬 Question

I want to be able to increase or decrease the font size at runtime (without using the device accessibility). Is this possible in ui-kitten? Maybe with dynamic mapping?

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2.0.0    |
| @ui-kitten/components   |   5.0.0   |

**Comment by arminghm** [comment]
Take a look at [Customize mapping](https://akveo.github.io/react-native-ui-kitten/docs/design-system/customize-mapping#customize-component-mapping) and [Custom component mapping](https://akveo.github.io/react-native-ui-kitten/docs/design-system/custom-component-mapping#create-a-custom-component-mapping)

**Comment by ana-lazar** [comment]
did you manage to do this?

**Comment by arminghm** [comment]
I barely remember!! Probably reading `size` property of mapping object from your state  can do the changes you want!
