### ISSUE TITLE
Add Search to TopNavigation using renderTitle

### ISSUE THREAD

**Issue by ankit5174** [akveo/react-native-ui-kitten#1113]
## 💬 Question
I am trying to add a search bar in TopNavigation, however i am not able to make it full width using flex. Do not want to use percentage width as it is not accurate with different screen size. Tried to use Dimensions window width but still no luck.
```
<TopNavigation
   accessoryLeft={renderBackAction}
   title={renderSearch}/>

const renderBackAction = () => <TopNavigationAction icon={BackIcon} />;
const renderSearch = (props) => <Input style={[styles.toolbarSearch]} />;

toolbarSearch: {
        flex: 1,
    },

```
## UI Kitten and Eva version
| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2.0.0    |
| @ui-kitten/components   |  5.0.0       |

**Comment by ankit5174** [comment]
Was able to use dimensions to get it working... However now facing another issue is that whenevr i type on the input box in TopNavigation, the keyboard loses its focus. It is happening only when i am placing the input field in TopNavigation.

**Comment by arminghm** [comment]
Please take a look at [Top Navigation api doc](https://akveo.github.io/react-native-ui-kitten/docs/components/top-navigation/api#topnavigation), your are returning Input component within renderSearch function, title is supposed to accept ReactText or a function which returns a Text component not an Input.

Name | Type | Description
-- | -- | --
title | `ReactText \| (TextProps) => ReactElement` | String, number or a function component to render within the top navigation. If it is a function, expected to return a Text.

you could add your input via accessoryRight or accessoryLeft property like this:

```javascript
<TopNavigation
  accessoryRight={(props) => <Input {...props} placeholder={'Search'} style={{flex: 1}} />}
/>
```

or even with more than just one component:

```javascript
<TopNavigation
  accessoryLeft={(props) => (
    <TopNavigationAction
      {...props}
      icon={(props) => <Icon {...props} name={'arrow-back-outline'} />}
      />
  )}
  accessoryRight={(props) => (
    <View {...props} style={{flexDirection: 'row', alignItems: 'center'}}>
      <Input placeholder={'Search'} style={{flex: 1}} />
      <TopNavigationAction
        icon={(props) => <Icon {...props} name={'search-outline'} />}
      />
    </View>
  )}
/>
```

**Comment by artyorsh** [comment]
@arminghm thanks for chipping in. I guess having Input inside TopNavigation is not possible because of #1146.
@ankit5174 anyways, please leave a comment if you have this resolved.

Will close this in favor of issue I mentioned above.

**Comment by arminghm** [comment]
@artyorsh actually I'm passing a function which returns an element inside TopNavigation, issue #1146 is about to adding an element to TopNavigation I guess. Here is the screenshot of the code above

![Screenshot_1594036219](https://user-images.githubusercontent.com/11267514/86590327-9eeb8b80-bfa4-11ea-9ae6-b6c7e8bcd6ad.png)

**Comment by Applizone** [comment]
> @artyorsh actually I'm passing a function which returns an element inside TopNavigation, issue #1146 is about to adding an element to TopNavigation I guess. Here is the screenshot of the code above
> 
> ![Screenshot_1594036219](https://user-images.githubusercontent.com/11267514/86590327-9eeb8b80-bfa4-11ea-9ae6-b6c7e8bcd6ad.png)

@arminghm Yes, it's working from your way, thanks man. But on my screen, the accessoryRight will utilize the screen and search outline icon will dissappear.  So, I made a little change and use in the title. Voila, all element are placed accordingly.
```js
<TopNavigation
    accessoryLeft={(props) => (
        <TopNavigationAction
            {...props}
            icon={(props) => <Icon {...props} name={'arrow-back-outline'} />}
        />
    )}
    title={(props) => (
        <View style={{ justifyContent: 'center', alignItems: 'center', flex: 1, height: 50 }}>
            <Input placeholder={'Search'} />
        </View>
    )}
    accessoryRight={(props) => (
        <View {...props} style={{ flexDirection: 'row', alignItems: 'center' }}>
            <TopNavigationAction
                icon={(props) => <Icon {...props} name={'search-outline'} />}
            />
        </View>
    )}
/>
```
![Searchbar](https://user-images.githubusercontent.com/90295274/153156186-18044976-00b6-4001-9791-9150712085aa.jpeg)
