### ISSUE TITLE
Async Autocomplete does not show options initially

### ISSUE THREAD

**Issue by fzf** [akveo/react-native-ui-kitten#1117]
## 🐛 Bug Report

When typing a value that is processed async the results do not populate until a user clicks in the box again.

## To Reproduce

It is currently broken in the [showcase](https://akveo.github.io/react-native-ui-kitten/docs/assets/playground-build/#/AutocompleteAsync)

## Expected behavior

Results should appear as soon as text is typed.

## Link to runnable example or repository (highly encouraged)

[showcase](https://akveo.github.io/react-native-ui-kitten/docs/assets/playground-build/#/AutocompleteAsync)

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |        |
| @ui-kitten/components   |   v5.0.0      |

**Comment by artyorsh** [comment]
@fzf thanks for reporting. I faced the same in the project I'm currently working on.
You may try using the workaround below if you use function components:
```ts
  // TODO: UI Kitten issue.
  // Not updates data list visibility, if initially focused with wrong value.
  React.useEffect(() => {
    const shouldBecomeVisible = (autocompleteRef.current?.isFocused() || false) && (data?.length || 0) > 0;
    if (autocompleteRef.current?.state.listVisible !== shouldBecomeVisible) {
      autocompleteRef.current?.setState({ listVisible: shouldBecomeVisible });
    }
  }, [data?.length]);
```

**Comment by fzf** [comment]
@artyorsh thanks for the code. Looking forward to a better solution in the future.

**Comment by Rizayev** [comment]
> @fzf thanks for reporting. I faced the same in the project I'm currently working on.
> You may try using the workaround below if you use function components:
> 
> ```ts
>   // TODO: UI Kitten issue.
>   // Not updates data list visibility, if initially focused with wrong value.
>   React.useEffect(() => {
>     const shouldBecomeVisible = (autocompleteRef.current?.isFocused() || false) && (data?.length || 0) > 0;
>     if (autocompleteRef.current?.state.listVisible !== shouldBecomeVisible) {
>       autocompleteRef.current?.setState({ listVisible: shouldBecomeVisible });
>     }
>   }, [data?.length]);
> ```

how to use it? Can you show code ex? please?

**Comment by artyorsh** [comment]
@Rizayev https://snack.expo.io/elAoHThIT
