### ISSUE TITLE
Drawer with ReactNavigation and SafeAreaView

### ISSUE THREAD

**Issue by joleb** [akveo/react-native-ui-kitten#1119]
## 💬 Question
Is it intended, that the navigation drawer is displayed as below? I think it is missing the safe area view (used an iPhone 11 Pro Simulator)
![image](https://user-images.githubusercontent.com/38313415/83021610-8d6ca680-a02a-11ea-8dc0-3410eb3ede15.png)

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   2.0.0     |
| @ui-kitten/components   |    5.0.0     |
| @react-navigation/drawer   |    5.8.0     |

**Comment by artyorsh** [comment]
@joleb we don't handle it out of the box because there are multiple approaches to handle safe area, e.g [by using context](https://github.com/th3rdwave/react-native-safe-area-context).
Also, sometimes you don't need safe area there (in case you use heading image).

So yes, it is.
