### ISSUE TITLE
CheckBox and Toggle iOS, no tick icons on checked items

### ISSUE THREAD

**Issue by CostachescuCristinel** [akveo/react-native-ui-kitten#1120]
## 💬 Question
I am not sure whether this is an issue in UI-Kitten or not.

On Android, the ticks on checked items of Checkbox and Toggle components are displayed correctly.
However, on iOS, there are no ticks on those items, only the rest of the item changes style. Below are screenshots of these in the checked false (left) and true (right) states.

![Screenshot 2020-05-27 at 18 02 18](https://user-images.githubusercontent.com/52235106/83037385-66bb6980-a044-11ea-8ca3-40f91c28f723.png) ![Screenshot 2020-05-27 at 18 02 46](https://user-images.githubusercontent.com/52235106/83037393-68852d00-a044-11ea-91f8-680c4bde9e64.png)
![Screenshot 2020-05-27 at 18 02 29](https://user-images.githubusercontent.com/52235106/83037405-6ae78700-a044-11ea-9652-8c8d821c056c.png) ![Screenshot 2020-05-27 at 18 02 36](https://user-images.githubusercontent.com/52235106/83037412-6c18b400-a044-11ea-8503-c960707548e5.png)

For comparison, here is the same running on Android:
<img width="323" alt="Screenshot 2020-05-27 at 18 09 32" src="https://user-images.githubusercontent.com/52235106/83038129-4809a280-a045-11ea-8495-cbdca825606b.png"> <img width="314" alt="Screenshot 2020-05-27 at 18 09 39" src="https://user-images.githubusercontent.com/52235106/83038138-4a6bfc80-a045-11ea-867b-7e6384075d6b.png">
<img width="319" alt="Screenshot 2020-05-27 at 18 09 44" src="https://user-images.githubusercontent.com/52235106/83038148-4c35c000-a045-11ea-9740-a44b8615da2c.png"> <img width="292" alt="Screenshot 2020-05-27 at 18 09 50" src="https://user-images.githubusercontent.com/52235106/83038156-4dff8380-a045-11ea-9f1d-1fef504f0a16.png">

I am using a metro.config.js (as in the "improving performance" guide), within an expo environment (expo-cli 3.21.1, Expo SDK 37.0.0.1 - React Native 0.61 - React 16.9).

I do have a branding JSON (exported as JSON from the colors.eva.design website) and a custom mapping JSON (this last one is empty, placeholder for further adjustments).

The same happens in both iOS 12.x and 13.x, and both in a simulator and a real device (iPhone SE with iOS 13).

Can you help me figure out what the issue is?

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2.0.0    |
| @ui-kitten/components   |    5.0.0     |

**Comment by artyorsh** [comment]
Which `@ui-kitten/eva-icons ` and `react-native-scg` version do you run?

**Comment by CostachescuCristinel** [comment]
Hi,

I am running `@ui-kitten/eva-icons: 5.0.0` and `react-native-svg: 12.1.0`

**Comment by artyorsh** [comment]
rnsvg v12 is not currently supported by expo as far as I know. Make sure to run `expo install react-native-svg`, then `pod install` and restart your app with clearing cache: `expo start -c`

**Comment by artyorsh** [comment]
It works properly in this config. [See Snack](https://snack.expo.io/oGqLGrNfW)

**Comment by CostachescuCristinel** [comment]
I have run `yarn remove react-native-svg` and then `expo install react-native-svg`, and it finally works correctly!

For people who are accustomed to installing packages directly through npm/yarn, expo installed `react-native-svg` at version `11.0.1`.

Thank you very much for your help, @artyorsh !

**Comment by artyorsh** [comment]
@CostachescuCristinel you should use `expo install` for everything within the Expo managed apps
