### ISSUE TITLE
Autocomplete keyboard doesn't persist when you click item on list

### ISSUE THREAD

**Issue by naegahyung** [akveo/react-native-ui-kitten#1122]
## 💬 Question
I am facing this similar issue as [this](https://github.com/facebook/react-native/issues/23732), where the keyboard gets dismissed when I click an item in the autocomplete list, or an icon within the textinput field. Is there a prop that I can use to persist the keyboard open when you click on the popover or textinput? I read all documentation and read inside code, but it looks like such functionality is not exposed to the component.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   2.0.0     |
| @ui-kitten/components   |  5.0.0     |

**Comment by artyorsh** [comment]
@naegahyung thanks for the interest and pointing on the related issue.
I guess it's not possible in current version, [here is what's blocking it](https://github.com/akveo/react-native-ui-kitten/blob/master/src/components/ui/autocomplete/autocomplete.component.tsx#L164).

I think adding `keyboardShouldPersistTaps` is a good idea for components like this.

**Comment by GantMan** [comment]
I just had the same issue.   And a positioning issue.

Would love for these this to be fixed/added.

**Comment by artyorsh** [comment]
@GantMan 

> And a positioning issue

Please see #743

**Comment by GantMan** [comment]
Position issue fixed!  Thanks for the link.

**Comment by DavidDunkovich** [comment]
+1 to adding keyboardShouldPersistTaps

**Comment by AntonBorovoi** [comment]
keyboardShouldPersistTaps='always' was added within https://github.com/akveo/react-native-ui-kitten/pull/1423
and released with the v5.1.1
