### ISSUE TITLE
Allow for text in Input accessories

### ISSUE THREAD

**Issue by TMcLoone** [akveo/react-native-ui-kitten#1123]
## 🚀 Feature Proposal

Right now you can only have images or icons as input accessories but it would be great to prefix/suffix with text

## Motivation

For a lot of inputs you want to add labels such as weight units (e.g. LB/KG), social handles/emails

## Example

![53967014-da0a5000-410d-11e9-8a74-c30650c5ac08](https://user-images.githubusercontent.com/2749978/83252404-2a3d5a00-a179-11ea-8215-b74a63f37604.png)

**Comment by artyorsh** [comment]
Hi! 👋  Thanks for the proposal.

It's not a big deal to achieve such behavior with a current realization, is it?
https://snack.expo.io/ksyUQNoIC

**Comment by TMcLoone** [comment]
Hah I was getting an error that it needed it be an Image but I was just not rendering the text component correctly. Thank you!
