### ISSUE TITLE
Change year in calendar does not work

### ISSUE THREAD

**Issue by heroic** [akveo/react-native-ui-kitten#1125]
## 🐛 Bug Report

Trying the demo here: https://akveo.github.io/react-native-ui-kitten/docs/components/calendar/overview

The calendar does not let me change the year.

## To Reproduce

Use the live demo provided in the documentation. Try to select year. 

## Expected behavior

Year should be selected.

## Link to runnable example or repository (highly encouraged)

https://akveo.github.io/react-native-ui-kitten/docs/components/calendar/overview

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |       2 |
| @ui-kitten/components   |  5       |

**Comment by artyorsh** [comment]
You should configure `min` and `max` properties. See the example on the same link
