### ISSUE TITLE
There's a bug in your AutoComplete Documentation

### ISSUE THREAD

**Issue by odetolakenny** [akveo/react-native-ui-kitten#1129]
## 🐛 Bug Report

When the filter is done, The value displayed in the text field does not correspond to what was chosen

If I search for "**The Matrix**" and I select it, it shows "**Star Wars**"

Instead of this
`const onSelect = (index) => {
    setValue(movies[index].title);
  };`

Should be this: 
`const onSelect = (index) => {
    setValue(data[index].title);
  };`

**Comment by arminghm** [comment]
If you would like you could fix it by sending PR. 👍

**Comment by artyorsh** [comment]
This issue duplicates #1097. Thanks for reporting!

**Comment by aitorbernis** [comment]
What about fixing it?
