### ISSUE TITLE
DrawerGroup in combination with react-navigation is broken

### ISSUE THREAD

**Issue by pitops** [akveo/react-native-ui-kitten#1130]
UI-Kitten v5

Consider the below:

```
import React, { useState } from 'react'
import { Drawer, DrawerItem, DrawerGroup, IndexPath } from '@ui-kitten/components'

export const DrawerContent = ({ navigation, state }) => {
  const [selectedIndex, setSelectedIndex] = useState(0)
  return (
    <Drawer
      selectedIndex={selectedIndex}
      onSelect={index => {
        setSelectedIndex(index)
        navigation.navigate(state.routeNames[index.row])
      }}>
      <DrawerItem title='Home' />
      <DrawerItem title='View recent locations' />
      <DrawerItem title='Symptoms Checker' />
      <DrawerItem title='News' />
      <DrawerItem title='Statistics' />

      <DrawerGroup title='Data'>
        <DrawerItem title='Import' />
        <DrawerItem title='Export' />
      </DrawerGroup>

      <DrawerGroup title='Legal'>
        <DrawerItem title='Privacy' />
        <DrawerItem title='Licenses' />
        <DrawerItem title='Acknowledgements' />
      </DrawerGroup>
    </Drawer>
  )
}
```

If I click on `Import` it gives the following for `index`:

```
{ row: 0, section: 5 }
```

However, as per the docs and logic, you need to pass an index to react-navigation

```
navigation.navigate(state.routeNames[index.row])
```

Hence, in this case, it will pass `0` when as far as `react-navigation` is concerned the screen I have chosen has an index of `5`

This also means that the DrawerItem highlight is also broken.

### Expected behavior

DrawerGroup index.row should not be relative OR give a third parameter as the actual index that `react-navigation` needs

```bash
  System:
    OS: macOS 10.15.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 28
      Build Tools: 28.0.3, 29.0.1, 29.0.3
      System Images: android-23 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.13.1 => 16.13.1 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

**Comment by artyorsh** [comment]
@pitops 
You have:
Section 0: Home
Section 1: View recent locations
...
Section 5: Data

> However, as per the docs and logic, you need to pass an index

The `routeNames` is a 1-dim array, and the configuration of the drawer you've built assumes usage of 2-dim arrays (array of sections, where a section is an array of routes). So the output you have is correct.

I would suggest mapping an existing array of `routeNames` to the one used in drawer component:
```js
const routes: {
  Statistics: ['Statistics'],
  Data: ['Import', 'Export'],
};

onSelect={index => {
  const sectionRoutesKey = Object.keys(routes)[index.section];
  const sectionRoute = routes[sectionRoutesKey][index.row];
  navigation.navigate(sectionRoute);
}}
```

**Comment by mofengfs** [comment]
@artyorsh 
Your method is feasible, but the answer you gave is wrong. It must be judged to run, and there will be performance problems during operation. This is related to the Drawer component. So you can say that this method is not feasible.

**Comment by artyorsh** [comment]
> but the answer you gave is wrong

From the end of the framework:
How can the UI layer we provide can probably know about the navigation layer of your app?
The framework gives you an abstraction layer of how you can compose the views, but the business logic is always stays up to you, being dependent on how you compose the view.

**Comment by mofengfs** [comment]
> > but the answer you gave is wrong
> 
> From the end of the framework:
> How can the UI layer we provide can probably know about the navigation layer of _your_ app?
> The framework gives you an abstraction layer of how you can compose the views, but the business logic is always stays up to you, being dependent on how you compose the view.

Yes, I think I found the reason for `performance`.
  `onSelect` adds judgment to run. But "selectedIndex" doesn't know how to make it the selected state color.

**Comment by mofengfs** [comment]
@artyorsh 
If `selectedIndex` is based on `row`, and let `row` be highlighted. So why the highlighted part is only `DrawerItem` outside of `DrawerGroup`.
![image](https://user-images.githubusercontent.com/16655229/100890856-a67f7400-34f3-11eb-9a89-d81aa5cc11fc.png)
![image](https://user-images.githubusercontent.com/16655229/100890956-be56f800-34f3-11eb-86b5-08e146903ca5.png)
![image](https://user-images.githubusercontent.com/16655229/100891041-d3338b80-34f3-11eb-864c-1aae28e06448.png)

**Comment by mofengfs** [comment]
@artyorsh 
I solved it, although a little luck. But thank you anyway.

**Comment by artyorsh** [comment]
@mofengfs
I was testing it with a demo in a meantime https://snack.expo.io/pvRIVrzJE

**Comment by mofengfs** [comment]
@artyorsh 
Oh, thank you. However, there are still some problems, such as launching the app, the first click will report an error: `TypeError: Cannot read property'section' of null`
![image](https://user-images.githubusercontent.com/16655229/100902414-d2a0f200-34ff-11eb-8987-721c2bf3c76d.png)

**Comment by mofengfs** [comment]
@artyorsh 
need your help
