### ISSUE TITLE
Modal layout is incorrect after Orientation change

### ISSUE THREAD

**Issue by lxzxl** [akveo/react-native-ui-kitten#1132]
## 🐛 Bug Report

the Modal content position is not correct after screen orientation is changed to landscape and back to portrait.

## To Reproduce

Rotate the screen to landscape and then rotate back to portrait view. Open a modal, the modal is not centered.

## Expected behavior

The modal should be centered in window with the correct left and top.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    5.0.0   |
| @ui-kitten/components   |    5.0.0     |

## Environment information

<img width="359" alt="Xnip2020-06-07_00-19-24" src="https://user-images.githubusercontent.com/2275002/83959328-34183900-a8ae-11ea-950b-6658c3944c0b.png">

**Comment by artyorsh** [comment]
Thanks for reporting!
