### ISSUE TITLE
Permission denied (publickey). fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by sanjeevkse** [akveo/react-native-ui-kitten#1133]
## 💬 Question
This command `npx react-native init JETAcademy --template @ui-kitten/template-js` is giving the below error. 

It sometimes gives. sometimes works.
Help me,

![dfasdf](https://user-images.githubusercontent.com/4029801/83961489-2c0dc880-a8b1-11ea-95ce-a8f1f799ffa9.JPG)

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |        |
| @ui-kitten/components   |     4    |

**Comment by sanjeevkse** [comment]
ok, if i create react native project and install this later, it works. but for a new project creation it would. it gives me this error.

**Comment by artyorsh** [comment]
You're using an outdated react-native-cli package. See https://github.com/react-native-community/react-native-template-typescript/issues/80
