### ISSUE TITLE
How to change font sizes for UI Kitten components like Inputs and Buttons?

### ISSUE THREAD

**Issue by mukurpuri** [akveo/react-native-ui-kitten#1135]
First of all, I want to burst lots and lots of appreciation for the amazing minds behind this amazing Design System and Project.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   2.0.0     |
| @ui-kitten/components   |    5.0.0     |

**Comment by artyorsh** [comment]
Yes, you can. See the Advanced Configuration topic of the Typography section in [Branding guide](https://akveo.github.io/react-native-ui-kitten/docs/guides/branding#typography).

**Comment by msarfrazanwar** [comment]
The same issue is there with List Component. It appears so small on by default.
