### ISSUE TITLE
Custom mapping per theme / Change mapping at runtime

### ISSUE THREAD

**Issue by Ben348** [akveo/react-native-ui-kitten#1136]
## 💬 Question
Hello,

I was wondering if it is possible to have custom mappings for each theme. I have a styled component with a `backgroundColor` parameter which references the `background-basic-color-1` variable. In the dark theme however I'd like to reference a different variable e.g. `background-basic-color-3`

```
{
    "StyledComponent": {
        "meta": {
            "parameters": {
                "backgroundColor": {
                    "type": "string"
                }
            },
            "appearances": {
                "default": {
                    "default": true
                }
            },
            "variantGroups": {},
            "states": {}
        },
        "appearances": {
            "default": {
                "mapping": {
                    "backgroundColor": "background-basic-color-1"
                }
            }
        }
    }
}
```

I have tried creating 2 mappings which has this change in and then change them at runtime depending on what theme I have on but it isn't working.

```
<ApplicationProvider
    mapping={mapping}
    customMapping={isLightTheme ? customMappingLight : customMappingDark}
```

Do I need to reload the whole application to get it working like this?

The only other way I can think of is to create a custom variable and then set that in both themes. Are there any other options that I am missing?

Thank you in advance

## UI Kitten and Eva version
| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      | 2.0.0 |
| @ui-kitten/components   | 5.0.0|

**Comment by artyorsh** [comment]
>  if it is possible to have custom mappings for each theme
It's not possible. Furthermore, this is out of the concept. The one of the main purposes of mapping is to "make a decision" of which color variable should be applied to the component, not depending on theme.

> In the dark theme however I'd like to reference a different variable

You may add a new variable with a different values in both themes and reference it in mapping

**Comment by Ben348** [comment]
Ok thank you I think this was the case but wanted to check in case I was missing something
