### ISSUE TITLE
Integrate react-redux with UI-kitten in App.js

### ISSUE THREAD

**Issue by MScMechatronics** [akveo/react-native-ui-kitten#1139]
## 💬 Question

I'm unable to figure out how to integrate react-redux with UI-kitten. UI-kitten mandates to apply the ApplicationProvider in the App.js file, while the react-redux mandates to apply the Provider from react-redux library. How do I integrate react-redux with UI-kitten in a react-native application? 

Kind regards,
MScMechatronics from Sweden 

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |        |
| @ui-kitten/components   |         |

**Comment by artyorsh** [comment]
@MScMechatronics it's ok to have multiple providers at the root.
Probably, the structure should be something like this (example with MobX):
```js
<ApplicationProvider>
  <Provider>
    // ...
  </Provider>
</ApplicationProvider>
```
