### ISSUE TITLE
[Android] Input multiple line auto justify center

### ISSUE THREAD

**Issue by dinhmai74** [akveo/react-native-ui-kitten#1140]
## 🐛 Bug Report

Input multiple line auto justify-content to center on android, work fine on ios

## To Reproduce

- Init expo project
- Install UI kitten follow docs: https://akveo.github.io/react-native-ui-kitten/docs/guides/getting-started#manual-installation
![102954462_1951253371677421_6506916208663789782_n](https://user-images.githubusercontent.com/40544043/84166202-cc751000-aa9e-11ea-9bba-813e8ca1a0ec.jpg)

## Link to runnable example or repository (highly encouraged)

https://snack.expo.io/@liugondar/textarea
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   ^2.0.0     |
| @ui-kitten/components   |     ^5.0.0    |

## Environment information

```bash
 System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
  Binaries:
    Node: 13.14.0 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.npm-global/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: ~16.9.0 => 16.9.0
    react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

**Comment by artyorsh** [comment]
This is a standard behavior of Android platform. You might want to use `textAlignVertical` property.
[Docs](https://reactnative.dev/docs/textinput#multiline) | [Example](https://snack.expo.io/vz2tdF7I1)
