### ISSUE TITLE
Select placeholder does not work

### ISSUE THREAD

**Issue by wigleyj** [akveo/react-native-ui-kitten#1143]
## 🐛 Bug Report

Placeholder on Select component appears to do nothing. no matter what I enter, and what values are used for the SelectItem, the default text of "Option 1" is displayed.
## To Reproduce

Create a select component and try to use placeholder
## Expected behavior
value passed to placeholder should override the default "Option 1" text.

## Link to runnable example or repository (highly encouraged)
https://snack.expo.io/KQEjC6pcW

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |     2.0.0   |
| @ui-kitten/components   |   5.0.0      |

## Environment information

```bash
System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 21, 22, 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 26.0.2, 27.0.3, 28.0.2, 28.0.3, 29.0.2
      System Images: android-26 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
```

**Comment by artyorsh** [comment]
@wigleyj placeholder is displayed in case there is no selected options
https://snack.expo.io/3vhNgwztR

**Comment by wigleyj** [comment]
hey thanks for the reply. between your post and me realizing i was editing the wrong, thing i got this working. It was definitely a me issue. sorry for the incorrect bug post.

**Comment by msarfrazanwar** [comment]
> @wigleyj placeholder is displayed in case there is no selected options https://snack.expo.io/3vhNgwztR
> 
> Also, please see Select Display Value example in the docs

Why is the snack not showing the value on select ? It's showing me option 1 and option 2 instead of selected value
