### ISSUE TITLE
Input component borderWidth not working!

### ISSUE THREAD

**Issue by mhmiton** [akveo/react-native-ui-kitten#1144]
I tried to increase borderWidth in the Input component. But it's not working. Also, I tried with textStyle and style, both not working. Here is my code.

<Input
      textStyle={{height: 40}}
      style={{borderColor: "#000", borderWidth: 5}}
      label="Username"
      value={this.state.username}
      onChangeText={username => this.setState({username})}
/>

Here is an image link of output - 

https://drive.google.com/file/d/1dC6GOr3TXCsBd014KU8KTpHnTfdT_15v/view?usp=sharing

**Comment by artyorsh** [comment]
Hi 👋 
Currently, the possible solution is to override borderWidth by using [mapping customization feature](https://akveo.github.io/react-native-ui-kitten/docs/design-system/customize-mapping#customize-component-mapping).
