### ISSUE TITLE
Unusably slow

### ISSUE THREAD

**Issue by isaaclem** [akveo/react-native-ui-kitten#1145]
First of all I must express my very good impression for the well written docs at https://akveo.github.io/react-native-ui-kitten/docs/guides/getting-started#getting-started

I was following the guide by creating a `HomeScreen` and a `DetailsScreen`, working together using `React-navigation`, and below is the GIF created to show how slow it is to render on screen.

![Bug](https://user-images.githubusercontent.com/32945572/84589484-54716600-ae61-11ea-93e0-63eb541230d6.gif)

After loaded 100%, clearly you can see that I have to wait close to 15 secs to see the HomeScreen being rendered on screen, am I the only one facing this issue?

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |        "^2.0.0"|
| @ui-kitten/components   |      "^5.0.0"   |

**Comment by artyorsh** [comment]
Could you please share the full code?

**Comment by Atww** [comment]
Same problem

**Comment by jiahong96** [comment]
Same problem here. the sample app **Kitten Tricks** also takes around **6-10 secs** to load on low-end Android phones (tested on _Redmi 8, Android 10_), high-end Android phones such as _Google Pixel 3 XL (Android 10)_ takes around **3 secs**. Anyway to optimize this for low-end phones?

**Comment by socialcode-rob1** [comment]
Have you tried compiling your mapping files?
https://akveo.github.io/react-native-ui-kitten/docs/guides/improving-performance#metro-bundler

**Comment by artyorsh** [comment]
@jiahong96 @Atww please follow the solution shared by @socialcode-rob1 
> the sample app Kitten Tricks also takes around 6-10 secs to load

You may use the same guide to faster it. We didn't update Kitten Tricks to follow that because it may run both Expo and Bare RN environments.

**Comment by jiahong96** [comment]
> @jiahong96 @Atww please follow the solution shared by @socialcode-rob1
> 
> > the sample app Kitten Tricks also takes around 6-10 secs to load
> 
> You may use the same guide to faster it. We didn't update Kitten Tricks to follow that because it may run both Expo and Bare RN environments.

Hi artyorsh, thanks for replying. I followed the guide and it's loading faster now. Thanks for the great UI library!

**Comment by Shihaburabbi** [comment]
same problem anyone help me 
```
"@eva-design/eva": "^2.1.1",
"@ui-kitten/components": "^5.1.1",
    "@ui-kitten/eva-icons": "^5.1.1",
```
