### ISSUE TITLE
Deprecate and remove render props function in favour of an element prop

### ISSUE THREAD

**Issue by Federkun** [akveo/react-native-ui-kitten#1146]
Currently, on most ui components, you can pass a component
```
  <TopNavigation accessoryLeft={BackAction} />
```
or a render function ( which is usually defined inside the render function of the component that use it )
```
  <TopNavigation accessoryLeft={() => <BackAction someProps={123} />} />
```
but not an element
```
  <TopNavigation accessoryLeft={<BackAction  someProps={123} />} />
```

Nothing bad with the first one. The only real disadvantage is the fact you cannot pass additional props. If you have that use case, you need to fallback with the render function. [But if we do that, the element is created using React.createElement.](https://github.com/akveo/react-native-ui-kitten/blob/master/src/components/devsupport/components/falsyFC/falsyFC.component.tsx#L46). The issue with that is that we'll create a new element each time the component is re-rendered. If `BackAction` has any state, it will be lost because `React.createElement` create a new element each time. Solution would be to pass an element directly, like in the third example. That tend to be the most flexible solution, would solve the life-cycle issues, and would render the render-function-api unnecessary.

**Comment by artyorsh** [comment]
@Federkun thanks for pointing on this.

> the element is created using React.createElement.

This [was done](https://github.com/akveo/react-native-ui-kitten/commit/5ba8daf7a1d223dedcbe34700cc177adaa88416d) for hooks support. Actually, I started thinking about adding support for each way we can nest components, so both render props and passing components directly are supported (which is done in bare react-native components). What do you think?

**Comment by florello-tbox** [comment]
As supporting component, element and function that return element? That would be super. And it's not a breaking change as I proposed above.
I guess even a

```
  if (React.isValidElement(component)) {
    return component;
  }
```

would do the job. At that point it's a matter of discriminate between `accessoryLeft={BackAction}` and `accessoryLeft={() => <BackAction someProps={123} />}`, as one require to be rendered with `component(props)` and the other `React.createElement(component, props)`. ( as far as i know, it may be required to relay on some of the implementation details of react to do that ).

That said I do feel that keeping the render props api may result in obscure issues ( when starting to relaying on state or effects on those inner components ), and minor performance impact ( as react needs to throw away the element every time when the parent component re-render ). But that's something maybe we can keep into consideration for v6.

**Comment by Federkun** [comment]
As supporting component, element and function that return element? That would be super. And it's not a breaking change as I proposed above.
I guess even a

```
  if (React.isValidElement(component)) {
    return component;
  }
```

would do the job. At that point it's a matter of discriminate between `accessoryLeft={BackAction}` and `accessoryLeft={() => <BackAction someProps={123} />}`, as one require to be rendered with `component(props)` and the other `React.createElement(component, props)`. ( as far as i know, it may be required to relay on some of the implementation details of react to do that ).

That said I do feel that keeping the render props api may result in obscure issues ( when starting to relaying on state or effects on those inner components ), and minor performance impact ( as react needs to throw away the element every time when the parent component re-render ). But that's something maybe we can keep into consideration for v6.

**Comment by CostachescuCristinel** [comment]
> At that point it's a matter of discriminate between `accessoryLeft={BackAction}` and `accessoryLeft={() => <BackAction someProps={123} />}`, as one require to be rendered with `React.createElement(component, props)` and the other `component(props)`

What about [`React.cloneElement()`](https://reactjs.org/docs/react-api.html#cloneelement) ?
Clones the original element, with the original props (maintains the ref, ect.), and does not need to discriminate between a functional component or class component.

**Comment by Federkun** [comment]
Hi Costachescu,
the problem is not to distinguish between functional component and class component, but from react component and inline rendering function. Both have a `(props) => JSX.Element` signature.
`cloneElement` is appropriate when we pass an element, which is what the PR that I opened try to support: https://github.com/akveo/react-native-ui-kitten/pull/1169/files#diff-7bb1ec7647020f5320903424638ce4a6R60-R62
