### ISSUE TITLE
 web  Failed to compile.

### ISSUE THREAD

**Issue by jasuno** [akveo/react-native-ui-kitten#1148]
## 🐛 Bug Report
```

/Users/jasonmatthews/Documents/atlantaDark/node_modules/@ui-kitten/components/ui/input/input.component.js 110:38
Module parse failed: Unexpected token (110:38)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|         this.webEventResponder = devsupport_1.WebEventResponder.create(this);
|         this.focus = () => {
>             this.textInputRef.current?.focus();
|         };
|         this.blur = () => {
```

## Expected behaviour

I expected it to build the web version of the application.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |  1.3.1  |
| @ui-kitten/components   |  5.0.0  |

**Comment by artyorsh** [comment]
This issue duplicates #996. Please check it for a [possible workaround](https://github.com/akveo/react-native-ui-kitten/issues/996#issuecomment-616115469)
