### ISSUE TITLE
Input accessoryRight always alligned in center

### ISSUE THREAD

**Issue by foubei** [akveo/react-native-ui-kitten#1150]
## 💬 Question

Is there a way to customize the allignment of **accessoryRight** Icon? I would like to show it on top of the **multiline** **Input** and not in the center.
![Screenshot_1592564811](https://user-images.githubusercontent.com/12202571/85126892-f5e12900-b260-11ea-9613-a3c9e21f3555.png)

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2.0.0    |
| @ui-kitten/components   |     5.0.0    |

**Comment by artyorsh** [comment]
@foubei if your Input has a fixed height, the option is to move icon to the top by using a negative margin, avoiding usage of an absolute positioning. [Here is an example](https://snack.expo.io/0aN3Olg0W)

Do you have the problem resolved?

**Comment by foubei** [comment]
Thanks for your reply. My input is not fixed height. Your solution may not work. I have used **onLayout** prop to get the input height and wrapped up the accessoryRight inside a View styling it with justifyContent to flex-start and height inherited to its parent (Input)
