### ISSUE TITLE
ButtonGroup appearance missing option 'ghost'

### ISSUE THREAD

**Issue by arafatzahan** [akveo/react-native-ui-kitten#1151]
As the title says, ButtonGroup prop appearance only allows filled and outline, but not ghost. This should be fixed as there's no reason to not allow ghost appearance in buttongroup.

**Comment by artyorsh** [comment]
@arafatzahan [this is handled](https://github.com/akveo/react-native-ui-kitten/blob/master/src/components/ui/buttonGroup/buttonGroup.component.tsx#L31), but of course if you'll pass 'ghost' as appearance, it [will be applied](https://github.com/akveo/react-native-ui-kitten/blob/master/src/components/ui/buttonGroup/buttonGroup.component.tsx#L131) by nested components. 

I see no reason to add an additional condition for handling that. Any problems with manual handling of that?

**Comment by artyorsh** [comment]
@arafatzahan 

> no reason to not allow

This would be the same as using multiple Buttons without wrapping it into a Group. Any reason to allow it?

**Comment by arafatzahan** [comment]
@artyorsh It feels inconsistent, as filled and outline options work, but not ghost. I wanted to create a rating buttongroup like this.

`
<ButtonGroup  
    style={styles.reviewButtons}
    appearance="ghost"
    status="warning"
>
	{steps.map((v, i) => (
		<Button
			key={i}
			icon={
				ratingReview > i ? StarIconFill : StarIcon
			}
			onPress={() => setRatingReview(v)}
		/>
	))}
</ButtonGroup>
`

ended up doing what you suggested: 

`
<View style={styles.reviewButtons}>
	{steps.map((v, i) => (
		<Button
			key={i}
			appearance="ghost"
			status="warning"
			icon={
				ratingReview > i ? StarIconFill : StarIcon
			}
			onPress={() => setRatingReview(v)}
		/>
	))}
</View>
`

I reported the issue because I thought it's kind of inconsistent how filled and outlined works but ghost doesn't. It's up to you. 

Thanks.

**Comment by ptboyer** [comment]
I'm in the same boat here.

It would be best to not discriminate the "ghost" appearance option for a ButtonGroup as it is ultimately passed into it's child Button elements — I still want to maintain the rounded corners for the **pressed** highlight when you have many ghost buttons in a group.

**Comment by ptboyer** [comment]
**Quick fix**: You can eliminate the warning message by patching in a functional appearance mapping for ButtonGroup via ApplicationProvider, hence making the "ghost" appearance a valid option.

```jsx
import * as eva from "@eva-design/eva";

...

const { outline } = eva.mapping.components.ButtonGroup.appearances;
const ghostStatusKeys = Object.keys(outline);
const ghostStatusGeneric = {
  borderColor: "transparent",
  dividerBackgroundColor: "transparent",
};

eva.mapping.components.ButtonGroup.appearances.ghost = {
  mapping: {},
  variantGroups: {
    status: ghostStatusKeys.reduce(
      (acc, key) => Object.assign(acc, { [key]: ghostStatusGeneric }),
      {}
    ),
  },
};

...

<ApplicationProvider {...eva} theme={eva.light}>
```
