### ISSUE TITLE
Input seems to ignore underlineColorAndroid TextInput prop

### ISSUE THREAD

**Issue by sudomann** [akveo/react-native-ui-kitten#1152]
## 🐛 Bug Report

Used [`underlineColorAndroid`](https://reactnative.dev/docs/textinput#underlinecolorandroid) but a line still shows which does not respect any valid color I specify.

## To Reproduce

Pass `underlineColorAndroid` to `Input` with any [valid color](https://reactnative.dev/docs/colors).

Snippet of my code which render fields shown in following screenshot:
```jsx
    <>
      <Input
        label={t('formFieldLabelEmail')}
        accessoryRight={EmailIcon}
        value={email}
        textContentType="emailAddress"
        onChangeText={setEmail}
        defaultValue="u@test.com"
        keyboardType="email-address"
        autoCorrect={false}
        autoCapitalize="none"
        returnKeyType="next"
        // android
        autoCompleteType="email"
        importantForAutofill="yes"
        underlineColorAndroid="transparent"  // <-------HERE
        // ios
        enablesReturnKeyAutomatically
      />

      <Input
        label={t('formFieldLabelPassword')}
        caption={PasswordFieldCaption}
        style={styles.passwordInput}
        accessoryRight={LockIcon}
        value={password}
        textContentType="password"
        secureTextEntry={!passwordVisible}
        onChangeText={setPassword}
        defaultValue="amildlylongpassword"
        returnKeyType="done"
        autoCorrect={false}
        autoCapitalize="none"
        // android
        autoCompleteType="password"
        underlineColorAndroid="transparent"  // <-------HERE
        // ios
        enablesReturnKeyAutomatically
      />
    </>
```

## Expected behavior

On Android, text underline color should match the props.

## Link to runnable example or repository (highly encouraged)
_None_

<img src="https://user-images.githubusercontent.com/16912950/85266823-6c894c80-b442-11ea-9533-66666c00ef82.png" alt="screenshot of my app demonstrating the issue" width="300">

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/material      |  2.0.0      |
| @ui-kitten/components   |     5.0.0    |

## Environment information

```bash
  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  Binaries:
    Node: 14.4.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    Watchman: 20200424.164118.0 - C:\redacted\path\to\watchman.EXE
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
  npmPackages:
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
```

**Comment by artyorsh** [comment]
It seems that you're missing the concept of that property. It doesn't configure the text underline as you probably think. [See an example](https://snack.expo.io/YSVgQ681fL)

You may also see [the code](https://github.com/akveo/react-native-ui-kitten/blob/master/src/components/ui/input/input.component.tsx#L293) used to provide any props to TextInput component

You probably won't using that property to remove the underline
