### ISSUE TITLE
OverflowMenu dynamic height

### ISSUE THREAD

**Issue by ArthurDelbeke** [akveo/react-native-ui-kitten#1153]
## 💬 Question

Hi ! 

Is there a way that an `OverflowMenu` can have an automatic size? Or a way to pass him a size, so far I pass him a height but it seems blocked around 250

```js
<OverflowMenu
        style={{ width: DEVICE.width / 2 }}
        anchor={renderToggleButton}
        placement='left start'
        visible={visible}
        onBackdropPress={() => setVisible(false)}
>
        {menuItems.map((item) => (
            (item.condition) && (
                <View style={styles.row}>
                    <MenuItem
                        title={item.title}
                        accessoryLeft={item.icon}
                        onPress={() => {
                            setVisible(false)
                            return item.event()
                        }}
                  />
              </View>
         )))}
</OverflowMenu>
```

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    ^2.0.0-alpha.1    |
| @ui-kitten/components   |    ^5.0.0-alpha.1     |

**Comment by artyorsh** [comment]
@ArthurDelbeke you can do it by setting maxHeight: https://snack.expo.io/Z3h3PCqJs

**Comment by artyorsh** [comment]
Btw, setting `null` will do the trick with automatic sizing
