### ISSUE TITLE
Tab Bar display issues on React Native Web

### ISSUE THREAD

**Issue by jackow98** [akveo/react-native-ui-kitten#1154]
## 🐛 Bug Report
When nesting TabBar components on react native web, the nested tab bar and all of its tabs shift left when using navigation within the nested tab. 

[Video of the problem](https://drive.google.com/file/d/15WtttS7GRRDu6RyB6Y39Q3Vge2iQWCSB/view?usp=sharing)

## To Reproduce

Steps to reproduce the behaviour:
- There is a Navigator with `MainTabs` as a screen
- `MainTabs` has multiple screens with their own navigators and uses the UI Kitten `TabBar` component 
- The screens with their own navigators within `MainTabs` also use the UI Kitten `TabBar` component
-  Calling `navigation.navigate` within a nested tab then going back to the nested tab causes the nested tabs to shift to the right and display a section of the adjacent nested tabs

## Expected behavior
Only display nested tab for current tab

## UI Kitten and Eva version
"@eva-design/eva": "^2.0.0",
"@ui-kitten/components": "^5.0.0",

## Environment information
```bash
  System:
    OS: Linux 4.4 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  Binaries:
    Node: 13.12.0 - ~/.nvm/versions/node/v13.12.0/bin/node
    Yarn: 1.21.1 - /mnt/c/Program Files (x86)/Yarn/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v13.12.0/bin/npm
  SDKs:
    Android SDK:
      API Levels: 28
      Build Tools: 28.0.3
```

**Comment by artyorsh** [comment]
@jackow98 could you please upload a minimal repo to reproduce that?

**Comment by Corliansa** [comment]
I have this same problem, the TabView becomes buggy after using react native navigation
