### ISSUE TITLE
ViewPager Null Skip

### ISSUE THREAD

**Issue by GantMan** [akveo/react-native-ui-kitten#1159]
#### In ViewPager, if a section returns null, it still gets a page.

I'm hoping to do some conditional pages (in a wizard), and when I do a conditional section like 

```
{ false && 
<Layout>

</Layout>
}  
```

It still renders the entire child as an empty spot.   Ideally, this empty child would be skipped in a pager, thus giving me the ability to optionally show certain steps in onboarding in a pager as long as the index size doesn't shrink.

## To Reproduce

Return null for any child in viewpager

## Expected behavior

Null children should not be rendered, just like they aren't rendered in react.

## Link to runnable example or repository (highly encouraged)

https://snack.expo.io/6NRfntmPi

Scroll right on the example.   The empty page is the issue.

**Comment by artyorsh** [comment]
Hi 👋  
This is most likely a feature request rather than a but report, since currently you may filter optional children by your own
However, I agree this should be handled out of the box. Thanks for pointing on this 👍
