### ISSUE TITLE
MenuGroup onToggle prop missing

### ISSUE THREAD

**Issue by foubei** [akveo/react-native-ui-kitten#1160]
## 🚀 Feature Proposal

Since the **MenuGroup** can play the role of an Accordion and would love if we can have an event when the **toggle** prop changes. So that we can add any action regarding to **onToggle** event.

In my case, I would scroll down to the opened content, it's more friendly than letting the user scrolling down by himself which quite annoying.
![Screenshot_1593008715](https://user-images.githubusercontent.com/12202571/85574735-9c666900-b669-11ea-9894-049e537e83a4.png)
![Screenshot_1593008717](https://user-images.githubusercontent.com/12202571/85574757-a12b1d00-b669-11ea-84e4-117841618f95.png)

**Comment by AntonBorovoi** [comment]
Hi @foubei 
For `MenuGroup` `onPress` callback was fixed within https://github.com/akveo/react-native-ui-kitten/pull/1339
I guess we can use it as an alternative for `onToggle` and this should cover most of the cases

What do you think?

**Comment by bataevvlad** [comment]
Closing the problem because it was fixed in related PR, with respect the team UI Kitten
