### ISSUE TITLE
How to style the TopNavigation title text.

### ISSUE THREAD

**Issue by matale** [akveo/react-native-ui-kitten#1161]
## 💬 Question
Can the TopNavigation Title be styled? I want to change the color to white while the bar itself is red. Currently I am able to set the background to red but not the color or style of the label.

`   <TopNavigation title="News" alignment="center" style={styles.topBar} />`

` .... topBar: {
    fontSize: 18,
    fontWeight: "bold",
    backgroundColor: "#d2232a",
    color: "#9C27B0",
  },`

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2.0.0    |
| @ui-kitten/components   |   5.0.0      |

**Comment by artyorsh** [comment]
Yes it can, please see the docs for examples.
In a few words, you can pass a component to a `title` prop instead of passing strings, e.g:
`title={props => <Text {...props} style={[props.style, { color: 'red }]}>TITLE</Text>}`

**Comment by vtabunov** [comment]
> Yes it can, please see the docs for examples.
> In a few words, you can pass a component to a `title` prop instead of passing strings, e.g:
> `title={props => <Text {...props} style={[props.style, { color: 'red }]}>TITLE</Text>}`

you forgot the semicolon after 'red', but the answer is right! thank you! the right variant will be:

title={props => <Text {...props} style={[props.style, { color: 'red' }]}>TITLE</Text>}
