### ISSUE TITLE
How to do custom component mapping using a functional component.

### ISSUE THREAD

**Issue by gimli01** [akveo/react-native-ui-kitten#1162]
## 💬 Question

In the documentation it says that the `styled` decorator can be used on class components, but what if we don't want to write out an actual class component such as 

```typescript
@style('BrandButton')
export class BrandButton extends React.PureComponent<any>{}
```
and instead we wanted to use functional components that will inherit the styles

```typescript
export const BrandButton = (props:any) => {}
```

or is this what the `withStyles` function was intended for. Although this function only seems to grab variables from the theme and doesn't do any custom component mapping itself.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      | 2.0.0|
| @ui-kitten/components   |5.0.0|

**Comment by artyorsh** [comment]
> and instead we wanted to use functional components

No way to use it with `styled` function yet.

> this function only seems to grab variables from the theme

That's what the docs say

**Comment by 3kumar** [comment]
Any update on if the hook will be available soon, or we need to implement it ourselves?

**Comment by freshedgarT** [comment]
I am in the midts of updating to 5. but since I am using mostly FCs the masking of styled HOC in a decorator doesn't work in my case. Therefore I am trying a hook alternative.
Here are some thoughts on your hook. You should try to not return new values each time the hook is executed (i.e. on every render). This could have significant performance impact. My first approach would be to memo basically everything. 

This is my version of your hook.
```
export function useStyled(name: string, sourceProps: Record<string, any>) {
  const [interaction, setInteraction] = React.useState([]);
  const mappingStyle = useContext(MappingContext);
  const evaTheme = useContext(ThemeContext);

  const service = useMemo(() => new StyleConsumerService(name, mappingStyle), [name, mappingStyle]);
  const defaultProps = useMemo(() => service.createDefaultProps(), [service]);

  const computedProps = useMemo(() => ({ ...defaultProps, ...sourceProps }), [defaultProps, sourceProps]);
  const computedStyle = useMemo(() => service?.createStyleProp(computedProps, mappingStyle, evaTheme, interaction), [
    service,
    computedProps,
    mappingStyle,
    evaTheme,
    interaction
  ]);
  return useMemo(
    () => ({
      ...computedProps,
      eva: {
        theme: evaTheme,
        style: computedStyle,
        dispatch: (newInteraction: any) => setInteraction(newInteraction)
      }
    }),
    [computedProps, evaTheme, computedStyle]
  );
}
```

**Comment by iMarvinS** [comment]
Is there any progress regarding the useStyled hook?

**Comment by RWOverdijk** [comment]
You can just use the hoc. I agree it's not ideal, but it works and doesn't require two types to be maintained.

```jsx
interface FooterProps extends StyledComponentProps { }

function FooterComponent({ eva: { style } = {}, ...props }: FooterProps) {
  return (
    <View style={[FooterStyle.container, style]}>
      <ExternalLink href="https://example.com/">Go to Example.com!</ExternalLink>
    </View>
  )
}

export const Footer = styled('Footer')(FooterComponent);
```

Silver linings... The upside is that you don't have to proxy your props in a hook.

Also I suppose it's easier to mock the component when running tests. Otherwise the code from @freshedgarT look good to me. 

@artyorsh is this something that could be added to ui kitten? I think it would be nice to have. I changed it a bit to make the prop types remain:

```ts
import { StyledComponentProps } from '@ui-kitten/components/theme/style/styled';
import { useCallback, useContext, useMemo, useState } from 'react';
import { MappingContext } from '@ui-kitten/components/theme/mapping/mappingContext';
import { ThemeContext } from '@ui-kitten/components/theme/theme/themeContext';
import { StyleConsumerService } from '@ui-kitten/components/theme/style/styleConsumer.service';

export function useStyled<T>(name: string, sourceProps: T): T & StyledComponentProps {
  const [interaction, setInteraction] = useState([]);
  const mappingStyle = useContext(MappingContext);
  const theme = useContext(ThemeContext);
  const service = useMemo(() => new StyleConsumerService(name, mappingStyle), [name, mappingStyle]);
  const defaultProps = useMemo(() => service.createDefaultProps(), [service]);
  const computedProps = useMemo(() => ({ ...defaultProps, ...sourceProps }), [defaultProps, sourceProps]);
  const dispatch = useCallback((newInteraction: any) => setInteraction(newInteraction), [setInteraction]);
  const style = useMemo(() => service?.createStyleProp(computedProps, mappingStyle, theme, interaction), [
    service,
    computedProps,
    mappingStyle,
    theme,
    interaction
  ]);

  return useMemo(() => ({
    ...computedProps,
    eva: { theme, style, dispatch }
  }), [computedProps, theme, style]);
}
```

Usage:
```tsx
import React from 'react';
import { View } from 'react-native';
import { FooterStyle } from './Footer.style';
import { ExternalLink } from '../ExternalLink';

import { useStyled } from '../../lib/hooks/useStyled';

interface FooterProps { }

export function Footer(props: FooterProps) {
  const { eva: { style = null } = {} } = useStyled('Footer', props);

  return (
    <View style={[FooterStyle.container, style]}>
      <ExternalLink href="https://google.com/">Go to link!</ExternalLink>
    </View>
  )
}
```

**Comment by artyorsh** [comment]
Hey @RWOverdijk thanks for giving a detailed answer here. I'm going to close that since we have an answer for that. Let's move to https://github.com/akveo/react-native-ui-kitten/issues/1436 to track the hook API feature request

**Comment by evansendra** [comment]
was a hook-based solution ever integrated?  Can't find anything about it in the docs or outside this issue
