### ISSUE TITLE
List with Typescript in React Native

### ISSUE THREAD

**Issue by gcrespe** [akveo/react-native-ui-kitten#1167]
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      | 2.0.0  |
| @ui-kitten/components   |  5.0.0 |

    const renderItem = (item: any) => (
        <ListItem
          title={`${item.title}`}
          description={`${item.description}`}
        />
      );
    
    return(
        <View>
            <List
            style={styles.container}
            data={data}
            ItemSeparatorComponent={Divider}
            renderItem={renderItem}
            />
        </View>
    )}

Well, I'm facing many issues when implementing a List component, because when I try to type the return of the renderItem function as ListRenderItem<any>, the error that comes is "Type element is not assignable to type ListRenderItem<any>". 
If I leave  the code as it is in the Components section, I get a many undefined list items.

Could someone give me a light? I'm really confused right now.

**Comment by artyorsh** [comment]
> Type element is not assignable to type ListRenderItem

As per the declaration, ListRenderItem is a function and not a return type of `renderItem` prop:
```
export type ListRenderItem<ItemT> = (info: ListRenderItemInfo<ItemT>) => React.ReactElement | null;
```

I suggest you looking through [this doc](https://react-typescript-cheatsheet.netlify.app/docs/advanced/types_react_api) to become familiar with type system.

> I get a many undefined list items.
What do you mean with that? Typescript typings can't affect the runtime.

**Comment by gcrespe** [comment]
> What do you mean with that? Typescript typings can't affect the runtime.

When I said that I get undefined list items, its exactly that. When I compile and run the project on an emulator, all of the list items are undefined.

> That means that ListRenderItem is a type definition for renderItem prop, and it should return React.ReactElement.
I suggest you looking through this doc to become familiar with type system.

Thanks for the hint! I'll take a time to read the documentation 

But actually I cant see how I could make progress with that, because if I make item as a ListRenderItemInfo<ItemT>, I cant access title and description

**Comment by artyorsh** [comment]
> because if I make item as a ListRenderItemInfo

You're missing the access to `item` property of the `renderItem` argument. Please be advised to read more about RN type definitions. You should have the ability to navigate to the type definitions in your IDE if you have `@types/react-native` package installed. In a few words: `title={item.item.title}`

https://facebook.github.io/react-native/docs/flatlist.html#props

```
export interface ListRenderItemInfo<ItemT> {
    item: ItemT;

    index: number;

    separators: {
        highlight: () => void;
        unhighlight: () => void;
        updateProps: (select: 'leading' | 'trailing', newProps: any) => void;
    };
}
```
