### ISSUE TITLE
Modal Error (Cannot update during an existing state transition)

### ISSUE THREAD

**Issue by RenatoSerra22** [akveo/react-native-ui-kitten#1172]
## 🐛 Bug Report

When rendering a modal, setting the **prop of visible** to any value causes an error of: "**Warning: Cannot update during an existing state transition  (such as within `render`). Render methods should be a pure function of props and state**".
Removing the set of **visible prop** stops the warning, but doesnt display the modal as it defaults to false.

## To Reproduce

Render a Modal

```
import React from "react";
import { Modal, Card, Text, Button } from "@ui-kitten/components";
import { StyleSheet } from "react-native";

export default ErrorModal = ({ error, clearErrors }) => {
  return (
    <Modal
      visible={true}
      backdropStyle={styles.backdrop}
      onBackdropPress={() => clearErrors()}
    >
      <Card disabled={true}>
        <Text style={styles.text}>{error.message}</Text>
        <Button
          style={styles.button}
          onPress={() => clearErrors()}
          status='danger'
          size='medium'
        >
          Ok
        </Button>
      </Card>
    </Modal>
  );
};

const styles = StyleSheet.create({
  container: {
    minHeight: 192,
  },
  backdrop: {
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  button: {
    marginTop: 20,
    alignSelf: "center",
  },
  text: {
    fontSize: 18,
  },
});

```
## Expected behavior

Shouldnt cause an error.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2.0.0    |
| @ui-kitten/components   |    5.0.0     |

**Comment by artyorsh** [comment]
Please see https://github.com/akveo/react-native-ui-kitten/issues/1094#issuecomment-630141254

**Comment by dozsolti** [comment]
It shouldn't be closed THE PROBLEM STILL EXISTS!!!
