### ISSUE TITLE
How to style DatePicker to avoid date in input to be gray when status is basic?

### ISSUE THREAD

**Issue by psegalen** [akveo/react-native-ui-kitten#1173]
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    ^2.0.0-alpha.1    |
| @ui-kitten/components   |    ^5.0.0     |

Hi! I'm using DatePicker component which is great but when in "basic" status, the date inside the input is coloured in gray which can be hard to read, how could I turn it into black to match the other inputs in basic status in my form and also to make it look different from the placeholder?
I've seen `controlStyle` but it just ignores the `color` prop.

**Comment by artyorsh** [comment]
@psegalen this can be achieved by following [this guide](https://akveo.github.io/react-native-ui-kitten/docs/design-system/customize-mapping#customize-component-mapping).

**Comment by rmarquois** [comment]
Hello,

I'm also using DatePicker component and I made the same observation. Indeed we can customize it using "Component Mapping" but I think there is a mistake in input rendering code.

I see at [this line](https://github.com/akveo/react-native-ui-kitten/blob/master/src/components/ui/datepicker/baseDatepicker.component.tsx#L229) that placeholder color is never used. Text color is always used instead.

I think placeholder color should be used when input is empty and text color when input is filled. What do you think of that ?

Regards.
