### ISSUE TITLE
Disabled button looks weird on Android 7.0

### ISSUE THREAD

**Issue by Rawphs** [akveo/react-native-ui-kitten#1174]
## 🐛 Bug Report

On Android 7.0 the disabled button behaves very oddly. I can only assume it's because the background color is somewhat transparent, because when I changed the style to use a normal hex color it didn't happen.
![Screenshot_1593707335](https://user-images.githubusercontent.com/17144983/86386413-01394900-bc92-11ea-9cfc-4c94ee361f02.png)

## To Reproduce

In my screen there's nothing really interesting in my screen so I assume that any disabled button will do. It just needs to be tested in an old android version. For now I will just set the color myself, but I thought you should know that this is happening.

## Expected behavior

I expected to see a uniform color.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   2.0.0     |
| @ui-kitten/components   |   5.0.0      |

## Environment information

```bash
System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 27.0.3, 28.0.3
      System Images: android-24 | Google Play Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: ~16.9.0 => 16.9.0
    react-native: ~0.61.4 => 0.61.5
```

**Comment by RWOverdijk** [comment]
Confirmed. I have the same issue. It is due to transparency.

**Comment by bataevvlad** [comment]
The problem was tested on the last current version of the package, there were no problems, below are attached screenshots of inactive buttons. 

If the problem still occurs, please write in the ticket, respectfully Vladislav.
<img width="346" alt="Screen Shot 2023-05-15 at 1 34 24 PM" src="https://github.com/akveo/react-native-ui-kitten/assets/24460899/2d778404-de42-4b70-9cfe-4875734e39c5">
