### ISSUE TITLE
Multiline input text starts from the center of the input vertically 

### ISSUE THREAD

**Issue by mukurpuri** [akveo/react-native-ui-kitten#1176]
UI Kitten is love. 

I realized that when I set the multiline property to input and set number of lines, the input becomes textarea but the text starts from the center vertically. How can I start from start i.e beginning?

<img width="287" alt="Screenshot 2020-07-04 at 1 23 38 PM" src="https://user-images.githubusercontent.com/10636579/86507938-9d319480-bdf9-11ea-838a-0fe34668f62a.png">

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   2.0.0     |
| @ui-kitten/components   |   5.0.0     |

**Comment by arminghm** [comment]
User [textAlignVertical ](https://reactnative.dev/docs/textinput#multiline) property of TextInput. `textAlignVertical : 'top'`
