### ISSUE TITLE
2 times click to focus input

### ISSUE THREAD

**Issue by Atww** [akveo/react-native-ui-kitten#1177]
![Screen-Recording-2563-07-08-at-1](https://user-images.githubusercontent.com/35207756/86875253-433c1200-c10c-11ea-8cb5-2e51a399179f.gif)

{
  "name": "LearningReactNative",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@eva-design/eva": "^2.0.0",
    "@react-native-community/async-storage": "^1.11.0",
    "@react-native-community/geolocation": "^2.0.2",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/bottom-tabs": "^5.6.0",
    "@react-navigation/drawer": "^5.8.4",
    "@react-navigation/material-top-tabs": "^5.2.11",
    "@react-navigation/native": "^5.5.1",
    "@react-navigation/stack": "^5.5.1",
    "@ui-kitten/components": "^5.0.0",
    "@ui-kitten/eva-icons": "^5.0.0",
    "lottie-ios": "^3.1.3",
    "lottie-react-native": "^3.4.0",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-camera": "^3.31.0",
    "react-native-device-info": "^5.6.1",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-reanimated": "^1.9.0",
    "react-native-safe-area-context": "^3.0.6",
    "react-native-screens": "^2.9.0",
    "react-native-settings": "^0.2.3",
    "react-native-spinkit": "^1.5.0",
    "react-native-svg": "^12.1.0",
    "react-native-tab-view": "^2.14.4",
    "styled-components": "^5.1.1"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "@ui-kitten/metro-config": "^5.0.0",
    "babel-jest": "^24.9.0",
    "eslint": "^6.5.1",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.58.0",
    "react-test-renderer": "16.11.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

Code here 
`import React,{useEffect} from 'react';
import { SafeAreaView,Alert,StyleSheet,View } from 'react-native';
import {
    Input,
    Button,
    Divider,
    Icon,
    Layout,
    Text,
    TopNavigation,
    TopNavigationAction, Spinner
} from '@ui-kitten/components';
import {UrlContext} from '../../context/url';
import Loader from '../../components/components/spinner/Loader'
const BackIcon = (props) => (
    <Icon {...props} name='arrow-back' />
);
const StarIcon = (props) => (
    <Icon {...props} name='people-outline'/>
);

export const Attend_Home = ({route, navigation }) => {
    const urlContext = React.useContext(UrlContext);
    const [isLoading, setIsLoading] = React.useState(false);
    const [value, setValue] = React.useState('');

    const BackAction = () => (
        <TopNavigationAction icon={BackIcon} onPress={navigateBack}/>
    );
    const navigateBack = () => {
        navigation.goBack();
    };
    const setNewUrl = ()=>{
        if(urlContext.url){
            setIsLoading(true);
            fetch(`${urlContext.url}Foreman`, {
                method: 'POST',
                headers: {
                    Accept: 'application/json',
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({
                    foremancode: value,
                    // password:data.lastName
                }),
            })
                .then((response) => response.json())
                .then((json) => {
                    if (json.status == 1) {
                        setIsLoading(false);

                        navigation.push('Project', {
                            foremancode: value,
                            forman_f_name: json.data.foremanfirstname,
                            forman_l_name: json.data.foremanlastname,
                        });
                    } else if (json.status == 0) {

                        Alert.alert(
                            'Warning',
                            json.message,
                            [
                                {
                                    text: 'ตกลง',
                                    onPress: () => {
                                        setIsLoading(false);

                                    },
                                    style: 'cancel',
                                },
                            ],

                            {cancelable: false},
                        );

                    } else {
                        Alert.alert(
                            'Error',
                            "เกิดข้อผิดพลาดในการติดต่อข้อมูลจาก Server",
                            [
                                {
                                    text: 'ตกลง',
                                    onPress: () => {
                                        setIsLoading(false);

                                    },
                                    style: 'cancel',
                                },
                            ],

                            {cancelable: false},
                        );

                    }
                })
                .catch((error) => {
                    Alert.alert(
                        'เกิดข้อผิดพลาด',
                        "กรุณาแจ้งเจ้าหน้าที่ :"+error,
                        [
                            {
                                text: 'ตกลง',
                                onPress: () => {
                                    setIsLoading(false);

                                },
                                style: 'cancel',
                            },
                        ],

                        {cancelable: false},
                    );
                });
            ;
        }else{
            Alert.alert('เกิดข้อผิดพลาด','เกิดข้อผิดพลาดการเรียก Url')
        }
    }

    return (
        <SafeAreaView style={{ flex: 1 }}>
            <TopNavigation title='สแกนเข้างาน' alignment='center' accessoryLeft={BackAction}/>
            <Divider/>
            <Layout style={{ flex: 1, justifyContent: "center"}}>
                <Text style={{alignSelf:"center"}} category={"h4"}>หัวหน้างาน</Text>
                <Divider/>
                <Loader loading={isLoading}/>
                <Input
                    placeholder='พิมพ์ชื่อโครงการที่ต้องการค้นหา'
                    value={value}
                    onChangeText={nextValue => setValue(nextValue)}
                    keyboardType={'number-pad'}
                    onFocus={()=>console.log('here')}
                    onBlur={()=>console.log('blur')}
                />
                <Button style={styles.button} status='primary' accessoryLeft={StarIcon} onPress={()=>setNewUrl()}>
                    <Text style={styles.texts}>ตรวจสอบรหัสหัวหน้างาน</Text>
                </Button>
            </Layout>
        </SafeAreaView>
    );

};
const styles = StyleSheet.create({
    container: {
        flexDirection: 'row',
        flexWrap: 'wrap',
    },
    button: {
        margin: 2,
        marginTop:20
    },
    indicator: {
        justifyContent: 'center',
        alignItems: 'center',
    },texts:{
        fontSize:18,
        color:"white"
    }
});
`

**Comment by artyorsh** [comment]
@Atww I'm not able to reproduce that with a regular implementation. [See the example](https://snack.expo.io/Dw1OhDmmf) and please make sure this is not related to the business-logic you've shared.
