### ISSUE TITLE
SelectItem hijacks onPress such that Select will not auto-close if it's overridden

### ISSUE THREAD

**Issue by Jahans3** [akveo/react-native-ui-kitten#1178]
## 🐛 Bug Report
The docs state that `SelectItem` extends `TouchableWithoutFeedback` props. I need to use `SelectItem.onPress` since `Select`/`SelectItem` don't support object values and I need to populate `SelectItem.title` with a human-readable value while populating my form with a related value that isn't very user-friendly.

To achieve this I simply override `SelectItem.onPress`:

```js
<Select
  placeholder="How often?"
  selectedIndex={selectIndex}
  value={values.interval.title}
  onSelect={setSelectIndex}>
  {intervalOptions.map(({ title, name }) => (
    <SelectItem
      title={title}
      onPress={() => {
        setFieldValue('interval', { title, name });
      }}
    />
  ))}
</Select>
```

This works almost as intended, however it does not close the dropdown once an option is selected. If I remove the `onPress` it works as expected (although obviously it displays "Option 1/2/3/etc" since `value` has not been populated.

## To Reproduce
1. Create a Select
2. Add SelectItem children
3. Set onPress on SelectItem elements
4. Form will not auto-close when item is selected

## Expected behavior
I should be able to extend `SelectItem.onPress` and pass custom handlers while not breaking intended functionality.

## Link to runnable example or repository (highly encouraged)

Link to Snack: https://snack.expo.io/rzVSndaEs

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      | 2.0.0       |
| @ui-kitten/components   | 5.0.0        |

## Environment information
```bash
  System:
    OS: macOS 10.15.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 14.4.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  npmPackages:
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1

```

**Comment by Jahans3** [comment]
So I just forked the repo in order to create the fix myself and I noticed the `onPressIn` prop already doing the same job, using that prop fixes the issue :)

**Comment by artyorsh** [comment]
@Jahans3 I would suggest following the documentation examples and use `onSelect` prop for modifying state.
```
const [selectedIndex, setSelectedIndex] = React.useState(null);

const onSelect = (index) => {
  setSelectedIndex(index);
  setFieldValue(intervalOptions[selectedIndex.row]);
};

<Select 
  selectedIndex={selectedIndex}
  value={intervalOptions[selectedIndex.row].title}
  onSelect={onSelect}
/>
```
