### ISSUE TITLE
Not working with React Native 0.63.0

### ISSUE THREAD

**Issue by evilchis94** [akveo/react-native-ui-kitten#1179]
## 🐛 Bug Report

I just started a new project using React Native 0.63 and then installed Ui Kitten but throws this error `TypeError: null is not an object (evaluating 'Object.keys(styles[name])')`

## To Reproduce

1. npx react-native init MyApp
2. yarn add @ui-kitten/components @eva-design/eva react-native-svg
3. npx pod-install
4. Configure App.js

<img width="703" alt="Captura de Pantalla 2020-07-09 a la(s) 12 48 24" src="https://user-images.githubusercontent.com/10981327/87073129-836dc400-c1e2-11ea-89de-576ebfec6823.png">

5. Open .xworkspace in Xcode and run project.

## Expected behavior

It should run without errors and show a "Home" text.
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2.0.0    |
| @ui-kitten/components   |     5.0.0    |

## Environment information

System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 25, 28, 29
      Build Tools: 26.0.3, 27.0.3, 28.0.2, 28.0.3, 30.0.0, 30.0.0
      System Images: android-29 | Google Play Intel x86 Atom, android-Q | Android TV Intel x86 Atom
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  npmPackages:
    react: 16.13.1 => 16.13.1
    react-native: 0.63.0 => 0.63.0

```bash

```

**Comment by rnds** [comment]
I'm getting the same error trying to upgrade my project from RN 0.62 => RN 0.63

<img width="380" alt="Screen Shot 2020-07-09 at 2 29 08 PM" src="https://user-images.githubusercontent.com/54993955/87082426-a30be900-c1f0-11ea-8391-73e7668bde2b.png">

**Comment by rnds** [comment]
I think it's is RN issue.   

See this commit:
https://github.com/facebook/react-native/commit/e75557b48fbee1d136b8b7d1a78ea8f9b9467479

I added these lines and it works for me now.

**Comment by Karniej** [comment]
I added those lines & it works for me know, but I hope this change will get merged to RN asap .

**Comment by RatebSeirawan** [comment]
+1

**Comment by artyorsh** [comment]
@evilchis94 thanks for reporting this.
It seems like this issue was already fixed internally (see https://github.com/facebook/react-native/pull/29171), and we should expect  I would suggest considering not upgrading to 0.63 yet. It's also more likely we should expect this in the [upcoming patch release](https://github.com/react-native-community/releases/issues/199).

**Comment by shawngustaw** [comment]
Looks like this is still broken in 0.63.1

**Comment by aganov** [comment]
Also it would be great if we replace `TouchableOpacity` with `Pressable` in the future releases of ui-kitten.

**Comment by codler** [comment]
I hope this gets fixed soon as im looking for a ui replacement of Native-base

**Comment by alexmgrant** [comment]
Looks like it's the `master` branch, but `master` has a failing test, so not yet pushed to npm?

**Comment by saihaj** [comment]
Should be fixed now https://github.com/facebook/react-native/releases/tag/v0.63.2

**Comment by tomcastro** [comment]
It is fixed now, just tested it :)

**Comment by artyorsh** [comment]
Yep. It works
Thanks everyone for the notice, especially @saihaj for cherry-pick request 🚀

**Comment by rardoz** [comment]
I did a fresh install today and am on react native 0.63.2 and I'm getting this issue.
