### ISSUE TITLE
Failed prop type on iOS < 13 and Android 5.x

### ISSUE THREAD

**Issue by CostachescuCristinel** [akveo/react-native-ui-kitten#1180]
## 💬 Question
I have a project developed under Expo SDK 38 / React 16.11.0 / React Native 0.62.
Everything works fine when I run it under iOS 13 or Android 9+. However, running it under a previous version of these OSs, all sorts of `Failed prop type` errors showed in the console. The UI is completely broken on these.

This is how the project looks like on iOS 13.x  and Android 9+:
(the green rectangles are added manually to cover some logos and login information)
![Screenshot 2020-07-09 at 20 01 51](https://user-images.githubusercontent.com/52235106/87069272-92269c00-c21f-11ea-87d6-68fd0d39bd8c.png) ![Screenshot 2020-07-09 at 20 03 25](https://user-images.githubusercontent.com/52235106/87069273-93f05f80-c21f-11ea-8680-a1d76410982b.png)

And this is how it looks like on iOS 12 and lower (same on Android 5.x emulator)
![Screenshot 2020-07-09 at 20 00 30](https://user-images.githubusercontent.com/52235106/87069363-c00be080-c21f-11ea-8ff2-80ea83de9ef0.png) ![Screenshot 2020-07-09 at 19 59 14](https://user-images.githubusercontent.com/52235106/87069370-c1d5a400-c21f-11ea-9425-26f239f4e447.png) ![Screenshot 2020-07-09 at 20 04 39](https://user-images.githubusercontent.com/52235106/87069380-c306d100-c21f-11ea-82e5-ae995a1508ca.png)

These are the errors logged in the console:

```
Warning: Failed prop type: Invalid prop `placeholderTextColor` supplied to `ForwardRef(TextInput)`: text-hint-color
Valid color formats are
  - '#f0f' (#rgb)
  - '#f0fc' (#rgba)
  - '#ff00ff' (#rrggbb)
  - '#ff00ff00' (#rrggbbaa)
  - 'rgb(255, 255, 255)'
  - 'rgba(255, 255, 255, 1.0)'
  - 'hsl(360, 100%, 100%)'
  - 'hsla(360, 100%, 100%, 1.0)'
  - 'transparent'
  - 'red'
  - 0xff00ff00 (0xrrggbbaa)
```
```
Warning: Failed prop type: Invalid prop `color` supplied to `ForwardRef(TextInput)`: text-basic-color
Valid color formats are
  - '#f0f' (#rgb)
  - '#f0fc' (#rgba)
  - '#ff00ff' (#rrggbb)
  - '#ff00ff00' (#rrggbbaa)
  - 'rgb(255, 255, 255)'
  - 'rgba(255, 255, 255, 1.0)'
  - 'hsl(360, 100%, 100%)'
  - 'hsla(360, 100%, 100%, 1.0)'
  - 'transparent'
  - 'red'
  - 0xff00ff00 (0xrrggbbaa)

Bad object: {
  "marginHorizontal": 8,
  "fontFamily": "regular",
  "fontSize": 15,
  "fontWeight": "normal",
  "color": "text-basic-color",
  "flexGrow": 1,
  "flexShrink": 1,
  "flexBasis": "auto"
}
```
```
Warning: Failed prop type: Invalid prop `tintColor` supplied to `Image`: text-hint-color
Valid color formats are
  - '#f0f' (#rgb)
  - '#f0fc' (#rgba)
  - '#ff00ff' (#rrggbb)
  - '#ff00ff00' (#rrggbbaa)
  - 'rgb(255, 255, 255)'
  - 'rgba(255, 255, 255, 1.0)'
  - 'hsl(360, 100%, 100%)'
  - 'hsla(360, 100%, 100%, 1.0)'
  - 'transparent'
  - 'red'
  - 0xff00ff00 (0xrrggbbaa)

Bad object: {
  "width": 20,
  "height": 20,
  "marginHorizontal": 8,
  "tintColor": "text-hint-color"
}
```
```
Warning: Failed prop type: Invalid prop `color` supplied to `Text`: text-hint-color
Valid color formats are
  - '#f0f' (#rgb)
  - '#f0fc' (#rgba)
  - '#ff00ff' (#rrggbb)
  - '#ff00ff00' (#rrggbbaa)
  - 'rgb(255, 255, 255)'
  - 'rgba(255, 255, 255, 1.0)'
  - 'hsl(360, 100%, 100%)'
  - 'hsla(360, 100%, 100%, 1.0)'
  - 'transparent'
  - 'red'
  - 0xff00ff00 (0xrrggbbaa)

Bad object: {
  "color": "text-hint-color",
  "fontSize": 12,
  "fontWeight": "400",
  "fontFamily": "regular",
  "width": "50%",
  "minWidth": 290,
  "marginBottom": 10,
  "textAlign": "center"
}
```

I have checked for issues with package dependencies, it seems everything is fine. I had issues with `react-native-svg@12.x.x` in the past, I have tried with `react-native-svg@9.13.6` (minimum required by UI Kitten), but other than multiple warnings of incorrect dependencies, I have no better result.

I also have a metro configuration file used to apply a custom mapping, but even removing it does not help - so I think it's not the issue.

Can you help me figure out what is wrong ?

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva | 2.0.0 |
| @ui-kitten/components | 5.0.0 |
| metro-config | 0.60.0 |
| expo | SKD 38 |
| react | 16.11.0 |
| react-native | 0.62 |
| react-native-svg | ^9.13.6 / ^12.1.0 |

**Comment by CostachescuCristinel** [comment]
I was messing with the packages, and I have noticed this warning:
```
warning "@ui-kitten/eva-icons > react-native-eva-icons@1.3.1" has incorrect peer dependency "react@16.5.0".
```

Maybe this has anything to do with the above issue?

For Expo SDK 38 the exact version of `react@16.11.0` is needed, trying to use `@16.5.0` fails to even start the project.

**Comment by CostachescuCristinel** [comment]
@artyorsh Tagging you here in case you missed this post, I would really appreciate your help as the project I'm working on is for a client and it's critical for it to work on older OS versions too...

I have made a backport of the project back to Expo SDK 37 (react@16.9.0, react-native@0.61.0).
The same issue happens.

**Comment by CostachescuCristinel** [comment]
Hi, does anyone have any idea what could be the issue ?

**Comment by artyorsh** [comment]
@CostachescuCristinel 
How is the ApplicationProvider configured in your case? According to the last two screenshots, it seems that the components simply do not receive their stylings

**Comment by CostachescuCristinel** [comment]
Hi, I have the setup as follows below:

metro.config.js
```
const MetroConfig = require("@ui-kitten/metro-config");

const evaConfig = {
	evaPackage: "@eva-design/eva",
	// Optional, but may be useful when using mapping customization feature.
	customMappingPath: "./theme/mapping.json",
};

module.exports = MetroConfig.create(evaConfig);
```

App.js
```
import * as eva from "@eva-design/eva";
import { ApplicationProvider as UIKittenProvider, IconRegistry, Layout } from "@ui-kitten/components";
import branding from "./theme/branding.json"; // custom JSON for branding colors

import { Provider as ReduxProvider, connect } from "react-redux";
import { store, actions } from "./redux";


// Using Redux
const Main = connect(
	(state) => ({ theme: state.theme }),
	{ ...actions.theme, ...actions.authentication.signIn, ...actions.device }
)(class extends React.Component {
	// ( ... )

	render = () => {
		// From redux, currentTheme is either "light" or "dark"
		// in case of any failure, currentTheme defaults to "light"
		// statusBarTheme is the opposite of currentTheme
		const { currentTheme, statusBarTheme } = this.props.theme;

		const UIKittenTheme = {
			...eva[currentTheme],
			...branding
		};

		if (this.state.loading === true) {
			return <AppLoading
				startAsync={this.onStartLoading}
				onFinish={this.onFinishLoading}
				onError={console.error}
			/>;
		}

		return <>
			{/* <IconRegistry icons={EvaIconsPack} /> // Not using Icons at the moment */}
			<StatusBar translucent={true} style={statusBarTheme} />
			<UIKittenProvider {...eva} theme={UIKittenTheme}>
				<Layout style={{ flex: 1 }}>
					{/* React navigation 5 navigation containers and screens, ect. */}
				</Layout>
			</UIKittenProvider>
		</>;
	}
});

// Need to separate the Main app from this part so the Redux
// store gets initialized and mounted before being used in <Main />
// <Main /> initialization will be delayed by the connect() function
// until the redux store is available
export default function (props) {
	return <ReduxProvider store={store}>
		<AppearanceProvider>
			<Main />
		</AppearanceProvider>
	</ReduxProvider>;
}
```

**Comment by CostachescuCristinel** [comment]
@artyorsh I have taken the time to strip out all the code from the app to a bare-minimum version that still reproduces the issue, with redux and some parts of the app. You can find it in this zip file (wetransfer link expires in 1 week)
https://we.tl/t-Oo4htCySP7

iPhone 11 Pro Max / iOS 13.5 (simulator)
![Screenshot 2020-07-14 at 18 39 30](https://user-images.githubusercontent.com/52235106/87445968-62054180-c601-11ea-9478-3556d95f757f.png)
iPhone SE (1st gen) / iOS 10.3.5 (simulator)
![Screenshot 2020-07-14 at 18 38 46](https://user-images.githubusercontent.com/52235106/87445978-64679b80-c601-11ea-8e10-003001195e7e.png) ![Screenshot 2020-07-14 at 18 38 57](https://user-images.githubusercontent.com/52235106/87445972-63366e80-c601-11ea-965f-a81265a5e538.png)

**Comment by RenatoSerra22** [comment]
i'm having the same issue

**Comment by CostachescuCristinel** [comment]
hi @artyorsh , is it you had any chance to look into this ?

**Comment by artyorsh** [comment]
@CostachescuCristinel I hadn’t. Not able to pay lots of attention into this project currently

**Comment by CostachescuCristinel** [comment]
Understood, is it you can give me any hints on where to start looking into this issue myself ?

**Comment by artyorsh** [comment]
It's hard to determine. Could you please try removing metro.conifg.js and see if it runs normally with built-in theme?
```js
import { mapping, light } from '@eva-design/eva';

<ApplicationProvider mapping={mapping} theme={light} />
```

**Comment by RenatoSerra22** [comment]
Having the same issue, every now and then it complains that the literal string "text-hint-color" is being passed as a colour. Happens on both ios and Android, even on iOS 13.5+. It works 90% of the time and then randomly this happens.

**Comment by RenatoSerra22** [comment]
Ok i found my issue, im dynamically rendering my theme dark/light from a redux store strong and applying it to the provider like `<ApplicationProvider {...eva} theme={{ ...eva[config.theme], ...curTheme }}>` the problem is on the very first render `config.theme` was undefined causing the exceptions and the app would not work until i had another render. 
In case anyone makes the same mistake as me.

**Comment by CostachescuCristinel** [comment]
> Ok i found my issue, im dynamically rendering my theme dark/light from a redux store string value and applying it to the provider like `<ApplicationProvider {...eva} theme={{ ...eva[config.theme], ...curTheme }}>` the problem is on the very first render `config.theme` was undefined causing the exceptions and the app would not work until i had another render.
> In case anyone makes the same mistake as me.

You just made my day!

@artyorsh Issue fixed, it was my fault

In my Redux module "theme" I have the following "currentTheme" and "systemTheme" reducers:
```
function systemTheme(state = initialState.systemTheme, action) {
	if (action.type === TYPES.THEME_CHANGESYSTEMTHEME) {
		if ((action.systemTheme !== "light") && (action.systemTheme !== "dark")) {
			// might be "no-preference" or "default" or other unsupported value
			return "light";
		}
		return action.systemTheme;
	}

	return state;
}

function currentTheme(state = initialState.currentTheme, action) {
	if ((action.type === TYPES.THEME_CHANGEUSERTHEME) || (action.type === TYPES.THEME_CHANGESYSTEMTHEME)) {
		const { systemTheme, userTheme } = action;

		return (userTheme === "system") ? systemTheme : userTheme;
	}

	return state;
}
```

The problem is that on iOS < 13, and on Android < 10, there is no support for system theme preference, thus, a value of "no-preference" is returned from React Native's Appearance API (by extension, also from Expo's Appearance API).
The `systemTheme` reducer correctly handles this value, converting it to `"light"`.
However, the `currentTheme` reducer does not. When called with `{ systemTheme: "no-preference", userTheme: "system" }`, the overall result is `currentTheme="no-preference"`. And obviously, `eva[currentTheme] = eva["no-preference"] = undefined`.

I was too confindent on the code I wrote that I completely ignored the possibility of this code being at fault. But at least I figured it out eventually...

**Comment by maheshlipane99** [comment]
@RenatoSerra22 Thanks, man. You just made my day!
