### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'this.meta.appearances')

### ISSUE THREAD

**Issue by houssemELbahri** [akveo/react-native-ui-kitten#1182]
## UI Kitten and Eva version

| Package      | Version |
 5.0.0  
| @eva-design/eva      |   5.0.0     |
| @ui-kitten/components   |     5.0.0    |

**Comment by artyorsh** [comment]
There is no `@eva-design/eva` of version 5. I guess you've missed "Configure Application Root" of the [manual installation process](https://akveo.github.io/react-native-ui-kitten/docs/guides/getting-started#manual-installation).
Please check that and leave a comment with a detailed description of the issue and related code if I'm not right.
