### ISSUE TITLE
Divider not visible

### ISSUE THREAD

**Issue by radud** [akveo/react-native-ui-kitten#1184]
First of all, thank you for this awesome framework. Great work!!

## 💬 Question
I cannot manage to use Divider control. Did anyone face the same problem? 
It does no show anything. Is it a V5 issue?
Can I change the line color?

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    ^2.0.0    |
| @ui-kitten/components   |    ^5.0.0     |

**Comment by artyorsh** [comment]
👋 
Any related code?

**Comment by MScMechatronics** [comment]
I'm having the same issue where I'd like to change the line color of the divider

**Comment by siyoola** [comment]
Same Here, The Divider will show as a List separator, however it is invisible when stand-alone

**Comment by Charles22219** [comment]
This happened a few times for me already although I still don't know when it specifically happens. I think it has something to do with the parent element. To 'fix' this you can specify the divider's width or most of the time for me I use alignSelf: 'stretch'

**Comment by yukkeechang** [comment]
Using the inspecter I see that it has a height of 1 and backgroundColor of #edf1f7 but trying to add in line styles to override it doesn't work :(

**Comment by dlwlrma00** [comment]
<Divider style={{alignSelf : 'stretch', backgroundColor : '#fff'}} />

**Comment by Applizone** [comment]
> <Divider style={{alignSelf : 'stretch', backgroundColor : '#fff'}} />

@artyorsh the divider appear on main screen. But it is not appear on custom modal class. I try both react native modal and ui kitten modal and it not appear. I try from one of this comment and it shows. Btw @dlwlrma00 thanks for sharing
