### ISSUE TITLE
Override color-primary-default in theme

### ISSUE THREAD

**Issue by arlyon** [akveo/react-native-ui-kitten#1185]
## 💬 Question

I am building a custom theme but want to make the 'default' primary colour the 'color-primary-900'. I can set this in the custom mapping, but then the value provided by useTheme is not correct. I cannot set this in the theme. Ideally, I'd like to, in my theme file, do something like this:

```json
{
    "color-primary-default": "color-primary-900"
}
```

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/material | 2.0.0        |
| @ui-kitten/components   |    5.0.0     |

**Comment by WilliamBlais** [comment]
Same question here!

**Comment by arlyon** [comment]
@WilliamBlais Just came back to this and reliased you need to prefix with a `$` for some reason.

So:

```json
{
    "color-primary-default": "$color-primary-900"
}
```

**Comment by artyorsh** [comment]
Yep. This is described in a [related guide](https://akveo.github.io/react-native-ui-kitten/docs/guides/branding#summary).
