### ISSUE TITLE
Expo project setup

### ISSUE THREAD

**Issue by eyalyoli** [akveo/react-native-ui-kitten#1188]
## 💬 Question
Hello,
I have two questions concerning the project setup.

1. Using the official guide to add ui-kittens to an existing project (which was created with Expo) requires to install via expo react-native-svg@9.13.6, but when running the command with the latest expo version you always get react-native-svg@12 because 9 isn't compatible with expo.
This is not an issue since the projects runs fine but with npm warning (dep is not met) and on runtime you get (when using Icon):
```
Warning: Unknown event handler property `onResponderTerminationRequest`. It will be ignored.
    in svg (created by Svg)
    in Svg
    in Unknown (created by Icon)
```
Is it ok to ignore such warnings?

2. In the official docs, it is said that the lib is ready to run on web (experimental), but it doesn't say that you should configure install & config the webpack to transpile ```@ui-kitten/components```, shouldn't this be stated somewhere?

Thank you very much for such an awsome lib 😄 

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2    |
| @ui-kitten/components   |     5    |
| expo | 38.0.8 |

**Comment by artyorsh** [comment]
Use `expo install ${packageName}` within Expo environment.
Running on the web with Expo is also mentioned [here](https://akveo.github.io/react-native-ui-kitten/docs/guides/running-on-the-web#quick-start).

**Comment by eyalyoli** [comment]
This is what I ran ```expo install react-native-svg@9.13.6```. expo will install v12 instead. tried to force it with npm but then expo gave an error that react-native-svg@9.13.6 isn't compatible with expo that needs v12+

> Running on the web with Expo is also mentioned [here](https://akveo.github.io/react-native-ui-kitten/docs/guides/running-on-the-web#quick-start).

Thank you I missed that :ok_hand:

**Comment by artyorsh** [comment]
@eyalyoli I'm not sure but I guess this should be fixed in latest SDK versions, so you can just use `expo install react-native-svg` and don't care about it :)
