### ISSUE TITLE
Warning: On RadioGroup onChange when inside e Modal

### ISSUE THREAD

**Issue by violabg** [akveo/react-native-ui-kitten#1189]
## 🐛 Bug Report
I have RadioGroup with Radio input inside a Modal component, when I setSelectedIndex I'm getting this warning:

**Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.**

it only happens if RadioGroup is inside a Modal component.

## To Reproduce

```jsx
import React from 'react';
import { Radio, RadioGroup, Text, Modal } from '@ui-kitten/components';

export const RadioGroupSimpleUsageShowcase = () => {

  const [selectedIndex, setSelectedIndex] = React.useState(0);

  return (
    <Modal>

      <Text category='h6'>
        {`Selected Option: ${selectedIndex + 1}`}
      </Text>

      <RadioGroup
        selectedIndex={selectedIndex}
        onChange={index => setSelectedIndex(index)}>
        <Radio>Option 1</Radio>
        <Radio>Option 2</Radio>
        <Radio>Option 3</Radio>
      </RadioGroup>

    </Modal>
  );
};
```

## Expected behavior

shouldn't get any warnings

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   2.0.0     |
| @ui-kitten/components   |   5.0.0      |

## Environment information

```bash

```

**Comment by artyorsh** [comment]
Please see https://github.com/akveo/react-native-ui-kitten/issues/1094#issuecomment-630141254
