### ISSUE TITLE
RkCard crashes with non-element children

### ISSUE THREAD

**Issue by lemori** [akveo/react-native-ui-kitten#119]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Crashes when there is a child as null or boolean.

**Expected behavior:**
Ignore children that are null, false or undefined.

**Steps to reproduce:**
When it renders a child on conditino in a loop, it crashes if the child is not an element.
It's the same result as `{i > 0 && <View style={{height: 10}} />}`.

**Related code:**
```
<RkCard>
  <View>
    {this.props.A.map((B, i) => {
      return (
        <View key={B.id}>
          {i > 0 ? <View style={{height: 10}} /> : null}
          <RkText rkType='large'>Any text</RkText>
        </View>
      )
    })}
  </View>
</RkCard>
```

### Other information:

**Quick fix**

It occurs in method `rkCard._process` on `for (let prop in elem.props) {}`. A fix may be:
```
_process(elem, readyStyles) {
    if (!elem) {
      return null
    }
    ......
}
```

byw, UI-Kitten is awesome :)

**Comment by artyorsh** [comment]
Hi @lemori,
This issue is solved and available in master branch. Also it will be available in future release.
Thanks for your reply!

**Comment by lemori** [comment]
Cheers!
