### ISSUE TITLE
Conditionally show accessoryLeft element

### ISSUE THREAD

**Issue by kockok** [akveo/react-native-ui-kitten#1191]
🐛 Bug Report

Typescript error raised when using ternary operator to determine its existence.

## To Reproduce
```
  const LoadingIndicator = () => (
    <View>
      <Spinner size="small" status="control" />
    </View>
  );
```
```
<Input
accessoryLeft={called && loading ? LoadingIndicator : null}
/>
```

error raised:
```
 Type '(() => Element) | null' is not assignable to type 'RenderProp<Partial<ImageProps>> | undefined'.
```
## Expected behavior

I hope that you can add an attribute to accept "null" or "none" so as to hide the accessories.

**Comment by joleb** [comment]
Just pass "null", that should work. You may ignore the typescript error there. For me that worked: `<Input accessoryRight={(evaProps) => true ? null : <Text {...evaProps}>Yikes</Text>}/>` and successfully returned "nothing" as `accessoryRight`

**Comment by Jonatthu** [comment]
Try () => called && loading ? LoadingIndicator : null

**Comment by kockok** [comment]
No, it won't accept `null`.

**Comment by markrickert** [comment]
I've run into this issue before and I find that just passing an empty `<View />` or `<Fragment />` works in this situation, though it would be nice to conditionally show the accessory.

```
const LoadingIndicator = () => (
    <View>
      <Spinner size="small" status="control" />
    </View>
  );
<Input accessoryLeft={called && loading ? LoadingIndicator : ()=> <View />} />
```

or even better:

```
const LoadingIndicator = () => (
  const spinner = <Spinner size="small" status="control" />
  return <View>{called && loading && spinner}</View>
)
<Input accessoryLeft={LoadingIndicator} />
```

**Comment by kockok** [comment]
> I've run into this issue before and I find that just passing an empty `<View />` or `<Fragment />` works in this situation, though it would be nice to conditionally show the accessory.
> 
> ```
> const LoadingIndicator = () => (
>     <View>
>       <Spinner size="small" status="control" />
>     </View>
>   );
> <Input accessoryLeft={called && loading ? LoadingIndicator : ()=> <View />} />
> ```
> 
> or even better:
> 
> ```
> const LoadingIndicator = () => {
>   const spinner = <Spinner size="small" status="control" />
>   return <View>{called && loading && spinner}</View>
> }
> <Input accessoryLeft={LoadingIndicator} />
> ```

Wow, neat! It works.

**Comment by eviliana-helvia** [comment]
If anyone comes here searching for this answer, it works if you return `undefined` instead of `null` (as indicated by the typescript error). This way you can hide the accessory view completely instead of rendering an empty view which pushes the text to the right (or left).
