### ISSUE TITLE
multiple dates selection on calendar in needed (range is not appropriate)

### ISSUE THREAD

**Issue by BayCo** [akveo/react-native-ui-kitten#1193]
How can i implement multiple dates selection on calendar?
Thank for your time

**Comment by artyorsh** [comment]
There is no way to do that. Could you please describe the use case?

**Comment by BayCo** [comment]
> There is no way to do that. Could you please describe the use case?
![Simulator Screen Shot - iPhone 11 - 2020-07-28 at 11 22 47](https://user-images.githubusercontent.com/2808949/88626826-b4943280-d0c4-11ea-95a7-bc9e48f6c65f.png)

On this screen user should select recurring dates, the calendar that i implemented for temporary tests is react-native-calendars

**Comment by ZeroJian** [comment]
Same problem

**Comment by eyalyoli** [comment]
@artyorsh  you should reopen the issue

**Comment by Pmccasky** [comment]
Can this issue please be reopened? The use case is when needing to select multiple dates that are distinct/not within a range. For example if you want to book something several times, but each date is not related to the other.

**Comment by Pmccasky** [comment]
> There is no way to do that. Could you please describe the use case?

@artyorsh

**Comment by artyorsh** [comment]
@Pmccasky it's better to open a corresponding feature proposal I'd say

**Comment by Pmccasky** [comment]
@eyalyoli @ZeroJian @BayCo I submitted a feature proposal here: https://github.com/akveo/react-native-ui-kitten/issues/1503

If you are still in need of this, please visit this proposal.
