### ISSUE TITLE
Touch effect on card

### ISSUE THREAD

**Issue by cr1979** [akveo/react-native-ui-kitten#1194]
## 💬 Question
Is there a way to disable or hide the touch effect on pressing the card? An attribute or any style?

on press:
<img width="364" alt="onPress" src="https://user-images.githubusercontent.com/7447711/88425079-0bf98080-cdef-11ea-8ac8-1b4cfd4cbdd3.png">

normal:
<img width="362" alt="normal" src="https://user-images.githubusercontent.com/7447711/88425103-1e73ba00-cdef-11ea-97b4-5ad6e645e83b.png">

## UI Kitten and Eva version
| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    ^2.0.0    |
| @ui-kitten/components   |    ^5.0.0    |

Thank you.

**Comment by artyorsh** [comment]
You may use `disabled`

**Comment by jeremyfrancis** [comment]
> You may use `disabled`

Unfortunantley this prop now affects all child components. Not sure why, pretty annoying.
