### ISSUE TITLE
TopNavigation fixed to top

### ISSUE THREAD

**Issue by kokhoor** [akveo/react-native-ui-kitten#1195]
## 💬 Question
For theming support, I presume we should be using TopNavigation instead of React Navigation StackNavigator Header.

1. Is it possible to fix the position of TopNavigation to the top and not allow it to be scrolled away?

2. Or if 1 cannot be done, is it possible to use StackNavigator header but let it use UI Kitten theme colors instead?

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   2.0.0     |
| @ui-kitten/components   |  5.0.0       |

**Comment by artyorsh** [comment]
> I presume we should be using TopNavigation instead of React Navigation StackNavigator Header.

Use [screenOptions](https://reactnavigation.org/docs/screen-options/#screenoptions-prop-on-the-navigator) to disable native headers.

`<Stack.Navigator screenOptions={{ headerShown: false }} />`

Then you may render TopNaviation where needed.

> Is it possible to fix the position of TopNavigation to the top and not allow it to be scrolled away?

It will be fixed until it's rendered in scrollable container.

**Comment by kokhoor** [comment]
Sorry for the silly question. Placed the TopNavigation inside a KeyboardAvoiding ScrollView.
This is perfect, thanks!
