### ISSUE TITLE
onPress handler for accessoryLeft and accessoryRight

### ISSUE THREAD

**Issue by kokhoor** [akveo/react-native-ui-kitten#1196]
## 💬 Question
Is it possible to add onPress handlers for accessoryLeft and accessoryRight to the element, for example to Button? (e.g. accessoryLeftOnPress and accessoryRightOnPress).

The reason for this is to reduce the need of re-defining the Icons every time in different pages (same Icon but different pages having different implementation of onPress).

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |     2.0.0   |
| @ui-kitten/components   | 5.0.0        |

**Comment by artyorsh** [comment]
You may put all of the icons in one place so you’re able to reuse them. And wrap it in any Touchable component if needed.
