### ISSUE TITLE
Default font seems to be missing on Android

### ISSUE THREAD

**Issue by fahimk** [akveo/react-native-ui-kitten#1197]
## 🐛 Bug Report

On android using the Text categories here (https://akveo.github.io/react-native-ui-kitten/docs/components/text/overview#text) seems to not work after following the getting started instructions. It looks fine on iOS, is it possible there is an additional step I need to take for it to work on Android?

## To Reproduce

Using 
```
      <Text category="h5" style={{ textAlign: "center" }}>
        Account
      </Text>
```

looks like: 
<img width="245" alt="Mouse_Highlight_Overlay" src="https://user-images.githubusercontent.com/857824/88518438-2a32cc80-cff9-11ea-8437-2188973a39a0.png">

## Expected behavior

<img width="302" alt="Mouse_Highlight_Overlay" src="https://user-images.githubusercontent.com/857824/88518499-420a5080-cff9-11ea-82d7-f44ae65cd1c1.png">

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2.0.0    |
| @ui-kitten/components   |     5.0.0    |

## Environment information

```bash
  System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.18.2/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 26, 27, 28, 29
      Build Tools: 23.0.1, 25.0.0, 26.0.2, 27.0.0, 27.0.1, 28.0.3, 29.0.2
      System Images: android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  npmPackages:
    react-native: ^0.62.2 => 0.62.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

**Comment by artyorsh** [comment]
There is no platform-dependent steps. Make sure the font is linked.

**Comment by fahimk** [comment]
How do I link the default font? To be clear, I'm not trying to customize the font here just followed the guide and trying to use the text component with different categories.

**Comment by artyorsh** [comment]
We use custom font (OpenSans) in the documentation examples. The final result you could expect can also mostly depend on this. I highly recommend doing this at least for Android platform, because you're never sure it uses Roboto on every device.

**Comment by lukeramsden** [comment]
I'm getting this issue too. I'm going to try linking the font. It seems to work fine by default on iOS but not Android, which is weird. I'll report back.

**Comment by amrhassab** [comment]
@fahimk here is how if you are still wondering 2 years later :)

https://akveo.github.io/react-native-ui-kitten/docs/guides/branding#typography
