### ISSUE TITLE
Icon animation not working with react navigation v5

### ISSUE THREAD

**Issue by kockok** [akveo/react-native-ui-kitten#1199]
## To Reproduce

1. add pulseIconRef
```
export const MainNavigator = () => {
  const pulseIconRef = React.useRef();

  return (
    <Tabs.Navigator
      tabBarOptions={{
...)}
```

2. set icon `ref` and  `tabPress` listener
![Screenshot 2020-07-27 at 7 11 43 PM](https://user-images.githubusercontent.com/232541/88535778-2aed5200-d03d-11ea-9e19-fde5fc0047ed.png)

the `ref` raised: 
```
The expected type comes from property 'ref' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<Icon<{ name: "people-outline"; width: number; height: number; fill: string; ref: MutableRefObject<undefined>; animation: "pulse"; }>> & Pick<...> & Partial<...> & Partial<...>'
```
`pulseIconRef.current` raised:
```
(property) React.MutableRefObject<undefined>.current: undefined
Object is possibly 'undefined'.ts(2532)
```

3. animation not working albeit using codes from the official docs.

## Expected behavior
When I tap the tabicon, the animation should run.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    "^2.0.0"    |
| @ui-kitten/components   |    "^5.0.0"     |
`"@ui-kitten/eva-icons": "^5.0.0",`
## Environment information

```bash
  npmPackages:
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 

```

**Comment by ScripTech** [comment]
Same issue

**Comment by ScripTech** [comment]
have you found a solution?

**Comment by kovetskiy** [comment]
Not really a solution, but it works if you use `React.useRef<any>()`

**Comment by bataevvlad** [comment]
@kockok 

Apparently you're trying to use an icon inside the tab bar itself, try using the custom tab bar from our library where you can handle all the events you need, if you need any more help, let me know.
