### ISSUE TITLE
Failed prop type: Invalid props.style key `style` supplied to `Text`

### ISSUE THREAD

**Issue by luutruong** [akveo/react-native-ui-kitten#1200]
## 🐛 Bug Report

This warning occurred when install RN 0.63.2

Component effected:

* ListItem (https://github.com/akveo/react-native-ui-kitten/blob/master/src/components/ui/list/listItem.component.tsx#L128)

## To Reproduce

Use a Text for accessoryLeft in ListItem.

Example:

```

<ListItem
   title="test a bug"
   accessoryRight={(props) => (
      <Text {...props}>Bug</Text>
   )} />

```

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |  5.0.0      |
| @ui-kitten/components   |   5.0.0      |

**Comment by artyorsh** [comment]
Please see the [API](https://akveo.github.io/react-native-ui-kitten/docs/components/list/api#listitem).
It is expected from this property to return an image. Which means it is called with props accessible by the Image component and not by text. If you want to render a Text please use the passed `props` argument accurately
