### ISSUE TITLE
Error - ./node_modules/@ui-kitten/components/ui/input/input.component.js 110:38

### ISSUE THREAD

**Issue by pherm** [akveo/react-native-ui-kitten#1201]
error - ./node_modules/@ui-kitten/components/ui/input/input.component.js 110:38
Module parse failed: Unexpected token (110:38)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
this.webEventResponder = devsupport_1.WebEventResponder.create(this);
|         this.focus = () => {
>             this.textInputRef.current?.focus();
|         };
|         this.blur = () => {

## UI Kitten and Eva version

| Package      | Version |
@eva-design/eva": "^2.0.0",
@ui-kitten/components": "^5.0.0",

any fix? 

Ps. I'm not working with expo (only react native web and next js)

**Comment by artyorsh** [comment]
You can do exact the same workaround discussed in #996
