### ISSUE TITLE
Select popover is displayed behind of react-native-community/react-native-modal

### ISSUE THREAD

**Issue by olckara** [akveo/react-native-ui-kitten#1202]
## 💬 Question

I'm using `react-native-community/react-native-modal` to display modal screens on top of views.

If you use `@ui-kitten/components/Select` inside a `react-native-community/react-native-modal`, popover list of SelectItems are rendered behind the modal so it is not selectable but visible if you make the modal transparent. I couldn't figure out how to add styles to popover of the select so I can give it a `zIndex: 9999` maybe it would work.

When I use `@ui-kitten/components/Modal` I have no problem. But I needed animations that's why I'm using `react-native-community/react-native-modal`

Maybe this is a bug? Help please 🙏

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    ^2.0.0    |
| @ui-kitten/components   |    ~5.0.0     |

**Comment by Arun-paramasivam** [comment]
even i have the same bug. But it works fine on uikittens Modal. But again it was not working on Oneplus 7 devices(even with uikitten modal) with OS android 10, it works fine on android 9 and below. stuck with this issue for 3 days. @olckara did you find any solution?

**Comment by kishanbharda** [comment]
Is there anyone have find proper solution ? I am also on same problem.

**Comment by KeturahDev** [comment]
@artyorsh, could you link the non-duplicate issue for reference?

**Comment by anhnch** [comment]
For me, the dropdown list is behind the modal screen
```
<Stack.Screen name="Edit" component={EditScreen} options={{ presentation: 'modal' }} />
```
In this modal screen, I have a form with a Select component. When I press the Select component, nothing appears. But when I drag the modal screen down, the select dropdown is behind. 

It'd been fine before I replaced the @react-navigation/stack with the @react-navigation/native-stack.
