### ISSUE TITLE
How to set Datepicker format if using MomentDateService ?

### ISSUE THREAD

**Issue by cuteprince** [akveo/react-native-ui-kitten#1203]
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   2.0.0     |
| @ui-kitten/components   |    5.0.0     |

**Comment by whitestranger7** [comment]
Hey, @cuteprince, you can find the exact usage example in the [documentation](https://akveo.github.io/react-native-ui-kitten/docs/components/datepicker/overview#datepicker).
Just scroll down through examples and find the one with `Datepicker Moment` header.

**Comment by artyorsh** [comment]
👋  there
Datepicker and every other date-rendering component takes the default format from the Date Service it's configured.
In case of Moment, it's configurable with [long date format](https://momentjs.com/docs/#/customization/long-date-formats/).

[Related code](https://github.com/akveo/react-native-ui-kitten/blob/master/src/moment/momentDate.service.ts#L153)
