### ISSUE TITLE
Refreshing Accessory in Input Dismisses Keyboard

### ISSUE THREAD

**Issue by NickTheTurtle** [akveo/react-native-ui-kitten#1204]
## 💬 Question
I'm not sure if this is intended behavior or not. In my use case I have a send icon wrapped in a TouchableOpacity as an accessoryRight to an input. When clicking the icon, I temporarily replace this send icon with a Spinner while I communicate with the server. The problem is that this refresh of the input's accessories causes the keyboard to automatically dismiss. Is there a way to replace an accessory of the input without dismissing the keyboard?

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
|react | 16.3.1|
|react-native | 0.63.1 |
| @eva-design/eva      |       2.0.0 |
| @ui-kitten/components   |         5.0.0|

**Comment by artyorsh** [comment]
👋  there,
This is a well-known issue in React Native. Wrapping the Input in the ScrollView component with configured [keyboardShouldPersistTaps](https://reactnative.dev/docs/scrollview#keyboardshouldpersisttaps) property should solve the problem.

[Demo](https://snack.expo.io/DYMS2RmrY)
