### ISSUE TITLE
Is there a way to scroll to the top of Layout using List component in response to a button press?

### ISSUE THREAD

**Issue by weslei-dias-vakt** [akveo/react-native-ui-kitten#1205]
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |        |
| @ui-kitten/components   |  4.4       |

**Comment by CostachescuCristinel** [comment]
`List` is wrapper component around react native's FlatList component. Other than the properties listed in the `List` component docs, you can apply any property that react native's FlatList component expects. This includes the `onScroll` events.

Scrolling manually can be done by using `this.myRef = React.createRef();`, passing it to the `<List ref={this.myRef} />` component, and manually calling `this.myRef.current.scrollTo({ x:0, y: 100, animated: true })`.

**Comment by weslei-dias-vakt** [comment]
Thanks @CostachescuCristinel  works perfectly.
Here is my code

`    const scrollRef = useRef<FlatList<any>>();
`

`                <List
                    ref={scrollRef}
                    refreshing={refreshing}
                    onRefresh={() => fetchData(false)}
                    style={styles.list}
                    contentContainerStyle={styles.listContent}
                    data={dataSource}
                    renderItem={renderItem}
                    ListFooterComponent={() => <Button onPress={() => scrollRef.current.scrollToIndex({index: 0})}Back to top</Button>}
                />`
