### ISSUE TITLE
Input Focus Tap/Click Area

### ISSUE THREAD

**Issue by m4ttheweric** [akveo/react-native-ui-kitten#1206]
Simple issue: 

For Input's, the area that you can tap/click to actually focus into the field is quite small compared with the size of the UI element. This can make a frustrating UX situation and requires more precision than feels should be necessary. It would be helpful make a tap anywhere on the UI element result in focus.

**Comment by aleqsio** [comment]
@m4ttheweric I have a temporary solution for you.
Add this custom mapping to input components:
```
{
  "components": {
    "Input": {
      "meta": {
        "parameters": {
          "minHeight": {
            "type": "number"
          },
          "paddingVertical": {
            "type": "number"
          },
          "textColor": {
            "type": "number"
          }
        },
        "states": {},
        "scope": "all"
      },
      "appearances": {
        "default": {
          "mapping": {
            "textColor": "text-basic-color",
            "paddingVertical": 0,
            "paddingHorizontal": 0,
            "minHeight": 0
          },
          "variantGroups": {
            "size": {
              "small": {
                "paddingVertical": 0,
                "paddingHorizontal": 0,
                "minHeight": 0
              },
              "medium": {
                "paddingVertical": 0,
                "paddingHorizontal": 0,
                "minHeight": 0
              },
              "large": {
                "paddingVertical": 0,
                "paddingHorizontal": 0,
                "minHeight": 0
              }
            }
          }
        }
      }
    },
```
And set this style as the input `textStyle` prop:
```
  input: {
    height: 48,
    paddingLeft: 21,
    paddingRight: 21,
    marginLeft: -7,
    marginRight: -7
  },
```
This replicates the large input size with the correct touch zone.

**Comment by m4ttheweric** [comment]
Hi, thanks for the workaround. Can you give me an example of what you mean by "add this custom mapping"?

**Comment by manuelmhtr** [comment]
+1 This behavior is quite problematic. The solution proposed works but it should be better fixed in the library.

**Comment by lukeramsden** [comment]
[`e992b66` (#1165)](https://github.com/akveo/react-native-ui-kitten/pull/1165/commits/e992b66fa27036bc85407a830c1cfca0708247a0)

It is being fixed! Hopefully this will be merged soon.

**Comment by zpv** [comment]
@artyorsh any update on this issue? This is pretty poor UX for a key component.
