### ISSUE TITLE
MenuGroup onPress is never fired

### ISSUE THREAD

**Issue by micaelomota** [akveo/react-native-ui-kitten#1207]
## 🐛 Bug Report

When using `MenuGroups`,  any `TouchableOpacityProps` were supposed to be accepted, but if you pass `onPress` it will never be fired because it will be overridden in the `render` function.

TouchableOpacityProps reference
https://github.com/akveo/react-native-ui-kitten/blob/ea4a3620e78a262419ee6c5b116dc70a5645eefd/src/components/ui/menu/menuGroup.component.tsx#L59

Render reference
https://github.com/akveo/react-native-ui-kitten/blob/ea4a3620e78a262419ee6c5b116dc70a5645eefd/src/components/ui/menu/menuGroup.component.tsx#L175

## To Reproduce

1. Create a Menu and add a `MenuGroup` item
2. Add the `TouchableOpacityProps` 
  ```javascript
<Menu>
   <MenuGroup
       onPressIn={() => console.log("onPressIn")}
       onPress={() => console.log("onPress")}
       onPressOut={() => console.log("onPressOut")}>
   // ...
```

## Expected behavior

When you tap on the `MenuGroup` item we expected to see the following in the console
```bash
onPressIn
onPress
onPressOut
```

But you only see
```bash
onPressIn
onPressOut
```

## Link to runnable example or repository (highly encouraged)

https://snack.expo.io/3JHB_ESV6

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |     2.0.0   |
| @ui-kitten/components   |     5.0.0    |

## Environment information

```bash
System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.3, 30.0.1
      System Images: android-30 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
```

**Comment by artyorsh** [comment]
👋 
I’m curious, what’s the reason to handle touches of the group?

**Comment by micaelomota** [comment]
> 👋
> I’m curious, what’s the reason to handle touches of the group?

Google analytics and one cute dynamic `accessoryRight` :)

**Comment by adokce** [comment]
thanks for issue and solution @micaelomota

@artyorsh I also want to do something with accessoryLeft when the group is expanded.
