### ISSUE TITLE
Unexpected behavior with inputs borders

### ISSUE THREAD

**Issue by adscud** [akveo/react-native-ui-kitten#1209]
## 💬 Question

Hi, 
I currently want to change the style of my input, however I have a problem with the borders of this one, why am I using two borders like this again?

I have remove the `backgroundColor: '#ffffff` and I see that the input is more little than his parent 🤔

```js
<Input
      style={styles.inputCodeLetter}
/>

// style of the input
inputCodeLetter: {
     height: 50,
     width: 40,
     marginHorizontal: 10,
     borderColor: '#ffffff',
     borderBottomWidth: 3,
     borderBottomColor: '#D0D5DE',
},
```
What I have : 
![IMG_8714](https://user-images.githubusercontent.com/34245352/89520484-34fe1600-d7de-11ea-81c6-fa0ed1586a28.jpg)
 

That what I want to do : 
![Capture d’écran 2020-08-06 à 12 12 24](https://user-images.githubusercontent.com/34245352/89520430-2283dc80-d7de-11ea-98db-773c9cfff665.png)

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    ^2.0.0-alpha.1    |
| @ui-kitten/components   |    ^5.0.0-alpha.1     |

**Comment by jeloagnasin** [comment]
I have the same issue as well. Were you able to figure it out?

| Package | Version |
| -- | -- |
| @eva-design/eva | ^2.0.0 |
| @ui-kitten/components | ^5.0.0 |

**Comment by ArthurDelbeke** [comment]
> I have the same issue as well. Were you able to figure it out?
> 
> Package	Version
> @eva-design/eva	^2.0.0
> @ui-kitten/components	^5.0.0

I've use the native input...

**Comment by whitestranger7** [comment]
Hi, everyone  👋
We're working on the issue right now, but regarding your case, @adscud  - I'd say you need to wrap `Input` with another element in order to apply appropriate `bottomBorder` properties.
Here you go, take a look, the example below will do the trick and it looks exactly like you need it =)
```js
<Layout style={styles.wrapperStyles}> // dont forget to import Layout from kitten library as well
   <Input
      style={styles.inputCodeLetter}
   />
</Layout>

// style of the input
const styles = StyleSheet.create({
wrapperStyles: {
     borderBottomWidth: 3,
     borderBottomColor: '#D0D5DE',
     paddingHorizontal: 10,
},
inputCodeLetter: {
     height: 50,
     width: 40,
     borderColor: '#fff',
     backgroundColor: '#fff',
},
})
```
