### ISSUE TITLE
[ViewPager] - Disable swipe gestures

### ISSUE THREAD

**Issue by LucasFsc** [akveo/react-native-ui-kitten#1210]
## 🚀 Feature Proposal

I would like to disable ViewPager swipe gestures.

## Motivation

Im trying to implement a multistep form using the component.

## Example

I have a multistep form, and each step need to be validated before proceeding, I would like to disable the swipe gestures so I can guarantee that the user will not jump any steps.

**Comment by VinodLouis** [comment]
@LucasFsc How are you handling it currently?

**Comment by LucasFsc** [comment]
I didn't found a possible way to disable the gestures, I tried with View props, but no success. In my case I wanted to disable/enable the gestures for both left and right and also just one side depending on the step condition. You can actually disable all gestures by wrapping the ViewPager into a View with `pointerEvents="none"`, but this is not what I want.

**Comment by evilchis94** [comment]
@LucasFsc I have a similar scenario, how did you manage it?

**Comment by toutouli** [comment]
My solution is wrapping the ViewPager into a TouchableOpacity

**Comment by iamnino** [comment]
> My solution is wrapping the ViewPager into a TouchableOpacity

I've tried Pressable and works well too.
TouchableOpacity makes the component a bit opaque when pressed/swiped.

**Comment by tareqlol** [comment]
> > My solution is wrapping the ViewPager into a TouchableOpacity
> 
> I've tried Pressable and works well too.
> TouchableOpacity makes the component a bit opaque when pressed/swiped.

Try adding `activeOpacity={1}` it will disable the opaque opacity when pressed.
