### ISSUE TITLE
How to hide a button in ui kitten button component?

### ISSUE THREAD

**Issue by Trisha005** [akveo/react-native-ui-kitten#1211]
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |        |
| @ui-kitten/components   |         |

**Comment by lesmo** [comment]
What's wrong with just conditionally rendering?

```jsx
{!hide && (<Button />)}
```

**Comment by sudomann** [comment]
Give more details, what you have there should work fine. Did you style your button in your code? Perhaps nearby object styling interferes???
