### ISSUE TITLE
What if it's not an Image? accessoryLeft / Right icons...

### ISSUE THREAD

**Issue by CostachescuCristinel** [akveo/react-native-ui-kitten#1213]
## 💬 Question
Most of the components that accept the `accessoryLeft` and `accessoryRight` props, expect these properties to be a function, that returns an `<Image />` component.
But what happens if the function does **not** return an `Image`, and instead, returns whatever else?
Is there anything in particular that UI-Kitten does that requires specifically an `Image` component? Or is that just because the props passed to the accessoryLeft/Right functions are props that would be more appropriate for use with an Image?

Case in point, I am loading multiple svg icons through `react-native-svg-transformer`. I have tested using the svg icons as accessoryLeft/Right, and it seems to render with no problems.
However, I'd like to make sure that I am not doing something wrong, so I'd like to ask for confirmation.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2.0.0    |
| @ui-kitten/components   |    5.0.0     |

**Comment by artyorsh** [comment]
`accessoryLeft` and `accessoryRight` properties in most cases expect an Image. That means that props passed to those components are [ImageProps](https://reactnative.dev/docs/image#props). If you want passing there something different to an Image, you should use (or not use) those props carefully.
