### ISSUE TITLE
TopNavigation action not working in iOS

### ISSUE THREAD

**Issue by dytra** [akveo/react-native-ui-kitten#1216]
## 🐛 Bug Report

I'm using `<TopNavigation/>`, I added accessory right, just a button with onpress event. But why in iOS if I press the button it doesn't trigger anything. works fine in Android.

## To Reproduce

```javascript
const ProfileScreen = () => {
const renderSettingsAction = () => (
    <TopNavigationAction icon={SettingsIcon} onPress={() => Alert.alert("suyoku")} />
  );
 return(
 <Layout style={{ flex: 1, }}>
      <TopNavigation
        title='Eva Application'
        accessoryLeft={renderBackAction}
        accessoryRight={renderSettingsAction}
      />
  </Layout>
)
}

```

## Expected behavior

It should trigger the onPress event in iOS

## Link to runnable example or repository (highly encouraged)

Source: https://github.com/dytra/sugary/blob/master/screens/Consumptions/Consumptions.js
Demo: https://expo.io/@dytra/sugary-dev

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2.0.0    |
| @ui-kitten/components   |  5.0.0       |

## Environment information

```bash

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz
  Binaries:
    Node: 10.19.0 - ~/.nvm/versions/node/v10.19.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v10.19.0/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
  IDEs:
    Android Studio: 3.3 AI-182.5107.16.33.5314842
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: ~16.11.0 => 16.11.0 
    react-native: ~0.62.2 => 0.62.2 
```

**Comment by artyorsh** [comment]
Hi @dytra and sorry for the late reply.

I couldn't reproduce this issue, unfortunatuly.
Please check [this demo](https://snack.expo.io/@art.yorsh/playground) to make sure it works.

**Comment by sikaco** [comment]
I encountered the same issue and found that the reason was that the <Navigator /> was not hiding the header correctly (the screenOptions' headerTitle parameter was set to '').
