### ISSUE TITLE
Link to list of possible theme keys is broken

### ISSUE THREAD

**Issue by eyalyoli** [akveo/react-native-ui-kitten#1218]
## 🚀 Feature Proposal

In the docs there should be a link to all eva theme vars that can be used. There are two pages about this:
1.  [Using Theme overview](https://akveo.github.io/react-native-ui-kitten/docs/components/using-theme/overview#usetheme) - doesn't have any link to such a list. 
2. [Using Theme Variables](https://akveo.github.io/react-native-ui-kitten/docs/design-system/use-theme-variables#using-theme-variables) - has a broken link to the list.

I figured out that [this](https://github.com/eva-design/eva/blob/master/packages/eva/themes/light.json)  is the list were are talking about.

## Motivation

To help guide those who are lost

**Comment by AntonBorovoi** [comment]
Hi @eyalyoli 
Thanks for raising this

1. Will be resolved by https://github.com/akveo/react-native-ui-kitten/pull/1494
2. Fixed by https://github.com/akveo/react-native-ui-kitten/pull/1381/files
