### ISSUE TITLE
How to pass ListItem data to accessoryLeft to access item image URI?

### ISSUE THREAD

**Issue by luiey** [akveo/react-native-ui-kitten#1219]
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   ^2.0.0     |
| @ui-kitten/components   |   ^5.0.0      |

How do I pass item from List rendering to accessory? 
```
  const RenderListItemRight = (props) => (
    <Button size='tiny'>AVAILABLE</Button>
  );
  const RenderItemImage = () => (
    <Image
      style={{ width: 40, height: 40 }}
      source={{ uri: item.IngImageUri }}
      resizeMode={"cover"}
    />
  );
  const RenderItem = ({ item, index }) => (
    <ListItem
      title={`${item.IngName}`}
      description={item.IngPrice > 0 ? `${item.IngPrice.toFixed(2)}` : ''}
      accessoryLeft={RenderItemImage}
      accessoryRight={RenderListItemRight}
      onPress={() => onPressListItem(item)}
    />
  );
  const onPressListItem = (item) => {
    console.log('item: ', item);
  }
  const onRefresh = () => {
    console.log('On Refresh');
    RetrieveData();
    setIsRefreshing(true);
  }
  const RenderList = () => (
    <List
      style={{ flex: 1 }}
      data={FlatData}
      renderItem={RenderItem}
      refreshing={IsRefreshing}
      keyExtractor={FlatData.IngID}
      onRefresh={() => onRefresh}
    />
  )
```
Before I use URI on accessory left image, it working but using static image from assets folder (using **require('')**). Now, I want to use live data. The FlatData having image uri from web. I have tried `accessoryLeft={RenderItemImage(item)}` and `const RenderItemImage = (item) => ` but none of it working

**Comment by Charles22219** [comment]
I've tried passing data before in accessoryRight. I did it like this
 `accessoryRight={ () => renderAccessory (info) }`

**Comment by YonathanMeguira** [comment]
@Charles22219 you have saved me a lot of hand banging. thank you.

**Comment by LoicC04** [comment]
Could you give me a hint on how to do that ? I am stil stuck...
```typescript
const renderItemAccessory = (props) => (
  <Button size='tiny'>Consulter</Button>
);

const renderItemIcon = (props, icon) => (
  <Icon {...props} name={`${icon}`}/>
);

const renderItem = ({ item, index }) => (
  <ListItem
    title={`${item.title}`}
    description={`${item.description}`}
    accessoryLeft={(props) => renderItemIcon(props, item.icon)}
    accessoryRight={renderItemAccessory}
  />
);
```
I get an error :
React.createElement: type is invalid -- "Expected a string but got : undefined

**Comment by rjsajnani** [comment]
Hi @LoicC04 
I have found a solution hope this helps you 

`
 accessoryLeft={(props) =>
            renderIcon({...{iconName: 'search'}, ...props})
          }
`

` const renderIcon = (props) => {
    return <Icon {...props} name={props.iconName} />;
  };
`
<img width="310" alt="Screenshot 2020-12-26 at 10 32 09 AM" src="https://user-images.githubusercontent.com/17737055/103144525-9d399e00-4765-11eb-8955-10a953e53aa0.png">

**Comment by nromero125** [comment]
> Hi @LoicC04
> I have found a solution hope this helps you
> 
> `accessoryLeft={(props) => renderIcon({...{iconName: 'search'}, ...props}) }`
> 
> `const renderIcon = (props) => { return <Icon {...props} name={props.iconName} />; };`
> <img alt="Screenshot 2020-12-26 at 10 32 09 AM" width="310" src="https://user-images.githubusercontent.com/17737055/103144525-9d399e00-4765-11eb-8955-10a953e53aa0.png">

That works for me, I was trying to pass a Text component. Thanks!
