### ISSUE TITLE
Using StyleService.create styles in Class Components

### ISSUE THREAD

**Issue by kokhoor** [akveo/react-native-ui-kitten#1221]
I am trying to use following styles created using StyleService.create in a React Native Class Component render function, but unable to get the translation for the backgroundColor: 'background-basic-color-1'. As I am not able to use hooks in a class component, I am not able to use: useStyleSheet. What do I need to use in this case?

Stylesheet created using StyleService.create:

```
const styles = StyleService.create({
  safeAreaLayout: {
    flex: 1
  },
  scrollView: {
  },
  scrollViewContent: {
    backgroundColor: 'background-basic-color-1',  // this did not get translated
    paddingVertical: 24,
  },
   ...
});
```

Class Component render function:

```
  public render() {
    const { eva, ...statusBarProps } = this.props;

    return (
        <ScrollView
          style={styles.scrollView}
          contentContainerStyle={styles.scrollViewContent}>
          ...
        </ScrollView>
    )
}
```

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2.0.0    |
| @ui-kitten/components   |   5.0.0      |

**Comment by kokhoor** [comment]
Please help to correct if wrong. What I did to fix is to use: StyleService.createThemed (but limited to eva theme only, I believe):

```
import * as eva from '@eva-design/eva';


export default class TestScreen extends React.Component {

  static contextType = Theming.ThemeContext;

  public render() {
    let screenStyles = StyleService.createThemed(styles, eva[this.context.currentTheme]);

    return (
        <ScrollView
          style={screenStyles.scrollView}
          contentContainerStyle={screenStyles.scrollViewContent}>
          ...
        </ScrollView>
    );
  }
}

const styles = StyleService.create({
  scrollView: {
    backgroundColor: 'background-basic-color-2',
  },
  scrollViewContent: {
    paddingVertical: 24,
  },
});
```

**Comment by artyorsh** [comment]
Inside a class components you might want to use [withStyles](https://akveo.github.io/react-native-ui-kitten/docs/components/using-theme/overview#withstyles) function.

**Comment by Bijiabo** [comment]
> Inside a class components you might want to use [withStyles](https://akveo.github.io/react-native-ui-kitten/docs/components/using-theme/overview#withstyles) function.

This will change the way code is written, `backgroundColor: 'background-basic-color-1'` -> `backgroundColor: theme['background-basic-color-1']`
