### ISSUE TITLE
RangeCalendar doesn't display selected Range when it is outside of the current month.

### ISSUE THREAD

**Issue by trevor-coleman** [akveo/react-native-ui-kitten#1222]
## 🐛 Bug Report

When using the RangeCalendar component, I have 'shortcut' buttons below the calendar that allow the user to quickly select a date range. (e.g. "Last Week, a month ago, two months ago, etc.")

When they press one of the buttons it updates the selected range of the calendar to the specified range.

If the range is outside of the currently displayed month, the calendar view doesn't change to show the new selection. 

This makes it seem as though the button isn't working, even though it is. (The range indicator is displayed correctly when I am already looking at the date range before pressing the button.)

This is true also if the selected range is set before the component renders the first time. (If I'm displaying the existing value in the field, for instance.)

I can't seem to find a way to make the calendar display anything but the current month programatically. Sorry if I'm missing something obvious here.

## To Reproduce

1. Load RangeCalendar component on screen. (
2. Set `range` prop programatically with start/end dates outside of currently displayed month.
3. Nothing happens.

(Note: setting the range with initial props also has same effect)

## Expected behavior

_Option One:_
1. Load `RangeCalendar` component.
2. Set `range` with start/end dates outside of currently displayed month.
3. Calendar displays the month containing the selected date range.

This could be enabled/disabled if needed with a "alwaysShowSelectedRange" prop.

_Option Two:
Add a `displayDate` prop which defaults to the current date. Can be overridden with some other date, and the calendar will show the month/year that contains that date.

## Link to runnable example or repository (highly encouraged)

```
import React, { useState } from 'react'
import { RangeCalendar, Button, Layout } from '@ui-kitten/components';

const MyControlledCalendar = ()=> {

    const [calendarRange, setCalendarRange] = useState(
        {
            startDate: new Date(),
            endDate: new Date(),
        });

    return (<Layout>
        <RangeCalendar
            range={calendarRange}
            min={new Date(0)}
            max={new Date()}
            onSelect={(range) => {
                setCalendarRange(range);
            }}
    />
        <Button
            status='primary'
            onPress={()=>setCalendarRange({
                startDate: new Date('Jan 01 2020'),
                endDate: new Date('Jan 05 2020')
            })}>
            Set date in the past.
        </Button>
        </Layout>)
}
```
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2.0.0    |
| @ui-kitten/components   |   ^5.0.0      |

## Environment information

```bash
  System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 60.27 MB / 16.00 GB
    Shell: 5.5.1 - /usr/local/bin/zsh
  Binaries:
    Node: 10.19.0 - ~/.nvm/versions/node/v10.19.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v10.19.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    Homebrew: 2.4.8 - /usr/local/bin/brew
    pip2: 20.1.1 - /usr/local/bin/pip2
    pip3: 19.0.3 - /usr/local/bin/pip3
    RubyGems: 3.0.3 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.17.0 - /usr/local/bin/git
    Clang: 1103.0.32.62 - /usr/bin/clang
  Servers:
    Apache: 2.4.41 - /usr/sbin/apachectl
  Virtualization:
    Docker: 19.03.12 - /usr/local/bin/docker
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 3.3 AI-182.5107.16.33.5264788
    Atom: 1.47.0
    Nano: 2.0.6 - /usr/bin/nano
    Vim: 8.1 - /usr/bin/vim
    WebStorm: 2020.2
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 11.0.2 - /usr/bin/javac
    Perl: 5.18.4 - /usr/bin/perl
    PHP: 7.3.11 - /usr/bin/php
    Python: 2.7.14 - /usr/local/bin/python
    Python3: 3.7.3 - /usr/local/bin/python3
    Ruby: 2.6.3 - /usr/bin/ruby
  Databases:
    SQLite: 3.28.0 - /usr/bin/sqlite3
  Browsers:
    Chrome: 84.0.4147.125
    Firefox: 78.0.1
    Safari: 13.1.1
```

**Comment by trevor-coleman** [comment]
Not sure if this is a bug report or a feature request. Happy to reclassify as required.

**Comment by trevor-coleman** [comment]
Found the problem:

```ts
protected selectedDate(): D {
    return this.dateService.today();
  }
```

Will see if I can figure out how to make a PR!

**Comment by trevor-coleman** [comment]
not sure if this is the right approach, but looking at the `Calendar` component, I'm thinking it might be something like this:

```ts
protected selectedDate(): D {
    return this.dateService.getMonthStart(this.props.range.startDate) || this.dateService.today();
}
````

**Comment by trevor-coleman** [comment]
I think I've figured it out:

The `CalendarPicker` component takes a `CalendarPickerProps<D>` object.

That object has a 'data' property which is an array of arrays fo date objects

```ts
export interface CalendarPickerProps<D> extends ViewProps {
  data: CalendarDateInfo<D>[][];
  // ...
}
```

Which looks like this:

```
[ [ {
      "bounding": true,
      "date": 2020-07-26T04:00:00.000Z,
      "holiday": false,
      "range": false,
    }, {
      "bounding": true,
      "date": 2020-07-27T04:00:00.000Z,
      "holiday": false,
      "range": false,
    }, 
   . . .
 ] ,
 [ . . .  ]
]
```

When you change the range, `RangeCalendar.createDates()` calls `CalendarDataService<D>.createDayPickerData()` which parses the range and creates that data object, which is then passed down to the picker. 

So when you change the range, the only things that change are the  `range` property on the `CalendarDateInfo<D>` objects in that array.

Because `shouldComponentUpdate` doesn't do deep comparisons of state and props (for performance reasons), `shouldComponentUpdate` returns `false`.

At least, this is my best guess. I'll have a think about it, but it seems to me that the solution is either to move the information about the change higher in the hierarchy, or else overriding `shouldComponentUpdate` at somewhere in the chain. 

I've never made a PR before, but this seems like it might be an achievable first issue, so happy to give it a try. If anyone has any feedback on either of the approaches or other tips they would be appreciated!

**Comment by TheEvisu** [comment]
solution is out of date? is there something relevant?
