### ISSUE TITLE
Change DateTime picker text color

### ISSUE THREAD

**Issue by radud** [akveo/react-native-ui-kitten#1224]
## 💬 Question
Hi there, 

Thank you for the awesome framework you built. 
I have one question. I use version 5 and for the DatePicker the text color is light gray. It matches placeholders' styles for other controls even when date is set. See the attached image.

![DatePicker](https://user-images.githubusercontent.com/2064363/90865392-f8fcb080-e39a-11ea-873a-d1056a7e21b3.jpg)

How can I configure/change its color?

Many thanks, 
Radu D

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |     2.0.0   |
| @ui-kitten/components   |     5.0.0    |

**Comment by trevor-coleman** [comment]
Can you share some sample code?

**Comment by radud** [comment]
Hi Trevor,

Thank you for following this. It is same behavior in Kitten Tricks apps. It looks like date picker with default style is having a gray color for text. Find the attached screenshot with the theme demo page. Kitten tricks show the same behavior. 

![datepicker_default_colors](https://user-images.githubusercontent.com/2064363/91213962-0e673700-e71b-11ea-8cf8-bb0df39acf28.png)

Is there a way to change colors of that control? Not through the theme file that will affect all other controls, which behave correctly. 

Many thanks,
Radu D

**Comment by artyorsh** [comment]
You may want to change [this property](https://github.com/eva-design/eva/blob/master/packages/eva/mapping.json#L2389).
👉  [How To](https://akveo.github.io/react-native-ui-kitten/docs/design-system/customize-mapping)
