### ISSUE TITLE
Improve input focus area

### ISSUE THREAD

**Issue by harryy2510** [akveo/react-native-ui-kitten#1227]
## 🐛 Bug Report

Can we make input more easibly clickable/focusable?

![image](https://user-images.githubusercontent.com/7416971/90988539-173bf980-e5b1-11ea-98e1-35ae91f43932.png)

Blue are is the exact are where it needs to be clicked for focusing the input. can we add more padding to input instead of the view box wrapping it to meet our styling requirements and also fulfilling the focus problem?

**Comment by artyorsh** [comment]
Please see related discussion here https://github.com/akveo/react-native-ui-kitten/issues/1206
