### ISSUE TITLE
How do I use theme in TopNavigation?

### ISSUE THREAD

**Issue by luiey** [akveo/react-native-ui-kitten#1230]
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    ^2.0.0    |
| @ui-kitten/components   |    ^5.0.0     |

### I'm currently not able to find a way to set `<TopNavigation/>` to follow theme color and set the accessory and title to be contrast with the theme. Is it available in UI Kitten? I'd love to see if the `<TopNavigation/>` have options to follow theme primary color.

Example like this:- [Food & Resto UI Kit](https://ui8.net/uicreative/products/food--resto-ui-kit)

**Comment by artyorsh** [comment]
You may want to change [this property](https://github.com/eva-design/eva/blob/master/packages/eva/mapping.json#L5742).
👉  [How To](https://akveo.github.io/react-native-ui-kitten/docs/design-system/customize-mapping)
