### ISSUE TITLE
OverflowMenu position cannot be specified.

### ISSUE THREAD

**Issue by pruge** [akveo/react-native-ui-kitten#1231]
## 🐛 Bug Report

OverflowMenu position cannot be specified.
Even if you specify botom end, it is always top end.

![Screen Shot 2020-08-26 at 9 30 23 PM](https://user-images.githubusercontent.com/5827473/91303733-649fad00-e7e3-11ea-960a-09bd764bb8d5.png)
![Screen Shot 2020-08-26 at 9 24 33 PM](https://user-images.githubusercontent.com/5827473/91303587-33bf7800-e7e3-11ea-86d0-1d9e3071700d.png)

## To Reproduce
[document top navation accessory] (https://akveo.github.io/react-native-ui-kitten/docs/components/top-navigation/overview#topnavigationaction)

## Expected behavior

![Screen Shot 2020-08-26 at 9 37 17 PM](https://user-images.githubusercontent.com/5827473/91304359-556d2f00-e7e4-11ea-8c76-54bb9d911f7f.png)

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   ^2.0.0     |
| @ui-kitten/components   |   ^5.0.0      |

## Environment information

```bash
System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
  Binaries:
    Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.18.0/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.18.0/bin/npm
  SDKs:
    Android SDK:
      API Levels: 16, 25, 26
      Build Tools: 26.0.1, 30.0.2
      System Images: a...google_apis | Google APIs Intel x86 Atom Sys...
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: /undefined - /usr/bin/xcodebuild
  npmPackages:
    react: ~16.13.1 => 16.13.1 
    react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
```

**Comment by artyorsh** [comment]
Please see #743
