### ISSUE TITLE
International phone number input field with flags needed

### ISSUE THREAD

**Issue by kockok** [akveo/react-native-ui-kitten#1235]
## 🚀 Feature Proposal

To add an international phone number input field with formatters and region flags.

## Motivation

There are many drop in packages for this, however, their themes don't match with ui kitten.

**Comment by artyorsh** [comment]
@kockok thanks for opening a proposal.
This package will not include such complex components. But I believe you're able to achieve such component by using `accessoryLeft` or `accessoryRight` properties where you can render a flag selector or something.

**Comment by obayit** [comment]
Isn't `accessoryLeft` is expected to be an image item? can I render anything there?
To quote the docs

> Input accessories are expected to be images or svg icons

![screenshot-akveo github io-2021 11 13-15_19_45](https://user-images.githubusercontent.com/20386024/141645313-b137e00d-f015-4e2e-9271-6755cb55edca.png)
