### ISSUE TITLE
TabIndicator style is not updated

### ISSUE THREAD

**Issue by MiloszFilimowski** [akveo/react-native-ui-kitten#1237]
## 🐛 Bug Report

The style of `TabBar`s `indicatorStyle` is not updated after a change because `shouldComponentUpdate` only checks if the index was changed. Other props are ignored. 

I attached a snack illustrating the issue.

I tried creating a PR fixing the issue but unfortunately adding another check for style in `shouldComponentUpdate` in `tabIndicator.component.tsx` causes the app to crash with "Attempted to remove more RCTNativeAnimatedModule listeners than added". 
Setting `useNativeDriver` to false in  `createOffsetAnimation` (same file) fixes the issue entirely but since it might impact other things I'd like to consult the change in this issue first. 

`shouldComponentUpdate`:
https://github.com/akveo/react-native-ui-kitten/blob/ea4a3620e78a262419ee6c5b116dc70a5645eefd/src/components/ui/shared/tabIndicator.component.tsx#L39

`createOffsetAnimation`:
https://github.com/akveo/react-native-ui-kitten/blob/ea4a3620e78a262419ee6c5b116dc70a5645eefd/src/components/ui/shared/tabIndicator.component.tsx#L95

## To Reproduce

1. Create TabBar
2. Try to change `indicatorStyle` to a different value without changing the tab index. 

## Expected behavior

Update indicatorStyle when it changes.

## Link to runnable example or repository (highly encouraged)

https://snack.expo.io/@andrzjugsziejestes/tabbarissueplayground

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   2.0.0   |
| @ui-kitten/components   |     5.0.0    |

## Environment information

```bash
  System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  Binaries:
    Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
    Yarn: 1.22.5 - ~/repos/tab_bar_test_repo/node_modules/.bin/yarn
    npm: 6.10.3 - ~/.nvm/versions/node/v12.10.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.9.0 => 16.13.1 
    react-native: ^0.61.5 => 0.61.5 
```

**Comment by pruge** [comment]
The style order is reversed.

[tabIndicator.component.js](https://github.com/akveo/react-native-ui-kitten/blob/982e835b336d651cd58242987207cc50b963a998/src/components/ui/shared/tabIndicator.component.tsx#L126)
```js

  public render(): React.ReactElement<ViewProps> {
    const { style, ...viewProps } = this.props;
    const evaStyle: ViewStyle = this.getComponentStyle();

    return (
      <Animated.View
        {...viewProps}
>        style={[style, evaStyle]}
        onLayout={this.onLayout}
      />
    );
  }
```

chnage 

```js
>        style={[evaStyle, style]}
```

Now you can change the color.

**Comment by andressana-s** [comment]
Did you find any solution or some way to force a change on the index?

**Comment by vitorverasm** [comment]
Same issue here

**Comment by AntonBorovoi** [comment]
Fixed within https://github.com/akveo/react-native-ui-kitten/pull/1474 and release v.5.1.1
