### ISSUE TITLE
How to change input style when RkTextInput is focused?

### ISSUE THREAD

**Issue by silasrm** [akveo/react-native-ui-kitten#124]
I'm desire to change styles (border color) only when RkTextInput is focused. How to do this?

**Comment by artyorsh** [comment]
Hi @silasrm,

Sorry for late reply. Currently css-like styling is not supported by Kitten. But this sounds like you can make some hooks on your component when it's state changed to focused.

**Comment by silasrm** [comment]
Hi @artyorsh,

Thanks for reply. I'll try make manually.
