### ISSUE TITLE
How to change the default color for datepicker

### ISSUE THREAD

**Issue by radud** [akveo/react-native-ui-kitten#1242]
## 💬 Question

Can I change the default color for date picker to be black?
If a date is selected, text color is still light gray as we have for placeholders. 

Can I achieve this with a custom mapping?
I tried this mapping, without success: 
mapping.json

{
    "components": {
        "Datepicker": {
            "appearances": {
                "default": {
                    "mapping": {
                        "text": {
                            "textColor": "black"
                        }
                    }
                }
            }
        }
    }
}

then is app.js
import { default as mapping } from './components/mapping.json';
...
<ApplicationProvider {...eva} theme={{ ...eva.light, ...theme }} customMapping={mapping}>

the output is: 
![Screenshot_20200915_132254_host exp exponent1](https://user-images.githubusercontent.com/2064363/93199342-f18cb500-f756-11ea-996c-c1cf76fbcdfd.jpg)

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |     2.0.0   |
| @ui-kitten/components   |     5.0.0    |

**Comment by hottmanmichael** [comment]
This appears to be a bug in UI kitten - It looks like the placeholder and the value text get the same component/styling - https://github.com/akveo/react-native-ui-kitten/blob/cacd67cb5ac0303eb9179e24607e695b58f012dd/src/components/ui/datepicker/datepicker.component.tsx#L212-L218

We were able to fix it temporarily by defining a custom placeholder component
```
import React from 'react';
import { TextStyle } from 'react-native';
import { Text, useTheme } from '@ui-kitten/components';

/**
 * e.g. (
 *   <DatePicker
 *     placeholder={() => <DatePickerPlaceholder text="Select a date" />}
 *   />
 * )
 */
export default function DatePickerPlaceholder({ text = 'Select a date' }: { text?: string }) {
  const theme = useTheme();
  const style = { color: theme['text-hint-color'], marginHorizontal: 8 } as TextStyle;

  return (
    <Text style={style} category="p1">
      {text}
    </Text>
  );
}
```

Then use it like so
```
<Datepicker
    date={value}
    placeholder={() => <DatePickerPlaceholder />}
/>

// or
<Datepicker
    date={value}
    placeholder={() => <DatePickerPlaceholder text="Some placeholder" />}
/>
```

**Comment by artyorsh** [comment]
> Can I change the default color for date picker to be black?

Please see [the guide](https://akveo.github.io/react-native-ui-kitten/docs/design-system/customize-mapping)
Also, [please check](https://akveo.github.io/react-native-ui-kitten/docs/guides/improving-performance#improving-performance) whether you have the metro.config.js configured in our way to improve the mapping compilation performance. 

You should probably have it configured if `customMapping` prop is not working.

**Comment by Caperious** [comment]
If anyone is looking at this issue, here is a working example.

```  "components": {
  "Datepicker": {
    "appearances": {
      "default": {
        "variantGroups": {
          "status": {
            "basic": {
              "textColor": "text-basic-color"
            }
          }
        }
      }
    }
  }
  ```

**Comment by rayhk6** [comment]
> If anyone is looking at this issue, here is a working example.
> 
> ```
>   "Datepicker": {
>     "appearances": {
>       "default": {
>         "variantGroups": {
>           "status": {
>             "basic": {
>               "textColor": "text-basic-color"
>             }
>           }
>         }
>       }
>     }
>   }
> ```

Do you know how to customize the picker background color? I don't know where I could find the component name. Thanks
<img width="366" alt="Screenshot 2022-04-24 at 8 43 13 PM" src="https://user-images.githubusercontent.com/13505570/164977129-8084d36b-0926-429e-854c-f0ce7062b7c8.png">
