### ISSUE TITLE
Width of tabIndicator is not working.

### ISSUE THREAD

**Issue by shawnzheng99** [akveo/react-native-ui-kitten#1243]
## 💬 Question
My question is that the `indicatorStyle` supplied to `TabView` component is not properly working.

As I passed `width` to `indicatorStyle`, it's not changing the width of indicator no matter the value is a number or a percentage. Other style properties are working fine (`height`, `backgroundColor`, `borderRadius`, etc.).

#### Screenshots:
<img width="833" alt="2020-09-15 下午4 33 33" src="https://user-images.githubusercontent.com/25445757/93275287-5ce38080-f771-11ea-802d-f9158362d270.png">
<img width="833" alt="2020-09-15 下午4 33 10" src="https://user-images.githubusercontent.com/25445757/93275292-5f45da80-f771-11ea-85bc-cc76aa9185dc.png">
I know the percentage is too small, but I just wanna demonstrate its not changing the width.

#### Expected something like this:
<img width="394" alt="截屏2020-09-15 下午4 34 14" src="https://user-images.githubusercontent.com/25445757/93275326-77b5f500-f771-11ea-8d52-327cb5bcc591.png">

#### [Runnable code](https://snack.expo.io/@zhengc/tabbarissueplayground)

If something wrong with my styling please let me know.

Thanks a lot!

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    1.2.0    |
| @ui-kitten/components   |    5.0.0     |

**Comment by artyorsh** [comment]
Seems to be the same issue as #1237

**Comment by phoenixbeats01** [comment]
I'm having the same problem still. @shawnzheng99 did you end up finding a solution?
