### ISSUE TITLE
Bottom margin of around 40 in iOS when using Select or OverflowMenu components

### ISSUE THREAD

**Issue by trurohit** [akveo/react-native-ui-kitten#1245]
## 🐛 Bug Report

In iOS devices, we're seeing a margin-bottom of 40 between the component and its child elements. This is manageable in OverflowMenu as we can give a margin-bottom of -40 but when using a Select component, we're unable to manage this and we're seeing a space of 40 between the dropdown and options

<img width="209" alt="Screen Shot 2020-09-21 at 2 19 49 PM" src="https://user-images.githubusercontent.com/70840315/93748232-85f28e00-fc15-11ea-96c4-266ac11abe5e.png">

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   2.0.0     |
| @ui-kitten/components   |    5.0.0     |

## Environment information

```bash
  System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.6.0 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.7/11E801a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

**Comment by be90728** [comment]
maybe you can go to 
node_modules\@ui-kitten\components\ui\select\select.component.js 
and set the "popover" stylesheet to 
```
popover: {
        overflow: 'hidden',
        top: -40
    },
```

**Comment by artyorsh** [comment]
I would suggest looking for the correct StatusBar implementation. Please see #743

**Comment by m4ttheweric** [comment]
I am seeing this happen in iOS 14.2 except the margin is around 24. 
<img width="162" alt="Screen Shot 2020-12-08 at 5 35 02 PM" src="https://user-images.githubusercontent.com/49927862/101554157-bd064f00-397b-11eb-98ce-b00a979e37d0.png">

**Comment by JustinRohweller** [comment]
Hey I ran into this issue on 5.0.0. Semi-solved it going off of Matt's comment above. Changed the Popover in my custom mapping:  Within meta.parameters
`"top": {
            "type": "number"
          }` and within appearances.default.mapping `"top": -15`
