### ISSUE TITLE
kittenTricks with Expo 38 

### ISSUE THREAD

**Issue by namfo** [akveo/react-native-ui-kitten#1248]
## 💬 Question

Hi,

I while ago I started my first App. It was easier for me to ust the Code from kittenTricks https://github.com/akveo/kittenTricks and modified it than starting from scratch.

kittenTricks and my App is working perfect with Expo 36 in Client mode or as APK on my Android Phone. But when I try to Upload this to Google Play Console I get the message I have to use API Level 29. But I use API 28.

So I upgraded to Expo 38. When I use the App or kittenTricks in Expo Client. Everything is working fine. When I build the APK with Expo an start the App. The App will close imediatley. I get no Error message. It is just closed.

I am working on this now for hours and find no solution. Do you have any hints for me?

Thanks a lot for your help.
Chris

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2.0.0    |
| @ui-kitten/components   |   5.0.0      |

**Comment by geocfu** [comment]
Be sure that you have updated the node_modules folder and also, for the upgrade of expo, you have used their indicated method.

**Comment by flexbox** [comment]
Hey @namfo 

As @geocfu suggested, you can try to flush all the React Native cache with

```
// package.json

  "cache:clear": "watchman watch-del-all && rm -rf node_modules yarn.lock && yarn install",
```

In the meantime, I am working on a project with

```
  "expo": "^39.0.0",
  "@ui-kitten/components": "^5.0.0",
```
And I was constantly bumping the version sine the SDK 36 and never encounter your issue.

Can you try to upgrade your dependencies?

If your problem is solved feel free to close the issue 😉

**Comment by artyorsh** [comment]
We started working on this. You may want to track the progress of https://github.com/akveo/kittenTricks/pulls if you're subscribed to this issue.

Closing it here.
