### ISSUE TITLE
Is there any photoshop file component that I can use to design the wireframe?

### ISSUE THREAD

**Issue by Smilefounder** [akveo/react-native-ui-kitten#125]
Hi team, thanks for the great open source so far. As I'm working on the wireframe that proposes to the client. Could you help advise if there are any PSD file that I can use based on the UI kitten?

best regards,
Huy

**Comment by malashkevich** [comment]
Hello @Smilefounder 
Unfortunately no, we don't have any UI kit. However, the next version will have UI kit.
Stay tuned!

**Comment by CapitanRedBeard** [comment]
@malashkevich Is that UI kit available yet? Would love to fiddle with a sketch file that is based on the EVA design system. Thanks!

**Comment by Davidzhu001** [comment]
+1

**Comment by malashkevich** [comment]
It's nice to know that you are still interested in UI kit. 
From v4 UI Kitten is an implementation of the EVA Design System.
We also have a website where you can get all EVA - based UI kits: https://eva.design
