### ISSUE TITLE
Expo SDK 39 Button Lag / Delay onPress

### ISSUE THREAD

**Issue by bnussman** [akveo/react-native-ui-kitten#1251]
## 🐛 Bug Report

I updated to Expo SDK 39, which updated RN to 63 and also bumped the version of many other dependencies. Now when I press on a Ui Kitten button, there is a noticeable delay after the button is pushed for the button to dim as it should if it was pressed and for the action to happen. The "onPress" animation for that button is also not really happening on iOS at all unless you push and hold for a long time before releasing the button. Web is not effected, have not tested Android.

Could this mean we need to update Ui Kitten with RN's new "Pressable" component over TouchableOpacity?

## To Reproduce

Update to latestes with "expo update"
Press any <Button> in app and delay is obvious compared to before on iOS

## Expected behavior

Buttons to be smooth and buttery like they use to be. 

## Link to runnable example or repository (highly encouraged)

 [github repo](https://github.com/bnussman/Beep)
 [snack demo](https://expo.io/@bnussman/Beep)

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2.0.0    |
| @ui-kitten/components   |    5.0.0     |

## Environment information

```bash
  System:
    OS: Linux 5.4 Pop!_OS 20.04 LTS
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.12.0 - /usr/bin/node
    npm: 6.14.8 - /usr/bin/npm
  npmPackages:
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
```

**Comment by bnussman** [comment]
could [this](https://github.com/facebook/react-native/issues/29376) be related?

**Comment by bnussman** [comment]
So basically what happened is the people over at Facebook thought it would be a good idea to add 130ms of delay to any pressable component. They have been notified that it was a terrible change and I am expecting them to revert this behavior very soon in a release.

**Comment by artyorsh** [comment]
Hi @bnussman! Please see the [0.63.3 changelog](https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#changelog). That's seems to be fixed
