### ISSUE TITLE
How to change line height for typography?

### ISSUE THREAD

**Issue by benediktdertinger** [akveo/react-native-ui-kitten#1252]
## 💬 Question
Like changing the overall `"text-font-family": "my-loaded-font",` ([described here](https://akveo.github.io/react-native-ui-kitten/docs/guides/branding#typography)) I would like to change the line height for all typograpy styles or each individually like: `"text-heading-1-line-height": 1.5,`. Is this currently possible?

I didn't find any typings for these in `mapping.d.ts`:
```ts
export declare const strict: {
    "text-font-family": string;
    "text-heading-1-font-size": number;
    "text-heading-1-font-weight": string;
    "text-heading-1-font-family": string;
```

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    ^2.0.0    |
| @ui-kitten/components   |    ^5.0.0     |

**Comment by artyorsh** [comment]
You might want to declare `lineHeight` property in [custom mapping](https://akveo.github.io/react-native-ui-kitten/docs/design-system/customize-mapping#customize-component-mapping) for Text component. And then assign the value for each `category`.

**Comment by benediktdertinger** [comment]
@artyorsh thanks for the hint. I solve it by adapting the _mapping.json_ as follows:

```json
{
  "strict": {
    "text-font-family": "baton-turbo-regular",

    "text-heading-1-font-size": 28,
    "text-heading-1-line-height": 32,

    "text-heading-2-font-size": 20,
    "text-heading-2-line-height": 24,

    "text-heading-3-font-size": 15,
    "text-heading-3-line-height": 18,

    ...
  },
  "components": {
    "Text": {
      "meta": {
        "scope": "all",
        "parameters": {
          "lineHeight": {
            "type": "number"
          }
        }
      },
      "appearances": {
        "default": {
          "mapping": {},
          "variantGroups": {
            "category": {
              "h1": {
                "lineHeight": "text-heading-1-line-height"
              },
              "h2": {
                "lineHeight": "text-heading-2-line-height"
              },
              "h3": {
                "lineHeight": "text-heading-3-line-height"
              },
              ...
            }
          }
        }
      }
    }
  }

**Comment by anhnch** [comment]
The mapping is confusing and no complete doc :(
