### ISSUE TITLE
Altering margin/border on Input element using style props not working as expected

### ISSUE THREAD

**Issue by m4ttheweric** [akveo/react-native-ui-kitten#1253]
Edit: Made a few edits as I found a hacky workaround.

Hi I am running UI Kitten 4.x and I am trying to eliminate the border and margin from the bottom of an input field.

Currently this is the only approach that "works":

```
{
   marginBottom: -4,
   borderBottomColor: 'transparent',
   borderBottomLeftRadius: 0,
   borderBottomRightRadius: 0
}
```

This feels somewhat hacky. 1) I am not totally sure how good of an idea it is to go with negative margins, and 2) I am not truly eliminating the border but just making it invisible. `borderBottomWidth: 0` seems like it would be preferable as well as `marginBottom: 0`. Is there a less hacky way to make this work?

![Screen Shot 2020-09-28 at 4 30 07 PM](https://user-images.githubusercontent.com/49927862/94495944-e77fa300-01a7-11eb-8f14-3bab6f19aa33.png)

**Comment by grigoll** [comment]
I'm having the same issue, but on latest UI Kitten 5.0.0. According to #942 it has been fixed in v5 but for me it still isn't working and I have to use workaround `marginBottom: -4`
