### ISSUE TITLE
Open modal from navigation

### ISSUE THREAD

**Issue by stephenhoult** [akveo/react-native-ui-kitten#1254]
## 💬 Question

Is it possible to open a modal from a UI kitten navigation?

Using react navigation we could set the `mode` type on the Navigator to`mode="modal"` but this doesn't seem to be an option from looking at the UI Kitten docs.

**Comment by artyorsh** [comment]
Modal component has no common with navigation types. You might want to open a screen which makes Modal component visible, for example, when the [screen becomes mounted](https://reactnavigation.org/docs/function-after-focusing-screen).
