### ISSUE TITLE
Calendar Component refresh

### ISSUE THREAD

**Issue by walidsaliba** [akveo/react-native-ui-kitten#1256]
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |  2.0.0      |
| @ui-kitten/components   |    5.0.0     |

Let's say the cells of your calendar are filled with values from an array of objects that can be updated by the user. For that I use the renderDay property. How can you refresh the values of all cells when the array changes? 
I tried to set the Array as a state and use UseEffect() to force a render when the Array changes. Still the Calendar cells in the calendar do not change values.

useEffect(() => {
      }, [Array])

**Comment by whitestranger7** [comment]
Hey, @walidsaliba.
Calendar render can't be forced like that in terms of performance. We'll implement specific prop for that in future obviously.
For now if you want to render calendar state and update cells you can change `min` & `max` properties which will trigger calendar render. Follow example below:

```js
const CalendarComponent = (props) => {
  const [date, setDate] = React.useState(props.date);
  const [minDate, setMinDate] = React.useState();

  React.useEffect(() => {
    setMinDate(date);
    props.someFunc();
    setMinDate(undefined);
  }, [])

  return (
    <Calendar {...props} min={minDate}  />
  )
}
```
