### ISSUE TITLE
Component "Select" at React Native ver 0.63

### ISSUE THREAD

**Issue by be90728** [akveo/react-native-ui-kitten#1257]
## 🐛 Bug Report

When using the [Select] component in Expo sdk 39, an error will pop up when the component is rendered. The error message is `"JSON Value'#8F9BB3' of type NSString cannot be converted to a UIColor. Did you forget to call processColor() on the JS side?"`
The point is that even if the program becomes a release version, the error will still pop up!

## To Reproduce

Using The Select Component with Expo SDK 39.

## Expected behavior

Errors will pop up, even in the release version

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2.0.0-alpha.1    |
| @ui-kitten/components   |     5.0.0-alpha.1    |

## Environment information

```
npx: installed 1 in 2.871s

  System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Pentium(R) CPU 5405U @ 2.30GHz
  Binaries:
    Node: 12.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
```

**Comment by artyorsh** [comment]
Please see https://github.com/akveo/react-native-ui-kitten/issues/1087#issuecomment-628614639
