### ISSUE TITLE
[Docs] onChangeText props in Input

### ISSUE THREAD

**Issue by robertwt7** [akveo/react-native-ui-kitten#1259]
## 🐛 Bug Report

Firstly, i'm sorry if this is my mistake. I just started using ui kitten this week actually! Trying to choose which UI kit fits for the next project in my company

Anyway, 

![image](https://user-images.githubusercontent.com/15647967/95199258-47212280-0828-11eb-9325-1570c823da9a.png)

Isn't that onChangeText supposed to be a function type? Just double checking. 

Shouldn't it be `(e) => void`?

Thanks

**Comment by artyorsh** [comment]
> Shouldn't it be (e) => void?

Yes, it should. Thanks for reporting
