### ISSUE TITLE
TopTab Navigator Horizontal Scroll

### ISSUE THREAD

**Issue by weslei-dias-vakt** [akveo/react-native-ui-kitten#1260]
Hey Is there a way to have a scrollable TopTabs on Horizontal?
If i have more than 4 tabs there is no scroll.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | 5.0.0 |
| @eva-design/eva      |        |
| @ui-kitten/components   |         |

**Comment by artyorsh** [comment]
Nope. There is no way to do that. But you may want to use [ViewPager](https://akveo.github.io/react-native-ui-kitten/docs/components/view-pager) with your own tabs.
