### ISSUE TITLE
How to pass dynamic data in select?

### ISSUE THREAD

**Issue by aidevpk** [akveo/react-native-ui-kitten#1262]
## 🐛 Bug Report

How to pass dynamic data in select?

`const array=['a','b','c','d']
<Select
          data={array}  
          selectedIndex={selectedIndex}  
          onSelect={index => setSelectedIndex(index)}>  
        </Select>
`

Whenever i use 
`<SelectItem title='Option 1'/>
        <SelectItem title='Option 2'/>
        <SelectItem title='Option 3'/>`
it is working fine but when  I am using data its not working.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   2.0.0     |
| @ui-kitten/components   |    5.0.0     |

## Environment information

```bash

```

**Comment by artyorsh** [comment]
You're not able to pass `data` starting from v5. Please see the [docs](https://akveo.github.io/react-native-ui-kitten/docs/components/select/overview#select).

**Comment by aidevpk** [comment]
> You're not able to pass `data` starting from v5. Please see the [docs](https://akveo.github.io/react-native-ui-kitten/docs/components/select/overview#select).

Can you share a small example please. I can't understand from docs.

**Comment by artyorsh** [comment]
@aidevpk 
```
<Select>
  {data.map(item => <SelectItem />)}
</Select>
```

**Comment by Summys** [comment]
@artyorsh It doesn't work of data is dynamically modified. I've came across this issue using DrawerGroup and MenuGroup

**Comment by artyorsh** [comment]
@Summys Would you provide an example code?

**Comment by Summys** [comment]
@artyorsh I don't have a full example at this time, but basically it's something like 

```
const [array, setArray] = React.useState(['a', 'b', 'c', 'd']);

<>
<DrawerGroup title='array' >
    {array.map((arr) =>
        <DrawerItem
            key={arr}
            title={arr}
        />
    )}
</DrawerGroup>

<Button onPress={setArray([...array, 'e'])} title="Push"/>
</>
```

In order to fix this issue I had to patch the menuGroup.component and replaced in render function
```
-             this.renderGroupedItemsIfNeeded({})));
+            this.renderItemsWithDefaultProps({})));
```

I guess the issue is in `renderGroupedItems` but I didn't had much time last night to investigate
