### ISSUE TITLE
MenuGroup missing props - expanded by default?

### ISSUE THREAD

**Issue by papay0** [akveo/react-native-ui-kitten#1265]
## 🚀 Feature Proposal

MenuGroup should have the ability to be expanded by default.

## Example

![image](https://user-images.githubusercontent.com/6967350/95816882-c9f12400-0ce5-11eb-988b-2d3702a43fdd.png)

**Comment by cangSDARM** [comment]
Can you consider extending this expandable behavior into a separate component?
The existing one needs to set a `Menu` first, then a `MenuGroup` and then a `MenuItem`

**Comment by wijayantoap** [comment]
Any updates for this?

**Comment by exzos28** [comment]
Any updates?
