### ISSUE TITLE
Tooltip change arrow color

### ISSUE THREAD

**Issue by wafda** [akveo/react-native-ui-kitten#1267]
How to change arrow color in Tooltip component?, I've try with backgroundColor but it's only change the rectangle color

**Comment by pablodenadai** [comment]
Did you manage to find a solution or even hide the arrow?

**Comment by pablodenadai** [comment]
You can use Popover instead.

**Comment by nikola1970** [comment]
Need this as well.

**Comment by artyorsh** [comment]
You may want to change [this property](https://github.com/eva-design/eva/blob/master/packages/eva/mapping.json#L5655).
👉  [How To](https://akveo.github.io/react-native-ui-kitten/docs/design-system/customize-mapping)
