### ISSUE TITLE
TypeError: Cannot read property 'appearances' of undefined

### ISSUE THREAD

**Issue by Sanjay1416** [akveo/react-native-ui-kitten#1269]
TypeError: Cannot read property 'appearances' of undefined

This error is located at:
    in Wrapper (created by Layout)
    in Layout (at CarRescueScreen.js:22)
    in RCTView (at View.js:34)
    in View (created by ViewPager)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (created by ViewPager)
    in ViewPager (created by TabView)
    in RCTView (at View.js:34)
    in View (created by TabView)
    in TabView (at CarRescueScreen.js:13)
    in CarRescueScreen (created by SceneView)
    in SceneView (created by CardContainer)
    in RCTView (at View.js:34)
    in View (created by CardContainer)
    in RCTView (at View.js:34)
    in View (created by CardContainer)
    in RCTView (at View.js:34)
    in View (created by ForwardRef(CardSheet))
    in ForwardRef(CardSheet) (created by Card)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (created by PanGestureHandler)
    in PanGestureHandler (created by PanGestureHandler)
    in PanGestureHandler (created by Card)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (created by Card)
    in RCTView (at View.js:34)
    in View (created by Card)
    in Card (created by CardContainer)
    in CardContainer (created by Context.Consumer)
    in RCTView (at View.js:34)
    in View (created by MaybeScreen)
    in MaybeScreen (created by Context.Consumer)
    in RCTView (at View.js:34)
    in View (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by Context.Consumer)
    in CardStack (created by KeyboardManager)
    in KeyboardManager (created by Context.Consumer)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:74)
    in SafeAreaProvider (created by Context.Consumer)
    in SafeAreaProviderCompat (created by StackView)
    in GestureHandlerRootView (at GestureHandlerRootView.android.js:31)
    in GestureHandlerRootView (created by StackView)
    in StackView (created by StackView)
    in StackView
    in Unknown (created by Navigator)
    in Navigator (created by SceneView)
    in SceneView (created by SwitchView)
    in SwitchView (created by Navigator)
    in Navigator (created by NavigationContainer)
    in NavigationContainer (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)

**Comment by chris-aeviator** [comment]
Facing the same issue when running your get started example (button) with expo

**Comment by chris-aeviator** [comment]
seems like we forgot to follow https://akveo.github.io/react-native-ui-kitten/docs/guides/getting-started#manual-installation

**Comment by malashkevich** [comment]
@Sanjay1416 is the issue still open?

**Comment by artyorsh** [comment]
@malashkevich we can close it. This error may only occur in case there is no `ApplicationProvider` in the root.
For anyone else who faces this, please check [the doc](https://akveo.github.io/react-native-ui-kitten/docs/guides/getting-started).

**Comment by IB3N** [comment]
Also happens if you have outdated node modules from npm or yarn updates, don't forget to delete and reinstall 👍
