### ISSUE TITLE
Specify path to node_modules in @ui-kitten/metro-config

### ISSUE THREAD

**Issue by dolhadan** [akveo/react-native-ui-kitten#1270]
## 🚀 Feature Proposal

Add a path to node_modules option in `evaConfig` object that it's passed to  `@ui-kitten/metro-config`. It will default to the current path if no path is specified .
## Motivation

We have a monorepo that supports multiple projects/apps. The `node_modules` directory is placed in the root directory.
When trying to run a single app from their own directory it will fail because `bootstrap.service.js` have the node_modules path hardcoded there.

## Example

Please provide an example for how this feature would be used.

```
const evaConfig = 
{
     evaPackage: '@eva-design/eva',
     modulesPath: '../node_modules`
 };

 return MetroConfig.create(evaConfig, ...);

**Comment by sschottler** [comment]
I ran into this same issue. This was my work-around:

```js
// cli.js
const path = require('path');
const findWorkspaceRoot = require('find-yarn-workspace-root');
const BootstrapService = require('@ui-kitten/metro-config/services/bootstrap.service').default;

function findRootFolder() {
  const packageFolder = path.dirname(__dirname);
  const index = packageFolder.toLowerCase().indexOf('node_modules');
  const isRunningInsideNodeModules = index > -1;

  if (isRunningInsideNodeModules) {
    return packageFolder.substring(0, index);
  }
  // running inside local monorepo:
  return findWorkspaceRoot(packageFolder);
}

const rootFolder = findRootFolder();
process.chdir(rootFolder);

BootstrapService.run({ evaPackage: '@eva-design/eva', customMappingFile: '....' });
```

```sh
node cli
```

**Comment by DomenicJahn** [comment]
Does this somehow work within an expo project? It would need to modify `metro.config.js` .
