### ISSUE TITLE
¿it is possible to use select list without accesories and text centered?

### ISSUE THREAD

**Issue by santiago1393** [akveo/react-native-ui-kitten#1272]
## 💬 Question

Hello! ¿It is possible to use the Select component with no accesories like icons etc and set value selected text centered on the touchable?

what it looks rigth now => 

![image](https://user-images.githubusercontent.com/7296373/96504635-926d0500-121a-11eb-8c0f-03ea60a9d270.png)

The main idea is use the select option menu but we want the touchable look as a button normal

what ux designer want =>  

![image](https://user-images.githubusercontent.com/7296373/96504495-5d60b280-121a-11eb-9b9b-f2d69ce1461b.png)

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |  "^2.0.0"      |
| @ui-kitten/components   |   "^5.0.0"      |

**Comment by artyorsh** [comment]
👋  there and sorry for the late reply.

You can also use Select for that. [Here](https://snack.expo.io/X8CAXUaJO) is an example code.
