### ISSUE TITLE
Select display value not taking

### ISSUE THREAD

**Issue by Bandwagoner** [akveo/react-native-ui-kitten#1275]
## 🐛 Bug Report

Passing in the **value** prop in Select component does not show the corresponding display value. However, passing in a render function works (e.g. render function that returns a Text component).

## To Reproduce

```
<Select
     value="Show this value"
     selectedIndex={selectedIndex}
     onSelect={() => {}}>
          {renderOptions()}
</Select>
```

## Expected behavior

Select shows the string value.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2.0.0    |
| @ui-kitten/components   |    5.0.0     |

## Environment information

  System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 AMD Ryzen 3 2300X Quad-Core Processor
  Binaries:
    Node: 12.19.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6858069
  npmPackages:
    react: 16.14.0 => 16.14.0
    react-native: 0.63.3 => 0.63.3

```bash

```

**Comment by artyorsh** [comment]
Please see the `Select Display Value` example in the docs. I'm almost sure the problem in your code is somewhere in `value` or `selectedIndex` props.

https://akveo.github.io/react-native-ui-kitten/docs/components/select
