### ISSUE TITLE
Top navigation action icon not greyed out when disabled

### ISSUE THREAD

**Issue by Bandwagoner** [akveo/react-native-ui-kitten#1277]
## 🐛 Bug Report

When a TopNavigationAction is disabled, the icon should be greyed out.

## To Reproduce

Pass disabled as true to a TopNavigationAction with a valid icon prop.

## Expected behavior

Icon should be greyed out

## Link to runnable example or repository (highly encouraged)

https://snack.expo.io/qB4tfY!ya

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    5.0.0    |
| @ui-kitten/components   |    2.0.0     |

## Environment information

```bash

```

**Comment by malashkevich** [comment]
Should be fixed with Eva mapping fix: https://github.com/eva-design/eva/pull/74
