### ISSUE TITLE
Spinner with custom size

### ISSUE THREAD

**Issue by jadfls** [akveo/react-native-ui-kitten#1278]
## 💬 Question

Assuming Spinner size="giant" is too small, how can I customize the spinner with a larger size? Ideally using direct width/height values?

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2.0.0    |
| @ui-kitten/components   |   5.0.0      |

**Comment by smoove** [comment]
Put this in your *[mapping.json](https://akveo.github.io/react-native-ui-kitten/docs/design-system/customize-mapping#customize-component-mapping)*

```json
{
  "components": {
    "Spinner": {
      "meta": {
        "variantGroups": {
          "size": {
            "galactic": {
              "default": false
            }
          }
        }
      },
      "appearances": {
        "default": {
          "variantGroups": {
            "size": {
              "galactic": {
                "width": 64,
                "height": 64,
                "borderRadius": 32,
                "borderWidth": 5.5
              }
            }
          }
        }
      }
    }
  }
}
```

Then use like this:
```js
<Spinner size="galactic" />
```

**Comment by exlnt** [comment]
I tried the above mapping file and I get this error:

Spinner: unsupported configuration.
Check one of the following prop values: {
  "appearance": "default",
  "variants": [
    "primary",
    "galactic"
  ],
  "states": []
}

**Comment by artyorsh** [comment]
@exlnt please make sure to follow [this guide](https://akveo.github.io/react-native-ui-kitten/docs/design-system/customize-mapping#merge-mappings).
