### ISSUE TITLE
making Selection Unique for UI kitten Select

### ISSUE THREAD

**Issue by AdebisiJoe** [akveo/react-native-ui-kitten#1279]
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |       |
| @ui-kitten/components   |   5.0      |

I have a list that I loop through to generate a list of select Elements in React native UI Kitten in that Loop I have a loop for each select item, selecting one activates the others how do I make the selection unique for each Select Element.
Here is my code

`export default function SelectSubjects() {
const [selectedIndex, setSelectedIndex] = React.useState(new IndexPath(0));
  return (
        {          
        getSchoolsubjects().map((subject, key)=>(

         <Card style={{height:wp('15%'),marginTop:20}}  key={key} >  

            <View >
              <CheckBox style={{alignSelf:'flex-start'}} checked={checkSubjects(testSubjects,subject)} 
              onChange={()=>setSubjects(subject)} >
                     {subject}         
              </CheckBox> 
            </View>  

            <View>
             <Select style={{alignSelf:'flex-end',marginTop:-wp('8%')}}
                selectedIndex={selectedIndex}
                onSelect={index => setSelectedIndex(index)}
                placeholder='Select year'         
                >

                {getSchoolSchoolYears(subject).map((year:number, index:number)=>(
                    <SelectItem    key={index} title={year}/>
                )) }   
                
              </Select>
            </View>                             
         </Card>

          ))}
)
<View>
</View>
}`

my data looks like this

`
export const schoolsubjects =[
     
    {
     "school":"University of Lagos",
     "subjects":{
         "CRS":["2009","2010","2011","2012"],
         "Literature":["2008","2009","2010"],
     }
     
    }

]    
`

**Comment by flexbox** [comment]
Hey @AdebisiJoe 
Can you put some efforts on your question? 
Using a tool like https://prettier.io/ for the formatting and add ```javascript on your code 🙏
