### ISSUE TITLE
RkTextInput placeholder fontFamily ??

### ISSUE THREAD

**Issue by deounix** [akveo/react-native-ui-kitten#128]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ x ] bug report
* [ ] feature request

### Issue description

**Current behavior:**
RkTextInput can't set placeholder fontFamily

**Comment by artyorsh** [comment]
Hi @deounix,

Sorry for late reply.
Do you mean placeholder should have the same font family as normal text or an ability to set custom font for placeholder?

**Comment by artyorsh** [comment]
@deounix,
Anyway, to customize rkTextInput for your purposes, you should use something like this. 
You need inputStyle prop. Read the docs ;)
```
<RkTextInput
  inputStyle={{fontFamily: 'Roboto-Medium'}}
  placeholder='Login' />
```
