### ISSUE TITLE
why React Native Scroll View not working with UI Kitten 5 ?

### ISSUE THREAD

**Issue by subhasisd1** [akveo/react-native-ui-kitten#1280]
I am using.

    "@eva-design/eva": "^2.0.0",
     "@ui-kitten/components": "^5.0.0",
        "@ui-kitten/eva-icons": "^5.0.0"

So what is the issue with React Native Scroll View here. 
Thank you

**Comment by artyorsh** [comment]
Hi! 👋 Could you please provide more details on this issue?

**Comment by subhasisd1** [comment]
@artyorsh , Its not scrolling on web .
I tried with simple code.

 <View style={styles.platformView}>
            <SafeAreaView>
                <ScrollView contentInsetAdjustmentBehavior="automatic">

                         <Layout style={styles.container} >


                         </Layout>
                 </ScroolView>
            </SafeAreaView>
</View>

**Comment by subhasisd1** [comment]
> Hi! 👋 Could you please provide more details on this issue?
> Maybe with example code: https://snack.expo.io/@ui-kitten/playground

this is the link please check this out.

https://snack.expo.io/@subhasisd4/online_consultancy
Sorry took time to build in expo snack.

Thank You

**Comment by artyorsh** [comment]
@subhasisd1 you need to add `flex: 1` to the container view to allow ScrollView growing. Not sure if it is a standard behavior compared to the RNW. See registration screen changes:

https://snack.expo.io/@art.yorsh/online_consultancy
