### ISSUE TITLE
Bottom of dropdown list can't be reached with scrolling

### ISSUE THREAD

**Issue by Minvy** [akveo/react-native-ui-kitten#1281]
## 💬 Question

My desired effect is to have a self contained dropdown list of fixed size, and when I expand various groups the drop down list pushes all other components down and allows me to scroll through them.

I managed to fix this with <Scrollview> but that makes my component take up most of the page which is not what I want.

Notice in image below last value in the list is "Meat Feast".
![image](https://user-images.githubusercontent.com/52128108/98042731-f6e3b300-1e1b-11eb-91de-73e7070bf80f.png)
This is with all tabs expanded and it just goes up to the pan ultimate value and refuses to scroll down further.
![image](https://user-images.githubusercontent.com/52128108/98042919-4de98800-1e1c-11eb-9db0-cac5091c241c.png)

Actually even if all tabs are not expanded the bottom is still cut out and I can't scroll down.

![image](https://user-images.githubusercontent.com/52128108/98043135-a0c33f80-1e1c-11eb-9c56-a001fdbbb589.png)

Heres some code snippets:

![image](https://user-images.githubusercontent.com/52128108/98043328-f4358d80-1e1c-11eb-9c1f-09ec022e838f.png)
![image](https://user-images.githubusercontent.com/52128108/98043361-01527c80-1e1d-11eb-85ab-2fb5136d4527.png)

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |        |
| @ui-kitten/components   |   5.0   |

**Comment by whitestranger7** [comment]
Hi, @Minvy. Im a little bit confusing with your issue. It's not reproducible on my side at all. I would appreciate you if you can provide github repo with code snippet and issue, so I can observe it closely.
P.S. Im not sure you're using 5.0 version of `ui-kitten`. Could you check it as well?

**Comment by malashkevich** [comment]
Closed due inactivity
