### ISSUE TITLE
accessibilityLabel

### ISSUE THREAD

**Issue by marcoj** [akveo/react-native-ui-kitten#1283]
## 💬 Question
How can I use accessibilityLabel prop on the Button component?

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   2.0.0   |
| @ui-kitten/components   |   5.0.0   |

**Comment by artyorsh** [comment]
```
<Button accessibilityLabel='Tap me'>
  BUTTON
</Button>
```

https://reactnative.dev/docs/accessibility#accessibilitylabel

**Comment by marcoj** [comment]
So it accepts the original touchableopacity props directly, got it. Thanks!
