### ISSUE TITLE
reflect-metadata issue

### ISSUE THREAD

**Issue by alwayrun** [akveo/react-native-ui-kitten#1285]
## 🐛 Bug Report

in entry file
import 'reflect-metadata' issue

error: 
TypeError
    at DecorateConstructor (Reflect.js:544)
    at Reflect.decorate (Reflect.js:130)
    at __decorate (text.component.js:15)
    at text.component.js:91
    at loadModuleImplementation (require.js:321)
    at guardedLoadModule (require.js:210)
    at metroRequire (require.js:128)
    at falsyText.component.js:7
    at loadModuleImplementation (require.js:321)
    at guardedLoadModule (require.js:210)

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2.0.0    |
| @ui-kitten/components   |    5.0.0     |

## Environment information

System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 366.47 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.19.0 - ~/.nvm/versions/node/v12.19.0/bin/node
    Yarn: Not Found
    npm: 6.14.8 - ~/.nvm/versions/node/v12.19.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 19, 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.1, 28.0.3, 29.0.2
      System Images: android-23 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.7/11E801a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_171 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

index.js
```javascript
/**
 * @format
 */

import 'reflect-metadata';
import 'react-native-gesture-handler';
import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';

AppRegistry.registerComponent(appName, () => App);


```

App.ts
```typescript
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * Generated with the TypeScript template
 * https://github.com/react-native-community/react-native-template-typescript
 *
 * @format
 */

import React from 'react';
import { ApplicationProvider, IconRegistry } from '@ui-kitten/components';
import { Text } from '@ui-kitten/components';
import { EvaIconsPack } from '@ui-kitten/eva-icons'
import * as eva from '@eva-design/eva';

const App = () => {
  return (
    <>
      <IconRegistry icons={EvaIconsPack}/>
      <ApplicationProvider {...eva} theme={eva['light']}>
        <Text>Hello World</Text>
      </ApplicationProvider>
    </>
  )
};

export default App;

```

**Comment by mrcwbr** [comment]
I'm having the same issue on a brand new react app using [InversifyJS](http://inversify.io). if I enable inversely including the line `import 'reflect-metadata';` I get this error message in the Debugger and the app won't start up:
```
ExceptionsManager.js:179 Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
reactConsoleErrorHandler @ ExceptionsManager.js:179
n @ backend.js:32
reportException @ ExceptionsManager.js:104
handleException @ ExceptionsManager.js:171
handleError @ setUpErrorHandling.js:24
reportFatalError @ error-guard.js:49
__guard @ MessageQueue.js:366
callFunctionReturnFlushedQueue @ MessageQueue.js:108
(anonymous) @ debuggerWorker.cff11639.js:4
ExceptionsManager.js:134 Unable to symbolicate stack trace: The stack is null

```

**Comment by Dammic** [comment]
We're having the same issue, one of the libraries we use requires this package, and in consequence, we got this weird error. Is there any workaround? I'll try to investigate on one myself.

**Comment by Dammic** [comment]
So far the only workaround I've found was to manually remove the importing of reflect-metadata' in the library I'm using in postinstall script (which of course is not in any shape any long-term solution). It looks like it replaces the global Reflect, which makes it incompatible with kitten legacy decorators (https://github.com/akveo/react-native-ui-kitten/blob/master/babel.config.js#L6).

**Comment by artyorsh** [comment]
For inversify support I ended with importing reflection services from core-js, and not reflect-metadata.

```js
import 'core-js/es7/reflect';
```

**Comment by zeallat** [comment]
> For inversify support I ended with importing reflection services from core-js, and not reflect-metadata.
> 
> ```js
> import 'core-js/es7/reflect';
> ```

typedi also worked

**Comment by rhyek** [comment]
With core-js 3.15.2 this worked for me `import 'core-js/proposals/reflect-metadata';`.

**Comment by Limuyang1013** [comment]
meet same issue

**Comment by AnsonT** [comment]
Same issue with typeorm

**Comment by bataevvlad** [comment]
To fix the issue with Inversify support, you can follow these steps:

Import reflection services from core-js instead of reflect-metadata. 
Use one of the following imports based on your version of core-js:

For core-js 2.x:
`import 'core-js/es7/reflect';
`
For core-js 3.x:
`import 'core-js/proposals/reflect-metadata';
`

Make sure to import this line before any other code that relies on decorators and reflection.

**Comment by AnsonT** [comment]
Core-js reflect-metadata does not work with the latest build of ReactNative  and UI Kitten. I've created a simple repo: https://github.com/AnsonT/uikittenTypeORMBug

I added reflect-metadata in App.tsx, and get the error: `Maximum call stack size exceeded (native stack depth).`, removing the reflect-metadata line will allow this example to run.

```typescript

/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 */

import React from 'react';
import 'core-js/proposals/reflect-metadata';
import * as eva from '@eva-design/eva';
import {ApplicationProvider, Layout, Text} from '@ui-kitten/components';

const HomeScreen = () => (
  <Layout style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
    <Text category="h1">HOME</Text>
  </Layout>
);

export default () => (
  <ApplicationProvider {...eva} theme={eva.light}>
    <HomeScreen />
  </ApplicationProvider>
);
```

**Comment by ankarm** [comment]
@bataevvlad - I am trying to add uikitten to a fairly large project that currently uses reflect-metadata. It is not feasible to substitute reflect-metadata for something else because of just the sheer size of my repo. Is there a different workaround for this issue?
