### ISSUE TITLE
Input in Modal (Keyboard overlap)

### ISSUE THREAD

**Issue by paulovnas** [akveo/react-native-ui-kitten#1287]
## 💬 Question

Hi Guys,  
I have one model with textinput inside, but, my keyboard overlap this field.
I tried to use KeyboardAvoidingView, but did not work.

Can someone help me please?  

[![Wrong][1]][1]

  [1]: https://i.stack.imgur.com/h232s.png

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |  2.0.0      |
| @ui-kitten/components   |    5.0.0     |

**Comment by Charles22219** [comment]
I saw this being used in kitten tricks https://www.npmjs.com/package/react-native-keyboard-aware-scroll-view. However it was not for a modal. Havent tried it myself but it might work.

**Comment by Antonhansel** [comment]
Hey, I have the same issue and using  https://www.npmjs.com/package/react-native-keyboard-aware-scroll-view doesn't work, as OP explained

**Comment by Charles22219** [comment]
The only solution I can think of is to put a position style on your card like this style={{ bottom: bottomValue }}, and then listen to keyboard when it open/close and inside it change value of 'bottomValue'

**Comment by ferprez** [comment]
how you guys solved this issue?

**Comment by MaloRchrd** [comment]
Same issue here
I Fixed it using Scrollview 

https://reactnative.dev/docs/scrollview

**Comment by SaidTorres3** [comment]
> The only solution I can think of is to put a position style on your card like this style={{ bottom: bottomValue }}, and then listen to keyboard when it open/close and inside it change value of 'bottomValue'

I used marginBottom instead of bottom, bottom made me many issues. Thank you.

This is the useEffect that I used in order to get the keyboard height every time the keyboard appeared or disappeared:

    useEffect(() => {
            Keyboard.addListener("keyboardDidShow", (e) => {
                setKeyboardSize(e.endCoordinates.height)
            })
    
            Keyboard.addListener("keyboardDidHide", (e) => {
                setKeyboardSize(e.endCoordinates.height)
            })
    
            return (() => {
                Keyboard.removeAllListeners("keyboardDidShow");
                Keyboard.removeAllListeners("keyboardDidHide");
            })
        }, [])

And this is the modal and card with the style:

      <Modal
            visible={addUserModal}
            backdropStyle={styles.backdrop}
            style={styles.modal}
            onBackdropPress={() => setAddUserModal(false)}>
            <Card style={{ marginBottom: keyboardSize }} disabled={true}>
                <AddUser finished={() => { setAddUserModal(false) }}></AddUser>
            </Card>
        </Modal>

**Comment by perry-mitchell** [comment]
@SaidTorres3 Thanks for that! Your solution works perfectly. I went ahead and make a separate hook so it's easily reused wherever you create modal components:

```typescript
import { useEffect, useState } from "react";
import { Keyboard } from "react-native";

export function useKeyboardSize(): number {
    const [keyboardSize, setKeyboardSize] = useState(0);
    useEffect(() => {
        Keyboard.addListener("keyboardDidShow", e => {
            setKeyboardSize(e.endCoordinates.height)
        });
        Keyboard.addListener("keyboardDidHide", e => {
            setKeyboardSize(e.endCoordinates.height)
        });
        return () => {
            Keyboard.removeAllListeners("keyboardDidShow");
            Keyboard.removeAllListeners("keyboardDidHide");
        };
    }, []);
    return keyboardSize;
}
```

**Comment by OziTFA** [comment]
@perry-mitchell maybe better to set 0 when hide;

`  const hideListener = Keyboard.addListener("keyboardDidHide", e => {
            setKeyboardSize(0)
        });`

**Comment by bataevvlad** [comment]
@SaidTorres3 @perry-mitchell 

Since our library is quite complex we cannot calculate all possible use cases, thank you very much for providing the correct answer :)
