### ISSUE TITLE
Could not resolve dependency

### ISSUE THREAD

**Issue by hrtorbov** [akveo/react-native-ui-kitten#1289]
```
hrtorbov@Hristo-Torbovs-MacBook gigs.com % npx react-native init mobile --template @ui-kitten/template-ts
                                                          
               ######                ######               
             ###     ####        ####     ###             
            ##          ###    ###          ##            
            ##             ####             ##            
            ##             ####             ##            
            ##           ##    ##           ##            
            ##         ###      ###         ##            
             ##  ########################  ##             
          ######    ###            ###    ######          
      ###     ##    ##              ##    ##     ###      
   ###         ## ###      ####      ### ##         ###   
  ##           ####      ########      ####           ##  
 ##             ###     ##########     ###             ## 
  ##           ####      ########      ####           ##  
   ###         ## ###      ####      ### ##         ###   
      ###     ##    ##              ##    ##     ###      
          ######    ###            ###    ######          
             ##  ########################  ##             
            ##         ###      ###         ##            
            ##           ##    ##           ##            
            ##             ####             ##            
            ##             ####             ##            
            ##          ###    ###          ##            
             ###     ####        ####     ###             
               ######                ######               
                                                          

                  Welcome to React Native!                
                 Learn once, write anywhere               

✔ Downloading template
✔ Copying template
✔ Processing template
✖ Installing dependencies
error Error: Command failed: npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: mobile@0.0.1
npm ERR! Found: react-native-svg@12.1.0
npm ERR! node_modules/react-native-svg
npm ERR!   react-native-svg@"^12.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native-svg@"^9.13.6" from @ui-kitten/components@5.0.0
npm ERR! node_modules/@ui-kitten/components
npm ERR!   @ui-kitten/components@"5.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/hrtorbov/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hrtorbov/.npm/_logs/2020-11-21T10_24_16_881Z-debug.log
```

**Comment by volkan-a** [comment]
I think that's because node@15. When I downgraded to @14 it worked.

**Comment by doanxuanhung1997** [comment]
You have dependency conflict (incorrect and potentially broken dependency) as it says, So try to to run the command with --force, or --legacy-peer-deps.
Try this command:

**npm install --save --legacy-peer-deps**

**Comment by hrtorbov** [comment]
> You have dependency conflict (incorrect and potentially broken dependency) as it says, So try to to run the command with --force, or --legacy-peer-deps.
> Try this command:
> 
> **npm install --save --legacy-peer-deps**

I doubt it. They might have fixed it now, but when I tried it back then it was on a brand new machine, freshly installed everything. I'll close the issue since I'm not sure if it's fixed already or not.

**Comment by nithinbabusage** [comment]
Hi @doanxuanhung1997 @volkan-a @artyorsh 
I am getting the error of the unable to resolve dependency tree
node_modules/semantic-release
npm ERR!   semantic-release@"^17.4.7" from the root project
and I tried the above command of the npm install --save --legacy-peer-deps and also npm install --force, and npm cache but still i get the same error not sure how to solve it

Kindly help.. attaching the screen shot
![image](https://user-images.githubusercontent.com/104903370/169103946-b3f5f697-5218-409f-a1cc-4211095f765a.png)

Also the package.json file

{
  "name": "sbc.clientmanagement.ui",
  "version": "0.0.0-dev",
  "repository": {
    "type": "git",
    "url": "https://github.com/Sage/sbc.accountants.clientmanagement.ui.git"
  },
  "main": "src/Index.tsx",
  "dependencies": {
    "@axe-core/react": "^4.0.0",
    "@flatfile/sdk": "^2.0.0-rc7",
    "@sage/sbc.core.authentication.ui": "^2.1.4",
    "@sage/sbc.core.authorization.ui": "^5.1.0",
    "@sage/sbc.core.scene.ui": "^1.3.4",
    "@sage/sbc.core.utils.ui": "^10.4.0",
    "@sage/sbc.core.audit.ui": "^1.8.0",
    "@types/resize-observer-browser": "^0.1.5",
    "carbon-react": "106.1.4",
    "core-js": "^3.8.1",
    "cross-env": "^7.0.3",
    "dotenv": "^8.2.0",
    "file-loader": "^6.2.0",
    "formik": "^2.1.5",
    "i18next": "^20.3.0",
    "identity-obj-proxy": "^3.0.0",
    "lodash": "^4.17.21",
    "lz-string": "^1.4.4",
    "moment": "^2.29.3",
    "normalizr": "^3.6.0",
    "odata-query": "^6.7.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-i18next": "^11.9.0",
    "react-markdown": "^6.0.3",
    "react-router": "6.0.0-beta.3",
    "react-router-dom": "6.0.0-beta.3",
    "semantic-release": "^17.4.7",
    "single-spa-react": "^3.2.0",
    "uuid": "^8.3.2",
    "waait": "^1.0.5",
    "yup": "^0.29.1"
  },
  "devDependencies": {
    "@babel/core": "^7.10.5",
    "@babel/preset-env": "^7.14.2",
    "@babel/preset-react": "^7.12.0",
    "@babel/preset-typescript": "^7.12.7",
    "@commitlint/cli": "^12.1.1",
    "@commitlint/config-conventional": "^12.1.1",
    "@sage/design-tokens": "^2.25.0",
    "@sage/sbc.ui.semantic-release-plugin-s3": "^1.1.0",
    "@semantic-release/changelog": "^5.0.1",
    "@semantic-release/exec": "^6.0.2",
    "@semantic-release/git": "^9.0.0",
    "@testing-library/jest-dom": "^5.11.1",
    "@testing-library/react": "^11.2.7",
    "@testing-library/react-hooks": "^6.0.0",
    "@testing-library/user-event": "^13.1.9",
    "@types/enzyme": "^3.10.5",
    "@types/enzyme-adapter-react-16": "^1.0.6",
    "@types/history": "^4.7.9",
    "@types/i18n-js": "^3.0.3",
    "@types/jest": "^26.0.5",
    "@types/jsdom": "^16.2.6",
    "@types/lodash": "^4.14.173",
    "@types/lz-string": "^1.3.34",
    "@types/node-fetch": "^2.5.7",
    "@types/react-dom": "^16.9.8",
    "@types/react-router-dom": "^5.1.5",
    "@types/service_worker_api": "0.0.9",
    "@types/single-spa-react": "^3.0.1",
    "@types/styled-components": "^5.1.9",
    "@types/styled-system": "^5.1.11",
    "@types/systemjs": "^6.1.1",
    "@types/uuid": "^8.3.0",
    "@types/yup": "^0.29.3",
    "@typescript-eslint/eslint-plugin": "^4.10.0",
    "@typescript-eslint/parser": "^4.28.5",
    "acorn": "^8.7.1",
    "babel-loader": "^8.1.0",
    "clean-webpack-plugin": "^3.0.0",
    "commitizen": "^4.2.4",
    "conventional-changelog-conventionalcommits": "^4.5.0",
    "copy-webpack-plugin": "^9.0.1",
    "css-loader": "^5.0.1",
    "cz-conventional-changelog": "^3.3.0",
    "draft-js": "^0.11.7",
    "enzyme": "^3.11.0",
    "enzyme-adapter-react-16": "^1.15.2",
    "enzyme-to-json": "^3.5.0",
    "eslint": "^7.18.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-import": "^2.21.2",
    "eslint-plugin-jest": "^24.1.3",
    "eslint-plugin-jest-dom": "^3.6.5",
    "eslint-plugin-jsx-a11y": "^6.3.1",
    "eslint-plugin-prettier": "^3.1.4",
    "eslint-plugin-react": "^7.20.0",
    "eslint-plugin-react-hooks": "^4.2.0",
    "eslint-plugin-testing-library": "^5.0.1",
    "fetch-mock": "^9.10.4",
    "fs": "0.0.1-security",
    "history": "^5.1.0",
    "husky": "^4.3.8",
    "install": "^0.13.0",
    "jest": "^26.1.0",
    "jest-teamcity-reporter": "^0.9.0",
    "jest-watch-typeahead": "^0.6.1",
    "jsdom": "^16.6.0",
    "lint-staged": "^10.2.11",
    "mini-css-extract-plugin": "^2.4.3",
    "mockdate": "^3.0.5",
    "msw": "^0.28.1",
    "node-fetch": "^2.6.7",
    "prettier": "^2.1.2",
    "prettier-eslint-cli": "^5.0.0",
    "style-loader": "^1.2.1",
    "styled-components": "^4.4.1",
    "systemjs-webpack-interop": "^2.1.1",
    "typescript": "4.1.6",
    "webpack": "^5.61.0",
    "webpack-cli": "^4.9.1",
    "webpack-dev-server": "^4.7.3",
    "whatwg-fetch": "^3.0.0"
  },
  "scripts": {
    "compile": "tsc",
    "start": "cross-env NODE_ENV=development webpack-dev-server",
    "build": "cross-env NODE_ENV=production webpack",
    "test": "jest --watchAll=true",
    "test:coverage": "npm test -- --coverage --watchAll=false",
    "test:debug": "npm test -- --detectOpenHandles",
    "test:silent": "npm test -- --silent",
    "lint": "npm run compile && prettier --check \"./src/**/*.{ts,tsx}\" && eslint \"./src/**/*.{ts,tsx}\"  --max-warnings 31",
    "lint-staged": "lint-staged",
    "format": "prettier --write \"./src/**/*.{ts,tsx}\"",
    "commit-msg": "commitlint -E HUSKY_GIT_PARAMS",
    "commit": "cz",
    "prepublishOnly": "npm run build",
    "release": "semantic-release"
  },
  "husky": {
    "hooks": {
      "pre-commit": "npm run lint-staged",
      "commit-msg": "commitlint -E HUSKY_GIT_PARAMS"
    }
  },
  "commitlint": {
    "extends": [
      "@commitlint/config-conventional"
    ]
  },
  "lint-staged": {
    "src/**/*.{tsx,ts}": [
      "npm run format",
      "npm run lint -- --fix"
    ]
  },
  "config": {
    "commitizen": {
      "path": "./node_modules/cz-conventional-changelog"
    }
  },
  "browserslist": {
    "production": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version",
      "last 1 edge version"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version",
      "last 1 edge version"
    ]
  },
  "testEnvironment": "jsdom"
}


Also the pacak
