### ISSUE TITLE
please support rn 0.56

### ISSUE THREAD

**Issue by zshchou** [akveo/react-native-ui-kitten#129]
rt.

**Comment by artyorsh** [comment]
Hi @zshchou,

We'll work on upgrading as soon as expo will support it and currently we're not able to do it.
Thanks

**Comment by LouisIV** [comment]
@zshchou All I had to do to get it to work was changing `node_modules/react-native-ui-kitten/src/components/image/rkModalImg.js` line 283 from: `...imgProps,` to: `...imgProps`
I haven't had any issues yet.

**Comment by LouisIV** [comment]
I realized today while writing a script to fix this that Prettier is changing my line numbers. Basically what you need to do is remove the trailing commas:
```
A,
B,
C, <-- Wrong

A,
B,
C <-- Right
```
I still haven't had any issues. 
react-native-ui-kitten 3.0.1
react-native 0.56

**Comment by artyorsh** [comment]
@LouisIV 
Thanks for suggestion.
Also if you don't use prettier but use eslint, you can do the following:
https://github.com/eslint/eslint/issues/7297

**Comment by artyorsh** [comment]
Fixed in [v3.1.0](https://github.com/akveo/react-native-ui-kitten/tree/v3.1.0)
