### ISSUE TITLE
Make Tab Scrollable

### ISSUE THREAD

**Issue by Vn-ChemGio** [akveo/react-native-ui-kitten#1292]
Hi guy.
I'm making a React Native with layout has multiple tab (>10 tab) but I have a problem when using Tab in UI Kitten 
See the image, 

![127280274_1027048067764503_5301100503378642083_n](https://user-images.githubusercontent.com/25608423/99999471-caa3cc80-2df2-11eb-9cd0-6cea5bdf6b9a.jpg)
The TabBar tittle has problem, 
So I need it can be scroll, 
Can you tell me how to fix, or additional this problem to next feature
Thanks!

**Comment by artyorsh** [comment]
👋 
 Please see https://github.com/akveo/react-native-ui-kitten/issues/634
