### ISSUE TITLE
ui-kitten react-native

### ISSUE THREAD

**Issue by abaidbutt** [akveo/react-native-ui-kitten#1295]
![kitten](https://user-images.githubusercontent.com/49604057/100830472-92049280-3485-11eb-8f4e-6acdab161761.png)
hi, 
i want color my text using props (status='primary') in react-native with ui kitten.

**Comment by artyorsh** [comment]
👋 
Did you complete [Getting Started Guide](https://akveo.github.io/react-native-ui-kitten/docs/guides/getting-started#getting-started)?

**Comment by abaidbutt** [comment]
yes, I completed this guide,  please make a project in react-native in @ui-kitten/components use mapping from eva or custom mapping send me your repository in which you are using mapping  or customMapping (status='primary') or (status='danger')

**Comment by artyorsh** [comment]
You can see the working example in our docs, it runs a bare setup. Please make sure you import `Text` component from the proper package

**Comment by abaidbutt** [comment]
/** * Sample React Native App * https://github.com/facebook/react-native * * Generated with the UI Kitten template * https://github.com/akveo/react-native-ui-kitten * * Documentation: https://akveo.github.io/react-native-ui-kitten/docs * * @format */ import React, {useEffect} from 'react';import {StyleSheet} from 'react-native';import {  ApplicationProvider,  Button,  Icon,  IconRegistry,  Layout,  Text,} from '@ui-kitten/components';import {EvaIconsPack} from '@ui-kitten/eva-icons';import * as eva from '@eva-design/eva';import SplashScreen from 'react-native-splash-screen';/** * Use any valid `name` property from eva icons (e.g `github`, or `heart-outline`) * https://akveo.github.io/eva-icons */const HeartIcon = (props) => <Icon {...props} name="heart" />; export default () => {  useEffect(() => {    SplashScreen.show();  }, []);   return (    <>      <IconRegistry icons={EvaIconsPack} />      <ApplicationProvider {...eva} theme={eva.light}>        <Layout style={styles.container}>          <Text style={styles.text} status="primary">            kuch niaya krty h          </Text>          <Text style={styles.text} status="info">            Start with editing App.js to configure your App          </Text>          <Text style={styles.text} status="success">            For example, try changing theme to Dark by using eva.dark          </Text>          <Button style={styles.likeButton} accessoryLeft={HeartIcon}>            LIKE          </Button>        </Layout>      </ApplicationProvider>    </>  );}; const styles = StyleSheet.create({  container: {    flex: 1,    justifyContent: 'center',    alignItems: 'center',  },  text: {    textAlign: 'center',  },  likeButton: {    marginVertical: 16,  },}); Sent from Mail for Windows 10 From: Artur YorshSent: Wednesday, December 2, 2020 2:34 PMTo: akveo/react-native-ui-kittenCc: abaidbutt; AuthorSubject: Re: [akveo/react-native-ui-kitten] ui-kitten react-native (#1295) You can see the working example in our docs, it runs a bare setup. Please make sure you import Text component from the proper package—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ImAbhishekTomar** [comment]
Maybe someone else also help you if you share code after some alignment formatting. Currently it's not readable.
