### ISSUE TITLE
Autocomplete list stuck on screen when hardware back pressed

### ISSUE THREAD

**Issue by eyalyoli** [akveo/react-native-ui-kitten#1297]
## 🐛 Bug Report

When using Autocomplete on Android and the pop over list is open, pressing hardware back button leaves the list open even when you leave the screen and you can't dismiss after that (only when reloading the app).

## To Reproduce

Steps to reproduce the behaviour:
1. Use Autocomplete on android device
2. Open the screen with autocomplete
3. search something that has results
4. click only on hardware back button to leave the screen
5. the lists stays open and cannot be dismissed

## Expected behavior

the list is dismissed on hardware back press

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2    |
| @ui-kitten/components   |      5   |

## Environment information

```bash

```

**Comment by eyalabs** [comment]
Anything?

**Comment by Dammic** [comment]
I wonder if this is also related to https://github.com/akveo/react-native-ui-kitten/issues/1229

**Comment by JulianoAmaralChaves** [comment]
I had the same problem with Select and Calendar, is there a specific solution for each one?

**Comment by bataevvlad** [comment]
We checked it on new versions, all looks good, please update to the latest version of package 5.3.0 issue already resolved there.
