### ISSUE TITLE
Drawer `highlight`

### ISSUE THREAD

**Issue by mofengfs** [akveo/react-native-ui-kitten#1298]
## I want to implement the default selected state of `Drawer' row` to "highlight" for the first time, instead of triggering the first state through "onSelect". I checked the `API` of `Drawer` and there is no relevant information.

| UI-Kitten      | @5.0.0|  
| @ui-kitten/components   |    Drawer     |

**Comment by artyorsh** [comment]
You should implement that behavior by yourself. Just remove any navigation logic from your handling function and add predicate for selected index comparison. I guess something like this should make it work


```js
const [selectedIndex, setSelectedIndex] = React.useState();

const onSelect = (index) => {
  const prevIndex = selectedIndex;

  setSelectedIndex(index); // highlight it
  if(prevIndex && prevIndex.equals(index)) {
    // navigate
  }
};

**Comment by artyorsh** [comment]
The first example in the docs.

**Comment by mofengfs** [comment]
> 文档中的第一个示例。

Sorry, I ignored it. It does exist. Thank you
