### ISSUE TITLE
Set indicator color to an inactive tab in TabView

### ISSUE THREAD

**Issue by adscud** [akveo/react-native-ui-kitten#1299]
## 💬 Question

Hi,
I want to add a color to the indicator if the tab is inactive, I would like to know how it is clean to do it, because by simply passing the style, it does not have the expected style.

Expected : 
![Capture d’écran 2020-12-03 à 09 27 11](https://user-images.githubusercontent.com/34245352/100983605-d48fa300-3549-11eb-9441-f3381238a1d0.png)

Actual : 
![Capture d’écran 2020-12-03 à 09 30 03](https://user-images.githubusercontent.com/34245352/100983846-2b957800-354a-11eb-968b-599f1da311bb.png)

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2.0.0    |
| @ui-kitten/components   |    5.0.0     |

**Comment by artyorsh** [comment]
There is no `activeColor` or something like this in any component in this library. And will never be because it's design-system driven. Please check [this guide](https://akveo.github.io/react-native-ui-kitten/docs/design-system/customize-mapping) to understand the way you can achieve that.

**Comment by productStef** [comment]
Hey @adscud, just curious if you were able to create your desired style using the guide? 

Was hoping to go the absolute positioning route (see below) but not working as expected
`<Tab
            title={title}
          />
          <Bar
            style={{
              position: "absolute",
              bottom: -7,
              left: 0,
              right: 0,
              height: 5,
              backgroundColor: "grey",
              zIndex: -1,
            }}
          />
</Tab>`

Best!

**Comment by productStef** [comment]
@adscud NVM, found a solution tweaking not just the Tab component but the TabBar as well. Happy to share if you never got around to doing it. 

Thanks @artyorsh for the guide.

**Comment by adscud** [comment]
Thanks @productStef but I'm out of this library now ! :)

**Comment by Omar-8** [comment]
> @adscud NVM, found a solution tweaking not just the Tab component but the TabBar as well. Happy to share if you never got around to doing it.
> 
> Thanks @artyorsh for the guide.

Could you show me around?

**Comment by MichalRemis** [comment]
I achieved something like that by tweaking custom TabBar props like this:
```
<TabBar
  ....
  indicatorStyle={{
    backgroundColor: 'blue',
    height: 4,
  }}
  indicatorContainerStyle={{
    backgroundColor: "silver",
    height: 4,
    marginTop: 44,
  }}
```
