### ISSUE TITLE
I moved the previous project to Expo, but an error was reported on the web.

### ISSUE THREAD

**Issue by mofengfs** [akveo/react-native-ui-kitten#1302]
![image](https://user-images.githubusercontent.com/16655229/101312333-7850ba00-388e-11eb-995f-88f046b1ad98.png)

![image](https://user-images.githubusercontent.com/16655229/101312225-2f990100-388e-11eb-8e99-3fe9fb732f4d.png)

**Comment by artyorsh** [comment]
https://github.com/akveo/react-native-ui-kitten/issues/996

**Comment by mofengfs** [comment]
@artyorsh 
[996](https://github.com/akveo/react-native-ui-kitten/issues/996#issuecomment-632729562) Yes, it can run. Thx
