### ISSUE TITLE
Change text color of a caption for an Input

### ISSUE THREAD

**Issue by parikh20** [akveo/react-native-ui-kitten#1306]
Is there a way I can change the color of Input caption easily?

**Comment by henriquemenegao** [comment]
You can just use the `Text` component as the `caption` parameter, and set the `status` prop with desired color, like this:

![image](https://user-images.githubusercontent.com/33027851/102710299-2d707280-4290-11eb-83ea-4611d3477ec4.png)

**Comment by artyorsh** [comment]
@henriquemenegao correct. But this should be a function, not an element passed directly 
See [docs](https://akveo.github.io/react-native-ui-kitten/docs/components/input/overview#input)

**Comment by parikh20** [comment]
Thanks I got it to work!

**Comment by Abhishek12345679** [comment]
I came here looking for a similar solution but with respect to the label prop, you can do exactly @artyorsh and @henriquemenegao did.

```javascript
<Input
   textStyle={{ color: "#000" }}
   label={() => <Text style={{fontWeight:"bold"}}>Name</Text>} // like this
   size="large"
   onChangeText={handleChange('name')}
   onBlur={handleBlur('name')}
   value={values.name}
/>
```
