### ISSUE TITLE
Modal memory leak

### ISSUE THREAD

**Issue by mofengfs** [akveo/react-native-ui-kitten#1308]
## 🐛 Bug Report

Warning: Cannot update during an existing state transition (such as withinrender). Render methods should be a pure function of props and state.
![image](https://user-images.githubusercontent.com/16655229/102195255-4926f200-3ef9-11eb-8a26-30046d5a1701.png)

## To Reproduce

I use pictures as the video list and modal as the window for video playback. After switching videos several times, an error is reported.

## Link to runnable example

[snack](https://snack.expo.io/@fengmo/memory-leak)

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva    |    ^2.0.0   |
| @ui-kitten/components   |    ^5.0.0     |

## Environment information

Type: [Simulator]
Device: [Genymotion]
OS: [Android9.0]
"expo-video-player": "^1.6.1",
Expo version (in 40)
Expo CLI version (4.0.13)

```bash

```

**Comment by artyorsh** [comment]
Please see https://github.com/akveo/react-native-ui-kitten/issues/1094#issuecomment-630141254
