### ISSUE TITLE
Why doesn't `DrawerGroup` have "Open section by default" properties?

### ISSUE THREAD

**Issue by mofengfs** [akveo/react-native-ui-kitten#1310]
## Why doesn't `DrawerGroup` have "Open section by default" properties?
I want the first `DrawerGroup` to Open section by default.
e.g : https://jqueryui.com/accordion/

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    ^2.0.0    |
| @ui-kitten/components   |     ^5.0.0    |

**Comment by artyorsh** [comment]
Duplicates https://github.com/akveo/react-native-ui-kitten/issues/1265
