### ISSUE TITLE
Is there a way to add custom fonts in expo setup ?

### ISSUE THREAD

**Issue by suchcodemuchwow** [akveo/react-native-ui-kitten#1311]
## 💬 Question
I tried the method explained in https://akveo.github.io/react-native-ui-kitten/docs/guides/branding#branding but I believe it doesn't work with expo. Searched through docs and couldn't find any information about that.
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |        |
| @ui-kitten/components   |         |

**Comment by valinagacevschi** [comment]
you need first to install `expo-font`
here's a way:

```
import { AppLoading } from 'expo'
import * as eva from '@eva-design/eva'
import * as Font from 'expo-font'

const loadFonts = () => {
  return Font.loadAsync({
    'roboto-bold': require('./assets/fonts/Roboto-Bold.ttf'),
    'roboto-italic': require('./assets/fonts/Roboto-Italic.ttf'),
    'roboto': require('./assets/fonts/Roboto.ttf'),
  })
}

....
  const [fontsLoaded, setFontsLoded] = useState(false)
....
  if (!fontsLoaded) {
    return <AppLoading startAsync={loadFonts} onFinish={() => setFontsLoded(true)} />
  }

  return (
      <ApplicationProvider {...eva} theme={eva['dark']}>
        {children}
      </ApplicationProvider>
  )
```
Then you can add the default font for instance in `mapping.json`.
```
{
  "strict": {
    "text-font-family": "roboto"
  }
}
```
or to button
```
{
  "components": {
    "Button": {
      "appearances": {
        "filled": {
          "mapping": {
            "textFontFamily": "roboto-bold"
          },
          "status":{
            "primary": {
              "textFontFamily":"roboto-italic"
            }
          }
        }
      }
    }
  }  
}
```

**Comment by emmaodia** [comment]
Kindly note that you have to install `AppLoading` using `expo install expo-app-loading` 
See documentation here: https://docs.expo.io/versions/latest/sdk/app-loading/#installation

Update the `if` statement to check `fontsLoaded` like so:

```javascript
 if (!fontsLoaded) {
    return <AppLoading startAsync={loadFonts} onFinish={() => setFontsLoded(true)}  onError={console.warn} />
  }
```

`AppLoading` requires `onError` prop if `startAsync` is provided.

Here's a Github gist: https://gist.github.com/emmaodia/3809d0fd3e7d07ffb86b9a4fdf8cd84c with a detailed example.

**Comment by DomenicJahn** [comment]
This doesn't work. When using a regular `Text` from `react-native`, the font will load. Importing `Text` from `@ui-kitten/components` and applying a style to it that makes use of that font, the app will crash:

	fontFamily "my-font-regular" is not a system font and has not been loaded through Font.loadAsync.

	- If you intended to use a system font, make sure you typed the name correctly and that it is supported by your device operating system.

	- If this is a custom font, be sure to load it with Font.loadAsync.
	at node_modules\react-native\Libraries\LogBox\LogBox.js:149:8 in registerError
	at node_modules\react-native\Libraries\LogBox\LogBox.js:60:8 in errorImpl
	at node_modules\react-native\Libraries\LogBox\LogBox.js:34:4 in console.error
	at node_modules\expo\build\environment\react-native-logs.fx.js:27:4 in error
	at node_modules\expo-font\build\Font.js:27:16 in processFontFamily
	at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:3707:14 in diffProperties
	at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:3579:37 in addNestedProperty
	at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:3718:40 in diffProperties
	at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:4039:28 in createInstance
	at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:15182:39 in completeWork
	at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18602:27 in completeUnitOfWork
	at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18574:22 in performUnitOfWork
	at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18499:21 in workLoopSync
	at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18464:18 in renderRootSync
	at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18158:31 in performSyncWorkOnRoot
	at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5911:33 in runWithPriority$argument_1
	at node_modules\scheduler\cjs\scheduler.development.js:468:23 in unstable_runWithPriority
	at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5906:23 in flushSyncCallbackQueueImpl
	at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5893:28 in flushSyncCallbackQueue
	at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:17745:30 in scheduleUpdateOnFiber
	at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:11332:25 in dispatchAction
	at App.tsx:23:67 in AppLoading.props.onFinish
	at node_modules\expo-app-loading\build\AppLoading.js:38:12 in startLoadingAppResourcesAsync
	at node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
	at node_modules\regenerator-runtime\runtime.js:294:29 in invoke
	at node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
	at node_modules\regenerator-runtime\runtime.js:155:27 in invoke
	at node_modules\regenerator-runtime\runtime.js:165:18 in PromiseImpl.resolve.then$argument_0
	at node_modules\react-native\node_modules\promise\setimmediate\core.js:37:13 in tryCallOne
	at node_modules\react-native\node_modules\promise\setimmediate\core.js:123:24 in setImmediate$argument_0
	at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:123:14 in _callTimer
	at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:177:14 in _callImmediatesPass
	at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:437:30 in callImmediates
	at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:388:6 in __callImmediates
	at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:132:6 in __guard$argument_0
	at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:365:10 in __guard
	at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:131:4 in flushedQueue

**Comment by ricjohn-acosta** [comment]
> This doesn't work within a monorepo-setup. When using a regular `Text` from `react-native`, the font will load. Importing `Text` from `@ui-kitten/components` and applying a style to it that makes use of that font will crash the app:
> 
> ```
> fontFamily "my-font-regular" is not a system font and has not been loaded through Font.loadAsync.
> 
> - If you intended to use a system font, make sure you typed the name correctly and that it is supported by your device operating system.
> 
> - If this is a custom font, be sure to load it with Font.loadAsync.
> at node_modules\react-native\Libraries\LogBox\LogBox.js:149:8 in registerError
> at node_modules\react-native\Libraries\LogBox\LogBox.js:60:8 in errorImpl
> at node_modules\react-native\Libraries\LogBox\LogBox.js:34:4 in console.error
> at node_modules\expo\build\environment\react-native-logs.fx.js:27:4 in error
> at node_modules\expo-font\build\Font.js:27:16 in processFontFamily
> at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:3707:14 in diffProperties
> at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:3579:37 in addNestedProperty
> at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:3718:40 in diffProperties
> at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:4039:28 in createInstance
> at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:15182:39 in completeWork
> at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18602:27 in completeUnitOfWork
> at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18574:22 in performUnitOfWork
> at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18499:21 in workLoopSync
> at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18464:18 in renderRootSync
> at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18158:31 in performSyncWorkOnRoot
> at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5911:33 in runWithPriority$argument_1
> at node_modules\scheduler\cjs\scheduler.development.js:468:23 in unstable_runWithPriority
> at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5906:23 in flushSyncCallbackQueueImpl
> at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5893:28 in flushSyncCallbackQueue
> at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:17745:30 in scheduleUpdateOnFiber
> at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:11332:25 in dispatchAction
> at App.tsx:23:67 in AppLoading.props.onFinish
> at node_modules\expo-app-loading\build\AppLoading.js:38:12 in startLoadingAppResourcesAsync
> at node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
> at node_modules\regenerator-runtime\runtime.js:294:29 in invoke
> at node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
> at node_modules\regenerator-runtime\runtime.js:155:27 in invoke
> at node_modules\regenerator-runtime\runtime.js:165:18 in PromiseImpl.resolve.then$argument_0
> at node_modules\react-native\node_modules\promise\setimmediate\core.js:37:13 in tryCallOne
> at node_modules\react-native\node_modules\promise\setimmediate\core.js:123:24 in setImmediate$argument_0
> at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:123:14 in _callTimer
> at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:177:14 in _callImmediatesPass
> at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:437:30 in callImmediates
> at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:388:6 in __callImmediates
> at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:132:6 in __guard$argument_0
> at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:365:10 in __guard
> at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:131:4 in flushedQueue
> ```

Can confirm I have this error too. Anyone got any suggestions?
