### ISSUE TITLE
popover based components(autocomplete,calendar) not working with React native navigation

### ISSUE THREAD

**Issue by SreevatsaAcharya** [akveo/react-native-ui-kitten#1312]
## 💬 Question

Project setup with React native navigation and ui kitten.

I have a form that has varied components like select and autocomplete which work fine right now.
I introduced a new component that requires me to open a modal or a new screen to select values.

The observation is that if i move to a new screen >> close it and come back to continue fill rest of the data in the form all components having a popover like select , autocomplete , color-picker stop working.

If the component is called in a bottom tab based view the popover opens in alternative tabs and the screen freezes. Kinda weird. 

Any suggestions?

## UI Kitten and Eva version
| @eva-design/eva      |  2.0.0      |
| @ui-kitten/components   |    5.0.0     |

| React native navigation | 6.11.0 |

**Comment by artyorsh** [comment]
Duplicates https://github.com/akveo/react-native-ui-kitten/issues/1312
