### ISSUE TITLE
component `select` bug

### ISSUE THREAD

**Issue by mofengfs** [akveo/react-native-ui-kitten#1315]
## 🐛 Bug Report

`ERROR
Warning: Each child in a list should have a unique "key" prop.`
![image](https://user-images.githubusercontent.com/16655229/102735297-fb890a00-437c-11eb-8b8e-1addb6e52701.png)

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    ^2.0.0    |
| @ui-kitten/components   |    ^5.0.0     |

**Comment by artyorsh** [comment]
You should do what the error says. Use `key` whenever you iterate through an array to render React components.
