### ISSUE TITLE
Datepicker end at 31/12/2020

### ISSUE THREAD

**Issue by IsabelPizarro** [akveo/react-native-ui-kitten#1318]
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |        |
| @ui-kitten/components   |         |

## Environment information

```bash

```

**Comment by IsabelPizarro** [comment]
it can be fixed, but you have to add the max atributte

**Comment by artyorsh** [comment]
Duplicates https://github.com/akveo/react-native-ui-kitten/issues/1067
