### ISSUE TITLE
ButtonGroup usage example

### ISSUE THREAD

**Issue by jorgegvallejo** [akveo/react-native-ui-kitten#1319]
## 💬 Question

Could anyone please share an example of how to use the button group? I tried using onSelect and onPress and can't get it to work.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   2.0.0     |
| @ui-kitten/components   |    5.0.0     |

**Comment by artyorsh** [comment]
https://akveo.github.io/react-native-ui-kitten/docs/components/button-group
