### ISSUE TITLE
Configure tabBarOptions in Navigator Can't work

### ISSUE THREAD

**Issue by mofengfs** [akveo/react-native-ui-kitten#1320]
## `tabBarOptions` and screen's `options` configuration don't  work at all.

```javascript

<Navigator
    tabBar={props => <TopTabBar {...props} />} 
    tabBarPosition='top'   
    swipeEnabled={true} 
    lazy={true}  
    removeClippedSubviews={true}
   
    initialRouteName='Orders'
    backBehavior='initialRoute' 

    tabBarOptions={{
      activeTintColor: 'tomato', 
      inactiveTintColor: 'gray', 
      showIcon: true, 
      showLabel: false, 
      pressColor: 'green', 
      scrollEnabled: true, 
      tabStyle: {width: 82}, 
      indicatorStyle:{height: 10},
      labelStyle: {color: 'green'},
      iconStyle: {}, 
      style: {backgroundColor: 'green'}, 
      allowFontScaling: true, 
    }}

  >
    <Screen name='Users' component={UsersScreen} options= { { title:'hey hey hey hey ...' } }  />
    <Screen name='Orders' component={OrdersScreen} />
  </Navigator>
```

![image](https://user-images.githubusercontent.com/16655229/103720009-5a00ea00-5005-11eb-9ba9-c7bb5777639e.png)

| software                            | version |
| ----------------------------------- | ------- |
| Android                      |   Genymotion android_9.0
| @react-navigation/native            |  "^5.8.10"
| @react-navigation/material-top-tabs |  "^5.3.10"
| react-native-tab-view               | "^2.15.2"
| react-native                        | "40.0.1"
| expo                                | "~40.0.0"
| node                                | 14.15.1
| yarn                         | 1.22.10

**Comment by artyorsh** [comment]
Hi @mofengfs. BottomNavigation component doesn't react itself on a props passed through the navigation.
The framework doesn't know anything about the stack used in your application.

On the other hand, I've [posted an answer](https://github.com/akveo/react-native-ui-kitten/issues/1333#issuecomment-766731791) showing how you can control TabBar visibility by passing any params to the Navigator. Consider using that as a reference or a generic idea of how you can make it work.
