### ISSUE TITLE
Theme Context for Class Components

### ISSUE THREAD

**Issue by joeljerushan** [akveo/react-native-ui-kitten#1321]
## 💬 Question
Is it possible to have a code example UI Kitten Theme Context for Class Components ? i'am new to UI Kitten.

**Comment by artyorsh** [comment]
In class components you may need to use `withStyles` HOC to use theme.
https://akveo.github.io/react-native-ui-kitten/docs/components/using-theme/overview

Please check this guide for details:
https://akveo.github.io/react-native-ui-kitten/docs/design-system/use-theme-variables

**Comment by imdkbj** [comment]
U can wrap class into fn to use hooks

```
import { useTheme } from '@ui-kitten/components';

class XYZ extends Component {
    constructor(props) {
        super(props);
        this.state = {
        };
    }

    render() {
        const { theme } = this.props;
        return (
            <>
            </>
        )
    }
}

export default function (props) {
    const theme = useTheme();
    return <XYZ {...props} theme={theme} />;
}
```
