### ISSUE TITLE
changing animation of indicator in tab bars

### ISSUE THREAD

**Issue by ronasuti** [akveo/react-native-ui-kitten#1322]
## 💬 Question

So I've been trying out UI Kitten for an app idea I've wanted to implement.
I tried Ionic before, but otherwise I'm not exactly a frontend wiz, my primary skill set is firmly backend (To be honest, I don't really understand CSS, and I'm dreading having to which is why I use these UI frameworks).
That being said, there's nothing in the documentation about how to go about changing the animation of the indicator bar.
To what degree can I change the animation, shape, etc. of the Indicator bar?

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |       2.0.0 |
| @ui-kitten/components   |         5.0.0|

**Comment by bataevvlad** [comment]
@ronasuti 

The Indicator component accepts several props that allow you to customize its style. Here are some of the props you can use:

animationType: Specifies the animation type for the indicator. The available options are 'slide' (default), 'scale', and 'none'. You can choose the desired animation type that suits your UI requirements.

style: Allows you to apply custom styles to the indicator container. You can modify properties such as backgroundColor, borderRadius, height, and width to change the shape and appearance of the indicator.

selectedStyle: Provides custom styles specifically for the selected indicator. This allows you to differentiate the selected indicator from the rest.

selectedIndex: Specifies the index of the selected item in the indicator. This helps the Indicator component determine the active position of the indicator bar.

By using these props and customizing their values, you can achieve some level of customization for the indicator bar animation and appearance in UI Kitten.

However, please note that UI Kitten is a predefined UI framework, and its customization options might have some limitations compared to building custom UI components from scratch. If you have specific and complex customization requirements beyond what the framework offers, you may need to explore other alternatives or consider building your own custom solution.

I recommend referring to the UI Kitten documentation and exploring the available props and styling options for the Indicator component to see how you can customize it further based on your specific needs.
