### ISSUE TITLE
Badge Component 

### ISSUE THREAD

**Issue by MirFahad58** [akveo/react-native-ui-kitten#1324]
## 🚀 Feature Proposal

Badge normally appears in proximity to notifications or user avatars with eye-catching appeal, typically displaying unread messages count.
I want a badge in UI kitten, It can be used for showing some number indicating some status for like an online-offline status

## Motivation

I was creating an app using UI kitten I missed that component a lot but now I want to add the component by my self and/or with the help of someone from you guys thanks!

## Example

Badges are small status descriptors for UI elements. A badge consists of a small circle, typically containing a number or other short set of characters, that appears in proximity to another object.
Badge normally appears in proximity to notifications or user avatars with eye-catching appeal, typically displaying unread messages count.

**Comment by MirFahad58** [comment]
just like [https://ant.design/components/badge/](url)

**Comment by artyorsh** [comment]
Duplicates #865
