### ISSUE TITLE
Not able to change listItem background color on touch 

### ISSUE THREAD

**Issue by Lekhrajk** [akveo/react-native-ui-kitten#1325]
## UI Kitten and Eva version

    | version - 5.0.0 |

| @eva-design/eva      |        |
| @ui-kitten/components   |         |

I am using List and ListItem i want to change the backgroundColor of Listitem on touch 
how to do this ? any suggestion?

**Comment by artyorsh** [comment]
There is no `activeColor` or something like this in any component in this library. And will never be because it's design-system driven. Please check [this guide](https://akveo.github.io/react-native-ui-kitten/docs/design-system/customize-mapping) to understand the way you can achieve that.
