### ISSUE TITLE
Using third party icons on their own

### ISSUE THREAD

**Issue by Nexey** [akveo/react-native-ui-kitten#1326]
## 💬 Question
I've followed the basic tutorial for registering both eva icons and third party icon packs (material and feather), and I'd like to use icons on their own rather than only using them in the accessoryLeft of a button for instance.
Here's how I want to use them:
![image](https://user-images.githubusercontent.com/1363147/104132868-485e7000-5380-11eb-8b8c-5cc04e14c85d.png)

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2.0.0    |
| @ui-kitten/components   |     5.0.0    |

**Comment by artyorsh** [comment]
You may need to pass `width` and `height` then, since there is no predefined styles

**Comment by Nexey** [comment]
> 
> 
> You may need to pass `width` and `height` then, since there is no predefined styles

Thank you for your suggestion! Unfortunately this doesn't seem to change anything, I still have the same error.
![image](https://user-images.githubusercontent.com/1363147/104226530-3d6f1280-5448-11eb-972c-16d9efe4ea5c.png)

Here's a look at how my class "FeatherIconPack" is made (it should be identical to the one from UI Kitten's tutorial)
<details>
<summary>FeatherIconPack.js</summary>
![image](https://user-images.githubusercontent.com/1363147/104226672-7c9d6380-5448-11eb-8ee7-e2f63fbec4ff.png)
</details>

**Comment by Nexey** [comment]
> 
> 
> You may need to pass `width` and `height` then, since there is no predefined styles

I did some more digging. This worked;
<Icon style={{ width: 32, height: 32 }} fill='#3366FF' name='star' pack="feather"/>

I realized the function was looking for a style prop, so I just added height and width this way. Thank you for your help!
