### ISSUE TITLE
Understanding suggested performance improvements

### ISSUE THREAD

**Issue by eyalyoli** [akveo/react-native-ui-kitten#1327]
## 💬 Question
Hello,
I've read the guide describing how to [improve the performance](https://akveo.github.io/react-native-ui-kitten/docs/guides/improving-performance#improving-performance) of the UI.
I didn't fully understand when it is needed.

Currently, I have an application with custom theming and fonts as described in [branding](https://akveo.github.io/react-native-ui-kitten/docs/guides/branding#text-and-icons). I don't have any [custom mapping](https://akveo.github.io/react-native-ui-kitten/docs/design-system/customize-mapping#customize-component-mapping) for the components.

Will the described metro config gives me better performance? Is theme/font mapping == custom mapping?
Should I apply the improvements when I don't feel that my app is performing badly (maybe I don't feel it because I'm running it on a high-end device)?

Thank you

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2    |
| @ui-kitten/components   |     5    |

**Comment by artyorsh** [comment]
Hey! 👋 

What is the target platform of your application? Is it Web or Mobile?

> Will the described metro config gives me better performance?

Yes. In case it's a mobile application.

> Is theme/font mapping == custom mapping?

No, it's not the same. 

> Should I apply the improvements when I don't feel that my app is performing badly

This guide only helps to avoid ~1-2sec application start delay.

You might be interested in [this thread](https://github.com/akveo/react-native-ui-kitten/issues/1057) to know the details.

**Comment by eyalyoli** [comment]
Thank you very much!
It is a mobile app (with future plans for web).
The guide is not detailed enough. What I understand from your answer:
1. Relevant only for mobile?
2. Theme/font mapping != custom mapping
3. This improves only app startup performance - didn't understand that way
4. Are there any side effects? What I understood from the thread - bigger app size?

I've read the linked thread a couple of times to try to understand it thoroughly. What happens is that the metro bundler compiles the base style with the custom mapping and generates a new mapping for the app to start with (this mapping is the `generated.json` file that they talked about as big) instead of doing so on every app startup.

**Comment by artyorsh** [comment]
> with future plans for web

I would highly recommend reading the thread posted above then :)

> Relevant only for mobil?

Yes. Running a mapping processing task when Metro Bundler starts or reloads is what it does.

> This improves only app startup performance - didn't understand that way

As already mentioned, it will process Eva JSON mappings during the build time and cache it inside `generated.json` for the future use instead of doing the same during the runtime and keeping styles in memory.

> bigger app size?

Yes. But it doesn't affect UX at all. It's better to have 3mb larger bundle than performance issues IMO. Compared to the web, the mobile bundle will be downloaded once - when the user installs it from a delivery channel.

**Comment by eyalyoli** [comment]
Okay, then I don't really need it now since I don't have any custom mappings. But when I need it I should, follow thread's instructions.
I didn't understand the first bullet:
> Make sure you don't have ui-kitten bootstrap script called

**Comment by artyorsh** [comment]
Even if you don't use custom mappings I would suggest using Improving Performance guide to process Eva mappings during the build time and reduce the application start time as a result.

It seems you don't have any scripts if you don't understand it :)
