### ISSUE TITLE
Can not position the Modal component

### ISSUE THREAD

**Issue by ardenercelik** [akveo/react-native-ui-kitten#1329]
## 💬 Question
Hi, 
I can not set the position of the Modal component provided by this library. I tried styling the actual component, styling the parent View component. I want to position it on the bottom of the screen but it refuses to stay any other position than center.
I can only move it to the bottom by setting the height:"105% but than I can't use the onBackdropPress method.
I really appreciate your help. 

PS:
Thank you for the package !

This the code:
```javascript
  <Modal
      backdropStyle={{alignItems: 'flex-start'}}
      visible={props.visible}
      style={{
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        marginTop: 'auto',
      }}
      onBackdropPress={props.toggle}
      backdropStyle={{backgroundColor: 'black'}}>
      <MyComponent toggle={props.toggle} />
    </Modal>
```
This the look i want:
![1](https://user-images.githubusercontent.com/58525494/104440696-b8007500-55a3-11eb-99a9-392cba72f84f.png)

this the parent view component:
```javascript
  <View
        style={{
          
          backgroundColor: 'pink',
        }}>
        <MyModalComponent
          visible={modelvisible}
          toggle={() => setMVisible(!modelvisible)}
        />
      </View>
```
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |      ^2.0.0  |
| @ui-kitten/components   |    5.0.0"     |

**Comment by SuhilMohammad-rogers** [comment]
you can set position to absolute and then give it a top or bottom number as needed

style={{width: '100%', position: 'absolute', top: 50}}

**Comment by MaximilianDietel03** [comment]
> you can set position to absolute and then give it a top or bottom number as needed
> 
> style={{width: '100%', position: 'absolute', top: 50}}

I tried this out and it doesnt seem to work as the position of all top, bottom,right and left is in the center of the screen

**Comment by SuhilMohammad-rogers** [comment]
> > you can set position to absolute and then give it a top or bottom number as needed
> > style={{width: '100%', position: 'absolute', top: 50}}
> 
> I tried this out and it doesnt seem to work as the position of all top, bottom,right and left is in the center of the screen

it worked fine for me:

<Modal
      style={{
        width: '100%',
        position: 'absolute',
        top: 0.1,
      }}
      visible={isShown}
      backdropStyle={styles.backdrop}
      onBackdropPress={onCloseIconPress}>
{'...your child items'}
</Modal>

**Comment by Kernael** [comment]
`top` seems to work properly, but `bottom` does not. As a replacement for `bottom: 0`, one could use `top: 70%, height: '30%'` for example

**Comment by bataevvlad** [comment]
Looks like we fix this issue in new version of UIKitten, please check it, and let us know in this ticket by reopening, if issue still there!

**Comment by lunacer** [comment]
@bataevvlad 
The issue still exists: the top, left, and right work fine but the bottom doesn't work.
