### ISSUE TITLE
Please add support to RN 0.56

### ISSUE THREAD

**Issue by jamesalways** [akveo/react-native-ui-kitten#134]
Hello! I've seen you have already fixed this issue:

```
A,
B,
C, <-- Wrong

A,
B,
C <-- Right
```

Please, can you release a new version with this fix?

Thanks!

**Comment by artyorsh** [comment]
Hi @jamesalways,
Thanks for report.
This change is already available in master branch and will be released in future.
You can refer to [this](https://github.com/akveo/react-native-ui-kitten/issues/133) or [this](https://github.com/akveo/react-native-ui-kitten/issues/127) issue.
