### ISSUE TITLE
scrollToTop and PopToTop when using BottomNavigation component

### ISSUE THREAD

**Issue by minashawky** [akveo/react-native-ui-kitten#1342]
## 💬 Question

How can I achieve the same "tabPress" experience in React Navigation 5 Bottom Tabs, using UI Kitten's BottomNavigation
https://reactnavigation.org/docs/bottom-tab-navigator#tabpress

The main issue I have is when I use BottomNavigation tabBar and tap on the same tab multiple times I don't get the "popToTop" and "scrollToTop" experience that I get when I remove it.

## UI Kitten and Eva version

| Package      | Version |
| @ui-kitten/components | ^5.0.0 |
| @ui-kitten/eva-icons | ^5.0.0 |
| @eva-design/eva      | ^2.0.0 |
| @react-navigation/native  | ^5.8.10 |
| @react-navigation/stack | ^5.12.8 |
| @react-navigation/bottom-tabs | ^5.11.2 |

**Comment by bencreynolds** [comment]
You can achieve .popToTop() behavior by changing the onSelect prop in the docs to:

```
<BottomNavigation
        selectedIndex={state.index}
        onSelect={index => index === state.index ? navigation.popToTop() : navigation.navigate(state.routeNames[index])}
>
```
