### ISSUE TITLE
create a table with ui kitten 

### ISSUE THREAD

**Issue by ZiedNcir** [akveo/react-native-ui-kitten#1343]
## 💬 Question

how can i create a table of element with basic components  of ui kitten because  i don’t  have  a component  table

**Comment by artyorsh** [comment]
It mostly depends on your needs. The table component is basically something abstract to me, so I would advice picking it from somewhere else like [react-native-table-component](https://github.com/Gil2015/react-native-table-component) to build a simple grid and modify it's styles in Eva way by [using theme](https://akveo.github.io/react-native-ui-kitten/docs/design-system/use-theme-variables) or following [this guide](https://akveo.github.io/react-native-ui-kitten/docs/design-system/custom-component-mapping).

[See how it's built](https://akveo.github.io/nebular/docs/components/tree-grid) with Eva for web purposes.
