### ISSUE TITLE
IconRegistry does not render children components, only renders white space

### ISSUE THREAD

**Issue by minhnbwork97** [akveo/react-native-ui-kitten#1347]
## To Reproduce

I install icon packages as the following guide: https://akveo.github.io/react-native-ui-kitten/docs/guides/icon-packages#icon-packages

I wrap my ApplicationProvider in IconRegistry, it does register the icon package but it makes all the components inside of it disappear. I tried wrapping my Button in IconRegistry, the button disappeared, I mean whatever you wrap it in, it disappears.

I delete IconRegistry, the icon package is still registered and all the components in side of it reappear. It works for now but the next time when I restart my project I have to wrap all my components in IconRegistry and then delete IconRegistry. 

## Expected behavior

I expect IconRegistry to render all the children components.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   2.0.0     |
| @ui-kitten/components   |    5.0.0     |

## Environment information

```  System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Core(TM) i3-9100F CPU @ 3.60GHz
  Binaries:
    Node: 15.0.1 - C:\Program Files\nodejs\node.EXE
    npm: 7.0.3 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    Visual Studio: 16.8.30711.63 (Visual Studio Community 2019)
  npmPackages:
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
```

**Comment by artyorsh** [comment]
There is no need to wrap the `ApplicationProvider` into the `IconRegistry`, consider the structure below as mentioned in the guide.

```
export default () => (
  <>
    <IconRegistry icons={EvaIconsPack} />
    <ApplicationProvider {...eva} theme={eva.light}>
      <HomeScreen />
    </ApplicationProvider>
  </>
);
```
