### ISSUE TITLE
SyntaxError: A trailing comma is not permitted after the rest element

### ISSUE THREAD

**Issue by brunoosilva** [akveo/react-native-ui-kitten#135]
### Issue type

**I'm submitting a bug in build, look the picture** 

* [X] bug report
* [ ] feature request

### Issue description

**Current behavior:**
When run `yarn start or npm run start` or `react-native run-ios`

**Expected behavior:**
The worked without bug

![image](https://user-images.githubusercontent.com/3465257/44241990-a2ea4680-a19d-11e8-8879-b42f228fc5b6.png)

### Other information:

**OS, device, package version**
```
OS: MacOS
Device: iPhone 6s and Android J5
Package Version: 3.0.1
```

**Comment by artyorsh** [comment]
Hi @arshidkv12,
Thanks for report.
This is occurred because of your project RN version.
You can refer to [this issue](https://github.com/akveo/react-native-ui-kitten/issues/129#issuecomment-408483828)
