### ISSUE TITLE
Navigation example with dark theme flashes when navigating

### ISSUE THREAD

**Issue by batjko** [akveo/react-native-ui-kitten#1354]
## 💬 Question

After setting up exactly the example for using React Navigation, I find that navigation has this blip, where the screen briefly flashes white between screens, before turning back to the expected dark-themed colors.

Is this expected in dark mode and perhaps a limitation of the kitten/navigation setup at the moment?

Edit: Here is a gif that shows it:
![](https://i.imgur.com/EBWWnXV.gif])

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2.0.0    |
| @ui-kitten/components   |    5.0.0     |

**Comment by artyorsh** [comment]
👋  there,
Starting from Navigation v5, you should also configure navigation theming. It wraps the entire screen with it's own root view.
See `background` property from [there](https://reactnavigation.org/docs/themes/).

**Comment by batjko** [comment]
Ah I see.
Ok thanks, I'll see how I can apply the Kitten theme's colors to the navigation elements.
Thanks.
