### ISSUE TITLE
Help with Rendering List Component 

### ISSUE THREAD

**Issue by Pickausername2017** [akveo/react-native-ui-kitten#1357]
## 💬 Question
I am working on my first ever React Native App, using Kitten UI.  

I am trying to use the list component to render a list that includes the title, and user ID from a data file.  Similar to the list rendered in the example for Lists Accessories.  When I render the list I am only seeing the title, icon, and button.  The user ID does not render.   
I'd like to discuss this someone who has a little more time.  
## UI Kitten  and Eva version 

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    '^5.0.0"    |
| @ui-kitten/components   |  "^2.0.0"       |

**Comment by artyorsh** [comment]
Hi @Pickausername2017 

Try looking through some of examples [here](https://reactnative.dev/docs/flatlist) or [here](https://akveo.github.io/react-native-ui-kitten/docs/components/list/overview#listitem).

If it's your first React Native project, I would recommend mastering some basic knowledge [here](https://www.reactnative.guide/index.html)
