### ISSUE TITLE
Getting typescript warning

### ISSUE THREAD

**Issue by Rc85** [akveo/react-native-ui-kitten#1358]
## 🐛 Bug Report

Getting a red squiggly under `eva[theme]` on

`<ApplicationProvider {...eva} theme={{ ...eva[theme], ...myTheme }}>`

```
Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'typeof import("f:/Projects/my_takeouts_app/node_modules/@eva-design/eva/index")'.
  No index signature with a parameter of type 'string' was found on type 'typeof import("f:/Projects/my_takeouts_app/node_modules/@eva-design/eva/index")'.
```

## To Reproduce

Follow this guide

https://akveo.github.io/react-native-ui-kitten/docs/guides/runtime-theming#register-theme

## Expected behavior

No warning

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   2.0.0     |
| @ui-kitten/components   |   5.0.0      |

## Environment information

VSCode
Windows 10 Pro

**Comment by artyorsh** [comment]
👋  there!
What is a `theme` in your code? Anyways, if you're trying to use it as an `eva` object key, make sure to tell TS it is `light` or `dark`.

```
type ThemeKey = 'light' | 'dark';
const theme: ThemeKey = 'light';
```

**Comment by binajmen** [comment]
```js
<ApplicationProvider {...eva} theme={{ ...eva[theme as "light" | "dark"], ...myTheme }}>
```
Will also work ;)
