### ISSUE TITLE
Multiple custom mappings

### ISSUE THREAD

**Issue by schiller-manuel** [akveo/react-native-ui-kitten#1359]
## 💬 Question
How can I have multiple custom mappings and change them during runtime?
For example, imagine I have two themes (theme1, theme2) that differ in both color and font family.
The font family can only be modified via custom mapping, so when changing from theme1 to theme2 I need to select the appropriate custom mapping. 
I use the metro config as described in the [docs](https://akveo.github.io/react-native-ui-kitten/docs/guides/improving-performance#metro-bundler), but it only allows a single custom mapping
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   2.0.0     |
| @ui-kitten/components   |  5.0.0       |

**Comment by artyorsh** [comment]
Hi @schiller-manuel 👋 
There is no way to change mapping during the app runtime unfortunately.
As a possible workaround, I'd suggest defining font styles as new variables in theme, giving them the same name in theme1 and theme2. After that, you should also rely on those variables with UI Kitten Text component by [customizing mapping](https://akveo.github.io/react-native-ui-kitten/docs/design-system/customize-mapping). That will do the trick.

**Comment by farazirfan47** [comment]
Thanks @artyorsh that did the trick!
