### ISSUE TITLE
How to change the color of radio button?

### ISSUE THREAD

**Issue by DarkPonyBee** [akveo/react-native-ui-kitten#1362]
## 💬  I want to change the color of radio button in ui-kitten. I am using default theme but it renders blue radio button.
How can I change the color of radio button? Is there color prop in this component?

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   2.0.0     |
| @ui-kitten/components   |   5.0.0      |

**Comment by artyorsh** [comment]
Because in default theme the primary color is blue.

https://akveo.github.io/react-native-ui-kitten/docs/guides/branding
