### ISSUE TITLE
Do you have a plan to update Kitten Tricks app with 5.0.0 version?

### ISSUE THREAD

**Issue by ardegirmencioglu** [akveo/react-native-ui-kitten#1364]
Hello,

We are facing some styling problem with 5.0.0 version. We would like to check the problem is existing on Kitten Tricks app but the app is not up to date. Do you have a plan to update it?

Thanks

**Comment by malashkevich** [comment]
@ardegirmencioglu please take a look at the [Kitten Tricks](https://github.com/akveo/kittenTricks) repository.
It's already updated to v5.
