### ISSUE TITLE
background: 'transparent' for a specific navbar screen

### ISSUE THREAD

**Issue by web75018** [akveo/react-native-ui-kitten#137]
hi akveo,

I tray to make the background: 'transparent' for a specific navbar screen.
But headerStyle: {backgroundColor: 'rgba(255, 255, 255, 0.4)'} don't works.

static navigationOptions = ({ navigation }) => {
return {
title: 'Explore'.toUpperCase(),
headerStyle: {
backgroundColor: 'rgba(255, 255, 255, 0.4)'
}
};
};

the navbar keeps the global background color.

Thank you.

**Comment by artyorsh** [comment]
@web75018 ,

I think this is probably [react-navigation](https://github.com/react-navigation/react-navigation) issue.
You should do some magic with headerStyle, I think:)
Anyway, thanks for report
