### ISSUE TITLE
Passing props into Modal's children

### ISSUE THREAD

**Issue by doliolarzz** [akveo/react-native-ui-kitten#1380]
## 💬 Question
Hi, using this code:
```
const { children, visible } = props;

<Modal visible={visible}>
  {children}
</Modal>
```

There's a warning when passing children props into Modal's children as below:
```Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.```

Is there any workaround to use pass them into the children of the modal properly? It has to be done.

Thanks for this useful library!

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   2.0.0     |
| @ui-kitten/components   |    5.0.0     |

**Comment by SaidTorres3** [comment]
How did you resolve that?

**Comment by doliolarzz** [comment]
I accidentally have the children's state outside the modal. So, it gave that warning. Please refer to this [#1094 (comment)](https://github.com/akveo/react-native-ui-kitten/issues/1172#issuecomment-657436828)
