### ISSUE TITLE
Not able to remove border from Input field

### ISSUE THREAD

**Issue by Lekhrajk** [akveo/react-native-ui-kitten#1384]
## UI Kitten and Eva version

 | Version |
     5..0.0
 | ----------- |
| @ui-kitten/components   |     Input    |

I was trying to remove border from top , left and right from input field but I am unable to do it
I just want border bottom of input field I tried to give borderLeftColor and borderRightColor as transparent but nothing works any solution or suggestions ?

**Comment by whitestranger7** [comment]
Hi, @Lekhrajk. Thanks for noticing the bug. It was fixed with #1351, now feel free to use `border` style properties on `Input`, it would work fine. Regarding your case, you can just follow the code example below:
```js
<Input {...props} style={{borderWidth: 0, backgroundColor: 'transparent', borderBottomWidth: 1, borderRadius: 0}} />
```
