### ISSUE TITLE
Select Items cover the select button

### ISSUE THREAD

**Issue by mjcarnaje** [akveo/react-native-ui-kitten#1388]
`<!--` Love UI Kitten? Please leave feedback: 👉  https://github.com/akveo/react-native-ui-kitten/issues/657 -->

## 🐛 Bug Report

I made a custom component to match the design of the application and when i click the select button it looks like this.

![image](https://user-images.githubusercontent.com/65398905/112707812-11ace600-8ee9-11eb-9ad6-c1f0d59d51eb.png)

It covers the button.

## Expected behavior

![image](https://user-images.githubusercontent.com/65398905/112707798-efb36380-8ee8-11eb-8337-b09f9fb1d928.png)

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   ^2.0.0     |
| @ui-kitten/components   |   ^5.0.0      |

## Environment information

```bash

```

**Comment by artyorsh** [comment]
See https://github.com/akveo/react-native-ui-kitten/issues/743
