### ISSUE TITLE
Syntax error in rkModalImg.js

### ISSUE THREAD

**Issue by merteroglu01** [akveo/react-native-ui-kitten#139]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [X] bug report
* [ ] feature request

### Issue description

**Current behavior:**
While installing app to emulator packager says syntax error.

**Expected behavior:**
No syntax error

**Steps to reproduce:**

**Related code:**
`error: bundling failed: SyntaxError: /Users/XXX/Documents/projects/XXX/react/node_modules/react-native-ui-kitten/src/components/image/rkModalImg.js: A trailing comma is not permitted after the rest element (277:17)

  275 |       index,
  276 |       style: imgStyle,
> 277 |       ...imgProps,
      |                  ^
  278 |     } = this.props;
  279 | 
  280 |     let {
    at _class.raise (/Users/XXX/Documents/projects/XXX/react/node_modules/@babel/core/node_modules/babylon/lib/index.js:776:15)
`
### Other information:

Android emulator API 27 Nexus 5
if i delete comma that came after imgProps it works

**Comment by artyorsh** [comment]
Hi @merteroglu01,
Please refer to [this](https://github.com/akveo/react-native-ui-kitten/issues/127) issue.
