### ISSUE TITLE
calendar customize

### ISSUE THREAD

**Issue by amrshadid** [akveo/react-native-ui-kitten#1391]
## 💬 Question
How make this ui using kitten calendar 
  
![calender1](https://user-images.githubusercontent.com/32217515/112769525-41afd280-902a-11eb-9174-3e592364d16d.png)
Expanding the field
![calender2](https://user-images.githubusercontent.com/32217515/112769532-4aa0a400-902a-11eb-9e7c-0451ec471f22.png)

any idea to implement this ui using react native kitten calendar?

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      | 2.0.0 |
| @ui-kitten/components   |  5.0.0 |

**Comment by artyorsh** [comment]
:wave: there!
Basically what you need to do is to [customize theme](https://akveo.github.io/react-native-ui-kitten/docs/guides/branding) and render custom day cell by implementing `renderDay`.  
Take a look at the "Calendar Custom Day" example in the [doc](https://akveo.github.io/react-native-ui-kitten/docs/components/calendar).

**Comment by amrshadid** [comment]
Expand the calendar, minimize it? How is this possible?
@artyorsh

**Comment by danya0365** [comment]
@artyorsh I already check in docs but no custom render cell example code
