### ISSUE TITLE
Divider: Add middle text

### ISSUE THREAD

**Issue by ricardopacheco** [akveo/react-native-ui-kitten#1393]
## 🚀 Feature Proposal

Any UI framework which offers Divider components, gives the option to add text or icon.

## Example

Some like this with more options: https://github.com/samuelcust/react-native-component-separator, https://flutter-examples.com/create-horizontal-divider-line/

**Comment by artyorsh** [comment]
I'd say it's architecturally wrong and doesn't worth potentially brought complexities. At the same time, the requested change is as easy as the following: 
```jsx
const TextDivider = ({ text }) => (
  <View style={{ flexDirection: 'row', alignItems: 'center' }}>
    <Divider style={{ flex: 1 }} />
    <Text style={{ marginHorizontal: 16 }}>{text}</Text>
    <Divider style={{ flex: 1 }} />
  </View>
);
```
