### ISSUE TITLE
UI kitten 5.0 autocomplete

### ISSUE THREAD

**Issue by ricardopacheco** [akveo/react-native-ui-kitten#1398]
In the example of the official documentation, the http request is always triggered when the component is mounted. 

My question is simple: How to trigger the request ONLY when the query (text) parameter has a value (something like query.length> 0).

Autocomplete in some cases does not come with "default values" as in the example.

**Comment by north8side** [comment]
Again someone messing with it not me look at the info and send me a copy

Powered by Cricket Wireless
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Ricardo Pacheco ***@***.***>
Sent: Wednesday, April 7, 2021 6:03:32 PM
To: akveo/react-native-ui-kitten ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [akveo/react-native-ui-kitten] UI kitten 5.0 autocomplete (#1398)


In the example of the official documentation, the http request is always triggered when the component is assembled.

My question is simple: How to trigger the request ONLY when the query (text) parameter has a value (something like query.length> 0).

Autocomplete in some cases does not come with "default values" as in the example.

**Comment by flexbox** [comment]
@ricardopacheco 
Maybe you can use the `onfocus` on your `<Autocomplete>` component

https://reactnative.dev/docs/next/textinput#onfocus

I think this kind of question should live on StackOverflow. It's not a bug in the library, it's an implementation on your project.
 
If your problem is solved feel free to close the issue 😉

**Comment by ricardopacheco** [comment]
@flexbox I understand, and, i agree.

But, i understand too which copy/paste for a example in official docs should be work, but, not, in this case.

**Comment by ricardopacheco** [comment]
@flexbox I can fixed with #1117.

**Comment by north8side** [comment]
The information taken as well as software need back from my development and the internal review
Thanx

Powered by Cricket Wireless
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
