### ISSUE TITLE
Most UI elements re-render even with no props changed

### ISSUE THREAD

**Issue by farcaller** [akveo/react-native-ui-kitten#1400]
## 🐛 Bug Report

It seems that the `TopNavigationAction` (at least) will always re-render because its `eva` prop changes:
![image](https://user-images.githubusercontent.com/693/114185297-7f233280-993d-11eb-9652-f67f962e0bfb.png)
![image](https://user-images.githubusercontent.com/693/114186168-6ff0b480-993e-11eb-97b1-e0ded6bd5f3c.png)

I'm looking at `src/components/theme/style/styled.tsx:133` and I'm not sure how it's supposed to work. To me it seems that `withEvaProp` will always re-eval a new `eva` as the object is constructed every time, thus the prop will be different (although equal by value). I can't find any verification down the stack that `eva` is compared by value. Thus every component that's using `@styled` must re-render no matter what if the parent render triggers.

## To Reproduce

The default example for the TopNavigationAction and WDYR/react profiler is enough to see the issue.

## Expected behavior

TopNavigationAction should not re-render unless it has to.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |     2.0.0   |
| @ui-kitten/components   |   5.0.0      |

## Environment information

This is a react-native-web project but I don't think web vs native matters in this context.

**Comment by farcaller** [comment]
After further experimenting it seems this is an issue with the style injector and it affects pretty much all the components apart from the lucky few (3) that have the `shouldComponentUpdate` defined.

**Comment by AntonBorovoi** [comment]
As @farcaller already mentioned it happens because of recreating Eva object each time
``` 
return {
        ...props,
        eva: {
          theme,
          style,
          dispatch: this.onDispatch,
        },
      }
```

It seems there is a need to add Eva object memoization to `styled() HOC`.
Another thing is that most of the components don't implement `PureComponent` or `shouldComponentUpdate` and will be re-rendered right after its parent. 
To prevent this I guess we may use `PureComponent` on `styled() HOC` by changing class definition
```
  class Wrapper extends React.PureComponent<PrivateRefProps, State> {
```
