### ISSUE TITLE
Vertical Button Group

### ISSUE THREAD

**Issue by Gondolav** [akveo/react-native-ui-kitten#1403]
## 💬 Question

Hello, is it possible to build a button group with vertical orientation at the moment? Thank you!

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |       2.0.0 |
| @ui-kitten/components   |        5.0.0 |

**Comment by artyorsh** [comment]
Hey. It's not possible. I mean, you may try passing somewhat like `flexDirection: 'column'` to make it vertical, but then threr might be some issues with button borders.
