### ISSUE TITLE
Error when use hooks inside Calendar renderDay

### ISSUE THREAD

**Issue by jiehan1029** [akveo/react-native-ui-kitten#1404]
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |  2.0.0      |
| @ui-kitten/components   |  5.0.0       |

I'm trying to customize calendar cell by showing how many logs are saved in that day. All logs info are saved in redux store, and here is my code:
```
import { Calendar, StyleType, Text } from '@ui-kitten/components'
import { StyleSheet, View } from 'react-native'
import { selectCurrentTaskKey, selectTaskLogs } from '../../redux/selectors/task'
import { switchDate, useAppDispatch, useAppSelector } from '../../redux'
import React, { useEffect } from 'react'

const DayCell = (info: { date: Date }, style: StyleType):React.ReactElement => {
	const { date } = info
	const dateTS = date.getTime()
	const currTaskKey = useAppSelector((state) => selectCurrentTaskKey(state))
	const logs = useAppSelector((state) => selectTaskLogs(state,currTaskKey,dateTS))
	return (
		<View
			style={[styles.dayContainer, style.container]}>
			<Text style={style.text}>{`${date.getDate()}`}</Text>
			<Text style={[style.text, styles.value]}>
				{`${logs.length}`}
			</Text>
		</View>
	)
}

const LogCalendar: React.FC = () => {
	const [date, setDate] = React.useState(new Date())
	const onSelectDate = (nextDate:Date) => {
		setDate(nextDate)
	}

	const dispatch = useAppDispatch()
	useEffect(() => {
		dispatch(switchDate(date.getTime()))
	}, [date])

	return (
		<Calendar
			date={date}
			onSelect={onSelectDate}
			renderDay={DayCell}
		/>
	)
}
```

However, it fails at line `const currTaskKey = useAppSelector((state) => selectCurrentTaskKey(state))` with such error message:
```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
```
Both my `react` and `react-dom` are 16.13.1 so 1) doesn't apply. 
Could someone give me an hint what's the proper way to use hooks inside `renderDay`?

**Comment by whitestranger7** [comment]
Hey, @jiehan1029. Currently we're extending classes functionality under the hood of kitten implementation, so it's obvious that you can't call call hooks inside children component. The only thing you could apply - pure `JSX | TSX`

In other case - you could define selector logic inside parent, extract state and pass pure function into DayCell component as a prop, then call it inside and get values you want to use.

In nearly future, we're planning to update major component into functional components in order to support hooks functionality.

**Comment by yasirrafiq786** [comment]
Hey @whitestranger7 , sorry for asking it here but could you be able to give an example of how to pass some additional data into renderDay?
