### ISSUE TITLE
 A trailing comma is not permitted after the rest element

### ISSUE THREAD

**Issue by usfslk** [akveo/react-native-ui-kitten#141]
### Issue type

**I'm submitting a**

* [x ] bug report
* [ ] feature request

### Issue description

**Current behavior:**  JS Bundle do not compile because of syntax error

**Steps to reproduce:** Install ui-kitten 3 or 3.1 and import it in your app

**Related code:**

```
  render() {
    let {
      imgContainerStyle,
      visible,
      animationType,
      transparent,
      modalStyle,
      modalImgStyle,
      headerStyle,
      footerStyle,
      source,
      index,
      style: imgStyle,
      ...imgProps,
    } = this.props;```

### Other information:
There's also same error at line 277
```

> error: bundling failed: SyntaxError: C:\Users\bs37\AwesomeProject\node_modules\react-native-ui-kitten\src\components\image\rkModalImg.js: A trailing comma is not permitted after the rest element (296:17)

**Comment by artyorsh** [comment]
Closing due to #127 and #129 duplication
