### ISSUE TITLE
Using @ui-kitten/metro-config will build but send no "exit" command to CI/CD so it runs endlessly

### ISSUE THREAD

**Issue by sajadghawami** [akveo/react-native-ui-kitten#1410]
## 🐛 Bug Report

After implementing the "Improving Performance Guide" everything works like before without a problem. So a `expo build:ios --no-wait` or `expo build:android --no-wait` will finish *without* a problem. 
The only problem is that the CLI will now *not* get a `exit` response, which will result in endless-loading if you use it in your CI/CD environment. If you remove the `@ui-kitten/metro-config` the build, it will exit accordingly in the CI/CD environment.

## To Reproduce

Follow this guide:
https://akveo.github.io/react-native-ui-kitten/docs/guides/improving-performance#metro-bundler

## Expected behavior

Exit when the local build finished.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva | 2.0.0 |
| @ui-kitten/components | 5.0.0 |
| @ui-kitten/metro-config | 5.0.0 |

**Comment by RWOverdijk** [comment]
I checked out the code and I think that [this happens when you have a custom mapping](https://github.com/akveo/react-native-ui-kitten/blob/master/src/metro-config/index.ts#L60-L64).

The best way to resolve that would be to only watch when in watch mode.

**Comment by sajadghawami** [comment]
thanks for the reply!

is that something i could fix on my side?

**Comment by brkastner** [comment]
@sajadghawami I was able to work around this by setting an env var `CI=true` in my CI/CD that's used to bypass `@ui-kitten/metro-config` integration in favor of manually bootstrapping the custom mapping before publish.

metro.config.js:
```js
const MetroConfig = require('@ui-kitten/metro-config');
const {getDefaultConfig} = require('expo/metro-config');

const config = getDefaultConfig(__dirname);
config.resolver.sourceExts.push('cjs');

const evaConfig = {
  evaPackage: '@eva-design/eva',
  customMappingPath: path.resolve(__dirname, 'src/theme/mapping.json')
}

module.exports = process.env.CI === "true" ? config : MetroConfig.create(evaConfig, config);
```

CI/CD publish step:
```bash
#!/usr/bin/env bash
yarn ui-kitten bootstrap @eva-design/eva $CUSTOM_MAPPING_PATH
yarn expo publish ...
```

**Comment by brkastner** [comment]
Once the pull request is approved, `yarn ui-kitten bootstrap @eva-design/eva $CUSTOM_MAPPING_PATH` shouldn't be necessary and `metro.config.js` can be rewritten as:

```js
const path = require('path');
const MetroConfig = require('@ui-kitten/metro-config');
const {getDefaultConfig} = require('expo/metro-config');

const config = getDefaultConfig(__dirname);

const evaConfig = {
  evaPackage: '@eva-design/eva',
  customMappingPath: path.resolve(__dirname, 'src/theme/mapping.json')
}

module.exports = MetroConfig.create(evaConfig, config, process.env.CI !== "true");
```
