### ISSUE TITLE
rkModalImg.js: a syntax error in react-native 0.57.0

### ISSUE THREAD

**Issue by youngcao2015** [akveo/react-native-ui-kitten#142]
### Issue type

**I'm submitting a ...**  (check one with "x")
* [x ] bug report

### Issue description

**Current behavior:**
react-native run-ios/android, then follow error appear：
react-native-ui-kitten/src/components/image/rkModalImg.js: A trailing comma is not permitted after the rest element (277:17)

**Related code:**
the file is: rkModalImg.js;
the code is:
```
let {
      imgContainerStyle,
      visible,
      animationType,
      transparent,
      modalStyle,
      modalImgStyle,
      headerStyle,
      footerStyle,
      source,
      index,
      style: imgStyle,
      ...imgProps,
    } = this.props;
```

### Other information:

**OS, device, package version**
```
mac os, iphone/android, "react-native-ui-kitten": "^3.0.1",react-native 0.57.0
```

**Comment by artyorsh** [comment]
Hi @youngcao2015,
We're working on new release, which will contain this fix

Closing due to #129 and #127 duplication.
