### ISSUE TITLE
Custom indicator for BottomNavigation

### ISSUE THREAD

**Issue by ecemac** [akveo/react-native-ui-kitten#1420]
## 💬 Question
Is it possible to create a custom indicator for the active BottomNavigationTab? The default indicator is above the tab icon and I would like it to be below the icon. The only options I see on documentation are "default" and "noIndicator".  Any help is much appreciated!
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2.1.0   |
| @ui-kitten/components   |  5.1.0    |

**Comment by artyorsh** [comment]
:wave:
The only way to do that is to build a custom view and render it below the BottomNavigation with `noIndicator` appearance, handling the selectedIndex changes to animate.
