### ISSUE TITLE
Accessories (Left and Right) how can i make them boolean?

### ISSUE THREAD

**Issue by kkkasio** [akveo/react-native-ui-kitten#1421]
I am using the List component, and in the ListItem, I would like to display the accessoryLeft for one condition!
I did my logic in react, and it was as I wished! However, as ts identifies an ImageProps typing, I have this "error"

Would there be a way to create a condition to have the accessory accessory or not?

code
![1](https://user-images.githubusercontent.com/19254402/116795853-4c88d780-aaae-11eb-9230-d7bfb5b65062.png)

ts error
![2](https://user-images.githubusercontent.com/19254402/116795788-ce2c3580-aaad-11eb-85c1-bf05af1ae92f.png)

Tanks! ><

**Comment by whitestranger7** [comment]
Hey, @kkkasio. I doubt there should be any error with using `null` condition 😀
The things you could do to avoid the issue:

1. make sure that you're using latest typescript version
2. try to mark `renderActiveIcon` as `React.ReactElement` type
3. if you're using confusing 3-rd party library that returns `ImageProps` type on `ViewProps`, you could apply
```ts
<Component {...props as ImageProps} />
```
4. also good option would be to define item interface, so active would have defined type
