### ISSUE TITLE
Bug - Bottom Bar Navigation

### ISSUE THREAD

**Issue by Morritz** [akveo/react-native-ui-kitten#1433]
![](https://i.gyazo.com/21e024296223548372d0f545be54dc32.gif)

## 🐛 Bug Report

The bug is in, bottom tab bar used in conjunction with ui-kitten. BottomBar appears shortly moved by an offset in y-axis (up), and then it moves back to the proper position.
## To Reproduce
It's all in snack or repo.

## Expected behavior
The bottom bar should not flicker on first boot of the app.

## Link to runnable example or repository (highly encouraged)
+ Repo: https://github.com/Morritz/bottomtab_repro_reactnavigation5

+ Snack: https://snack.expo.io/K8N9V2DWG

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2.1.0    |
| @ui-kitten/components   |   5.1.0      |

## Environment information

```bash
  System:
    OS: Windows 10 10.0.16299
    CPU: (4) x64 Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
  Binaries:
    Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 16, 19, 23, 26, 27, 28, 29, 30
      Build Tools: 23.0.1, 25.0.3, 26.0.2, 27.0.3, 28.0.2, 28.0.3, 29.0.2, 30.0.2, 30.0.3
      System Images: android-28 | Intel x86 Atom_64
      Android NDK: 22.0.6917172-beta1
    Windows SDK:
      AllowAllTrustedApps: Enabled
      AllowDevelopmentWithoutDevLicense: Enabled
      Versions: 10.0.17763.0
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    Visual Studio: 16.6.30028.174 (Visual Studio Community 2019)
  npmPackages:
    react: 17.0.1 => 17.0.1
    react-native: 0.64.1 => 0.64.1
```

**Comment by whitestranger7** [comment]
Hey, @Morritz. Unfortunately, the issue is not reproducible on my side. Could you pls describe what action trigger the BottomBar wrong offset animation?

**Comment by Morritz** [comment]
> Hey, @Morritz. Unfortunately, the issue is not reproducible on my side. Could you pls describe what action trigger the BottomBar wrong offset animation?
Basically the problem on expo (and other) appears at first load of the app and it is not connected with any action.
At first I didn't know if this problem was related to ui-kitten library or react-navigation particulary. 
But I wrote my experiences and current workaround I use in this issue 
https://github.com/react-navigation/react-navigation/issues/9623. 
I don't really know what exactly causes it, but it seems to be something related to safe area. It is described in issue above , I downgraded react-native-safe-area-context and issue disappeared on every emulator/device. Before I used ui-kitten example from the website, but I wanted to make it lighter so I ditched custom component and started to use bare tab navigation just with eva icons and around the time of this change i noticed it.

**Comment by artyorsh** [comment]
> downgraded react-native-safe-area-context and issue disappeared

The BottomNavigation component doesn't explicitely rely on the device metrics to provide proper positioning. If the issue still appear, please investigate the issue on the safe-area-related ends.
