### ISSUE TITLE
Calendar Custom Day Rendering not updating consistently

### ISSUE THREAD

**Issue by adamf59** [akveo/react-native-ui-kitten#1446]
## 💬 Question

Hey there! So I'm attempting to implement the UI Kitten calendar, and I'm running into issues in terms of rendering custom days (using `renderDay`). The expected behavior is that, when a month (i.e. June) is selected, the `renderDay` function is called  for every day in June. The same should be true of other months, i.e. moving from June to July should call `renderDay` for all days in July.

With this not working, I implemented `onVisibleDateChange`, referenced from #1256. The whole Calendar component can be seen below:

```js
<Calendar
  date={calSelectedDate}
  renderDay={EventCalendarDay}
  boundingMonth={false}
  min={calendarSelectableMinDate}
  max={calendarSelectableMaxDate}
  onVisibleDateChange={(D) => {
    console.log("visible date change to min" + D);
    setCalendarSelectableMinDate(D);
    console.log("max " + new Date(D.getTime() + (31 * 24 * 60 * 60 * 1000)));
    setCalendarSelectableMaxDate(
      new Date(D.getTime() + 31 * 24 * 60 * 60 * 1000)
    );
  }}
  onSelect={(nextDate) => {
    setCalSelectedDate(nextDate);
  
  }}
  style={{ flex: 1 }}
  getItemLayout={(data, index) => ({ length: 145, offset: 145 * index, index })}
/>;

``` 
Here is the `renderDay` function:
```js
const EventCalendarDay = ({ date }, style) => (
        <View
            style={[styles.dayContainer, style.container]}>
            <Text style={[style.tinyText, {
                fontWeight: "600",
                marginTop: 4,
                color: "whitesmoke"
            }]}>{`${date.getDate()}`}</Text>

            <Text>
                <CalendarDayIcon today={date}/>
            </Text>

        </View>
    );
```
And the `CalendarDayIcon` component:
```js
const CalendarDayIcon = (props) => {
        const [eventOnDay , setEventOnDay] = useState(false);
        useEffect(() => {
            console.log("Render: " + props.today)
            setEventOnDay(checkEventOnDay(props.today));
        }, []);
        return (
            <>
                {eventOnDay ? <>
                    {props.today.getTime() < todayAsDate.getTime() ? <>
                        <Icon {...props} style={[props.style, {height: 16, width: 16, padding: 3, marginTop: 3}]} opacity={0.30} fill={theme['color-danger-400']} name='radio-button-on'/>
                    </> : <>
                        <Icon {...props} style={[props.style, {height: 16, width: 16, padding: 3, marginTop: 3}]} fill={theme['color-danger-400']} name='radio-button-on'/>
                    </>}
                </> : <></>}
            </>
        );
    };
```
You'll notice the `checkEventOnDay` function call in the `useEffect` of the `CalendarDayIcon`. While I cannot release this function's code, assume it returns a boolean on whether there is an event on `props.today`.
But more importantly, you'll see the `console.log`, which gets called each time a calendar day is rendered.

When the calendar is first rendered, it works as expected, outputting:
```txt
 LOG  Render: Tue Jun 01 2021 00:00:00 GMT-0400 (EDT)
 LOG  Render: Wed Jun 02 2021 00:00:00 GMT-0400 (EDT)
 LOG  Render: Thu Jun 03 2021 00:00:00 GMT-0400 (EDT)
  ...
 LOG  Render: Tue Jun 29 2021 00:00:00 GMT-0400 (EDT)
 LOG  Render: Wed Jun 30 2021 00:00:00 GMT-0400 (EDT)
```

Switching to another month, in this case July, gives the following output:
```txt
 LOG  visible date change to minThu Jul 01 2021 00:00:00 GMT-0400 (EDT)
 LOG  max Sun Aug 01 2021 00:00:00 GMT-0400 (EDT)
 LOG  Render: Thu Jul 29 2021 00:00:00 GMT-0400 (EDT)
 LOG  Render: Fri Jul 30 2021 00:00:00 GMT-0400 (EDT)
 LOG  Render: Sat Jul 31 2021 00:00:00 GMT-0400 (EDT)
```

But sometimes, gives:
```txt
 LOG  visible date change to minThu Jul 01 2021 00:00:00 GMT-0400 (EDT)
 LOG  max Sun Aug 01 2021 00:00:00 GMT-0400 (EDT)
 LOG  Render: Thu Jul 29 2021 00:00:00 GMT-0400 (EDT)
 LOG  Render: Fri Jul 30 2021 00:00:00 GMT-0400 (EDT)
 LOG  Render: Sat Jul 31 2021 00:00:00 GMT-0400 (EDT)
 LOG  Render: Sat Jul 03 2021 00:00:00 GMT-0400 (EDT)
 LOG  Render: Sun Jul 04 2021 00:00:00 GMT-0400 (EDT)
 LOG  Render: Mon Jul 05 2021 00:00:00 GMT-0400 (EDT)
 LOG  Render: Tue Jul 06 2021 00:00:00 GMT-0400 (EDT)
 ...
 LOG  Render: Sat Jul 24 2021 00:00:00 GMT-0400 (EDT)
 LOG  Render: Sun Jul 25 2021 00:00:00 GMT-0400 (EDT)
 LOG  Render: Mon Jul 26 2021 00:00:00 GMT-0400 (EDT)
 LOG  Render: Tue Jul 27 2021 00:00:00 GMT-0400 (EDT)
 LOG  Render: Wed Jul 28 2021 00:00:00 GMT-0400 (EDT)
 LOG  Render: Thu Jul 29 2021 00:00:00 GMT-0400 (EDT)
 LOG  Render: Fri Jul 30 2021 00:00:00 GMT-0400 (EDT)
 LOG  Render: Sat Jul 31 2021 00:00:00 GMT-0400 (EDT)
```

So, just inconsistent re-render behavior that results in some days having "ghost events," which disappear from the `renderDay` when the day is rendered due to being selected on the calendar.

I understand that there are some performance limitations involved with the calendar currently. I'm just trying to understand why the calendar behaves like this, and if there is any fix I could look at. 

Any help is greatly appreciated! 

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2.0.0    |
| @ui-kitten/components   |    5.1.0     |

**Comment by adamf59** [comment]
I'm mainly confused as to why the render is skipping days, i.e.
```txt
 ...
 LOG  Render: Sat Jul 31 2021 00:00:00 GMT-0400 (EDT)
 LOG  Render: Sat Jul 03 2021 00:00:00 GMT-0400 (EDT)
 ...
```
and rendering days later in the month early twice:
```txt
LOG  Render: Thu Jul 29 2021 00:00:00 GMT-0400 (EDT)
LOG  Render: Fri Jul 30 2021 00:00:00 GMT-0400 (EDT)
LOG  Render: Sat Jul 31 2021 00:00:00 GMT-0400 (EDT)
...
LOG  Render: Thu Jul 29 2021 00:00:00 GMT-0400 (EDT)
LOG  Render: Fri Jul 30 2021 00:00:00 GMT-0400 (EDT)
LOG  Render: Sat Jul 31 2021 00:00:00 GMT-0400 (EDT)
```

It almost works out if I auto-select the first day of the month in the `onVisibleDateChange` prop. But, we're still skipping the second of the month.

**Comment by whitestranger7** [comment]
Hey, @adamf59. The reason of such behaviour is in your `useEffect` usage. Please, remove dependency array in order to call event with every update.
```js
useEffect(() => {
  console.log("Render: " + props.today)
  setEventOnDay(checkEventOnDay(props.today));
});
```

But I really dont recommend you to use such realisation in your case, it may cause performance problems. Consider please to create `today` prop realisation inside parent and pass processed prop into `CalendarDayIcon` component
