### ISSUE TITLE
react-native-mobx useStores not working when Element is in Modal 

### ISSUE THREAD

**Issue by scottzhang** [akveo/react-native-ui-kitten#1450]
I wrote an element named "TextInputAuto", code like following:

export interface TextInputAutoProps extends ViewProps{
    title:string;
    placeholderText: string;
    value:string;
    setValue:any;
    model:string;
    showOnly:Boolean;
    valid?:boolean;
    messages?:string;
}
export const TextInputAuto = (props?: TextInputAutoProps): React.ReactElement => {
  const { placeholderText, value, setValue, model, showOnly, style, valid, messages } = props

  const { utilStore } = useStores()
  console.log("get store", utilStore)
  const [data, setData] = useState([])

  const onSelect = (index) => {
    setValue(data[index]);
  };

Please note I want to use useStores to get mobx-store. This works fine in normal screen or elements. Untils after I put TextInputAuto in Modal. The useStores return undefined.

code like :
 <Modal visible={true} style={{width:'100%'}} backdropStyle={{backgroundColor: 'rgba(0, 0, 0, 0.5)'}}> 
<TextInputAuto />
</Model>

I can't tell difference why when put code in Modal the call failed. 
Please help. Thanks.

**Comment by artyorsh** [comment]
👋 
Could you please share a code of how is the ApplicationProvider / MobX Provider are structured in the entry point of the app?
