### ISSUE TITLE
UI Kitten components throw errors while unit tests 

### ISSUE THREAD

**Issue by l30ni3** [akveo/react-native-ui-kitten#1455]
## 🐛 Bug Report

I am getting the following error on all ui kitten components when doing unit tests with Jest. 

List: unsupported configuration.
      Using UI Kitten components is only possible with configuring ApplicationProvider.
      📖 Documentation: https://akveo.github.io/react-native-ui-kitten/docs/guides/getting-started#manual-installation
      
In case you have all in place, there might be an incorrect usage of a "styled" function.
      📖 Documentation: https://akveo.github.io/react-native-ui-kitten/docs/design-system/custom-component-mapping
      
Of course I configured the ApplicationProvider and I do not have any custom component mapping. I also followed previous instructions on other issues to  configure the jest config to ignore all 3rd party modules, but I still do not seem to get this to work. 

My jest configuration in package.json (I tried a lot with transformIgnorePatterns already, nothing worked)

```
"jest": {
    "preset": "react-native",
    "transformIgnorePatterns": [
      "node_modules/@ui-kitten"
    ]
  }
```

HomeScreen.js

```
import React, {useState, useEffect} from 'react';
import {
  Avatar,
  Button,
  Icon,
  Divider,
  Layout,
  List,
  ListItem,
  Text,
  TopNavigation,
  TopNavigationAction,
} from '@ui-kitten/components';
import {SafeAreaView} from 'react-native';
import {useIsFocused} from '@react-navigation/native';
import Moment from 'react-moment';
const GLOBAL = require('./components/constants');

export const HomeScreen = props => {
  const navigation = props.navigation;
  const [data, setData] = useState([]);
  const MenuIcon = props => <Icon {...props} name="menu-outline" />;

  const isFocused = useIsFocused();

  const MenuAction = () => (
   ...
  );

  const renderAvatar = props => (
    ...
  );

  const renderItemAccessory = props => (
    ...
  );

  const renderItem = ({item, index}) => (
   ...
  );

  useEffect(() => {
   ...
  }, []);

  return (
    <SafeAreaView style={{flex: 1}}>
      <TopNavigation
        title="Meine Messungen"
        alignment="center"
        accessoryLeft={MenuAction}
      />
      <Divider />
      <Layout
        style={{
          flex: 1,
        }}>
        <List data={data} renderItem={renderItem} />
        <Button
          style={{
            margin: 30,
          }}
          onPress={() => navigation.navigate('Tutorial 1')}>
          Neue Messung starten
        </Button>
      </Layout>
    </SafeAreaView>
  );
};
```

HomeScreen-test.js

```
/**
 * @format
 */

import 'react-native';
import React from 'react';
import {HomeScreen} from '../screens/HomeScreen';

// Note: test renderer must be required after react-native.
import renderer from 'react-test-renderer';
jest.mock('@react-navigation/native');

it('renders correctly', () => {
  const tree = renderer.create(<HomeScreen />).toJSON();
  expect(tree).toMatchSnapshot();
});
```

## To Reproduce

create react native app
npm test with given screen and testscreen above

## Expected behavior

Either jest properly ignores uikitten somehow, or even better: i can also do unit tests with uikitten components with jest, without getting the error above.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    "^2.1.0"    |
| @ui-kitten/components   |    "^5.1.0"     |

## Environment information

```
System:
    OS: macOS 10.15.7
 
npmPackages:
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 

```

**Comment by artyorsh** [comment]
> Of course I configured the ApplicationProvider 

By following the example code, the `renderer.create` doesn't render an ApplicationProvider

**Comment by l30ni3** [comment]
thanks @artyorsh! for others that might have problems with it - importing ApplicationProvider and IconRegistry to test file and wrap the test component with it worked for me:

```
/**
 * @format
 */

import 'react-native';
import React from 'react';
import {HomeScreen} from '../screens/HomeScreen';
import * as eva from '@eva-design/eva';
import {EvaIconsPack} from '@ui-kitten/eva-icons';
import {ApplicationProvider, IconRegistry} from '@ui-kitten/components';

// Note: test renderer must be required after react-native.
import renderer from 'react-test-renderer';
jest.mock('@react-navigation/native');

it('renders correctly', () => {
  const tree = renderer
    .create(
      <>
        <IconRegistry icons={EvaIconsPack} />
        <ApplicationProvider {...eva} theme={eva.light}>
          <HomeScreen />
        </ApplicationProvider>
      </>,
    )
    .toJSON();
  expect(tree).toMatchSnapshot();
});
```
