### ISSUE TITLE
What is the difference between Menu and List?

### ISSUE THREAD

**Issue by ramuta** [akveo/react-native-ui-kitten#1459]
I'd like to better understand the difference between List and Menu and their pros/cons. On the surface they look the same, but I'm sure there's much more beneath.

For example, if I have a larger dynamic list, which one should I use? Are there any performance or rendering differences between the two?

**Comment by whitestranger7** [comment]
Hi, @ramuta. Both `Menu` and `List` used `FlatList` from inside, so it doesn't really matter which one to use in terms of performance, they both fits if you're willing to render large amount of data.. The decision which one to use depends on case.
Let me explain you =)

[List](https://github.com/akveo/react-native-ui-kitten/blob/83c75b0ab7a654f264e92724506163f355dd4fc6/src/components/ui/list/list.component.tsx#L91) component represents `FlatList` with predefined styles & methods inside. Its recommended to use it with `ListItem` render component, but you can render whatever you want to. Consider to use this one if you're want to display large dynamic list.

[Menu](https://github.com/akveo/react-native-ui-kitten/blob/83c75b0ab7a654f264e92724506163f355dd4fc6/src/components/ui/menu/menu.component.tsx#L161) represents `List` realisation from beneath, but it also could use nested items at a glance, [so each group item can be accessed by group render element](https://github.com/akveo/react-native-ui-kitten/blob/83c75b0ab7a654f264e92724506163f355dd4fc6/src/components/ui/menu/menu.component.tsx#L155).

I recommend to use `Menu` component when it's really represents menu bar (items could be selected and nested). And with help of `MenuGroup` & `MenuItem` components you can create an awesome menu bar =)

You could also take a look at [docs](https://akveo.github.io/react-native-ui-kitten/docs/components/components-overview), there's really good examples of usage

**Comment by ramuta** [comment]
Oh, they are both FlatList, I didn't know that - thanks for your explanation and links! 🙂
