### ISSUE TITLE
Is it possible to change the theme at the component level?

### ISSUE THREAD

**Issue by nyoung697** [akveo/react-native-ui-kitten#1461]
I am using the Eva Dark theme, which looks great!  I have a bottom sheet that pops up and I want that to be white.  If I use any of the UI Kitten components on my bottom sheet, they are expecting a dark background, so they don't appear nice.  I am wondering if I can easily wrap the bottom sheet content and tell all the ui kitten children components to render as if they are the light theme (without actually changing the entire context to be the light theme)??

Thank you!

**Comment by artyorsh** [comment]
Hey :wave:
It is! Thank you for the question - it helped me to realize we don't have it documented. See [the code](https://github.com/akveo/react-native-ui-kitten/blob/master/src/showcases/components/showcaseThemingIFrame.component.tsx#L30)
