### ISSUE TITLE
Popover style prop

### ISSUE THREAD

**Issue by johnkmzhou** [akveo/react-native-ui-kitten#1465]
## 🚀 Feature Proposal

Implement a popover style prop for components like OverflowMenu, Datepicker, Autocomplete, Select.

## Motivation

There's been an ongoing issue with the popover covering the input in cases where the Android Status Bar is translucent (the default behavior in Expo). #743 The last attempt to fix the issue didn't actually fix the issue #1372 so I believe this is most practical and flexible approach to handling it.

## Example

```
<Select popoverStyle={{marginTop: 20}}></Select>
```

**Comment by artyorsh** [comment]
As mentioned multiple times before, the hacky marginTop style is never needed if the StatusBar and it's offset is handled properly.

**Comment by johnkmzhou** [comment]
Currently resolving this issue with a workaround from https://github.com/akveo/react-native-ui-kitten/issues/1245#issuecomment-809852228.
```
  const mapping = {
    components: {
      Popover: {
        meta: { parameters: { top: { type: 'number' } } },
        appearances: {
          default: {
            mapping: { top: insets.top },
          },
        },
      },
    },
  };
  
  return (
    <ApplicationProvider
      customMapping={Platform.OS === 'android' ? mapping : null}
    >
    </ApplicationProvider>
  );
```

**Comment by Codelica** [comment]
> As mentioned multiple times before, the hacky marginTop style is never needed if the StatusBar and it's offset is handled properly.

Given all the closed issues regarding this position with translucent Android statusbar, I'm curious what the "proper handling" really is?   Doing a conditional custom mapping like above doesn't "feel right" but what other option is there?
