### ISSUE TITLE
Ref missing on Modal

### ISSUE THREAD

**Issue by imdkbj** [akveo/react-native-ui-kitten#1467]
## To Reproduce

Assign ref to the modal and access it ,the object is undefined.

## Expected behavior
It should have modal ref object.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      | 2.1.0    |
| @ui-kitten/components   |  5.1.0     |

**Comment by artyorsh** [comment]
:wave:
Could you please share the example code?

**Comment by imdkbj** [comment]
I was trying it to access since last few hr and was not able to get and at surprise it's working, Sorry for the same.
