### ISSUE TITLE
Can not reach out 4.x version on website

### ISSUE THREAD

**Issue by zahidinho** [akveo/react-native-ui-kitten#1476]
## 💬 Question

 I still use UI-Kitten version 4x. I can not reach out 4x docs on website. Will it be back?

**Comment by ACamiruaga** [comment]
Same issue.

**Comment by whitestranger7** [comment]
Hey, @zahidinho. Thanks for noticing the issue. We've republished our docs and now old version woks as well.

Here's direct link for ya => https://akveo.github.io/react-native-ui-kitten/docs/4.x/
