### ISSUE TITLE
How to use UI Kitten Icons outside of a buttons accessory prop

### ISSUE THREAD

**Issue by OmarKhattab** [akveo/react-native-ui-kitten#1477]
## 💬 Question

I am trying to use <Icon name="arrow-left" /> but the icon does not appear on the UI.

But when I add icon as accessoryLeft on a button it appears.

```
const ArrowLeft = (props) => <Icon {...props} name="arrow-left" />;

const HeaderBack = () => {
  const navigation = useNavigation();
  return (
    <Layout style={NativeHeaderStyles.HeaderLeftWrapper}>
      <Button
        status="ghost"
        accessoryLeft={ArrowLeft}
        style={{}}
        onPress={() => navigation.goBack()}
        appearance="ghost"
      ></Button>
    </Layout>
  );
};
```

How can I use icons without attaching it to a button?

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |     2.1.0   |
| @ui-kitten/components   |     5.1.0    |

**Comment by artyorsh** [comment]
Hey :wave:
It works because of the props implicitely applied by spreading the `props` argument passed to it. Basically, there nothing special but the size of the icon and it's color. 
```tsx
<Icon name='arrow-left' style={{ width: 24, height: 24, tintColor: 'black' }} />
```
