### ISSUE TITLE
How to use ui kitten with any mask library

### ISSUE THREAD

**Issue by crisfcodes** [akveo/react-native-ui-kitten#1479]
## 💬 Question

How to use ui kitten with any mask library?

What I want is to use UI Kitten input component with any react native input mask like [
react-native-text-input-mask](https://github.com/react-native-text-input-mask/react-native-text-input-mask) or [react-native-masked-text](https://github.com/benhurott/react-native-masked-text) but this kind of libraries comes with its own inputs components, so how to use it with ui kitten components?

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    ^2.1.0    |
| @ui-kitten/components   |    ^5.1.0     |

**Comment by artyorsh** [comment]
As far as I can see from the input-mask code base there is no way to do that, since the library itself relies on custom Input component built with native modules.
