### ISSUE TITLE
how to use ui kitten layouts that are showing on the Kitten Tricks App

### ISSUE THREAD

**Issue by aianshume** [akveo/react-native-ui-kitten#1480]
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |        |
| @ui-kitten/components   |         |

we i not install the package right now, just reading the docs from the website i found that the layouts that define on the app, i want to use these layouts. 

i searched all over the docs and find nothing

i want to use

![Screenshot_2021-07-17_21-40-31](https://user-images.githubusercontent.com/68537640/126043172-143c921f-2669-4900-9568-958517f4d9d3.png)

**Comment by malashkevich** [comment]
Helli @aianshume,
To reuse layouts from kitten tricks you can just go to the source code, copy and paste it.
It should be pretty straightforward.
Let me know if you have some issues with it.
