### ISSUE TITLE
Live view not working in Documentation - 404 error

### ISSUE THREAD

**Issue by daryllukas** [akveo/react-native-ui-kitten#1486]
## 🐛 Bug Report
The live view in docs doesn't seem to be working at the moment. I'm seeing a not found response in Dev tools. See attachment.

![404-ui-kitten](https://user-images.githubusercontent.com/1014489/126432449-248b6e55-3bd2-4c27-bc9e-82726e73bb3a.png)

**Comment by AntonBorovoi** [comment]
Hi @daryllukas 
Thanks for raising this!

It is back to normal after redeploy
