### ISSUE TITLE
Typescript error on component usage when define a custom param on mapping.json

### ISSUE THREAD

**Issue by iabadie-dataart** [akveo/react-native-ui-kitten#1492]
## 💬 Question
Hi! I'm new on Kitten and in my project we are trying to add a custom property to the Text Component.
So I do it on the mapping.json file inside of the variantGroups (and inside the meta) and all is working well but as I have Typescript on the project I'm getting an error when I pass my custom property to the Text component.

For example:
declaration (and in meta too with default true)
![image](https://user-images.githubusercontent.com/85507388/127054984-5cbdb875-112a-4d7c-918f-faad70874f6d.png)

usage
![image](https://user-images.githubusercontent.com/85507388/127055154-9ffa35c1-799d-4ce3-979f-88960fe751a0.png)

I don't know how to do for Typescript recognize my Text component custom property

Checking on the Text type definition inside node module I realize that there is not supporting different params options 

## UI Kitten and Eva version

| Package                             | Version     |
| ------------------------- | -----------|
| @eva-design/eva              |    2.0.0      |
| @ui-kitten/components    |   5.0.0       |

**Comment by malashkevich** [comment]
@iabadie-dataart I guess the only way to get this work is to create your own component. At the moment its not possible to add the new properties in existing types. We will think about this.
