### ISSUE TITLE
Increasing the font size of buttons and inputs

### ISSUE THREAD

**Issue by squareborg** [akveo/react-native-ui-kitten#1495]
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2.1.1    |
| @ui-kitten/components   |    5.1.1     |

Hey, I'm having trouble increasing the font size of buttons and inputs. 

How do I achieve this in `mapping.json`

I tried 

```
{
    "strict": { 
        "components": {
            "Button": {
              "meta": {},
              "appearances": {
                  "outline": {
                    "mapping": {
                        "textFontFamily": "text-font-family",
                        "iconMarginHorizontal": 4
                      },
                    "variantGroups" : {
                        "size": {
                            "medium":  {
                                "textFontSize": 100
       ...
```

This does not appear to affect the font size. Any help appreciated

**Comment by deepakkumardk** [comment]
@squareborg Did you find any solution for this?

**Comment by squareborg** [comment]
@deepakkumardk 

In the end, I ended up having to add a Text component wrapped in a View to control text size. 

```
<Button
    >
        <View>
            <Text category='h6'>
            </Text>
        </View>
</Button>
```

**Comment by deepakkumardk** [comment]
Thanks, @squareborg but then I need to change this in all files.

@artyorsh Any props that can work for the mapping.json file?

**Comment by squareborg** [comment]
@deepakkumardk Agreed its not ideal, I never figured out the mappings.json, let me know if you figure it out

**Comment by deepakkumardk** [comment]
@squareborg Finally found one, this [json file](https://github.com/eva-design/eva/blob/master/packages/eva/mapping.json#L437) helped me out.

> 
    "Button": {
      "appearances": {
        "filled": {
          "variantGroups": {
            "size": {
              "medium": {
                "textFontSize": 24
              }
            }
          }
        }
      }
    }
