### ISSUE TITLE
Adding margin in each Input component

### ISSUE THREAD

**Issue by kamal-hossain** [akveo/react-native-ui-kitten#1496]
There should be an api for adding margin horizontally or vertically on **Input** elements. I have searched for that  in input [api](https://akveo.github.io/react-native-ui-kitten/docs/components/input/api#input) but didn't found it.

**Comment by artyorsh** [comment]
:wave:

Margins and everything style-related is configurable with a `style` property, available in almost every React Native component. [See the documentation](https://reactnative.dev/docs/view-style-props).

```tsx
<Input style={{ marginHorizontal: 8 }} />
```
