### ISSUE TITLE
App Crashes when an Icon is used inside ListView Item

### ISSUE THREAD

**Issue by kvicera** [akveo/react-native-ui-kitten#1505]
## 💬 Question
Is it not possible to use Icon inside a ListView Item? I have tried and it causes my app to crash without outputting errors.
I have tried using fontawesome and it works as intended.

I have set it up here: https://snack.expo.dev/@vfvicera220/playground
And it also crashes the app if Line 99 is not commented out, regardless how or where the code is defined.

Am I missing something here? Sorry I'm just new to react-native. 
Well, for the mean time I'll go with fontawesome.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
@eva-design/eva | 2.1.1
@fortawesome/fontawesome-svg-core | 1.2.36
@fortawesome/free-brands-svg-icons | 5.15.4
@fortawesome/free-regular-svg-icons | 5.15.4
@fortawesome/free-solid-svg-icons | 5.15.4
@fortawesome/react-native-fontawesome | 0.2.7
@react-navigation/drawer | 5.12.3
@react-navigation/native | 5.9.2
@react-navigation/stack | 5.14.2
@ui-kitten/components | 5.1.1
@ui-kitten/eva-icons | 5.1.1
react | 17.0.2
react-native | 0.65.1
react-native-gesture-handler | 1.7.0
react-native-reanimated | 1.13.2
react-native-safe-area-context | 3.3.0
react-native-screens | 3.5.0
react-native-svg | 12.1.1

PS: If it is relevant, I am using an older version of @react-navigation stuff and did some hacking to get it work since the latest version is producing errors due to dependency stuff.

**Comment by RayVR** [comment]
I don't really understand the problem you had that required sticking the Icon outside the card component. I modified your example to include an Icon in your List and it works fine. 

https://snack.expo.dev/P-F56A_zl

**Comment by kvicera** [comment]
> I don't really understand the problem you had that required sticking the Icon outside the card component. I modified your example to include an Icon in your List and it works fine.
> 
> https://snack.expo.dev/P-F56A_zl

Thanks for the reply! Turns out I'm doing it wrong. I will close this now as I moved on and used another library. Your solution is valid and will be useful for newbies like me who encounters this deadlock.
