### ISSUE TITLE
Kitten UI Network Gallery

### ISSUE THREAD

**Issue by ugurozturk** [akveo/react-native-ui-kitten#151]
* [ ] bug report
* [X] feature request

### Issue description

**Current behavior:**
So there is no way to do it right now. If nobody knows the answer.

https://stackoverflow.com/questions/52525212/kitten-ui-network-gallery

**Comment by artyorsh** [comment]
Hi @ugurozturk ,

Looks like you already have this ability :)
If you look through sources, you should see, that `RkGallery` items are [RkGalleryImage](https://github.com/akveo/react-native-ui-kitten/blob/master/src/components/gallery/rkGalleryImage.js).
When you pass array of items to `RkGallery`, it translates it one-by-one into each RkGalleryImage through the `source` prop. This prop works the same way as it does plain react-native `Image` component.
So you can use it like this:
```
<RkGallery items={[
  {uri: 'https://path-to/my-awesome-pic-0.jpg'},
  {uri: 'https://path-to/my-awesome-pic-0.jpg'},
]} />
```

**Comment by ugurozturk** [comment]
Thank you :)

**Comment by ugurozturk** [comment]
![kittenui](https://user-images.githubusercontent.com/7994408/46262758-5ae57000-c50e-11e8-9dbe-af611efc4741.jpg)

You might want to look into it @artyorsh

**Comment by artyorsh** [comment]
@ugurozturk 
No need in use React components as array items. Just [{ uri: https://... }, ... ]
