### ISSUE TITLE
The Tooltip component doesn't display when rendered within a react-native Modal

### ISSUE THREAD

**Issue by ajstokar** [akveo/react-native-ui-kitten#1513]
## 🐛 Bug Report

The Tooltip component doesn't display when rendered within a react-native Modal

## To Reproduce

Add Tooltip within react-native Modal

## Expected behavior

The tooltip should display as it does otherwise when used outside of a react-native Modal.

## Link to runnable example or repository (highly encouraged)

N/A

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   2.0.0     |
| @ui-kitten/components   |     5.0.0    |

## Environment information

  System:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 16.8.0 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 7.21.0 - /usr/local/bin/npm
    Watchman: 2021.08.23.00 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
  npmGlobalPackages:
    react-native-cli: 2.0.1

```bash
```

**Comment by dVaytul** [comment]
Hello @ajstokar 
Unfortunately, I can only suggest you to use our Modal instead of react-native Modal.
