### ISSUE TITLE
Persist scroll bar in select element

### ISSUE THREAD

**Issue by RenatoSerra22** [akveo/react-native-ui-kitten#1516]
Hello, how can i persist the scrollbar of the select componenet? Where in the ui kitten code could would i have to add `persistentScrollbar` if i were to patch it? cant seem to find it (New to react/typescript)
Several of my users leaving feedback they cant to something that should be possible and i realised its because they are not aware the list within selects is scrollable and there are more options below.
Would really appreciate some help :)

**Comment by malashkevich** [comment]
@RenatoSerra22 @marianocorvatta unfortunately it's difficult to implement on iOS. https://stackoverflow.com/a/51595310
Closing this, because it's not UI KItten issue
