### ISSUE TITLE
Back button Icon with RTL support

### ISSUE THREAD

**Issue by ajakka** [akveo/react-native-ui-kitten#1522]
## 💬 Question
I have an issue when trying to implement RTL where the back icon doesn't flip with the UI.
In [react native blog](https://reactnative.dev/blog/2016/08/19/right-to-left-support-for-react-native-apps), they mentioned flipping the Image using transform property but that didn't work.

This is how it looks right now. The back arrow should be facing the other direction
<img width="295" alt="image" src="https://user-images.githubusercontent.com/25665218/136010156-908a87bd-ef8b-41f7-8b9c-ed4104d01fff.png">

The code for the Top Navigation
```tsx
<TopNavigation
        alignment="center"
        title="الحدث"
        accessoryLeft={
          <TopNavigationAction
            icon={<Icon {...props} name="arrow-back" />}
            onPress={e => navigation.goBack()}
          />
        }
        accessoryRight={
          <TopNavigationAction
            icon={<Icon {...props} name="edit" />}
            onPress={e => setEditMode(!isEditMode)}
          />
        }
      />
```

## UI Kitten and Eva version

| Package                            | Version       |
| ------------------------- | ----------- |
| @eva-design/eva              |5.1.1             |
| @ui-kitten/components    |5.1.1             |

**Comment by malashkevich** [comment]
@ajakka it seems you are not correctly applying the approach described in the blog.
Please try something like this:
```
  const rtlStyle = {transform: [{scaleX: -1}]};
  return (
      <TopNavigation
        alignment="center"
        title="الحدث"
        accessoryLeft={() =>
          <TopNavigationAction
            icon={({style, ...props}) => <Icon {...props} style={[style, rtlStyle]} name="arrow-back"/>}
          />
        }
      />

  );
```
