### ISSUE TITLE
Render a <SelectItem/> from JSON object array

### ISSUE THREAD

**Issue by Applizone** [akveo/react-native-ui-kitten#1532]
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    ^2.1.1    |
| @ui-kitten/components   |    ^5.1.1     |

I have a sample data as below:
`unloadlocation: [{ "id": 1, "location": "RL1" }, { "id": 2, "location": "RL2" }, { "id": 3, "location": "RL3" }, { "id": 4, "location": "RL4" }]`

If I use string of array in for SelectItem, it is not an issue. But it is when I use JSON object. This object will be use when user using the app.

My current script:
```
    const renderUnloadLocationName = React.useCallback(
        (item, index) => <SelectItem title={item.title} key={index} />,
        []
    )
    const renderUnloadLocation = () => (
        <Select
            size='small'
            style={{ width: '100%' }}
            value={displayUnloadLocationName}
            selectedIndex={unloadLocationIndex}
            onSelect={index => setUnloadLocationIndex(index)}>
            {AppData.unloadlocation.map((item) => renderUnloadLocationName(item.location))}
        </Select>
    )
```

But it result in Render Error with 

> Objects are not valid as a React child (found: object with keys {id, location}). If you meant to render a collection of children, use an array instead.

I did try several way to solve the render error but still it showing the same error.

**Comment by Applizone** [comment]
> Hello @Applizone.
> It's actually difficult to understand what exact issue you have.
> Could you please provide fully reproducible example?

Does reproducible example mean by I put my code somewhere like Sandbox/Expo so you could see it in full picture of the problem? If yes, can you suggest one of the site that can run with UI Kitten? Never done one of these.

**Comment by dVaytul** [comment]
Hello @Applizone

Thanks for sharing all the code.

Your issue appears because the value attribute of `<Select />` should be `ReactText | ReactElement | (TextProps) => ReactElement` ( [docs](https://akveo.github.io/react-native-ui-kitten/docs/components/select/api#:~:text=set%20to%20true.-,value,-ReactText%20%7C%20ReactElement%20%7C%20(TextProps)) ).
In your case `displayUnloadLocationName` is an object `{ id, location}` and you need to use only `location` property:

```
// add .location
const displayUnloadLocationName = unloadLocation[unloadLocationIndex.row].location;
```

Also, please, use the following code to avoid warnings:

```
// use title instead of item.title here
(title, index) => <SelectItem title={title} key={index} />,

...
// add item.id as index
{unloadLocation.map((item) => renderUnloadLocationName(item.location, item.id))}
```
