### ISSUE TITLE
How to run on web with expo?

### ISSUE THREAD

**Issue by obayit** [akveo/react-native-ui-kitten#1535]
## 💬 Question
When I try to run my expo project in the web, I get this page:

![screenshot-localhost_19006-2021 10 15-19_13_14](https://user-images.githubusercontent.com/20386024/137526914-bb14d4c3-9e29-4e44-8e9b-db57e2d01d18.png)

Error in text:
```
./node_modules/@ui-kitten/components/ui/input/input.component.js 105:38
Module parse failed: Unexpected token (105:38)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|         this.webEventResponder = devsupport_1.WebEventResponder.create(this);
|         this.focus = () => {
>             this.textInputRef.current?.focus();
|         };
|         this.blur = () => {

```
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    5.1.1    |
| @ui-kitten/components   |    5.1.1     |

**Comment by joleb** [comment]
add `@expo/webpack-config` as dependency and add the following code inside `webpack.config.js`

```
const createExpoWebpackConfigAsync = require('@expo/webpack-config');

module.exports = async function(env, argv) {
    const config = await createExpoWebpackConfigAsync({
        ...env,
        babel: {
            dangerouslyAddModulePathsToTranspile: ['@ui-kitten/components']
        }
    }, argv);
    return config;
};

```

checkout this for more details: https://github.com/akveo/react-native-ui-kitten/issues/996#issuecomment-616115469
