### ISSUE TITLE
Accept react-i18next `TFunctionResult` type

### ISSUE THREAD

**Issue by gabrielmoncea** [akveo/react-native-ui-kitten#1539]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@ui-kitten/components@5.1.1` for the project I'm working on.

I'm using UI Kitten with Typescript and React-i18next. The problem is that the `Text` component doesn't accept the string resulted from the `t()` function because it can return a null or object if the namespace doesn't exist. This patch would fix this issue.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@ui-kitten/components/ui/text/text.component.d.ts b/node_modules/@ui-kitten/components/ui/text/text.component.d.ts
index 9496be9..13035f1 100644
--- a/node_modules/@ui-kitten/components/ui/text/text.component.d.ts
+++ b/node_modules/@ui-kitten/components/ui/text/text.component.d.ts
@@ -3,6 +3,7 @@
  * Copyright Akveo. All Rights Reserved.
  * Licensed under the MIT License. See License.txt in the project root for license information.
  */
+import { TFunctionResult } from 'i18next';
 import React from 'react';
 import { TextProps as RNTextProps } from 'react-native';
 import { EvaStatus, Overwrite, LiteralUnion } from '../../devsupport';
@@ -12,7 +13,7 @@ declare type TextStyledProps = Overwrite<StyledComponentProps, {
 }>;
 declare type ChildElement = React.ReactText | TextElement;
 export interface TextProps extends RNTextProps, TextStyledProps {
-    children?: ChildElement | ChildElement[];
+    children?: ChildElement | ChildElement[] | TFunctionResult;
     category?: LiteralUnion<'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 's1' | 's2' | 'p1' | 'p2' | 'c1' | 'c2' | 'label'>;
     status?: EvaStatus;
 }
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by whitestranger7** [comment]
Hi, @gabrielmoncea! Personally, I don't think it's a good idea to add whole package in order to support type. Type we provide is matchable for `i18next` type. You could just go with:
```ts
<Text>{t<string>('smth')}</Text>
```

**Comment by gabrielmoncea** [comment]
That's a good idea! Thanks!
