### ISSUE TITLE
how to trigger a groupMenu component ?

### ISSUE THREAD

**Issue by Wimmind** [akveo/react-native-ui-kitten#1540]
how to trigger a groupMenu component ? I try through the `ref.current.onPress()` , the event is triggered, but does not expand under the menu, help
```js
  constructor() {
    this.menuItemRef = React.createRef();
  }
  componentDidMount() {
    this.menuItemRef.current.onPress();
  }
...

 <Menu>
<MenuGroup ref={key === selected ? this.menuItemRef : null}>
<MenuItem>
 </MenuItem>
<MenuItem>
 </MenuItem>
</MenuGroup>
</Menu>
```

**Comment by greenfrvr** [comment]
@Wimmind sorry for late response. can you please describe your use case? 
next release we'll deliver new prop for `MenuGroup` component which will allow to make it expanded for initial render. will it match your request?

**Comment by greenfrvr** [comment]
closing the issue for now. update with fix will be delivered in next release
