### ISSUE TITLE
TabView Tab taking height of longest tab

### ISSUE THREAD

**Issue by Davete0302** [akveo/react-native-ui-kitten#1541]
## 🐛 Bug Report

I have a tabview and inside is 4 tabs, on first tab view I have a flatlist with atlest 20 data. When I navigate to other tabs  it seems to be taking the height of the longest list in the tab group (tab 1 in this case)

## Expected behavior
` <TabView
                selectedIndex={selectedIndex}
                onSelect={index => setSelectedIndex(index)}>
                <Tab title={Labels.updates}>
                  <Layout style={styles.tabContainer}>
                    {updates()}
                  </Layout> </Tab>
                <Tab title={Labels.groups}>
                  <Layout style={styles.tabContainer}>
                    {groups()}</Layout>
                </Tab> <Tab title={Labels.projects}>
                  <Layout style={styles.tabContainer}>
                    {projects()}</Layout>
                </Tab>
                <Tab title={Labels.following}>
                  <Layout style={styles.tabContainer}>
                    {following()}</Layout>
                </Tab>
              </TabView>`

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    "^2.1.1"    |
| @ui-kitten/components   |    "^5.1.1"     |

## Environment information

 System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 AMD Ryzen 3 3100 4-Core Processor
  Binaries:
    Node: 12.18.4 - D:\Programs\Node  JS\node.EXE
    npm: 6.14.6 - D:\Programs\Node  JS\npm.CMD
  npmPackages:
    react: 16.13.1 => 16.13.1 
    react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
```bash

```

**Comment by dVaytul** [comment]
Hello @Davete0302 

In TabView implementation we use a custom ViewPager (horizontal ScrollView), which height is determined by the height of the tallest child. So, there is no bug.
But you can try to play around with TabView height by onSelect event.

**Comment by kieuquang1110tt** [comment]
@Davete0302  any way to fix it?

**Comment by malashkevich** [comment]
@kieuquang1110tt I guess you can try to subscribe to `onLayout` event on the active tab content and change the height of `TabView` accordingly

**Comment by huzaifa26** [comment]
@dVaytul that a very bad response to a bug you cannot resolve. How can you ship a component with this scroll issue.
