### ISSUE TITLE
Unable to select year on date picker

### ISSUE THREAD

**Issue by OmarKhattab** [akveo/react-native-ui-kitten#1542]
## 🐛 Bug Report

Clicking year on date picker shows years but does not allow years to be selected.

## To Reproduce

Click date picker input, select year at top left, attempt to click year and its greyed out.

## Expected behavior

I expect year to change when clicked
<img width="736" alt="Screen Shot 2021-10-23 at 10 27 41 PM" src="https://user-images.githubusercontent.com/26516889/138582062-32d97933-ac92-40eb-ab61-d33a2fb8bf72.png">
## Link to runnable example or repository (highly encouraged)

https://akveo.github.io/react-native-ui-kitten/docs/components/datepicker/overview#rangedatepicker

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    @latest    |
| @ui-kitten/components   |  @latest      |

## Environment information

On Website

**Comment by malashkevich** [comment]
@OmarKhattab this is most likely should be documented, but it's actually correct behavior.
In the examples from the documentation, there is no `min` and `max` props set. If those props are not set, the calendar will take props by default: `min` as the beginning of the current year and `max` as the end.https://github.com/akveo/react-native-ui-kitten/blob/04481cec49a78f859c4cde65a45b157770ea1439/src/components/ui/calendar/baseCalendar.component.tsx#L91
