### ISSUE TITLE
SelectItem moved down for the size of the status bar on iOS

### ISSUE THREAD

**Issue by vuk-nikolic** [akveo/react-native-ui-kitten#1546]
## 🐛 Bug Report

We added custom theme via mapping.json file where just changed background color and borders.
When I tap on a `Select` component, it's `SelectItem`s are moved down, it seems like for the size of the status bar if i'm not mistaken.
Here is a screenshot, I tapped on "Select Time" and it went down even below "Additional notes" that's the row below it:
![Screenshot 2021-11-03 at 18 19 56](https://user-images.githubusercontent.com/1084214/140150147-b1466ce7-bdce-4883-b894-23251c19a252.png)

Is there something we can do with that popover? 
It's fine in Android. 

I tried with just showing that `Select` without any other elements on the screen and it's still performing like this.

Here is the mapping file if that helps [mapping.json.zip](https://github.com/akveo/react-native-ui-kitten/files/7469577/mapping.json.zip)

## To Reproduce

1. Added Select with SelectItem
2. Applied backgrounds and boarders in mapping.json
2. On iOS SelectItems are moved down (seems like for the size of the status bar?)

## Expected behavior

1. SelectItem is not moved down

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |      2.0.0 |
| @ui-kitten/components   |       5.0.0  |

## Environment information

```bash
 System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.22.15 - ~/.yarn/bin/yarn
    npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-25 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  npmPackages:
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 


```

**Comment by malashkevich** [comment]
Hello @vuk-nikolic, please make sure that `ModalService. setShouldUseTopInsets` is used on Android only. Most likely this is root cause

**Comment by vuk-nikolic** [comment]
> Hello @vuk-nikolic, please make sure that `ModalService. setShouldUseTopInsets` is used on Android only. Most likely this is root cause

thanks @malashkevich, I'll check it out! Do I set `ModalService` on the app level or per component that uses a popover internally?

If I got it right from here it's global https://akveo.github.io/react-native-ui-kitten/docs/components/modal-service/overview#modalservicetype but I guess internally select is using it :)

**Comment by vuk-nikolic** [comment]
Changing `ModalService.setShouldUseTopInsets` to either true or false did not change anything.
I had to upgrade to uikitten 5.1.1 in order to have that property.

In the file where that screen is defined I'm setting `ModalService.setShouldUseTopInsets = false` for iOS but nothing is happening. What I am doing wrong? :)

**Comment by vuk-nikolic** [comment]
I saw that if I add to the `Popover` via react native debugger style `{ top: -44 }` it looks like it should. Now I need to figure out how to do that in code :) 

Is there a way to override that style just for iOS? In`mapping.json` it does not have parameters for `Popover`, while in `Select` there are `popoverMaxHeight`, `popoverBorderRadius`, `popoverBorderColor` and `popoverBorderWidth`, and not for actual placement (like `top`).

Obviously some component introduced this offset and great suggestion for `ModalService.setShouldUseTopInsets`. 
Any more ideas what I can try to debug this issue @malashkevich?

**Comment by dVaytul** [comment]
Hello @vuk-nikolic 
I can't repeat your issue.
Could you please provide code example of screen initialisation?

**Comment by dVaytul** [comment]
Closed due to inactivity. Feel free to reopen
