### ISSUE TITLE
Prevent RkTextInput focus on label press (or make it optional)

### ISSUE THREAD

**Issue by Johan-dutoit** [akveo/react-native-ui-kitten#155]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description
I've implemented a "show" password feature, using the label prop provided by RkTetxInput.

**Current behavior:**
When pressing on a label (which is string or icon), it focuses the underlying text input and then triggers my onPress.

**Expected behavior:**
When providing an onPress, it should ignore the default focus behaviour or at least be optional.

**Steps to reproduce:**
See code below

**Related code:**

```
 <RkTextInput
        {...otherProps}
        label={this.renderIcon()}
        placeholder={placeholder}
        rkType='iconRight'
        secureTextEntry={!showPassword}
      />

 renderIcon = () => {
    const { showPassword } = this.state;
    const name = showPassword ? 'eye-off' : 'eye';

    return <Icon name={name} onPress={this.toggleShowPassword} />;
  };
```

### Other information:

The code that needs to be changed: https://github.com/akveo/react-native-ui-kitten/blob/586b4f22b540b1ee0deaf194053907c0b51dc6e4/src/components/textinput/rkTextInput.js#L184

I'm happy to PR this myself, however would like to discuss first.

The change could look something like this: 

`label.props.onPress ? label.props.onPress(e) : this.inputRef.focus();`

**Comment by malashkevich** [comment]
Hi @Johan-dutoit 
Thanks for contributing!
We are working on the new version which will be completely redesigned. So it makes sense to close this issue as we don't have plans to support this version of lib.

**Comment by Johan-dutoit** [comment]
@malashkevich anyway I can get access to this? i.e. I'd love to contribute and/or test :)

**Comment by artyorsh** [comment]
@Johan-dutoit 
For now you can stay tuned on repo updates and see issues we are working on.
As a contributor you can have some ideas on features we're going to implement, etc
