### ISSUE TITLE
Issues with Modal Service

### ISSUE THREAD

**Issue by garrylachman** [akveo/react-native-ui-kitten#1551]
## 🐛 Bug Report
1. In Modal Service example the modalID is stored in re-assign to const 
```
const modalID = '';

  const showModal = () => {
    const contentElement = this.renderModalContentElement();
    this.modalID = ModalService.show(contentElement, { onBackdropPress: this.hideModal });
  }
```
I think i dont need to explain why its wrong (and not working for me).
2. in `showModal` function modalID access via `this`, in react functional component this is `undefined`.
3. I try to store `modalID` in React.useState but after the assign i can't access to the modalID via state, its just empty. i dont know why...
4. Using Modal Service there is no option to change the modal style, basic example like center the modal is not working. In the example all the Application is centered but its now useable in real life.

**Comment by dVaytul** [comment]
Hello @garrylachman

p.1, 2 - You are right, the example is broken. It should be `let modaID` and `this` should be removed, of course.

p.3 - useState hook is asynchronous, and will not be reflected immediately. 
```
setId(modalID);
console.log(id) // id here is not updated yet
```
but will be updated later:
```
React.useEffect(() => {
  console.log(id);
}, [ id ]);
```

Regarding p.4 - you need to calculate and specify correct position (`position: 'absolute', top/left`) by yourself to set `contentElement` in the centre of the screen. ModalService, unlike ModalComponent. has no such functionality. It only allows to manage custom modal component.
