### ISSUE TITLE
Invisible modal appears to be stripping away the redux provider?

### ISSUE THREAD

**Issue by tdranv** [akveo/react-native-ui-kitten#1553]
## 🐛 Bug Report

I have this component:

```jsx
import React, { useState } from "react";
import { Modal } from "@ui-kitten/components";
import { TouchableWithoutFeedback, View } from "react-native";

function PressAndHoldCard({ renderContent, renderOnHoldContent, ...props }) {
  const [previewOpen, setPreviewOpen] = useState(false);

  return (
    <TouchableWithoutFeedback
      {...props}
      onLongPress={() => setPreviewOpen(true)}
    >
      <View>
        {renderContent}
        <Modal
          visible={previewOpen}
          onBackdropPress={() => setPreviewOpen(false)}
        >
          {renderOnHoldContent}
        </Modal>
      </View>
    </TouchableWithoutFeedback>
  );
}
```
The `App.js` is wrapped in a redux `Provider`, everything else works fine.

Initially, the modal is hidden, as you can see. If I press and hold in order to show the `onHoldContent`, I get an error that the app is not wrapped in a `Provider`.

It works if you wrap the `renderOnHoldContent`, or if you switch to `react-native`'s `Modal`, which leads me to think that it must be an issue with the modal being unmounted at first?

## Expected behavior

To be able to use redux's store from inside the modal.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    "2.1.1"    |
| @ui-kitten/components   |    "5.1.1"     |

## Environment information
```bash
  System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.4 - ~\AppData\Roaming\npm\npm.CMD
  IDEs:
    Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7621141
  npmPackages:
    react: 17.0.1 => 17.0.1
    react-native: 0.63.4 => 0.63.4
```

**Comment by sergeu90** [comment]
@tdranv  Hi. I think i have same issue in this ticket https://github.com/akveo/react-native-ui-kitten/issues/1585

**Comment by greenfrvr** [comment]
I think @sergeu90  is right. The issue is likely to be related to context access inside our modals. Please check #1585 status to be aware of updates regarding this issue.
