### ISSUE TITLE
Can't select same date in the date range calendar

### ISSUE THREAD

**Issue by sathishkumar1911** [akveo/react-native-ui-kitten#1564]
The Date range calendar not allowing to select same date for both start and end date. Like If I want to use the single date range calendar for below scenarios 
* Select Dec 1st to Dec 15th
* Select Dec 15th to Dec 15th (I am providing the option to select the times like Dec 15th 9 AM to Dec 15th 5PM). 

It is not working on the second case.

**Comment by sawndur** [comment]
The range calendar should be used for dates... I don't think the range calendar was intended to provide the option to select time. If you select Dec 15th, and only Dec 15th, that will be the only startDate. You can use that fact to maybe open another modal showing time selection.

**Comment by praveen-ennea** [comment]
allowBackwardRangeSelect    
pass this prop
