### ISSUE TITLE
No option to change the color of the current date selection

### ISSUE THREAD

**Issue by sathishkumar1911** [akveo/react-native-ui-kitten#1565]
When I use the single date calendar on my app, it is showing the current date as selected but it is not actually selected and when it is selected, it is highlighted with the same style. It is hard for users to know whether the date is selected or the current date is highlighted.

Current Date:
![image](https://user-images.githubusercontent.com/2183751/145489003-95cc730e-ffcb-494c-b08a-d2e940cd7e2a.png)

After Selecting Dec 9th:
![image](https://user-images.githubusercontent.com/2183751/145489062-370770a9-0d40-44f4-9c9f-4652abf43df9.png)

There is no way to tell that the current date is selected or not.

**Comment by sawndur** [comment]
You can change the style of selected date with customized mapping.

**Comment by dVaytul** [comment]
Hi @sathishkumar1911,

looks like date property should be required. In this case a color of the current date (01/06/2022) differs from the color of selected date (01/12/2022).
<img width="368" alt="Screenshot 2022-01-06 at 15 07 28" src="https://user-images.githubusercontent.com/31446157/148380773-023c1ad6-1b16-4660-99c7-bd8532d705a1.png">

As advised above, if you want to customise colours, you can use own mapping:
- create mapping.json with new styles (see example bellow);
- merge mapping inside ApplicationProvider;

For more information read [documentation](https://akveo.github.io/react-native-ui-kitten/docs/design-system/customize-mapping#customize-component-mapping).

Example of custom mapping.json:
```
{
  "components": {
    "CalendarCell": {
      "appearances": {
        "default": {
          "mapping": {
            "state": {
              "selected": {
                "contentBorderColor": "red",
                "contentBackgroundColor": "red",
                "contentTextColor": "white"
              },
              "today": {
                "contentBorderColor": "red",
                "contentBackgroundColor": "pink"
              }
            }
          }
        }
      }
    }
  }
}

```
