### ISSUE TITLE
The Select element does not select items from the list

### ISSUE THREAD

**Issue by Latgals** [akveo/react-native-ui-kitten#1566]
## 🐛 Bug Report

In the Expo application, the Select element does not select items from the list, but shows "Option 1", "Option 2", etc.

I copied the code from the UI Kitten documentation for the Select element and pasted it into my application. I just replaced the "title" value in <SelectItem> with my own text. But the Select after selection still shows "Option 1", "Option 2", and not my items.

![scr_select_bug3](https://user-images.githubusercontent.com/44416239/146797349-bac8f951-a164-422e-a6b4-0e9f153d140d.jpg) 
![scr_select_bug1](https://user-images.githubusercontent.com/44416239/146797337-6732a35f-8db2-455a-97a3-a4b3851879b8.jpg) 
![scr_select_bug2](https://user-images.githubusercontent.com/44416239/146797345-a3ad01f9-60ef-4f0a-87d3-9743d5e745c5.jpg)

I have reproduced the bug at Expo Snack - [you can check it here](https://snack.expo.dev/@latglas/ui-kitten-select).

The same thing happens with the enabled and disabled multiSelect option.

How do I fix the bug?

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   2.1.1     |
| @ui-kitten/components   |    5.1.1     |

## Environment information

"expo": "~43.0.2",
"react": "17.0.1",
"react-dom": "17.0.1",
"react-native": "0.64.3",

```bash

```

**Comment by Ycmelon** [comment]
Having the same problem... unless we're missing something?

In the meantime, this is how I'm doing it:

```jsx
const [index, setIndex] = useState();
const options = ["a", "b", "c"];
...
<Select selectedIndex={index} onSelect={setIndex} value={options[index.row]}>
  {options.map((value)=><SelectItem title={value} key={value}>)}
</Select>
```

Seems like `value` is what is displayed in the input box.

**Comment by Latgals** [comment]
> Having the same problem... unless we're missing something?
> 
> In the meantime, this is how I'm doing it:
> 
> ```js
> const [index, setIndex] = useState();
> const options = ["a", "b", "c"];
> ...
> <Select selectedIndex={index} onSelect={setIndex} value={options[index.row]}>
>   {options.map((value)=><SelectItem title={value} key={value}>)}
> </Select>
> ```
> 
> Seems like `value` is what is displayed in the input box.

Thanks to. With single select I solved the problem too. 
But with multiSelect not yet.

**Comment by dVaytul** [comment]
@Latgals 

By default, `Select` displays a value by building strings for selected indices. For a real-word examples, a `value` property should be configured.

Please, take a look at the example ['Select Display Value'](https://akveo.github.io/react-native-ui-kitten/docs/components/select/overview#:~:text=Select%20Display%20Value).
