### ISSUE TITLE
Custom year in Calendar Component

### ISSUE THREAD

**Issue by pavitpim40** [akveo/react-native-ui-kitten#1571]
## 💬 Question
How can I change year number in calendar component (eg. 2022 to 2565 for buddhist calendar)
thank you in advance.
![ภาพถ่ายหน้าจอ 2565-01-01 เวลา 18 44 30](https://user-images.githubusercontent.com/63455126/147849763-00d222f0-334e-4000-9f2f-d00e29210257.png)

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2.1.1    |
| @ui-kitten/components   |    5.1.1     |

**Comment by dVaytul** [comment]
Hi @pavitpim40 

If you want to use date in usual format (2022), but show a different year (2565) in the calendar, you should set custom title and renderYear props. Check details in the [docs](https://akveo.github.io/react-native-ui-kitten/docs/components/calendar/api#calendar).

[See the example](https://snack.expo.dev/ZklBpTdpx)
