### ISSUE TITLE
Selectable text not working when part of a List

### ISSUE THREAD

**Issue by JoeKlimcak** [akveo/react-native-ui-kitten#1577]
Even if we just take the basic example list demo from your website:

```
import React from 'react';
import { StyleSheet } from 'react-native';
import { Divider, List, ListItem } from '@ui-kitten/components';

const data = new Array(8).fill({
  title: 'Item',
  description: 'Description for Item',
});

export const ListDividersShowcase = () => {

  const renderItem = ({ item, index }) => (
    <ListItem
      title={`${item.title} ${index + 1}`}
      description={`${item.description} ${index + 1}`}
    />
  );

  return (
    <List
      style={styles.container}
      data={data}
      ItemSeparatorComponent={Divider}
      renderItem={renderItem}
    />
  );
};

const styles = StyleSheet.create({
  container: {
    maxHeight: 200,
  },
});
```

If I insert something like the following:

```
    <ListItem
      title={`${item.title} ${index + 1}`}
      description={<Text selectable={true}>Foo Bar</Text>}
    />
```

The selectable feature doesn't work.

How can I make the text inside your List selectable?

**Comment by dVaytul** [comment]
Hello @JoeKlimcak 

We are using `<FlatList>` as a core of our `<List>`.
There is a known issue where `<Text>` inside `<FlatList>` cannot be selectable.
It can be resolved by adding `removeClippedSubviews={false}` prop to `<FlatList>` and our `<List>` too.

You can check details [here](https://github.com/facebook/react-native/issues/26264)
