### ISSUE TITLE
Is it possible to refer to variables defined in "strict" in mapping.json in nested objects?

### ISSUE THREAD

**Issue by aminta** [akveo/react-native-ui-kitten#1591]
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |     "^2.1.1"   |
| @ui-kitten/components   |   "^5.1.1      |

```
 "strict" {
 "cell-medium": 1.5
}

"variantGroups": {
            "type": {
              "a": {
                "cellStyles": {
                  "position": {
                    "size": "cell-medium",
                    "alignment": "flex-start",
                    "textStyle": "bold"
                  },
                  "name": {
                    "size":  "cell-medium"
                    "alignment": "baseline",
                    "textStyle": "regular",
                    "paddingLeft": 5,
                    "paddingRight": 5
                  },
}
```

It returns this error: `JSON value 'table-cell-medium' of type NSString cannot be converted to NSNumber`, so `cell-medium` is interpreted as literal string; if I try to use `cell-medium` as value in a not nested object it works.

**Comment by aminta** [comment]
Ok, so I've mapped the code flow and found a solution but I'm asking here if anyone has an idea on how implement it without overwriting the source code.

In `node_modules/@eva-design/processor/js/src/service/style/style.service.js` I've modified function `withStrictTokens` in this way:

```
unction withStrictTokens(mapping, theme) {

    return Object.keys(mapping).reduce((acc, next) => {
        let currentToken = mapping[next];
        /* MAPPING
          iconMarginHorizontal: 10,
          borderColor: 'transparent',
          backgroundColor: 'color-basic-transparent-200',
          textColor: 'text-primary-color',
          iconTintColor: 'text-primary-color',
          minWidth: 'size-medium',
        */


        /* NEXT
        iconTintColor
        */


        /* theme
        è l'oggetto con le variabili definite in "strict" in mapping.json
        */

        if(isObject(mapping[next])) {
          let o = mapping[next];
          let k = Object.keys(o).reduce((acc, next) => {
            const currentToken = o[next];
            const nextToken = common_1.isNil(theme[currentToken]) ? currentToken : theme[currentToken];
            return Object.assign(Object.assign({}, acc), { [next]: nextToken });
          }, {})
          currentToken = k
        }
        const nextToken = common_1.isNil(theme[currentToken]) ? currentToken : theme[currentToken];
        return Object.assign(Object.assign({}, acc), { [next]: nextToken });
    }, {});
}

```

**Comment by greenfrvr** [comment]
@aminta are you trying to create mapping for your custom component? I think current mapping implementation was not designed to be used with nested objects. if you check UI Kitten components, each component which is compound extracts style object for each sub-component from flat object with no nested structures. having nested structures inside mappings may be a nice thing to have, but it will increase complexity for validation and for style generator. not sure if we're going to work on it for nearest release.
