### ISSUE TITLE
Select Component having inconsistent behaviours on android and iOS platform.

### ISSUE THREAD

**Issue by ShubhamBathe-KM** [akveo/react-native-ui-kitten#1592]
## 🐛 Bug Report

Select Component having inconsistent behaviours on android and iOS platform. I was trying to implement simple select component in my project. Its working perfectly on android but for iOS platform its have some extra spacings while the dropdown menu is in open state.

![image](https://user-images.githubusercontent.com/67695272/156348101-32d2823f-00a3-4513-a9cc-7f3eba51413e.png)

I also tried running on a completely new react native setup to make sure there is no styles overriding issue in my project. Here is the screenshot for the same:-

![image (1)](https://user-images.githubusercontent.com/67695272/156357769-04a9f6c6-d1f3-43b6-b199-e31f145483d6.png)

## To Reproduce

Note:- Setup is created using React Native CLI.

Add the dropdown inside your react functional component:-

import { IndexPath, Layout, Select, SelectItem } from '@ui-kitten/components';

const [selectedIndex, setSelectedIndex] = useState(new IndexPath(0));

      <Select selectedIndex={selectedIndex} onSelect={(index) => setSelectedIndex(index)}>
        <SelectItem title="Option 1" />
        <SelectItem title="Option 2" />
        <SelectItem title="Option 3" />
      </Select>

## Expected behavior:-

Have consistent UI behaviour on both platforms.

## Link to runnable example or repository (highly encouraged)

Note:- Setup is created using React Native CLI. On expo playground it works fine for some unknown reasons.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    ^2.1.1    |
| @ui-kitten/components   |     ^5.1.1    |

## Environment information

System:
    OS: macOS 11.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.17 - ~/.yarn/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
    Watchman: 2022.01.31.00 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 23, 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0
      System Images: android-30 | Google APIs Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8092744
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  npmPackages:
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2

Please provide a fix for this bug as soon as possible. Thanks in advance.

**Comment by kssai-62** [comment]
+1

**Comment by ShubhamBathe-KM** [comment]
@kssai-62  Still no solution I am still waiting for someone to provide the same. @artyorsh Can you ask the team to please look into this issue on immediate basis? Thanks for the same.

**Comment by ShubhamBathe-KM** [comment]
> @ShubhamBathe-KM sorry for delay. I've checked `Select` component both with kitten tricks demo app and with fresh test app, and behaviour for iOS is the same it works correctly with no additional margin. is it possible to share some more details how do you achieve result that you shared with screenshots? maybe there are some additional styles or wrapping components involved? are you using some custom mappings overrides? it would help to investigate the issue

@greenfrvr Initially I also though the same that there might be some additional styles in my main project. Thats why I created a bare new react native project setup and tried implementing the select component in it. So as you can see the second screenshot I shared is the one from the newly created react native setup with absolutely no other styles. Maybe I can share my compressed project setup with you or a github link whichever you prefer. Thanks and regards.

**Comment by greenfrvr** [comment]
@ShubhamBathe-KM if you could share a project where the issue is reproducible it would help a lot!

**Comment by ShubhamBathe-KM** [comment]
@greenfrvr I checked with the latest react native version. Not able to reproduce the issue now. I think you can close the issue for now.
