### ISSUE TITLE
How to remove outline in input component in iOS browsers?

### ISSUE THREAD

**Issue by ruida-shen** [akveo/react-native-ui-kitten#1593]
## 💬 Question
I use UI Kitten + expo web for my project, when I open my app in ios browsers, e.g. chrome, safari, the text input when focused has this blue outline, for example:

### Chrome:
<img src="https://user-images.githubusercontent.com/75506336/156837622-412e947e-95d5-4836-b6fb-aa760a4c07c6.jpg" width="300" height="600" />

### Safari:

<img src="https://user-images.githubusercontent.com/75506336/156837669-2c0d769a-6c63-4bed-842f-379d03057479.jpg" width="300" height="600" />

**How do I get rid of this blue outline?**

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   2.1.1     |
| @ui-kitten/components   |    5.1.1     |

**Comment by noone-silent** [comment]
Also happens in Firefox

![grafik](https://user-images.githubusercontent.com/1089817/182791341-1d46368e-258d-40ee-a316-cc5c82bec83f.png)

@eva-design/eva 2.1.1
@ui-kitten/components 5.1.2

**Comment by ruida-shen** [comment]
> Also happens in Firefox
> 
> 
> 
> ![grafik](https://user-images.githubusercontent.com/1089817/182791341-1d46368e-258d-40ee-a316-cc5c82bec83f.png)
> 
> 
> 
> @eva-design/eva 2.1.1
> 
> @ui-kitten/components 5.1.2
> 
> 
> 
> 

Adding

input:focus { outline:none; }

to my global css style fixes the issue

**Comment by noone-silent** [comment]
Please reopen. This is still a bug. Just because you hacked your way through (global style in react-native?), doesn't mean it's fixed.

**Comment by ruida-shen** [comment]
> Please reopen. This is still a bug. Just because you hacked your way through (global style in react-native?), doesn't mean it's fixed.

I don't think this is a bug, i think it is browser'a default style applied to input element

**Comment by noone-silent** [comment]
Yes and this component should render it correctly and disable the outline

**Comment by ruida-shen** [comment]
> Yes and this component should render it correctly and disable the outline

They may intentionally leave it like this for better accessibility, but I will reopen the issue and wait for the official response

**Comment by inform880** [comment]
I'm github surfing trying to find the best UI library for React Native Web, and came across this issue. The creator of React Native Web is leaving the blue outline on purpose for a11y benefits, as you suggested in your last comment @ruida-shen, https://github.com/necolas/react-native-web/issues/48#issuecomment-165980585, but he added some props to make it easy to override it a few years ago.

A more succinct solution is here, later on in the same issue, if you don't want a global style,  https://github.com/necolas/react-native-web/issues/48#issuecomment-788966150. 
@ruida-shen  I think you can close this issue, unless you need to add some props to ui-kitten

@noone-silent So this isn't a bug at all, it's completely intentional and really has nothing to do with ui-kitten, as I personally would always keep the default a11y unless overridden by the end developer. 

I also wouldn't call the global style a hack, as you can always override it on the component level. It's quite literally using global styles exactly how they should be. I know of several production RNW apps using this same global fix without issue.

**Comment by ruida-shen** [comment]
> I'm github surfing trying to find the best UI library for React Native Web, and came across this issue. The creator of React Native Web is leaving the blue outline on purpose for a11y benefits, as you suggested in your last comment @ruida-shen, https://github.com/necolas/react-native-web/issues/48#issuecomment-165980585, but he added some props to make it easy to override it a few years ago.
> 
> 
> 
> A more succinct solution is here, later on in the same issue, if you don't want a global style,  https://github.com/necolas/react-native-web/issues/48#issuecomment-788966150. 
> 
> @ruida-shen  I think you can close this issue, unless you need to add some props to ui-kitten
> 
> 
> 
> @noone-silent So this isn't a bug at all, it's completely intentional and really has nothing to do with ui-kitten, as I personally would always keep the default a11y unless overridden by the end developer. 
> 
> 
> 
> I also wouldn't call the global style a hack, as you can always override it on the component level. It's quite literally using global styles exactly how they should be. I know of several production RNW apps using this same global fix without issue.

Thanks for clarifying, I will close this.

**Comment by 3days3ways** [comment]
This JUST started happening to my macbook pro (running ventura) after running a CleanMyMacX scan and "cleaning up" the system. I don't do anything remotely to deal with coding or developing so its not a hack or coding issue as the above comments seem to suggest (i could be wrong about the content of this thread but thats what it sounds like to me...?). Out of no where (aside from the scan) this started happening in addition to a few other symptoms of messed up software/system. 

<img width="1280" alt="Screenshot 2023-12-24 at 4 19 19 AM" src="https://github.com/akveo/react-native-ui-kitten/assets/86909820/2db1399e-d08f-42ed-bb05-c9b2aada0f75">

While on safari (havent tried chrome or anything else) i get the colored outline box around focus/input areas and it gets triggered occasionally after hitting spacebar but it comes and goes, it is not constant. 
safari also gets force refreshed aftewr every click or tap. For example: while searching safari for solutions i would double tap/right click a URL and add to reading list (and if i open it), as soon as i continue to browse the other search results the page refreshes on its own after every single tap/click.... makes searching incredibly difficult and frustrating. 
Another thing ive noticed so far is the 'space bar' occasionally decides to just not work unless i use 'shift' at the same time as 'spacebar' (this took awhile to figure out...). 
I was able to catch a screen recording of most of this and im thnking ill reach out to apple support with that but previous times reaching out to appke supoort was always a complete waste of time so i dont have high expectations. Id really appreciate any help anyone can give me on how to solve this, or resources i can use to get to a solution. Im really not tech smart so the more entry level the solution, the better please. 
Thanks
