### ISSUE TITLE
How to: TopNavigation style/appearance transparent

### ISSUE THREAD

**Issue by sergioutronics** [akveo/react-native-ui-kitten#1597]
## 💬 Question
I need to make the TopNavigation bar transparent in one specific "Fullscreen" page,
[like in this print](https://imgur.com/B7ROgml)
But the menu icon must show,
i have tried many number of configs like:
`<TopNavigation appearance="default" style={{background:"rgba(0,0,0,0)"}} alignment='center'/>`
But nothing works
have read in the feature that it is already implemented, can i get guidance on how?
## UI Kitten and Eva version
UI Kitten 5.1.1
| @ui-kitten/components   |         |

**Comment by bataevvlad** [comment]
Closing due to zero activity in the ticket.
Issue has been checked.
