### ISSUE TITLE
Third Party Icons do not render

### ISSUE THREAD

**Issue by dvdprr6** [akveo/react-native-ui-kitten#1601]
## 🐛 Bug Report

Third party icons do not render.
![image](https://user-images.githubusercontent.com/1852283/160513507-0001635a-1ca3-4296-8bc7-abde2ee1a95c.png)

I have followed the Third Party Icon guide found [here](https://akveo.github.io/react-native-ui-kitten/docs/guides/icon-packages#3rd-party-icon-packages), 

This is how I am registering the Feather Icons Pack

```JavaScript
function FeatherIcon({ name, style }){
  const { height, tintColor, ...iconStyle } = StyleSheet.flatten(style)

  return <Icon name={name} size={height} color={tintColor} style={iconStyle} />
}

const IconProvider = (name: any) => ({
  toReactElement: (props: any) => FeatherIcon({ name, ...props })
})

function createIconsMap() {
  return new Proxy({}, {
    get(target, name) {
      return IconProvider(name);
    },
  });
}

const FeatherIconsPack = {
  name: 'feather',
  icons: createIconsMap()
}

const App = () => {

  return (
    <Provider store={store}>
      <IconRegistry icons={FeatherIconsPack}/*icons={EvaIconsPack}*/ />
      <ApplicationProvider {...eva} theme={{ ...eva.dark, ...theme2}}>
        <Stack />
      </ApplicationProvider>
    </Provider>
  )
}

export default App
```
This is how I am applying the icons

```JavaScript
const BottomTabBar: FC<{ navigation: any, state: any }> = (props) => {
  const { navigation, state } = props

  return (
    <BottomNavigation
      selectedIndex={state.index}
      onSelect={(index: React.ReactText) => navigation.navigate(state.routeNames[index])}
      appearance={'noIndicator'}
    >
      <BottomNavigationTab icon={props => <Icon {...props}  name={'facebook'} />} />
      <BottomNavigationTab icon={props => <Icon {...props} name={'facebook'} />} />
      <BottomNavigationTab icon={props => <Icon {...props} name={'facebook'} /> } />
    </BottomNavigation>
  )
}
```
I also tried with Material Icons but I run into the same problem.

Any help would be greatly appreciated.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |  ^2.2.1      |
| @ui-kitten/components   | ^5.1.1        |

## Environment information

```bash
  System:
    OS: Linux 5.16 Pop!_OS 21.10
    CPU: (16) x64 Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
  Binaries:
    Node: 16.13.2 - /usr/local/bin/node/bin/node
    npm: 8.4.1 - /usr/local/bin/node/bin/npm
  SDKs:
    Android SDK:
      API Levels: 26, 27, 28, 29, 30
      Build Tools: 27.0.3, 29.0.2, 30.0.2, 30.0.3, 33.0.0
      System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-Tiramisu | Google APIs Intel x86 Atom_64
  npmPackages:
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.2 => 0.67.2 
```

**Comment by greenfrvr** [comment]
@dvdprr6 from what I see, there is an icon pack name missing, so you should pass it explicitly:
`<BottomNavigationTab icon={props => <Icon {...props}  pack={'feather'} name={'facebook'} />} />`

also be careful with destructuring `style` prop in your `FeatherIcon` component. it may cause a crash if you won't pass `style` prop to an `Icon`.

**Comment by bataevvlad** [comment]
I move the ticket to closed due to low activity and the proposed option to help.

If the problem continues to occur, please indicate in the ticket we will reopen it and look for a solution.
