### ISSUE TITLE
Can I look up a built-in style for a ui-kitten component?

### ISSUE THREAD

**Issue by gavingolden** [akveo/react-native-ui-kitten#1626]
## 💬 Question

I'm using a third-party component library that allows me to style the component via props (but I can't override the component type).

Is there a hook to lookup the entire style for a built-in kitten component (e.g. `Input`)? Something like:
```tsx
const theme = useTheme()
const inputStyle = theme['Input']

return <ThirdPartyInput style={inputStyle} />
```

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2.1.1    |
| @ui-kitten/components   |     5.1.2    |

**Comment by greenfrvr** [comment]
@gavingolden short answer is no. style usage is a bit more complicated than just getting object by component name as a key. for example for `Input` component there are several variables which defines style object e.i. appearance, category, status and even component state (focused, disabled and etc.) so in fact there are many style objects for each possible configuration of that variables, and there is corresponding compound key for each style, which was not design to manual usage. style processing is designed for internal usage only, with components provided with current library. not sure we're going to change that in near future.
