### ISSUE TITLE
Compatible with React Native Web

### ISSUE THREAD

**Issue by AtifShahzed** [akveo/react-native-ui-kitten#1629]
## 💬 Question
Hi,
I am in love with this library, my question is can we use this library with REACT NATIVE WEB ?
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |        |
| @ui-kitten/components   |         |

**Comment by flexbox** [comment]
Hey @AtifShahzed 
https://akveo.github.io/react-native-ui-kitten/docs/guides/running-on-the-web#running-on-the-web

TLDR
**yes**

If your problem is solved can you please close the issue? 
It sparks joy for maintainers ✨
