### ISSUE TITLE
Creating a new project fails

### ISSUE THREAD

**Issue by parsa-j42** [akveo/react-native-ui-kitten#1630]
## 🐛 Bug Report
Creating a new Project fails using the command provided in the docs (only for JavaScript projects, creating a TypeScript project doesn't have a problem). The created project is incomplete and the following error is thrown:
```
✔ Downloading template
⠋ Copying template/usr/lib/node_modules/@react-native-community/cli/node_modules/graceful-fs/polyfills.js:265
        if (!chownErOk(er)) throw er
                            ^

Error: ENOENT: no such file or directory, chmod '/home/user/Programming/ui-kitten/MyApp/metro.config.js'
    at Object.chmodSync (node:fs:1843:3)
    at Object.chmodSync (/usr/lib/node_modules/@react-native-community/cli/node_modules/graceful-fs/polyfills.js:263:21)
    at ReadStream.<anonymous> (/usr/lib/node_modules/@react-native-community/cli/build/tools/copyFiles.js:105:19)
    at ReadStream.emit (node:events:527:28)
    at emitCloseNT (node:internal/streams/destroy:138:10)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  syscall: 'chmod',
  code: 'ENOENT',
  path: '/home/user/Programming/ui-kitten/MyApp/metro.config.js'
}
```

## To Reproduce

Run `npx react-native init MyApp --template @ui-kitten/template-js`

## Expected behavior

A new UI Kitten project should be created completely and without errors.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    8.11.0    |
| @ui-kitten/components   |   8.11.0    |

## Environment information

```bash
  System:
    OS: Linux 5.18 Pop!_OS 22.04 LTS
    CPU: (16) x64 AMD Ryzen 7 5700U with Radeon Graphics
  Binaries:
    Node: 16.15.1 - /usr/bin/node
    Yarn: 1.22.15 - /usr/bin/yarn
    npm: 8.11.0 - /usr/bin/npm
```

**Comment by flexbox** [comment]
Hey @parsa-j42 

Have you run this before?
```
npm un -g react-native-cli && npm i -g @react-native-community/cli
```

You can also debug your computer setup with https://reactnative.dev/blog/2019/11/18/react-native-doctor
```
npx @react-native-community/cli doctor
```

I checked on my machine without problems
![image](https://user-images.githubusercontent.com/360936/181575064-83fa7c34-e681-4fbd-8160-cc9a2dedf4d1.png)


If your problem is solved can you please close the issue? 
It sparks joy for maintainers ✨

**Comment by parsa-j42** [comment]
@flexbox 
Hmm, I just re-ran the command, and it worked, I don't have any idea what the issue was the last time.

Thank you for your response, I will close the issue.
