### ISSUE TITLE
Button Unsupported configuration

### ISSUE THREAD

**Issue by fatihozkir** [akveo/react-native-ui-kitten#1635]
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |     ^2.1.1   |
| @ui-kitten/components   |   ^5.1.2      |

Hello, 
Good day.

We are pretty new on the usage of UI Kitten, upon our custom component implementations we are having the warning for UIKitten button.
Both in our props and UIKitten button's props there are no variants and states properties. But the error says to check one of the following prop values.

The code block is here:
![image](https://user-images.githubusercontent.com/18119024/180421029-75d19f7e-dc65-46aa-a5cf-b0d710b17c15.png)

![image](https://user-images.githubusercontent.com/18119024/180420622-031717cc-ade7-45d4-bb95-220c876bf7f0.png)

Looking forward to hearing from you.

**Comment by flexbox** [comment]
What happens when you spread all the attributes?

Example:
```
function QiButton({...props}) {
  return <Button {...props}>;
}
```

https://davidl.fr/pattern#spread-attributes

**Comment by fatihozkir** [comment]
@celinedupuis 
props appearance has the default value which is  'filled', nevertheless still the issue is being persisted.

**Comment by fatihozkir** [comment]
> What happens when you spread all the attributes?
> 
> Example:
> 
> ```
> function QiButton({...props}) {
>   return <Button {...props}>;
> }
> ```
> 
> https://davidl.fr/pattern#spread-attributes

I am going to give it a try, thanks a lot

**Comment by greenfrvr** [comment]
@fatihozkir There might be 2 cases: either passed appearance/status/size are undefined or non-null values, which are not described in mappings. From the code snippet it's not clear where default value values for that props are defined, and what exact values are passed to button. Can you check which case do you have? And maybe tell which values are passed to `Button` props?

**Comment by bataevvlad** [comment]
Closing the problem because of the long response time, there is a chance that the problem has already been fixed, if you have any questions, happy to help, you can reopen the ticket for this, with respect the team UI Kitten
