### ISSUE TITLE
Custom mapping: couldn't find DrawerItem

### ISSUE THREAD

**Issue by celinedupuis** [akveo/react-native-ui-kitten#1638]
Hi,

I wanted to increase the font size and icon size of the **DrawerItem** by using custom mapping, but couldn't find the component in **mapping.json**. How come ? 

Note that I tested the custom mapping with MenuItem and it worked fine.

```
"components": {
    "MenuItem": {
      "appearances": {
        "default": {
          "mapping": {
            "titleFontSize": 14,
            "iconWidth": 24,
            "iconHeight": 24,
          }
        }
      }
    },
 }
```

Thanks in advance!

## UI Kitten and Eva version
| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2.1.1    |
| @ui-kitten/components   |     5.1.2   |

**Comment by malashkevich** [comment]
@celinedupuis it's because the Drawer [using MenuItem as DrawerItem](https://github.com/akveo/react-native-ui-kitten/blob/master/src/components/ui/drawer/drawerItem.component.tsx)
So the best way is to change the mapping for `MenuItem`. You could also add a new appearance just for drawer.
