### ISSUE TITLE
Support React Version 18 and React Native 0.69 (latest), especially in conjunction with expo SDK 46.

### ISSUE THREAD

**Issue by woltob** [akveo/react-native-ui-kitten#1640]
Hello,

I was wondering when this library will support later versions for React and React Native and what the update timeline for this is.
Looking at the package.json (https://github.com/akveo/react-native-ui-kitten/blob/master/package.json) I see the following versions being enforced:

```
    "react": "~16.9.0",
    "react-native": "~0.61.4",
    "react-native-svg": "~9.13.6",
    "react-native-testing-library": "^1.12.0",
    "react-test-renderer": "16.9.0",
```

Are there any known issues using this library with React v18 and React Native 0.69, especially with the widely used expo environment for react native https://github.com/expo/expo.

Thank you for a quick response.

Thumbs up if any of you have the similar question.

**Comment by woltob** [comment]
Hi @artyorsh,  @32penkin, @malashkevich,

I've seen you're among the most contributing developers to this library. 
Could you provide us with an update timeline for @akveo/react-native-ui-kitten ?

Thank you, this would be appreciated by so many I suppose!

**Comment by artyorsh** [comment]
Hi @woltob thanks for the opening a very valid topic.

I'm not directly associated with this project anymore, but I think I can squeeze some time to check if the library is compatible with latest versions of RN/Expo as I'm still using it in a project that I'm currently working on. If you have any progress on it, it would be nice to have someone involved as well (PRs were always welcome).

**Comment by woltob** [comment]
Hi @artyorsh,

thank you for the quick response. That sounds awesome, very much appreciated!

Do you know who is currently in charge of the project and is there any timeline for future development? 
I believe this is a pretty cool library being used by many developers for active (and also commercial) projects.
Do you know if https://www.akveo.com/ is still actively working with / on this?

Cheers!

**Comment by artyorsh** [comment]
> Do you know if https://www.akveo.com/ is still actively working with / on this?

I believe yes :) I'll make a heads up to @malashkevich as to the mobile development driver at the company

**Comment by woltob** [comment]
HI @malashkevich  and @artyorsh, 
just wanted to quickly check in again if there is any news on this topic? 
Thanks!

**Comment by woltob** [comment]
Hi @malashkevich  and @artyorsh,
any updates on this topic? 
Thanks!

**Comment by malashkevich** [comment]
Hey @woltob.

Yeah, sorry for the delay. We were quite busy with other projects. But we started to work on UI Kitten again.
We will take a look at it soon.
