### ISSUE TITLE
Open DrawerGroup by default

### ISSUE THREAD

**Issue by elmurci** [akveo/react-native-ui-kitten#1647]
## 💬 Question

Is there any way to have a `DrawerGroup` open by default, or programmatically?

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   5.0.0     |
| @ui-kitten/components   |  5.0.0       |

**Comment by greenfrvr** [comment]
@elmurci there is pull request #1389 it will allow to set drawer group to be opened by default with a prop `initiallyExpanded`. 
I'll close this issue, you can watch PR status to get notified if it was merged.
