### ISSUE TITLE
UI Kitten TopBar with indicator below

### ISSUE THREAD

**Issue by hoangquocan** [akveo/react-native-ui-kitten#1656]
Hi! Can anyone help me with issue?
I want create Topbar with Indicator below Text but default it position on Text like this 
![Screenshot from 2022-10-04 20-23-06](https://user-images.githubusercontent.com/105065106/193832693-d6daf97e-e090-4956-9ab4-d630186d36bb.png)

Expect it 

![Screenshot from 2022-10-04 20-24-19](https://user-images.githubusercontent.com/105065106/193833215-3bf11c15-bdf2-4bef-9e15-54dca01b9955.png)

Tks All!

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |        |
| @ui-kitten/components   |         |

**Comment by kendrickw** [comment]
This seems to be a change in behaviour?  If I downgrade to v5.1.1, the tab indicator is positioned below the text (as expected)

**Comment by TMcLoone** [comment]
Agree on this, much butter with indicator below
