### ISSUE TITLE
Does anyone support the project?

### ISSUE THREAD

**Issue by exzos28** [akveo/react-native-ui-kitten#1657]

**Comment by malashkevich** [comment]
Hello @exzos28 
Let me answer this one.

The project is maintainable, but in slow mode. The reason behind it that in our company (Akveo) we do not have dedicated person who works on this project fulltime. So sometimes there might be large pauses between activities.

We are trying to figure out the better way to provide a support, but at the moment it will stay as is.
We are sorry about that.
