### ISSUE TITLE
Disabled multi select item is still selectable

### ISSUE THREAD

**Issue by tomgreener** [akveo/react-native-ui-kitten#1667]
## 🐛 Bug Report

Disabling a `SelectItem` that belongs to a multi `Select` element does not disable multi select checkbox for row.

https://user-images.githubusercontent.com/19623235/199224503-cb92d923-6eef-4bec-b8da-fa4b14cb76ad.mov

## To Reproduce

1. Create a `<Select multiSelect />` element and fill it with `<SelectItem disabled />`.
2. Open the rendered `<Select />` - `<SelectItem />` text should appear disabled and should not be pressable.
3. Press checkbox for `<SelectItem />` - item should be added to selected list of elements.

## Expected behavior

The checkbox for the `<SelectItem />` should appear disabled and not be pressable.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      | 2.1.1        |
| @ui-kitten/components   |  5.1.1       |

## Environment information

```bash
System:
    OS: macOS 11.5.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 3.1.0-rc.4 - /usr/local/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Watchman: 2021.11.01.00 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
  IDEs:
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
```

**Comment by tomgreener** [comment]
FYI my workaround for now is overwriting the onPress event:
```
<SelectItem
    disabled={option.disabled}
    {...(option.disabled && { onPress: () => {} })}
/>
```

**Comment by greenfrvr** [comment]
@tomgreener thanks for the report!
