### ISSUE TITLE
Icon triggers error with tintColor

### ISSUE THREAD

**Issue by ekokotov** [akveo/react-native-ui-kitten#1675]
## To Reproduce

Following code 
<img width="563" alt="image" src="https://user-images.githubusercontent.com/11966000/201541751-20cf6c6c-1dc4-414f-86f5-0bc02b3edbb2.png">
triggers error
<img width="446" alt="image" src="https://user-images.githubusercontent.com/11966000/201541660-4aa126a5-d72d-4636-9bb8-de50178d0233.png">
Its something related to tintColor
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |      2.1.1  |
| @ui-kitten/components   |      5.1.2   |

## Environment information

```bash
  System:
    OS: macOS 12.2
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 18.11.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.4/13F17a - /usr/bin/xcodebuild
  npmPackages:
    react: 18.2.0 => 18.2.0 
    react-native: 0.70.5 => 0.70.5 


```

**Comment by affan338** [comment]
Is there any update on this issue? I am also facing an issue due to tintColor.

**Comment by jane-airen** [comment]
I am also experiencing this issue right now.

**Comment by a-y-u-s-h** [comment]
Happening with me as well. Icon works fine when used alone, gives out this error when used inside as an accessory or something.

**Comment by lianmetrobi** [comment]
Just got this too, started happening after upgrading from expo 46 to 47, downgrading react-native-svg to 13.2.0 fixed it for me, although expo says it's not compatible with current version.

**Comment by koukoujohn** [comment]
Yes I can confirm. The crash started when I upgraded from expo 46 to 47 which updated react-native-svg from 12.3.0 to 13.4.0

I cannot use akveo icons inside components anymore. For example with accessoryLeft, accessoryRight etc.

**Comment by Derrick-Tan-D-WEBDEV** [comment]
Hi, any update on this? I am facing it as well on my side.
![image](https://user-images.githubusercontent.com/70192063/204798105-760df134-c70b-4616-a3c4-c8d32b486356.png)

**Comment by duytuan001** [comment]
It is solved when upgrading "react-native-svg" to "13.6.0".
But another error appeared:
`Invariant Violation: requireNativeComponent: "RNSVGSvgViewAndroid" was not found in the UIManager.`

**Comment by Ackerize** [comment]
@lianmetrobi It works, thank you.
@duytuan001  You should implement the solution: https://github.com/akveo/react-native-ui-kitten/issues/1675#issuecomment-1328165387

**Comment by koukoujohn** [comment]
@Ackerize you are making it sound as if this issue is solved. It's not solved, but it's a good temp solution until akveo updates ui-kitten with react-native-svg latest versions or whatever.

**Comment by manssorr** [comment]
> Just got this too, started happening after upgrading from expo 46 to 47, downgrading react-native-svg to 13.2.0 fixed it for me, although expo says it's not compatible with current version.

Thanks! that make it work perfectly!

**Comment by ngalande** [comment]
I also got this error after upgrading expo SDK to 47

**Comment by Codelica** [comment]
I'm afraid this is still an issue and with Expo 48 becomes even more complicated, as iOS won't build under EAS with react-native-svg @ 13.2.0.  Using 13.5.0+ will build, but won't help Expo Go.  So either Expo needs to update to 13.5.0+ or Kitten UI needs to be updated to work.

**Comment by lianaraujo** [comment]
had the same problem updating to expo 48, applied this patch on react-native-svg 13.4.0 and it worked, it looks a bit hacky, but I got his code from the newer versions of react-native-svg
```
diff --git a/node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/SvgView.java b/node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/SvgView.java
index 523fcc1..ad3c476 100644
--- a/node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/SvgView.java
+++ b/node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/SvgView.java
@@ -186,7 +186,7 @@ public class SvgView extends ReactViewGroup implements ReactCompoundView, ReactC
   }
 
   public void setTintColor(Integer tintColor) {
-    mTintColor = tintColor;
+    mTintColor = tintColor != null ? tintColor : 0;
     invalidate();
     clearChildCache();
   }
```

**Comment by vinodsptharsha** [comment]
I was also getting the same error. I was putting Text elements for accessories of the menu and buttons instead of Icon elements in some places (to show the number widget). I wrapped Text elements with <></> and the error is gone!

**Comment by bataevvlad** [comment]
@ekokotov 

Hi there! 

Can I ask you to show me which icon pack you are using? 

And also interested in styles property.

Regards, Vlad

**Comment by bataevvlad** [comment]
@ekokotov 

Hello there!

Due investigation i found that tintColor became null value on react-native-svg side

So there are two fixes for it right now: 

**Fix 1 (add <View> tag inside all UI Kitten icon tags):**

```
<TopNavigationAction
    icon={(
        <View>    // <-- Crash fix
            <YourCustomIconWrapper
                 height={24}
                 width={24}
                 icon="chevronLeft"
             />
        </View>    // <-- Crash fix
    )}
/>
```


**Fix 2 (setting the icon color prop to a value of a color):**

```
<YourCustomIconSvgImport 
    height={32} 
    width={32} 
    style={style}
    color="red" // <-- Crash fix
/>;
```

Thanks to [adrihegg](https://github.com/software-mansion/react-native-svg/issues/1899#issuecomment-1502899819)

**Comment by bataevvlad** [comment]
After investigate it was found that this problem occurs only on one version of the SVG package, we have previously described how to solve this problem using it, further SVG package has returned all the necessary checks to prevent this crash for our components, you can use a fresh version and all should be fine!

**Comment by Codelica** [comment]
Yes, version 13.5.0+ of the SVG lib will not error, but unfortunately Expo (and their Expo Go dev client) still hasn't been updated to that.  So the for now if people are developing using Expo and their Go client, they need to work around the error.  You could do build with the newer 13.5.0+ and ignore the Expo build warnings, but the Go client is sort of stuck currently.
