### ISSUE TITLE
`template-js` doesn't seem to work?

### ISSUE THREAD

**Issue by alpacc** [akveo/react-native-ui-kitten#1678]
I followed the simple new app instructions [in the docs](https://akveo.github.io/react-native-ui-kitten/docs/guides/getting-started#new-apps) but when I `run-android` I get the following error:

```
The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-29).
```

I tried changing the `targetSdkVersion` in build.gradle but then I got this error:  
```
* What went wrong:
Execution failed for task ':app:mergeDebugNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > More than one file was found with OS independent path 'lib/armeabi-v7a/libfbjni.so'. If you are using jniLibs and CMake IMPORTED targets, see https://developer.android.com/studio/preview/features#automatic_packaging_of_prebuilt_dependencies_used_by_cmake
```

I tried fixing that one for a while but this a self-contained template that should just work without any changes so I'm wondering what I could be doing wrong. Dependency versions should already be sorted out, right? 

I am new to react native and I don't see others talking about this so it seems like I am doing something obvious wrong but I can't figure out what it is.

Thank you in advance for any help you can provide!

**Comment by greenfrvr** [comment]
Please check latest version, we've updated templates. Feel free to re-open the issue if it will appear for 5.3.+ templates
