### ISSUE TITLE
vibration on Modal !?

### ISSUE THREAD

**Issue by pooryamd** [akveo/react-native-ui-kitten#1681]
## 💬 Question
I have a strange problem:
My modal code is like:

<Modal
        animationType="slide"
        transparent={true}
        visible={modal2Visible2}
        onBackdropPress={() => setModal2Visible(!modal2Visible)}
        backdropStyle={styles.backdrop}
		onRequestClose={() => {
          setModal2Visible(!modal2Visible);
        }}
      >	
<KeyboardAvoidingView      behavior={Platform.OS === "ios" ? "padding" : "height"}    >
<Animated.View style={{opacity: values, transform: [{ scaleY: values }], backgroundColor: "#ffefbf", borderRadius: 20, minWidth: 312}}> 
<ImageBackground    source={require('../../Image/honeycomb2.png')} resizeMode="repeat" style={styles.image}   imageStyle={{ borderRadius: 20}}>
        <View style={styles.centeredView}>
          <View style={styles.modalView}>
		///// other staf
          </View>
        </View>
</ImageBackground>
</Animated.View>
</KeyboardAvoidingView>
</Modal>  

and on some devices (Note 8, android 9), when I have {minWidth: 300} on my Animated.View, (or even as a simple View), I see a strange vibration (as little as a pixel!) in opened modal!
if I set it to my minWidth: 312 or 299 or 301, or anything except 300, It does not vibrate!

I upgraded and downgraded RN and UI Kitten and every thing. Nothing changes.

Why is this happening?

My current setup:
    "react-native": "0.70.5",
    "@eva-design/eva": "^2.1.1",
    "react-native-ui-kitten": "^4.4.1",
    "@ui-kitten/eva-icons": "^5.1.2",

**Comment by greenfrvr** [comment]
@pooryamd we've merged the fix for the issue, it will be delivered in next release. I'm closing it for now
