### ISSUE TITLE
Add textStyle to Button

### ISSUE THREAD

**Issue by obayit** [akveo/react-native-ui-kitten#1683]
## 🚀 Feature Proposal

Can we please have a way to apply a custom style to the button's text? This can come in handy in many cases.

## Motivation

I have a project which started with pure UI Kitten, but now I have a UI/UX design and I need to apply custom style to the text of a button.

**Comment by greenfrvr** [comment]
@obayit Hi! Can you please share some more context, regarding custom text style for a button component. If you have you're own design system you don't need to customize each component manually with the help of styles (which uses default eva design system), instead you can override mappings and themes to match your own design system. I think [this](https://akveo.github.io/react-native-ui-kitten/docs/design-system/customize-mapping#customize-component-mapping) and [this](https://akveo.github.io/react-native-ui-kitten/docs/guides/runtime-theming#register-theme) documentation sections may be helpful here.

**Comment by obayit** [comment]
A valuable solution is to provide a text element as child to the button
```js
      <Button>
        <Text style={rs.emphasizedText}>{label}</Text>
      </Button>
```

**Comment by c-goettert** [comment]
Please note that the solution provided by @obayit did only work for me after modifying it to a function. Also in order to not reset all default styles of the button, I had to pass those styles aswell like this:
```
      {({ style, ...props }) => (
        <Text {...props} style={[style, { fontWeight: 'normal' }]}>
          {I18n.t(`Relations.${option}`)}
        </Text>
      )}
```
