### ISSUE TITLE
React native UI Kitten causes slow start up in Android devices

### ISSUE THREAD

**Issue by Luatnd98** [akveo/react-native-ui-kitten#1688]
## 🐛 Bug Report

I noticed that when The ApplicationProvider tag is present, my react native app start up time increases to more than 10 seconds in Android devices. I've already followed the guide from UI-Kitten team by improving the performance through configuring the metro.config.js file but doesn't seem to help.

<ApplicationProvider {...eva} theme={{...eva.light, ...theme}}>
       <Text>{'Test'}</Text>
</ApplicationProvider>

## UI Kitten version
| @ui-kitten/components   |  5.1.2       |

**Comment by sergey-kozel** [comment]
@Luatnd98 could you please provide your project configuration? Also see please [this comment](https://github.com/akveo/react-native-ui-kitten/issues/1704#issuecomment-1485057814) if it is relevant to your case.
