### ISSUE TITLE
Small bug in autocomplete example in docs

### ISSUE THREAD

**Issue by amitchell-tbox** [akveo/react-native-ui-kitten#1689]
In the documentation for Autocomplete component, here:
https://akveo.github.io/react-native-ui-kitten/docs/components/autocomplete/examples#autocomplete

In the first example provided, line 47
setValue(movies[index].title);

That line of code should be changed to
setValue(data[index].title);

Because what happens is, user types into the autocomplete, data state gets updated to be a filtered down array, and then when you select an item, the index thats passed into the onSelect function, is an index of the data array, not of the original movies array, so the wrong item gets selected

To illustrate this, in the example given, type "B" into the autocomplete, and it will filter it down such that the only option given is "Back to the future", if you press that option, an index of 0 is passed into onSelect, and it selects movies[0], which is "Star wars", which is not the intended choice

**Comment by greenfrvr** [comment]
@amitchell-tbox thanks for reporting. I think this one was fixed withing #1632 PR. closing it for now
