### ISSUE TITLE
I'm geting this error in handleDelete as well as handleShare

### ISSUE THREAD

**Issue by rituraj421** [akveo/react-native-ui-kitten#1692]
Module parse failed: Unexpected token (263:22)
You may need an appropriate loader to handle this file type.
|         columnNumber: 53
|       }
>     }, "Share"), User?.result?._id === question?.userId && /*#__PURE__*/React.createElement("button", {
|       type: "button",
|       onClick: handleDelete,

**Comment by greenfrvr** [comment]
@rituraj421 could you please share more context, currently it's not clear how it is related to ui kitten. it would be great if you could share what component are struggling with and maybe some context where it is used

**Comment by rituraj421** [comment]
@greenfrvr  the issue has been solved now (btw it's not related to UI kitten), thanks for your quick response.
