### ISSUE TITLE
 ERROR  TypeError: undefined is not an object (evaluating '_StyleSheet$flatten.height')

### ISSUE THREAD

**Issue by njoromyke** [akveo/react-native-ui-kitten#1696]
![Screenshot from 2022-12-27 12-26-35](https://user-images.githubusercontent.com/56773318/209644763-4e8f342f-8c80-43aa-a497-6be65dc8186e.png)
![Screenshot from 2022-12-27 12-26-28](https://user-images.githubusercontent.com/56773318/209644774-c648f1de-4d69-4ad7-aa97-aa09e65ef443.png)

**Comment by njoromyke** [comment]
Getting above error when I try to add expo icons using UI kitten.

**Comment by greenfrvr** [comment]
@njoromyke the problem is located in `FeatherIcon` function. I think the case is you're flattening `undefined` value which returns `undefined` and then trying to destruture it. Could you please check it?

**Comment by njoromyke** [comment]
Copied same example as in your documentation

**Comment by greenfrvr** [comment]
I believe main goal of the example from documentation is to explain how to use 3rd party icons. Implementation from example works fine in case `style` prop is defined and has all fields which are extracted during destructuring. So there are 2 basic options: adjust your own implementation, for example to have some fallback styles in case `style` props is `undefined` or always pass required `style` prop for each `Icon` component usage.
