### ISSUE TITLE
Centering of support icons

### ISSUE THREAD

**Issue by Hum4n01d** [akveo/react-native-ui-kitten#17]
As you can see here, the text descriptions would look much more aesthetic if they were aligned with the image.

![screen shot 2017-06-29 at 5 02 37 pm](https://user-images.githubusercontent.com/17228477/27715530-cfc37f88-5cec-11e7-99e8-a4d434bc7e0d.png)

If you disagree, no worries :) Looks like a really cool project!

**Comment by Hum4n01d** [comment]
After poking around a bit I was able to remove the `position: absolute` from the images and come up with this:

![screen shot 2017-06-29 at 5 09 24 pm](https://user-images.githubusercontent.com/17228477/27715703-cfb6721a-5ced-11e7-9feb-fee38605a2ef.png)

**Comment by nnixaa** [comment]
Thanks @Hum4n01d  for the bug report, this's been fixed!

**Comment by Hum4n01d** [comment]
Sure thing!
