### ISSUE TITLE
How to clear select?

### ISSUE THREAD

**Issue by Asinox** [akveo/react-native-ui-kitten#1700]
## 💬 Question
Hello there, Im having an issue trying to clear the select/s using the `clear()` method, but after call the method, I got some error:
`null is not a object (evaluating selectedSectorIndex.row)`

A bit of code:

`let sectorRef = useRef();`
`sectorRef.current.clear();`
`<Select ref={sectorRef} ...>
</Select>
`

How I can clear the `select` without any error?

Thank you!

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   ^2.1.1     |
| @ui-kitten/components   |    ^5.1.2     |

**Comment by greenfrvr** [comment]
@Asinox could you please share other props that you're passing. mostly interested in `selectedIndex` and `onSelect` props

**Comment by Asinox** [comment]
Sure, thank you for you reply

`let sectorRef = useRef();`

`let [selectedSectorIndex, setSelectedSectorIndex] = useState(
    new IndexPath(0),
  );`

`<Select  ref={sectorRef}
                    placeholder="Pick a sector"
                    selectedIndex={selectedSectorIndex}
                    value={displaySectorName}
                    onSelect={index => {
                      setSelectedSectorIndex(index);
                    }}>
                    {updatedSector.map(doc => {
                          return (
                            <SelectItem
                              title={doc.name}
                              key={doc.slug}
                              value={doc}
                            />
                          );
                      })}
                  </Select>`

I just cant clear it without any error after call clear() method.
