### ISSUE TITLE
Set new font family not works

### ISSUE THREAD

**Issue by adam-lages** [akveo/react-native-ui-kitten#1702]
## 💬 Question dsdsd
 
 
Goodnight!
I'm trying to set up a new font, but it's not loading! I can set "font size" and "font weight" but the font stays the same.

I followed a video as an example, it seems to be very simple... it still doesn't work.
**time**: 18:50
https://www.youtube.com/watch?v=S8DHAEy22Jo

Please help me! I've looked all over the forum and haven't found a solution. thanks

<br /><br /><br />

<img width="650" alt="image" src="https://user-images.githubusercontent.com/44977396/211460954-a04138d5-247e-4843-a15c-6b408c83af6a.png">
 
<img width="247" alt="image" src="https://user-images.githubusercontent.com/44977396/211461043-1f0eae1c-aa14-4c6a-bdbb-df9c52f8efc5.png">
 
<img width="658" alt="image" src="https://user-images.githubusercontent.com/44977396/211461935-99d4274c-1ed9-4e2e-859a-1c233548b130.png">

<img width="687" alt="image" src="https://user-images.githubusercontent.com/44977396/211461849-97881351-ae53-4e32-8b34-776a9063dbe1.png">

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |  ^2.1.1    |
| @ui-kitten/components   |   ^5.1.2    |

**Comment by greenfrvr** [comment]
@adam-lages could you please check [typography](https://akveo.github.io/react-native-ui-kitten/docs/guides/branding#typography) section in our docs, just to make sure you've added font resources correctly.

**Comment by adam-lages** [comment]
> @adam-lagesvocê poderia verificar a seção de [tipografia](https://akveo.github.io/react-native-ui-kitten/docs/guides/branding#typography) em nossos documentos, apenas para ter certeza de que adicionou os recursos de fonte corretamente.

Thanks for the answer :)
I have already tried this procedure but without success.
I also ran "npx react-native link" before running "npm run android" and it doesn't work.
<br />

<img width="525" alt="image" src="https://user-images.githubusercontent.com/44977396/211559441-0c47ed9c-4e57-4b78-a541-61f5da689fdf.png">

<img width="480" alt="image" src="https://user-images.githubusercontent.com/44977396/211559530-9545fd4a-61ab-4705-a507-e8b17d9fdc17.png">

<img width="718" alt="image" src="https://user-images.githubusercontent.com/44977396/211559601-a9120b19-ca75-4f33-8926-9c8a5a8db2cf.png">


<br /><br />
Am I downloading the wrong (ttf) font? I chose 100, 400, 600 and 800!
After downloading, I renamed it and pasted it into the project.

<img width="218" alt="image" src="https://user-images.githubusercontent.com/44977396/211560965-8d52c41f-f9e4-4f7d-ad17-806106a5ac5e.png">

<img width="1385" alt="image" src="https://user-images.githubusercontent.com/44977396/211560395-9493e038-5d2a-4f48-a3da-9196194820af.png">

**Comment by adam-lages** [comment]
hello!
Can help me?
