### ISSUE TITLE
Blank screen RN 0.71

### ISSUE THREAD

**Issue by chemiadel** [akveo/react-native-ui-kitten#1704]
I'm having blank screen using UI kitten with latest RN version 0.71 

[screenshot](https://user-images.githubusercontent.com/26901572/212431709-b30f32d8-21ae-48b5-a5d9-f7d511b7d35f.jpg
)

**Comment by 0xTux** [comment]
I'm also having the same issue

**Comment by chemiadel** [comment]
> For me, It was blank at first but it took some time, and the content rendered.
> 
> ```
> Note: Video speed is 10X. It took almost 2 minutes for the content to show up.
> ```
> 
>  Render.mp4

Exactly the same

**Comment by rohanprasadofficial** [comment]
Facing the same issue. Render takes almost 2 minutes to complete.

**Comment by greenfrvr** [comment]
@rohanprasadofficial @chemiadel @0xTux does the issue appear only on Android? or both platforms?

**Comment by 0xTux** [comment]
> @rohanprasadofficial @chemiadel @0xTux does the issue appear only on Android? or both platforms?

Unfortunately, I don't have any IOS devices to test around.

**Comment by franka107** [comment]
i'm have the same problem

**Comment by sergey-kozel** [comment]
Is it with the Hermes engine? If yes, there was [a certain performance issue](https://github.com/facebook/react-native/issues/35828) in 0.71.0. And it seems like it remains to some extent even after the supposed fix in 0.71.1. So theme generating on application start takes about 10 times longer than on versions of react-native < 0.71 (it took ~4s for me on 0.71.4). Although I am not sure about the exact reasons of such performance degradation yet, this can be avoided with [compile-time theme generation](https://akveo.github.io/react-native-ui-kitten/docs/guides/improving-performance#improving-performance) feature.
