### ISSUE TITLE
Calendar on new year

### ISSUE THREAD

**Issue by MarkoCelovsky** [akveo/react-native-ui-kitten#1706]
## Hey everyone
On the brink of the end of the last year I've been working on my app and using DatePicker but what I found was that I've been unable to go to January and select a day in the new year, what can I do so that users can open the calendar and pick a date from whatever year

## thanks for answers 

`@ui-kitten`

**Comment by silentsilas** [comment]
Hey @MarkoCelovsky ! Not part of the team, but you should be able to set the `max` property in the `DatePicker` to resolve this. Just set it to a date as far into the future you'd like your users to be able to choose from. The same goes from `min` if you find you can't choose a year in the past.

**Comment by bataevvlad** [comment]
@silentsilas thank for reply! yes you right, u need to handle min and max for DatePicker component.
