### ISSUE TITLE
Tried to register two views with the same name RNSVGRect

### ISSUE THREAD

**Issue by MinChanSike** [akveo/react-native-ui-kitten#1708]
Package conflict issue with  ```react-native-svg``` from ```@ui-kitten/eva-icons``` and ```react-native-gifted-charts```

> Invariant Violation: Tried to register two views with the same name RNSVGRect, js engine: hermes
 

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      | 2.1.1      |
| @ui-kitten/eva-icons      | 5.1.2     |
| @ui-kitten/components   | 5.1.2        |

## Other dependency version
| Package      | Version |
| ----------- | ----------- |
| react-native-gifted-charts      | 1.2.42      |
| react-native-svg                      | 13.4.0     |
| expo                      | 48.0.6     |

**Comment by bataevvlad** [comment]
@MinChanSike 

This problem is related to [react-native-eva-icon](https://github.com/artyorsh/react-native-eva-icons), currently working on a fix.

https://github.com/artyorsh/react-native-eva-icons/issues/45

**Comment by Trapintrovert** [comment]
Fixed yet?
