### ISSUE TITLE
specifying parentTypes ignores 'content' styles

### ISSUE THREAD

**Issue by Johan-dutoit** [akveo/react-native-ui-kitten#171]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description
When specifying a parent type to my RkButton, then 'content' (and probably other) styles are not applied successfully.

**Current behavior:**
Styles are ignored

**Expected behavior:**
Styles not to be ignored

**Steps to reproduce:**
```

 RkTheme.setType(
    'RkButton',
    'styleA',
    {
      height: 50,
      width: 200,
      //...
    }
  );


 RkTheme.setType(
    'RkButton',
    'styleB',
    {
      content: { 
        color: theme => theme.colors.randomColor,
      }
    },
    'styleA'
  );
```

### Other information:

**OS, device, package version**
```
 "react-native": "0.57.1",
 "react-native-ui-kitten": "3.1.2",
```

**Comment by Johan-dutoit** [comment]
FWIW I've tried multiple combinations.  i.e. both styles have "content", etc.

**Comment by malashkevich** [comment]
Hi @Johan-dutoit 
Thanks for contributing!
We are working on the new version which will be completely redesigned. So it makes sense to close this issue as we don't have plans to support this version of lib.
