### ISSUE TITLE
Icon not working on Expo 48 android

### ISSUE THREAD

**Issue by abhisin98** [akveo/react-native-ui-kitten#1718]
## Link to runnable example or repository (highly encouraged)
[https://github.com/abhisin98/ui-icon](https://github.com/abhisin98/ui-icon)

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2.2.0    |
| @ui-kitten/components   |    5.3.0     |
| @ui-kitten/eva-icons   |    5.3.0     |

## Environment information
Node: 18.15.0
npm: 9.5.0

```bash

```

**Comment by abhisin98** [comment]
I solved this problem by editing the file `node_modules/@ui-kitten/eva-icons/evaIcon.component.js`

```typescript
diff --git a/node_modules/@ui-kitten/eva-icons/evaIcon.component.js b/node_modules/@ui-kitten/eva-icons/evaIcon.component.js
index b382042..f68ee7d 100644
--- a/node_modules/@ui-kitten/eva-icons/evaIcon.component.js
+++ b/node_modules/@ui-kitten/eva-icons/evaIcon.component.js
@@ -15,8 +15,8 @@ class EvaIcon {
         const Icon = this.content;
         const { style, ...svgProps } = props;
         // @ts-ignore - UI Kitten components pass here `tintColor`
-        const fillColor = react_native_1.StyleSheet.flatten(style || {}).tintColor;
-        return (<Icon style={props.style} fill={fillColor} {...svgProps}/>);
+        const  {tintColor, ...rest} = react_native_1.StyleSheet.flatten(style || {})
+        return (<Icon style={rest} fill={tintColor} {...svgProps}/>);
     }
 }
 exports.EvaIcon = EvaIcon;

```

**Comment by dembal1990** [comment]
That is still problem for me.  Did you make a pull request for that fix ? @abhisin98
