### ISSUE TITLE
Center align text in button 

### ISSUE THREAD

**Issue by Geperson** [akveo/react-native-ui-kitten#1730]
Could you please provide an example: how to align long (multiply rows ) text in button by horizontal? I've tried to provide style={{textAlign: 'center'}} to button and to entire <Text> but it not works. 

```
<Button style={{textAlign: 'center'}} size='large' onPress={() => this.correctionsMade()}>
<Text style={{textAlign: 'center'}}>TITLE</Text>
</Button>
```

**Comment by bataevvlad** [comment]
Hello there @Geperson !

You can check our [example codes](https://akveo.github.io/react-native-ui-kitten/docs/components/button/overview#button) !

You also can use without 
`<Text style={{textAlign: 'center'}}>TITLE</Text>`

Like so: 

` <Button>L</Button>`
