### ISSUE TITLE
Change Dark/Light main color

### ISSUE THREAD

**Issue by harisriss** [akveo/react-native-ui-kitten#1731]
Hi everyone !!

Actually i try to custom UI Kitten and change the main background color of the dark and the light theme, but i can not find how to do it in the doc. How can do that ? (I have seen that there  is a `theme.js` file to edit in order to custom the colors of my app but i don't find which property should i edit for the background. If some can provide me this file with all the editable property, it will help me a lot, if the background color is editable in this file)

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |2.1.1|
| @ui-kitten/components   |5.1.2|

**Comment by bataevvlad** [comment]
Hello @harisriss 

You can look through this[link](https://akveo.github.io/react-native-ui-kitten/docs/components/application-provider/overview#applicationprovider)

There you can find how themes can be used, and you can create custom switcher for it or regarding your conditions.

gl&hf.
