### ISSUE TITLE
Button: unsupported configuration.

### ISSUE THREAD

**Issue by RenatoSerra22** [akveo/react-native-ui-kitten#1732]
## 🐛 Bug Report

I keep getting this error suddenly on button and input

```
Button: unsupported configuration.
Check one of the following prop values: {
  "appearance": "filled",
  "variants": [
    "primary"
  ],
  "states": []
}
```

    "@ui-kitten/components": "5.1.2",
    "@ui-kitten/eva-icons": "5.1.2",
    "@ui-kitten/metro-config": "5.1.2",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.2",

I've tried clearing all caches and re-installing all libs but still getting this warning

**Comment by greenfrvr** [comment]
Could you please share code snippet with `ApplicationProvider`? And probably JSX with the place where you're using `Button` component?

**Comment by bataevvlad** [comment]
@RenatoSerra22 Hello there!

You can use our docs for creation of customized mappings here the [link](https://akveo.github.io/react-native-ui-kitten/docs/design-system/customize-mapping#customize-component-mapping)
