### ISSUE TITLE
TypeError: Cannot read property 'appearances' of undefined

### ISSUE THREAD

**Issue by Under-Warz** [akveo/react-native-ui-kitten#1739]
## 🐛 Bug Report

I'm trying to update the lib from `5.1.2` to `5.3.1` to use the new `<CircularProgressBar />` component but I'm facing an error when I want to use it : `TypeError: Cannot read property 'appearances' of undefined`

I already check the other issue with the same error and I'm already using the `<ApplicationProvider />` in the main app file.

```
const App = () => (
  <ApplicationProvider {...eva} theme={{ ...eva.dark, ...theme }}>
    <RootNavigator />
  </ApplicationProvider>
);
```

and here is my custom theme file 

```
{
  "background-basic-color-1": "#263155"
}
```

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    5.3.1    |
| @ui-kitten/components   |    5.3.1     |

## Environment information

```bash
  System:
    OS: macOS 13.3.1
    CPU: (10) x64 Apple M1 Pro
  Binaries:
    Node: 16.13.2 - ~/.nodenv/versions/16.13.2/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.2 - ~/.nodenv/versions/16.13.2/bin/npm
    Watchman: 2021.10.18.00 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      API Levels: 27, 28, 29, 30, 31, 33
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0, 34.0.0
      System Images: android-30 | AOSP ATD ARM 64 v8a, android-30 | Google Play Intel x86 Atom, android-31 | Google APIs ARM 64 v8a
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9514443
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  npmPackages:
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.5 => 0.70.5
```

**Comment by felipesuazo** [comment]
Same here. Is not working in mobile

**Comment by vins13pattar** [comment]
Anyone able to solve this issue?

**Comment by bataevvlad** [comment]
Hi @Under-Warz 

Could you please provide your code example with **CircularProgressBar** where you catch such issue?

Regards, 
Vlad

**Comment by think-divergent** [comment]
For anyone upgrading from 5.1.x, you'd also have to upgrade the @eva-design/eva package. 
Make sure you have `"@eva-design/eva": "^2.2.0",` or higher in your package.json

**Comment by bataevvlad** [comment]
@think-divergent thanks for such point! We will add right now this info for update info!

**Comment by felipesuazo** [comment]
> This issue is due to missing CircularProgressBar definitions in mappings.json. For anyone upgrading from 5.1.x, you'd also have to upgrade the @eva-design/eva package. Make sure you have `"@eva-design/eva": "^2.2.0",` or higher in your package.json.

Thank you!
