### ISSUE TITLE
rkPicker is not working properly. 

### ISSUE THREAD

**Issue by Lucasyc** [akveo/react-native-ui-kitten#175]
I saw there was a similar problem. 
I also got an error when using RKPicker with the example on the document web. 
I looked into the code a little bit and it turns out that in 'rkOption.js' and 'rkOptionList.js', 
The `compareOptions` function doesn't check whether 'option1' and 'option2' are undefined before accessing the 'key'. 
I change that from 
`compareOptions(option1, option2) {
    return (option1.key && option2.key && option1.key === option2.key)
      || (!option1.key && !option2.key && option1 === option2);
  }
`
into 
` compareOptions(option1, option2) {
    return (option1 && option2 && option1.key && option2.key && option1.key === option2.key)
      || (option1 && option2 && !option1.key && !option2.key && option1 === option2);
  }`
and then it works.

**Comment by artyorsh** [comment]
Hi @Lucasyc 
Thanks for your report and investigation!
Feel free to open PR and become a contributor :)

**Comment by eathentica** [comment]
> I saw there was a similar problem.
> I also got an error when using RKPicker with the example on the document web.
> I looked into the code a little bit and it turns out that in 'rkOption.js' and 'rkOptionList.js',
> The `compareOptions` function doesn't check whether 'option1' and 'option2' are undefined before accessing the 'key'.
> I change that from
> `compareOptions(option1, option2) { return (option1.key && option2.key && option1.key === option2.key) || (!option1.key && !option2.key && option1 === option2); } `
> into
> ` compareOptions(option1, option2) { return (option1 && option2 && option1.key && option2.key && option1.key === option2.key) || (option1 && option2 && !option1.key && !option2.key && option1 === option2); }`
> and then it works.

Thank you for sharing!

**Comment by jamalabo1** [comment]
any updates? same error here.

**Comment by leitooop** [comment]
Solved Thank you @Lucasyc

**Comment by artyorsh** [comment]
This stays actual for v3.*
Check out the brand new v4 update!
