### ISSUE TITLE
RkTabView in example --> Tab set does not work

### ISSUE THREAD

**Issue by eathentica** [akveo/react-native-ui-kitten#178]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x ] bug report
* [ ] feature request

### Issue description

**Current behavior:**
I downloaded the latest react-native-ui-kitten, stripped expo and built the example with normal react-native run-android. Everything works fine, except the tabs Calendars and Tab Set. 

If I click on one of the three tabs "Base", "Badge" or "Icon", the app will crashed immediately.

Invariant Violation: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `IconTabScreen`.

This error is located at:
    in RCTView (at View.js:44)
    in IconTabScreen (at SceneView.js:9)
    in SceneView (at StackViewLayout.js:478)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in AnimatedComponent (at screens.native.js:58)
    in Screen (at StackViewCard.js:42)
    in Card (at createPointerEventsContainer.js:26)
    in Container (at StackViewLayout.js:507)
    in RCTView (at View.js:44)
    in ScreenContainer (at StackViewLayout.js:401)
    in RCTView (at View.js:44)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.js:49)
    in RCTView (at View.js:44)
    in Transitioner (at StackView.js:19)
    in StackView (at createNavigator.js:57)
    in Navigator (at createKeyboardAwareNavigator.js:11)
    in KeyboardAwareNavigator (at createNavigationContainer.js:376)
    in NavigationContainer (at App.js:88)
    in RCTView (at View.js:44)
    in App (at renderApplication.js:34)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in AppContainer (at renderApplication.js:33)

This error is located at:
    in NavigationContainer (at App.js:88)
    in RCTView (at View.js:44)
    in App (at renderApplication.js:34)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in AppContainer (at renderApplication.js:33)
createFiberFromElement
    ReactNativeRenderer-dev.js:5691:10
reconcileSingleElement
    ReactNativeRenderer-dev.js:9824:8
reconcileChildFibers
    ReactNativeRenderer-dev.js:9908:14
reconcileChildren
    ReactNativeRenderer-dev.js:10422:6
updateHostComponent
    ReactNativeRenderer-dev.js:10936:4
beginWork
    ReactNativeRenderer-dev.js:11615:8
performUnitOfWork
    ReactNativeRenderer-dev.js:14357:21
workLoop
    ReactNativeRenderer-dev.js:14395:41
renderRoot
    ReactNativeRenderer-dev.js:14492:15
performWorkOnRoot
    ReactNativeRenderer-dev.js:15450:17
performWork
    ReactNativeRenderer-dev.js:15347:24
performSyncWork
    ReactNativeRenderer-dev.js:15304:14
batchedUpdates$1
    ReactNativeRenderer-dev.js:15572:21
batchedUpdates
    ReactNativeRenderer-dev.js:2675:31
_receiveRootNodeIDEvent
    ReactNativeRenderer-dev.js:2770:17
receiveTouches
    ReactNativeRenderer-dev.js:2846:28
__callFunction
    MessageQueue.js:349:47
<unknown>
    MessageQueue.js:106:26
__guard
    MessageQueue.js:297:10
callFunctionReturnFlushedQueue
    MessageQueue.js:105:17

**Expected behavior:**
No Bug please. I would fix it myself if I could

**Steps to reproduce:**
I downloaded the latest react-native-ui-kitten, stripped expo and built the example with normal react-native run-android. Everything works fine, except the tabs Calendars and Tab Set. 

If I click on one of the three tabs "Base", "Badge" or "Icon", the app will crashed immediately.

**Related code:**
It is your example.

### Other information:

**OS, device, package version**
Android - Emulator
{
  "name": "Example",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "prop-types": "^15.6.2",
    "react": "16.6.0-alpha.8af6728",
    "react-native": "0.57.4",
    "react-native-ui-kitten": "^3.1.2",
    "react-native-vector-icons": "^6.0.2",
    "react-navigation": "^2.18.2"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.49.0",
    "react-test-renderer": "16.6.0-alpha.8af6728"
  },
  "jest": {
    "preset": "react-native"
  }
}

buildscript {
    ext {
        buildToolsVersion = "27.0.3"
        minSdkVersion = 16
        compileSdkVersion = 27
        targetSdkVersion = 26
        supportLibVersion = "27.1.1"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.4'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

**Comment by artyorsh** [comment]
Hi @eathentica,
Your problem is that you make it run `with normal react-native run-android`
If you clone this repo and try running demo app you should use `npm run start-dev` from `./example` dir. As you see, example app depends on latest released to npm version of framework, which doesn't contain sources of some components. The script I described above will fetch it, as it is described in [doc](https://github.com/akveo/react-native-ui-kitten/tree/master/example#npm-start-dev)
Happy coding :)

**Comment by eathentica** [comment]
Hi @artyorsh ,

Thank you for your quick reply. 

Actually I have exactly the same problem with my Android App ([https://play.google.com/store/apps/details?id=com.eathentica] )

I have used RkTabView before. It has been working fine, until I had to fix my app to confirm with the new Google requirement [https://developer.android.com/distribute/best-practices/develop/target-sdk].

I just add your example code from your documentation page:

let renderTab = (isSelected, title, icon) => {
 let backgroundColor = isSelected ? 'cornflowerblue' : 'white';
 let color = (!isSelected) ? 'cornflowerblue' : 'white';
 return (
   <View
     style={{
       backgroundColor,
       justifyContent: 'center',
       flexDirection: 'row',
       alignItems: 'center',
       padding: 17,
     }}>
     <Icon name={icon} style={{color, fontSize: 16}}/>
     <RkText style={{color, marginLeft: 11}}>{title}</RkText>
   </View>);
};

//...

<RkTabView>
  <RkTabView.Tab title={(selected) => {
     return renderTab(selected, 'Bus', 'ios-bus');
   }}>
    <Text>Bus</Text>
  </RkTabView.Tab>

  <RkTabView.Tab title={(selected) => {
     return renderTab(selected, 'Train', 'ios-train');
  }}>
    <Text>Train</Text>
  </RkTabView.Tab>
  <RkTabView.Tab title={(selected) => {
     return renderTab(selected, 'Plain', 'ios-plane');
   }}>
    <Text>Plain</Text>
  </RkTabView.Tab>
</RkTabView>

And it crashed right at the front!

It is no problem on iOS. 

My project have a different build script:
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        minSdkVersion       = 16
        compileSdkVersion   = 26
        targetSdkVersion    = 26
        buildToolsVersion   = "26.0.2"
        supportLibVersion   = "26.1.0"
        googlePlayServicesVersion   = "11.8.0"
        androidMapsUtilsVersion     = "0.5+"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}


task wrapper(type: Wrapper) {
    gradleVersion = '4.4'
    distributionUrl = distributionUrl.replace("bin", "all")
}


Every other elements are working fine, except the tabs.

Best regards,
Eathentica
[https://www.eathentica.com]

**Comment by eathentica** [comment]
Hi @artyorsh ,

Sorry, but you can now close the issue ;). It had something to do with the <Text /> element, which does not allow empty space on Android ;(. It is just so weird, that it crashed as I added RkTabView. I had deleted everything and went step by step to find the issue. 

Thank you
[https://www.eathentica.com](Eathentica)
