### ISSUE TITLE
Can't find variable: React

### ISSUE THREAD

**Issue by Usman4358** [akveo/react-native-ui-kitten#1786]
I am using React Native version 0.68.2 and React version 17.0.2. When I run the app, it crashes with the error "Can't find variable React." When I comment out the library imports, the app works smoothly. I don't know what the issue is; I have configured everything according to the documentation.

**Comment by CrashHunter** [comment]
the same to me 
my "react-native": "0.63.3",

**Comment by Usman4358** [comment]
This is actually version issue. Install the library version that is compatible with React Native 0.63.3.

**Comment by Usman4358** [comment]
The issue has been resolved by installing compatible version of the library.

**Comment by vcankur** [comment]
Getting same issue

**Comment by ghousesaqlain** [comment]
Still facing the issue with
"react": "^18.2.0",
"react-native": "^0.72.4",
"@eva-design/eva": "2.2.0",
"@ui-kitten/components": "5.3.1",
"@ui-kitten/eva-icons": "5.3.2",

Anyone have fix for this error?
