### ISSUE TITLE
Select option inner radius issue

### ISSUE THREAD

**Issue by prakhargvp** [akveo/react-native-ui-kitten#1804]
## 🐛 Bug Report

I'm not getting why select inner container have border radius and how can i remove that.

![CleanShot 2024-02-24 at 17 30 28](https://github.com/akveo/react-native-ui-kitten/assets/7056772/79e819f6-1884-439b-a533-f1253088b0a9)

![CleanShot 2024-02-24 at 17 29 41@2x](https://github.com/akveo/react-native-ui-kitten/assets/7056772/5e17c87c-9c49-4750-b563-7b2c5baa3c96)

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   ^5.1.2     |
| @ui-kitten/components   |     ^5.1.2    |

## Environment information

```bash

```

**Comment by kdgreen398** [comment]
did you find any solution to this?
