### ISSUE TITLE
How to change fonts?

### ISSUE THREAD

**Issue by itsgratien** [akveo/react-native-ui-kitten#1814]
Hello,

I would like to ask how to change fonts? I tried to follow the documentation using mapping but seems fonts aren't changing. 
any suggestion would be appreciated.

Thanks

**Comment by Bill-Niz** [comment]
Same here, i'm using expo

**Comment by danya0365** [comment]
```
<ApplicationProvider customMapping={{  "strict": {
    "text-font-family": "Sarabun_400Regular"
  },}}>
 <Text>Hello world</Text>
</ApplicationProvider>
```

**Comment by itsgratien** [comment]
> Config with customMapping param
> 
> ```
> import { default as appMapping } from "@/constants/app-mapping-eva.json";
> import { ApplicationProvider } from "@ui-kitten/components";
> import * as eva from "@eva-design/eva";
> 
> <ApplicationProvider 
>    {...eva}
>    theme={eva.dark} 
>    customMapping={appMapping as any}>
>  <Text>Hello world</Text>
> </ApplicationProvider>
> ```
> 
> for `app-mapping-eva.json`
> 
> ```
> {
>   "__comment__": "node_modules/@eva-design/eva/mapping.json",
>   "strict": {
>     "text-font-family": "Sarabun_400Regular"
>   }
> }
> ```

Thank you.
