### ISSUE TITLE
expo 52 use Icon property 'name' of undefined

### ISSUE THREAD

**Issue by wangmiJM** [akveo/react-native-ui-kitten#1842]
## 🐛 Bug Report

(NOBRIDGE) ERROR  Warning: TypeError: Cannot read property 'name' of undefined

This error is located at:
    in Icon (created by renderShakeIcon)
    in renderShakeIcon (created by FalsyFC)
    in FalsyFC (created by Button)
    in RCTView (created by View)
    in View (created by CssInterop.View)
    in CssInterop.View (created by Animated(View))
    in Animated(View) (created by TouchableOpacity)
    in TouchableOpacity (created by TouchableOpacity)
    in TouchableOpacity (created by CssInterop.TouchableOpacity)
    in CssInterop.TouchableOpacity (created by TouchableWithoutFeedback)
    in TouchableWithoutFeedback (created by TouchableWeb)
    in TouchableWeb (created by Button)
    in Button
    in Wrapper (created by Button)
    in WrappingElement (created by LoginScreen)
    in RCTView (created by View)
    in View (created by CssInterop.View)
    in CssInterop.View (created by Card)
    in RCTView (created by View)
    in View (created by CssInterop.View)
    in CssInterop.View (created by Animated(View))
    in Animated(View) (created by TouchableOpacity)
    in TouchableOpacity (created by TouchableOpacity)
    in TouchableOpacity (created by CssInterop.TouchableOpacity)
    in CssInterop.TouchableOpacity (created by TouchableWithoutFeedback)
    in TouchableWithoutFeedback (created by TouchableWeb)
    in TouchableWeb (created by Card)
    in Card
    in Wrapper (created by Card)
    in WrappingElement (created by LoginScreen)
    in RCTView (created by View)
    in View (created by CssInterop.View)
    in CssInterop.View (created by Layout)
    in Layout
    in Wrapper (created by Layout)
    in WrappingElement (created by LoginScreen)
    in LoginScreen
    in Unknown (created by Route(index))
    in Suspense (created by Route(index))
    in Route (created by Route(index))
    in Route(index) (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by NativeStackNavigator)
    in RNSScreenContentWrapper (created by ScreenContentWrapper)
    in ScreenContentWrapper (created by DebugContainer)
    in DebugContainer
    in RNSScreen (created by Animated(Anonymous))
    in Animated(Anonymous)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze
    in InnerScreen (created by Screen)
    in Screen
    in ScreenStackItem (created by SceneView)
    in SceneView (created by NativeStackView)
    in RNSScreenStack (created by ScreenStack)
    in Unknown (created by ScreenStack)
    in ScreenStack (created by NativeStackView)
    in RCTView (created by View)
    in View (created by SafeAreaProviderCompat)
    in SafeAreaProviderCompat (created by NativeStackView)
    in NativeStackView (created by NativeStackNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by NativeStackNavigator)
    in NativeStackNavigator
    in Unknown (created by RootLayoutNav)
    in ThemeProvider (created by RootLayoutNav)
    in ThemeProvider (created by StyleProvider)
    in MappingProvider (created by StyleProvider)
    in StyleProvider (created by ApplicationProvider)
    in ApplicationProvider (created by RootLayoutNav)
    in RootLayoutNav (created by RootLayout)
    in RootLayout
    in Try
    in Unknown
    in Unknown (created by Route())
    in Suspense (created by Route())
    in Route (created by Route())
    in Route() (created by ContextNavigator)
    in SafeAreaEnv (created by SafeAreaProviderShim)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by SafeAreaProviderShim)
    in SafeAreaProviderShim (created by wrapper)
    in wrapper (created by ContextNavigator)
    in ThemeProvider
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in NavigationContainerInner (created by ContextNavigator)
    in ContextNavigator (created by ExpoRoot)
    in ExpoRoot (created by App)
    in App (created by ErrorOverlay)
    in ErrorToastContainer (created by ErrorOverlay)
    in ErrorOverlay (created by withDevTools(ErrorOverlay))
    in withDevTools(ErrorOverlay)
    in RCTView (created by View)
    in View (created by CssInterop.View)
    in CssInterop.View (created by AppContainer)
    in RCTView (created by View)
    in View (created by CssInterop.View)
    in CssInterop.View (created by AppContainer)
    in AppContainer
    in main(RootComponent)

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |        |
| @ui-kitten/components   |         |

## Environment information
   "@eva-design/eva": "^2.2.0",
    "@expo/vector-icons": "^14.0.2",
    "@react-navigation/bottom-tabs": "^7.2.0",
    "@react-navigation/elements": "^2.2.5",
    "@react-navigation/native": "^7.0.14",
    "@ui-kitten/components": "^5.3.1",
    "@ui-kitten/eva-icons": "^5.3.1",
    "expo": "~52.0.23",
    "expo-blur": "~14.0.1",
    "expo-constants": "~17.0.3",
    "expo-font": "~13.0.2",
    "expo-haptics": "~14.0.0",
    "expo-linking": "~7.0.3",
    "expo-router": "~4.0.15",
    "expo-splash-screen": "~0.29.18",
    "expo-status-bar": "~2.0.0",
    "expo-symbols": "~0.2.0",
    "expo-system-ui": "~4.0.6",
    "expo-web-browser": "~14.0.1",
    "nativewind": "^4.1.23",
    "react": "18.3.1",
    "react-dom": "18.3.1",
    "react-native": "0.76.5",
    "react-native-gesture-handler": "~2.20.2",
    "react-native-reanimated": "~3.16.1",
    "react-native-safe-area-context": "4.12.0",
    "react-native-screens": "~4.4.0",
    "react-native-svg": "15.8.0",
    "react-native-web": "~0.19.13",
    "react-native-webview": "13.12.5"

```bash

```

**Comment by mregan59** [comment]
I'm running into something similar. Do you mind sharing what your solution was?
