### ISSUE TITLE
What is the easiest way to Run this?

### ISSUE THREAD

**Issue by ngethe** [akveo/react-native-ui-kitten#188]
Hi I am a beginner with react native please guide on the easiest way to execute this.

I have set up the environment but get the default message for an APP 
please guide on the steps to make.

Regards

**Comment by artyorsh** [comment]
Hi @ngethe 
Please follow the [docs](https://github.com/akveo/react-native-ui-kitten#demo-applications) if you want to see demo applications. Or use [integration documentation](https://akveo.github.io/react-native-ui-kitten/#/docs/quick-start/getting-started)

**Comment by ngethe** [comment]
I want to run it with Expo and the screens like the splash screen..

**Comment by ngethe** [comment]
Thanks @artyorsh
