### ISSUE TITLE
Current master is not in NPM

### ISSUE THREAD

**Issue by gcemaj** [akveo/react-native-ui-kitten#211]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

The current version in the example as well as the master branch is not in NPM
**Expected behavior:**

To be able to use the latest version by installing from NPM
**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

### Other information:

**OS, device, package version**
```
insert information here
```

**Comment by artyorsh** [comment]
Hi @gabox8888 
Yes, we know :) We're planing to release it soon
If you want using not released things now, your dependency can be explicitly defined as [link to github](https://docs.npmjs.com/files/package.json#github-urls)
Stay tuned
