### ISSUE TITLE
RkTextInput: rkType topLabel omits input

### ISSUE THREAD

**Issue by hatemalimam** [akveo/react-native-ui-kitten#222]
### Issue type

**I'm submitting a ...** 

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Using `<RkTextInput rkType="topLabel" label="Login" />` would omit the input.

**Expected behavior:**
In the little showcase it's working because all the inputs are wrapped in a `<ScrollView>`, whereas if the input is wrapped in a `<View>` for example, the input is gone.

**Steps to reproduce:**

Just render an `RkTextInput` with rkType `topLabel`

**Related code:**
```
import React, { Component } from "react";
import { RkTextInput } from "react-native-ui-kitten";

export default class App extends Component<Props> {
  render() {
    return <RkTextInput rkType="topLabel" label="Login" />;
  }
}

```

**To make it work (as the showcase):**
Wrap the input in a `ScrollView`
```
import React, { Component } from "react";
import { ScrollView } from "react-native";
import { RkTextInput } from "react-native-ui-kitten";

export default class App extends Component<Props> {
  render() {
    return (
      <ScrollView>
        <RkTextInput rkType="topLabel" label="Login" />
      </ScrollView>
    );
  }
}
```

But of course it doesn't make sense to wrap the component in a `ScrollView` to render it correctly.

**Steps to fix:**
In my case adding `flexBasis` to the input, exactly [here](https://github.com/akveo/react-native-ui-kitten/blob/master/src/components/textinput/types.js#L77), fixed the problem.

**Comment by vorasudh** [comment]
+1

**Comment by artyorsh** [comment]
Thanks for report @hatemalimam 
Yes, something like the snippet below this should solve the problem
```
topLabel: {
    input: {
      flexBasis: theme.fonts.sizes.base * 1.42,
    },
}
...
```

Feel free to open PR

**Comment by artyorsh** [comment]
This stays actual for v3.*
Check out the brand new v4 update!
