### ISSUE TITLE
access props in component types

### ISSUE THREAD

**Issue by hatemalimam** [akveo/react-native-ui-kitten#224]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [x] feature request

### Issue description
It would be nice if in the component types we have access to the components props, for example we may adjust the radius of the component based on the width and height passed in the props:

**An example could be:**
```
export const AvatarTypes = (theme, props) => ({
  _base: {
    container: {
      width: '100%',
      borderRadius: Math.round(props.width + props.height) / 2
    },
  },
});

```
Any other way to access the props here ?

**Comment by artyorsh** [comment]
Thanks for suggestion @hatemalimam 
We will think about adding this to the next release roadmap as I mentioned this in #226
