### ISSUE TITLE
withRkTheme - forwardRef

### ISSUE THREAD

**Issue by hatemalimam** [akveo/react-native-ui-kitten#226]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [x] feature request

### Issue description

**Current behavior:**
The current `withRkTheme` HOC doesn't pass through refs, that’s because ref is not a prop, it’s handled differently by React. so using `hoistNonReactStatic` won't help neither ([see](https://reactjs.org/docs/higher-order-components.html#static-methods-must-be-copied-over)) 

**Expected behavior:**

It has to explicitly forward refs to the inner Wrapped ([see](https://reactjs.org/docs/forwarding-refs.html#forwarding-refs-in-higher-order-components))

Let me know if I can open a PR regarding that.

**Comment by artyorsh** [comment]
Hi @hatemalimam 

We're working on next version of framework where new `react.context` api is used. Stay tuned
