### ISSUE TITLE
rkChoice onChange

### ISSUE THREAD

**Issue by hatemalimam** [akveo/react-native-ui-kitten#229]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [X] bug report
* [ ] feature request

### Issue description

**Current behavior:**
rkChoice onChange is passing old `selected` state.

**Expected behavior:**
onChange has to pass the current reflected state of `selected`

**Steps to reproduce:**

``` jsx
<RkChoice
   rkType="radio"
   onChange={selected => {
       // here is false, if the rkChoice IS SELECTED
   }}
/>

```
**Suggested fix:**

https://github.com/akveo/react-native-ui-kitten/blob/master/src/components/choice/rkChoice.js#L222

this 
``` js
onPress(e) {
    this.setState({ selected: !this.state.selected });
    this.props.onChange(this.state.selected, e);
}
```
The above code is failing, because setState is asynchronous. onChange function is being triggered before the `selected` has been changed.

should be changed to this

``` js
onPress(e) {
    this.setState({ selected: !this.state.selected }, () => {
       this.props.onChange(this.state.selected, e);
    } );
}
```

Let me know if I can open a PR.

**Comment by artyorsh** [comment]
Hi @hatemalimam 

Thanks for report. 

> Let me know if I can open a PR.

Your welcome. Your fix suggestion looks nice
