### ISSUE TITLE
Ability to view full landscape image in RkGallery

### ISSUE THREAD

**Issue by skyleraustin** [akveo/react-native-ui-kitten#248]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [x] feature request

### Issue description

**Current behavior:**

When a landscape image is viewed in an RkGallery, it appears that the window dimensions are used to set the image size. Image is effectively cropped to window dimensions and only partially visible.

**Expected behavior:**

It would be ideal if the full landscape image (width) could be viewed by default.

**Steps to reproduce:**

**Related code:**

```
<RkGallery
    items={[require('path-to-landscape-image.jpg')]}
/>
```

### Other information:

**OS, device, package version**
```
Package version 3.1.2
Tested on Expo 32.0.2, iOS 11
```

**Comment by artyorsh** [comment]
Hi @skyleraustin 
Thanks for report and sorry for so late reply
To be honest, we're currently unable to fix this because our team works on something really cool you could see in future release. Stay tuned 😏
PR's are welcome ❤️

**Comment by skyleraustin** [comment]
OK, thanks. Looking forward to seeing what you are working on.

**Comment by artyorsh** [comment]
This stays actual for v3.*
Check out the brand new v4 update!
