### ISSUE TITLE
Failed prop type: Invalid props.contentStyle key color supplied to RkButton

### ISSUE THREAD

**Issue by skyleraustin** [akveo/react-native-ui-kitten#249]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

Receive "Warning: Failed prop type: Invalid props.contentStyle key `color` supplied to `RkButton`" when applying a color via documented method @ https://akveo.github.io/react-native-ui-kitten/#/docs/ui-components/rkbutton.

**Expected behavior:**

Content style color can be set without an error

**Steps to reproduce:**

**Related code:**

```
<RkButton
          contentStyle={{color: 'red'}}>
          SUBMIT
</RkButton>
```

### Other information:

**OS, device, package version**
```
Package version 3.1.2
Expo 32.0.2
```

**Comment by artyorsh** [comment]
Thanks for report, @skyleraustin 

Looks like it is caused by passing `contentStyle` to `Touchable` [spreading props](https://github.com/akveo/react-native-ui-kitten/blob/master/src/components/button/rkButton.js#L197).
Will fix this in future. PR's are welcome

**Comment by skyleraustin** [comment]
I can ignore the warning until this is resolved. Thanks.

**Comment by artyorsh** [comment]
This stays actual for v3.*
Check out the brand new v4 update!
