### ISSUE TITLE
Invalid prop source supplied to RkGalleryImage, expected a ReactNode

### ISSUE THREAD

**Issue by skyleraustin** [akveo/react-native-ui-kitten#250]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

When an object with a uri property is supplied as source to RkGallery/RkGalleryImage, the following warning is received. Image *is* rendered properly.

**Expected behavior:**

No warning would be received. Again, Image *is* already rendered properly.

**Steps to reproduce:**

**Related code:**

```
<RkGallery
          items={[{uri: 'https://www.fillmurray.com/200/300'}]}
/>
```

### Other information:

**OS, device, package version**
```
Package version 3.1.2
Expo 32.0.2
```

**Comment by artyorsh** [comment]
Hi @skyleraustin 
Thanks for report

As a temporary solution you can try changing type to `Image.propTypes.source` or using prop-types `shape` like it is used [here](https://github.com/facebook/react-native/blob/master/Libraries/Image/Image.android.js#L45) directly in your `node_modules`.
We will fix it in future. PR's are welcome

**Comment by skyleraustin** [comment]
Sorry, I was away. I will review this this evening.

**Comment by skyleraustin** [comment]
Because the image is still rendered, I will ignore the warning until this is resolved in the future. Thanks for the response.

**Comment by mbecker** [comment]
Hey,
any plans to include just the prop validation from the linked react native source?

**Comment by artyorsh** [comment]
This stays actual for v3.*
Check out the brand new v4 update!
