### ISSUE TITLE
RkButton rkType style not getting passed to non-string children

### ISSUE THREAD

**Issue by adongy** [akveo/react-native-ui-kitten#255]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [x] feature request

### Issue description

**Current behavior:**

When using the RkButton with non-string children (example: Icons), the style props applied to the children are different from styles applied to text.
Ultimately, it makes a difference when the children renders text down the line (in my case, icon fonts are text so `color` applies).

Example JSX:
```
<RkButton rkType="secondary">
  <Icon name="star"/>
  Button Text
</RkButton>
```

In this case, the secondary style (colors) will change the `Button Text` text color, but the `Icon` will be rendered in its default color (most likely black).

**Expected behavior:**

The `Icon` element receives the theme derived from the `rkType` and becomes the same color as the text.

**Steps to reproduce:**

cf example beforehand.

**Related code:**

https://github.com/akveo/react-native-ui-kitten/blob/88a537e077c4c1099d70db723de04e920ee06a12/src/components/button/rkButton.js#L184

The children will only get directly passed `contentStyle`, not the `renderChildren` argument `style` as done with text:

https://github.com/akveo/react-native-ui-kitten/blob/88a537e077c4c1099d70db723de04e920ee06a12/src/components/button/rkButton.js#L173

I understand this is hard to fix, as there is no easy way to know in advance what the children will render into. If it renders into a View, we'll get a React warning as text style props do not apply to Views. However, the current workaround is to pass the `contentStyle` around, so I have two style definitions for the same result: once in the RkTheme that defines the Type, and once again in the `contentStyle` which is what I'm trying to avoid.

```
insert short code snippets here
```

### Other information:

**OS, device, package version**
```
Tested on iOS simulator
"react-native-ui-kitten": "^3.1.2",
```

**Comment by adongy** [comment]
I noticed the Card component parses the children props to know what styles to apply, maybe we can support the same pattern to indicate to pass the style props.

**Comment by artyorsh** [comment]
Hi @adongy 

Very nice notice. Sorry for so late reply
Thanks for your detailed report, but to be honest we're not able to fix this right now because currently our team works on something really cool for next version. Stay tuned 😏

Anyway, PR's are welcome

**Comment by artyorsh** [comment]
This stays actual for v3.*
Check out the brand new v4 update!
