### ISSUE TITLE
RkTabView question

### ISSUE THREAD

**Issue by elupanov** [akveo/react-native-ui-kitten#27]
Created by request:

I’m using RkTabView to create custom tab and I want to make the tabs changes another components view based on which tab that is selected.

I just want to ask is there any props that works like onPress in TouchableOpacity? Or is there any way for me to pass action creator (to trigger reducer) when a tab is selected?

I tried to pass action creator in title prop but that will triggers error since in always run in render function. Can you guide me the best way to do that?
Thanks.

Example of the way that I tried but fail
```
<RkTabView.Tab 
            title={(selected) => {
                if(selected){
                    This.props.changeTab(‘Badge');
                }
                return this.renderTab(selected, '610', 'Badges');
            }}
        >
            <Text>Train</Text>
        </RkTabView.Tab>
```

**Comment by fundon** [comment]
Same problem.

**Comment by sergey-kozel** [comment]
Hi @elupanov , @fundon,

onTabChanged prop was added in ac2904371a6a636cd61f1d87b239094d3a73a912. Will be available in next release.
