### ISSUE TITLE
Render Tabs on Bottom of Screen

### ISSUE THREAD

**Issue by reggie3** [akveo/react-native-ui-kitten#28]
Is it possible to render the tabs of a RkTabView on the bottom of the screen vice the top?

**Comment by malashkevich** [comment]
Hello @reggie3, no it's not possible with current version.

**Comment by GabeCabrera** [comment]
Any update on this?

**Comment by artyorsh** [comment]
@GabeCabrera unfortunately, no. We don't support v3. However, you can use [BottomNavigation](https://akveo.github.io/react-native-ui-kitten/docs/components/bottom-navigation/overview#bottomnavigation) in case of migration to v4
