### ISSUE TITLE
Not found RkCalendar component

### ISSUE THREAD

**Issue by lashevskiy** [akveo/react-native-ui-kitten#294]
I try to use react-native-ui-kitten. But then I execute npm install --save react-native-ui-kitten
I can not use RkCalendar, because this component is not found. How can I solve this problem and that I do wrong?

**Comment by artyorsh** [comment]
Hi @lashevskiy

Thanks for report.
`RkCalendar` is not included in latest release. To use it you can install framework directly from github:
```
npm i react-native-ui-kitten akveo/react-native-ui-kitten
```

**Comment by lashevskiy** [comment]
Hi @artyorsh

Does it work correctly? Can I use it in accordance with the documentation and not worry? Will it be included in the next version of the library?

**Comment by artyorsh** [comment]
@lashevskiy 

You can use it without worries :) Documentation is actual and describes the main principles of how it can be used

**Comment by lashevskiy** [comment]
@artyorsh I try to use them like you write above, but I have the next problem:
 ```
Support for the experimental syntax 'exportNamespaceFrom' isn't currently enabled
export * as Base from './baseCalendarSelectionStrategy';
export * as Range from './rangedCalendarSelectionStrategy';
```
How can I solve this problem? 
I try use @babel/plugin-syntax-export-namespace-from but it not helped me.

**Comment by artyorsh** [comment]
@lashevskiy 
Looks like you have configuration issues in your .babelrc
Take a look on our [playground app](https://github.com/akveo/react-native-ui-kitten/tree/master/example) configuration. It also demonstrates practical usage for all framework components

**Comment by weikilla** [comment]
> @lashevskiy
> Looks like you have configuration issues in your .babelrc
> Take a look on our [playground app](https://github.com/akveo/react-native-ui-kitten/tree/master/example) configuration. It also demonstrates practical usage for all framework components

hi，i can run the example，but when i use ui-kitten 3.13 In my rn project，it show an error in RkCalendarDay.component.js line 52 that undefined is not an object(evaluating '_reactNative.View.propTypes.style')，i found this .js is the same as example(can run) , but when i run with react-native run-android , i got this error

**Comment by kubido** [comment]
in expo, I manage to remove the error by adding babel plugin `@babel/plugin-proposal-export-namespace-from` 

`yarn add @babel/plugin-proposal-export-namespace-from --dev`
and in your babel.config.js:
`plugins: ['@babel/plugin-proposal-export-namespace-from']`

but still got calendar error related to this issue #357 (ver 3.1.3)

**Comment by eggandmoney** [comment]
Did anyone found the solution for it ?
