### ISSUE TITLE
Missing StartScreen in ExploreApp 

### ISSUE THREAD

**Issue by felixrigorii001** [akveo/react-native-ui-kitten#3]
When I try to run the ExploreApp it returns StartScreen is missing 

Unknown named module: './screens/StartScreen'
_require
    require.js:93
<unknown>
    index.android.js:13
loadModuleImplementation
    require.js:171
guardedLoadModule
    require.js:116
_require
    require.js:107
global code
    require-0.js:1

Regards,

**Comment by malashkevich** [comment]
Hi @felixrigorii001.
Current version don't support android.

But soon we will release new version with android support and other features.
Stay tuned.
