### ISSUE TITLE
RkTabSet and RkTab not found in version 3.1.2 

### ISSUE THREAD

**Issue by yaibait** [akveo/react-native-ui-kitten#301]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description
RkTabSet and RkTab not found in version 3.1.2

**Comment by artyorsh** [comment]
Hi @yaibait 

Some components included in framework were not released to npm.
Just like `RkCalendar` (#294), `RkTabSet` was not included in latest release. To use it you can install framework directly from github:
```
npm i react-native-ui-kitten akveo/react-native-ui-kitten
```

**Comment by yaibait** [comment]
@artyorsh  Thanks you 👍
