### ISSUE TITLE
Latest version of Rk is not published to NPM.

### ISSUE THREAD

**Issue by J-Cake** [akveo/react-native-ui-kitten#302]
I'm trying to use the new `RkTabSet` and `RkTab` but the `index.js` in the _react-native-ui-kitten_ node module folder does not contain the reference and the `src` directory does not contain its source either. 

Please push to NPM.

Current workaround: clone repo into node_modules.

**Comment by artyorsh** [comment]
Hi @J-Cake 

Some components included in framework were not released to npm (noticed in #211 and #301)
Please follow suggestions posted to [this issue](https://github.com/akveo/react-native-ui-kitten/issues/301)

**Comment by J-Cake** [comment]
May I ask why it has not been published?

Thanks

**Comment by artyorsh** [comment]
@J-Cake 

To be honest, we were not able to release this due to next release planning
Check [this](https://github.com/akveo/react-native-ui-kitten/tree/next#whats-new-will-you-have) out and stay tuned  😉
