### ISSUE TITLE
RkButton disabled

### ISSUE THREAD

**Issue by veedeo** [akveo/react-native-ui-kitten#31]
It would be handy to add disabled implementation to RkButton component

**Comment by 7laria** [comment]
Done.
#32

**Comment by sergey-kozel** [comment]
Fixed in d29f6273dbd9f1dafbaf7de51fa3250f290d59ce by adding maintenance of all TouchableOpacity props

**Comment by numediaweb** [comment]
Could you please provide an example of a disabled button?
