### ISSUE TITLE
RkPicker's RkOption cannot render properly on Android

### ISSUE THREAD

**Issue by LiuMengzhou** [akveo/react-native-ui-kitten#333]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

RkOption of RkPicker cannot render completely on Android.

![144361553767892_ pic_hd](https://user-images.githubusercontent.com/13726966/55149321-ee79bf80-5184-11e9-87c8-d970655d1995.jpg)

**Expected behavior:**

just like it shows on iOS.

![image](https://user-images.githubusercontent.com/13726966/55149630-7b247d80-5185-11e9-8db1-4ab91af4f448.png)

**Steps to reproduce:**

**Related code:**

```js
generateArrayFromRange(start, finish) {
    return Array.apply(null, Array(finish - start + 1)).map((_, i) => {
      return start + i;
    });
  }

let hours = this.generateArrayFromRange(0, 12);
let minutes = this.generateArrayFromRange(0, 60);

<RkPicker
    optionNumberOnPicker={5}
    title='开启时间'
    confirmButtonText="确定"
    cancelButtonText="取消"
    data={[hours, minutes]}
    visible={this.state.pikerVisible}
    onConfirm={this.handlePickedValue}
    onCancel={this.hidePicker}
    selectedOptions={this.state.pickedValue} />
```

### Other information:

**OS, device, package version**
```
Android version: 8.0.0
Phone: Xiaomi MIX 2
MIUI version: 10.2.2.0
"react-native-ui-kitten@3.1.2",
```

Thanks for ur help in advance!!!

**Comment by LiuMengzhou** [comment]
keep active

**Comment by artyorsh** [comment]
Hi @LiuMengzhou 

What do you mean with not properly?
Just ran your code on android sdk 26 (8.0, Nexus 5X) and could not reproduce

<img src="https://user-images.githubusercontent.com/10753921/55274579-bbe9d700-52ea-11e9-8218-2938208b817e.png" alt="drawing" width="375"/>

Any other implementation details?

**Comment by LiuMengzhou** [comment]
Hi @artyorsh 
Thanks for ur reply.
`render completely` means `28` is rendered `28 not `2`.
Our application have some pages running with React Native, instead of being a pure RN app.
```
React Native version: 0.54.4,
compileSdkVersion: 28,
targetVersion: 26,
```
I can reproduce my issue based on this environment with true phone.
I didn't try on emulator, I will.

**Comment by artyorsh** [comment]
Ah, yep. I didn't even seen this on your screenshot :)
Anyway it looks like there is trouble with rendering "large" content

**Comment by LiuMengzhou** [comment]
sorry. my screenshot may not describe details clearly. 
render `minutes` range from `0` to `60`
<img width="963" alt="WeChat1537a63158fd6ebf8f5616261049726e" src="https://user-images.githubusercontent.com/13726966/55304685-38152380-547f-11e9-9452-d0a208292043.png">

**Comment by LiuMengzhou** [comment]
keep alive

**Comment by artyorsh** [comment]
@LiuMengzhou 
To be honest we're not currently able to fix this because we're working on a major release
It would be awesome if you have some workarounds on your issue. PR's are welcome
