### ISSUE TITLE
Can't capture onPress event with RkTextInput is a nested element

### ISSUE THREAD

**Issue by bsmayer** [akveo/react-native-ui-kitten#354]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [x] feature request

### Issue description

**Current behavior:**

When nesting RkTextInput inside a TouchableOpacity, onPress is not captured. 

**Expected behavior:**

Should fire TouchableOpacity onPress function

**Steps to reproduce:**

- Create a TouchableOpacity
- Create RkTextInput with editable = false inside TouchableOpacity
- Try to call onPress function

**Related code:**

```
<TouchableOpacity onPress={() => this.setState({ pickerVisible: true })}>
   <RkTextInput label={icon} editable={false} value={this.state.pickedValue[0].value} />
</TouchableOpacity>
```

### Other information:

**OS, device, package version**
```
iOS and Android
```

**Comment by artyorsh** [comment]
Hi @bsmayer

That's because `RkTextInput` is already wrapped in `TouchableOpacity` with own `onPress`
For quick fix you can pass `onPress` inside `RkTextInput` and modify existing code to call this prop
We'll fix this in future release, but PR's are welcome 

Thanks!

**Comment by artyorsh** [comment]
This stays actual for v3.*
Check out the brand new v4 update!
