### ISSUE TITLE
babel issue when upgrading to 59.4

### ISSUE THREAD

**Issue by YazeedAsaad** [akveo/react-native-ui-kitten#356]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x ] bug report
* [ ] feature request

### Issue description

**Current behavior:**
babel issue when upgrading to 59.4  returns an error as soon as the app runs

**Expected behavior:**
app works normally without errors
**Steps to reproduce:**

**Related code:**

error i get 
http://prntscr.com/ncq9l5

`The development server returned response error code: 500

URL: http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false

Body:
{"type":"TransformError","lineNumber":1,"column":9,"filename":"node_modules\\react-native-ui-kitten\\src\\components\\calendar\\layout\\index.js","errors":[{"description":"SyntaxError: d:\\Kensoftware Work\\Apps\\Lyv2\\node_modules\\react-native-ui-kitten\\src\\components\\calendar\\layout\\index.js: Support for the experimental syntax 'exportNamespaceFrom' isn't currently enabled (1:10):\n\n> 1 | export * as Vertical from './rkCalendarVerticalLayout';\n    |          ^\n  2 | export * as Horizontal from './rkCalendarHorizontalLayout';\n  3 | \n\nAdd @babel/plugin-proposal-export-namespace-from (https://git.io/vb4SG) to the 'plugins' section of your Babel config to enable transformation.","filename":"node_modules\\react-native-ui-kitten\\src\\components\\calendar\\layout\\index.js","lineNumber":1}],"name":"SyntaxError","message":"SyntaxError: d:\\Kensoftware Work\\Apps\\Lyv2\\node_modules\\react-native-ui-kitten\\src\\components\\calendar\\layout\\index.js: Support for the experimental syntax 'exportNamespaceFrom' isn't currently enabled (1:10):\n\n> 1 | export * as Vertical from './rkCalendarVerticalLayout';\n    |          ^\n  2 | export * as Horizontal from './rkCalendarHorizontalLayout';\n  3 | \n\nAdd @babel/plugin-proposal-export-namespace-from (https://git.io/vb4SG) to the 'plugins' section of your Babel config to enable transformation.","stack":"SyntaxError: d:\\Kensoftware Work\\Apps\\Lyv2\\node_modules\\react-native-ui-kitten\\src\\components\\calendar\\layout\\index.js: Support for the experimental syntax 'exportNamespaceFrom' isn't currently enabled (1:10):\n\n> 1 | export * as Vertical from './rkCalendarVerticalLayout';\n    |          ^\n  2 | export * as Horizontal from './rkCalendarHorizontalLayout';\n  3 | \n\nAdd @babel/plugin-proposal-export-namespace-from (https://git.io/vb4SG) to the 'plugins' section of your Babel config to enable transformation.\n    at Object.raise (d:\\Kensoftware Work\\Apps\\Lyv2\\node_modules\\@babel\\parser\\lib\\index.js:3851:17)\n    at Object.expectPlugin (d:\\Kensoftware Work\\Apps\\Lyv2\\node_modules\\@babel\\parser\\lib\\index.js:5172:18)\n    at Object.maybeParseExportNamespaceSpecifier (d:\\Kensoftware Work\\Apps\\Lyv2\\node_modules\\@babel\\parser\\lib\\index.js:8392:12)\n    at Object.maybeParseExportNamespaceSpecifier (d:\\Kensoftware Work\\Apps\\Lyv2\\node_modules\\@babel\\parser\\lib\\index.js:2251:32)\n    at Object.parseExport (d:\\Kensoftware Work\\Apps\\Lyv2\\node_modules\\@babel\\parser\\lib\\index.js:8334:42)\n    at Object.parseExport (d:\\Kensoftware Work\\Apps\\Lyv2\\node_modules\\@babel\\parser\\lib\\index.js:2199:24)\n    at Object.parseStatementContent (d:\\Kensoftware Work\\Apps\\Lyv2\\node_modules\\@babel\\parser\\lib\\index.js:7395:27)\n    at Object.parseStatement (d:\\Kensoftware Work\\Apps\\Lyv2\\node_modules\\@babel\\parser\\lib\\index.js:7291:17)\n    at Object.parseStatement (d:\\Kensoftware Work\\Apps\\Lyv2\\node_modules\\@babel\\parser\\lib\\index.js:1993:26)\n    at Object.parseBlockOrModuleBlockBody (d:\\Kensoftware Work\\Apps\\Lyv2\\node_modules\\@babel\\parser\\lib\\index.js:7868:25)"}
processBundleResult
    BundleDownloader.java:296
access$200
    BundleDownloader.java:37
onResponse
    BundleDownloader.java:174
execute
    RealCall.java:206
run
    NamedRunnable.java:32
runWorker
    ThreadPoolExecutor.java:1162
run
    ThreadPoolExecutor.java:636
run
    Thread.java:764
`
### Other information:

**OS, device, package version**
```
latest version 3.1.3


insert information here
```

**Comment by artyorsh** [comment]
Hi @YazeedAsaad 
We don't currently support latest RN. This will come with future releases, stay tuned

**Comment by vivek1996** [comment]
@artyorsh  

> Hi @YazeedAsaad
> We don't currently support latest RN. This will come with future releases, stay tuned

What version can be used to get away from this error?

**Comment by evertonmadeira** [comment]
npm install react-timer-mixin. Hava a good day!

**Comment by alxpy** [comment]
@artyorsh hello! Do you have plan to support latest RN version?

**Comment by artyorsh** [comment]
Thanks for your interest @alxpy 
Yes. Read [this reply](https://github.com/akveo/react-native-ui-kitten/issues/358#issuecomment-500062046) for more details

**Comment by alxpy** [comment]
thx!
