### ISSUE TITLE
rkCalendar cause application to crash at start

### ISSUE THREAD

**Issue by JaWoGit** [akveo/react-native-ui-kitten#357]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [X ] bug report
* [ ] feature request

### Issue description

**Current behavior:**

Some components in node_modules, like RkCalendarDay, cause application to crash at start. Even if the components aren't used in the application. 

Dependency:
`react-native-ui-kitten": "github:akveo/react-native-ui-kitten`

**Expected behavior:**

Application will be launched after expo start.

**Steps to reproduce:**

Delete node_modules, run npm install, start application with `expo start´ and try to run the application on your device.

**Related code:**

```
 base: View.propTypes.style,
 today: View.propTypes.style,
 selected: View.propTypes.style,
```

<img width="478" alt="Bildschirmfoto 2019-04-16 um 18 14 47" src="https://user-images.githubusercontent.com/16936560/56226472-9511fb80-6073-11e9-94ba-32434f4ae591.png">

### Other information:

**OS, device, package version**
```
iOS, Simulator and physical device
```

**Comment by weikilla** [comment]
+1

**Comment by JoseAntonio029** [comment]
+1

**Comment by artyorsh** [comment]
Hi @JaWoGit, thanks for report
Could you please provide related code which causes crash?

**Comment by dhwanilvyas** [comment]
Hello!

[This line](https://github.com/akveo/react-native-ui-kitten/blob/master/src/components/calendar/cells/rkCalendarDay.component.js#L52) here seems to be causing the issue I guess. Changing `View.propTypes.style` to `PropTypes.style` fixes the issue for me.

**Comment by richardvanbergen** [comment]
It seems that you already have the root of the issue but I was also wondering if you could provide some insight into this stack trace:

```
undefined is not an object (evaluating '_reactNative.View.propTypes.style')

<unknown>
    rkCalendarDay.component.js:52:29
loadModuleImplementation
    require.js:331:6
<unknown>
    rkCalendarWeek.component.js:4
loadModuleImplementation
    require.js:331:6
<unknown>
    rkCalendarMonth.component.js:5
loadModuleImplementation
    require.js:331:6
<unknown>
    rkCalendarView.component.js:7
loadModuleImplementation
    require.js:331:6
<unknown>
    rkCalendar.component.js:4
loadModuleImplementation
    require.js:331:6
<unknown>
    index.js:10
loadModuleImplementation
    require.js:331:6
<unknown>
    App.js:10
loadModuleImplementation
    require.js:331:6
<unknown>
    index.js:6
loadModuleImplementation
    require.js:331:6
guardedLoadModule
    require.js:197:45
global code
    <unknown file>:0
```

Standard right? But what is on App.js:10?

`import { RkButton } from 'react-native-ui-kitten';
`
Why would importing RkButton trigger an undefined props error in RkCalendar? Am I reading the stack trace wrong?

**Comment by artyorsh** [comment]
> [This line](https://github.com/akveo/react-native-ui-kitten/blob/master/src/components/calendar/cells/rkCalendarDay.component.js#L52) here seems to be causing the issue I guess. Changing `View.propTypes.style` to `PropTypes.style` fixes the issue for me.
> This issue is in tabset component as well.
> 
> I'm can send in a PR if this fixes the issue 😄

Thanks for details @dhwanilvyas! Yes, PR's are welcome

**Comment by JaWoGit** [comment]
In my case, there are more components affected.
I changed the proptypes in the following components and my application works as expected again:

rkCalendarDay.component.js line **52-56**
rkCalendarWeek.component.js line **35**
rkCalendarMonth.component.js line  **40**
rkCalendarDaysNames.component.js line  **18**
rkCalendarMonthHeader.component.js line **19**
rkCalendarView.component.js line **71**
rkTab.components.js line **37-38**
rkTabBar.component.js line  **33-34**
rkTabBarIndicator.component.js line **25-26**
rkTabPager.component.js line  **30**

**Comment by YazeedAsaad** [comment]
im now getting this error http://prntscr.com/nd2y1v   after fixing view.proptypes.style i changed it to ViewPropTypes.style  (importing from RN)

**Comment by artyorsh** [comment]
@YazeedAsaad for quick fix you can see @dhwanilvyas's [answer](https://github.com/akveo/react-native-ui-kitten/issues/357#issuecomment-483918433)

**Comment by richardvanbergen** [comment]
The issue is also present in:

- rkCalendarWeek.component.js:35
- rkCalendarMonth.component.js:40
- rkCalendarDayNames.component.js:18
- rkCalendarMonthHeader.component.js:19
- rkCalendarView.component.js:71
- rkTab.component.js:37+38
- rkTabBar.component.js:33+34
- rkTabBarIndicator.component.js:25+26
- rkTabPager.component.js:30

Here's my package.json. It's basically just a newly created project with `react-native init`

```
{
  "name": "TestProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "@babel/plugin-proposal-export-namespace-from": "^7.2.0",
    "react": "16.8.3",
    "react-native": "0.59.3",
    "react-native-ui-kitten": "^3.1.3"
  },
  "devDependencies": {
    "@babel/core": "7.4.3",
    "@babel/runtime": "7.4.3",
    "babel-jest": "24.7.1",
    "flow-bin": "^0.97.0",
    "jest": "24.7.1",
    "metro-react-native-babel-preset": "0.53.1",
    "react-test-renderer": "16.8.3"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by richardvanbergen** [comment]
Once I edited all these files then it started working for me.

**Comment by riyadshauk** [comment]
Why has nobody submitted a PR for this yet? Or even updated their fork of this repo on their GitHub? The easiest thing to get this library working as it did earlier is to simply use version 3.1.2 for the time being.

In your project's package.json:
```
"react-native-ui-kitten": "3.1.2",
```

**Comment by richardvanbergen** [comment]
I would like to but according to the contributing guide on the master branch, I much test! However, unless I'm being dumb, the current master does not have tests, only `next`.

I'm guessing the test stipulation is for the next branch and not the current?

Here's my branch if you're interested, it's very simple really. Not even sure how you would test it beyond "do the existing components fail to run?".

Someone, please let me know if/how I should proceed. I don't want to waste my time.

https://github.com/richardvanbergen/react-native-ui-kitten/tree/proptype-undefined-fix

**Comment by adamsolomon1986** [comment]
Can we downgrade to a stable version? which version does not have this problem?

**Comment by artyorsh** [comment]
For all faced this issue, you can use v3.1.2 if you're not going to use `RkCalendar` and `RkTabView`:
```
npm i react-native-ui-kitten@3.1.2
```
We're sorry for such type of trouble

**Comment by Deboracgs** [comment]
I make the downgrade to 3.1.2, but it is giving error

```
bundling failed: Error: Unable to resolve module `./src/components/badge/rkBadge.component` from `D:\proj\app\prop10-client-app\ClubeTarget\node_modules\react-native-ui-kitten\index.js`: The module `./src/components/badge/rkBadge.component` could not be found from `D:\proj\app\prop10-client-app\ClubeTarget\node_modules\react-native-ui-kitten\index.js`. Indeed, none
of these files exist:`
```

**Comment by ronniepbdigital** [comment]
+1

**Comment by Ahrimaan** [comment]
Any News on this Bug ?
