### ISSUE TITLE
Support for the experimental syntax 'exportNamespaceFrom' isn't currently enabled

### ISSUE THREAD

**Issue by imranali4264** [akveo/react-native-ui-kitten#358]
export * as Vertical from './rkCalendarVerticalLayout';
 export * as Horizontal from './rkCalendarHorizontalLayout';
  
i didnt use calendar in app

**Comment by artyorsh** [comment]
Hi @imranali4264 
What's your babel config?
For quick fix adding [namespace import plugin](https://babeljs.io/docs/en/next/babel-plugin-proposal-export-namespace-from) into your .babelrc
[Might be helpful](https://github.com/expo/ex-navigation/issues/511)

**Comment by imranali4264** [comment]
after adding  plugin in my package.json file it give this error

undefined is not an object (evaluating '_reactnative.viewproptypes.style')

**Comment by imranali4264** [comment]
{
  "name": "LinkAsset",
  "version": "0.0.1",
  "babel": {
    "plugins": [
      "@babel/plugin-proposal-export-namespace-from"
    ]
  },
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.8.3",
    "react-native": "0.59.4",
    "react-native-ui-kitten": "^3.1.3"
  },
  "devDependencies": {
    "@babel/core": "^7.4.3",
    "@babel/plugin-proposal-export-namespace-from": "^7.2.0",
    "@babel/plugin-syntax-export-namespace-from": "^7.2.0",
    "@babel/runtime": "^7.4.3",
    "babel-jest": "^24.7.1",
    "jest": "^24.7.1",
    "metro-react-native-babel-preset": "^0.53.1",
    "react-test-renderer": "16.8.3"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by artyorsh** [comment]
> after adding plugin in my package.json file it give this error
> 
> undefined is not an object (evaluating '_reactnative.viewproptypes.style')

This is already [known issue](https://github.com/akveo/react-native-ui-kitten/issues/357)
Will be fixed soon

**Comment by santiblanko** [comment]
same error here!

**Comment by marionmenzl** [comment]
unfortunately same error here

**Comment by rolignu2** [comment]
same error

**Comment by itcurves** [comment]
same error

**Comment by ZhuBit** [comment]
Same error :( Help

**Comment by lsantamaria** [comment]
same

**Comment by sootood** [comment]
same error

**Comment by tiagoferraro** [comment]
same error

**Comment by fengdexunmi** [comment]
same error

**Comment by botareyka** [comment]
same error

**Comment by kazewonginc** [comment]
same error, any temporary fix?

**Comment by botareyka** [comment]
I downloaded version 3.1.4, replaced the /src/components folder and the problem was gone

**Comment by kllr** [comment]
> 
> 
> I downloaded version 3.1.4, replaced the /src/components folder and the problem was gone
Hi,
how can we install that version? 
npm install --save react-native-ui-kitten@3.1.4 
does not work. Isn't 3.1.3 the newest version?

**Comment by adrielcardoso** [comment]
"react-native-ui-kitten": "^3.1.2",



Support for the experimental syntax 'exportNamespaceFrom' isn't currently enabled (1:10):

> 1 | export * as Base from './baseCalendarSelectionStrategy';
    |          ^
  2 | export * as Range from './rangedCalendarSelectionStrategy';


it is dont work for me 

Add @babel/plugin-proposal-export-namespace-from (https://git.io/vb4SG) to the 'plugins' section of your Babel config to enable transformation

**Comment by Ashkur** [comment]
I had to create a .babelrc file and paste [this](https://babeljs.io/docs/en/next/babel-plugin-proposal-export-namespace-from)

After that another error appears:

> Unexpected token '*'. import call expects exactly one argument.
> no stack

pls, help

**Comment by adrielcardoso** [comment]
i have some problem, 

more, after change to version 3.0.0 and downgrade react-native 

i haved success..

but, i need upgrade to last version react-native-ui-kitten..

help!

**Comment by shreyansh073** [comment]
Same error here. Did anybody find any fix? Also, I see that you are updating your code base for expo-33. Any idea how soon should we be expecting the release?

**Comment by Devsome** [comment]
Got the same Error, hope it will be fixed soon.

**Comment by artyorsh** [comment]
For anyone else here looking for the solution.
For now we're going to release a major update. If you need this issue to be fixed asap - please use #385 pr branch to close your issues and resolve this.
I hope we'll release 3.1.4 when we'll get all the things done on the major release 🤞 
Stay tuned :)

**Comment by artyorsh** [comment]
Hey everyone! Hope to notify you that you can now fix this issue in your apps updating to 3.1.4.
But better check out brand new v4.0 :fire:
