### ISSUE TITLE
RkAvoidKeyboard not working for iOS

### ISSUE THREAD

**Issue by RobertArissen** [akveo/react-native-ui-kitten#36]
Hello,

The RkAvoidKeyboard is not working fine on iOS. In the demo app (Chat screen) on the first click everything is fine, but if you click again on the text field he doesn't do the job.

How can I (and you) fix this?

**Comment by sergey-kozel** [comment]
Hello @RobertArissen,

Sorry, we do not longer plan to support this feature and going to remove it from the library soon.

Please, try to find another solution.
