### ISSUE TITLE
OnEndReached and pull to refresh in RkGallery

### ISSUE THREAD

**Issue by adamsolomon1986** [akveo/react-native-ui-kitten#382]
How can I pass onEndReached and RefreshControl to the RkGallery? I need to be able to page images as users scroll? thanks much

**Comment by artyorsh** [comment]
Hi @adamsolomon1986 

Thanks for report. That's a framework bug and currently there is no way to pass custom props to `RkGallery`. But you can try modify existing code directly in your `node_modules` with [following code](https://gist.github.com/artyorsh/e1f94551f8ceefa4bea291c41761bef5)

Try this and welcome to create PR if everything is okay for your case

**Comment by artyorsh** [comment]
This stays actual for v3.*
Check out the brand new v4 update!
