### ISSUE TITLE
can't add prop to RkButton to disable TouchableOpacity

### ISSUE THREAD

**Issue by timurridjanovic** [akveo/react-native-ui-kitten#39]
It would be nice to be able to disable an RkButton.

**Comment by sergey-kozel** [comment]
Hello @timurridjanovic,
This issue was fixed in d29f627 by adding maintenance of all TouchableOpacity props

**Comment by reggie3** [comment]
@timurridjanovic Were you able to disable RkButton using the TouchableOpacity prop?  Can you share how you did it?
