### ISSUE TITLE
Keyboard avoiding broken second and subsequent time a text input is focused

### ISSUE THREAD

**Issue by iosdev-republicofapps** [akveo/react-native-ui-kitten#43]
Hi,

Thanks so much for making this available!  Your components look great and I'm eager to use them.

There seems to be a bug in your keyboard avoiding on text inputs in your Kitten Tricks iOS app.  I just downloaded the latest version from the iOS App Store, 1.0.9, on iOS 11 on an iPhone 6.

Here's what happens:

1. Launch app.
2. Tap Auth from Grid Menu.
3. Tap Login V1 from Login Menu.
4. Tap Username text input field.  The scrollview containing the Username field scrolls up to avoid the keyboard.  Good!
5. Type something into the Username field using the onscreen keyboard.
6. Tap Login to dismiss the screen.
7. Repeat steps 3-5 again.  This time, at step 4, the scrollview does NOT scroll up to avoid the keyboard, and it obscures the the Username field.  This seems broken.

I do notice that in step 6, the first time around, the keyboard does not dismiss until after the login screen has been popped off the nav stack and we've returned to the main Login Menu.  Not sure if that helps.

I'm happy to try stuff or attach debug logs if you can give me some hints.

I'd really love to use (and credit) your kitten UI, but I'm hesitant to do so if the keyboard avoiding behavior doesn't work consistently.

Any ideas?

Thanks, and thanks again for making this available!

**Comment by iosdev-republicofapps** [comment]
Sorry, I didn't see https://github.com/akveo/react-native-ui-kitten/issues/36 when I created my issue, but they seem to be related ...

**Comment by sergey-kozel** [comment]
Hello, @iosdev-republicofapps,

Thank you for such detailed report, but we do not longer plan to support this feature and going to remove it from the library soon.

Sorry and try to find other solution for this feature.
