### ISSUE TITLE
Ui kitten for web

### ISSUE THREAD

**Issue by Gi972** [akveo/react-native-ui-kitten#44]
Hello team,

I know you are focus  on android an IOS support, but do you think make a version of ui kitten for the web?

thanks for your answer.

**Comment by MarAvFe** [comment]
I don't really think so. Remember kitten is developed by [Akveo team](https://www.akveo.com/), and they already have some wonderful web tools. I'm not in their team, though. It's not an official answer

**Comment by malashkevich** [comment]
Hello @Gi972 and @MarAvFe.
Yes, we are not plan to move somehow our kitten to web mostly because react-native and react are a bit different things.
If you need UI frameworks - take a look at our [Nebular framework](https://akveo.github.io/nebular/#/home)

**Comment by geminiyellow** [comment]
@malashkevich i try to use `react-native-web` to load `kitten`, but it give me that

![image](https://user-images.githubusercontent.com/929878/37079693-d1b351ba-2226-11e8-9868-f7cabfa08ce8.png)

**Comment by malashkevich** [comment]
@geminiyellow, unfortunately, we don't support `react-native-web`.
But if you can submit PR to support it - it would be great!

**Comment by geminiyellow** [comment]
woo, thank you  @malashkevich

**Comment by bkniffler** [comment]
Anyone had success with react-native-web?

**Comment by slorber** [comment]
Hey,

Just want to say this lib can work with React-Native-Web
Probably not all compos but at least some of them seems to work

You can see a demo here: https://gatsby-rnw-uikits.netlify.com/uiKittens


Note: you have to configure webpack to transpile ui-kittens source. Also, ui kittens expose some comps with only .ios.js and .android.js extension. In such case it would be helpful to provide a .web.js extension as well, even if it's just an alias for the android or the ios version. I'd recommend aliasing the web version to a version that do not use any native widget. 

I successfully exposed RkSwitch.android.js in my example, had to add to webpack resolution extensions to support .android.js as well, which is not ideal

**Comment by hmheng** [comment]
@slorber would you mind to provide steps to use UIKittens in react-native-web project? im using typescript template.

**Comment by malashkevich** [comment]
@hmheng you can go through [these steps](https://akveo.github.io/react-native-ui-kitten/docs/guides/using-with-react-native-web#using-with-react-native-web).

**Comment by hmheng** [comment]
@akveo thank you so much :D

**Comment by artyorsh** [comment]
@slorber and anyone other interested in - we fully support react-native-web starting from v4.1 👍

**Comment by hmheng** [comment]
is it possible not to use webpack? but using metro?

**Comment by artyorsh** [comment]
@hmheng we don't rely on a webpack. We use it in a playground module just because we use Expo. The final configuration depends on your project needs

**Comment by hmheng** [comment]
@artyorsh , hmmm.... do you have any idea for the error that I faced above? the code looks fine to me.. but it just throws error :(

**Comment by hmheng** [comment]
it can be compiled on android. but not web... can it be due to transpile issue?

**Comment by joshbedo** [comment]
Interested in this too, love how things look on the react native app I'm building and would love to use the UI components within a chrome extension I'm building :)
