### ISSUE TITLE
Docs: add more component usage examples

### ISSUE THREAD

**Issue by artyorsh** [akveo/react-native-ui-kitten#442]
Documentation looks poor now, need to contain more usage examples and other guides

**Comment by DaniShalash** [comment]
+1

**Comment by govem** [comment]
+1000

**Comment by 32penkin** [comment]
Hello @DaniShalash and @govem ! First of all, thanks for your replies. Expansion of documentation with examples is included in our immediate plans, so stay tuned! :)
