### ISSUE TITLE
npm start causes an error

### ISSUE THREAD

**Issue by josemob87** [akveo/react-native-ui-kitten#448]
error Cannot find module './config'. Run CLI with --verbose flag for more details.
Someone can hello my please.
I clone the git kitten after install npm and when try to do expo start:
error Cannot find module './config'. Run CLI with --verbose flag for more details.

### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [ ] feature request

### Issue description

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

### Other information:

**OS, device, package version**
```
insert information here
```

**Comment by artyorsh** [comment]
Hi @josemob87 

You don't need using expo-cli to start an app.
Consider using `npm start`. This will do the same, but with some configuration magic

Thanks for the report. We'll document the guide to start an app

**Comment by josemob87** [comment]
How can i do a configuration Magic?

**Comment by artyorsh** [comment]
You don't need do this. Consider running `npm start` instaead of `expo start`

**Comment by srivempati** [comment]
I have the same issue when running with npm start as well.

**Comment by artyorsh** [comment]
@srivempati can you please provide a detailed log of an error and some information about the device you're trying to run it?

**Comment by srivempati** [comment]
I have just checked out the repo and ran `npm install` followed by `npm start` and this is what I see. 

> 
> kittenTricks@2.0.0 start /Users/svempati/code/cortex-react-native
> expo start

Starting project at /Users/svempati/code/cortex-react-native
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
Warning: This project contains unoptimized assets. Please run `expo optimize` in your project directory.
error Cannot find module './config'. Run CLI with --verbose flag for more details.

Metro Bundler process exited with code 1
Error: Metro Bundler process exited with code 1
    at ChildProcess.packagerProcess.once (/@expo/xdl@54.1.5/src/Project.js:1594:16)
    at Object.onceWrapper (events.js:285:20)
    at ChildProcess.emit (events.js:197:13)
    at ChildProcess.EventEmitter.emit (domain.js:481:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kittenTricks@2.0.0 start: `expo start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kittenTricks@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/svempati/.npm/_logs/2019-06-12T20_05_08_144Z-debug.log

>

**Comment by artyorsh** [comment]
You're trying to run `Kitten Tricks` app.
Please report such issues for the corresponding repo to avoid misunderstanding.

Anyway, I've discovered the root of trouble. You can run it with `npm run start:prod`. We'll fix this soon. Thanks for the log details!

**Comment by srivempati** [comment]
got it, thansk!

**Comment by prideaux** [comment]
`npm run env -- prod && expo start`
