### ISSUE TITLE
RkModalImage zoom and pan feature

### ISSUE THREAD

**Issue by makafuji** [akveo/react-native-ui-kitten#45]
Hi, this is a great ui library and I like it so much.
I would like to propose an enhancement.
In RkModalImage would be nice to have the opportunity to zoom an pan the image.
I apologize in advance for my bad english.

**Comment by malashkevich** [comment]
Hello @makafuji.
Thanks for a proposal.
Sounds like a good idea.

**Comment by hardcodet** [comment]
+1: A gallery with pan/zoom would make my day (looking at how many other projects struggle with it, there may be dragons though!)

**Comment by artyorsh** [comment]
@makafuji @hardcodet 

Glad to introduce you this feature in [RkGalleryImage](https://akveo.github.io/react-native-ui-kitten/#/docs/ui-components/rkgalleryimage) :)

**Comment by willwright82** [comment]
Hi there! The ability to zoom in RKGalleryImage doesn't really solve the raised issue… I would also like to zoom in RKModalImage as we don't want to use a gallery instead.

Thanks!

**Comment by artyorsh** [comment]
Hi @willwright82 ,

If you don't want use gallery, you can just use [RkGalleryImage](https://akveo.github.io/react-native-ui-kitten/#/docs/ui-components/rkgalleryimage), like you previously used RkModalImg.

**Comment by willwright82** [comment]
Oh right, thanks @artyorsh!!
