### ISSUE TITLE
Documentation error? - Cannot read property 'background-basic-color-2' of undefined

### ISSUE THREAD

**Issue by zeekrey** [akveo/react-native-ui-kitten#450]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x ] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Installed ui-kitten as described here: [Getting started](https://akveo.github.io/react-native-ui-kitten/docs/guides/add-into-existing-project#add-into-existing-project) and implemented a list as described here: [List](https://akveo.github.io/react-native-ui-kitten/docs/components/list/overview#list)
When I run my application I get an error: 
`TypeError: Cannot read property 'background-basic-color-2' of undefined` 

**Expected behavior:**
A list is displayed.

**Steps to reproduce:**
Add ui-kitten to an existing project (without expo) and implement a list as described here: [List](https://akveo.github.io/react-native-ui-kitten/docs/components/list/overview#list)

**Related code:**

```
const ListShowcase = (props) => {
  const data = [
    'Item 1',
    'Item 2',
    'Item 3'
  ]

  const onItemPress = (index: number) => {
    // Handle item press
  }

  const renderItem = (info) => {
    return (
      <ListItem
        title={info.item}
        description='Description'
        onPress={onItemPress}
      />
    )
  }

  return (
    <List
      data={data}
      renderItem={renderItem}
    />
  )
}

export const ListItemShowcase = (props) => {
  return (
    <ListItem
      title='Title'
      description='Description'
    />
  )
}
```

### Other information:

**OS, device, package version**
```
ios
```

**Comment by artyorsh** [comment]
Thanks for report @zeekrey
This is already known issue (#440 #446) and we have a [fix for it](#447) which will be merged soon
Check out the [quick solution](https://github.com/akveo/react-native-ui-kitten/issues/440#issuecomment-501160471)
