### ISSUE TITLE
Quickstart snippet not working

### ISSUE THREAD

**Issue by Bosskee** [akveo/react-native-ui-kitten#460]
**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
The quickstart snippet from the main website is not functioning

**Expected behavior:**
The quickstart code should execute without errors

**Steps to reproduce:**
Install the UI kit + Eva via NPM
Use the code(see below)

**Related code:**
```
import React from 'react';
import { Button } from 'react-native-ui-kitten';
export const AwesomeButton = () => (
 <Button>BUTTON</Button>
```

### Other information:
The error:
`Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: %s.%s%s, undefined, You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`

This error makes no sense to me since the component is being exported, I've checked the theme folder.

**Comment by Bosskee** [comment]
> Thanks for report @Bosskee
> 
> Have you done the steps described in [this guide](https://akveo.github.io/react-native-ui-kitten/docs/guides/add-into-existing-project#install-eva-design-system-and-theme)? You need to configure an `ApplicationProvider` to use basic components like `Button`

Ah so sorry, I hadn't done that!

I tried it with thew ApplicationProvider but that seems to have generated a new error, this is my App.js:
```
import React from 'react';
import {
  mapping,
  theme,
} from '@eva-design/eva';
import { ApplicationProvider, Button } from 'react-native-ui-kitten';

export default class App extends React.Component {

   public render(): React.ReactNode {
     return (
       <ApplicationProvider
         mapping={mapping}
         theme={theme}>
         <Application/>
       </ApplicationProvider>
     );
   }
}
```
And the error I get is Unexpected token @ `public class`

**Comment by artyorsh** [comment]
Also you need to update a theme import:
```
import { mapping, light as theme } from '@eva-design/eva';
```

This is a typo we're sorry about. Btw we're going to update documentation this week to get it more detailed

Related issue #440

**Comment by Bosskee** [comment]
```
import React from 'react';
import { mapping, light as theme } from '@eva-design/eva';
import { ApplicationProvider, Button } from 'react-native-ui-kitten';

export default class App extends React.Component {

   public render(): React.ReactNode {
     return (
       <ApplicationProvider
         mapping={mapping}
         theme={theme}>
         <Application/>
       </ApplicationProvider>
     );
   }
}

```

Shouldn't this code work?

**Comment by artyorsh** [comment]
This code assumes you have some `Application` component which can be any screen in your app.
You can also replace it with `Button` to quickly review how it works

**Comment by Bosskee** [comment]
What confuses me is that the code I posted above doesn't work. This is the exact error:
```
App.js: Unexpected
token (7:10)

   5 | export default class App extends React.Component {
   6 |
>  7 |    public render(): React.ReactNode {
     |           ^
   8 |      return (
   9 |        <ApplicationProvider
  10 |          mapping={mapping}
Failed building JavaScript bundle.
```

**Comment by artyorsh** [comment]
Because you're trying to use TypeScript code in a JavaScript file

**Comment by Bosskee** [comment]
> Because you're trying to use TypeScript code in a JavaScript file

So none of the documentation code goes into App.js ?

**Comment by artyorsh** [comment]
We're working on updating it with a JavaScript examples. For now, if you're not familiar with TypeScript, use the following code:

```js
import * as React from 'react';
import { mapping, light as lightTheme } from '@eva-design/eva';
import { ApplicationProvider, Layout } from 'react-native-ui-kitten';

export default App = () => (
  <ApplicationProvider
    mapping={mapping}
    theme={lightTheme}>
    <Layout style={{flex: 1}}/>
  </ApplicationProvider>
);
```

**Comment by Bosskee** [comment]
> We're working on updating it with a JavaScript examples. For now, if you're not familiar with TypeScript, use the following code:
> 
> ```js
> import React from 'react';
> import { mapping, light as lightTheme } from '@eva-design/eva';
> import { ApplicationProvider, Layout } from 'react-native-ui-kitten';
> 
> export default App = () => (
>   <ApplicationProvider
>     mapping={mapping}
>     theme={lightTheme}>
>     <Layout style={{flex: 1}}/>
>   </ApplicationProvider>
> );
> ```

Ah ok, I understand, that works. So this should render a button then?
```
import React from 'react';
import { mapping, dark as darkTheme } from '@eva-design/eva';
import { ApplicationProvider, Layout, Button, Text } from 'react-native-ui-kitten';

export default App = () => (
  <ApplicationProvider
    mapping={mapping}
    theme={darkTheme}>
  </ApplicationProvider>
);

export const AwesomeButton = () => (
 <Button>BUTTON</Button>
);
```

**Comment by artyorsh** [comment]
This will not render a Button because you didn't place it in a `render` method. I suggest you reading [React Native documentation](https://facebook.github.io/react-native/docs/tutorial) before you start.
