### ISSUE TITLE
Interface 'TouchableIndexedProps' incorrectly extends interface 'TouchableOpacityProps'

### ISSUE THREAD

**Issue by germanp173** [akveo/react-native-ui-kitten#462]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
After configuring my React Native typescript application root by following the setup instructions from [here](https://akveo.github.io/react-native-ui-kitten/docs/guides/add-into-existing-project#configure-application-root), my typescript build now fails with the following errors:

![Capture](https://user-images.githubusercontent.com/38846104/59746041-e03ebb00-922a-11e9-9406-41dc45055580.PNG)

As a workaround, anyone using UI Kitten with Typescript will have to toggle the `skipLibCheck` flag to `true` in their `tsconfig.json`.

**Expected behavior:**
Setting up and configuring `react-native-ui-kitten` should not break the tsc build.

**Steps to reproduce:**

1. Initialize a new react native typescript application by running `react-native init TempApp --template typescript` (assuming you have the react-native cli installed)
2. Follow the `react-native-ui-kitten` setup instructions from [here](https://akveo.github.io/react-native-ui-kitten/docs/guides/add-into-existing-project#add-into-existing-project)
3. Run `tsc -p ./tsconfig.json` to execute the typescript build

**Related code:**
This problem can also be reproduced in the Kitten Tricks demo application when the `skipLibCheck` flag is toggled to `false` in their `tsconfig.json` (ignore all expo ts errors).

### Other information:

**OS, device, package version**
```
react: 16.8.3
react-native: 0.59.8
react-native-ui-kitten: 4.0.1
@eva-design/eva: 1.0.0
```

**Comment by artyorsh** [comment]
Thanks for report @germanp173. This is already known issue. We'll fix this soon. You're right about `skipLibCheck`. For now, this is a simpliest way to get your typescript projects compiled without errors

**Comment by germanp173** [comment]
Great thanks for the quick response!

**Comment by artyorsh** [comment]
This is fixed. You can update to the latest 4.0.3 version 👍

**Comment by germanp173** [comment]
@artyorsh Just verified the fix and it's solid 👌 ... thanks again for resolving this!
