### ISSUE TITLE
Error: Unable to resolve module `./theme`

### ISSUE THREAD

**Issue by dewabagasql** [akveo/react-native-ui-kitten#463]
![image](https://user-images.githubusercontent.com/31444446/59837755-f9a14d80-9377-11e9-86e2-0e0b422db089.png)

i got this error in version 3.1.2 / 3.1.4, 
but when i upgrade to 4.0 i can't use RkCard anymore. any suggestion?

**Comment by artyorsh** [comment]
Hi @dewabagasql 

Version 4.0 is the major update that has no `Rk*` components. We don't recommend updating your apps to v4 if it was previously built on top of v3.

Please use v3.1.4 as it is a last update of v3.

[Read the documentation](https://akveo.github.io/react-native-ui-kitten/) to get more information about v4 and available components
