### ISSUE TITLE
Help ! ArticleList onPress to Good Article

### ISSUE THREAD

**Issue by tcainne** [akveo/react-native-ui-kitten#467]
Hi,
I would like to navigate on the article pressed in a article list.

However, in : containers/layouts/articles/articleList1/articleList1.container.tsx
this.props.navigation.navigate('Article 1'); ------> go always to Article 0

Because, in : containers/layouts/articles/article1/article1.container.tsx
 public state: State = {
    article: articles[0],
  };

So, to to pass or bind the good article ?

Thx for your help ...

Regards,

**Comment by artyorsh** [comment]
This is not a framework issue, but it's more related to [Kitten Tricks application](https://github.com/akveo/kittenTricks)

You should learn more about [passing parameters to a route](https://reactnavigation.org/docs/en/params.html).
