### ISSUE TITLE
undefined is not an object (evaluating 'this.meta.appearances')

### ISSUE THREAD

**Issue by amansharmarepository** [akveo/react-native-ui-kitten#469]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

### Other information:

**OS, device, package version**
```
insert information here
```

**Comment by artyorsh** [comment]
Hi @amansharmarepository 
Any related code or description what have you did?

**Comment by amansharmarepository** [comment]
Steps to reproduce(I'm using react native client) -
Install ui kitten using npm
then import any component from ui kitten and when i use that component it shows that error

import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View } from 'react-native';
import { Button } from 'react-native-ui-kitten';

export default class App extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Button>BUTTON</Button>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
});

![Screen Shot 2019-06-21 at 12 07 10 PM](https://user-images.githubusercontent.com/47665774/59902944-35dab980-941d-11e9-851f-3f6e6c7426ca.png)

**Comment by artyorsh** [comment]
@amansharmarepository before using components you need to follow [this guide](https://akveo.github.io/react-native-ui-kitten/docs/guides/add-into-existing-project#configure-application-root)
