### ISSUE TITLE
Input type "textarea"

### ISSUE THREAD

**Issue by kevinweber** [akveo/react-native-ui-kitten#476]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [x] feature request

### Issue description

**Current behavior:**

Looking at https://akveo.github.io/react-native-ui-kitten/docs/components/input/overview#input, the screenshots show different component types, including `textarea` and `select` but I'm unclear on how to use them. Are those types implemented? If so, how to use them? If not, by when do you plan to implement them?

**Expected behavior:**

Support `textarea` and `select` input types.

**Comment by artyorsh** [comment]
Hi @kevinweber 
Unfortunately, these types of inputs are not currently implemented but will be available in future releases. We're working on documentation to get it more clear now
Thanks for your interest

**Comment by artyorsh** [comment]
I also recommend you looking through [API block](https://akveo.github.io/react-native-ui-kitten/docs/components/input/api#input). This would contain actual information about styling components.

**Comment by mrmurphy** [comment]
Yes! A bit added to the documentation stating that a text input *cannot* be styled to look like a text area right now would be really helpful. I thought I had found a bug and was poking around the source code.

**Comment by mrmurphy** [comment]
Actually I'm starting to think that I just haven't found the right attribute to override to set the height of the input. I've tried height, and maxHeight. Anyone know which CSS attribute I could override to make a tall input?

**Comment by artyorsh** [comment]
@mrmurphy, unfortunately, we don't have `TextArea` yet. Can be `size` property helpful for you?
If not, you set the height of the Input based on your needs with Eva mappings. [See an example](https://gist.github.com/artyorsh/b544e2569ee40441d10db78019b340e2)

**Comment by kiyasov** [comment]
It worked for me
![image](https://user-images.githubusercontent.com/16527461/66465634-e979bf00-ea89-11e9-8aab-da6fc66c25c6.png)


> ### Issue type
> **I'm submitting a ...** (check one with "x")
> 
> * [ ]  bug report
> * [x]  feature request
> 
> ### Issue description
> **Current behavior:**
> 
> Looking at https://akveo.github.io/react-native-ui-kitten/docs/components/input/overview#input, the screenshots show different component types, including `textarea` and `select` but I'm unclear on how to use them. Are those types implemented? If so, how to use them? If not, by when do you plan to implement them?
> 
> **Expected behavior:**
> 
> Support `textarea` and `select` input types.
