### ISSUE TITLE
No focusInput() in Input (react-native-ui-kitten 4.0.3)

### ISSUE THREAD

**Issue by FabianEhringer** [akveo/react-native-ui-kitten#479]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

There is no focusInput() in the current version.

**Expected behavior:**

I want to be able to focus the Input programmatically.

**Steps to reproduce:**

1. Use a simple input
2. Assign the input to a ref
3. Call focusInput() on ref

**Related code:**

```
import React, { useRef, useImperativeHandle, forwardRef } from "react";
import {
  Input as KittenInput,
  InputProps as KittenInputProps
} from "react-native-ui-kitten";

interface Props {}
export type InputProps = Props & KittenInputProps;

const InputComponent: React.FC<InputProps> = (props, ref) => {
  const inputRef = useRef();

  useImperativeHandle(ref, () => ({
    focus: () => {
      console.log("focus", inputRef.current.refs);
      inputRef.current.focusInput();
    }
  }));

  return <KittenInput ref={inputRef} {...props} />;
};

export const Input = forwardRef(InputComponent);
```

### Other information:

**OS, device, package version**
```
"react-native-ui-kitten": "^4.0.3"
```

**Comment by artyorsh** [comment]
Thanks for report @FabianEhringer

**Comment by artyorsh** [comment]
Looks like this is a global problem, related not only to an Input but for all components 😱
Working on this. Thanks again

**Comment by FabianEhringer** [comment]
You are welcome! Thank's for the quick response time. We're switching from native-base to ui-kitten and we're very excited about your framework. We're on the verge of using it in production. :)

**Comment by artyorsh** [comment]
Pleased to hear that 👍 
We're interested in any feedback on using our library in production. Feel free to contact us at contact@akveo.com

**Comment by artyorsh** [comment]
@FabianEhringer pleased to hear that 👍 
We're interested in the purposes of your migration decision. We think this could help us become even better. Can you please contact us?

**Comment by FabianEhringer** [comment]
@artyorsh Yes of course, we would be happy to help. We will contact you with the reasons for our migration and additional feedback via email. :)

**Comment by artyorsh** [comment]
contact@akveo.com - your feedback would be very helpful for us :)
