### ISSUE TITLE
Docs: Theming details and further instructions

### ISSUE THREAD

**Issue by josefrichter** [akveo/react-native-ui-kitten#480]
Theming docs could use some more details, please:

- a list of all variables that can be modified
- some "mapping" guide why do I need all those shades of each color from -100 to -800 etc.
- how to change typeface
- how to change border radius globally for all elements (and maybe locally for individual ones)

The basic documentation and approach are clear and solid, but these are some additional questions and I can't find answers to them. Been digging thru source code, but not sure I fully understand how to do it properly. Thank you.

**Comment by artyorsh** [comment]
Thanks for the feedback @josefrichter 
We are planning to add more complete guides in future, thanks for the details. Because even for us this way of styling components looks like a bit complex process.

If you have any question on mapping usage, I can give you some short explanations here, if needed

**Comment by atasanchez** [comment]
Guys, I'm currently working with Kitten UI and Eva Design system and have some questions. For example, I can add new values in the mapping of a exist component? It's possible?

**Comment by artyorsh** [comment]
Hi @atasanchez 
No, it's not possible to add, but you can [override](https://akveo.github.io/react-native-ui-kitten/docs/design-system/customize-mapping) one of registered (declared in `meta`) parameters.

**Comment by atasanchez** [comment]
@artyorsh thanks for your answer! So, to add a new value in the mapping I must create a new component?

**Comment by artyorsh** [comment]
@atasanchez yes, that will work
