### ISSUE TITLE
Toggle value is not working and onValueChange not trigger function

### ISSUE THREAD

**Issue by mreorhan** [akveo/react-native-ui-kitten#481]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Toggle open-close not working.

**Expected behavior:**
When value changed, toggle button will change open/close.
Value is true but toggle is still closed.

**Steps to reproduce:**

**Related code:**

Same with Documentation
https://akveo.github.io/react-native-ui-kitten/docs/components/toggle/examples#toggle

### Other information:

Windows 10
Google Pixel 2

**Comment by artyorsh** [comment]
Ensure you're using `checked` instead of `value` prop and `onChange` instead of `onValueChange`
The documentation is wrong now, but we've already fixed this and waiting to publish
