### ISSUE TITLE
Support for custom children in Button

### ISSUE THREAD

**Issue by dotconnor** [akveo/react-native-ui-kitten#488]
### Issue type

**I'm submitting a ...**

* [ ] bug report
* [x] feature request

### Issue description

Allow custom children of Buttons

**Current behavior:**

The button component checks if the children prop is a string and returns a Text component if it is, and returns nothing if its not.

**Expected behavior:**

If the children prop is string wrap it in a text component, if not leave it untouched.

**Related code:**
Allow both of these:
```html
<Button>
	Hello!
</Button>

<Button>
	<View>
		<Text>Hello!</Text>
	</View>
</Button>
```

**Comment by artyorsh** [comment]
Hi @dotconnor.
Unfortunately, following Eva Design System rules, we can't allow doing this.  Furthermore, I think this is unuseful and I have no examples of where it can be used - because a button is already a container which contains a text.
Thanks for the advice!

**Comment by muratakbal** [comment]
Hi @artyorsh,

A button with multiline text is where that could be useful. Here is a sample design:
 
![multiline-button](https://user-images.githubusercontent.com/1921705/72023221-15dade00-3227-11ea-8579-94fe18f2d701.png)

WDYT? Should it be possible to create a button like the above using the `Button` component or should it be a custom component that the developer needs to introduce in their own codebase?

btw, thanks for all the effort you're putting into Eva and ui-kitten
