### ISSUE TITLE
Adding the ability to use TopNavigation component for rendering the popover-based components

### ISSUE THREAD

**Issue by 32penkin** [akveo/react-native-ui-kitten#489]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [x] feature request

### Issue description

**Current behavior:**
At the moment there is no possibility to use the **TopNavigationAction** component for showing **Popover**-based components since the **TopNavigation** component restricts the expected element by the properties of **TopNavigationAction** component.

**Expected behavior:**
No ts errors. For example: *Type 'OverflowMenuProps' is not assignable to type 'TopNavigationActionProps'.*

**Related code:**

```
  private renderRightControl = (): React.ReactElement<OverflowMenuProps> => {
    const { themedStyle } = this.props;

    return (
      <OverflowMenu
        style={themedStyle.menu}
        visible={this.state.menuVisible}
        placement='bottom end'
        items={this.items}
        onRequestClose={this.onMenuPress}
        onSelect={this.onMenuItemPress}>
        <TopNavigationAction
          icon={MenuIconAuth}
          onPress={this.onMenuPress}
        />
      </OverflowMenu>
    );
  };

  private renderRightControls = (): React.ReactElement<TopNavigationActionProps>[] => {
    return ([
      this.renderRightControl(),
    ]);
  };
```

**Comment by 32penkin** [comment]
Temporary possible "solution": ```// @ts-ignore```. Anyway rendering of overflow-menu will be proper.

**Comment by artyorsh** [comment]
I have a fix for you 😄 
```ts
type TopNavigationActionElement = React.ReactElement<TopNavigationActionProps>;
type PopoverElement = React.ReactElement<PopoverElementProps>;
type PopoverElementProps = Override<PopoverProps, {
  children: TopNavigationActionElement;
}>;
type ActionElement = TopNavigationActionElement | PopoverElement;
type ActionElementProp = ActionElement | ActionElement[];
```

**Comment by 32penkin** [comment]
At the moment we can not be sure of the sufficiency of this solution. Every time we need a custom behavior TopNavigationAction - have to make such additions.

**Comment by smaldd14** [comment]
> ```ts
> type ActionElement = TopNavigationActionElement | PopoverElement;
> ```

Does this change work to allow a right control that is an overflow menu? Looking to create a 'settings' gear as a right control and when you click on it, it displays a pop over menu that has different buttons, info, etc.

Also, where (what file) to make this change?

**Comment by artyorsh** [comment]
@smaldd14 This should be pasted in `topNavigation.component.tsx` if you're using typescript without `skipLibCheck: true` in your tsconfig.
Otherwise, you're able to render what you've described without any changes

**Comment by smaldd14** [comment]
> 
> 
> @smaldd14 This should be pasted in `topNavigation.component.tsx` if you're using typescript without `skipLibCheck: true` in your tsconfig.
> Otherwise, you're able to render what you've described without any changes

I am trying to render an Overflow menu item as my top navigation rightcontrol. I have my <TopNavigation rightControl=this.renderRightControl>, and in renderRightControl I am returning a TopNavigationAction which calls this.renderOverflowmenu onPress. Code listed below.

<TopNavigation title='ReSupply' alignment='center' rightControls={this.renderRightControl()}/>

renderRightControl = (): TopNavigationActionElement[] => {
            console.log("rende rightControl);
            return ([
                <TopNavigationAction icon={this.getSettingsImage} onPress={this.renderOverflowMenu}>
                </TopNavigationAction>,
            ]);
 };

renderOverflowMenu = (): React.ReactNode => {

        console.log("trying to render overflowmenu");
        var items: OverflowMenuItemType[] = [
            { text: 'Menu Item 1' },
            { text: 'Menu Item 2' },
            { text: 'Menu Item 3' },
          ];

          onItemSelect = (index: number) => {
            // Handle Menu Item selection
          };

          toggleMenu = () => {
            this.setState({ menuVisible: !this.state.menuVisible });
          };

          return (
              <OverflowMenu
                items={this.items}
                visible={this.state.menuVisible}
                onSelect={this.onItemSelect}
                onBackdropPress={this.toggleMenu}>
                <Button onPress={this.toggleMenu}>
                  TOGGLE MENU
                </Button>
              </OverflowMenu>
            );
};


The method renderOverflowMenu is getting called, but no  overflowMenu is popping up on click. Any idea what's going on?

**Comment by artyorsh** [comment]
@smaldd14 

You don't need to render it on `TopNavigationAction` onPress.
Instead, you can wrap TopNavigationAction in OverflowMenu like it is implemented in example you shared

Your code should look similar to this:
```js
toggleMenu = () => {
  this.setState({ menuVisible: !this.state.menuVisible });
};

renderRightControls = () => (
  <OverflowMenu
    items={this.items}
    visible={this.state.menuVisible}
    onBackdropPress={this.toggleMenu}>
    <TopNavigationAction
      icon={this.renderProfileAvatar}
      onPress={this.toggleMenu}
    />
  </OverflowMenu>
);
```

But keep in mind, that this stays an experimental feature

**Comment by ng-kode** [comment]
I did as told by @artyorsh , but i got something like below:
![image](https://user-images.githubusercontent.com/35693118/64322444-28cd6f80-cff5-11e9-841e-0841b6a9b705.png)

Here's my code
```
const renderRightControls = () => {
  const MenuIcon = styling => (
    <Icon name="more-vertical-outline" {...styling} />
  );
  const [menuVisible, setMenuVisible] = useState(false);
  const [selectedIndex, setSelectedIndex] = useState(0);

  return (
    <OverflowMenu
      data={[
        {title: 'v1.0'},
        {title: 'v2.0'},
        {title: 'v3.0'},
        {title: 'v4.0'},
      ]}
      visible={menuVisible}
      selectedIndex={selectedIndex}
      onSelect={setSelectedIndex}
      onBackdropPress={() => setMenuVisible(!menuVisible)}>
      <TopNavigationAction
        icon={MenuIcon}
        onPress={() => setMenuVisible(!menuVisible)}
      />
    </OverflowMenu>
  );
};
```

Here's my package.json
```
{
  "name": "rn_fun",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "ios": "react-native run-ios",
    "android": "react-native run-android"
  },
  "dependencies": {
    "@eva-design/eva": "^1.0.1",
    "@ui-kitten/eva-icons": "^4.2.0-beta.1",
    "prop-types": "^15.7.2",
    "react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-svg": "^9.8.4",
    "react-native-ui-kitten": "^4.2.0-beta.2"
  },
  "devDependencies": {
    "@babel/core": "^7.5.5",
    "@babel/runtime": "^7.5.5",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.3.0",
    "eslint-plugin-react": "^7.14.3",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-test-renderer": "16.8.6"
  },
  "jest": {
    "preset": "react-native"
  }
}
```
Plz lemme know if further info. needed for debugging. Cheers mate.

**Comment by 32penkin** [comment]
Hi @ng-kode! Please upgrade "@eva-design/eva" package to '1.1.0-beta.1' version

**Comment by ng-kode** [comment]
Thanks @32penkin it's working. I think we should doc that btw ~

**Comment by 32penkin** [comment]
@ng-kode nice catch, thank you :) will refactor the documentation somehow...

**Comment by IgnacioGarciaGimenez** [comment]
Hello, im having the same issue as @ng-kode when implementing the popover as @artyorsh . I have the 1.1.0-beta.1 version of the package '@eva-design/eva' and the 4.2.0-beta.1 version of 'react-native-ui-kitten'. The thing is that when i want to upgrade the ui kitten package version to 4.2.0-beta.2, when running on android i get the following error:

**error: bundling failed: Error: Unable to resolve module `./calendar/calendar.component` from `C:\Users\Ignacio\source\repos\Closely\Producto\Codigo_Fuente\AppMobile\node_modules\react-native-ui-kitten\ui\index.js`: The module `./calendar/calendar.component` could not be found from `C:\Users\Ignacio\source\repos\Closely\Producto\Codigo_Fuente\AppMobile\node_modules\react-native-ui-kitten\ui\index.js`. Indeed, none of these files exist**

What should i do to be able to compile the latest beta version without the calendar component?

**Comment by artyorsh** [comment]
Calendar component is still unreleased. It will be available in UI Kitten 4.2 stable version. But thanks for your interest :)

Subscribe to [release news](https://github.com/akveo/react-native-ui-kitten/issues/517) to stay tuned 👍

**Comment by IgnacioGarciaGimenez** [comment]
Yes, but what im trying to say is that if I try to **"npm install react-native-ui-kitten@beta"** it installs version 4.2.0-beta.2 and when i try to run my projecto on android with the command **"react-native run-android"** that error that i mentioned earlier occurs and i have to downgrade to version 4.2.0-beta.1.

Do you have any solution to this problem?

**Comment by artyorsh** [comment]
@IgnacioGarciaGimenez That's quite interesting. I've just checked 4.2.0-beta.2 release sources ([see index.ts](https://github.com/akveo/react-native-ui-kitten/blob/c45b273f99/src/framework/ui/index.ts) that is actual for this release) and there is no `calendar` exported.
Please try re-install your node modules and start app with clearing cache.
```bash
watchman watch-del-all && rm -rf $TMPDIR/react-* ./node_modules ./package-lock.json && npm i && npm start -- --reset-cache
```

**Comment by artyorsh** [comment]
Well, doing something like this will not break the ts build (this is simplified [Top Navigation with Menu](https://akveo.github.io/react-native-ui-kitten/docs/assets/examples-build/#/TopNavigationWithMenu) example). 

Note the return type of the `renderMenuAction` function. It is `TopNavigationActionElement` but the actual rendered element is `OverflowMenu`. The code below will not throw ts errors.

```js
import React from 'react';
import { Icon, OverflowMenu, TopNavigation, TopNavigationAction, TopNavigationActionElement } from 'react-native-ui-kitten';

const MenuIcon = (style) => (
  <Icon {...style} name='more-vertical'/>
);

export const TopNavigationWithMenuShowcase = () => {

  const renderMenuAction = (): TopNavigationActionElement => (
    <OverflowMenu>
      <TopNavigationAction icon={MenuIcon} onPress={toggleMenu} />
    </OverflowMenu>
  );

  return (
    <TopNavigation title='Application Title' rightControls={renderMenuAction()} />
  );
};
```

**Comment by rdewolff** [comment]
I

> Well, doing something like this will not break the ts build (this is simplified [Top Navigation with Menu](https://akveo.github.io/react-native-ui-kitten/docs/assets/examples-build/#/TopNavigationWithMenu) example).
> 
> Note the return type of the `renderMenuAction` function. It is `TopNavigationActionElement` but the actual rendered element is `OverflowMenu`. The code below will not throw ts errors.
> 
> ```js
> import React from 'react';
> import { Icon, OverflowMenu, TopNavigation, TopNavigationAction, TopNavigationActionElement } from 'react-native-ui-kitten';
> 
> const MenuIcon = (style) => (
>   <Icon {...style} name='more-vertical'/>
> );
> 
> export const TopNavigationWithMenuShowcase = () => {
> 
>   const renderMenuAction = (): TopNavigationActionElement => (
>     <OverflowMenu>
>       <TopNavigationAction icon={MenuIcon} onPress={toggleMenu} />
>     </OverflowMenu>
>   );
> 
>   return (
>     <TopNavigation title='Application Title' rightControls={renderMenuAction()} />
>   );
> };
> ```

Is this supposed to work with the last stable version? I keep getting the error : 

```
TypeError: undefined is not an object (evaluating 'data.length')

This error is located at:
    in OverflowMenuComponent (created by Context.Consumer)
    in Wrapper (created by OverflowMenuComponent)
    in OverflowMenuComponent (at agenda-month-screen.tsx:70)
    in RCTView (created by TopNavigationComponent)
    in RCTView (created by TopNavigationComponent)
    in TopNavigationComponent (created by Context.Consumer)
    in Wrapper (created by TopNavigationComponent)
    in TopNavigationComponent (at agenda-month-screen.tsx:82)
    in RCTScrollContentView (at ScrollView.js:1038)
    in RCTScrollView (at ScrollView.js:1178)
    in ScrollView (at screen.tsx:43)
    in RCTView (at screen.tsx:42)
    in RCTView (at KeyboardAvoidingView.js:207)
    in KeyboardAvoidingView (at screen.tsx:36)
    in ScreenWithScrolling (at screen.tsx:63)
    in Screen (at screen-themed.tsx:17)
    in ScreenWithTheme (created by Context.Consumer)
    in Wrapper (created by ScreenWithTheme)
    in ScreenWithTheme (at agenda-month-screen.tsx:75)
    in wrappedComponent (at SceneView.tsx:98)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:89)
    in EnsureSingleNavigator (at SceneView.tsx:88)
    in SceneView (at useDescriptors.tsx:125)
    in RCTView (at BottomTabView.tsx:38)
    in SceneContent (at BottomTabView.tsx:122)
    in RNSScreen (at createAnimatedComponent.js:151)
    in AnimatedComponent (at screens.native.js:109)
    in Screen (at ResourceSavingScene.tsx:21)
    in ResourceSavingScene (at BottomTabView.tsx:117)
    in RNSScreenContainer (at screens.native.js:134)
    in ScreenContainer (at BottomTabView.tsx:101)
    in RCTView (at BottomTabView.tsx:100)
    in SafeAreaProviderCompat (at BottomTabView.tsx:99)
    in BottomTabView (at createBottomTabNavigator.tsx:41)
    in BottomTabNavigator (at bottom-navigator.tsx:62)
    in BottomNavigator (at SceneView.tsx:98)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:89)
    in EnsureSingleNavigator (at SceneView.tsx:88)
    in SceneView (at useDescriptors.tsx:125)
    in RCTView (at NativeStackView.tsx:73)
    in RNSScreen (at createAnimatedComponent.js:151)
    in AnimatedComponent (at screens.native.js:109)
    in Screen (at NativeStackView.tsx:47)
    in RNSScreenStack (at NativeStackView.tsx:36)
    in NativeStackView (at createNativeStackNavigator.tsx:69)
    in NativeStackNavigator (at root-navigator.tsx:36)
    in RootStack (at root-navigator.tsx:82)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:268)
    in ForwardRef(BaseNavigationContainer) (at NavigationContainer.tsx:39)
    in ThemeProvider (at NavigationContainer.tsx:38)
    in ForwardRef(NavigationContainer) (at root-navigator.tsx:81)
    in RootNavigator (at app.tsx:131)
    in RCTView (created by ModalPanel)
    in ModalPanel (created by ApplicationProvider)
    in ThemeProvider (created by StyleProvider)
    in MappingProvider (created by StyleProvider)
    in StyleProvider (created by ApplicationProvider)
    in ApplicationProvider (at app.tsx:130)
    in RNCSafeAreaView (at src/index.tsx:28)
    in SafeAreaProvider (at app.tsx:128)
    in App (at renderApplication.js:40)
    in RCTView (at AppContainer.js:101)
    in RCTView (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:39)

renderPopoverContentElement
    overflowMenu.component.js:83:161
OverflowMenuComponent#render
    overflowMenu.component.js:89:31
renderRoot
    [native code]:0
runRootCallback
    [native code]:0
dispatchAction
    [native code]:0
tryCallOne
    core.js:37:14
setImmediate$argument_0
    core.js:123:25
callImmediates
    [native code]:0
flushedQueue
    [native code]:0
invokeCallbackAndReturnFlushedQueue
    [native code]:0
```

Am using :

    "@eva-design/eva": "^1.4.0",
    "@ui-kitten/components": "^4.4.1",
    "@ui-kitten/eva-icons": "^4.4.1",
