### ISSUE TITLE
Bundling error

### ISSUE THREAD

**Issue by gouthamgandhi** [akveo/react-native-ui-kitten#49]
I am getting a bundling error, can someone please shed some light on what is causing this

Loading dependency graph, done.
Bundling `index.js`  [development, non-minified]  0.0% (0/1), failed.
error: bundling failed: ambiguous resolution: module `/Users/gouthamgandhi/Desktop/Riku/index.js` tries to require `react-native`, but there are several files providing this module. You can delete or fix them: 

  * `/Users/gouthamgandhi/Desktop/Riku/node_modules/react-native-drawer-layout-polyfill/node_modules/react-native/package.json`
  * `/Users/gouthamgandhi/Desktop/Riku/node_modules/react-native-drawer-layout/node_modules/react-native/package.json`
  * `/Users/gouthamgandhi/Desktop/Riku/node_modules/react-native-progress-bar/node_modules/react-native/package.json`
  * `/Users/gouthamgandhi/Desktop/Riku/node_modules/react-native-svg/node_modules/react-native/package.json`
  * `/Users/gouthamgandhi/Desktop/Riku/node_modules/react-native-tab-view/node_modules/react-native/package.json`
  * `/Users/gouthamgandhi/Desktop/Riku/node_modules/react-native-ui-kitten/node_modules/react-native/package.json`
  * `/Users/gouthamgandhi/Desktop/Riku/node_modules/react-native/package.json`
  * `/Users/gouthamgandhi/Desktop/Riku/node_modules/react-navigation/node_modules/react-native/package.json`
  * `/Users/gouthamgandhi/Desktop/Riku/node_modules/victory-native/node_modules/react-native/package.json`

**Comment by skyride99** [comment]
I get the same thing when I upgrade RN to 48.4

**Comment by sergey-kozel** [comment]
Hi @gouthamgandhi, @skyride99,

Did you manage to resolve your problem?

In this situation, the first things that I would suggest are:
* Re-install node_modules (`rm -rf node_modules && npm install`)
* Reset cache (`npm start --reset-cache`)

**Comment by skyride99** [comment]
Yes its fixed, reset cache.
