### ISSUE TITLE
Android text clip when Smallest width is high

### ISSUE THREAD

**Issue by JCKodel** [akveo/react-native-ui-kitten#493]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [X] bug report
* [ ] feature request

### Issue description

**Current behavior:**

Some texts appears clipped in high dpi Android devices:
![image](https://user-images.githubusercontent.com/379339/60465796-54646000-9c28-11e9-8f69-21fe98152d1e.png)
(screenshot from OnePlus 6)

**Expected behavior:**

All texts being displayed:
![image](https://user-images.githubusercontent.com/379339/60465857-78c03c80-9c28-11e9-9fb6-051be8e34efa.png)
(screenshot from Android Emulator (Nexus 5))

**Steps to reproduce:**

Open the Kitten Tricks official demo app in a high dpi device (OnePlus has 411dp, emulator has 360dp). You can change this setting on Android's Developer Options (OnePlus is 411 from factory):
![image](https://user-images.githubusercontent.com/379339/60466092-203d6f00-9c29-11e9-93a9-425dedb7ddc0.png)

**Related code:**

```
insert short code snippets here
```

### Other information:

**OS, device, package version**
```
insert information here
```

**Comment by JCKodel** [comment]
Actually, those settings mean nothing to the problem at hand.
It's a font-related bug in React, AFAIK: https://github.com/facebook/react-native/issues/15114

**Comment by artyorsh** [comment]
Thanks,

This is already reported in https://github.com/akveo/kittenTricks/issues/182. Also it has a [solution](https://github.com/akveo/kittenTricks/issues/182#issuecomment-505219820)
