### ISSUE TITLE
How can I focus another Input?

### ISSUE THREAD

**Issue by mreorhan** [akveo/react-native-ui-kitten#498]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Im trying to focus another input. But it doesnt happen. Give an error; _this2.refs.confirmPassword.focusInput is not a function

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
<Input onSubmitEditing={() => this.refs.confirmPassword.focusInput()}/>
<Input ref='confirmPassword'/>
```

### Other information:

**OS, device, package version**
```
     win 10
     google pixel 2
    "react": "16.8.3",
    "react-native": "0.59.9",
    "react-native-ui-kitten": "^4.0.3",
```

**Comment by artyorsh** [comment]
This type of initialization refs is deprecated. Also `focusInput` was renamed to `focus`:
```
import React from 'react';
// ...
const passwordInput = React.createRef();

const onSubmitEditing = () => {
  this.passwordRef.current.focus();
};

//...
<Input ref={this.passwordInput} placeholder='password'/>
```

**Comment by obayit** [comment]
This does not work on `Select`
