### ISSUE TITLE
Typo in Docs

### ISSUE THREAD

**Issue by deadcoder0904** [akveo/react-native-ui-kitten#500]
### Issue type

**I'm submitting a ...** 

* [x] bug report
* [ ] feature request

I think there is a typo in the docs where it is `@kitten/ui` & I think it should be `react-native-ui-kitten`.

Link → https://akveo.github.io/react-native-ui-kitten/docs/guides/create-ui-kitten-screen#modify-styles

**Comment by artyorsh** [comment]
Thanks!

**Comment by taslimy** [comment]
Just noticed this today and it kept crashing my APP. 👍

**Comment by artyorsh** [comment]
@taslimy we already have a [pr for it](#507 )
