### ISSUE TITLE
Where i can change my DEFAULT THEME to DARK THEME?

### ISSUE THREAD

**Issue by phantoxe** [akveo/react-native-ui-kitten#51]
Sorry guys.. i not find in code... the CONST where i can change my default theme...

Could u help me please?

Thanks

**Comment by malashkevich** [comment]
Hello @phantoxe.
Actually to change theme you have to call RkTheme.setTheme() and pass your new theme.
It's described here https://akveo.github.io/react-native-ui-kitten/#/docs/quick-start/theme

**Comment by malashkevich** [comment]
Closing this due to no response.
