### ISSUE TITLE
White space and horizontal scroll on the website.

### ISSUE THREAD

**Issue by Yoona8** [akveo/react-native-ui-kitten#512]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

There is a white space and horizontal scroll on your [website](https://akveo.github.io/react-native-ui-kitten/) ([screenshot](https://snag.gy/73C9hi.jpg)).

**Expected behavior:**

No white space, no horizontal scroll.

**Steps to reproduce:**

Just check it in the browser.

**Related code:**

```
insert short code snippets here
```

### Other information:

**OS, device, package version**
```
Windows 10, screen 2560 x 1080, browser Chrome
```

**Comment by artyorsh** [comment]
Thanks for reporting this!
