### ISSUE TITLE
Docs: add examples for ES6 javascript

### ISSUE THREAD

**Issue by breakhack** [akveo/react-native-ui-kitten#515]
currently all examples are written in typescript, it would be great to see examples of implementations in javascript

**Comment by Hedronmx** [comment]
I am dying because of this, trying to make them work in es6...

**Comment by taslimy** [comment]
I am having the same issues i try to do it with es6 not working out very well.

**Comment by joeyscarim** [comment]
would be extremely helpful for me as well

**Comment by breakhack** [comment]
nice!!! )))
