### ISSUE TITLE
Is there a chance you would make UI Kitten for React

### ISSUE THREAD

**Issue by thelaith** [akveo/react-native-ui-kitten#52]
I really like this kit for React Native, and I was wondering if you'd do a similar component set for the web? like Bootstrap or Bulma, but in the style of UI Kitten and perhaps something in the style of http://akveo.com/ngx-admin/#/pages/dashboard but usable for React?

Just wondering, keep up the good work!

**Comment by malashkevich** [comment]
Hello @thelaith 
Thanks for such kind words.
Unfortunately, we do not have plans to create React UI framework.
