### ISSUE TITLE
Code under Modal component documentation has bugs

### ISSUE THREAD

**Issue by cargallo** [akveo/react-native-ui-kitten#525]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ X ] bug report
* [ ] feature request

### Issue description

**Current behavior:**
The code under Modal component documentation has bugs. 
The line 20 is closing Text with Test
<Text>Hi! This is Modal Component!</Test>
And the buttons in lines 15 and 21 are using a prop called title that is not recognized. I changed 
to this <Button onPress={() => this.setVisible(true)} >Show Modal</Button>

**Expected behavior:**
That you could do copy & paste without need to change code. 

**Steps to reproduce:**
Just copy the code into kittens tricks app in a container.

**Comment by artyorsh** [comment]
Thanks for reporting this!

**Comment by 32penkin** [comment]
Hello @cargallo ! Thank you for your report. Will be fixed in the next patch.
