### ISSUE TITLE
📆 [Sticky] UI Kitten 4.2 Discussion & Roadmap

### ISSUE THREAD

**Issue by artyorsh** [akveo/react-native-ui-kitten#539]
This is a communication-open issue indicating version 4.2 roadmap. Our plan is:

**Features**

- Popover auto-placement #258 
- RTL support #561 

**UI components**

- Select #523 
- Calendar #520 
- Drawer #521 
- Activity Indicator #519 

**Modules**

In version 4.2, we're going to become a modular framework. This means it will help you with creating apps with more flexibility allowing to install the only things you need! Besides the main package of UI components, we also going to introduce following easily adaptable to UI Kitten packages:
- [Eva Icons](https://akveo.github.io/eva-icons) #522. A pack of more than 480 beautifully crafted Open Source icons. 
- [Moment](https://momentjs.com/) and [date-fns](https://date-fns.org/) adapters for Calendar component. By default, a calendar component will work with a native date object, but we also going to introduce additional packages that will allow you to work with moment or date-fns (if you're looking for easier formatting) 
- Template App Module #553. Supporting module to make a start as easy as `react-native init --template ui-kitten`

**Documentation**

- Add more ready-to-go examples in the component Overview section #442

Feel free to add your proposals on what we need to include!

**Comment by sudomann** [comment]
I'm curious, whats the timeline for the features on your roadmap?

**Comment by malashkevich** [comment]
Hello @sudomann.
We don't have an exact date for this. 
I guess 4.2 will be landed approx. at the end of August - start of September.

**Comment by klaaz0r** [comment]
Are there any plans for audio and video components?

**Comment by malashkevich** [comment]
@klaaz0r actually we don't plan something similar into 4.2. But it would be nice if you create an issue with the description of what you need. So we would know the users' opinions.

**Comment by klaaz0r** [comment]
@malashkevich will do! Thanks for your response!

**Comment by sudomann** [comment]
I see the documentation shows different input types:
<img width="662" alt="Screen Shot 2019-08-23 at 6 11 52 PM" src="https://user-images.githubusercontent.com/16912950/63626531-8616f900-c5d1-11e9-916b-db499b816d45.png">

But I have only been able to get a plain single line input field. The docs don't demonstrate how to change to a picker, for example, even though the image shows it. Perhaps the picker should be made into its own component like react-native's `Picker`?

**Comment by artyorsh** [comment]
@sudomann Yes, we have this documentation issue. But in 4.2 will include this component. We call it `Select` 🚀

**Comment by artyorsh** [comment]
@sudomann glad to announce you're able to use this component. We just released a v4.2 beta, so you can update with `npm i react-native-ui-kitten@beta`

**Comment by sudomann** [comment]
Awesome! Right on the weekend 🙂 so is there any documentation for 4.2 improvements yet?

**Comment by artyorsh** [comment]
Yes. Check this [release comment](https://github.com/akveo/react-native-ui-kitten/issues/517#issuecomment-526539301). I also recommend you subscribing to this issue to stay tuned on the latest updates 👍

**Comment by ibraveboy** [comment]
not able to import { Icon } from react-native-ui-kitten
and also { IconRegistry }

**Comment by artyorsh** [comment]
@ibraveboy It's only available in 4.2-beta for now: `npm i react-native-ui-kitten@beta`

**Comment by ibraveboy** [comment]
@artyorsh thank you i was following the documentation and this was not mentioned there. Thanks again.

**Comment by sudomann** [comment]
Nice work with releasing 4.2! :)

I don't know if I'm doing something wrong or this is a bug, but when i try to use Calendar or Datepicker I'm getting:

```
console.error: "
Calendar: unsupported configuration.
Using UI Kitten components is only possible with configuring ApplicationProvider.
📖 Documentation: https://akveo.github.io/react-native-ui-kitten/docs/guides/install-ui-kitten#configure-application-root

In case you have all in place, there might be an incorrect usage of a "styled" function.
📖 Documentation: https://akveo.github.io/react-native-ui-kitten/docs/design-system/custom-component-mapping"

install/console.error
    YellowBox.js:63:8
StyleConsumerService
    styleConsumer.service.js:23:20
Wrapper/_this.onInit
    styleConsumer.component.js:119:31
Wrapper/_this.renderWrappedElement
    styleConsumer.component.js:133:25
onmessage</<
    debuggerWorker.js:80:58
```

My code for both are exactly as your docs have it, very simple example.

**Comment by artyorsh** [comment]
@sudomann You also need to update eva 
`npm i @eva-design/eva@latest`

**Comment by sudomann** [comment]
Wow, looks very nice, and I like the new changes to eva styling. You guys are doing some amazing work here 👍
