### ISSUE TITLE
RkModalImage is not working properly on iPad

### ISSUE THREAD

**Issue by pascalknecht** [akveo/react-native-ui-kitten#54]
Hello there.
First of all many thanks for your great UI Framework you created.
I created a small app for an iPad and the gallery functionality does not work there. If I click on an image the selected image is not shown but the first image in the collection is displayed.
Any help would be appreciated.
Example Code here:

`export default class Overview extends React.Component {

    static navigationOptions = ({navigation, screenProps}) => ({
        header: (
            <Header navigation={navigation}/>
        )
    });

    state = {
        products: [],
        images: []
    };

    constructor(props) {
        super(props);
        this.renderItem = this._renderItem.bind(this);
        this.renderFooter = this._renderFooter.bind(this);
    }

    async componentDidMount() {
        const products = await api.getProductsByCategory(this.props.navigation.state.params);
        const images = products.map((p) => {
            return {uri: p.src}
        });
        this.setState({products, images});
    }

    _renderFooter(options) {
        if (this.state.products.length === 0) {
            return null;
        }

        const currentProduct = this.state.products[options.pageNumber - 1];

        return (
            <View style={{justifyContent: 'center'}}>
                <View style={{width: 350, justifyContent: 'space-between', alignItems: 'center'}}>
                    <View>
                        <Text style={{color: 'white'}}>{currentProduct.name}</Text>
                        <Text style={{color: 'white'}}>{currentProduct.price}</Text>
                    </View>
                    <View>
                        <Like product={currentProduct}/>
                    </View>
                </View>
            </View>
        );
    }

    _renderItem(product, imageIndex) {
        return (
            <TouchableOpacity
                delayPressIn={70}
                activeOpacity={0.8}
                key={imageIndex}>
                <RkCard style={styles.listItem}>
                    <View rkCardHeader>
                        <View
                            style={{flexDirection: 'row', justifyContent: 'space-between', width: '100%'}}>
                            <View>
                                <RkText rkType='header4' style={{fontSize: 25, fontWeight: 'bold'}}>{product.name}</RkText>
                                <RkText rkType='secondary2 hintColor'>Grösse</RkText>
                            </View>
                            <View>
                                <Like product={product}/>
                                <RkText>{product.price.toString()}</RkText>
                            </View>
                        </View>
                    </View>
                    <RkModalImg
                        source={this.state.images} index={imageIndex}
                                style={{width: '100%', height: 600, resizeMode: 'cover'}} modalImgStyle={{resizeMode: 'contain'}}/>
                </RkCard>
            </TouchableOpacity>
        )
    }

    render() {
        if (this.state.products.length === 0) {
            return (
                <Loader/>
            )
        }

        return (
            <ScrollView>
                <View style={styles.list}>
                    {this.state.products.map((product, imageIndex) => this.renderItem(product, imageIndex) )}
                </View>
            </ScrollView>
        );
    }
}

const styles = RkStyleSheet.create(theme => ({
    container: {
        margin: 8
    },
    list: {
        flexDirection: 'row',
        flexWrap: 'wrap'
    },
    listItem: {
        maxWidth: Dimensions.get('window').width / 3,
        flex: 0.33333,
        backgroundColor: '#fff',
        borderWidth: 1,
        borderColor: '#363636',
        margin: 8
    },
}));`

**Comment by sergey-kozel** [comment]
Hi @pascalknecht,

I cannot reproduce your issue. Is this happened only on iPad and on iPhones all work correctly? Also tell me please did you use simulator or real device and which version of the framework do you use?

Thanks!
