### ISSUE TITLE
Images are not visible in ListItem component via url

### ISSUE THREAD

**Issue by MuhammedKpln** [akveo/react-native-ui-kitten#541]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
It only shows a gray bar but nothing else
![image](https://i.imgur.com/05HeRhC.png)

**Expected behavior:**
It should show the image provided from Image component

**Related code:**

Providing my image to my list component as an object like this (just a wrapper to make it more compatible with my app): 
```
icon: () => <Image source={{ uri: user.actor_details.profile_picture }} style={{ width:50, height:50 }}/>


```

You can see my wrapper component for list [here](https://gist.github.com/MuhammedKpln/f10236977f2dc60ce59b9b3485859460)

### Other information:

**OS, device, package version**
Tested on LG G7 ThinQ on Android 9.0 also on Emulator which runs on Android Q, both gives me same results.
```
"react-native-ui-kitten": "^4.1.0",
"react-native": "0.59.3",
"react": "16.8.3"
"@eva-design/eva": "^1.0.1"
```

**Comment by MuhammedKpln** [comment]
It actually renders the image when you providing local image via Image component with require() function, but not when you are tyring to get image via url.

**Comment by 32penkin** [comment]
Hello @MuhammedKpln! Thanks for reporting this! Unfortunately, I could not reproduce the bug described by you. However, I can share a working example:
```
import React from 'react';
import {
  ListRenderItemInfo,
  ImageProps,
  Image,
} from 'react-native';
import {
  ListItem,
  ListItemProps,
  List,
} from '@kitten/ui';
import { StyleType } from '@kitten/theme';

interface ListItemType {
  title: string;
  description: string;
  iconUri: string;
}

export class ListContainer extends React.Component {

  private getListItemExample = (item: any, index: number): ListItemType => {
    return {
      title: `Item ${index}`,
      description: `Item ${index} description`,
      iconUri: 'https://akveo.github.io/eva-icons/fill/png/128/star.png',
    };
  };

  private renderIcon = (style: StyleType, uri: string): React.ReactElement<ImageProps> => {
    return (
      <Image
        style={style}
        source={{ uri }}
      />
    );
  };

  private renderItem = (info: ListRenderItemInfo<ListItemType>): React.ReactElement<ListItemProps> => {
    return (
      <ListItem
        title={info.item.title}
        description={info.item.description}
        icon={(style: StyleType) => this.renderIcon(style, info.item.iconUri)}
      />
    );
  };

  public render(): React.ReactNode {
    const items: ListItemType[] = new Array(20)
      .fill(null)
      .map(this.getListItemExample);

    return (
      <List
        data={items}
        renderItem={this.renderItem}
      />
    );
  }
}
```

**Comment by MuhammedKpln** [comment]
Turns out List Item component converts all icons to a grayscale color which that's why it didn't work. Well than we can put all other stuff inside children prop. Tought it will be easy just set icon to a random image

**Comment by artyorsh** [comment]
@MuhammedKpln Was it resolved for you? Btw, can it be reproduced if you pass a style prop to an `Image` in your `icon` method (you've omitted this)

**Comment by Floridus** [comment]
I had the same error with an external image. I found out that it was the style that was given. Each picture was filled with the tintColor. So I deleted the tintColor style and now it works.

That is the style for the "icon":
`{ width: 40,
height: 40,
marginHorizontal: 8,
tintColor: '#8F9BB3' }`

So I removed the tintColor.

```
renderIcon = (style, uri) => {
    delete style.tintColor
    return (
      <Image
        style={style}
        source={{ uri }}
      />
    )
  }
```

**Comment by jaksm** [comment]
> I had the same error with an external image. I found out that it was the style that was given. Each picture was filled with the tintColor. So I deleted the tintColor style and now it works.
> 
> That is the style for the "icon":
> `{ width: 40, height: 40, marginHorizontal: 8, tintColor: '#8F9BB3' }`
> 
> So I removed the tintColor.
> 
> ```
> renderIcon = (style, uri) => {
>     delete style.tintColor
>     return (
>       <Image
>         style={style}
>         source={{ uri }}
>       />
>     )
>   }
> ```

Also, this is useful when you want to adjust image size, just delete `style.width` & `style.height`
