### ISSUE TITLE
Help - Date Input & fix width Control?

### ISSUE THREAD

**Issue by ImAbhishekTomar** [akveo/react-native-ui-kitten#550]
Hi,

How can i implement date picker in your UI tool kit?
How can i create fix width button according to contain text? 

Thanks.

**Comment by artyorsh** [comment]
Hi👋

Button component is already self-sized, so I think it does what you need. Please provide more details or a screenshot what do you expect for

The same about datepicker. It's not included in current version, but in the next 4.2 we will announce a calendar component.
Could it be helpful?

**Comment by IAmAbhishekTomar** [comment]
I will share some examples for my button question...

**Comment by ImAbhishekTomar** [comment]
I think the issue is in my project setup, not in the toolkit, because when I try to clone the issue on the snack it works fine. but in my solution Button automatically fixed as per screen size.

https://snack.expo.io/@abhi.tomar/evabuttonissue

ISSUE CLOSE : ISSUE IN MY PROJECT SETUP.
