### ISSUE TITLE
Input: unsupported configuration. Check one of the following prop values

### ISSUE THREAD

**Issue by mhmdAljefri** [akveo/react-native-ui-kitten#565]
### Issue 
* [x] bug report

### Issue description
Once I added size props with value = '**tiny**'
**_Determines the size of the component. Can be giant, large, medium, small, or tiny. Default is medium._**
Input: unsupported configuration.
Check one of the following prop values {
  "appearance": "default",
  "variants": [
    "tiny"
  ],
  "states": []
}
📖 Documentation: https://akveo.github.io/react-native-ui-kitten/docs/components/input/api

**Current behavior:**
The size was not changed

**Expected behavior:**
Show small Input

```
import React from 'react';
import { Input as UIKInput } from 'react-native-ui-kitten';

export default function Input(props) {
  return <UIKInput {...props} size="tiny" style={{ marginBottom: 20 }} />;
}
```

### Other information:

**OS, device, package version**
```
    OS: Linux 4.15 Ubuntu 16.04.4 LTS (Xenial Xerus)
      CPU: (4) x64 Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
      Memory: 123.69 MB / 5.73 GB
      Shell: 5.1.1 - /usr/bin/zsh
    Binaries:
      Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
      Yarn: 1.6.0 - /usr/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.0/bin/
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: ^0.59.10 => 0.59.10 
    npmGlobalPackages:
      react-native-create-library: 3.1.2
```

**Comment by artyorsh** [comment]
Hi 👋 
We're sorry, but this is a documentation issue. You can use one of the following sizes: `small`, `medium`, or `large`

Thanks for reporting this

**Comment by adnan909** [comment]
@artyorsh can we customize input style so that it is even smaller then `small`.? i tried changing minHeight:20 but it doesn't change height of input. it seems like minHeight stays at `small` i.e 40 even if i change it.

**Comment by artyorsh** [comment]
Just noticed this is quite tricky to do with inline styling. Thanks for the question
You can try doing [with extending Eva configuration](https://akveo.github.io/react-native-ui-kitten/docs/design-system/customize-mapping#merge-mappings)

**Comment by artyorsh** [comment]
[Example](https://gist.github.com/artyorsh/cebf547ddea1df50b5daa4b9beca4d96)

**Comment by adnan909** [comment]
Thanks @artyorsh. I will try this.

**Comment by rickerp** [comment]
I am having a similar issue:
```
 WARN  Input: unsupported configuration.
Check one of the following prop values: {
  "appearance": "default",
  "variants": [
    "medium"
  ],
  "states": []
}
```

**Comment by artyorsh** [comment]
@greenfrvr up. I think something is going wrong with recent update of eva-design packages. We are experiencing weird issues too (custom mapping setup), and I have seen the reported above. Can come with more details later.

**Comment by manuelmhtr** [comment]
> I am having a similar issue:
> 
> ```
>  WARN  Input: unsupported configuration.
> Check one of the following prop values: {
>   "appearance": "default",
>   "variants": [
>     "medium"
>   ],
>   "states": []
> }
> ```

I'm facing the same issue too. I'm not even sending those props.

**Comment by manuelmhtr** [comment]
Solved it. The problem is that defaults are no longer applied when sending `null`, therefore, `null` is an invalid prop value.
For example:
```jsx
const CustomButton = ({
  status,
}) => (
  <Buttom status={status} style={style.customButton} />
);

CustomButton.defaultProps = {
  status: null,
};
```

Raised the warning. I had to change it to:
```jsx
const CustomButton = ({
  status,
}) => (
  <Buttom status={status} style={style.customButton} />
);

CustomButton.defaultProps = {
  status: 'basic',
};
```
