### ISSUE TITLE
Remove 'Rk' from components

### ISSUE THREAD

**Issue by periabyte** [akveo/react-native-ui-kitten#57]
What do you think about removing "Rk" from components for simplicity like react-native base components? 
NativeBase, React Native Elements use this approach

```
<RkText rkType="hero"></RkText>
<Text type="hero"></Text>
```

**Comment by malashkevich** [comment]
Hello @periabyte actually there is a reason to use Rk prefix. Sometimes u may need both RkText and Text component and in order to avoid this ambiguity, we define those prefixes.
But in case you want to use `Text` component - you can wrap our `RkText` in your own `Text component` and use it.

**Comment by micimize** [comment]
@periabyte you can also alias imports:
```js
import { RkText as Text } from 'react-native-ui-kitten'
```
It might be nice to at some point have `react-native-ui-kitten/unprefixed` for applications that are pervasively `ui-kitten` based eventually, but that seems like more trouble than it's worth atm
