### ISSUE TITLE
Themeing docs - Input

### ISSUE THREAD

**Issue by yoerivdm** [akveo/react-native-ui-kitten#571]
Hi, not really a bug, rather a call for help/info.

I'm searching for a good way to style the focus-border of the input component, can't seem to find the current blue color :-). It looks like it's being used to style the tabcomponent active tab-color too ...

Any help or some more themeing info per component would be great!

**Comment by artyorsh** [comment]
Hi @yoerivdm 👋  

To style an Input in active state, you can use Eva mappings to override pre-defined stylings: [Read the guide](https://akveo.github.io/react-native-ui-kitten/docs/design-system/customize-mapping#customize-component-mapping) or [see an example](https://gist.github.com/artyorsh/03e597af1175ce9e8fc593aae6bf9f28)

**Comment by yoerivdm** [comment]
I can only say: big thanks for the gist :-)
Clarifies a lot
