### ISSUE TITLE
Top Navigation Controls mutli-press

### ISSUE THREAD

**Issue by Farangi** [akveo/react-native-ui-kitten#577]
I was using the top-navigation controls, and i noticed that if you press a navigation-control multiple times, it generates multiple events simultaneously.

I was opening a modal with a top-navigation control, and if you press it multiple times, it opens multiple modals, which are unable to close later on, and it causes the application to get stuck.

Is there a workaround to that? Or is there anyway i could disable the navigation control after the first press event?

**Comment by 32penkin** [comment]
Hi @Farangi ! Thanks for your reply. Could you please share the code example with us, it seems to me that I know the issue but just want to make sure.

**Comment by artyorsh** [comment]
@Farangi you just need to apply debounce effect to prevent such issues. This is not a framework issue, but it is well known in frontend development. Check [lodash.debounce](https://lodash.com/docs/4.17.15#debounce)
