### ISSUE TITLE
Button text with custom font does not center vertically

### ISSUE THREAD

**Issue by EdmundMai** [akveo/react-native-ui-kitten#582]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
My button text does not center vertically

**Expected behavior:**
I expect the text to be centered vertically

**Steps to reproduce:**
Download this font: http://fontsgeek.com/fonts/Adobe-Caslon-Pro-Regular
Put the .TFF file in `src/assets/fonts/AdobeCaslonPro-Regular.ttf`

App.js:

```
import * as Font from "expo-font";
import { Button } from "react-native-ui-kitten";
import { mapping, light as lightTheme } from "@eva-design/eva";

const App = () => {
  useEffect(() => {
    Font.loadAsync({
      "adobe-caslon-pro-regular": require("./src/assets/fonts/AdobeCaslonPro-Regular.ttf"),
    });
  }, []);

  return (
            <ApplicationProvider mapping={mapping} theme={lightTheme}>
                    <Button
                      textStyle={{ fontFamily: "adobe-caslon-pro-regular" }}
                      onPress={console.log}>
                      CREATE ACCOUNT
                    </Button>
            </ApplicationProvider>
  );
};

```

Result:

![Screenshot_8_27_19__9_02_PM](https://user-images.githubusercontent.com/1857068/63818220-09a45300-c90e-11e9-8c78-e82bf984b845.png)

**Related code:**

```
insert short code snippets here
```

### Other information:

**OS, device, package version**
```
    "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",

```

**Comment by artyorsh** [comment]
Hi @EdmundMai 
This is because Eva Design System configured to use OpenSans fonts. Try switching to use them or try using another `lineHeight` style property. That's already known issue which we're unable to fix currently

Thanks

**Comment by artyorsh** [comment]
Btw I have the same issue on our another internal project, and I can share you solution if I find it

**Comment by artyorsh** [comment]
Would be glad to do this when I have it :)
