### ISSUE TITLE
Theming example does not work

### ISSUE THREAD

**Issue by EdmundMai** [akveo/react-native-ui-kitten#584]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

I am trying to create a label with a custom background color. Like the one described here: https://akveo.github.io/react-native-ui-kitten/docs/design-system/use-theme-variables#declare-custom-component

**Current behavior:**
The background color is not blue

**Expected behavior:**
The background color should be blue

**Steps to reproduce:**
Copy the lines below

**Related code:**

Given I have a file in `src/components/shared/Label.tsx`

```
import * as React from "react";
import { View } from "react-native";
import { withStyles } from "react-native-ui-kitten";

const AwesomeView = props => {
  const { themedStyle, style, ...restProps } = props;

  return <View {...restProps} style={[themedStyle, style]} />;
};

export default withStyles(AwesomeView, theme => ({
  backgroundColor: "blue", // theme["color-primary-500"],
}));
```

When I use it like this:

```
                      <Label>
                        <Text>How do you identify?</Text>
                      </Label>

```

Then it should render render
And have a different background color

### Other information:

**OS, device, package version**
```
insert information here
```

**Comment by artyorsh** [comment]
omg, that's a quite strange solution :)
sorry for late reply. I guess checking [this issue](https://github.com/akveo/react-native-ui-kitten/issues/464) can solve your trouble. Please leave feedback if so
