### ISSUE TITLE
Basic Select component throws errors

### ISSUE THREAD

**Issue by Antonhansel** [akveo/react-native-ui-kitten#595]
### Issue type

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
When trying to implement a very basic `Select` component in an existing app using react-native-ui-kitten, I get the following error:

```
Select: unsupported configuration.
Using UI Kitten components is only possible with configuring ApplicationProvider.
📖 Documentation: https://akveo.github.io/react-native-ui-kitten/docs/guides/install-ui-kitten#configure-application-root

In case you have all in place, there might be an incorrect usage of a "styled" function.
📖 Documentation: https://akveo.github.io/react-native-ui-kitten/docs/design-system/custom-component-mapping
```

**Expected behavior:**

The select component should show up

**Steps to reproduce:**

A very basic example like this triggers the bug on my end:

```
import React from 'react';
import { mapping, light as lightTheme } from '@eva-design/eva';
import { Select, ApplicationProvider } from 'react-native-ui-kitten';

interface MyProps {}
interface MyState {}

class App extends React.Component<MyProps, MyState>  {
  render() {
    return (
        <ApplicationProvider
          mapping={mapping}
          theme={lightTheme}
        >
        <Select
          data={[]}
          onSelect={() => {}}
        />
        </ApplicationProvider>
    );
  }
}
```

### Other information:

```
- iOS (not tested on Android)
- "react-native-ui-kitten": "^4.2.0-beta.2"
- "@eva-design/eva": "^1.0.1"
```

Am I missing something ?

Thank you 🙏

**Comment by 32penkin** [comment]
Hi @Antonhansel! Thanks for the issue. Please try to upgrade '@eva-design/eva' package to version '1.1.0-beta.1'. I am practically sure that this is a mistake. Let me know if something goes wrong.

**Comment by Antonhansel** [comment]
I verified that I was on the last release of `eva` but I forgot to check beta releases, thank you 🙏
