### ISSUE TITLE
RkAvoidKeyboard is not reacting dynamic for text inputs

### ISSUE THREAD

**Issue by kay-es** [akveo/react-native-ui-kitten#60]
Hey guys,

if I have a text input field within a RkAvoidKeyboard and focus on the upmost text input the keyboard comes up and the focused text input slides out of the visible screen. I'm now not able to see what im typing. Is there any solution for that?

best regards
kay

**Comment by slawek-mazur** [comment]
Same problem here. Looking at code it seems that it's ment to work only on **ios**.

`RkAvoidKeyboard` methods 

`componentWillMount` and `componentWillUnmount` at first line do this kinda check `if (Platform.OS === 'ios')`

**Comment by sergey-kozel** [comment]
Hello @kay-es, @slawek-mazur,

Sorry, we do not longer plan to support this feature and going to remove it from the library soon.

Please, try to find another solution.
