### ISSUE TITLE
Bug during using Select in Modal

### ISSUE THREAD

**Issue by DonWasyl** [akveo/react-native-ui-kitten#600]
### Issue type

**I'm submitting a ...**

* [X] bug report
* [ ] feature request

### Issue description

**Current behavior:**
When I change value in Select component inside opened modal window, then something weird happened with modal.
Please check this video:
https://streamable.com/lfmxo

It's happening with RN component also.

**Expected behavior:**
Modal should behave normally

**Steps to reproduce:**
Add Select component into Modal window

**Related code:**
I prepared App.js with included modal and select component.
https://pastebin.com/ttfsRbty

### Other information:

**OS, device, package version**
```
Pixel 2 Emulator, Android 7.0 API 24
UI Kitten: 4.2.0-beta.2
```

**Comment by 32penkin** [comment]
Hi @DonWasyl ! Thanks for the issue, very interesting. I will check and let you know if there are any results. Keep posted.

**Comment by 32penkin** [comment]
@DonWasyl, by the way I've already found the bug. The fix will be in the next stable version. Thank you!
