### ISSUE TITLE
Tab content inside TabView is not taking all available height

### ISSUE THREAD

**Issue by eblancperso** [akveo/react-native-ui-kitten#601]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Content inside a Tab does not take all available height.

**Expected behavior:**
It should take all available height.

**Steps to reproduce:**
I tried to put the "flex: 1" style on each node individually but the content of the tab never takes all the available height. Is there something i'm not doing right?

**Related code:**

```
<View>
  <TopNavigation title="Title" alignment="center" />
  <TabView selectedIndex={selectedTabIndex} onSelect={onTabSelected}>
    <Tab title="TAB 1">
      <Text style={{ backgroundColor: "red" }}>Tab 1</Text>
    </Tab>
    <Tab title="TAB 2">
      <Text style={{ backgroundColor: "blue" }}>Tab 2</Text>
    </Tab>
  </TabView>
</View>
```

### Other information:

**OS, device, package version**
```
react-native using expo sdk-34.0.0.
react-native-ui-kitten 4.1.1
```

![image](https://user-images.githubusercontent.com/13789373/64396633-3e11c080-d02c-11e9-8be5-c0c2d0cdf00a.png)

**Comment by artyorsh** [comment]
Hi @eblancperso. Thanks for reporting. Fortunately, we've already faced this issue and will be able to fix this in the next release (I guess). If you need a quick solution for this, take a look at [this answer](https://github.com/akveo/react-native-ui-kitten/issues/581#issuecomment-525607822)

**Comment by muhzi4u** [comment]
@eblancperso Did you able to fix this issue?

**Comment by ayozebarrera** [comment]
@muhsin-k you have to pass **style** property to _TabView_
