### ISSUE TITLE
Docs: OverflowMenu 'data' prop type is instead 'items'

### ISSUE THREAD

**Issue by Kejoku** [akveo/react-native-ui-kitten#606]
In the documentation for the usage and API of the OverflowComponent, the `data` prop seems to be incorrect/legacy at the moment, instead its currently named `items`.  A working usage sample is:

```javascript

render () {
    let { menuVisible, selectedMenuIndex } = this.state
    let items = [{
        title: 'Item 1'
    }]
    return (
        <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
            <OverflowMenu
            onSelect={this.onSelect}
            visible={menuVisible}
            selectedIndex={selectedMenuIndex}
            onSelect={this.onSelect}
            items={items}
            />
        </View>
    )
}

```

Sorry it's not typescript

**Comment by 32penkin** [comment]
Hi @Kejoku! Thanks, will be fixed.

**Comment by 32penkin** [comment]
By the way, the right property is "data". So everything is correct in the documentation

**Comment by artyorsh** [comment]
I guess @Kejoku is using version 4.1, that exports `items`
Try updating to the beta version :)
`npm i react-native-ui-kitten@beta @eva-design/eva@beta`

**Comment by Kejoku** [comment]
@artyorsh thanks for that, you're completely right. I didn't realize I'd locked the version to 4.1.0 😄
