### ISSUE TITLE
Input has extra vertical paddings on Android

### ISSUE THREAD

**Issue by artyorsh** [akveo/react-native-ui-kitten#609]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

`Input` component has extra text paddings on Android

**Current behavior:**

[Screenshot on iOS](https://take.ms/9J4Nb)
[Screenshot on Android](https://take.ms/3de3D)

**Workaround:**
Currently, to achieve same UI we can use
```jsx
const styles = StyleSheet.create({
  text: Platform.select({
    ios: undefined,
    android: { paddingVertical: 0 },
  });
});

// ...

render() {
  return (
    <Input textStyle={styles.text} />
  );
}
```

### Other information:

**OS, device, package version**
```
Nexus 5x API 26
```

**Comment by artyorsh** [comment]
Looks like it was RN issue, as it was fixed with updating dependencies to latest in our playground applications

**Comment by tuanna1601** [comment]
@artyorsh Hi, could you tell me which dependencies you updated? I'm having this issue too using `react-native@0.61.2` and `react-native-ui-kitten@4.2.0`

**Comment by artyorsh** [comment]
@tuanna1601 can you please try running UI Kitten 4.3?
```
npm i react-native-ui-kitten@beta @eva-design/eva@beta
```

**Comment by tuanna1601** [comment]
@artyorsh I updated `react-native-ui-kitten` and `@eva-design/eva` but no good

**Comment by Lynss** [comment]
I met the same problem.

**Comment by aganov** [comment]
Same issue...

```
"react-native": "0.61.5",
"react-native-ui-kitten": "^4.3.1",
"@eva-design/eva": "^1.3.0",
```

**Comment by tuanna1601** [comment]
We were able to solve this issue by adding this to custom mappings: 
```
const mapping = {
  components: {
  ...
    Input: {
      appearances: {
        default: {
          mapping: {
            ...Platform.select({
              android: {
                textMarginHorizontal: 2,
              },
              ios: {
                textMarginHorizontal: 8,
              },
            }),
          }
        }
      }
    }
  ...
  }
}
```

**Comment by artyorsh** [comment]
@tuanna1601 I just wonder why horizontal?

**Comment by tuanna1601** [comment]
@artyorsh I'm sorry, it's my bad, I copied the wrong one, I edited my answer above

**Comment by bmbknds** [comment]
I got the same problem, can you fix it ? 
I tried to use lower version of @eva/design like Kitten tricks  App but the input still bigger on andori.

**Comment by artyorsh** [comment]
@bmbknds we have no solution published in the actual version, you can use the workaround I described

**Comment by papigers** [comment]
Same issue here...
```
"@eva-design/eva": "^1.3.1",
"@ui-kitten/components": "4.3.2",
"@ui-kitten/eva-icons": "4.3.2",
"react": "^16.12.0",
"react-native": "^0.61.5",
```

**Comment by Frans-L** [comment]
Hey, is there any update? Has anyone started do a fix / pr?

**Comment by artyorsh** [comment]
@Frans-L yes. This will be fixed in next release
