### ISSUE TITLE
Spinner fails to render

### ISSUE THREAD

**Issue by jpaulomotta** [akveo/react-native-ui-kitten#612]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

Spinner fails to render with:

Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: %s.%s%s, undefined,  You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

**Expected behavior:**
The Spinner would render.

**Steps to reproduce:**
I'm just adding the spinner to the code and it doesn't work. Removing the spinner makes the component render

**Related code:**

```
import { Text, List, withStyles, Spinner } from 'react-native-ui-kitten'
//...
function Stations({stations, loading, error, themedStyle}) {
    return (
      <SafeAreaView>
        <View style={{...themedStyle.container, ...themedStyle.containerBlankState }}>
          <Spinner />
          <Text category="h4">Carregando os dados das suas estações</Text>
        </View>
      </SafeAreaView>
    )
}
```

### Other information:
I'm running eva-design.eva **^1.1.0-beta.1**

```
"@eva-design/eva": "^1.1.0-beta.1",
"react-native-ui-kitten": "^4.1.1",
```

**OS, device, package version**
```
Running on IPhone XR 12.1 Simulator
```

**Comment by artyorsh** [comment]
Hi! Please upgrade UI Kitten to beta, since it’s not available in this version 
```
npm i react-native-us-kitten@beta
```

**Comment by jpaulomotta** [comment]
Thanks, it works like a charm.
