### ISSUE TITLE
Prop "numColumns" in List still working

### ISSUE THREAD

**Issue by androidjaijai** [akveo/react-native-ui-kitten#615]
I was trying to make 2 items per row in a List. Tried using flexbox way many times but didn't work out, it kept only showing 1 item per row(i.e. just a column). And eventually figured that gotta use "numColumns".

Sample code
```
      <List
        numColumns={2}
        style={styles.list}
        renderItem={renderItem}
        data={[1, 2, 3, 4, 5]}
      />
```

**Comment by artyorsh** [comment]
Here is an example we implemented in [Kitten Tricks app](https://github.com/akveo/kittenTricks). Take a look at the [list item styles](https://github.com/akveo/kittenTricks/blob/master/src/components/common/layoutGridList/layoutGridList.component.tsx#L64)

**Comment by androidjaijai** [comment]
Thanks @artyorsh . This was where I figured the property "numColumns" matters. It would be great if that can be reflected from the 4.2-beta documentation 'cause I couldn't see it, or maybe that property is from "FlatListProps<ItemType>" but I couldn't see the detail of it either. I was not implementing in the TS way.
