### ISSUE TITLE
Import Select

### ISSUE THREAD

**Issue by Ifunanyacollins** [akveo/react-native-ui-kitten#616]
import {
  Select,
  SelectOptionType,
  SelectOption,
} from 'react-native-ui-kitten';

trying to import Select throws export-import error and say the component is not undefined.

**Comment by artyorsh** [comment]
@Ifunanyacollins what version of `react-native-ui-kitten` and `@eva-design/eva` are you running?

**Comment by Ifunanyacollins** [comment]
react-native-ui-kitten: 4.1.1
 @eva-design/eva: 1.0.1

**Comment by 32penkin** [comment]
Please try to do like: ```npm install react-native-ui-kitten@beta @eva-design/eva@beta```
