### ISSUE TITLE
Input needs to support the independent editable property

### ISSUE THREAD

**Issue by rendongsc** [akveo/react-native-ui-kitten#617]
* [√ ] feature request
Currently it is editable set by disable. Sometimes you need to set InputText to not edit, but the whole component is not disabled. 
For example: Develop a date select component through Input+Icon, I hope InputText can not be edited, but support icon click. After the disabled setting, the style display is very strange!
[editable={!disabled}](url)
```
 <Fragment>
      <Input
        autoCapitalize="none"
        {...restProps}
        editable={false}
        style={[themedStyle.container, style]}
        icon={ClockIconOutline}
        onIconPress={() => {
          setVisible(true);
        }}
      />
      <DateTimePicker
        maximumDate={maximumDate}
        minimumDate={minimumDate}
        isVisible={visible}
        is24Hour={is24Hour}
        onConfirm={onConfirm}
        onCancel={onCancel}
        date={value}
        mode={mode}
      />
    </Fragment>
```

**Comment by artyorsh** [comment]
Hi @rendongsc 
Fortunately, I've already faced the same issue while trying to build DatePicker based on Input on the project I'm currently working.

My solution was to wrap `Input` in `View` and manage this with `PanResponder`

```tsx
private birthInputResponser: PanResponderInstance = PanResponder.create({
  onStartShouldSetPanResponder: (): boolean => {
    return true;
  },
  onPanResponderStart: (): void => {
    this.requestDatePickerVisibility();
  },
});


<View {...this.birthInputResponser.panHandlers}>
  <Input
    label='Date on Birth'
    autoCapitalize='none'
    disabled={true}
  />
</View>
```

**Comment by artyorsh** [comment]
@rendongsc Btw I was able to use this code above in production. And it still works fine. Can it be helpful for your case? Creating an additional property for disabling input can lead to inconsistency and other issues

**Comment by rendongsc** [comment]
@artyorsh   use the input icon to achieve click-to-display date selection. Is this more lightweight?
These form components, such as date/time select, lookup select, etc., are intended to be entered directly in the text box, but allow the icon icon to be clicked to load the custom UI.
Thank you!

**Comment by artyorsh** [comment]
@rendongsc I think that disabling both `Input` and icon inside it is a correct behavior when you pass `disabled={true}` (disabling only one of them in this case feels like it is inconsistent). This is the only way to achieve keyboard-aware behavior
