### ISSUE TITLE
Warning: Invalid theme provider : [Object Object]. Only light and dark are support. Falling back to light

### ISSUE THREAD

**Issue by ImAbhishekTomar** [akveo/react-native-ui-kitten#620]
When my app load its display yellow warning.

Warning: Invalid theme provider : [Object Object]. Only light and dark are support. Falling back to light

Configuration

```
	"react-native-ui-kitten": "^4.1.1",
	"expo": "^34.0.4",
	"@eva-design/eva": "^1.0.1",
	"react": "^16.9.0",
```

![Screenshot 2019-09-18 at 18 01 03](https://user-images.githubusercontent.com/6933841/65139565-73140f00-da3f-11e9-96b6-d54143ff7e60.png)

**Comment by ImAbhishekTomar** [comment]
Anyone please help in this?

**Comment by artyorsh** [comment]
@ImAbhishekTomar just tried to do something like
```
<ApplicationProvider
  mapping={mapping}
  theme={{...light, 'screen-padding': 20}}>
  { /*Children*/ }
</ApplicationProvider>
```

Got no errors. Still actual?

**Comment by ImAbhishekTomar** [comment]
Still same error.

**My current code**
```
return (
			<ApplicationLoader assets={assets}>
				<ThemeContext.Provider value={contextValue}>
					{/* <Provider contacts={stores}> */}
					<ApplicationProvider mapping={mapping} theme={themes[this.state.theme]}>
						<IconRegistry icons={EvaIconsPack} />
						<LoadingComponent animating={stores.store.GlobalStore.isLoading} />
						{/* <DynamicStatusBar currentTheme={this.state.theme} />*/}
						{/* <Router onNavigationStateChange={this.onNavigationStateChange} />  */}
						<Router />
					</ApplicationProvider>
					{/* </Provider> */}
				</ThemeContext.Provider>
			</ApplicationLoader>
		);
```

**Change according to your suggestion**
```
return (
			<ApplicationLoader assets={assets}>
				<ThemeContext.Provider value={contextValue}>
					{/* <Provider contacts={stores}> */}
					<ApplicationProvider mapping={mapping} theme={{...light}}>
						<IconRegistry icons={EvaIconsPack} />
						<LoadingComponent animating={stores.store.GlobalStore.isLoading} />
						{/* <DynamicStatusBar currentTheme={this.state.theme} />*/}
						{/* <Router onNavigationStateChange={this.onNavigationStateChange} />  */}
						<Router />
					</ApplicationProvider>
					{/* </Provider> */}
				</ThemeContext.Provider>
			</ApplicationLoader>
		);
```

**Comment by artyorsh** [comment]
Why do you need ThemeContext *before* ‘ApplicationProvider‘ and what is the ‘contextValue’?

**Comment by ImAbhishekTomar** [comment]
here is the full code....

![Screenshot 2019-09-20 at 14 01 11](https://user-images.githubusercontent.com/6933841/65303032-60b8e300-dbaf-11e9-8d65-7970300cf1d9.png)

**Comment by artyorsh** [comment]
What is `themes`?

**Comment by ImAbhishekTomar** [comment]
themes code....


> export const themes: ThemeRegistry = {
> 	'Eva Light': light,
> 	'Eva Dark': dark,
> 	'App Theme': appTheme,
> 	'quibik-theme-light': quibikThemeLight
> };


```
import { dark, light } from '@eva-design/eva';
import { default as appTheme } from './appTheme.json';
import { ThemeType } from '@kitten/theme';
import { quibikThemeLight } from './quibikTheam';
interface ThemeRegistry {
	['Eva Light']: ThemeType;
	['Eva Dark']: ThemeType;
	['App Theme']: ThemeType;
	['quibik-theme-light']: ThemeType;
}

export type ThemeKey = keyof ThemeRegistry;

export const themes: ThemeRegistry = {
	'Eva Light': light,
	'Eva Dark': dark,
	'App Theme': appTheme,
	'quibik-theme-light': quibikThemeLight
};

export { ThemeContext, ThemeContextType } from './themeContext';

export { ThemeStore } from './theme.store';
export { ThemeService } from './theme.service';
```

**Comment by artyorsh** [comment]
@ImAbhishekTomar I'm sorry, but your code snippets are not informative. If you're trying to copy-paste code from [KittenTricks app](https://github.com/akveo/kittenTricks), please try doing this more carefully as you can see that it works there.
The main point of this (and your's also) structure is that `state` in App component stores a *string* that represents a key in `themes` object, and when you change a theme, you simply change this key in a state

**Comment by ImAbhishekTomar** [comment]
This code was working for me a few days ago, but I have been facing this issue when I updated my version of "Kitten UI".

react-native-ui-kitten": "^4.1.1"

I am using same code pattern like  kitten app...... because am new with React and TypeScript so i have learning and i like  kitten app code pattern.
