### ISSUE TITLE
Select component requires a size attribute

### ISSUE THREAD

**Issue by rendongsc** [akveo/react-native-ui-kitten#621]
* [x ] feature request
The Select component requires a size(large, medium, small) attribute, just like the Input component. 
These are the components of the form, providing consistent properties as much as possible, which makes it easier to use.
thanks!

**Comment by artyorsh** [comment]
Definitely.Thanks for reporting

**Comment by rendongsc** [comment]
@artyorsh Thank you for your reply!
 textStyle should also be consistent with the Input component by default.
![屏幕快照 2019-09-19 上午8 01 40](https://user-images.githubusercontent.com/12553638/65196962-eb1c1c80-dab3-11e9-9484-3a46ae168ec6.png)

**Comment by artyorsh** [comment]
Let’s keep it open, so we can track it
