### ISSUE TITLE
startAnimation dose not exist on type ‘unknow’

### ISSUE THREAD

**Issue by ImAbhishekTomar** [akveo/react-native-ui-kitten#622]
When I have trying icon animation using example
... according to this link [Document Link](https://akveo.github.io/react-native-ui-kitten/docs/components/icon/overview#icon)  it’s showing error in react native expo

**Error message**

![F650856B-08FB-41A1-83A8-5EC0A6170779](https://user-images.githubusercontent.com/6933841/65185053-5c020b00-da99-11e9-9cd6-0e5958f59402.jpeg)

**Comment by artyorsh** [comment]
You have no type definition for `iconRef`. It's kinda complicated declaration for now, as Icon can accept generic props

```ts
const iconRef: React.RefObject<Icon<ImageProps>> = React.createRef();
```

Also, consider declaring refs inside components. In `LogInComponent` in your case
