### ISSUE TITLE
RkChoice onPress ignored

### ISSUE THREAD

**Issue by dwsmart** [akveo/react-native-ui-kitten#63]
Hi:
<View>
<RkChoice onPress={() => console.log('test')} />
</View>
Results in nothing being logged? Does onPress not work?

**Comment by sobiso** [comment]
Check https://github.com/akveo/react-native-ui-kitten/issues/59, maybe this will help you

**Comment by dwsmart** [comment]
Yep, That pointed me in the right direction! Thanks!

**Comment by rafser01** [comment]
use onChange prop
