### ISSUE TITLE
Have error when use Icon component

### ISSUE THREAD

**Issue by DinhHuyHoang** [akveo/react-native-ui-kitten#633]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

When I use Icon component, sometime I encounter error "view nested within a text must have a width and height"

**Expected behavior:**

It should not have error and crash app
**Steps to reproduce:**

Use Icon component
**Related code:**

Not applicable.

### Other information:

**OS, device, package version**
```
samsung device
"react-native": "0.60.5"
"react": "16.9.0"
"@ui-kitten/eva-icons": "4.2.0-beta.2"
"@eva-design/eva": "1.1.0-beta.1"

```

**Comment by artyorsh** [comment]
Hi, please provide related code on how do you use this component. Thanks

**Comment by DinhHuyHoang** [comment]
Hi,

This is some examples that I use Icon component. I don't know where fired
error.
But when a replace and use package "react-native-eva-icons": "1.1.0",  the
error don't occurred.

**Comment by artyorsh** [comment]
@DinhHuyHoang unfortunately, there is no code I can see to determine what's wrong. I would like to see how do you use `Icon`, if possible

**Comment by DinhHuyHoang** [comment]
I sent two image attaches above.

this is some code I used Icon component, because it have error then I
replace with package "react-native-eva-icons".

Two links bellow are code example in my project, I just know when I use
"react-native-eva-icons", the error not fired,

Please, check my code and if have any problem tell me know.

Thanks you.

http://codepad.org/E8oApexl
http://codepad.org/1knu3Abt

**Comment by artyorsh** [comment]
Have you instantiated `IconRegistry` like it is described in [this guide](https://akveo.github.io/react-native-ui-kitten/docs/guides/eva-icons)?

**Comment by DinhHuyHoang** [comment]
Yes, I did

this is my implementation code
http://codepad.org/JKZ4gfM9

**Comment by artyorsh** [comment]
Please try refactoring to something like this as it looks like we were wrong about this guide
The main point is to render `IconRegistry` **before** `ApplicationProvider`.

```js
import React from 'react';
import { mapping, light as lightTheme } from '@eva-design/eva';
import { EvaIconsPack } from '@ui-kitten/eva-icons';
import { ApplicationProvider, IconRegistry, Layout, Text } from 'react-native-ui-kitten';

const App = () => (
  <React.Fragment>
    <IconRegistry icons={EvaIconsPack} />
    <ApplicationProvider
      mapping={mapping}
      theme={lightTheme}>
      <YourApp />
    </ApplicationProvider>
  <React.Fragment />
);

export default App;``

**Comment by DinhHuyHoang** [comment]
I solved my problem, the error fired when I wrap Text component with Icon
component

Thank for your help.
