### ISSUE TITLE
TabView Tab scrollable

### ISSUE THREAD

**Issue by rendongsc** [akveo/react-native-ui-kitten#634]
* [ ] bug report
* [ x] feature request
There are more than 5 tabs, how to make the tab title not squeezed, and support sliding
![image](https://user-images.githubusercontent.com/12553638/65400961-b7b0f900-ddf7-11e9-95c7-2b81216b76f4.png)
thanks!

**Comment by artyorsh** [comment]
Hi @rendongsc
Unfortunately, we don't support this currently and have no plans on it in future releases. For now, we're not allowed to do this because of Eva specifications :)

**Comment by rendongsc** [comment]
@artyorsh Thanks very much！

**Comment by personify-dev** [comment]
@artyorsh Apologies for bumping an old thread, but I have to ask what part of the Eva specifications disallow this feature? Some features in my app are spec'd around having a scrollable TabBar on the TabView control, and I don't think Bottom Navigation will help.

Looking at the commit history, it seems like at some point the tab APIs supported an isScrollable prop. Is there a reason that was deprecated?

**Comment by artyorsh** [comment]
> what part of the Eva specifications disallow this feature

There is no technical specification for that. That was a decision of the Design Team.

**Comment by palicko** [comment]
You can do this by wrapping TabBar with ScrollView, but this approach also needs few other CSS adjustments (set `flexShrink: 0` for Tab, etc.)
