### ISSUE TITLE
docs: Generation of methods info works incorrect

### ISSUE THREAD

**Issue by sergey-kozel** [akveo/react-native-ui-kitten#64]
See returns param
![screen shot 2017-12-11 at 5 45 19 pm](https://user-images.githubusercontent.com/34234276/33837252-d207d956-de9c-11e7-9264-020fa1742572.png)
<img width="1007" alt="screen shot 2017-12-11 at 5 45 44 pm" src="https://user-images.githubusercontent.com/34234276/33837254-d227a51a-de9c-11e7-85bd-2e6f70535673.png">

**Comment by 32penkin** [comment]
Fixed in new version @2.0.1.
