### ISSUE TITLE
Datepicker performance issue

### ISSUE THREAD

**Issue by 32penkin** [akveo/react-native-ui-kitten#641]
**I'm submitting a ...**  (check one with "x")

* [x] performance issue

### Issue description

**Current behavior:**
Datepicker renders slowly.

**Expected behavior:**
Datepicker should rende quickly.

**To do:**
Investigate Popover performance

**Comment by artyorsh** [comment]
Got this fixed in 4.3.2 🎉 
[Upgrade](https://github.com/akveo/react-native-ui-kitten/issues/517#issuecomment-565398953)
