### ISSUE TITLE
Help : Possible to customise Input component? 

### ISSUE THREAD

**Issue by ImAbhishekTomar** [akveo/react-native-ui-kitten#644]
Help : Possible to customise Input component like below image?

![Screenshot 2019-09-26 at 15 23 30](https://user-images.githubusercontent.com/6933841/65667232-e0442780-e071-11e9-9334-bcf135a9dbc6.png)

**Comment by 32penkin** [comment]
Hi @ImAbhishekTomar! You can find the full API of the Input component here: https://akveo.github.io/react-native-ui-kitten/docs/components/input/api#input. 
It will help you to customize almost all params of the component.
