### ISSUE TITLE
'.' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by chandusr** [akveo/react-native-ui-kitten#645]
i clone this project i try to start the application using npm start i got error in my cmd i attached that along this 
![Capture4](https://user-images.githubusercontent.com/24756336/65668807-0cef4380-e060-11e9-8a3f-17bccbceb613.PNG)

**Comment by artyorsh** [comment]
The script you trying to run is using bash script (which is not supported on your machine) to set the development environment. Since you don't need to use development environment, please try `npm run start:pg`

**Comment by artyorsh** [comment]
@chandusr btw thanks for reporting. We fixed this in #646 
But if you want to use the development environment to review the latest features, please follow [this doc](https://github.com/akveo/react-native-ui-kitten/blob/master/DEV_DOCS.md#start-a-playground)
