### ISSUE TITLE
Bundling in version 4.2 produces "Unable to resolve "./overflowMenu/overflowMenuItem.component""

### ISSUE THREAD

**Issue by damienix** [akveo/react-native-ui-kitten#650]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [X] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Bundling ends with the following error:

> Unable to resolve "./overflowMenu/overflowMenuItem.component" from "node_modules/react-native-ui-kitten/ui/index.js"
> Failed building JavaScript bundle.
> 

**Expected behavior:**
Bundling works.

**Steps to reproduce:**

Upgrade `react-native-ui-kitten` to 4.2. In particular I narrowed this down to upgrading `@eva-design/eva` to 1.2, which gets installed with `react-native-ui-kitten` from 4.2 beta.

**Related code:**

```
insert short code snippets here
```

### Other information:

**OS, device, package version**
```
@eva-design/eva@1.2.0
react-native-ui-kitten@4.2.0
```

**Comment by artyorsh** [comment]
It should not :)
Please try following this answer https://github.com/akveo/react-native-ui-kitten/issues/643#issuecomment-534931117

**Comment by damienix** [comment]
Thanks for swift response. While your code didn't work (I'm on Mac), I did all sort of other cleanups plus reinstalled packages using `expo install` rather than npm (I'm new to expo) and finally it worked!

**Comment by BrunoLambert** [comment]
I am having the same error. I already tryied the answers frmo @artyorsh suggested.

**Comment by ben-wright** [comment]
I have just run into this issue as well but I solved it by firstly by:

1. watchman watch-del-all && rm -rf $TMPDIR/react-* && rm -rf ./node_modules ./package-lock.json && npm i && npm start -- --reset-cache ( #643 )
2. expo r -c
3. Force quit and reopen expo app

**Comment by artyorsh** [comment]
@ben-wright thanks for posting this. Your answer is actual for Expo users.
The final command will look like:

```
watchman watch-del-all && rm -rf $TMPDIR/react-* && rm -rf ./node_modules ./package-lock.json && npm i && expo start -c
```

Btw, this should be actual not only for our library, but for any other reproducing changes in exported modules when updating
