### ISSUE TITLE
Card component

### ISSUE THREAD

**Issue by artyorsh** [akveo/react-native-ui-kitten#652]

**Comment by RomanShabanov** [comment]
Is there a plan to share code examples from **Kitten Tricks** demo app?

**Comment by artyorsh** [comment]
@RomanShabanov in case you mean moving it to documentation - we don’t plan it. But we’re going to restructure Kitten Tricks to make it as simple as it can be.
If you have more questions about it - please refer to https://github.com/akveo/react-native-ui-kitten/issues/657 or https://github.com/akveo/kittenTricks/issues/243
We would appreciate your feedback

**Comment by sarathkcm** [comment]
Just wondering if this is published. The document for 4.3.0-beta.1 mentions card component and usage, but i am not able to find it in that version.

**Comment by jaslyn-siliconjungles** [comment]
Same issue as @sarathkcm, can't find this Card component anywhere.

**Comment by artyorsh** [comment]
It's not published yet. But stay tuned, it will be available in 4.3 this week

**Comment by sarathkcm** [comment]
Thank you for the update. Looking forward to use it.
