### ISSUE TITLE
PNG Icons color changed Issue.

### ISSUE THREAD

**Issue by ImAbhishekTomar** [akveo/react-native-ui-kitten#660]
Hi,

I am setting up color google png icon on button, but this icon color change when button render.

![Screenshot 2019-10-03 at 17 04 12](https://user-images.githubusercontent.com/6933841/66113907-4d226900-e600-11e9-9ec1-2b970a1c9f99.png)
![Screenshot 2019-10-03 at 17 04 30](https://user-images.githubusercontent.com/6933841/66113908-4dbaff80-e600-11e9-9e79-b89f3936e771.png)

**Comment by 32penkin** [comment]
Hi @ImAbhishekTomar! What icon color do you need?

**Comment by artyorsh** [comment]
@ImAbhishekTomar I suggest [using icons module](https://akveo.github.io/react-native-ui-kitten/docs/guides/eva-icons#setup-icons-module). If you're using Kitten Tricks code base, it uses the same icons, but in png format

**Comment by Manne010** [comment]
am also facing same issue because in need  to use external Icon(not available in eva-icons).
Any Help? @ImAbhishekTomar  and @artyorsh

**Comment by artyorsh** [comment]
@Manne010 you can ignore the styles passed to the icon (since it is a function with a `style` argument)

```jsx
import { Button, Icon } from 'react-native-ui-kitten';

const StarIconWitoutStyles = (style) => (
  <Icon name='star' width={24} height={24} />
);

const StarButton = () => (
  <Button icon={StarIconWitoutStyles} />
);
```
