### ISSUE TITLE
## 🎉 v4.2.0 (2019-09-27)

### ISSUE THREAD

**Issue by ZeroCool00** [akveo/react-native-ui-kitten#662]
## 🎉 v4.2.0 (2019-09-27)

**Release Notes:**

🐛 Fixed [react-native template modules](https://akveo.github.io/react-native-ui-kitten/docs/guides/start-a-new-app)
```bash
# Simply run the command below to initialize application based on UI Kitten
npx react-native init AwesomeApp --template react-native-template-ui-kitten
```

Its still not working, now its looking for this package ```react-native-template-react-native-template-ui-kitten```

```error An unexpected error occurred: "https://registry.npmjs.org/react-native-template-react-native-template-ui-kitten: Not found".```

**Comment by artyorsh** [comment]
This is not a documentation issue, you should update your react-native CLI. 
https://github.com/react-native-community/react-native-template-typescript#note-on-the-legacy-cli

**Comment by ZeroCool00** [comment]
@artyorsh Thank you, I did'nt know about legacy cli concept until now.
