### ISSUE TITLE
Has tick icon on the unchecked toggle

### ISSUE THREAD

**Issue by iswanj** [akveo/react-native-ui-kitten#665]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Has tick icon on the unchecked toggle. but it's only on some devices. (please see the following images)

<img src="https://user-images.githubusercontent.com/7093947/66366638-ad7c2680-e9c3-11e9-9890-6b693858f6a7.jpg" data-canonical-src="https://user-images.githubusercontent.com/7093947/66366638-ad7c2680-e9c3-11e9-9890-6b693858f6a7.jpg" width="200" />

<img src="https://user-images.githubusercontent.com/7093947/66366727-ff24b100-e9c3-11e9-9d5f-fe1887be2229.png" data-canonical-src="https://user-images.githubusercontent.com/7093947/66366727-ff24b100-e9c3-11e9-9d5f-fe1887be2229.png" width="200" />

**Expected behavior:**

Toggle should same for every device and should remove the tick icon for unchecked status

**Related code:**

```
<Toggle
  size="small"
  checked={switchStatus.inbox}
  onChange={value =>
    setSwtichStatus({ ...switchStatus, inbox: value })
  }
/>
```

### Other information:

**OS, device, package version**
```
ui-kitten version: 4.1.1
```

**Comment by 32penkin** [comment]
Hi @iswanj! Thanks for the report! Could you clarify on which devices this bug is produced?

**Comment by iswanj** [comment]
I found issues is comming from version 4.2.0. In that version, unchecked toggle has a blue color tick.

**Comment by 32penkin** [comment]
Could you please share with us the exact devices? The thing is a can't reproduce this bug on any of my si-/emulators. Thanks in advance!

**Comment by artyorsh** [comment]
@iswanj In my case, I can't find any issues with this. If you were able to use previous versions (4.1 or 4.2 beta), please try starting with clearing cache (and updating your package-lock, if possible) like it is described in [this comment](https://github.com/akveo/react-native-ui-kitten/issues/643#issuecomment-534931117)

**Comment by iswanj** [comment]
Hi, I removed the `node_module` directory and clean the project and re-run it again, but the issue is still there. 

![toggle](https://user-images.githubusercontent.com/7093947/66883661-3cf78a00-f001-11e9-973a-37c8132dcecb.png)

**Comment by 32penkin** [comment]
Hi @is343. Could you clarify on which devices this bug is produced?

**Comment by artyorsh** [comment]
@32penkin I guess the problem is not with particular devices, but maybe custom styles were applied. @iswanj Please provide related code so we can review it and try to solve an issue

**Comment by iswanj** [comment]
@artyorsh  I'm not using custom styles for the toggle.

```js
<Toggle
  size="small"
  checked={toggleStatus}
  onChange={status => setToggleStatus(status)}
/>
```
But I'm still passing older mapping here, because I'm using costom mapping
```js
<ApplicationProvider mapping={mapping} theme={lightTheme}>

**Comment by artyorsh** [comment]
In case you use UI Kitten 4.2 with Eva version lower than 1.2, you need to update Eva

**Comment by iswanj** [comment]
@artyorsh Ok I'll try this.

**Comment by BrunoLambert** [comment]
I am having the same errors on update to Kitten 4.2.

> In case you use UI Kitten 4.2 with Eva version lower than 1.2, you need to update Eva

I tried it too, but it's still not working.

**Comment by artyorsh** [comment]
@BrunoLambert @iswanj I guess the only way to reproduce this is to use custom mappings. I can prove it with multiple apps built with the latest UI Kitten versions. In case you use custom mappings, make sure to change icon color for each state of the Toggle. You're also able to contact us via contact@akveo.com to get help with it. I'm able to review it
