### ISSUE TITLE
Select appears under Modal

### ISSUE THREAD

**Issue by andrewanderson58** [akveo/react-native-ui-kitten#668]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [X ] bug report
* [ ] feature request

### Issue description

**Current behavior:**
I added a basic Select inside a modal from `react-native-modal` and when selecting the drop down to show the items nothing appears (symbol turns). If I then close my dialog I can see the select options on the page.

**Expected behavior:**
The select should render on top of the modal. Other input fields do from ui-kitten

**Steps to reproduce:**
Add the following select inside a `<Modal></Modal>`
```
          <Select
            data={[{text: 'male'}, {text: 'female'}, {text: 'other'}]}
            selectedOption={gender}
            onSelect={val => console.log(val)}
            tyle={styles.select}
          />
```

**Related code:**
![Screen Shot 2019-10-08 at 4 11 20 PM](https://user-images.githubusercontent.com/55415304/66433995-30fb3f00-e9e7-11e9-95c0-e3afa12cfa94.png)
![Screen Shot 2019-10-08 at 4 11 29 PM](https://user-images.githubusercontent.com/55415304/66434003-335d9900-e9e7-11e9-9e56-631399e5906e.png)

```
insert short code snippets here
```

### Other information:

**OS, device, package version**
```
UI Kitten 4.2.0
RN 0.61.1
```

**Comment by artyorsh** [comment]
Hi @andrewanderson58 👋 
Thanks for report. Can you please share the related code when using Modal?
Btw, UI Kitten uses its own Modal implementation, which Select also relies on.
Please try using [our implementation of Modal](https://akveo.github.io/react-native-ui-kitten/docs/components/modal/overview#modal) and see if it is reproduced.

**Comment by 28harishkumar** [comment]
This bug is still there in latest version

**Comment by artyorsh** [comment]
@28harishkumar 

> UI Kitten uses its own Modal implementation, which Select also relies on.
Please try using our implementation of Modal and see if it is reproduced.

So can you please provide the related code?

**Comment by rosnaib11** [comment]
Same here

**Comment by artyorsh** [comment]
@rosnaib11 

> UI Kitten uses its own Modal implementation, which Select also relies on.
Please try using our implementation of Modal and see if it is reproduced.

**Comment by msvargas** [comment]
I fixed wrapping ModalPanel with React Native Modal

example:

```ts
.... others imports
import { Text, ModalPanel } from '@ui-kitten/components';

const MyModal = () => <Modal><ModalPanel><Text>Select HERE </Text><ModalPanel> </Modal>

```
