### ISSUE TITLE
Invalid value for prop `dispatch` on <div> tag

### ISSUE THREAD

**Issue by rfretes** [akveo/react-native-ui-kitten#669]
### Issue type 

**I'm submitting a ...** 

* [x] bug report
* [ ] feature request

### Issue description

Whenever using a Button and a Text component with ReactJS v16..0 even though elements are render and they work as expected an error message is displayed with the text: 

> Warning: Invalid value for prop `dispatch` on <div> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM. For details, see https://fb.me/react-attribute-behavior

 
**Current behavior:**
Use a Button element in a render function, when element is render in the browser the error is displayed in the console. 

**Expected behavior:**
Not display error message. 

**Related code:**

```
import React, { ChangeEvent } from 'react';
import { Button, Text } from 'react-native-ui-kitten';

const Test: React.FC<TestProps> = (props) => {

  return (
        <Button onPress={goNext} >
          Next
        </Button>
  );
};

interface TestProps {
}

export default Test;
```

### Other information:

**OS, device, package version**
```
"react": "16.9.0",
"react-native-web": "0.11.7",
"react-native": "0.61.1"
```

**Comment by artyorsh** [comment]
Thanks for the report @rfretes. We're still working on better support of `react-native-web` and I guess this will be fixed soon 😄But currently, please, consider using RNW as a beta feature :)

**Comment by lesmo** [comment]
Shouldn't this be kept open? Web support was announced on [July 11th](https://github.com/akveo/react-native-ui-kitten/issues/517#issuecomment-510503249), and while *it is experimental* these issues allow for keeping track of what needs to be done to get closer to production-grade support.

Just my two cents

**Comment by artyorsh** [comment]
@lesmo can you share a repro?
