### ISSUE TITLE
Unable to resolve module `./drawer`

### ISSUE THREAD

**Issue by yogevlahyani** [akveo/react-native-ui-kitten#670]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
After upgrade react-native to 0.61.2 I'm getting this error:
![image](https://user-images.githubusercontent.com/9413983/66714806-36c89a00-edc4-11e9-83f4-d7d75f99b0a8.png)

**Expected behavior:**
I didn't find anywhere an import or usage of drawerFence.component

**Steps to reproduce:**
Create a new react-native app using react-native CLI (Not expo) and install react-native-ui-kitten as mentioned in the [docs](https://akveo.github.io/react-native-ui-kitten/docs/guides/install-into-existing-app#add-into-existing-project)

**Related code:**
No code, just the initial boilerplate

### Other information:

**OS, device, package version**
IOS, iPhone 11 simulator

package.json dependencies:
```
"dependencies": {
    "@eva-design/eva": "^1.2.0",
    "react": "16.9.0",
    "react-native": "0.61.2",
    "react-native-svg": "^9.11.1",
    "react-native-ui-kitten": "^4.2.0"
  },
  "devDependencies": {
    "@babel/core": "^7.6.4",
    "@babel/runtime": "^7.6.3",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.5.1",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-test-renderer": "16.9.0"
  },
```

**Comment by yogevlahyani** [comment]
FYI -> ran `react-native start --reset-cache` and it fixed it, still interesting why this happened

**Comment by artyorsh** [comment]
That's what I personally facing too from time to time. I guess this issue belongs to cli
