### ISSUE TITLE
Modal opens up when changing backdrop style through theme

### ISSUE THREAD

**Issue by Farangi** [akveo/react-native-ui-kitten#679]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x ] bug report
* [ ] feature request

### Issue description

**Current behavior:**

Modal opens up when changing theme, as soon as change theme is clicked, a modal pops up.

**Expected behavior:**

Modal shouldn't pop up.

**Steps to reproduce:**

- Use theme color in backdrop style as:
backDrop: {
        backgroundColor: theme['background-basic-color-2'],
        opacity: 0.7
    }
- Try changing theme

### Other information:

**OS, device, package version**
```
OS: Windows
Device: Android/iOS
Package Version: "react-native-ui-kitten": "^4.1.1"
```

**Comment by artyorsh** [comment]
@Farangi can you describe in a few words how did you fixed this? We were not able to reproduce this

**Comment by Farangi** [comment]
It was a mistake on my end, i was using componentwillrecieveprops and not comparing the props with the previous
