### ISSUE TITLE
Remove sidebar

### ISSUE THREAD

**Issue by loic-lopez** [akveo/react-native-ui-kitten#68]
Hello,

it is possible to remove the side menu of the home view in ui kitten?
Thanks for reply.

**Comment by sergey-kozel** [comment]
Hi @loic-lopez,

I am not sure I understand you. What menu do you mean? Can you please provide some picture?

**Comment by loic-lopez** [comment]
<img width="414" alt="capture d ecran 2017-12-28 a 12 21 08" src="https://user-images.githubusercontent.com/17724398/34409353-a4857d0a-ebc9-11e7-939d-765a441730b0.png">

**Comment by sergey-kozel** [comment]
@loic-lopez, do you mean kitten-tricks application?

If yes, then it's possible.

Just replace the appropriate piece of code to this in app.js:
```
const KittenApp = StackNavigator({
  First: {
    screen: Screens.SplashScreen
  },
    ...AppRoutes
}, {
  headerMode: 'none',
});
```
and the appropriate piece of code to this in splash.js:
```
let toHome = NavigationActions.reset({
  index: 0,
  actions: [NavigationActions.navigate({routeName: 'GridV2'})]
});
```

**Comment by loic-lopez** [comment]
@sergey-kozel Thanks a lot.
Have a nice day 👍 :).
