### ISSUE TITLE
Calendar/Datepicker: min value pager problem

### ISSUE THREAD

**Issue by kevinbuyck** [akveo/react-native-ui-kitten#680]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [X] bug report
* [X] feature request

### Issue description

**Current behavior:**
As soon as I set a minimum date value (native date), on a RangeDatepicker, the pager starts acting weird, you can't page the months.

![rangeDatepicker_minStartDate](https://user-images.githubusercontent.com/55855503/66962685-e24a4680-f071-11e9-9d8f-eec6a3b152e6.gif)

**Expected behavior:**
Pager should work like it does when no minimum date value is set.

![rangeDatepicker_withoutMinStartDate](https://user-images.githubusercontent.com/55855503/66962786-33f2d100-f072-11e9-948c-7ffc1253b135.gif)

**Steps to reproduce:**

1. Add a rangedatepicker component.
2. Set the range and assign the onSelect function (like the documents).
3. Set a minimum date value. For example: minimum should be today. (The current default minimum value is: this.dateService.getYearStart(this.dateService.today());).
4. Use the arrows on the top right to navigate between the months. As soon as you click the right one, the days disappear.

**Related code:**

```
const minStartDate = new Date();
minStartDate.setHours(0, 0, 0, 0);

<RangeDatepicker
  min={minStartDate}
  range={range}
  onSelect={this.onSelect}
/>
```

### Feature request

Add the ability to change the first day of the week, currently it's always Sunday, but it would be nice to have Monday as the first day of the week.

### Other information:

**OS, device, package version**
```
React Native v0.61.1 on iPhone 11 Pro simulator 11.1.
React Native UI Kitten v4.2.0.
```

**Comment by artyorsh** [comment]
Hi 👋 Thanks for reporting this. Investigating

**Comment by artyorsh** [comment]
@kevinbuyck I guess the fix will be available soon as we plan to release beta

**Comment by kevinbuyck** [comment]
@artyorsh I will check it out later today or tomorrow. Nice!
