### ISSUE TITLE
can we use flip animation for icon?what is the animation name? 'flip' not working

### ISSUE THREAD

**Issue by vipinkviswanath** [akveo/react-native-ui-kitten#683]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [ ] feature request

### Issue description

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

### Other information:

**OS, device, package version**
```
insert information here
```

**Comment by artyorsh** [comment]
@vipinkviswanath as we mentioned in [Icon API docs](https://akveo.github.io/react-native-ui-kitten/docs/components/icon/api#icon): 

> Available `zoom`, `pulse` and `shake`. Default is `zoom`.
