### ISSUE TITLE
Calendar: year selection not possible

### ISSUE THREAD

**Issue by kevinbuyck** [akveo/react-native-ui-kitten#688]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [X] bug report
* [ ] feature request

### Issue description

**Current behavior:**
If I have a minimum value (e.g. today) and a maximum value (e.g. one year from today). I can't selected the current year, to select the months in the current year. I can only select the next year.

<img width="276" alt="Schermafbeelding 2019-10-17 om 16 43 35" src="https://user-images.githubusercontent.com/55855503/67019675-57af2900-f0fd-11e9-8a18-aaa8c5e96071.png">

In the above screenshot:
- I can click on 2020 and select months in 2020.
- I cannot click on 2019 and select months in 2019.

**Expected behavior:**
Year selection (and month selection after that) should work for both 2019 and 2020.

**Steps to reproduce:**
1. Add a rangecalendar component.
2. Set the range and assign the onSelect function (like the documents).
3. Set a min and max value.
4. Use the arrow on the top left to select a year.
5. Click on the highlighted year.

**Related code:**

```
private getMinStartDate = () => {
  const minStartDate = new Date();
  minStartDate.setHours(0, 0, 0, 0);
  return minStartDate;
};

private getMaxEndDate = () => {
  const minStartDate = this.getMinStartDate();
  const maxEndDate = new Date(minStartDate);
  maxEndDate.setFullYear(maxEndDate.getFullYear() + 1);
  return maxEndDate;
};

<RangeCalendar
  min={this.getMinStartDate()}
  max={this.getMaxEndDate()}
  range={range}
  onSelect={this.onRangeSelect}
/>
```

### Other information:

**OS, device, package version**
```
React Native v0.61.1 on iPhone 11 Pro simulator 11.1.
React Native UI Kitten v4.2.0.
```

**Comment by artyorsh** [comment]
Thanks for reporting multiple issues on this component 👍 We've merged fixes for your issues and hopefully will update npm package soon

**Comment by kevinbuyck** [comment]
@artyorsh No problem. Nice work on the package otherwise!

**Comment by PavanTank4631** [comment]
is this resolve yet? its not working.

**Comment by artyorsh** [comment]
@PavanTank4631 Will be available in 4.3, we're going to publish it this week

**Comment by PavanTank4631** [comment]
@artyorsh  Thank you, I am looking forward to that.

**Comment by ZeroCool00** [comment]
This is still not working.

**Comment by artyorsh** [comment]
@ZeroCool00 could you share a repro?

**Comment by Manengelo** [comment]
Still not working

**Comment by altssolution** [comment]
Still not working

**Comment by dheerajpoonia29** [comment]
work for me, thanks

**Comment by masads** [comment]
Still not working
