### ISSUE TITLE
strip invalid View props 

### ISSUE THREAD

**Issue by micimize** [akveo/react-native-ui-kitten#69]
I've been using ui-kitten with [react-native-web](https://github.com/necolas/react-native-web) with a fair amount of success, but get the following warning quite frequently:
> React does not recognize the `rkCardContainer` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `rkcardcontainer` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

**Comment by sergey-kozel** [comment]
Hello @micimize,

Sorry, but we do not have plans to support the library for using with react-native-web yet.
