### ISSUE TITLE
Error during creating new app from template

### ISSUE THREAD

**Issue by DonWasyl** [akveo/react-native-ui-kitten#690]
### Issue type

**I'm submitting a ...** 

* [X ] bug report
* [ ] feature request

### Issue description

**Current behavior:**
I'm unable to create new project, there is a problem with template url :(

**Related code:**
```
info Fetching template react-native-template-react-native-template-ui-kitten...
yarn add v1.17.3
[1/4] 🔍  Resolving packages...
warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > left-pad@1.3.0: use String.prototype.padStart()
error An unexpected error occurred: "https://registry.yarnpkg.com/react-native-template-react-native-template-ui-kitten: Not found".
```

**Comment by artyorsh** [comment]
Hi. You're using old react-native-cli. See [my answer on this](https://github.com/akveo/react-native-ui-kitten/issues/662#issuecomment-538282917) in a similar issue.
