### ISSUE TITLE
why is it taking a 3 second delay to navigate to other pages on button click? help needed ,suggest solutions 

### ISSUE THREAD

**Issue by vipinkviswanath** [akveo/react-native-ui-kitten#691]

**Comment by artyorsh** [comment]
Hi 👋 Do you use [Kitten Tricks](https://github.com/akveo/kittenTricks) as a starter app?
Since this is not UI Kitten issue, I suggest you looking through [react-navigation guidelines](https://reactnavigation.org/docs/en/navigating.html) in case this is a framework of your choice

**Comment by vipinkviswanath** [comment]
may be  related  to https://github.com/akveo/react-native-ui-kitten/issues/613#issue-493615327
