### ISSUE TITLE
Modals not working for React Native Web Safari browser

### ISSUE THREAD

**Issue by srodney86** [akveo/react-native-ui-kitten#692]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x ] bug report

### Issue description

**Current behavior:**
https://akveo.github.io/react-native-ui-kitten/docs/components/datepicker/examples#datepicker

I am not able to open the modal or datepicker when using React Native Web on Safari browser.

**Expected behavior:**
Modals should open as expected (works fine with Chrome)

**Steps to reproduce:**
Visit using Safari and try the examples: https://akveo.github.io/react-native-ui-kitten/docs/components/datepicker/examples#datepicker

### Other information:

**OS, device, package version**
MacOS Safari version 12.1.2

**Comment by artyorsh** [comment]
Hi 👋 Thanks for reporting this
