### ISSUE TITLE
docs: link not working

### ISSUE THREAD

**Issue by amandeepmittal** [akveo/react-native-ui-kitten#694]
The link in the guides 👉 [https://akveo.github.io/react-native-ui-kitten/docs/guides/create-ui-kitten-screen#create-ui-kitten-screen](https://akveo.github.io/react-native-ui-kitten/docs/guides/create-ui-kitten-screen#create-ui-kitten-screen) is giving an error 404.

The link is highlighted in the screenshot below.

![Screenshot 2019-10-21 at 7 23 28 PM](https://user-images.githubusercontent.com/10234615/67211626-b09dfa80-f438-11e9-9cef-7437b03cc113.png)

The result of the above link:

![Screenshot 2019-10-21 at 7 27 06 PM](https://user-images.githubusercontent.com/10234615/67211709-cf9c8c80-f438-11e9-8e12-4d027e2907ca.png)

I guess the appropriate link would be [this](https://akveo.github.io/react-native-ui-kitten/docs/guides/install-into-existing-app#install-ui-kitten-and-eva-design-system) one?

### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

### Other information:

**OS, device, package version**
```
insert information here
```

**Comment by artyorsh** [comment]
Thanks for reporting!

**Comment by amandeepmittal** [comment]
No problem. I hope you are not annoyed by me opening these issues. 🙌
