### ISSUE TITLE
feat: use hairlineWidth in custom mapping

### ISSUE THREAD

**Issue by jbtheard** [akveo/react-native-ui-kitten#695]
### Issue type

**I'm submitting a ...** 

* [ ] bug report
* [x] feature request

### Issue description

**Current behavior:**
When defining a custom mapping, we need to explicitly define variables such as my-border-width : 1

**Expected behavior:**
In custom-mapping.json file, we should be able to refer to [StyleSheet.hairlineWidth](https://facebook.github.io/react-native/docs/stylesheet#hairlinewidth).

Hairline width is very useful to draw crisps lines (and borders) in various situations. A use case would be to define component borders referring to that values instead of specifically specifying a value.

**Comment by artyorsh** [comment]
Hi 👋 Thanks for the proposal. Unfortunately, we don't plan using mappings to access something from js. But we use it only to map component parameters on theme variables (currently only colors).
Within the next releases, we plan to support more theme variables like global `borderRadius`, etc.

You still able to use [withStyles](https://akveo.github.io/react-native-ui-kitten/docs/components/withstyles) function, can it be helpful?
