### ISSUE TITLE
Modal positioned by screen size (not browser size) on web

### ISSUE THREAD

**Issue by AndyHubert** [akveo/react-native-ui-kitten#699]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
The <Modal /> component attempts to center its positioning. However, on web, it bases its calculation off of the monitor width, not the browser width. Thus, if the browser width is less than the full width of the monitor, the Modal's positioning will not be centered.

**Expected behavior:**
For web, the <Modal /> component should center its x position on the browser window width.

**Steps to reproduce:**
Use a Modal with react native web, and open up in a browser window which does not extend the full width of the monitor.

**Related code:**
[The offending line of code](https://github.com/akveo/react-native-ui-kitten/blob/f8fe134555e38cc55cbe41c80ea48af3770dc0c8/src/framework/ui/modal/modal.component.tsx#L29)

### Other information:

**OS, device, package version**
```
React Native Web
```

**Comment by artyorsh** [comment]
Hi 👋 Thanks for reporting this!
