### ISSUE TITLE
TopNavigation leftControl does not display

### ISSUE THREAD

**Issue by dherault** [akveo/react-native-ui-kitten#702]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
The `TopNavigation` component does not display its `leftControl` component.

**Expected behavior:**
To display it. Display the associated icon.

**Steps to reproduce:**
```jsx
function createIcon(name) {
  return props => <Icon {...props} name={name} />
}
```
```jsx
<TopNavigation
     leftControl={props => <TopNavigationAction {...props} icon={createIcon('arrow-back-outline')} />}
     title={currentDirectory}
/>
```

**Related code:**
![image](https://user-images.githubusercontent.com/4154003/67805496-67c9ef80-fa91-11e9-851d-16f30f7f3234.png)

As you can see, the left arrow is not present.

### Other information:

**OS, device, package version**
```
On iOS 13 simulator and react-native-web
```

**Comment by dherault** [comment]
MY BAD !
--> `leftControl` accepts a node not a component

**Comment by dherault** [comment]
![image](https://user-images.githubusercontent.com/4154003/67810857-bbd9d180-fa9b-11e9-8cee-75264fa1e110.png)
New bug: On Android, the `leftControl` does not display. On the picture: iOS, Android, web.

**Comment by dherault** [comment]
![image](https://user-images.githubusercontent.com/4154003/67810970-f6dc0500-fa9b-11e9-9790-1502d74b3230.png)
New bug: On Android the `leftControl` does not display. On the picture: iOS, Android, web.

**Comment by artyorsh** [comment]
Can you share the full code, please?

**Comment by artyorsh** [comment]
@dherault you can find the runnable example of TopNavigation with actions in [our docs](https://akveo.github.io/react-native-ui-kitten/docs/components/topnavigation/overview#topnavigation). Make sure to follow the api standards. Just tried this on each platform and could not reproduce your issue

**Comment by dherault** [comment]
A rebuild did the trick, still by looking at the picture I cannot help but think there is a bug somewhere. Must be emulator or server-related. 
I love your lib ❤️
