### ISSUE TITLE
OverflowMenu placement obsolete documentation

### ISSUE THREAD

**Issue by dherault** [akveo/react-native-ui-kitten#711]
### Issue type

**I'm submitting a ...** 

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
In the `TopNavigation` docs, `OverflowMenu` has a `placement` property.

**Expected behavior:**
This property, if applicable, should be documented.

**Comment by artyorsh** [comment]
Thanks for reporting! In the [OverflowMenu API block](https://akveo.github.io/react-native-ui-kitten/docs/components/overflow-menu/api), you can see that it accepts `PopoverProps`. Referring to the [Popover API](https://akveo.github.io/react-native-ui-kitten/docs/components/popover/api), you can see that this property is documented.

But yes, I agree it's better to simplify this 👍
