### ISSUE TITLE
Calendar UI Bug - Left / Right Navigation - Invalid Header

### ISSUE THREAD

**Issue by wrsulliv** [akveo/react-native-ui-kitten#713]
**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

![Calendar Buttons](https://user-images.githubusercontent.com/5376731/68082115-be636080-fde6-11e9-8f8a-6d8e4fac1f39.gif)

**Current behavior:**

The header of the "Calendar" component does not update as expected while **using the left / right navigation buttons**.

**Expected behavior:**

The header of the "Calendar" component properly updates while **using the left / right navigation buttons**.

**Steps to reproduce:**

1.  Navigate to:  https://akveo.github.io/react-native-ui-kitten/docs/components/calendar/overview#calendar  

2.  Observe that **using the right navigation button**  does not update the Calendar header, and **using the left navigation button** produces an unexpected jump in months.

> NOTE:  If the website is unavailable in step 1, you can insert a "Calendar" component into a demo project from the `4.3.0-beta.1` build.

**Related code:**

Render the following component:
```
import { Calendar } from 'react-native-ui-kitten';

const ExampleComponent = () => {
    return <Calendar date={ new Date() } onSelect={ () => null } />;
}
```

### Other information:

**OS, device, package version**

`MacOS 10.14`, `4.3.0-beta.1`

**Comment by artyorsh** [comment]
Thanks for reporting this and #712. I've reviewed your PR #714 and left a comment on this. We can use this PR for the future discussion
