### ISSUE TITLE
List's keyExtractor

### ISSUE THREAD

**Issue by Reggionick** [akveo/react-native-ui-kitten#716]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
The keyExtractor function setted as List prop is not passed to FlatList component

**Expected behavior:**
The keyExtractor function setted as List prop should be passed to FlatList component in order to customize the ListItem key

**Steps to reproduce:**

1. Add a List component
2. Set the List component keyExtractor prop to `item => item.id`

### Other information:

**Current master code**
```
  private keyExtractor = (item: ItemType, index: number): string => {
    return index.toString();
  };
```

```
    return (
      <FlatList
        {...derivedProps}
        ref={this.listRef}
        style={[componentStyle.container, styles.container, style]}
        keyExtractor={this.keyExtractor}
        renderItem={this.renderItem}
      />
    );
```

**Comment by artyorsh** [comment]
Hi 👋 Thanks for reporting. Definitely makes sense
