### ISSUE TITLE
Overflow Menu extends beyond device window

### ISSUE THREAD

**Issue by AndyHubert** [akveo/react-native-ui-kitten#719]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
The Overflow Menu centers itself upon the element it wraps. When the wrapped element is close to the edge of the device window, the Overflow Menu overflows beyond the device window.

**Expected behavior:**
The positioning of the Overflow Menu should be adjusted (when need be) so as to not extend beyond the edge of the device window.

**Steps to reproduce:**
Render an Overflow Menu at the left or right edge of the device window.

**Comment by artyorsh** [comment]
Hi 👋 
Can you share a reproducible demo?

**Comment by AndyHubert** [comment]
Correction from the original issue: It is only a problem when on the right edge of the device window. Here is an example: https://snack.expo.io/H1cVyMzsS

**Comment by artyorsh** [comment]
I guess the problem is reproduced when you using absolute positioning. I've tried simplifying this example using flex-box and it worked properly. Can you get rid of using `absolute`?

**Comment by AndyHubert** [comment]
I just checked and the issue does not seem to be dependant upon absolute positioning.

https://snack.expo.io/@andyhubert/overlow-menu-extends-past-right-side.

This issue is problematic for me in the real world because I have an Overflow Menu opening up from a header icon on the right side.

**Comment by artyorsh** [comment]
@AndyHubert 
unfortunately, [can not open your snack](https://monosnap.com/file/HphDQ8yHxISGUZzhGP8A9qQaZKc1TG). We also covered this use-case with [TopNavigation example](https://akveo.github.io/react-native-ui-kitten/docs/components/topnavigation/overview#topnavigation) (see `Top Navigation with Menu` example). We don't use absolute positioning there, and I think this should do the trick in the real world too

**Comment by AndyHubert** [comment]
Sorry for the issue with the previous snack. 

The example you point to was helpful. (By the way, should the `placement` prop on Overflow Menu be added to the API? I think this is why I did not find it before.)

However, even your example does not work properly when the titles are longer. Consider this snack in which I just made a couple of small modifications to the example you pointed to:

https://snack.expo.io/@andyhubert/033c17

**Comment by artyorsh** [comment]
> should the placement prop on Overflow Menu be added to the API?

Yes, it should. We have done some improvements in documentation, and it will be updated with the next release.

> However, even your example does not work properly when the titles are longer

Agreed. However, for the quick fix, you can try passing `width` or `maxWidth` property to `OverflowMenu` styles. I guess we can fix this in future. Thanks!

**Comment by AndyHubert** [comment]
Passing `width` to `OverflowMenu` style does give a temporary fix. Thanks.
