### ISSUE TITLE
customMapping problem when implementing dynamic theme switcher

### ISSUE THREAD

**Issue by David-Melo** [akveo/react-native-ui-kitten#720]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [X] bug report
* [ ] feature request

### Issue description
I am trying to implement a theme switcher using KittenTricks and [this example in this repo](https://github.com/akveo/react-native-ui-kitten/blob/a08e1d36d6a1c9b7635748c727d42dff821ffee6/src/playground/src/app.component.tsx). Everything works as expected until i try to implement a custom font family using customMapping like in [this example](https://github.com/akveo/react-native-ui-kitten/issues/517#issuecomment-535988646). If I pass in a customMapping prop, the theme switching breaks and many of the styles no longer change.

**Current behavior:**

It seems that once an initial customMapping is applied, dynamically switching the theme does not refresh all the styles leaving some aspects of the light theme mixed in with other aspects of the dark theme.

**Expected behavior:**

Dynamically switching themes when using a customMapping should refresh all the styles.

**Steps to reproduce:**

Pass in a customMapping into the ApplicationProvider when using a theme switcher like in [this example](https://github.com/akveo/react-native-ui-kitten/blob/a08e1d36d6a1c9b7635748c727d42dff821ffee6/src/playground/src/app.component.tsx)

**Related code:**

I'm not too familiar with setting up and sharing an Expo playground to provide any samples.

### Other information:

**OS, device, package version**
```
"react": "16.9.0",
"react-native": "0.61.1",
"@eva-design/eva": "^1.2.0",
"react-native-ui-kitten": "^4.2.0",
```

**Comment by artyorsh** [comment]
@David-Melo did you managed to resolve this issue?

**Comment by David-Melo** [comment]
@artyorsh Yes, thank you. I was able to find a work around. 

I was generating a customMapping for each of my themes, this is what was giving me the problem. I simplified my customMapping to work for both themes so that it wasn't something that was affected by switching themes since that prop one the ApplicationProvider no longer changes with the theme switch.

Although I do suspect that If I did need to switch the customMapping I would still have the issue.

**Comment by artyorsh** [comment]
@David-Melo Yes, in current implementation we do not expect switching mappings during runtime. Proper creation of custom themes will cover most of use cases without a need to customize mapping. But we're investigating how this process can be simplified.

Thanks for the details 👍

**Comment by SimonHausdorf** [comment]
I was trying to add two different mappings for dark and light theme. Any idea how to solve this if the mapping does not reload on theme switch?

The goal is to have the buttomNavigation have two different active colors for dark and light theme

**Comment by artyorsh** [comment]
@SimonHausdorf Can be done.
The trick is to have a custom theme property in both themes. This is undocumented and should be used on your own risk https://github.com/akveo/react-native-ui-kitten/issues/881#issuecomment-584594077

**Comment by Jonatthu** [comment]
Is there any better way to make this work?
