### ISSUE TITLE
Calendar/Datepicker: placeholders

### ISSUE THREAD

**Issue by kevinbuyck** [akveo/react-native-ui-kitten#721]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [X] feature request

### Issue description

**Current behavior:**
No placeholders supported.

**Expected behavior:**
Placeholders supported.

**Related code:**
Placeholders like we have on the 'Input' component would be nice.

```
<Input
  style={styles.input}
  value={this.state.value}
  onChangeText={this.onChangeText}
  placeholder='Active'
/>
```

**Comment by artyorsh** [comment]
@kevinbuyck will be available in the next release. Stay tuned 👍
