### ISSUE TITLE
All Buttons inside ButtonGroup have same status

### ISSUE THREAD

**Issue by 28harishkumar** [akveo/react-native-ui-kitten#724]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [x] feature request

### Issue description

**Current behavior:**
Button elements in ButtonGroup have same status

**Expected behavior:**
Each Button should have its own status

**Steps to reproduce:**
```
<ButtonGroup>
     <Button status='success'>
         A
     </Button>
     <Button>
        B
     </Button>
     <Button>
        C
     </Button>
</ButtonGroup>
```

**Related code:**

```
insert short code snippets here
```

### Other information:

**OS, device, package version**
```
package: 4.3.0
```

**Comment by artyorsh** [comment]
Hi @28harishkumar 👋 
You can achieve this by passing `appearance` or `status` property to `ButtonGroup`

```js
import React from 'react';
import { ButtonGroup, Button } from 'react-native-ui-kitten';

const SameStatusButtonGroup = () => (
  <ButtonGroup status='success'>
    <Button>A</Button>
    <Button>B</Button>
    <Button>C</Button>
  </ButtonGroup>
);
```

**Comment by 28harishkumar** [comment]
Hi @artyorsh 

I typed `appearance` instead of `status`.
My point is different status inside ButtonGroup

```
<ButtonGroup>
     <Button status='success'>
         A
     </Button>
     <Button>
        B
     </Button>
     <Button status='danger'>
        C
     </Button>
</ButtonGroup>
```

**Comment by artyorsh** [comment]
@28harishkumar can you share a bit more information about the use-case? Such changes need discussion with our design team

**Comment by 28harishkumar** [comment]
Currently I am not able to give inline Action Buttons with different colors. 
Simple use case is providing `Save`, `Save & Add Another` and `Delete` options for some entry. `Save` with primary status, `Save & Add Another` with `info` status and `Delete` with `danger` status.

Another use case is providing `OK` and `Cancel` buttons.

Althouth all use cases can be covered by replacing ButtonGroup with View and writing extra style. But it will be better if ButtonGroup does not restrict individual Button property.

**Additionally** I found one more issue. `ButtonGroup` is accepting `white` status and it is passing it to `Button`. `Button` does not accept `white` status. It accepts `basic` status that is not accepted by 
`ButtonGroup`. 
It raises following warning:

```
Button: unsupported configuration.
Check one of the following prop values {
  "appearance": "filled",
  "variants": [
    "white",
    "medium"
  ],
  "states": []
}
📖 Documentation: https://akveo.github.io/react-native-ui-kitten/docs/components/button/api
```

**Comment by artyorsh** [comment]
@28harishkumar we don't think `ButtonGroup` should be used for this case. Instead, just use multiple `Button`s without wrapping into `ButtonGroup`. [See our vision of it](https://snack.expo.io/@art.yorsh/ui-kitten---dialog).

> I found one more issue

Thanks for reporting 👍 We've already got fix for this. Will be available in next release

**Comment by pjnovas** [comment]
@artyorsh hey, I came up with a similar case; what I'm trying to do is like the old [pagination from bootstrap](https://getbootstrap.com/docs/3.4/components/#disabled-and-active-states)

![image](https://user-images.githubusercontent.com/712927/77802537-d4a1df80-7059-11ea-9bcd-436dc04705b9.png)

Snack has that feature for selecting the platform too:

![image](https://user-images.githubusercontent.com/712927/77802233-331a8e00-7059-11ea-8b0e-1218cd731cf8.png)

My first attemp was to set up a `ButtonGroup` and changing one to the children `Button`'s state as a "Selected one". Is there a way of accomplish that on the current version of the library?

Thanks!

**Comment by artyorsh** [comment]
Actually, `ButtonGroup` is not about selection mode. For this case, you may see [this gist](https://gist.github.com/artyorsh/f4521fb53ade5dad5a6c880f7785e971) I use in my project

**Comment by garrett-gottlieb** [comment]
@artyorsh this would be a great element to include in a future release.

**Comment by Luard** [comment]
You can also achieve this by changing the button style instead of the status, for example:

```javascript
<ButtonGroup status="basic" appearance="outline" >
	<Button 
		textStyle={ selected ? { color: "white" } : null }
		style={ selected ? styles.buttonSelected : null }>
			L
	</Button>
	<Button>M</Button>
	<Button>R</Button>
</ButtonGroup>
```

Also, I realised that using `status="basic"` on the ButtonGroup on Dark Mode is showing a highlighten white instead on a gray. Is that correct?

Example, using Dark Mode, the border of the `basic` status is has strong as the `control` status:
```javascript
<ButtonGroup status="basic" appearance="outline" >
	<Button>L</Button>
	<Button>M</Button>
	<Button>R</Button>
</ButtonGroup>
```
