### ISSUE TITLE
Text Input Color

### ISSUE THREAD

**Issue by ChristopherJohnson25** [akveo/react-native-ui-kitten#726]
How can I change the text input color to black when not focused? Currently, even when the input is filled in, it looks like a placeholder (even on the documentation). When text input is filled in, the text that is inputed should be black (or any color).

**Comment by artyorsh** [comment]
@ChristopherJohnson25 

It may be only documentation issue as it runs React Native for web.
[See how it looks on mobile](https://gph.is/g/4g1wWlL)

**Comment by ChristopherJohnson25** [comment]
Yep, on mobile when I click off of an input after filling it in, it goes back to gray. Do you have the code used to create the GIF?

**Comment by artyorsh** [comment]
Please share more information about the packages you're using:
`react-native`
`react-native-ui-kitten`
`@eva-design/eva`

> Do you have the code used to create the GIF?

No I don't :)

**Comment by ChristopherJohnson25** [comment]
See below, thanks!

    "@eva-design/eva": "^1.2.0",
    "react-native": "0.60.0",
    "react-native-ui-kitten": "^4.2.0",

**Comment by artyorsh** [comment]
@ChristopherJohnson25 just reviewed on your config and agree this issue exists. This will be fixed in the next release [as soon as Eva 1.3 comes](https://github.com/akveo/react-native-ui-kitten/pull/728). Stay tuned 👍

**Comment by ChristopherJohnson25** [comment]
Thank you!!
