### ISSUE TITLE
ERROR: cannot find module : template.config

### ISSUE THREAD

**Issue by Work90210** [akveo/react-native-ui-kitten#734]
After running "npx react-native init MyApp --template react-native-template-ui-kitten"

I am presented with an error.

Copying template
error Error: Cannot find module 'C:\Users\kylef\AppData\Local\Temp\rncli-init-template-ECjTX0\node_modules\react-native-template-ui-kitten\template.config'
Require stack:
- C:\Users\kylef\node_modules\@react-native-community\cli\build\commands\init\template.js
- C:\Users\kylef\node_modules\@react-native-community\cli\build\commands\init\init.js
- C:\Users\kylef\node_modules\@react-native-community\cli\build\commands\init\index.js
- C:\Users\kylef\node_modules\@react-native-community\cli\build\commands\index.js
- C:\Users\kylef\node_modules\@react-native-community\cli\build\index.js
- C:\Users\kylef\node_modules\react-native\cli.js

I am running VS Code latest on windows

**Comment by artyorsh** [comment]
Can you try updating the React Native CLI?
```bash
npm un -g react-native && npm i -g @react-native-community/cli
```

**Comment by Work90210** [comment]
I still get the same error.

**Comment by artyorsh** [comment]
@Work90210 Unfortunately, running this command on Win 10 I was not able to reproduce your issue. However, I don't think this issue belongs to UI Kitten templates, but to [React Native CLI](https://github.com/react-native-community/cli) because it can not resolve the module that actually exists.

**Comment by Work90210** [comment]
@artyorsh Do you have any suggestions to resolve the issue?

**Comment by artyorsh** [comment]
You still able to init the bare react native project by running `npx react-native init MyApp` and then install UI Kitten manually by following [this guide](https://akveo.github.io/react-native-ui-kitten/docs/guides/install-into-existing-app).

However, I’d suggest posting this issue to cli repo, where you should get help with this
