### ISSUE TITLE
Select List(ui -kitten react native)

### ISSUE THREAD

**Issue by Manne010** [akveo/react-native-ui-kitten#736]
import React from 'react';
import { StyleSheet } from 'react-native';
import {
  Layout,
  Select,
} from 'react-native-ui-kitten';

export class SelectSimpleUsageShowcase extends React.Component {

  data = [
    { **text**: 'Option 1' },
    { **text**: 'Option 2' },
    { **text**: 'Option 3', disabled: true },
    { **text**: 'Option 4' },
  ];

  state = {
    selectedOption: null,
  };

  onSelect = (selectedOption) => {
    this.setState({ selectedOption });
  };

  render() {
    return (
      <Layout style={styles.container}>
        <Select
          style={styles.select}
          data={this.data}
          placeholder='Active'
          selectedOption={this.state.selectedOption}
          onSelect={this.onSelect}
        />
        <Select
          style={styles.select}
          data={this.data}
          placeholder='Disabled'
          disabled={true}
          onSelect={this.onSelect}
        />
      </Layout>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flexDirection: 'row',
    height: 230,
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  select: {
    flex: 1,
    marginHorizontal: 4,
  },
});

in these code i want to change data[index].key value (**"text"**) some other **"name"** and in ui display  i want to dsplay **Name** .
how can i do it?

**Comment by Manne010** [comment]
import React from 'react';
import { StyleSheet } from 'react-native';
import {
  Layout,
  Select,
} from 'react-native-ui-kitten';

export class SelectSimpleUsageShowcase extends React.Component {

  data = [
    { **text**: 'Option 1' },
    { **text**: 'Option 2' },
    { **text**: 'Option 3', disabled: true },
    { **text**: 'Option 4' },
  ];

  state = {
    selectedOption: null,
  };

  onSelect = (selectedOption) => {
    this.setState({ selectedOption });
  };

  render() {
    return (
      <Layout style={styles.container}>
        <Select
          style={styles.select}
          data={this.data}
          placeholder='Active'
          selectedOption={this.state.selectedOption}
          onSelect={this.onSelect}
        />
        <Select
          style={styles.select}
          data={this.data}
          placeholder='Disabled'
          disabled={true}
          onSelect={this.onSelect}
        />
      </Layout>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flexDirection: 'row',
    height: 230,
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  select: {
    flex: 1,
    marginHorizontal: 4,
  },
});

in these code i want to change data[index].key value (**"text"**) some other **"name"** and ui display name i want to dsplay .
how can i do it?

**Comment by artyorsh** [comment]
You can use [map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) function to transform data.

```js
const users = [{ name: 'Jonh Doe' }, { name: 'Alice Cooper' }];
const data = users.map(user => ({ text: user.name }));
```

**Comment by Manne010** [comment]
I can map but it is not  correct way of doing.Because unnecessarily i  need to loop entire array
yes there any way to customize text filed to name file.
