### ISSUE TITLE
Add left icon on Input

### ISSUE THREAD

**Issue by jeloagnasin** [akveo/react-native-ui-kitten#737]
### Issue type

* [ ] bug report
* [x] feature request

### Issue description

**Current behavior:**

* `icon` is always rendered on the right side of `Input`

**Expected behavior:**

* There's a way for me to render `icon` on the left side of `Input`

**Related code:**

```jsx
<Input leftIcon={this.renderLeftIcon} />
```

**Comment by artyorsh** [comment]
Hi! Can you, please, describe the use case? We need to discuss such changes with our design team. Thanks!

**Comment by jeloagnasin** [comment]
@artyorsh, search icons in search fields are usually placed on the left side.

**Comment by artyorsh** [comment]
@jeloagnasin Yes, that makes sense. I think we could implement this in future releases

**Comment by jeloagnasin** [comment]
I'll try to make a PR for this around Dec 22/23.

**Comment by rosnaib11** [comment]
+1

**Comment by ardasatata** [comment]
I need this too!

**Comment by harshnavadiya** [comment]
@jeloagnasin  Alternatively you can do like it. I Hope it will help you.


export const EmailTextBox = () => {
  const [value, setValue] = React.useState('');

  const renderIcon = style => (
    <Image
    style={{position:"absolute"}}
      source={{
        uri: 'https://akveo.github.io/eva-icons/outline/png/128/person-outline.png',
      }}
    />
  );

  return (
    <Input  
      textStyle={{paddingLeft:25}} 
      value={value}
      placeholder="Email"
      icon={renderIcon}
      onChangeText={setValue}
    />
  );
};

**Comment by vomchik** [comment]
+1

**Comment by vomchik** [comment]
@harshnavadiya good idea, but if UI requires both icons? :)

**Comment by ashishfeels** [comment]
+1

**Comment by artyorsh** [comment]
Available in v5! 🎉
