### ISSUE TITLE
icon in calendar rtl

### ISSUE THREAD

**Issue by shachardevops** [akveo/react-native-ui-kitten#739]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

bad looking icon in the calendar
**Expected behavior:**

normal icon
**Steps to reproduce:**

simple app with rtl
![Screen Shot 2019-11-24 at 20 20 09](https://user-images.githubusercontent.com/36663539/69499157-de72d500-0ef7-11ea-9ec1-c2abc19064e8.png)

**Related code:**

```
          <RangeDatepicker
            range={businessesList.item.range}
            onSelect={onSelectfunc}

          />
```
### Other information:

**OS, device, package version**
```
4.2
insert information here
```

**Comment by artyorsh** [comment]
Hi! 👋Thanks for reporting this
We have replaced these icons with svg and it will come with 4.3 stable

**Comment by shachardevops** [comment]
thanks

**Comment by shachardevops** [comment]
btw it will be great if you could add custom style to your components for example change colors and not with info danager,etc .........
