### ISSUE TITLE
Input: multiline not displaying properly

### ISSUE THREAD

**Issue by kevinbuyck** [akveo/react-native-ui-kitten#747]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [X] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Setting multiline/number of lines doesn't work on input. The height stays the same.

**Expected behavior:**
Setting multiline/number of lines should make the input field bigger in height (according to the number of lines). See: https://facebook.github.io/react-native/docs/textinput

**Steps to reproduce:**
1. Add a input component.
2. Set multiline too true.
3. Set the number of lines.

**Related code:**

```
<Input
  multiline={true}
  numberOfLines={10}
/>
```

If I'm missing anything here, let me know.

### Other information:

**OS, device, package version**
```
React Native v0.61.1 on iPhone 11 Pro simulator 11.1.
React Native UI Kitten v4.2.0.
```

**Comment by artyorsh** [comment]
Hi 👋 
I guess this is standard behavior of TextInput in React Native. Setting `minHeight` or `maxHeight` to styles should make it work

**Comment by kevinbuyck** [comment]
It does not, see below. Setting minHeight/maxHeight has no affect either. Only when you start typing text, the red box will start growing. But I need to display a bigger one from start.

Code:

```
<Input
  style={{ backgroundColor: "red", height: 150 }}
  multiline={true}
  numberOfLines={10}
/>

<TextInput
  style={{ backgroundColor: "yellow", height: 150 }}
  multiline={true}
  numberOfLines={10}
/>
```

Screenshot:

<img width="311" alt="Schermafbeelding 2019-12-04 om 21 35 37" src="https://user-images.githubusercontent.com/55855503/70179289-150dd400-16de-11ea-8718-b3e514fba808.png">
