### ISSUE TITLE
docs: how to install @ui-kitten/components

### ISSUE THREAD

**Issue by charlzyx** [akveo/react-native-ui-kitten#753]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Thanks for this awesome UI Kitten! but docs confuse me, where docment start said 
```
Install UI Kitten
npm i @ui-kitten/components @eva-design/eva react-native-svg
```
but no @ui-kitten/components can searched by npm

**Expected behavior:**

update doc or publish @ui-kitten

**Steps to reproduce:**
npm search @ui-kitten

**Related code:**

``` bash
npm search @ui-kitten
NAME                      | DESCRIPTION          | AUTHOR          | DATE       | VERSION  | KEYWORDS       
@ui-kitten/eva-icons      | @ui-kitten/eva-icons | =ui-kitten      | 2019-09-27 | 4.2.0    | react-native ty
@ui-kitten/moment         | @ui-kitten/moment    | =ui-kitten      | 2019-09-27 | 4.2.0    | react-native ty
@ui-kitten/date-fns       | @ui-kitten/date-fns  | =ui-kitten      | 2019-09-27 | 4.2.0    | react-native ty
```

### Other information:

**OS, device, package version**
```
insert information here
```

**Comment by artyorsh** [comment]
published 🎉

**Comment by charlzyx** [comment]
congratulation 🎉🎉🎉
