### ISSUE TITLE
Unable to resolve module @eva-design/processor

### ISSUE THREAD

**Issue by PasinduDineth** [akveo/react-native-ui-kitten#757]
I have installed libraries using the provided code of the documentation.
`npm un -g react-native-cli && npm i -g @react-native-community/cli npx`

Then created a new project using the provided code 
`npx react-native init MyApp --template @ui-kitten/template-js`

After that, I used react-native run-android to start the app. Then I got the following issue.
`bundling failed: Error: Unable to resolve module `../../../../node_modules/@eva-design/processor` from `node_modules/@ui-kitten/components/theme/application/applicationProvider.component.js`:`

How to fix this?

**Comment by artyorsh** [comment]
Hi! 👋 Thanks for reporting
We already working on it, the patch will be available soon

**Comment by stay2be** [comment]
As a workaround, change the following file:
`node_modules/@ui-kitten/components/theme/application/applicationProvider.component.js`

from
```js
...
import React from 'react';
import merge from 'lodash.merge';
/* THIS LINE => */ import { SchemaProcessor } from '../../../../node_modules/@eva-design/processor';
import { StyleProvider } from '../style/styleProvider.component';
import { ModalPanel } from '../modal/modalPanel.component';
...
```

to
```js
...
import React from 'react';
import merge from 'lodash.merge';
/* THIS LINE => */ import { SchemaProcessor } from '../../node_modules/@eva-design/processor';
import { StyleProvider } from '../style/styleProvider.component';
import { ModalPanel } from '../modal/modalPanel.component';
...
```

**Comment by artyorsh** [comment]
@PasinduDineth @stay2be 
We've just published an update that should generate your project properly. Try reinitializing and thanks again for reporting 👍

**Comment by stay2be** [comment]
Works now. Thanks @artyorsh !

**Comment by PasinduDineth** [comment]
Works fine mate. Thanks!
