### ISSUE TITLE
date picker is very slow component and doesnt have change color option

### ISSUE THREAD

**Issue by shachardevops** [akveo/react-native-ui-kitten#761]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x ] bug report
* [ ] feature request

### Issue description
date picker is very slow component
**Current behavior:**

that he will run faster 
**Expected behavior:**

**Steps to reproduce:**

simple  picker 
        <RangeDatepicker
          range={item.range}
          onSelect={range => updateDates(businessesList.index, { range })}
          dateService={dateService}
        />
[Screen Recording 2019-12-04 at 18.15.55.mov.zip](https://github.com/akveo/react-native-ui-kitten/files/3922859/Screen.Recording.2019-12-04.at.18.15.55.mov.zip)

**Comment by artyorsh** [comment]
This is already reported in #641 

> date picker is very slow component

You're running your app in development mode. Switching your environment to production will partially resolve this issue. This means for production users this doesn't look so ugly. And yes, we're working on it.

> doesnt have change color option

Did you read [theming guide](https://akveo.github.io/react-native-ui-kitten/docs/guides/branding#theming)?

**Comment by artyorsh** [comment]
@shachardevops performance is fixed in 4.3.2, you can [upgrade](https://github.com/akveo/react-native-ui-kitten/issues/517#issuecomment-565398953)
