### ISSUE TITLE
"Card: unsupported configuration" when trying to use the Card after installing this new version

### ISSUE THREAD

**Issue by damienleri** [akveo/react-native-ui-kitten#762]
I had ui kitten working with the beta version and just updated it. It still works fine except when I try to use 
```
     <Card>
        <Text>test</Text>
      </Card>
```
which throws ""Card: unsupported configuration". Since I may be one of the first users trying out the Card component I wonder if this is a bug. 

fyi:

```
          <AppearanceProvider>
            <IconRegistry icons={EvaIconsPack} />
            <ApplicationProvider
              mapping={mapping}
              theme={colorScheme === "dark" ? darkTheme : lightTheme}
            >
              <View style={styles.container}>
                {Platform.OS === "ios" && <StatusBar barStyle="default" />}
                <AppNavigator theme={colorScheme} />
              </View>
            </ApplicationProvider>
          </AppearanceProvider>
```

**Comment by artyorsh** [comment]
Remove your package.lock and start with clearing cache
`rm -rf ./package.lock ./node_modules && npm I && npm start --reset-cache`

**Comment by artyorsh** [comment]
Similar issues: #662 #650

**Comment by damienleri** [comment]
That worked - thanks for the quick response. In my case I used yarn so 

```rm -rf ./yarn.lock ./node_modules && yarn && npm start --reset-cache```
