### ISSUE TITLE
Please add 'SearchBar' component

### ISSUE THREAD

**Issue by JaeWangL** [akveo/react-native-ui-kitten#764]

**Comment by artyorsh** [comment]
@JaeWangL what do you mean with SearchBar and what features should it cover? You can do something like.
```
import { Input, Icon } from '@ui-kitten/components';

const SearchIcon = (style) => (
  <Icon {...style} name='search' />
);

const SearchBar = () => (
  <Input placeholder='Search' icon={SearchIcon} />
);
```

**Comment by JaeWangL** [comment]
I want to place my icon in left-side 
But, I realized this is duplicate with https://github.com/akveo/react-native-ui-kitten/issues/737
So I'll close

**Comment by aprilmintacpineda** [comment]
@artyorsh can this be reopened with possible considerations, something like this:

https://react-native-elements.github.io/react-native-elements/docs/searchbar.html

**Comment by artyorsh** [comment]
@aprilmintacpineda

What you share can be achieved with Input in 10 lines of code

**Comment by aprilmintacpineda** [comment]
Yeah, but wouldn't it be good if it's a built in option in the header?

**Comment by artyorsh** [comment]
You also can do this with accessoryLeft and accessoryRight props in TopNavigation
