### ISSUE TITLE
Styling Drawer Items

### ISSUE THREAD

**Issue by m4ttheweric** [akveo/react-native-ui-kitten#769]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [x ] feature request

### Issue description

**Current behavior:**
Currently the only interface we have to style Drawer Items is the ``titleStyle`` prop on the ``MenuItemType`` ``interface`` which is only set to accept ``StyleProp<TextStyle>`` which limits what kind of styles we can pass in.

**Expected behavior:**
Some kind of API to be able to provide styles to Drawer Items.

Would would be great is a way to provide a custom component as a prop to ``<Drawer/>`` that allows us to provide a render component for Drawer Items. 

What's odd is that ``DrawerProps`` is a combination of ``MenuProps`` and some others. ``MenuProps`` normally takes a ``renderItem`` prop, but this prop is specifically omitted via ``Omit<T,K>``.

**Comment by m4ttheweric** [comment]
It seems that even though the ``renderItem`` prop is Omitted, it actually still works. Is this intended?

**Comment by artyorsh** [comment]
@m4ttheweric I guess no 😄 But thanks for reporting. Btw, with the way you render a drawer you can render any other component if needed, e.g [List](https://akveo.github.io/react-native-ui-kitten/docs/components/list) or [Menu](https://akveo.github.io/react-native-ui-kitten/docs/components/menu)

**Comment by m4ttheweric** [comment]
@artyorsh You said that "with the way you render a drawer you can render any other component if needed". Could you give an example of what you mean there?

**Comment by m4ttheweric** [comment]
When I am using react-navigation, and I pass a "custom drawer" is there any value in using the Drawer component? Why not just use a List or something else?
