### ISSUE TITLE
Having lots of issues resolving measure.component

### ISSUE THREAD

**Issue by hesa2020** [akveo/react-native-ui-kitten#775]
Unable to resolve "../popover/measure.component" from "node_modules/@ui-kitten/components/ui/menu/subMenu.component.js"

### Issue type
* [x] bug report

### Issue description

**Current behavior:**
Unable to resolve "../popover/measure.component" from "node_modules/@ui-kitten/components/ui/menu/subMenu.component.js"

**Expected behavior:**
It resolve correctly.

**Steps to reproduce:**
Im not sure what i did, but after changing a few modules and running npm update it started happening.

**Comment by hesa2020** [comment]
Not first it was comming from i think the selectComponent but after i saved that one during my expo loading it catched a hot reload and it fixed it for that file.

**Comment by artyorsh** [comment]
🤔 it should not
Is it reproducible?
