### ISSUE TITLE
[Feature Request] More flexibility of Component props

### ISSUE THREAD

**Issue by lesmo** [akveo/react-native-ui-kitten#777]
As requested in #776 by @artyorsh:

### Issue type

**I'm submitting a ...**

* [x] feature request

### Issue description

**Current behavior:**
Attempting to customize the contents of a Components to compose new, exciting components is impossible. Trying to achieve something like this:
```ts
const ImpossibleTopNavigation = (props) => (
   <TopNavigation {...props} title={<Image {... someStuff} />} />
);
```

Ends up with this error:
```Type 'Element' is not assignable to type 'string'```
_(Because ```title``` only allows strings)_

**Expected behavior:**
Most Components in UI Kitten with small modifications *can receive a different PropType and still function properly*... avoiding [awkward workarounds](https://github.com/akveo/react-native-ui-kitten/issues/564#issuecomment-521421127):

```ts
const PossibleNavigation = (props) => (
   <TopNavigation {...props} title={<Image {... someStuff} />} />
);

const LoadingButton: ({ isLoading, children }) => {
  <Button>
     {/* This doesn't cover disabling it an other stuff, but you get the idea */}
     {isLoading ? (<SomeCoolSpinner />) : (children)}
  </Button>
};
```

By allowing for more flexibility in contents of components like Text or Button, probably these kinds of issues probably won't exist anymore:
* #488
* #564
* #776

I believe that would require repeating  #627 on the rest of Components' Props interfaces/types. I did something similar for my particular need of customizing the ```TopNavigationBar```Component.

**Comment by artyorsh** [comment]
Thanks for the detailed explanation 👍 

>   <TopNavigation {...props} title={<Image {... someStuff} />} />

Love the idea because it is a common use-case, but I believe we need more accurate syntax because nobody likes components in props. May be using children:
```js
const TopNavigationWithCustomContent = (props) => (
  <TopNavigation {...props} title='My App' alignment='center'>
    <Image source={require('./brand-logo')} />
  </TopNavigation>
);
```
This is my vision of it. Note, that this way title should be ignored.
My question is: is this code clear enough to say `This is a header with an image positioned in center`?

> const LoadingButton: ({ isLoading, children }) => {
>  <Button>
>     {/* This doesn't cover disabling it an other stuff, but you get the idea */}
>     {isLoading ? (<SomeCoolSpinner />) : (children)}
>  </Button>
>};

The same is here. Using children for custom content is a good idea.
**But.** Sometimes we may want to apply styles provided by Eva on it (just like with the case of `icon` props), so for now, I guess this is the only thing where we can stuck.

**Comment by lesmo** [comment]
> because nobody likes components in props

Ah yeah, that was just a lazy example... and a nasty hack, honestly 😅

My modification to ```TopNavigation``` didn't use that because I wanted to keep current API. Using ```{children}``` solves most use cases. Ignoring ```title``` property when ```{children}``` is set could work for this case.

> My question is: is this code clear enough to say _This is a header with an image positioned in center?_

Maybe the code isn't clear in that regard, but if well documented I don't see that being a problem. It's clear enough to state "I'm displaying a thing, and it has buttons" for example:

```js
const MagicalTopNavigation = (props) => (
  <TopNavigation leftAction={anAction} rightActions={someMagic}>
    {/* Oh! It's an image with left and right actions! */}
    <Image source={require('./brand-logo')} />
  </TopNavigation>
);
```

> But. Sometimes we may want to apply styles provided by Eva on it (just like with the case of ```icon``` props)

Yeah, I found the current API a bit confusing at first. Perhaps cloning the Element and merging it's Props? That way we could have the wonders of both worlds:
```js
React.cloneElement(props.children, { style: {...blah} )); // Over simplified, of course
```

It's just an idea.

**Comment by asabadyr** [comment]
Hey guys! We really need an option to provide a component to the title instead of a plain string.
Please suggest smth. Otherwise have to switch to plain react-native solution

**Comment by artyorsh** [comment]
@asabadyr unfortunately, there is no way to provide a component as a title currently

**Comment by lesmo** [comment]
> Hey guys! We really need an option to provide a component to the title instead of a plain string.
> Please suggest smth. Otherwise have to switch to plain react-native solution

Using _directly_ this library is not possible (hopefully yet). I needed this exact behavior, and thus I opened this issue, but my current solution was to directly edit the library's code.

**Comment by lesmo** [comment]
> Hey guys! We really need an option to provide a component to the title instead of a plain string.
> Please suggest smth. Otherwise have to switch to plain react-native solution

This is exactly why I was looking for a way to extend the classes. Ultimately what I ended up doing was copying this libs' code for a couple of components (namely `TopNavigation` and `ListItem`) so I could render what I needed where I needed. I lost upstream changes, I know, but the tweaks were pretty minimal (at least that's how I remember it) so if any new cool stuff comes up I'll be able to merge it rather easily.

**Comment by artyorsh** [comment]
@lesmo I'm happy to say this is available in v5 :)
[Release notes](https://github.com/akveo/react-native-ui-kitten/issues/517#issuecomment-610952452)

**Comment by lesmo** [comment]
> @lesmo I'm happy to say this is available in v5 :)
> [Release notes](https://github.com/akveo/react-native-ui-kitten/issues/517#issuecomment-610952452)

Lovely!! Thanks!! Migration looks pretty straightforward, maybe I'll update my production App. I'll upgrade my current project to use v5.

I guess I'll close this issue 😄
