### ISSUE TITLE
Swiping not working properly in TabView

### ISSUE THREAD

**Issue by muhzi4u** [akveo/react-native-ui-kitten#784]
I am trying to add a [TabView](https://akveo.github.io/react-native-ui-kitten/docs/components/tab-view/overview) in my app. But swiping is not working properly. Am I missing something here?

**Code**
```
class HomeScreen extends Component {
  render() {
    const { selectedIndex } = this.state;
    return (
      <Layout style={styles.container}>
        <TopNavigation
          alignment="center"
          title="My App"
          rightControls={this.renderRightControls()}
        />
        <TabView
          selectedIndex={selectedIndex}
          indicatorStyle={styles.tabViewIndicator}>
          <Tab title="Mine (10)">
            <Layout>
              <Text>List of users.</Text>
            </Layout>
          </Tab>
          <Tab title="Unassigned (0)">
            <Layout>
              <Text>List of profiles.</Text>
            </Layout>
          </Tab>
          <Tab title="All (38)">
            <Layout>
              <Text>List of transactions.</Text>
            </Layout>
          </Tab>
        </TabView>
      </Layout>
    );
  }
}

export default HomeScreen;
```
**Screenshot**
![WhatsApp Image 2019-12-20 at 7 56 26 PM](https://user-images.githubusercontent.com/12408980/71261247-df661d80-2362-11ea-9815-0ba61ac0635d.jpeg)

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   1.2.0     |
| @ui-kitten/components   |   4.2.0      |

**Comment by artyorsh** [comment]
@muhzi4u you missed passing `onSelect` to `TabView`

**Comment by muhzi4u** [comment]
@artyorsh I have already added  `onSelect` in `TabView` and `TabView` is loading when I click on each tab. But it is not loading when I swipe
