### ISSUE TITLE
Text not being rendered properly (cutoff)

### ISSUE THREAD

**Issue by potateprogrammer** [akveo/react-native-ui-kitten#786]
## 🐛 Bug 

Text rendered using react-native Text component
![Screenshot_20191224_222910](https://user-images.githubusercontent.com/30571723/71416995-004dac00-269e-11ea-9871-057433016f9d.jpg)

Text rendered using ui-kitten Text component
![Screenshot_20191224_222928](https://user-images.githubusercontent.com/30571723/71416959-d72d1b80-269d-11ea-8b28-a142e68a53ae.jpg)

As you can see the text appears cutoff
I've tried re-installing all ui-kitten packages but it didn't fix it

Code for text component:
`<Text style={styles.text}>kitten</Text>`

Code for style:
`... {fontSize:48, alignSelf:'center'} ...`

Bug or error on my side? Thanks for the help!

**Comment by artyorsh** [comment]
@potateprogrammer because by default Text is also styled with lineHeight, which is less than 48. Try updating style with lineHeight or using `category` prop (that combines fontSize, fontWeight and lineHeight. Examples are [here](https://akveo.github.io/react-native-ui-kitten/docs/components/text)
