### ISSUE TITLE
I want to change the color or icon of the subMenu component， please help me，

### ISSUE THREAD

**Issue by shiqian123** [akveo/react-native-ui-kitten#787]
## 💬 Question
I want to change the color or icon of the subMenu component，                                                           
I want to change the drop arrow to other icons. please help me，
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |  1.3.1      |
| @ui-kitten/components   |     4.3.2   |

**Comment by artyorsh** [comment]
@shiqian123 if you use a [Menu With Icons example](https://akveo.github.io/react-native-ui-kitten/docs/components/menu/overview#menu), you should be able to do this with overriding color with the code below:

```
const StarIcon = (style) => (
  <Icon {...style} fill='#000000' name='star'/>
);

const data = [
  { title: 'Item 1', icon: StarIcon },
  { title: 'Item 2', icon: StarIcon },
  { title: 'Item 3', icon: StarIcon },
  // ...
];
```

**Comment by shiqian123** [comment]
![image](https://user-images.githubusercontent.com/9497069/71496819-38b4dc00-2890-11ea-9602-998ba28feac8.png)
@artyorsh  sorry ,I want change this icon ,

**Comment by artyorsh** [comment]
@shiqian123 I guess it's not possible now. I will open a new issue to track this. Thanks for reporting
