### ISSUE TITLE
Expo 36 with warning: componentWillReceiveProps has been renamed, and is not recommended for use.

### ISSUE THREAD

**Issue by nguyenrio18** [akveo/react-native-ui-kitten#792]
I face some warning after upgrading expo 36, please help to change:
componentWillReceiveProps has been renamed, and is not recommended for use.

**Comment by artyorsh** [comment]
Hi @nguyenrio18 
We can't help you with this issue because UI Kitten components don't use `componentWillReceiveProps` function, so this issue does not belong to this library
