### ISSUE TITLE
Select menu no longer has scroll view to show large list of options

### ISSUE THREAD

**Issue by jobinmatt** [akveo/react-native-ui-kitten#794]
## 🐛 Bug Report

The select menu seems to no longer have a scroll view to view large lists of options, the select menu was working fine in version 4.2.0. 

Version 4.3.2 seemed to have changed this behaviour.

**Comment by artyorsh** [comment]
Hi @jobinmatt 👋 
Thanks for report

**Comment by artyorsh** [comment]
What behavior do you mean when saying displaying large lists?

**Comment by jobinmatt** [comment]
I was trying to describe a select menu with more than 10 options in it, in the current version the select menu goes off screen when the number of options are too many. In the older version mentioned about the select menu was a fixed size with a scrollable list op options.

**Comment by artyorsh** [comment]
In both versions automatic positioning should work properly. Can you please provide related code and screencast if possible? Just tried displaying 16 items at the bottom, and it works as expected - popup menu shows above the select. Btw, you try using `placement` property to pass preferred positioning, e.g:

```js
<Select placement='top' />
```

Default is `bottom`

**Comment by jobinmatt** [comment]
This is how my select is setup, using default values:
```
<Select style={styles.inputRightColumn}
     data={units}
     placeholder='Unit'
     selectedOption={this.state.sizeUnit}
     onSelect={(sizeUnit) => this.setState({ sizeUnit })}/>
```
Here are two screenshots from both versions:
Version 4.2.0:  
![Screenshot_20200103-022529_Expo](https://user-images.githubusercontent.com/31484380/71711843-d3ea0c00-2dd0-11ea-93b6-641f61cc68dc.jpg)
Version 4.3.2:
![Screenshot_20200103-022135_Expo](https://user-images.githubusercontent.com/31484380/71711889-faa84280-2dd0-11ea-875d-2913cc2d0462.jpg)

**Comment by artyorsh** [comment]
@jobinmatt thanks. I'll investigate it. I would also appreciate if you can provide your `styles.inputRightColumn`

**Comment by jobinmatt** [comment]
here is `styles.inputRightColumn`
```
inputRightColumn: {
    flex: 1,
    paddingTop: 21,
    paddingLeft: 8,
    paddingVertical: 4,
    minWidth: 60,
  },
```

**Comment by calendee** [comment]
I'm experiencing a similar issue.  When the list of options is long, I would expect some visual indicator that this is a scroll list.  If one of the items in the bottom of the list just happens to peak above the cutoff, that tells the user they can scroll.  However, this does not always happen.  So, a scroll bar in the list would be very helpful.

Additionally, when the last item in the list (or any one below the cutoff) is selected and then the select list displayed again, it'd be really useful for the selected item to be scrolled into view.

Here's a video showing what I'm talking about.

<div style="position: relative; padding-bottom: 197.08029197080293%; height: 0;"><iframe src="https://www.loom.com/embed/3a5d1df5f4b84b2297d27848aa52038b" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;"></iframe></div>

**Comment by calendee** [comment]
Here is the relevant parts of my code:

```
  return (
    <Select
      controlStyle={style}
      data={options}
      label={label}
      name={name}
      onSelect={option => {
        setSelectedOption(option);
      }}
      placeholder={placeholder}
      selectedOption={selectedOption}
      style={styles.select}
    />
  );
```

```
const styles = StyleSheet.create({
  select: {
    width: "100%",
    marginBottom: 10,
  },
});

```

**Comment by jessicarobins** [comment]
I was debugging this a bit and it seems all the popover styles are undefined in `select.component.ts`

```
 popover: {
                    maxHeight: popoverStyles.popoverMaxHeight,
                    borderRadius: popoverStyles.popoverBorderRadius,
                    borderColor: popoverStyles.popoverBorderColor,
                    borderWidth: popoverStyles.popoverBorderWidth,
                },
```

I am not sure what the permanent solution is, but I was able to work around it by adding this to my custom mapping:

```
'Select': {
      meta: {
        parameters: {
          popoverBorderColor: {
            type: 'string'
          },
          popoverBorderRadius: {
            type: 'number'
          },
          popoverBorderWidth: {
            type: 'number'
          },
          popoverMaxHeight: {
            type: 'numbe4r'
          }
        }      
      },
      appearances: {
        default: {
          mapping: {
            popoverBorderColor: 'border-basic-color-3',
            popoverBorderRadius: 'border-radius',
            popoverBorderWidth: 'border-width',
            popoverMaxHeight: 150,
          }
        }
      }
    },
```

**Comment by artyorsh** [comment]
@jessicarobins what ui-kitten and eva version you're running?
This is actual styles with no custom mapping
![image](https://user-images.githubusercontent.com/10753921/72267135-9c7d2a00-3630-11ea-8579-7ba8bee6e143.png)

**Comment by jessicarobins** [comment]
@artyorsh I'm on ui-kitten 4.3.2 and eva 1.3.0

if it helps, my select is the accessory inside a `ListItem`:

```
function NotificationTimeSelect(props) {
  const data = reminderHours.map(hour => ({ text: formatReminderHour(hour), value: hour }))

  const renderAccessory = style => (
    <Select
      data={data}
      selectedOption={props.selected}
      onSelect={props.onSelect}
      style={[style, styles.select]}
    />
  );

  return (
    <ListItem
      title="Reminder Time"
      accessory={renderAccessory}
    />
  );
};
```

**Comment by artyorsh** [comment]
The scroll indicator is back now. 
@jobinmatt Tested it in beta with your config and everything looks fine. Could it be `customMapping` issue?
@calendee A new issue for your feature request is opened #822

**Comment by ycldz** [comment]
Merhaba

[https://www.loom.com/share/3a5d1df5f4b84b2297d27848aa52038b](https://www.loom.com/share/3a5d1df5f4b84b2297d27848aa52038b)

I have the same problem as in the video but I don't know how to solve it, can you help me? I am using UI Kitten version 5.1.2.
