### ISSUE TITLE
EVA Icon not working ,when using ICON from component

### ISSUE THREAD

**Issue by henoktsegaye** [akveo/react-native-ui-kitten#796]
## 🐛 Bug Report

When using EVA icon pack, I have an error saying that the name of the icon was not registered in the pack EVA.
![Screenshot_1577977462](https://user-images.githubusercontent.com/37017648/71673926-0d982400-2d8b-11ea-8975-0094a76ba757.png)

Here its good to not that i have react-native-svg installed also.

`<Icon name="whatever"> #`
## Expected behavior

The Icons was supposed to be displayed.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      | 4.3.2    |
| @ui-kitten/components   | 4.3.1       |

## Environment information
Ubuntu 18.04
node js version 8.10
react 16.6

 System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: x64 Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz
  Binaries:
    Node: 8.10.0 - /usr/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.13.1 - /usr/local/bin/npm
  SDKs:
    Android SDK:
      Build Tools: 27.0.3, 28.0.3, 29.0.2
      API Levels: 23, 27, 28, 29
  npmPackages:
    react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728 
    react-native: ^0.58.6 => 0.58.6

**Comment by artyorsh** [comment]
Did you follow [Icon Packages](https://akveo.github.io/react-native-ui-kitten/docs/guides/icon-packages#eva-icons) guide?

**Comment by henoktsegaye** [comment]
Of course

**Comment by henoktsegaye** [comment]
"dependencies": {
    "@eva-design/eva": "^1.3.0",
    "@ui-kitten/components": "^4.3.1",
    "@ui-kitten/eva-icons": "^4.3.2",
    "native-base": "^2.12.1",
    "proxy-polyfill": "0.1.6",
    "react": "16.6.0-alpha.8af6728",
    "react-native": "^0.58.6",
    "react-native-snap-carousel": "^3.8.4",
    "react-native-svg": "^9.13.6",

**Comment by artyorsh** [comment]
@henoktsegaye can you please provide related code where you're using `ApplicationProvider` and `IconRegistry`?

**Comment by henoktsegaye** [comment]
```
/** @format */

import { ApplicationProvider, IconRegistry } from "@ui-kitten/components";
import { light as lightTheme, mapping } from "@eva-design/eva";

import App from "./App";
import { AppRegistry } from "react-native";
import { EvaIconsPack } from '@ui-kitten/eva-icons';
import { Provider } from "react-redux";
import React from "react";
import { name as appName } from "./app.json";
import configureStore from "./store/configureStore";

const store = configureStore();

function Entry() {
  return (
      <>
    <IconRegistry icons={EvaIconsPack} />
      <ApplicationProvider mapping={mapping} theme={lightTheme}>
        <App />
      </ApplicationProvider>
      </>
  );
}

export default Entry
//this is after Redux provider
```

**Comment by henoktsegaye** [comment]
By the way, i have native base installed already, I don't know if that is conflicting somehow

**Comment by artyorsh** [comment]
@henoktsegaye I can't say that you do something wrong based on your setup. Needs investigation

**Comment by ardasatata** [comment]
> ```
> /** @format */
> 
> import { ApplicationProvider, IconRegistry } from "@ui-kitten/components";
> import { light as lightTheme, mapping } from "@eva-design/eva";
> 
> import App from "./App";
> import { EvaIconsPack } from '@ui-kitten/eva-icons';
> import React from "react";
> 
> 
> function Entry() {
>   return (
>       <>
>     <IconRegistry icons={EvaIconsPack} />
>       <ApplicationProvider mapping={mapping} theme={lightTheme}>
>         <App />
>       </ApplicationProvider>
>       </>
>   );
> }
> 
> export default Entry
> //this is after Redux provider
> ```

have u tried to wrap all your component using react.fragment?

```
    <React.Fragment>
      <IconRegistry icons={EvaIconsPack}/>
      <ApplicationProvider mapping={mapping} theme={lightTheme}>
        <RootStoreProvider value={rootStore}>
          <BackButtonHandler canExit={canExit}>
            <StatefulNavigator />
          </BackButtonHandler>
        </RootStoreProvider>
      </ApplicationProvider>
    </React.Fragment>
```

**Comment by henoktsegaye** [comment]
Thank you for your help, but I have whipped the old installation with a new one and everything is working okay

**Comment by rahmatputrawiranata** [comment]
i got error too , this icon package working fine on dev mode, but when the i build for release version this package make my apps force close maybe somebody can help me
