### ISSUE TITLE
Add OnValueChange prop to Select Component

### ISSUE THREAD

**Issue by jobinmatt** [akveo/react-native-ui-kitten#799]
## 🚀 Feature Proposal
It would be nice if there was an onValueChange prop for the Select Component as this will allow updating the selectedOption when there is a stateChange on the selectedOption value.

Currently, there is only an onSelect prop which updates the selectedOption when the user selects the option manually.

**Comment by matheuszenker** [comment]
Removed select form my screens because I need to clear all the fields.

**Comment by artyorsh** [comment]
@matheuszenker what do you mean with `clear`?

**Comment by matheuszenker** [comment]
Need to set my state as empty after clicking in other component, but the select besides the state is now empty shows the value of selection, not from state.

**Comment by artyorsh** [comment]
@matheuszenker we've got a temporary workaround on this with #824 so you can use `clear` method via ref. This is going to be released soon, but we also will back to this issue in future releases

**Comment by artyorsh** [comment]
@jobinmatt can you please also provide an example code of what you're trying to achieve? Seems like I couldn't catch your idea for the proper implementation

**Comment by jobinmatt** [comment]
One of the issues that I was having was that the select component's selectedOption property (selectedOption={this.state.selected}) would not update(the selected option that is displayed by the component) when the selected state variable(this.state.selected) was updated by some other code(this.setState({selected: 'some value'})).
