### ISSUE TITLE
Autocomplete component emergence bug

### ISSUE THREAD

**Issue by 32penkin** [akveo/react-native-ui-kitten#800]
## To Reproduce

Just try to render the Autocomplete component on the Android simulator.

## Expected behavior

Lack of crash expected: "Maximum call stack size exceeded".

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    1.3.1    |
| @ui-kitten/components   |    4.4.0-beta.1     |

## Environment information

System:
    OS: macOS 10.15.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
    Yarn: 1.21.0 - ~/.nvm/versions/node/v10.15.0/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.2
      System Images: android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.2/11B52 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by wigleyj** [comment]
i am running into the same issue. i get a stacktrace that points to line 37 and 38 of measure.component.js. It says the function bindToWindow is the problem. I peeked at the code and it looks to be getting stuck in a recursive call and never ends. not really sure how to proceed from here. I might have to go back to using react-native-autocomplete-input.

**Comment by mtbrault** [comment]
When i use this component, I have the following issue. I'm running my app with Expo on IOS.
My 'Profile' component use Autocomplete, and when I delete it, I have no problem.
![IMG_12ECA780C484-1](https://user-images.githubusercontent.com/39492061/72658095-4125a180-397a-11ea-950c-f1e5bd102294.jpeg)
