### ISSUE TITLE
Select component mutating props

### ISSUE THREAD

**Issue by saby1101** [akveo/react-native-ui-kitten#804]
## 🐛 Bug Report

Passing read-only array to Select component (Multi-select mode) causes crash.
"selectedOption is readonly" 

## To Reproduce

- pass `Object.freeze([array])` to `selectedOption` prop
- select another option from the UI

Issue is at 
https://github.com/akveo/react-native-ui-kitten/blob/f5f13d737e6d4fc0c16a077e7cf37517557151cb/src/components/ui/select/selection.strategy.ts#L83

## Expected behavior

No crash

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @ui-kitten/components   |  4.3.2       |

## Environment information

```bash

```

**Comment by artyorsh** [comment]
Hi @saby1101 
Can you please describe the use-case when `Object.freeze` needs to be passed?

**Comment by saby1101** [comment]
If you use immerjs, it will use Object.freeze internally on the objects to ensure immutability.

**Comment by artyorsh** [comment]
Got it. Let's keep it open so we can back to this in the nearest future. Thanks for reporting 👍 
Btw, do you have some workaround on it?

**Comment by saby1101** [comment]
Currently, I am making a copy of the object and then assigning it to props.
