### ISSUE TITLE
Easy way to copy and paste screens to my project from demo app

### ISSUE THREAD

**Issue by tokomeno** [akveo/react-native-ui-kitten#805]
## 💬 Question
Hello, I want to use some of the screens which are shown on kitten tricks app, is there any way to copy and paste simple and not build it just by using components. 

I created my react native app by the expo and then added kitten by the expo.

I have also cloned the demo app git@github.com:akveo/kittenTricks.git to just copy screens but there are a lot of hardcoded components that are used by screens and I need to take all the components to manually and paste to my project.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    1.3.1    |
| @ui-kitten/components   |    4.3.2     |

**Comment by artyorsh** [comment]
Thanks for report @tokomeno, we realize this problem and this app is going to be completely refactored soon. Let's keep this issue open so we can track it
