### ISSUE TITLE
Cannot interact with Modal on Android

### ISSUE THREAD

**Issue by huynhtastic** [akveo/react-native-ui-kitten#807]
## 🐛 Bug Report

Cannot interact with components inside of a modal on Android only (i.e. pressing a button rendered in a modal). This is observable in a snack created by @artyorsh for issue #718.

Modals seem to work correctly for IOS.

## To Reproduce

* Build a modal with a button on Android and try to click on the button. It will not work.

## Expected behavior

Should be able to interact with components that are rendered in a modal.

## Link to runnable example or repository (highly encouraged)

https://snack.expo.io/@art.yorsh/ui-kitten---dynamic-modals-(v4.2)

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @ui-kitten/components      |   v4.2, v4.4-beta.1    |

I've tried this with v4.2 and updated my environment to the v4.4-beta.1 and it doesn't work on both versions. One other thing I've noticed is that if you allow the backdrop for a modal, a press anywhere on the screen will trigger the callback supplied to onBackdropPress.

Popovers seem to not be affected by this bug.

**Comment by Swabow** [comment]
Still can not interact with modal on Android devices. I am using UIKitten v4.4.0

**Comment by artyorsh** [comment]
@Swabow please provide a reproducible demo
