### ISSUE TITLE
Datepicker doesnt dismiss on back press on Android

### ISSUE THREAD

**Issue by wigleyj** [akveo/react-native-ui-kitten#808]
## 🐛 Bug Report
If I open the datepicker component on a screen after the home screen and then hit the back button on android it takes me back to the previous screen and keeps the datepicker open. From this point on i can no longer interact with the screen because the datepicker is still open and no longer dismissable. Every press of the back button takes me back one screen, but leaves the datepicker open. i attached a screen shot of the date picker still open on a screen with no datepicker component.

![Screenshot_20200109-101405](https://user-images.githubusercontent.com/22456447/72079410-debd0900-32c8-11ea-94b9-30be97c473cd.jpg)

## To Reproduce

1: add datepicker component to a second, third, fourth, or later screen.
2: run app on android
3. select datepicker on next screen.
4. hit back button

## Expected behavior
datepicker should close on backbutton press

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    1.3.1    |
| @ui-kitten/components   |    4.4.0-beta.1     |

## Environment information

 System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 21, 22, 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 26.0.2, 27.0.3, 28.0.2, 28.0.3
      System Images: android-26 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5

```bash

```

**Comment by CharlyJazz** [comment]
#813

**Comment by artyorsh** [comment]
This also may be closed by #735
Thanks for reporting, we'll back to this in nearest future
