### ISSUE TITLE
Add ability to customize Text proos on TopNavigation title & description

### ISSUE THREAD

**Issue by stay2be** [akveo/react-native-ui-kitten#810]
Please add an option to add additional props to the **Text** component of **TopNavigation** used for title & description.

Our current use case is, that we need to truncate the text there and show ellipsis chars after. This could be achived by setting the `numberOfLines` prop on the `<Text numberOfLines={1}>Some long tex...</Text>` component.

Ref: https://stackoverflow.com/questions/30594080/how-to-have-ellipsis-effect-on-text

**Comment by artyorsh** [comment]
Hi @stay2be. I don't think that having something like `titleProps` or `descriptionProps` is a good solution for this and will fit library API in general. However, I do think that having `numberOfLines={1}` by default is a good option. Let's keep it open so we can track this and close in future releases.
Thanks for reporting 👍

**Comment by bogdanvidican** [comment]
Hi @artyorsh, maybe modifying TopNavigationProps interface to receive title as React.ReactNode would make sense; this way, a <Text  /> component with all the required props set could be passed.

In our case, we need to disable font scaling by setting allowFontScaling={false}

**Comment by stay2be** [comment]
Hi @artyorsh , some flexibility here would be nice, because we have also some cases where we need a multiline title and no truncation.

**Comment by artyorsh** [comment]
@stay2be we have started working on this, and it will be landed in v5. Maybe with some `alpha` versions before the official release so users can test it. You can see my proposals on this in #896 

Testing this in Kitten Tricks 👍 
![image](https://user-images.githubusercontent.com/10753921/74930560-fc64ae80-53ee-11ea-8a04-187ee975e6fd.png)
