### ISSUE TITLE
Disabling / changing the animation of tabview

### ISSUE THREAD

**Issue by Cloudef** [akveo/react-native-ui-kitten#811]
Is it possible to disable or change the animation of tabview?

**Comment by artyorsh** [comment]
No. You can describe the use-case so we can think about better API for it if needed

**Comment by Cloudef** [comment]
I just think the animation itself is too slow. If you decide to hide the bottom bar too, the feedback for selected tab title getting highlighted gets delayed for the invisible bottom bar animation duration.

**Comment by artyorsh** [comment]
@Cloudef we could think about having and api to solve this, so let's keep it open for tracking

**Comment by artyorsh** [comment]
@Cloudef closing this due to mentioning in #837
