### ISSUE TITLE
Select list still showing when i navegate to a new screen

### ISSUE THREAD

**Issue by CharlyJazz** [akveo/react-native-ui-kitten#813]
## 🐛 Bug Report

![image](https://user-images.githubusercontent.com/12489333/72210298-ec74b900-3497-11ea-9f41-a0da73920532.png)

![image](https://user-images.githubusercontent.com/12489333/72210301-f5fe2100-3497-11ea-921e-82d8914fe8c3.png)

## To Reproduce

Open a select and navegate to other screen. The absolute position list still is opening

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |        |
| @ui-kitten/components   |         |

## Environment information
"@ui-kitten/components": "^4.3.2",
"react-navigation": "^4.0.10",
 "react-navigation-drawer": "^2.3.3",
  "react-navigation-stack": "^1.10.3"

```bash

```

**Comment by artyorsh** [comment]
@CharlyJazz I'm working on this currently. Can you please describe the use-case on how do you perform navigation? In default behavior, Select should be dismissed when any touch outside is performed.
