### ISSUE TITLE
useTheme is not a function

### ISSUE THREAD

**Issue by DavidGOrtega** [akveo/react-native-ui-kitten#814]
## 🐛 Bug Report

![image](https://user-images.githubusercontent.com/414967/72226986-ae5ebe80-3597-11ea-866c-4cd19fb4ebc7.png)

## To Reproduce

```
npm i @ui-kitten/components @eva-design/eva react-native-svg
```

```js
import { useStyleSheet, useTheme,  Layout } from '@ui-kitten/components';

const THEME = useTheme();
```

## Expected behavior

The function to exist. Seems that is not present inside node_modules. Nor useTheme nor useStyleSheet either.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |1.3.1|
| @ui-kitten/components   |  4.3.2  |

## Environment information

```bash

  System:
    OS: macOS 10.15.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  Binaries:
    Node: 13.6.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  SDKs:
    Android SDK:
      API Levels: 23, 26, 28
      Build Tools: 23.0.1, 25.0.0, 26.0.1, 26.0.3, 28.0.3
      System Images: android-28 | Google APIs Intel x86 Atom
      Android NDK: 19.1.5304403
  IDEs:
    Xcode: /undefined - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

**Comment by artyorsh** [comment]
Currently, you can use this feature only in 4.4.0-beta.1
