### ISSUE TITLE
Enable string localization on DatePicker

### ISSUE THREAD

**Issue by nutritiousreject** [akveo/react-native-ui-kitten#815]
## 🚀 Feature Proposal

Currently only DD/MM/YYYY format is supported to be displayed on the datepicker component with no way to over-ride this or set a custom localization string. 

## Motivation

This is just super inconvenient for anyone living in America. Please add support for specifying any datestring 
![image](https://user-images.githubusercontent.com/22464716/72230231-b576d400-3579-11ea-90a6-f1ef72fcdd14.png)

## Example

Add a property to the datePicker components of localizationString

**Comment by artyorsh** [comment]
[Answer](https://github.com/akveo/react-native-ui-kitten/pull/816#issuecomment-573527259)
