### ISSUE TITLE
Autocomplete input box throws a 'maximum call stack size exceeded' on Android

### ISSUE THREAD

**Issue by jobinmatt** [akveo/react-native-ui-kitten#823]
## 🐛 Bug Report

On android the Autocomplete input box throws a 'maximum call stack size exceeded' error when trying to replicate the 'Autocomplete Simple Usage' [example](https://akveo.github.io/react-native-ui-kitten/docs/components/autocomplete/overview#autocomplete). It seems to be working fine on iOS.

Here is a screen shot of the error on expo:
![Screenshot_20200114-070243_Expo](https://user-images.githubusercontent.com/31484380/72343466-eb60a900-369c-11ea-9b8e-03a380731ac9.png)

## To Reproduce

Steps to reproduce the behavior: Try the 'Autocomplete Simple Usage' [example](https://akveo.github.io/react-native-ui-kitten/docs/components/autocomplete/overview#autocomplete) on an android device.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    1.3.1    |
| @ui-kitten/components   |    4.4.0-beta.1     |

**Comment by artyorsh** [comment]
This is known issue #800 and it is got fixed in #818. The fix will be available in future release soon

**Comment by dehypnosis** [comment]
not get fixed... only for me?
