### ISSUE TITLE
How to create global style component?

### ISSUE THREAD

**Issue by Triyugi** [akveo/react-native-ui-kitten#825]
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   ^1.3.1     |
| @ui-kitten/components   |    ^4.3.2     |

I would like to create a global style component so, that I can use it through out the application. For that I have created a `Style.js` file as given below;

import { StyleSheet } from 'react-native';

```
export default StyleSheet.create({
	headerContainer: {
		justifyContent: 'center',
		alignItems: 'center',
		minHeight: 216,
		backgroundColor: 'color-primary-default'
	}
});
```
And when I am importing that file in my `home.component.js` by using `import styles from '../css/Style';`, it's throwing following error:

> Invariant Violation: Invalid prop `backgroundColor` supplied to `StyleSheetheaderContainer`: color-primary-default

**Comment by artyorsh** [comment]
You can't use React Native StyleSheet with Eva style variables. You can find the way you can achieve it in [docs](https://akveo.github.io/react-native-ui-kitten/docs/components/themed-component) (you may need `useStyleSheet` function). Notice it is available starting from `4.4.0-beta.1`
