### ISSUE TITLE
Popover inside a Modal

### ISSUE THREAD

**Issue by artyorsh** [akveo/react-native-ui-kitten#826]
## 🐛 Bug Report

Popover-based components like Autocomplete or Datepicker are not updated properly if placed in Modal. The content displayed in popover may be closed whenever user starts interacting with component.

[Demo](https://i.imgur.com/ljo8cFz.gif)

## To Reproduce

```js
import React from 'react';
import { Button, Modal, Datepicker } from '@ui-kitten/components';

export const DatepickerInModal = () => {

  const [visible, setVisible] = React.useState(false);
  const [date, setDate] = React.useState(null);

  const toggleModal = (): void => {
    setVisible(!visible);
  };

  return (
    <React.Fragment>
      <Button onPress={toggleModal}>
        TOGGLE MODAL
      </Button>
      <Modal visible={visible} onBackdropPress={toggleModal}>
        <Datepicker date={date} onSelect={setDate} />
      </Modal>
    </React.Fragment>
  );
};
```

## Expected behavior

Popover-based components should be updated properly not depending on where it was rendered.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    any    |
| @ui-kitten/components   |   any      |

## Environment information

```bash
react: ~16.9.0 => 16.9.0
react-native: ~0.61.4 => 0.61.5
```

**Comment by AnasAlamin** [comment]
did anyone figure out how to solve this issue?

**Comment by skylinezum** [comment]
I think I had this same problem while using `Autocomplete` and `Input` inside a `Modal`. My solution was to move the inside of the Modal to a subcomponent, so that any state updates or rerenders would happen at a lower level than the Modal.
