### ISSUE TITLE
Modal content isn't rendering and backdrop doesn't show up

### ISSUE THREAD

**Issue by garrett-gottlieb** [akveo/react-native-ui-kitten#832]
## 🐛 Bug Report

The modal isn't showing up, nor is the backdrop.

## To Reproduce

```js
// This is my screen's structure. I copied the modal code from the modal with backdrop:
// https://akveo.github.io/react-native-ui-kitten/docs/components/modal/overview#modal
<Layout>
  <Modal ... />
  <Text />
  <KeyboardAwareScrollView />
</Layout>
```

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    1.3.1    |
| @ui-kitten/components   |   4.4.0-beta.1      |

## Environment information

```bash

```

**Comment by artyorsh** [comment]
Please [upgrade to beta.2](https://github.com/akveo/react-native-ui-kitten/issues/517#issuecomment-575060796) if you're running beta.1
