### ISSUE TITLE
Autocomplete component - Render problem

### ISSUE THREAD

**Issue by mtbrault** [akveo/react-native-ui-kitten#835]
##  🐛 Bug Report

When i use this component, I have the following issue. I'm running my app with Expo on IOS.
My 'Profile' component use Autocomplete, and when I delete it, I have no problem.

## To Reproduce

Simply copy/past the code in the documentation and try to render it : https://akveo.github.io/react-native-ui-kitten/docs/components/autocomplete/overview#autocomplete.

## Expected behavior

Having a rendered component

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    ^1.3.2    |
| @ui-kitten/components   |  ^4.3.2       |

## Environment information

System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  Binaries:
    Node: 12.4.0 - /usr/local/bin/node
    npm: 6.13.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
  IDEs:
    Android Studio: 3.2 AI-181.5540.7.32.5056338
    Xcode: 10.2/10E125 - /usr/bin/xcodebuild
  npmGlobalPackages:
    react-native-cli: 2.0.1

![IMG_12ECA780C484-1](https://user-images.githubusercontent.com/39492061/72667483-43bfdf80-39ea-11ea-8c53-c1ea90c6d2cc.jpeg)

**Comment by artyorsh** [comment]
It is available [starting from 4.4.0-beta.1](https://github.com/akveo/react-native-ui-kitten/blob/master/CHANGELOG.md#440-beta1-2020-01-03)

**Comment by artyorsh** [comment]
But you may need beta.2 because there was critical bug with this component in beta.1
