### ISSUE TITLE
Select Component Design 

### ISSUE THREAD

**Issue by meetparikh112** [akveo/react-native-ui-kitten#836]
### Select Component 
 Is there any way to change options component design in dark mode ?

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |^1.3.1|
| @ui-kitten/components   |^4.3.2|

**Comment by artyorsh** [comment]
Hi @meetparikh112 what do you dislike about select component design?

**Comment by meetparikh112** [comment]
I am not talking about select component im talking about Option container design ....

In Dark mode background is dark and select option container is also dark, so its bit difficult to see that option container is opened or not.

**Comment by artyorsh** [comment]
@meetparikh112 Please make a screenshot on what you described, thanks

**Comment by meetparikh112** [comment]
![rsz_1screenshot_from_2020-01-21_11-37-19](https://user-images.githubusercontent.com/20968172/72779727-e7a3c800-3c42-11ea-9520-d8b118aad1f1.png)

Hear i wanna to add border around the select option container ...

**Comment by artyorsh** [comment]
@meetparikh112 The list of options in select component has border by default. In case you're using `Layout` component as container, you may use `level` property to configure darknes of a background. [See API](https://akveo.github.io/react-native-ui-kitten/docs/components/layout/overview#layout)
