### ISSUE TITLE
Autocomplete-input automatically closes the keyboard on Android

### ISSUE THREAD

**Issue by jobinmatt** [akveo/react-native-ui-kitten#840]
## 🐛 Bug Report

Autocomplete-input automatically closes the keyboard when the input is pressed ([the keyboard opens and closes](https://imgur.com/a/oFkBGbv)), this happens only on a physical Android device.

## To Reproduce

I simply have an autocomplete inside a modal.

## Expected behavior

Keyboard should stay opened when the autocomplete-input is pressed on, on Android.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    1.3.1     |
| @ui-kitten/components   |    4.4.0-beta.2     |

**Comment by artyorsh** [comment]
This is a known issue when using popover-based components in modal #826

**Comment by artyorsh** [comment]
I'm not able to fix this in nearest future, but we're always welcome for contributions
