### ISSUE TITLE
Datepicker is not showing label

### ISSUE THREAD

**Issue by NathanNeves** [akveo/react-native-ui-kitten#841]
Hello Everyone,

I'm trying to set the datepicker label prop, but apparently there is some issue that he is not being displayed

**Comment by artyorsh** [comment]
@NathanNeves it seems like you're running wrong UI Kitten version.
`label` property is available [starting from v4.4.0-beta.2](https://github.com/akveo/react-native-ui-kitten/issues/517#issuecomment-575060796)
