### ISSUE TITLE
use yarn to install ui kitten

### ISSUE THREAD

**Issue by hanaechahid** [akveo/react-native-ui-kitten#844]
## 💬 Question

My question is: Can I install this ui library with yarn instead of npm?

thanks
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |        |
| @ui-kitten/components   |         |

**Comment by artyorsh** [comment]
Yes. You may use `yarn add @ui-kitten/components @ui-kitten/eva-icons react-native-svg`
Or simply [start with UI Kitten template](https://github.com/akveo/react-native-ui-kitten#quick-start), remove `package-lock.json` and call `yarn` from project root to install dependencies.
