### ISSUE TITLE
Autocompelte popover hidden by keyboard

### ISSUE THREAD

**Issue by wigleyj** [akveo/react-native-ui-kitten#845]
## 🐛 Bug Report
when using a autocomplete that is placed lower on the screen, especially while in landscape, its popover can be hidden by the keyboard and invisible to the user. I tried KeyboardAvoidingView, but this did nothing to fix the hidden popover.

## To Reproduce

place a autocomplete near the bottom of the screen and press on it to open the keyboard.
## Expected behavior
if the keyboard is open and covering the popover, then the popover should appear on top instead of bottom.

## Link to runnable example or repository (highly encouraged)
i came up with a solution, though i dont know if it is the best one. I added a keyboard listener to the autocomplete component, and if the keyboard would cover the popover, the popover opens on top. the "new" version of the autocomplete.component.js file is 

```
const { State: TextInputState } = TextInput;
export class Autocomplete extends React.Component {
    constructor() {
        super(...arguments);
        this.state = {
            optionsVisible: false,
            popOverPlacement: 'bottom',
        };
        this.popoverRef = React.createRef();
        this.inputRef = React.createRef();
        this.show = () => {
            this.popoverRef.current.show();
        };
        this.hide = () => {
            this.popoverRef.current.hide();
        };
        this.focus = () => {
            this.inputRef.current.focus();
        };
        this.blur = () => {
            this.inputRef.current.blur();
        };
        this.isFocused = () => {
            return this.inputRef.current.isFocused();
        };
        this.clear = () => {
            this.inputRef.current.clear();
        };
        this.onInputFocus = (e) => {
            if (this.props.onFocus) {
                this.props.onFocus(e);
            }
        };
        this.onBackdropPress = () => {
            this.setState({ optionsVisible: false });
        };
        this.onOptionPress = (index) => {
            if (this.props.onSelect) {
                this.props.onSelect(this.props.data[index]);
                this.setState({ optionsVisible: false });
            }
        };
        this.renderOptionElement = (info) => {
            return (React.createElement(ListItem, { title: info.item.title, onPress: this.onOptionPress }));
        };
        this.renderCustomOptionElement = (info) => {
            return (React.createElement(ListItem, { onPress: this.onOptionPress }, this.props.renderItem(info)));
        };
        this.renderInputElement = (props) => {
            return (React.createElement(Input, Object.assign({ ref: this.inputRef }, props, { onFocus: this.onInputFocus })));
        };
        this.renderComponentChildren = (props) => {
            const { data, renderItem, placeholderData, ...inputProps } = props;
            return [
                this.renderInputElement(inputProps),
                this.renderOptionListElement({ data, renderItem }),
            ];
        };
    }
    componentDidMount() {
        this.keyboardDidShowSub = Keyboard.addListener('keyboardDidShow', this.handleKeyboardDidShow);
    }
    componentWillUnmount() {
        this.keyboardDidShowSub.remove();
    }
    handleKeyboardDidShow = (event: { endCoordinates: { height: any; }; }) => {
        if(this.inputRef.current.isFocused()) {
            const {height: windowHeight} = Dimensions.get('window');
            const keyboardHeight = event.endCoordinates.height;
            const currentlyFocusedField = TextInputState.currentlyFocusedField();
            UIManager.measure(currentlyFocusedField, (originX, originY, width, height, pageX, pageY) => {
                const gap = (windowHeight - keyboardHeight) - (pageY + height) - 100;
                if (gap >= 0) {
                    this.setState({popOverPlacement: PopoverPlacements.BOTTOM}, () => {
                        this.setState({optionsVisible: true});
                    })
                    return;
                } else {
                    this.setState({popOverPlacement: PopoverPlacements.TOP}, () => {
                        this.setState({optionsVisible: true});
                    })
                }
            });
        }
    }
    get data() {
        const hasData = this.props.data && this.props.data.length > 0;
        return hasData && this.props.data || this.props.placeholderData;
    }
    renderOptionListElement(props) {
        return (React.createElement(List, Object.assign({ style: styles.optionList }, props, { data: this.data, bounces: false, renderItem: props.renderItem && this.renderCustomOptionElement || this.renderOptionElement })));
    }
    render() {
        const [inputElement, listElement] = this.renderComponentChildren(this.props);
        return (React.createElement(Popover, { ref: this.popoverRef, style: styles.popover, visible: this.state.optionsVisible, placement : this.state.popOverPlacement, fullWidth: true, content: listElement, onBackdropPress: this.onBackdropPress },
            React.createElement(View, null, inputElement)));
    }
}
```

I added a new state value, 3 new methods, and a const object. componentDidMount and componentWillUnmount where added for adding and removing the listener respectively . I also added handleKeyboardDidShow to perform the calculation, set top or bottom for position of popover accordingly, and then call setState again to open the popover. i nested the setState to make sure the opening of the popover would always happen last. This has been working for me even with multiple autocompletes on screen. Still not sure if this is the best approach though.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   1.3.1     |
| @ui-kitten/components   |   4.4.0-beta.2      |

## Environment information

```bash

```

**Comment by artyorsh** [comment]
Known issue. Please see #840 and #826

**Comment by artyorsh** [comment]
This issue can not be handled by autocomplete.
You should avoid the keyboard in a proper way based on the needs of your application since this component can't cover every use-case. See, for example, custom [KeyboardAvoidingView implementation in KittenTricks](https://github.com/akveo/kittenTricks/blob/master/src/scenes/articles/article-3/extra/keyboard-avoiding-view.component.tsx), or a [3rd party libarary](https://github.com/APSL/react-native-keyboard-aware-scroll-view) that also can help you with this issue.

Can I ask you to share your workaround here for other users who also stuck with this?

**Comment by wigleyj** [comment]
how would i change the placement property? as far as i can tell autocomplete doesn't have a placement property. at least Intellij is telling me it doesn't.

**Comment by artyorsh** [comment]
@wigleyj Sorry about that, that was our issue. Just added this property and example usage, that should solve this use-case
