### ISSUE TITLE
UiKitten doesn't works with jacklam718/react-native-modals

### ISSUE THREAD

**Issue by SiOuz** [akveo/react-native-ui-kitten#846]
## 💬 Question

When I use ui kitten component inside the modal content of  jacklam718/react-native-modals.

I get this error :

> Text: unsupported configuration.
> Using UI Kitten components is only possible with configuring ApplicationProvider.
> � Documentation: https://akveo.github.io/react-native-ui-kitten/docs/guides/getting-started#manual-installation
> 
Ui kitten works fine on my project, I have already set ApplicationProvider on startup.
I have to set <ApplicationProvider> inside the modalContent to avoid this error, but its not great because the modal become very slow.

```
import Modal, {
  ModalTitle,
  ModalContent,
} from 'react-native-modals';

import {
  Text,
  ThemedComponentProps,
  withStyles,Select
} from '@ui-kitten/components';

<Modal.BottomModal
          visible={isModalVisible}
          style={themedStyle}
          swipeDirection={['up', 'down']} // can be string or an array
          onTouchOutside={() => setModalVisible(false)}
          height={0.95}
          width={1}
          onSwipeOut={() => setModalVisible(false)}
          modalTitle={
            <ModalTitle
              title="Bottom Modal"
              style={{height: 20,padding: 0}}
              // textStyle={textStyle.subtitle}
              align="left"
              hasTitleBar
            />
          }>
        <ModalContent>
          <Text>
            Bottom Modal with Title
          </Text>
        </ModalContent>
      </Modal.BottomModal>
```
I'm missing something ?

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |      ^4.3.2  |
| @ui-kitten/components   |   ^4.3.2      |
| react-native-modals  |   ^0.19.9      |

**Comment by artyorsh** [comment]
Uhm. Faced the same running your code. I have no idea why but will investigate. Could you please also duplicate this issue to `react-native-modals` repo with referencing this one?

**Comment by SiOuz** [comment]
already did [https://github.com/jacklam718/react-native-modals/issues/213](url)

**Comment by SiOuz** [comment]
Before a patch is release... how to improve performance on loading <ApplicationProvider> </ApplicationProvider>

**Comment by artyorsh** [comment]
@SiOuz how do you use it? It should be rendered once, in the root of the application

**Comment by artyorsh** [comment]
Closing due to https://github.com/jacklam718/react-native-modals/issues/213#issuecomment-593227627
