### ISSUE TITLE
Warning when rendering Modal: Cannot update during an existing state transition

### ISSUE THREAD

**Issue by fvieira** [akveo/react-native-ui-kitten#847]
🐛 Bug Report

Rendering a Modal throws a React warning: "Cannot update during an existing state transition".

## To Reproduce

Render a modal (`<Modal visible={true}></Modal>`) while on development mode in Android (haven't tested iOS). Let me know if this is not enough, but it seems to do it for me.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    4.4.0-beta.3    |
| @ui-kitten/components   |    4.4.0-beta.3     |

**Comment by artyorsh** [comment]
Yes. Can you please provide the full code? I can't reproduce it in scope of our demo application

**Comment by fvieira** [comment]
Sure, here you go:

https://github.com/MoscaDigital/reproducemodalwarning

Just clone, run `yarn`, install app with `npm react-native run-android`, open app, and touch the "Show modal" button.

**Comment by azurinspire** [comment]
I have same problem in iOS. When I was using version 4.3.1 there was no error, it started to happen after I updated to 4.4.0-beta.3.

**Comment by artyorsh** [comment]
Thanks for the details. I prove it exists. We'll try get rid of it in the next release
