### ISSUE TITLE
Autocomplete import issue

### ISSUE THREAD

**Issue by walidpsg** [akveo/react-native-ui-kitten#856]
i have a problem with the new Autocomplete when i import it, it tell me ''node_modules/@ui-kitten/components"' has no exported member 'Autocomplete'''

im on @ui-kitten/components@4.4.0-beta.3

**Comment by artyorsh** [comment]
You might need to [restart application with clearing cache](https://github.com/akveo/react-native-ui-kitten/issues/650#issuecomment-545358903)
