### ISSUE TITLE
Delay

### ISSUE THREAD

**Issue by vipinkviswanath** [akveo/react-native-ui-kitten#860]
I use react navigation.When navigating to screens containing Applicationprovider of ui kitten i could see 2000ms+ delay to navigate to that screen.(tested in iphone se)Other screens without this root element loads on time.What is the reason? How to solve it. i think with newer phones with plenty of ram could handle that delay, but how to optimise on devices like iphone se(with smaller ram)

**Comment by artyorsh** [comment]
You don't need render ApplicationProvider per screen. It should be rendered once, [in the root of the application](https://akveo.github.io/react-native-ui-kitten/docs/guides/getting-started#manual-installation).
