### ISSUE TITLE
How to change button colour? since setting background colour avoids click effect

### ISSUE THREAD

**Issue by vipinkviswanath** [akveo/react-native-ui-kitten#861]

**Comment by artyorsh** [comment]
You may achieve this by [creating custom theme](https://akveo.github.io/react-native-ui-kitten/docs/guides/branding#branding)

**Comment by MirFahad58** [comment]
and also just like this
` <RNView
              style={{
                backgroundColor: theme['color-success-600'],
                marginTop: 10,
                width: '49%',
                marginLeft: '1%',
                borderRadius: 5,
              }}>
              <Button
                style={{borderColor: theme['color-success-600']}}
                status="control"
                appearance="ghost"
                accessoryLeft={PlusIcon}></Button>
            </RNView>`
