### ISSUE TITLE
Able to tap through modal backdrop

### ISSUE THREAD

**Issue by ctohster** [akveo/react-native-ui-kitten#862]
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |        |
| @ui-kitten/components   |         |

## Environment information

```bash

```

**Comment by artyorsh** [comment]
Would you provide a details, version, example code?

**Comment by switz** [comment]
I am also able to click through the backdrop of a modal on 4.3.1. But it appears to be fixed on 4.4.0-beta.3, so all is well. Just posting for future issue viewers.
