### ISSUE TITLE
Drawer/Home component - when use it to navigate it doesn't call the function always and after some random amount of clicks it triggers.

### ISSUE THREAD

**Issue by 5etar** [akveo/react-native-ui-kitten#864]
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |        |
| @ui-kitten/components   |         |

**Comment by 5etar** [comment]
`import React from "react";
import {SafeAreaView} from 'react-navigation';
import { DrawerItems } from 'react-navigation-drawer';
import {Image, ScrollView, StyleSheet} from "react-native";
import {
    Drawer,
    Icon,
    Button,
    Menu
} from '@ui-kitten/components';

const PersonIcon = (style) => (
    <Icon {...style} name='person-outline'/>
);

const BellIcon = (style) => (
    <Icon {...style} name='bell-outline'/>
);


const drawerData = [
    {
        title: 'Login',
        icon: PersonIcon,
    },
    {
        title: 'List',
        icon: BellIcon,
    }
];


const CustomDrawerContentComponent = (props) => {
    
    const onRouteSelect = (index) => {
        console.log('fdsa');
        const route = drawerData[index];
        // navigate with React Navigation
        props.navigation.navigate(route.title);
    };

    return (
        <SafeAreaView>
            <Drawer
                data={drawerData}
                onSelect={onRouteSelect}
            />
            <Menu
                data={drawerData}
                onSelect={onRouteSelect}
            />
            {/*<DrawerItems {...props} />*/}
            {/*<Button onPress={() => { props.navigation.navigate('List')}}>Navigate to List</Button>*/}
        </SafeAreaView>
    );
};
export default CustomDrawerContentComponent;`

**Comment by artyorsh** [comment]
What versions of UI Kitten and React Navigation your application runs?

**Comment by 5etar** [comment]
"@eva-design/eva": "^1.3.2",
    "@react-native-community/masked-view": "^0.1.6",
    "@ui-kitten/components": "4.4.0-beta.3",
    "@ui-kitten/eva-icons": "4.4.0-beta.3",

"react-navigation": "^4.0.10",
    "react-navigation-drawer": "^2.3.3",
    "react-navigation-stack": "^2.0.16"

**Comment by artyorsh** [comment]
I see no issue in your code. Moreover, I can't reproduce it running same versions. I guess, it depends on how you configured navigator. Try opening same issue at react navigation repo with example code of your navigator.

**Comment by artyorsh** [comment]
Btw, why do you use both menu and drawer components with same state?

**Comment by 5etar** [comment]
It doesn't matter. After the Drawer I've tried with the menu component and the result was same. Also I tried to make it in a class based component but the result was the same again.

**Comment by 5etar** [comment]
The problem is that it works on double click. Not opening the navigation but the onSelect method of your component when.
