### ISSUE TITLE
Weird Spinner animation inside Button component

### ISSUE THREAD

**Issue by Menganitou** [akveo/react-native-ui-kitten#866]
## 🐛 Bug Report

Weird Spinner animation when is used inside icon prop of a Button

## To Reproduce

```
  <Layout
	style={{ flex: 1, justifyContent: "flex-start", alignItems: "center" }}
  >
	<Text>Example text </Text>
	<Spinner status="warning" />
	<Button size="large" icon={() => <Spinner status="basic" />}>
	  Test button
	</Button>
  </Layout>
```

## Expected behavior
I expect that the spinner animates correctly

## Link to runnable example or repository (highly encouraged)
https://drive.google.com/file/d/1Hd9kpkjBA0oHhbN7qViSovPjjmUjjK_0/view?usp=sharing

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   ^1.3.1     |
| @ui-kitten/components   |   ^4.3.2      |

## Environment information

```bash
Android 9
```

**Comment by artyorsh** [comment]
@Menganitou 
We don't expect rendering Spinner inside a Button. Your code is a temporary workaround that **might not** work as you expect it. However, you can try using `ActivityIndicator` component from the `react-native` package.

**Comment by Menganitou** [comment]
Hi @artyorsh 
So maybe it could be a new feature in the future? It's not unusual to place a _Loading_ animation inside a button to tell the user that the action is in progress.

Anyways thanks for your suggestion. The `ActivityIndicator` solution works perfectly.

**Comment by artyorsh** [comment]
@Menganitou this feature is already requested, you can track the discussion in another issue #564
We will work on this in future, definitely
