### ISSUE TITLE
Themed component documentation problem

### ISSUE THREAD

**Issue by iimog** [akveo/react-native-ui-kitten#871]
## 🐛 Bug Report

The documentation for using themed components does not work as is.
One problem has already been reported: https://github.com/akveo/react-native-ui-kitten/issues/464 but the docu is not yet updated. There is an additional problem causing the error:

```
TypeError: undefined is not an object (evaluating '_this$props.themedStyle')
```

This is caused by accessing `this.props` in `AwesomeView` even though it is a function component and not a class.

## To Reproduce

Use the example code as given in [docs/src/articles/design-system/use-theme-variables.md](https://github.com/akveo/react-native-ui-kitten/blob/master/docs/src/articles/design-system/use-theme-variables.md)

## Expected behavior

The code should work without error message and applying the passed styles.

## Link to runnable example or repository (highly encouraged)

https://github.com/akveo/react-native-ui-kitten/blob/master/docs/src/articles/design-system/use-theme-variables.md

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    1.3.1    |
| @ui-kitten/components   |    4.3.2     |

## Environment information

```bash
  System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
  Binaries:
    Node: 13.6.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: ~16.9.0 => 16.9.0 
    react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
```

**Comment by artyorsh** [comment]
@iimog documentation is actual for 4.4.0-beta.3, which is menu on the website. Can you confirm you have this problem? [Live examples](https://akveo.github.io/react-native-ui-kitten/docs/components/themed-component) use same code

**Comment by artyorsh** [comment]
Ah, you're about `this` keyword in functional components. Then yes, thanks for reporting 😄
