### ISSUE TITLE
TypeError: Super expression must either be null or a function

### ISSUE THREAD

**Issue by zohraj** [akveo/react-native-ui-kitten#885]
I was using kitten ui with react native version 0.55.4 and created some custom components which extend RkComponent and other components from kitten ui. Now I have upgraded my react-native version to 0.61 , it gives me this error  
TypeError: Super expression must either be null or a function

**Comment by artyorsh** [comment]
We do not support v3. But this error commonly means you missed some import statement, probably, ensure you have `import { RkComponent } from 'react-native-ui-kitten'.
