### ISSUE TITLE
Select requires props onFocus, onBlur

### ISSUE THREAD

**Issue by bkwhite** [akveo/react-native-ui-kitten#886]
## 🐛 Bug Report

The select component now requires _onFocus_ and _onBlur_ properties in version 4.4.0.

## To Reproduce

`<Select
             data={this.programOptions}
             label="Program"
             onSelect={option => this.onSelect(option)}
 />`

## Expected behavior

Before version 4.4.0 onFocus and onBlur were not required by the Prop types for the select component. onFocus and onBlur should be optional props. 

## Link to runnable example or repository (highly encouraged)

😇

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    1.3.0    |
| @ui-kitten/components   |    4.4.0     |

## Environment information

```bash
react-native run-ios
```

**Comment by mdebo** [comment]
I meet the same i end up by overriding selectui-kitten  SelectProps: type MySelectProps = Omit<SelectProps, 'onFocus' | 'onBlur'>

**Comment by artyorsh** [comment]
The fix is already present in master https://github.com/akveo/react-native-ui-kitten/pull/877 and will be included in the next release

**Comment by mdebo** [comment]
@artyorsh thank you!
