### ISSUE TITLE
How to set the Select forms  background color dynamically ? 

### ISSUE THREAD

**Issue by jackywei1228** [akveo/react-native-ui-kitten#888]
## 💬 Question

How to set the Select forms  background color dynamically ? 

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |        |
| @ui-kitten/components   |         |

**Comment by artyorsh** [comment]
@jackywei1228 what do you mean with `dynamically`? Do you mean inline stylings?
