### ISSUE TITLE
CustomPicker component

### ISSUE THREAD

**Issue by veedeo** [akveo/react-native-ui-kitten#889]
It would be nice to have a custom picker component, something like datepicker or select but with ability to open a popover with custom component.
Or even something more generic so we would be able to open custom bottom sheet or dialog.

**Comment by artyorsh** [comment]
I don't get your idea. UI Kitten already includes a generic interface for that. You can use [Popover](https://akveo.github.io/react-native-ui-kitten/docs/components/popover/overview#popover) or [Modal](https://akveo.github.io/react-native-ui-kitten/docs/components/modal/overview#modal) based on your needs. All `Pickers` in this library are based on these components.
