### ISSUE TITLE
Fix document: RkChoice onPress should be onChange

### ISSUE THREAD

**Issue by 1c7** [akveo/react-native-ui-kitten#89]
## Document:
https://akveo.github.io/react-native-ui-kitten/#/docs/ui-components/rkchoice

![image](https://user-images.githubusercontent.com/1804755/34950707-e60d5e1c-fa4e-11e7-89a1-986f9f115796.png)

I pass in onPress and it didn't work at all

## so I check the source, it should be `onChange`
https://github.com/akveo/react-native-ui-kitten/blob/2f31d91cabaaa4420ada37e27a7f54774af0dfcb/src/components/choice/rkChoice.js

![image](https://user-images.githubusercontent.com/1804755/34950730-f58e3208-fa4e-11e7-876d-c2bf1b2523f4.png)

and I try `onChange`, it work
document are wrong, please fix it

Thanks!

**Comment by sergey-kozel** [comment]
Hello @1c7,

Thank you for your report!

We will fix that.
