### ISSUE TITLE
Create custom component based on theme variables

### ISSUE THREAD

**Issue by veedeo** [akveo/react-native-ui-kitten#890]
I would like to create a custom Picker component that will look like a regular Input/DatePicker/Select. Pressing on this CustomPicker should open a Modal.
I looked into code of existing pickers but couldn't understand how they get their styling.

So I came up with this code:
```
const themedStyles = StyleService.create({
  buttonTextStyle: {
    color: 'text-hint-color',
  },
  button: {
    backgroundColor: 'background-basic-color-2',
  },
});

export default function EventTimePickerInput(props) {
  const styles = useStyleSheet(themedStyles);
  return (
    <View style={props.style}>
      <Text appearance="hint">Date</Text>
      <Button
        style={styles.button}
        textStyle={styles.buttonTextStyle}
        status="basic">
        {new Date().toISOString()}
      </Button>
    </View>
  );
}
```
![image](https://user-images.githubusercontent.com/1064630/74589104-095a5a00-500b-11ea-9a4f-a9c0603be543.png)

I would like to understand how to:

1. How can I style Label Text to be exactly as default Label of Input component
2. How can I use TouchableOpacity and style it with default theme

Appreciate your help.

**Comment by artyorsh** [comment]
If you look through the source code, our components are based on a `styled` which is not only about a theme variables. Look through the [live examples source code](https://akveo.github.io/react-native-ui-kitten/docs/components/styled-component), it includes some comments on how it works.

> How can I style Label Text to be exactly as default Label of Input component

You can view Select stylings [here](https://github.com/eva-design/eva/blob/master/packages/eva/mapping.json#L3619). It may be quite complex to understand how it works, but by following the guide below you may find it simpler

> How can I use TouchableOpacity and style it with default theme

By following the Styled Component guides.
