### ISSUE TITLE
font not applied to all of my components

### ISSUE THREAD

**Issue by amira133** [akveo/react-native-ui-kitten#892]
| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    1.4.0    |
| @ui-kitten/components   |     4.4.0    |

Hi
I followed the tutorials on how to implement and add fonts, but the font does not apply to some components.
For example, fonts do not apply to buttons.

app.tsx:
```
import React from 'react';
import { ApplicationProvider, IconRegistry } from '@ui-kitten/components';
import { EvaIconsPack } from '@ui-kitten/eva-icons';
import { mapping } from '@eva-design/eva';
import { default as customMapping } from './custom-mapping.json';
import { lightTheme, darkTheme } from './custom-theme';

import { AppNavigator } from './src/navigation/navigation.component';
import { ThemeContext } from './theme-context';


const App = () => {
  return (

    <React.Fragment>
      <IconRegistry icons={EvaIconsPack} />
      <ThemeContext.Provider value={{ theme, toggleTheme }}>
        <ApplicationProvider
          mapping={mapping}
          theme={lightTheme}
          customMapping={customMapping}
          >
          <AppNavigator />
        </ApplicationProvider>
      </ThemeContext.Provider>
    </React.Fragment>
  );
};

export default App;

```

custom-mapping.json:

```
{
  "strict": {
    "text-font-family": "bad_bold_college"
  }
}
```
![image](https://user-images.githubusercontent.com/27830573/74603157-daed8500-50c5-11ea-95ac-74e03f8e9514.png)

**Comment by artyorsh** [comment]
I guess you have problems with linking. Do you run Expo?

**Comment by amira133** [comment]
no I don't use Expo and I run `yarn react-native link`.

**Comment by artyorsh** [comment]
@amira133 try running `npx react-native link` since yarn may call react-native package installed globally

**Comment by amira133** [comment]
@artyorsh thanks for response, I try `npx react-native link` but still issue not solved!!!

```
npx react-native link
info Linking assets to ios project
info Linking assets to android project
success Assets have been successfully linked to your project
```


also there is a warning in `App.txs' may caused

```
<React.Fragment>
      <IconRegistry icons={EvaIconsPack} />
      <ThemeContext.Provider value={{ theme, toggleTheme }}>
        <ApplicationProvider
          mapping={mapping}
          theme={light}
          **customMapping**={customMapping} ----->>>>>>>>Warning
          >
          <AppNavigator />
        </ApplicationProvider>
      </ThemeContext.Provider>
    </React.Fragment>
```


warning : 

```
Property 'components' is missing in type '{ "strict": { "text-font-family": string; }; }' but required in type 'CustomSchemaType'.ts(2741)
schema-customization.d.ts(3, 5): 'components' is declared here.
applicationProvider.component.d.ts(11, 5): The expected type comes from property 'customMapping' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<ApplicationProvider> & Readonly<ApplicationProviderProps> & Readonly<...>'
```

**Comment by artyorsh** [comment]
> also there is a warning in `App.txs' may caused

ts definitions for custom mapping is our fault.

I guess you still have react-native installed globally. Try running `where react-native` from command line. In case there is no `react-native` installed globally it should output `react-native` not found.
In case of other output, you should remove this package and use npx to use latest React Native CLI so it will perform linking correctly. Btw, what react-native version your application runs?

**Comment by allpwrfulroot** [comment]
I'm experiencing similar difficulty with UI Kitten and custom fonts. 

I was able to brute-force fonts when using Expo + UI Kitten in most cases, but with a default `react-native init` app I can only use custom fonts with react-native Text, UI Kitten components won't acknowledge them at all. Custom mapping, theme overrides, simple StyleSheet: they won't apply a custom font?

**Comment by mateussmohamed** [comment]
i have same problem on android platform

**Comment by HacerBusraKILIC** [comment]
Same problem

**Comment by allpwrfulroot** [comment]
You have to also specify font weight, and sometimes for each (and every) size or appearance.

**Comment by brodao** [comment]
Try
` 
<ApplicationProvider
      {...eva}
      customMapping={**merge(eva.mapping, mapping)**}
      theme={{ ...eva.dark, ...theme }}>
      <NavigationContainer>
        <DrawerNavigator />
      </NavigationContainer>`

**Comment by alinooshabadi** [comment]
I`m having the same problem. for Button component, only "borderColor", "backgroundColor", "textColor", "iconTintColor" can be overridden.
seems that something related to the default eva definition mapping file.

https://github.com/eva-design/eva/blob/58f41aafb11bfeea83540977f92a7c47b5a695ab/packages/eva/mapping.json#L446

**Comment by radihuq** [comment]
> Try
> 
> ```
> <ApplicationProvider
>       {...eva}
>       customMapping={merge(eva.mapping, mapping)}
>       theme={{ ...eva.dark, ...theme }}>
>       <NavigationContainer>
>         <DrawerNavigator />
>       </NavigationContainer>
> ```

alternatively,

```
customMapping={{...eva.mapping, mapping}}
```

**Comment by reloadedhead** [comment]
I am having this problem with the Button component. Fonts have already been linked successfully. I can't get to customize it's font family. My custom mapping json file is the following:
```
"components": {
      "Button": {
        "meta": {},
        "appearances": {
          "filled": {
            "mapping": {
              "textFontFamily": "Raleway-SemiBold",
              "iconMarginHorizontal": 4
            },
            "status":{
              "primary": {
                "textFontFamily":"Raleway-SemiBold"
              }
            }
          }
        }
      }
    }
```
And I merge mappings as commented above, with no success. Why is this so hard?

**Comment by SebuJang** [comment]
i'm also have same problem.
i solved this by wrapping.

```
//-----------
// wrapping component
//-----------
import React from 'react';
import {StyleSheet} from 'react-native';
import {Text} from '@ui-kitten/components';

const NText = (props) => {
  const {bold} = props;
  let newProps = {...props};
  newProps.style = bold
    ? {...styles.fontNanumB, ...props.style}
    : {...styles.fontNanumR, ...props.style};
  return <Text {...newProps}>{props.children}</Text>;
};

export default NText;

const styles = StyleSheet.create({
  fontNanumR: {
    fontFamily: 'NanumSquareR',
  },
  fontNanumB: {
    fontFamily: 'NanumSquareB',
  },
});

//------------------
//usage
//------------------
<NText category="h5">Test1</NText>
<NText category="h5" bold>Text2</NText>
//------------------
```

**Comment by Frixoe** [comment]
Same issue here. Don't understand why this issue was closed as it hasn't been resolved.

**Comment by MendelBak** [comment]
Same issue here. Any other solutions?

**Comment by DomenicJahn** [comment]
I'm facing the same issue using Next.js in an expo project. It doesn't matter what I try to override. 

	{
	  "strict": {
		"text-font-family": "Arial"
	  }
	}

will result in 

	Property 'components' is missing in type '{ strict: { ... }; }' but required in type 'CustomSchemaType'.ts(2741)

if `customMapping={mapping}` is defined in a `tsx` file. It does work if it's inside of a `js` file.

`customMapping={{...eva.mapping, mapping}}` does not throw an error, but doesn't work.

`customMapping={merge(eva.mapping, mapping)}` could technically work, but I don't know where to import `merge` from.

What do I need to do, to be able to to override global styles?

**Comment by DomenicJahn** [comment]
I just added an empty

    "components": {},

so the mapping gets accepted within TS.

**Comment by dasler-fw** [comment]
<img width="353" alt="image" src="https://user-images.githubusercontent.com/33331165/175819120-9fd0e3db-084c-417b-a827-b9d8e8b816b6.png">
