### ISSUE TITLE
Warning when onSelect Menu: state updates from the useState() and  usereducer() hooks don't support the second callback argument

### ISSUE THREAD

**Issue by mohamed-alashry** [akveo/react-native-ui-kitten#894]
## 🐛 Bug Report

onSelect  Menu item throws a React warning:  "state updates from the usestate() and usereducer() hooks don't support the second callback argument"

## To Reproduce

just selecting any item throws the warning

`
    <Menu
      data={data}
      selectedIndex={selectedIndex}
      onSelect={setSelectedIndex}
    />
`

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    1.4.0    |
| @ui-kitten/components   |     4.4.0    |

**Comment by artyorsh** [comment]
```js
<Menu 
  data={data}
  selectedIndex={selectedIndex}
  onSelect={index => setSelectedIndex(index)}
/>
```
