### ISSUE TITLE
ScrollView inside Tab is not working

### ISSUE THREAD

**Issue by superdev0505** [akveo/react-native-ui-kitten#899]
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |  ^1.3.0  |
| @ui-kitten/components   |  4.3.1  |

Hello

I tried to place ScrollView inside the Tab.
but it is not working.

Is there any solution for it?

Thanks.

**Comment by artyorsh** [comment]
@superdev0505 can you provide the full code?

**Comment by superdev0505** [comment]
Here is code of it.
`return (
    <SafeAreaView style={styles.body}>
      {
        loading || Object.keys(planData).length == 0 ? (
          renderLoading()
        ) : (
            <React.Fragment>
              <TopNavigation
                title={planData.plan.name}
                alignment='center'
                leftControl={BackAction()}
                style={styles.topNavigation}
                titleStyle={styles.topNavigationTitle}
              />
              <View style={{flex: 1}}>
                <TabView
                  selectedIndex={selectedIndex}
                  onSelect={setSelectedIndex}>
                  <Tab title='Exercise'>
                    <Exercises 
                      planData = {planData}
                      has_track = {has_track}
                      exerciesLog = {exerciesLog}
                      date = { date }
                      handleLike = {handleLike}
                      handleDone = {handleDone}
                      handleDislike = {handleDislike}
                      handleSlider = {handleSlider}
                      monitoringConfig = {monitoringConfig}
                      monitoringValue = {monitoringValue}
                      NextDate = {NextDate}
                      PrevDate = {PrevDate}
                      navigateDetail = {navigateDetail}
                      navigateToProm = {navigateToProm}
                    />
                  </Tab>
                  {
                    planData.advice_sheet.length > 0 &&
                    <Tab title='Advice'>
                      <Layout style={styles.tabContainer}>
                        <Text>List of orders.</Text>
                      </Layout>
                    </Tab>
                  }
                  
                  <Tab title='TRANSACTIONS'>
                    <Layout style={styles.tabContainer}>
                      <Text>List of transactions.</Text>
                    </Layout>
                  </Tab>
                </TabView>
              </View>
              <Modal
                allowBackdrop={true}
                backdropStyle={styles.backdrop}
                onBackdropPress={setVisible}
                visible={visible}>
                <Layout
                  level='3'
                  style={styles.modalContainer}>
                  <Text>{planData.plan.notes}</Text>
                </Layout>
              </Modal>
            </React.Fragment>
          )
      }
    </SafeAreaView>
)`

`const renderPlan = () => {
    if (planData.hasOwnProperty('prom')) {
      const proms = planData.prom;
      for (let i = 0; i < proms.length; i++) {
        if (proms[i].require_answers) {
          return (
            <Layout style={styles.row}>
              <Image
                style={styles.headerImage}
                source={require('../../assets/showing.png')}
              />
              <Layout style={styles.textLayout}>
                <Text
                  style={styles.headerText}
                  category='h4'>
                  Your therapist wants you to answer one Survey [{proms[i].prom_name}]
                </Text>
                <Button status="primary" onPress={()=>navigateToProm(proms[i].id, proms[i].scheduled_value)}>Press Here to Start</Button>
              </Layout>
            </Layout>
          )
        }
      }
    }
    return renderMain();
  }

  const renderMain = () => (
    <ScrollView>
      {
        has_track != 0 && (
          <Layout style={styles.row}>
            <Button onPress={PrevDate}>Prev</Button>
            <Text style={styles.date}>{date}</Text>
            <Button onPress={NextDate}>Next</Button>
          </Layout>
        )
      }
      <Layout style={styles.exerciseContainer}>
        {
          planData.exercises.map((item, index) => (
            renderExcerciseItem(item, index, planData.plan.image_type)
          ))
        }
      </Layout>
      {
        has_track != 0 && (
          <Layout style={styles.monitor}>
            {
              JSON.stringify(monitoringConfig) != "{}" &&
              planData.monitor.map((item, index) => (
                renderMonitorIem(item, index)
              ))
            }
          </Layout>
        )
      }
    </ScrollView>
  )

  const renderMonitorIem = (item, index) => {
    return (
      <Layout key={index} style={styles.monitorItem}>
        <Layout style={styles.monitorContainer}>
          <Text style={styles.date}>
            {item.patient_question}
          </Text>
          <Icon pack="fa" name={monitoringConfig[item.name].face} tintColor={monitoringConfig[item.name].color} width={30} height={30} />
        </Layout>
        <Slider
          maximumValue={parseInt(item.to)}
          minimumValue={parseInt(item.from)}
          value={monitoringValue[item.name]}
          onSlidingComplete={(val) => handleSlider(item.name, val, item.inverted_graph)}
          minimumTrackTintColor={monitoringConfig[item.name].color}
          step={1}
        />
        <Layout style={styles.sliderAddon}>
          <Text>
            {item.from_label}
          </Text>
          <Text>
            {item.to_label}
          </Text>
        </Layout>
      </Layout>
    )
  }

  return (
    <View>
      {
        renderPlan()
      }
      <Modal
        allowBackdrop={true}
        backdropStyle={styles.backdrop}
        onBackdropPress={setYoutubeVisible}
        visible={youtubeVisible}>
        {renderYouTubeVideo()}
      </Modal>
    </View>
  );`

And Here is screenshot of it.
![Screenshot_1582166111](https://user-images.githubusercontent.com/38669289/74928147-cb07c680-538d-11ea-864a-459c25d46fbc.png)

**Comment by artyorsh** [comment]
@superdev0505 I do not understand anything from here. Can you please edit your comment with [using formatting](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting) just like this?
```js
// Example
``` 
Also, please include the imports so it will be clear what components do you use.

You may also see [this example](https://github.com/akveo/kittenTricks/tree/master/src/layouts/dashboards/trainings-1) which successfully implements tabs with scrolling so I'm going to close this. Please provide a readable code so I can help you.
