### ISSUE TITLE
codesandbox template has a TypeError

### ISSUE THREAD

**Issue by wigleyj** [akveo/react-native-ui-kitten#901]
## 🐛 Bug Report

When navigating to template for code sandbox provided in bug template, i am getting an error that prevents it from loading the preview. I tried in firefox, chrome, and waterfox and all three had the same issue.
![Annotation 2020-02-20 134638](https://user-images.githubusercontent.com/22456447/74967943-f7503100-53e7-11ea-9212-aabf1ea37e28.png)

## To Reproduce

go to https://codesandbox.io/s/ui-kitten-welcome-x8q8z
## Expected behavior

Preview should load with no errors
## Link to runnable example or repository (highly encouraged)
https://codesandbox.io/s/ui-kitten-welcome-x8q8z

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |        |
| @ui-kitten/components   |         |

## Environment information

```bash

```

**Comment by artyorsh** [comment]
@wigleyj did you resolve this? I guess this is not UI Kitten problem, but maybe with react-native-svg or even codesandbox itself. Because UI Kitten requires includes react-native-svg as a peerDependency which means you should install both `@ui-kitten/components` and `react-native-svg` packages.

**Comment by wigleyj** [comment]
I have not been able to resolve it. I tried changing the packages versioning around to see if it was a version issue, but no go. I cant seem to get it to work on any of my browsers. I agree now that it seems more likely to be a react-native-svg or codesandbox issue, so i will go ahead and close this issue.
