### ISSUE TITLE
time picker and birthday picker

### ISSUE THREAD

**Issue by shachardevops** [akveo/react-native-ui-kitten#902]
## 🚀 Feature Proposal

A clear and concise description of what the feature is.

## Motivation

Please outline the motivation for the proposal.

## Example

Please provide an example for how this feature would be used.

**Comment by 32penkin** [comment]
I also really miss BirthdayPicker component!

**Comment by artyorsh** [comment]
@shachardevops @32penkin TimePicker is requested here #778, it's on the plan for v5 (#896)
> and birthday picker 
You may use [Datepicker](https://akveo.github.io/react-native-ui-kitten/docs/components/datepicker)
