### ISSUE TITLE
custom status(active color) name for toggle 

### ISSUE THREAD

**Issue by shachardevops** [akveo/react-native-ui-kitten#903]
## 🚀 Feature Proposal

A clear and concise description of what the feature is.

## Motivation

Please outline the motivation for the proposal.

## Example

Please provide an example for how this feature would be used.

**Comment by artyorsh** [comment]
There is no specific property to do that, but you may follow [Branding guide](https://akveo.github.io/react-native-ui-kitten/docs/guides/branding) to achieve this in a more appropriate way.
