### ISSUE TITLE
captionStyle not working

### ISSUE THREAD

**Issue by jasuno** [akveo/react-native-ui-kitten#906]
## 🐛 I am trying to use the property but it is not working

I expect the caption to change to the style I'm giving it 

import { Input } from "@ui-kitten/components";
import React from "react";
import { Styles } from "../config/styleSheet";
import { View } from "react-native";

const Label = props => {
  return (
    <View>
      <Input
        captionStyle={Styles.captionStyle}
        style={Styles.input}
        {...props}
        textStyle={Styles.inputText}
        captionStyle={{fontSize: 100}}
      />
    </View>
  );
};

export default Label;

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |        |
| @ui-kitten/components   |         |

## Environment information

```bash

```

**Comment by jasuno** [comment]
Documentation is wrong, the right property to use is captionTextStyle

**Comment by artyorsh** [comment]
@jasuno thanks for reporting 👍

**Comment by artyorsh** [comment]
@jasuno I guess you're using outdated version. This works properly in 4.4.1

**Comment by kockok** [comment]
@artyorsh Is `captionTextStyle` being deprecated in V5, if yes, what's the substitute?

**Comment by artyorsh** [comment]
@kockok it was. Please see https://akveo.github.io/react-native-ui-kitten/docs/migration/4x500-migration#migrate-components
