### ISSUE TITLE
Loading Button

### ISSUE THREAD

**Issue by ImAbhishekTomar** [akveo/react-native-ui-kitten#908]
## 🚀 Feature Proposal

I am a web developer and i have using  "ladda" button  for  auto disable button and showing spinner on postback,

This is really helpful if your Button have  callback for loading something like below.

## Motivation

Using This In Web - https://lab.hakim.se/ladda/

## Example

**My Custom Component**

> <KittenButton  
>         Loading={true}  
>         LoadingText={`Loading {this.state.loading}`} 
>         LoadingElement={() => {return <Spinner/>}}
> />

![btnx](https://user-images.githubusercontent.com/6933841/75262933-41d01400-5813-11ea-9436-771799a19992.png)

![Screenshot 2020-02-25 at 21 05 37](https://user-images.githubusercontent.com/6933841/75262473-9921b480-5812-11ea-93c8-9f0b1b330490.png)

**Comment by artyorsh** [comment]
duplicates #564 and will be landed in [v5](https://github.com/akveo/react-native-ui-kitten/issues/896)
