### ISSUE TITLE
Docs incorrect?

### ISSUE THREAD

**Issue by allpwrfulroot** [akveo/react-native-ui-kitten#911]
## 🐛 Bug Report

Following the docs for "Change a semantic parameter" results in style loss (loses padding, border, etc). (The default solid Button before making that semantic change works fine.)

## To Reproduce

Follow the instructions for "Change a semantic parameter":
https://akveo.github.io/react-native-ui-kitten/docs/design-system/customize-mapping#change-a-semantic-parameter

## Expected behavior

I would expect `<Button>Continue</Button>` to show an outline button.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    1.4.0    |
| @ui-kitten/components   |    4.4.1     |

## Environment information

```bash
System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5
  Binaries:
    Node: 13.6.0 - ~/.nvm/versions/node/v13.6.0/bin/node
    Yarn: 1.22.0 - ~/.yarn/bin/yarn
    npm: 6.13.7 - ~/.nvm/versions/node/v13.6.0/bin/npm
  IDEs:
    Xcode: /undefined - /usr/bin/xcodebuild
  npmPackages:
    react: ~16.9.0 => 16.9.0 
    react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 

```

**Comment by artyorsh** [comment]
@allpwrfulroot works for me with
```json
"meta": {
  "appearances": {
     "outline": {
       "default": true
     }
  }
}
```
Looks like this behavior was changed during the updates. Thanks for posting
