### ISSUE TITLE
Error calling JSTimers.callTimers

### ISSUE THREAD

**Issue by madun** [akveo/react-native-ui-kitten#912]
Hi, i always getting this error, when Metro Bundle reloaded. 
but theres no error when build from xcode. can you help me please

thanks

![IMG_9F216BCE1DF9-1](https://user-images.githubusercontent.com/5608541/75459052-6530c580-59b1-11ea-8e50-4138738cc576.jpeg)

System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Memory: 23.83 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 23.0.1, 28.0.3, 29.0.2
      System Images: android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.3/11C24b - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by artyorsh** [comment]
I can't say this is UI Kitten issue by reviewing this logs. You can see a thread with same issue [here](https://github.com/facebook/react-native/issues/23200)
