### ISSUE TITLE
Select Placeholder color

### ISSUE THREAD

**Issue by pasalino** [akveo/react-native-ui-kitten#915]
## 💬 Question

In Select Componente Kitten exposes `placeholderStyle` to change style in placeholder.
I make this component in my app:
```react
       <Input
          label={i18n.t('NEW_POI_NAME')}
          labelStyle={{color: '#FF0000'}}
          placeholderTextColor="#FF0000"
          placeholder={i18n.t('NEW_POI_NAME_TOOLTIP')}
        />
        <Select
          label={i18n.t('NEW_POI_TYPES')}
          labelStyle={{color: '#FF0000'}}
          placeholderStyle={{
            placeholderTextColor: '#FF0000',
            fontSize: 40,
            fontWeight: '800',
            color: '#FF0000',
          }}
          data={poiTypesSelect}
        />
```
The result is: the input change placeholder color, the select ignore completaly placeholderStyle

![image](https://user-images.githubusercontent.com/18738567/75545288-31dc4e00-5a26-11ea-87c6-d9846438027f.png)

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    1.4.0    |
| @ui-kitten/components   |   4.4.1      |

**Comment by artyorsh** [comment]
It accepts TextStyle props, not that you pass to TextInput
```js
placeholderStyle={{ color: '#FF0000' }}
```

**Comment by pasalino** [comment]
Sorry but seems not to work.
```
        <Select
          label={i18n.t('NEW_POI_TYPES')}
          labelStyle={{ color: '#FF0000' }}
          placeholderStyle={{ color: '#FF0000' }}
          data={poiTypesSelect}
        />
````

![image](https://user-images.githubusercontent.com/18738567/75554335-6a862280-5a3a-11ea-9c97-b567900c2303.png)

**Comment by artyorsh** [comment]
@pasalino prove this is a bug. By looking through your code, you use same text color everywhere. Currently, you can solve this with custom theme:
```json
"text-default-color": "#FF0000"
```

The fix for styling it inline will be available soon
