### ISSUE TITLE
Is there a way to make icon inside Button bigger? 

### ISSUE THREAD

**Issue by Timikcool** [akveo/react-native-ui-kitten#916]
## 💬 Question

Hey! Working on audio player and wondering is there's a way to make icons really huge inside Button? 

Currently having:
![photo_2020-02-28_18-26-35](https://user-images.githubusercontent.com/26065587/75570700-f78ba480-5a57-11ea-9b08-6f9d99d8b79a.jpg)

But I want to implement something closer to Spotify design:
![image](https://user-images.githubusercontent.com/26065587/75570863-581ae180-5a58-11ea-83c6-82134b770974.png)

**Comment by Timikcool** [comment]
Forgot to mention that I'm passing "giant" for to size of Buttons

**Comment by artyorsh** [comment]
You may pass width and height directly to Icon

```
<Icon {...props} width='' height='' name='...' />
```
