### ISSUE TITLE
Icons not showing up on Android

### ISSUE THREAD

**Issue by mcostaflor** [akveo/react-native-ui-kitten#917]
Followed the Icon Package getting started on the documentation but couldn't make Android to show Icons, iOS is doing fine.

How do I check if there's something wrong with my installation? console is clear, did the tutorial three or four times already.

**Comment by artyorsh** [comment]
What versions of `@ui-kitten/components`, `@ui-kitten/eva-icons` and `react-native-svg` do you use?
Also, do you use Expo?

**Comment by mcostaflor** [comment]
No expo, fixed it last night.

After some other changes the terminal came up with something about some dependecies being already linked and suggested running react-native unlink, which worked.
