### ISSUE TITLE
Multiline autocomplete

### ISSUE THREAD

**Issue by pasalino** [akveo/react-native-ui-kitten#921]
## 💬 Question

In AutoComplete component i've set multiline at true and numberOfRow at 4 .
The result is: the component growth till 4 lines, but if i have only 1 line the component show only one line:

![image](https://user-images.githubusercontent.com/18738567/75711058-02e40780-5cc6-11ea-88c5-df2ab15f15a3.png)

![image](https://user-images.githubusercontent.com/18738567/75711100-15f6d780-5cc6-11ea-917d-542cdb22a9a6.png)

But if i set the height atleast 200px if i have only one line, the component not show the gray square directly for 4 lines.

```
 <Autocomplete
          inputStyle={{
            color: 'black',
            height: 350,
            width: 250,
          }}
```

![image](https://user-images.githubusercontent.com/18738567/75711249-5bb3a000-5cc6-11ea-9a0d-ae5a177889e0.png)

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   4.4.1     |
| @ui-kitten/components   |  4.4.1       |

**Comment by artyorsh** [comment]
@pasalino 

```js
<Layout style={{ flex: 1, justifyContent: 'center' }}>
      <Autocomplete
        multiline={true}
        numberOfLines={4}
        value={value}
        data={data}
        onChangeText={onChangeText}
        onSelect={onSelect}
      />
    </Layout>
```

![image](https://user-images.githubusercontent.com/10753921/75760776-e50bb680-5d48-11ea-85c9-a4ca9b52fe70.png)

**Comment by pasalino** [comment]
My question means that i want input text directly with 4 line height when never are inserted in.

When the component is blank, the inputbox must have 4 line height instead of adapt when insert text

**Comment by artyorsh** [comment]
You may use `style` prop to set needed height

**Comment by pasalino** [comment]
Not work! Produce only white space after component 
`<Autocomplete
          style={{
              height: 200,
            }}
          inputStyle={{
            color: 'black',
            height: 150,
            width: 250,
          }}
          style={{
            flexGrow: 2,
            width: '100%',
            minHeight: 200,
            color: 'black',
            height: 200,
          }}`

![image](https://user-images.githubusercontent.com/18738567/75764434-221e7b80-5d3e-11ea-9afa-43cd1303cc30.png)

**Comment by artyorsh** [comment]
@pasalino agreed. Thanks for posting this.
However, there is a workaround for this. You may pass `height` directly to Autocomplete without using `style`

```js
<Autocomplete                
  height={200}               
  {...props}     
/>                           
```

Should work, but warn if you use typescript

**Comment by pasalino** [comment]
it work!
