### ISSUE TITLE
CardHeader doesn't respond to activeOpacity or onPress

### ISSUE THREAD

**Issue by m4ttheweric** [akveo/react-native-ui-kitten#923]
## 🐛 Bug Report

In version 4.4.1, CardHeader does not respond to activeOpacity or onPress for the Card element. This means that if either of those props are used to handle touches to the card, touches to the header don't do anything. This seems to me like a UX problem at the least or a bug at worst.

## Expected behavior

I would expect things handled on the Card element to also work for the header.

**Comment by artyorsh** [comment]
@m4ttheweric that's true. We're sorry for that issue.
I recommend you using custom header as it is simple component able to render only title and subtitle Texts. We're going to deprecate it in v5

**Comment by artyorsh** [comment]
@m4ttheweric 🤔 I guess I found a quick workaround for you. You may pass `onPress` to CardHeader and set it handler to same function you pass to Card. Ugly, but should work

**Comment by m4ttheweric** [comment]
thanks, yes I was able to get around it by passing the same handler to both onPress props. I also had to pass the same value to activeOpacity on the CardHeader as well to make it look right.
