### ISSUE TITLE
Autocomplete items are not showing when user taps on screen.

### ISSUE THREAD

**Issue by trcielomuyot** [akveo/react-native-ui-kitten#924]
## 🐛 Bug Report

Autocomplete items are not showing when user taps on screen, unless the focus was removed from the input then returned.

## To Reproduce

1. Tap on autocomplete input, the dropdown list will show as expected.
2. Tap on the autocomplete input once again or on any part of the screen.
3. When you type the filter query, the dropdown list doesn't show unless you remove then return the focus to the input.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/23519585/75745477-66b41200-5d52-11ea-9937-2951c0a598ab.gif)

## Expected behavior

The dropdown list should remain shown while the focus is in the autocomplete input.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   ^1.4.0     |
| @ui-kitten/components   |  ^4.4.1       |

## Environment information

```bash
System:
    OS: macOS Mojave 10.14.6
    CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
  Binaries:
    Node: 10.17.0 - /usr/local/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
```

**Comment by artyorsh** [comment]
@trcielomuyot thanks for reporting. 
I guess this is a bit complex to fix it currently, because when options list becomes visible everything under it becomes a backdrop with touch handler, which closes options on tap. We may back to this later.

**Comment by cristianmiranda** [comment]
I've been fighting with this bug all day, I should have came here first 🤦‍♂. Any updates? 
I'm also struggling with another issue (probably related): Whenever I tap outside (the text input and the popover), the popover hides itself but the input keeps the focus. I must tap twice to get it blurred 😕 

![Screen Recording 2020-03-29 at 19 34 06](https://user-images.githubusercontent.com/972572/77862826-65acbe00-71f4-11ea-9887-740fd4582fe4.gif)
