### ISSUE TITLE
ListItem Icon as Accessory

### ISSUE THREAD

**Issue by pitschbr** [akveo/react-native-ui-kitten#931]
## 💬 Question
Is there a better way to use an Icon as the right-hand accessory in a ListItem?
If you try to set your accessory to be an Icon, then icon doesn't show up.
You can add a style for height and width and it will show up, but it won't be themed.
If you try to use tintColor or fill, those properties seem to be ignored and the icon shows in black.
The best workaround I have so far is to make the accessory a ghost Button with the icon, but that creates an unnecessary button.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   1.4.0     |
| @ui-kitten/components   |   4.4.1      |

Examples:
1) This one won't show anything
  <ListItem title='Title'
   accessory={style => <Icon style={style} name='arrow-ios-forward-outline' />} />
2) This one shows up but is not themed (if you add tintColor or fill they are ignored)
  <ListItem title='Title'
     accessory={style => <Icon style={[style, { width: 24, height: 24 }]} name='arrow-ios-forward-outline' />} />
3) This is the only way I can seem to get it themed, but it creates a button I don't need
  <ListItem title='Title'
    accessory={style => (
      <Button style={style} appearance='ghost' 
          icon={style => <Icon {...style} name='arrow-ios-forward-outline' />}
       />
    }/>

**Comment by pitschbr** [comment]
Please Disregard.
After looking through the repo and seeing how the code works I figured it out. I used 'useTheme' and some styles to get it work correctly. 
const theme = useTheme();
...
  accessory={style => (
        <Icon
          style={[style, myStyle.iconAccessory]} // setting height and width here
          fill={theme['color-basic-600']}
          name='arrow-ios-forward-outline'
        />
      )}

**Comment by artyorsh** [comment]
@pitschbr you could use `style={{ flexDirection: 'row-reverse }}` :)

**Comment by pitschbr** [comment]
> @pitschbr you could use `style={{ flexDirection: 'row-reverse' }}` :)

Thank you, that's a good idea.  Unfortunately they wanted icons on both sides of the list.  I was going to alter my local library and add an 'iconAccessory' property to ListItem so that it would follow the theme automatically, but decided against that for now.
