### ISSUE TITLE
Toggle size ?

### ISSUE THREAD

**Issue by dovahkrid** [akveo/react-native-ui-kitten#932]
## 💬 Question
Can the toggle be smaller or sizable ? There is a "size" property but it's useless.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |  4.4.1      |
| @ui-kitten/components   |  4.4.1       |

**Comment by artyorsh** [comment]
@dovahkrid currently, this can only be achieved by [cusomizing mapping](https://akveo.github.io/react-native-ui-kitten/docs/design-system/customize-mapping#change-a-semantic-parameter). `size` declaration is our fault. Thanks for reporting this.

**Comment by dovahkrid** [comment]
You mean like this ?

`{
  "components": {
    "Toggle": {
      "meta": {
        "appearances": {
          "size": {
            "default": "tiny"
          }
        }
      }
    }
  }
}`

**Comment by artyorsh** [comment]
Yes, see the current implementation [here](https://github.com/eva-design/eva/blob/master/packages/eva/mapping.json#L5204). You might be interested in all `*width` and `*height` parameters to make it look consistent.

**Comment by jasuno** [comment]
how do I access the `*width` and `*height` parameters? can you please put an example?

**Comment by cangSDARM** [comment]
How to adopt the size that needs to be dynamically modified?

**Comment by phoenixbeats01** [comment]
I'm having trouble with this too, I've done this:

`"Toggle": {
        "meta": {
          "appearances": {
            "default": {
              "mapping": {
                "width": 22,
                "height": 20,
                "borderRadius": 6,
                "borderWidth": 0,
                "thumbWidth": 10,
                "thumbHeight": 10,
                "thumbBorderRadius": 14,
                "outlineWidth": 14,
                "outlineHeight": 42,
                "outlineBorderRadius": 21,
                "textMarginHorizontal": 12,
                "textFontSize": "text-subtitle-2-font-size",
                "textFontWeight": "text-subtitle-2-font-weight",
                "textFontFamily": "text-subtitle-2-font-family",
                "iconWidth": 12,
                "iconHeight": 12
              }
            }
        }
      }
    }`

and put it inside my `mapping.json` file, however I don't see any results. What am I doing wrong? Thanks.

**Comment by siarheipashkevich** [comment]
@cangSDARM did you find a solution?

**Comment by cangSDARM** [comment]
Forcibly override with `style` : )

> @cangSDARM did you find a solution?

**Comment by siarheipashkevich** [comment]
@cangSDARM per each component? I think it can decrease performance..

**Comment by findhumane** [comment]
This worked for me:

```
            <ApplicationProvider
              {...eva}
              theme={eva.light}
              customMapping={
                {
                  components: {
                    Toggle: {
                      appearances: {
                        default: {
                          mapping: {
                            width: 39,
                            height: 24,
                            borderRadius: 12,

                            thumbWidth: 20,
                            thumbHeight: 20,
                            thumbBorderRadius: 10,

                            outlineWidth: 39,
                            outlineHeight: 24,
                            outlineBorderRadius: 12,

                            textMarginHorizontal: 12,

                            iconWidth: 12,
                            iconHeight: 12
                          },
                          variantGroups: {
                            status: {
                              basic: {
                                backgroundColor: "#ffffff",
                                thumbBackgroundColor: "#dddddd",
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            >
```

**Comment by luoyuex** [comment]
The checkbox sets the size, this is the code:
`<ApplicationProvider {...eva} theme={eva.light} customMapping={{
      "components": {
        "CheckBox": {
          "appearances": {
            "default": {
              "mapping": {
                "width": 16,
                "height": 16
              }
            }
          }
        }
      }
    }}>`
