### ISSUE TITLE
App crashed when nesting components in `NavigationContainer`

### ISSUE THREAD

**Issue by iam-kevin** [akveo/react-native-ui-kitten#934]
The application through `expo` crashes when I touch any component that has been nested in a `NavigationContainer`. So far, this happens when I use the `Stack.Navigator`

I am using these relevant packages from the `dependencies`
```json
{
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "~0.61.4",
    "react-native-safe-area-context": "^0.7.3",
    "@react-navigation/native": "^5.0.8",
    "@react-navigation/stack": "^5.1.1",

    "@eva-design/eva": "^1.4.0",
    "@ui-kitten/components": "^4.4.1",
}
```

Also, I am running my application on through Expo App installed on Android `7.0`
## To Reproduce

To reproduce the bug, create any UI Kitten component and nest it in the `NavigationContainer`. To start you of, mine looks something like this:

`SampleScreen.js`
```js
import React, { useState } from 'react'
import { Layout, Input, Button } from '@ui-kitten/components'
import { SafeAreaView } from 'react-native-safe-area-context'

export default () => {
    const [ number, setNumber ] = useState('')

    return (
        <SafeAreaView>
            <Layout style={{ flex: 1 }}>                
                <Text>Your number is: {number}</Text>
                <Input placeholder='Enter a number' keyboardType='numeric' value={number} onChange={setNumber(number)}/>
            </Layout>
        </SafeAreaView>
    )
}
```

and in the `App.js`
```js
import React from 'react'
import { SafeAreaProvider } from 'react-native-safe-area-context'
import { ApplicationProvider } from '@ui-kitten/components'
import ErrorBoundary from './src/components/error_boundary'

import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';

import SampleScreen from './src/screens/SampleScreen'

const Stack = createStackNavigator();

export default function App() {
    return (
        <SafeAreaProvider>
            <ApplicationProvider>
                <ErrorBoundary>
                    <NavigationContainer>
                        <Stack.Navigator headerMode='none'>
                            <Stack.Screen name='Sample' component={SampleScreen} />
                        </Stack.Navigator>
                    </NavigationContainer>
                </ErrorBoundary>
            </ApplicationProvider>
        </SafeAreaProvider>
    )
}
```
If you so much as breath 😅 (I mean touch) the app at this point. It crashes

## Environment information
This was the output obtained form running `npx envinfo --preset react-native`
```bash
PS X:Path\to\Project>npx envinfo --preset react-native
  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 12.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: ~16.9.0 => 16.9.0 
    react-native: ~0.61.4 => 0.61.5 
```

**Comment by artyorsh** [comment]
@iam-kevin this one?
![image](https://user-images.githubusercontent.com/10753921/76058692-25a84180-5f8e-11ea-9389-c98093b9c80a.png)

Because in react-native you should use `onChangeText` instead of `onChange` 👍
See the code in [live examples](https://akveo.github.io/react-native-ui-kitten/docs/components/input)

**Comment by iam-kevin** [comment]
Putting aside the `onChange` property, even when there is just the `<Input placeholder="Type here" />` The application still crashes. This only happens when the components are wrapped in the `NavigationContainter`

**Comment by artyorsh** [comment]
@iam-kevin what is a stack trace?

**Comment by iam-kevin** [comment]
No stackTrace was ever printed. It only showed that the app has crashed.
I was able to resolve the problem. This had nothing to do with the `@ui-kitten/components` 

After reviewing the documentation for the `react-navigation`, It seems I had forgotten to add

```js
import 'react-native-gesture-handler`
```

at the root of my application.

After that, everything worked out alright
