### ISSUE TITLE
feature(Select): add a 'renderItem' prop similar to Autocomplete

### ISSUE THREAD

**Issue by kaminskypavel** [akveo/react-native-ui-kitten#936]
## 🚀 Feature Proposal

A clear and concise description of what the feature is.
add a a 'renderItem' method to a Select component

## Motivation
for a very similar reason we use renderItem in autocomplete , i think most of us would be happy to add a visual icon to the list component shown on the the dropdown/select

Please outline the motivation for the proposal.

## Example

Please provide an example for how this feature would be used.

**Comment by artyorsh** [comment]
Hi @kaminskypavel 
This will be landed in v5, you can see the new syntax for these components [here](https://github.com/akveo/react-native-ui-kitten/issues/896#issuecomment-595748412)

**Comment by kaminskypavel** [comment]
@artyorsh thanks for the clarification! 🎉
