### ISSUE TITLE
undefined is not an object stylesheet$flatten.height when adding icon

### ISSUE THREAD

**Issue by jithinlal** [akveo/react-native-ui-kitten#937]
Now, this error is happening a lot of time now, and I am always looking for an alternative all the time.
When i import Icon from ui-kitten components, all the time it is throwing me this error.

And I just added the icon as given in the documentation.

Please have a look.

`<Icon name="star" width={32} height={32} fill="#3366FF" />`

Is there anything wrong in the way I do things here?

**Comment by artyorsh** [comment]
I guess this can be caused by recent updates of react-native-svg library.
Try `<Icon style={{ width: 32, height: 32 }} fill='#3366FF' name='star' />`
