### ISSUE TITLE
Autocomplete doesn't exist in the ui kitten library files

### ISSUE THREAD

**Issue by AnasAlamin** [akveo/react-native-ui-kitten#938]
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but 
got: %s.%s%s, undefined,  You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |        |
| @ui-kitten/components   |         |

## Environment information

```bash

```

**Comment by artyorsh** [comment]
What UI Kitten / Eva versions you run?
Did you update from previous versions? In case yes 👇 
https://github.com/akveo/react-native-ui-kitten/issues/930

**Comment by AnasAlamin** [comment]
> What UI Kitten / Eva versions you run?
> Did you update from previous versions? In case yes 👇
> #930

my @ui-kitten/components is 4.3.2

**Comment by artyorsh** [comment]
Autocomplete was released in 4.4
