### ISSUE TITLE
After creating a SELECT list, Expo returns an error

### ISSUE THREAD

**Issue by SerTimBerrners-Lee** [akveo/react-native-ui-kitten#941]
After creating a SELECT list, Expo returns an error
State updates from the useState() and useReducer() Hooks don't support the second callback argument. To execute a side effect after rendering, declare it in the component body with useEffect().%s,

**Comment by artyorsh** [comment]
@SerTimBerrners-Lee related code?

**Comment by achyutb6** [comment]
`const [eventType, setEventType] = React.useState(null);`
`<Select
                data={filterData}
                selectedOption={eventType}
                onSelect={setEventType}
              />` 

Gives this warning on Expo -

Warning: State updates from the useState() and useReducer() Hooks don't support the second callback argument. To execute a side effect after rendering, declare it in the comp
onent body with useEffect().%s,

**Comment by artyorsh** [comment]
```
onSelect={ type => setEventType(type) }
```
