### ISSUE TITLE
Input component has unremovable margin at the bottom

### ISSUE THREAD

**Issue by sudomann** [akveo/react-native-ui-kitten#942]
## 🐛 Bug Report

The `Input` component has some space at the bottom which I have not been able to remove by setting `margin: 0`
![Screenshot_20200312-021107](https://user-images.githubusercontent.com/16912950/76493358-d9835400-6408-11ea-998c-805bf45d8229.png)

## To Reproduce
```jsx
// ...
<Layout>
  <Input style={{margin: 0}} />
</Layout>
//...
```

## Expected behavior

I should see only the input element with no additional spacing

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |     1.4.0   |
| @ui-kitten/components   |    4.4.1     |

## Environment information

```bash
  System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
  Binaries:
    Node: 12.6.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 21, 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-25 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.1 => 16.8.1 
    react-native: ^0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

**Comment by artyorsh** [comment]
Thanks for reporting. I've got this fixed in the upcoming v5, so I'm going to close this.
As for workaround, you may use the negative margin `marginBottom: -4`

**Comment by grigoll** [comment]
@artyorsh I'm running latest 5.0.0 version but _margin:0/marginBottom:0_ doesn't work and I still have to use your workaround. Any thoughts?
