### ISSUE TITLE
Select component not working inside modal

### ISSUE THREAD

**Issue by Frans-L** [akveo/react-native-ui-kitten#945]
## 🐛 Bug Report

[Select](https://akveo.github.io/react-native-ui-kitten/docs/components/select/overview#select) component is not working inside [react-native's modal](https://reactnative.dev/docs/modal). The options are rendered under the modal, so no items can be selected.

Select does not show options:
![photo6014672313443791435](https://user-images.githubusercontent.com/29607206/76710105-3afb3980-670d-11ea-9974-909b0c9d49ea.jpg)

With opacity, the problem can be noticed:
![photo6014672313443791434](https://user-images.githubusercontent.com/29607206/76710103-39317600-670d-11ea-9c7c-bcd7ab60f9ad.jpg)

## To Reproduce

Put Select component inside a modal.

## Expected behavior

Select component should work inside modal.

## Link to runnable example or repository (highly encouraged)

```javascript
import React from "react";
import { View, Modal } from "react-native";
import {
  ApplicationProvider,
  Layout,
  Text,
  Select,
} from "@ui-kitten/components";
import { mapping, light as lightTheme } from "@eva-design/eva";

const data = [{ text: "Option 1" }, { text: "Option 2" }, { text: "Option 3" }];

const HomeScreen = () => (
  <Layout>
    <Modal visible transparent>
      <View
        style={{
          flex: 0,
          padding: 100,
          backgroundColor: "red",
          opacity: 0.5,
        }}
      >
        <Select data={data} onSelect={() => 0}></Select>
        <Text style={{ marginTop: 10 }}>
          Cannot select modals. The options are rendered under the modal.
        </Text>
      </View>
    </Modal>
  </Layout>
);

const App = () => (
  <ApplicationProvider mapping={mapping} theme={lightTheme}>
    <HomeScreen />
  </ApplicationProvider>
);

export default App;

```

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |     1.4.0   |
| @ui-kitten/components   |   4.4.1   |

**Comment by artyorsh** [comment]
UI Kitten uses it's own implementation of [Modal](https://akveo.github.io/react-native-ui-kitten/docs/components/modal/overview#modal) which Select relies on.

**Comment by Frans-L** [comment]
That's unfortunate, since the native modal's (especially react-native-modal's) animation features outperform UI Kitten's version.  

Would you @artyorsh be interested in a pull request that adds support to native modals? It would mean that you could add a separate component inside native modal that renders UI Kitten's modal inside native modal?

**Comment by artyorsh** [comment]
@Frans-L pr's are always welcome, I would be glad to review 👍

**Comment by CedThen** [comment]
What happened to the pull request? I'm also running into this problem, is it possible to see @Frans-L 's solution?

**Comment by jaredswenson** [comment]
Is there a solution for this?

**Comment by Codelica** [comment]
This can be a difficult limitation to discover, and ends up affecting a number of components (select, popover, overflow, etc) when used on a React Native modal.   Simple tossing a `ModalPanel` wrapper under RN's `Modal`  (as one issue suggests) does allow the elements to display, but can also create issues with other elements present behind the modal.  It's not the answer.  

I'd be eternally grateful if the authors could provide some insight as to wether this is a "lost cause" or if there is some sort of (even semi-hackish) workaround that could work.   Kitten UI has saved me a LOT of time overall, but this is one of a couple pain points that keep coming up for me.

**Comment by isaachinman** [comment]
@artyorsh This issue should not be closed. The `Select` component does not render correctly inside iOS-native modal presentations for screens.

**Comment by palicko** [comment]
This seems to be fixed in https://github.com/akveo/react-native-ui-kitten/pull/1615 in version `5.2.0` version of the `@ui-kitten/components` (it's not released yet at this moment and it's tagged as `next`)
