### ISSUE TITLE
Card Status Accent on Cards without Header

### ISSUE THREAD

**Issue by lukeramsden** [akveo/react-native-ui-kitten#947]
## 🚀 Feature Proposal

Have card statuses show on cards without  a `CardHeader`.

## Motivation

For me, I'm using cards to separate out sections in a form, and I'd like to use the card status to show the validation status of the section, but right now you have to have a `CardHeader` set on the card for the accent bar to show. I'm not sure whether this is an oversight or intentional, can anyone confirm either way?

**Comment by artyorsh** [comment]
@lukeramsden this is a bug in v4, I'm not sure if it can be fixed without breaking changes as it needs changes in Eva. However, this is fixed in v5 #914 and is waiting for the review. I guess we can close this?

**Comment by lukeramsden** [comment]
@artyorsh I see, well then if it's fixed by that PR then you could add 'Closes #947' to it. Thanks for all the hard work on V5, looks like that fixes a lot of the issues I've had to patch out or work around in my app.

**Comment by artyorsh** [comment]
@lukeramsden yes that makes sense.
Thanks, I think this will be public this week (may be with alpha release for the first versions :) )
