### ISSUE TITLE
Improve TypeScript annotations for known properties like Text category 

### ISSUE THREAD

**Issue by hrastnik** [akveo/react-native-ui-kitten#949]
## 🚀 Feature Proposal

Improve TypeScript annotations for knows properties like Text category, appearance etc. Currently the type is `string`, while it could be changed to `"h1" | "h2" | "h3" ...`

## Motivation

Editor autocomplete feature could offer available options, and developers wouldn't need to open docs to know the available options are.

## Example
Current type annotation for Text category prop is 

  `category?: string;`

If the type was changed to list all available categories like this: 

  `category?: "h1" | "h2" | "h3" ...`
 
...Then the editor autocomplete feature could offer those options.

**Comment by artyorsh** [comment]
I'm going to close this, this is already implemented and will be landed v5 #914
