### ISSUE TITLE
Dead link in docs

### ISSUE THREAD

**Issue by RWOverdijk** [akveo/react-native-ui-kitten#951]
First off: awesome looking elements. 

Second: Not really something that warrants the template. 

https://github.com/akveo/react-native-ui-kitten/blob/master/docs/src/articles/guides/components/drawer does not exist.

Linked to from: https://github.com/akveo/react-native-ui-kitten/blob/master/docs/src/articles/guides/configure-navigation.md

Now I'm left wondering how to integrate these two in a nice way. Where did the guide go? :)

**Comment by artyorsh** [comment]
@RWOverdijk these links are used as relative to the [documentation website](https://akveo.github.io/react-native-ui-kitten/) assuming you're reading it and not the github markdown 😄. 

What you're trying to open, should be opened from [here](https://akveo.github.io/react-native-ui-kitten/docs/guides/configure-navigation)

**Comment by artyorsh** [comment]
Btw, what do you mean with

> Second: Not really something that warrants the template.

**Comment by RWOverdijk** [comment]
@artyorsh Ah, I meant the github issue template.  Just explaining why I truncated it 😄

Regarding the link: good point. I'm too used to reading markdown files directly, my bad.
