### ISSUE TITLE
Where are the UI kitten mappings?

### ISSUE THREAD

**Issue by RWOverdijk** [akveo/react-native-ui-kitten#953]
I'm trying to create a custom SectionList, for which I'd like to closely follow the List component. But I can't find the mapping for List so I don't fully know how to do that.

## 💬 Question

Where are the UI kitten mappings? Are they in this repo? I could only find mappings in the showcase directory.

**Comment by artyorsh** [comment]
[Here](https://github.com/eva-design/eva/tree/master/packages/eva) or [here](https://github.com/eva-design/eva/tree/master/packages/material), depending on what design package you use. Thanks for the interest 👍

**Comment by RWOverdijk** [comment]
I found it 😄 But then I saw that you commented already and I felt silly. Thanks!
