### ISSUE TITLE
Use forwardRef

### ISSUE THREAD

**Issue by RWOverdijk** [akveo/react-native-ui-kitten#955]
## 🚀 Feature Proposal

It's not really a feature proposal, more of a change proposal. I made a SectionList and used the current List as an example. I noticed that it overrides/proxies some methods such as scrollToIndex and scrollToEnd.

My suggestion is to use forwardRef for these components to make them cleaner and more compatible (any API changes in RN won't need changes in those components). Here's how I did it for my SectionList:

```jsx
import React, { forwardRef } from 'react';
import { SectionList as NativeSectionList } from 'react-native';
import { styled } from '@ui-kitten/components';

const SectionList = forwardRef(({ style, themedStyle, ...derivedProps }, ref) => (
  <NativeSectionList
    {...derivedProps}
    ref={ref}
    style={[themedStyle, style]}
  />
));

SectionList.styledComponentName = 'SectionList'

export default styled(SectionList)
```

I've tested changing the mapping, checked if the methods are there (scrollToLocation) and verified everything works as I expect. The only difference is that it can now be made pretty using the styling system.

Thoughts?

**Comment by artyorsh** [comment]
You mean moving forwardRef to `styled`?

We still writing in class components because of the consistency across the code base. Moving to functions is nice but then it should be done in each component (IMO).
However, refactoring whole code base to forwardReft was on my plan. You may contribute with this if you want :) It is better opening PR directly to [v5 branch](https://github.com/akveo/react-native-ui-kitten/tree/v5) in this case

**Comment by RWOverdijk** [comment]
@artyorsh Oh cool :) But no, I meant using forwardRef in the [components like ListItem](https://github.com/akveo/react-native-ui-kitten/blob/master/src/components/ui/list/listItem.component.tsx).

It doesn't require functions, it also works with a HoC if that's your preference. I also prefer classes but... You know, they're pushing functions 😄

**Comment by artyorsh** [comment]
> using forwardRef in the components like ListItem

Then why ref can be required in list item?

**Comment by RWOverdijk** [comment]
I don't understand your question, sorry. But I do realise I made a mistake, I [meant the List component](https://github.com/akveo/react-native-ui-kitten/blob/master/src/components/ui/list/list.component.tsx#L75,L85)

These methods can be removed by using forwardRef. It's just an idea.

**Comment by artyorsh** [comment]
@RWOverdijk then yes. As mentioned above 
> refactoring whole code base to forwardRef was on my plan. You may contribute with this if you want :) It is better opening PR directly to v5 branch in this case

**Comment by kav** [comment]
Any further thoughts here? Happy to help functionalize things or take a stab at adding forwardRef to styled. Also for my use case (in input) I'm cool with just adding a prop and passing the input component ref rather than creating it in the construction. Happy to help PR any of that.

**Comment by RWOverdijk** [comment]
I'm not using ui-kitten anymore and this ref stuff should probably be a different, new issue. I'm closing this and disabling notifications.

**Comment by kav** [comment]
Ah yes my question was more for @artyorsh as I've got a similar forwardRef requirement for input. I can open a new issue or just a PR if someone with merge permission can give me a bit of direction on which approach they'd like to follow.
