### ISSUE TITLE
Web: dispatch and icon props set as attributes

### ISSUE THREAD

**Issue by RWOverdijk** [akveo/react-native-ui-kitten#958]
## 🐛 Bug Report

I'm getting the following in the browser (expo, react native web):

> Warning: React does not recognize the `marginHorizontal` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `marginhorizontal` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

All I'm doing is:

```jsx
<Button
  style={style}
  icon={iconStyle => <Icon name='plus' {...iconStyle} />}
  size='small'
  status='primary'
/>
```

as stated in the docs. However, the props get passed through all the way to the rendered component and that's not allowed for attributes.

I'm having the same issue with dispatch:

> Warning: Invalid value for prop `dispatch` on <div> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM. For details, see https://fb.me/react-attribute-behavior

Although I'm not sure where that's coming from to be honest.

## To Reproduce

- New expo project
- add ui kitten
- open in the browser
- Implement some components with UI kitten
- Check console

## Expected behavior

No warnings

## Link to runnable example or repository (highly encouraged)

I tried, but the sandbox seems broken (https://codesandbox.io/s/ui-kitten-welcome-x8q8z)

> (0 , _reactNative.requireNativeComponent) is not a function

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |     Master   |
| @ui-kitten/components   |      Master   |

**Comment by artyorsh** [comment]
> Warning: React does not recognize the marginHorizontal prop on a DOM element.

Pay attention on what you're passing to components and how it is applied. I can't give you more details on it.

> Invalid value for prop dispatch.

This property comes from `styled`, you may know this from the docs. Also, it is a known issue #669. Fixed in v5 which is currently on review.

**Comment by RWOverdijk** [comment]
@artyorsh I'm not doing that, your Icon component is. It takes a marginHorizontal but passes it on to the dom element. I'm pretty sure this is not something I'm doing wrong as they're props coming from bugs taken from your documentation 😄

I think this should be reopened. I don't mind submitting a fix with some assistance.

**Comment by artyorsh** [comment]
>  your Icon component is.
Then I don't understand why `marginHorizontal` is not recognizable? 🤔 Do you run it on web?
Eva Icons is nothing more than svg elements from [react-native-svg](https://github.com/react-native-community/react-native-svg) lib.

**Comment by RWOverdijk** [comment]
@artyorsh All I'm doing is what's in the description:

```jsx
<Button
  style={style}
  icon={iconStyle => <Icon name='plus' {...iconStyle} />}
  size='small'
  status='primary'
/>
```

Exactly like the docs say I should do it. Nothing more. The icon registry is set to eva icons: `<IconRegistry icons={EvaIconsPack} />`

**Comment by artyorsh** [comment]
@RWOverdijk seems to be web-specific behavior. Svg elements may accept a style property, meaning you may extract `marginHorizontal` and pass it into `style` prop. If web is your primary platform, I would suggest reading [this guide](https://akveo.github.io/react-native-ui-kitten/docs/guides/icon-packages#icon-packages), and configure your own Icon package, where you can manage style props more accurately.

**Comment by RWOverdijk** [comment]
All right. I could do that... But I think I'll instead look into fixing it for this library and make a PR.

**Comment by artyorsh** [comment]
Web is not our primary goal, but, definitely, will appreciate it a lot! 🚀

**Comment by RWOverdijk** [comment]
@artyorsh I get that, but it would be an excellent addition! I'll close this for now.

**Comment by mehmetor** [comment]
I faced the same problem and I just fixed it by replacing it as below:

`<Button
  style={style}
  icon={(props) => <Icon name='plus' {...props.iconStyle} />}
  size='small'
  status='primary'
/>`
