### ISSUE TITLE
background-primary-color theme variable no longer available

### ISSUE THREAD

**Issue by IgnacioGarciaGimenez** [akveo/react-native-ui-kitten#959]
I have just updated ui kitten and eva design to the latest version and it seems that everywhere i used theme[‘background-primary-color-#’]  now isnt styled anymore. Reviewing the docs, it seems that the variable doesnt exist anymore. Is this intended? Now what variable should i use if i want to mantain the component styled the way it was?

**Comment by artyorsh** [comment]
@IgnacioGarciaGimenez I'm not sure we ever had this variable. Can you clarify what color value it was?
For backgrounds, `background-basic-color-${LEVEL}` variables are used.
