### ISSUE TITLE
Docs still shows onPress rather than onChange for rkchoice

### ISSUE THREAD

**Issue by gmertk** [akveo/react-native-ui-kitten#96]
### Issue type
* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

https://akveo.github.io/react-native-ui-kitten/#/docs/ui-components/rkchoice says that rkchoice has onPress.

**Expected behavior:**

It should be onChange

**Comment by malashkevich** [comment]
Thanks for submitting the issue.
It's related to #89.
I just added milestone 3.1.0. That means that we will deliver it with next release.
