### ISSUE TITLE
How can I change the primary theme color?

### ISSUE THREAD

**Issue by jojigeorge009** [akveo/react-native-ui-kitten#961]
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |        |
| @ui-kitten/components   |         |

I have to change the bottom tab bar icon selection color, how can I achieve this? Please suggest.

**Comment by artyorsh** [comment]
https://akveo.github.io/react-native-ui-kitten/docs/guides/branding#branding
