### ISSUE TITLE
Overrides and mismatch with figma

### ISSUE THREAD

**Issue by RWOverdijk** [akveo/react-native-ui-kitten#962]
## 💬 Question

According to the Figma file for eva design the button group when using icon-only buttons shouldn't have _more_ horizontal spacing.

From the figma file:

![image](https://user-images.githubusercontent.com/781745/77313496-4699c200-6d04-11ea-8b66-035127b47656.png)

From the UI Kitten documentation:

![image](https://user-images.githubusercontent.com/781745/77313550-5d401900-6d04-11ea-904a-e9fa50a0e2ef.png)

As you can see the buttons from the docs have more horizontal spacing. So a couple of questions:

1. Which is wrong? The figma file or the component documentation?
2. How can I override values for existing components?
3. How can I add variants/appearances to existing component?
4. How can I use the white-background button group from figma with UI Kitten (it doesn't appear to be an appearance or state or anything)?

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   1.4.0     |
| @ui-kitten/components   |   4.4.1      |

**Comment by artyorsh** [comment]
1. The wrong is dev implementation
2. You may tweak a Button component with your implementation. It's more likely you may want to override `iconMarginHorizontal` in case there is no text. As far as I remember, in current realization the final spacing is `paddingHorizontal` + `textMarginHorizontal` (if there is text) + `iconMarginHorizontal` (if there is an icon). 
3. [Docs](https://akveo.github.io/react-native-ui-kitten/docs/design-system/customize-mapping#create-a-custom-mapping) and [example](https://akveo.github.io/react-native-ui-kitten/docs/components/styled-component/overview#styled) (pay attention on the comments above the code)
4. I suppose this is just an example in Figma. Buttons in `ButtonGroup` may have one of existing appearances / statuses. In your case, adding a custom one should solve this.

**Comment by RWOverdijk** [comment]
@artyorsh Thorough answers. I appreciate it!

**Comment by RWOverdijk** [comment]
@artyorsh Is this something that will be fixed?

**Comment by artyorsh** [comment]
@RWOverdijk  Yes, we'll sync this later. For now the team is focused on other products to be honest. Thanks for the interest

Still an issue for you?

**Comment by RWOverdijk** [comment]
@artyorsh It is. I wouldn't mind fixing it... If you could give me some pointers. I'm not just here to complain 😄

**Comment by artyorsh** [comment]
@RWOverdijk Well, I don't think there is a good approach to solve this with mapping (because you can't determine whether you have only an icon or icon and text there), but I would suggest creating your own component for this case. E.g `IconButton` where you use the same mappings as Button, but without `text` parameters. This will be a true way for current version

**Comment by RWOverdijk** [comment]
@artyorsh All right. I'll override the button anyway because it doesn't allow custom content.
