### ISSUE TITLE
ButtonGroup outline styling broken

### ISSUE THREAD

**Issue by RWOverdijk** [akveo/react-native-ui-kitten#963]
## 🐛 Bug Report

The ButtonGroup styling when using outline isn't working well on web and android. This is visible in the docs, too. The outline seems to fit to parent and leave a single pixel between the button and the border at the bottom.

Screenshot:

![image](https://user-images.githubusercontent.com/781745/77317027-b8750a00-6d0a-11ea-8b6a-ae2999596e0b.png)

(For the sake of screenshot size I cut it off, but the outline keeps going until the end of the parent)

You can see the same behaviour in the docs (The whitespace at the bottom):

![image](https://user-images.githubusercontent.com/781745/77317353-5668d480-6d0b-11ea-857e-e26588cc7f77.png)

## To Reproduce

```js
<Layout>
  <ButtonGroup size='small' appearance='outline' status='basic'>
    <Button style={{ paddingHorizontal: 0 }} icon={({ marginHorizontal, ...iconStyle}) => <Icon name='minus' {...iconStyle} />} onPress={() => {}} />
    <Button style={{ paddingHorizontal: 0 }} icon={({ marginHorizontal, ...iconStyle}) => <Icon name='plus' {...iconStyle} />} onPress={() => {}} />
  </ButtonGroup>
</Layout>
```

## Expected behavior

Border neatly clamed to the outline of the buttons

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   1.4.0     |
| @ui-kitten/components   |     4.4.1    |

**Comment by artyorsh** [comment]
Possibly similar to [this one](https://github.com/akveo/react-native-ui-kitten/issues/640). This means this is a platform-specific rendering issue.
Closing due to duplication.
