### ISSUE TITLE
Can't get parameters in styled component

### ISSUE THREAD

**Issue by RWOverdijk** [akveo/react-native-ui-kitten#964]
## 🐛 Bug Report

Disclaimer: it could be that my understanding of the system is wrong, but looking at the Button source code [here](https://github.com/akveo/react-native-ui-kitten/blob/master/src/components/ui/button/button.component.tsx#L201,L202) it looks like I should be able to get the values of parameters in my component using `themedStyle`.

However, `this.props.themedStyle` is an empty object. My mapping looks like this:

```js
export default {
  'meta': {
    'scope': 'all',
    'parameters': {
      'multiplierIconColor': {
        'type': 'string'
      },
    },
    'variantGroups': {},
    'states': {},
    'appearances': {
      'default': {
        'default': true
      }
    }
  },
  'appearances': {
    'default': {
      'mapping': {
        'multiplierIcon': 'color-basic-500',
      }
    }
  }
}
```

And my component as simple as this:

```jsx
import React, { Component } from 'react'
import { StyleSheet } from 'react-native'
import { boundMethod } from 'autobind-decorator'
import { Button, styled, Icon, Divider, Text, Layout, ButtonGroup } from '@ui-kitten/components'

class OrderItemComponent extends Component {
  static styledComponentName = 'OrderItem'

  render () {
    const { themedStyle } = this.props

    console.log(themedStyle)

    return null
  }
}

export const OrderItem = styled(OrderItemComponent)
```

I'd expect the `multiplierIconColor` to be in `themedStyle`.

**Comment by artyorsh** [comment]
According to the code, there is no `multiplierIconColor`
```
'appearances': {
    'default': {
      'mapping': {
        'multiplierIcon': 'color-basic-500',
      }
    }
  }
```

**Comment by RWOverdijk** [comment]
@artyorsh Yes, I broke that in copy/pasting to this issue 😄 but the `themedStyle` is empty, so changing the name isn't going to make a difference I'm afraid.

**Comment by RWOverdijk** [comment]
Nope... Nope. nu-uh.

... Okay yes, maybe I am a moron and made a mistake there, and you're right.

Leaving up the comment where I was wrong as punishment and closing the issue 😅

**Comment by artyorsh** [comment]
@RWOverdijk usually we forget to declare a variable within the `parameters` object. In this case, you will have a warning meaning `don't know what is it`. Be careful :)
