### ISSUE TITLE
Where are prebuilt screen ui code?

### ISSUE THREAD

**Issue by abhigk** [akveo/react-native-ui-kitten#966]
## 💬 Question

I have downloaded the Kitten-Tricks application from Google play store to test.
I love prebuilt layouts like auth, social and ecommerce in app. I want to use them. Where is the code for the prebuilt layout screen? 
I was unable it find on Github.

**Comment by artyorsh** [comment]
[In the docs on Kitten Tricks](https://github.com/akveo/kittenTricks/blob/master/DEV_DOCS.md#reusing-screens)
