### ISSUE TITLE
How to put Icon inside (or next to) Text?

### ISSUE THREAD

**Issue by andyfo** [akveo/react-native-ui-kitten#967]
Hello! 

Sorry if this is a really basic question...

How do I put `<Icon/>` inside or next to a `<Text></Text>`? I want to simply have a text label with an icon on the left side.

**Comment by artyorsh** [comment]
```js
<View style={{ flexDirection: 'row' }}>
  <Icon name='github' fill='black' />
  <Text>View it on Github!</Text>
</View>
```
