### ISSUE TITLE
Typescript: Type 'string[]' is not assignable to type 'string' ts(2322)

### ISSUE THREAD

**Issue by boraikizoglu** [akveo/react-native-ui-kitten#969]
## 🐛 Bug Report

I get a type error when I use some string as a child of Button.

    Type 'string[]' is not assignable to type 'string'.ts(2322)

![Screen Shot 2020-03-26 at 00 42 40](https://user-images.githubusercontent.com/17179767/77588600-3c8de400-6efb-11ea-9eca-7a0874b0fb08.png)

## To Reproduce

Create a button component with a string child.

`<Button style={styles.likeButton} icon={HeartIcon}> {'SOME TEXT'} </Button>`

## Expected behavior

No error

## Example Repository

https://github.com/boraikizoglu/button-ts-error-ui-kitten

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   1.4.0     |
| @ui-kitten/components   |   4.4.1      |
| typescript |    3.8.3      |

**Comment by artyorsh** [comment]
@boraikizoglu this is not a library issue. Adding spacings before `{` and after `}` equals to empty strings, so the error is correct - you pass 3 strings. I don't think with the code above you expect to render 3 strings instead of one, so I'm going to close this.

So instead of
```js
<Button> Text </Button>
```

Use

```js
<Button>Text</Button>
```
