### ISSUE TITLE
Possible bug in RkAvoidKeyboard

### ISSUE THREAD

**Issue by tkuanlun350** [akveo/react-native-ui-kitten#97]
Hi, 
I cannot get expected behavior with RkAvoidKeyboard and I think that in function _onKeyboardWillShow the offset should be calculated with endCoordinates instead of startCoordinates. (startCoordinates always gives me height = 0)

I'm using react-native 0.52.0

Thanks.

**Comment by artyorsh** [comment]
Hi @tkuanlun350,

Thanks for reporting. But RkAvoidKeyboard is going to be deprecated in future releases.

**Comment by numediaweb** [comment]
@artyorsh is there any replacement for RkAvoidKeyboard?
