### ISSUE TITLE
How to use differing values and value labels for select box?

### ISSUE THREAD

**Issue by JohannesKlauss** [akveo/react-native-ui-kitten#970]
## 💬 Question

Hello,
nice work with the framework, I really like it. Question though: How can I use a different value (different from the `text` prop) for select boxes?
Inside the typings I didn't find any clue to what that field would be?

So basic example, option 1 in a select box holds the value `en` but I want to display `English` to the user. How can I do that?

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      | 1.4.0       |
| @ui-kitten/components   |  4.4.1       |

**Comment by artyorsh** [comment]
@JohannesKlauss thanks for the meaningful question. However, I guess this is not possible within this version, but I thought about this in v5 #914

**Comment by JohannesKlauss** [comment]
Ah okay, thx for the fast reply. Any idea when the v5 will be released? The framework is super handy, but working with select boxes is very fiddly right now.

**Comment by artyorsh** [comment]
@JohannesKlauss we don't know yet. The truth is that the team is currently focused on other products and there is not enough time to make a good code review to avoid publishing "as is".
