### ISSUE TITLE
Input labelFontFamily on Custom Mapping

### ISSUE THREAD

**Issue by llcernicchiaro** [akveo/react-native-ui-kitten#972]
(First of all, sorry for my bad english)

## 🐛 Bug Report
I'm using custom mapping to change all project fonts. I'm using the font `TitilliumWeb`, and to change all components fonts I created 3 vars:
```js
"text-font-family": "TitilliumWeb-Regular",
"text-font-family-semibold": "TitilliumWeb-SemiBold",
"text-font-family-bold": "TitilliumWeb-Bold",
```
Then I passed this vars to `labelFontFamily` on `Input`, `DatePicker` and `Select` components, and changed as they use the `text-label-font-weight` var, I changed that to "normal". So it should use "TitilliumWeb-Bold" and normal weight. On DatePicker and Select it worked, but Input label keeps using "text-font-family".

I know I can deal this using "labelStyle" prop, but I wanted to keep everything on a pattern.

## To Reproduce
`Custom-mapping.json: `
```json
 "strict": {
        "text-font-family": "TitilliumWeb-Regular",
        "text-font-family-semibold": "TitilliumWeb-SemiBold",
        "text-font-family-bold": "TitilliumWeb-Bold",
         ...
        "text-label-font-size": 12,
        "text-label-line-height": 16,
        "text-label-font-weight": "normal",
  }
  ...
"Input": {
           ...
            "appearances": {
                "default": {
                    "mapping": {
                        ...
                        "labelFontWeight": "text-label-font-weight",
                        "labelLineHeight": "text-label-line-height",
                        "labelFontFamily": "text-font-family-bold",
                         ...
                    },
...
```

## Expected behavior
Like the `DatePicker `and `Select`, `Input `label to use the `labelFontFamily`.

## Link to runnable example or repository (highly encouraged)
Sorry for not providing it. 

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |  ^1.4.0  |
| @ui-kitten/components   |  ^4.4.0   |

## Environment information

```bash
System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz      
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD    
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548 
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
```

**Comment by artyorsh** [comment]
@llcernicchiaro [looks like a bug](https://github.com/akveo/react-native-ui-kitten/blob/master/src/components/ui/input/input.component.tsx#L240) in current implementation, meaning it can't be changed with mapping. Please use `labelStyle` as a temporary solution
