### ISSUE TITLE
useNativeDriver in Animated is required (RN v0.62)

### ISSUE THREAD

**Issue by sakhnyuk** [akveo/react-native-ui-kitten#974]
## 🐛 Bug Report

Animated require useNativeDriver option in react-native v0.62

## To Reproduce

Just trying to use BottomNavigation with animated Indicator (appearance="default")

![useNativeDriver_warn](https://user-images.githubusercontent.com/32235469/77894757-f096c280-729f-11ea-8c4a-387cc979af22.png)

![warn_logs](https://user-images.githubusercontent.com/32235469/77894874-1de37080-72a0-11ea-911c-6307e23709f7.png)

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |  v1.4.0      |
| @ui-kitten/components   |    v4.4.1     |

**Comment by abdulhamidOumer** [comment]
Getting the same issue on react native 0.62.0 as well. This also happens in select component and TsbView  as well. @sakhnyuk  did you find a way to resolve this yet ?

**Comment by artyorsh** [comment]
@abdulhamidOumer 
unfortunately, this is required by rn 0.62 meaning now, to fix UI Kitten warnings, you can deal with it only with YellowBox :(
We’ll include this in future release.

**Comment by SaveYourTime** [comment]
Same error occurs on NativeBase.
All instances of Animated.timing or Animated.spring need to add `useNativeDriver` with true or false.

https://stackoverflow.com/questions/61014661/animated-usenativedriver-was-not-specified-issue-of-reactnativebase-input
https://github.com/GeekyAnts/NativeBase/issues/3109

**Comment by luutruong** [comment]
I have make a PR this fix this: https://github.com/akveo/react-native-ui-kitten/pull/995

**Comment by SaveYourTime** [comment]
@artyorsh When will release a new version with this fixed?

**Comment by nashford77** [comment]
+1 - This is unbearable and crashes my app :) theres so many instances of it

**Comment by haystome** [comment]
+1

**Comment by hatim-developer** [comment]
@artyorsh when we can expect next release with this fix?

**Comment by artyorsh** [comment]
It's included in v5-alpha, you may upgrade to it right now. It will become stable during the next week ([track it here](#1055)). 0.62 support in v4 will be released as 4.4.2 right after v5, becoming the last supported 4.x.

**Comment by hatim-developer** [comment]
@artyorsh thanks, 
Sorry for delayed response we are using 4.x will be waiting for 4.4.2, once its released will upgrade it.
