### ISSUE TITLE
Does Range Calendar support language change? Or how can I change it manually?

### ISSUE THREAD

**Issue by mahiraltinkaya** [akveo/react-native-ui-kitten#975]
## 💬 Question
Hello friends;
I just started using React native and UI kitten. Language change is required for my application. Does the UI support the kitten? How can I change it manually? Thanks in advance.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   1.4.0    |
| @ui-kitten/components   |   4.4.1      |

**Comment by artyorsh** [comment]
It does. Check the [docs](https://akveo.github.io/react-native-ui-kitten/docs/components/calendar) for examples, `custom locale` section
