### ISSUE TITLE
Component: BottomNavigation onTabSelect() behaviour 

### ISSUE THREAD

**Issue by SandroDahl** [akveo/react-native-ui-kitten#977]
## 💬 Question

```
bottomNavigation.component.tsx:125

private onTabSelect = (index: number): void => {
    if (this.props.onSelect && this.props.selectedIndex !== index) {
      this.props.onSelect(index);
    }
};
```

Is there any reason why onSelect() is only allowed to call if the selected index is not equal to the current index. 

I would like to listen to this event, even if it is the same index, so I can refresh my tab content (scroll view to top). 

Or do I miss something and can solve it differently?
## UI Kitten

| Package      | Version |
| ----------- | ----------- |
| @ui-kitten/components   | v4.4.1 |

**Comment by artyorsh** [comment]
@SandroDahl my vision was we don't need to handle this. Most cases assume changes in navigation state with this event, so this is why this condition was added. Not sure, but as far as I remember adding `onPress` for BottomNavigationTab can solve your case. Pleas try it and comment if it does.

**Comment by SandroDahl** [comment]
An added `onPress` function on BottomNavigationTab is also not called. But I can use an added  `onPressIn` or `onPressOut` function as workaround for now.
