### ISSUE TITLE
BottomNavigation Prevents Proper Press handling

### ISSUE THREAD

**Issue by RipTheJacker** [akveo/react-native-ui-kitten#979]
## 🐛 Bug Report

In a typical app with tab navigation, a second press on the tab button will jump back to the root tab. This is prevented in the current implementation by this line:

https://github.com/akveo/react-native-ui-kitten/blob/master/src/components/ui/bottomNavigation/bottomNavigation.component.tsx#L126

## To Reproduce

Follow the BottomNavigation directions in the documentation.

## Expected behavior

I would expect the `onSelect` to still fire and allow me to control the state myself.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    1.4.0    |
| @ui-kitten/components   |    4.4.1     |

## Environment information

```bash
  System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
  Binaries:
    Node: 10.19.0 - ~/.nvm/versions/node/v10.19.0/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v10.19.0/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Xcode: 11.2/11B52 - /usr/bin/xcodebuild
  npmPackages:
    react: ~16.9.0 => 16.9.0 
    react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
```

**Comment by artyorsh** [comment]
Duplicates #977

**Comment by RipTheJacker** [comment]
Ah, that didn't come up in my search. My bad.
