### ISSUE TITLE
Issue in RkModalImg

### ISSUE THREAD

**Issue by harshrajk** [akveo/react-native-ui-kitten#98]
RkModalImg in full screen Modal is showing incorrectly if images are more than 10.
Example code : 
` {this.state.stpimages.map((item, index) => {`
                                    `return (`
                                       ` <View key={index}>`
                                            `<RkModalImg`
                                                `style={[styles.usergallery_bottom_cat_3]}`
                                                `modalImgStyle={{ flex: 1, resizeMode: 'contain', justifyContent: 'center'  ` `}}`
                                               ` renderHeader={this._renderHeader.bind(this)}`
                                              `  source={this.state.stpimages}`
                                               ` index={index} />`
                                       ` </View>`
                                 `  );`
                              `  })}`

Image falls back to pageNumber 10 if I'm opening any image i.e. higher in index than 10.
You can check kitten tricks app also as there's also same issue.

**Comment by artyorsh** [comment]
Hi @harshrajk,
Thx for submitting and sorry for late reply.
This issue is fixed and currently is available in master branch. Will be publicly available in next release.
