### ISSUE TITLE
Button textStyle fontFamily not working

### ISSUE THREAD

**Issue by ekalostz** [akveo/react-native-ui-kitten#981]
## 💬 Question

On app-mapping i set 
```
"strict": {
    "text-font-family": "sarabun-regular"
  },
```
every component change default font to sarabun-regular by itslef except Button
then I edit button style to
`<Button style={styles.numButton} textStyle={{ fontFamily: 'sarabun-regular' }}>1</Button>`

but font still the same
How can I fix this?

## UI Kitten and Eva version

| Package      | Version |
| @eva-design/eva      |    1.4    |
| @ui-kitten/components   |    4.4     |

**Comment by zzzzasd** [comment]
Were you able to fix this? I'm still facing this issue.

**Comment by emmaodia** [comment]
Hi @ekalostz @zzzzasd Did you folks find a fix? I'm currently experiencing the same issue.
You also referenced it here: #1192 @zzzzasd 

Any possible fix for this? @artyorsh

**Comment by eyalyoli** [comment]
You could just give it a custom component returning `Text`:
```javascript
const CustomText=(props) => (
    <Text
      {...props}
      style={[props?.style, { fontFamily: "OpenSans-SemiBold" }]}
    >
     Test
    </Text>
  );

...

<Button status="warning" size="tiny">
   {CustomText}
</Button>
```
