### ISSUE TITLE
Add animation props to TabView

### ISSUE THREAD

**Issue by marcoburrometo** [akveo/react-native-ui-kitten#982]
## 🚀 Feature Proposal

Add animation props to TabView component. Easing and durations should be enough.

## Motivation

Actually easing is linear, not very modern :)

**Comment by artyorsh** [comment]
Thanks for opening a proposal. Actually, this was already requested #837

**Comment by marcoburrometo** [comment]
> Thanks for opening a proposal. Actually, this was already requested #837

Ok thanks, i hope that this changes will be taken soon :)
