### ISSUE TITLE
Allowing Button's icon prop as string for icon name 

### ISSUE THREAD

**Issue by illuminist** [akveo/react-native-ui-kitten#983]
## 🚀 Feature Proposal

Allow putting icon name for a prop for Button, etc, instead of manually creating and putting icon render function each time.

## Motivation

Most of the time I find myself have to create a function just to render an icon for a button, while the function content doesn't have anything else inside and it's just the same every time where the difference only is icon name in each of the function. So allowing icon prop to be just a string will pretty much eliminate need for creating a function for each of icon.

## Example

Before:
```jsx
const PrinterIcon = style => <Icon name="printer" {...style} />

const CustomButton = () => {
  return <Button icon={PrinterIcon}>Custom Text</Button>
}
```

After:
```jsx
const CustomButton = () => {
  return <Button icon="printer">Custom Text</Button>
}
```

**Comment by artyorsh** [comment]
We can’t allow this since in this versions there are some workarounds used to display something different rather than icon. Also, there are different icon sets, not only Eva icons that blocks this.

I would suggest moving all functions to render an icon into separate file for easier usage
