### ISSUE TITLE
List component, swipe to delete

### ISSUE THREAD

**Issue by fireridlle** [akveo/react-native-ui-kitten#984]
#230  💬 Question

## UI Kitten and Eva version
I have List component inside TabView component. I would like to have feature swipe to delete and have tried to use react-native-swipeout. But when i do swap, application swap tab. Is there any solution i missed?

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    1.41    |
| @ui-kitten/components   |    4.4.1     |

**Comment by artyorsh** [comment]
You may configure PanResponder to prioritize the gestures sent to views

**Comment by stingers** [comment]
@fireridlle  hello! any solution?!!
