### ISSUE TITLE
Button: text - center, icon - right

### ISSUE THREAD

**Issue by 32penkin** [akveo/react-native-ui-kitten#986]
## 🚀 Feature Proposal

It would be great to add the ability to style the Button with Icon according the following layout:
  1. Text in the center.
  2. An Icon on the right side.

## Motivation

A fairly common use case

## Example
![image](https://user-images.githubusercontent.com/24478448/78242333-7f971b00-74ea-11ea-9eab-bbb6b7256399.png)

**Comment by artyorsh** [comment]
@32penkin I've got the solution with v5 :)
https://snack.expo.io/78Gxa7wzq
