### ISSUE TITLE
Autocomplete placement is off on android

### ISSUE THREAD

**Issue by ginold** [akveo/react-native-ui-kitten#990]
1) The list appears ok on the web but is off on the android emulator - it is placed in the middle of the text input and hides the input text completely on my real android device. In addition, it takes the whole width of the screen whereas it is in a container with padding (show fine on the web).

2) Is it possible to stylize the dropdown? (not the list items) Id like to add some shadow.

**Comment by artyorsh** [comment]
1. Duplicates #743. Please refer to the discussion of that issue for more details and possible solution
2. No. At least adding a shadow is not possible

Btw, shadows are under the internal discussion. Ideas of using libraries or a good ways to implement it to make it look same way across the platforms are appreciated 🙏
