### ISSUE TITLE
React Native UI Kitten custom theming not working on demo version

### ISSUE THREAD

**Issue by YioGoi** [akveo/react-native-ui-kitten#993]
We decided to use UI Kitten Demo [https://github.com/akveo/react-native-ui-kitten-demo-app](url) structure in our app. Before we tried custom theming and it has no problem. But in demo version, we are changing app-theme.json but lots of warnings came out and colors are not changing.

All documentation is clear, we've changed the json but no result. Is there an another way to override the theme colors without broken the dark/light usage in mapping and theming options.

"@eva-design/eva": "^1.4.0",
"@eva-design/material": "^1.4.0",
"@ui-kitten/components": "^4.4.0",
"@ui-kitten/date-fns": "^4.4.0",
 "@ui-kitten/eva-icons": "^4.4.0",
 "@ui-kitten/moment": "^4.4.0",

**Comment by artyorsh** [comment]
@YioGoi what do you mean with using https://github.com/akveo/react-native-ui-kitten-demo-app and how did you actually found it? :)

It’s outdated and relies on the really first library implementations. Take a look at [Kitten Tricks](https://github.com/akveo/kittentricks)

**Comment by YioGoi** [comment]
@artyorsh sorry for the wrong url.
We've also implemented [https://github.com/akveo/kittentricks](kitten tricks) but this problem still occures. 

`import { default as appTheme } from './app-theme.json';

export const appMappings = {
  eva: {
    mapping: eva.mapping,
    customMapping: customEva,
  },
  material: {
    mapping: material.mapping,
    customMapping: customMaterial,
  },
};

export const appThemes = {
  eva: {
    light: eva.light,
    dark: eva.dark,
    brand: {
      light: appTheme,
      dark: appTheme,
    },
  },
  material: {
    light: material.light,
    dark: material.dark,
    brand: {
      light: {},
      dark: {},
    },
  },
};`

We changed appTheme.json but lots of warnings occured and no colors set.

**Comment by artyorsh** [comment]
@YioGoi could you please post a repo with a demo project that runs your configuration? It's not clear for me to understand.
The theming functionality in Kitten Tricks is a bit complex, because it key feature of it to demonstrate was running both Eva and Material mappings, and this feature not described in the docs.

Officially, what you should do is [this](https://akveo.github.io/react-native-ui-kitten/docs/guides/branding#branding).
