### ISSUE TITLE
FastImage for Avatar

### ISSUE THREAD

**Issue by artyorsh** [akveo/react-native-ui-kitten#999]
## 🚀 Feature Proposal

It would be nice to use [react-native-fast-image](https://github.com/DylanVann/react-native-fast-image) for avatar component.

## Motivation

This library includes caching and other features needed in a real-world applications.

## Example

```js
import { Avatar } from '@ui-kitten/components';

const YourImage = () => (
  <Avatar
    size='giant'
    source={{ uri: 'https://unsplash.it/400/400?image=1' }}
  />
)
```

**Comment by lesmo** [comment]
Better yet... how about being able to use a custom `Image` component? `react-native-fast-image` is cool, but it could also be nice to have `react-native-fade-in-image` or `react-native-image-progress` - I personally wrap `react-native-fast-image` in lots of scenarios to do a Fade In effect or some other things.

I think something like the `Icon` component API would be cool.

**Comment by artyorsh** [comment]
@lesmo thanks for the details. Yes this makes more sense to extend this with a property, but it requires other libraries to be compatible at least with a props that the default Image accepts. I won't to create a middlewares to support each of them :D So what I think is use a `component` prop which accepts a class component, like it is implemented in lists, e.g with `ListHeaderComponent`. This way users can do all the specific library things in a separate component.

**Comment by lesmo** [comment]
That's even better. You could even use a `<Video>` component... 😜

**Comment by kockok** [comment]
What's the exact implementation for fastimage?

I couldn't get it to work by filling the component prop with a fastimage element.

![Screen Shot 2021-04-05 at 6 03 33 PM](https://user-images.githubusercontent.com/232541/113562816-5b0fda80-9639-11eb-85d0-014f43419ede.png)

**Comment by artyorsh** [comment]
@kockok you should use `ImageComponent` and not `component`
